### ISSUE TITLE
fields.Date deserialize resulting in datetime

### ISSUE THREAD

**Issue by Ondkloss** [marshmallow-code/marshmallow#1001]
Today I moved from 3.0.0b16 to 3.0.0b17 since I wanted the `format` option for `fields.Date` ([this commit](https://github.com/marshmallow-code/marshmallow/commit/8efb79a8ed45906853c53335b0ca1b36e8528208)). However I'm getting some unexpected results:

    >>> import marshmallow
    >>> print(marshmallow.__version__)
    3.0.0b17
    >>> d = marshmallow.fields.Date(format='%Y-%m-%d')
    >>> result = d.deserialize('2018-01-01')
    >>> print(type(result), result)
    <class 'datetime.datetime'> 2018-01-01 00:00:00

The functionality is greatly desired, however I wasn't expected that using a `format` for a `fields.Date` resulted in a `datetime.datetime`. Is this really intended?

(This is my first issue here. Provide constructive feedback if I should somehow improve my format)

**Comment by lafrech** [comment]
Thanks for reporting.

This bug should be fixed in https://github.com/marshmallow-code/marshmallow/pull/1002.

**Comment by sloria** [comment]
@Ondkloss The fix has been released in 3.0.0b18. Thanks for reporting the bug!
