### ISSUE TITLE
Marshmallow List invalidates an array from GET Request

### ISSUE THREAD

**Issue by edaddou** [marshmallow-code/marshmallow#1004]
I am working on validating a `GET` request that passed an array in the `params`. In marshmallow Schema I have `post_ids = fields.List(fields.Integer)` But, it raises a bad request

```
{
    "error": "Bad Request",
    "error_description": {
        "location_ids": [
            "Not a valid list."
        ]
    }
}
```

I tried to investigate via other tools, and when I do something like  return `isinstance(request.args["post_ids"], list)` I get `True` same when I check `type(request.args["post_ids"]) `I get` <class, list>`

**UPDATE**
After investigating Marshmallow Code, the `_deserialize` function is using a custom function in marshmallow `utils.is_collection` where it checks if the var is `Iterable` and not `hasattr(obj, 'strip')`

Should I create a custom Field for `List` or override `is_iterable_but_not_string` by checking if the string can be cast to List
So something like `(isinstance(obj, collections.Iterable) and isinstance(obj,list)) or is_generator(obj)`

**Comment by sloria** [comment]
@edaddou If I'm understanding correctly, `request.args["post_ids"]` is a custom list subclass that implements `strip` and therefore `is_collection` is returning `False`.

If that's the case, then yes, you could create a custom `List` field that overrides `_deserialize` the type check before deserializing.

Alternatively, you could pre-process `request.args["post_ids"]` so that it is passed to marshmallow as a `list`. Where you do this will depend on what object you're deserializing.

**Comment by sloria** [comment]
Closing for now. Feel free to re-open if you're still running into issues.

**Comment by ghost** [comment]
I encountered a similar issue. The request URL was `http://localhost/eat?food=pizza&food=burger`, and the `request.args` in my Flask app looked like this:

```
ImmutableMultiDict([('food', 'pizza'), ('food', 'burger')])
```

My schema was defined as:

```python
class FoodRequestSchema(Schema):
    food = fields.List(fields.Str(validate=validate.Regexp("^\w[\w_-]*$")), required=True)
```

I was able to apply the schema to the request using:

```
FoodRequestSchema().load(request.args.to_dict(False))
```

If your payload contains nested lists that you need to preserve, use `request.args.to_dict(False)`. For more details, see the Werkzeug documentation: https://werkzeug.palletsprojects.com/en/stable/datastructures/#werkzeug.datastructures.MultiDict.to_dict

I hope this helps anyone else facing this issue!
