### ISSUE TITLE
Attribute Kwarg Error

### ISSUE THREAD

**Issue by namccart** [marshmallow-code/marshmallow#1005]
```
class TestSchema(Schema):
    title = fields.Str()
    title_sub = fields.Str(attribute='title')
```
If I try to instantiate this class in 3.0.0b17 and above, I get `ValueError: Duplicate attributes: set(['title'])`.  I've inherited some Marshmallow test code using similar attributes.  Seems awfully like a bug to me given the documentation for the attribute kwarg for Field, but I'm not sure.

**Comment by lafrech** [comment]
This is intended:

https://marshmallow.readthedocs.io/en/3.0/upgrading.html#attribute-or-data-key-collision-triggers-an-exception
https://github.com/marshmallow-code/marshmallow/pull/992

**Comment by namccart** [comment]
Oh, nice.  Thank you.

**Comment by sloria** [comment]
Yes, the error is intentional. Perhaps we need to improve the error message to make this more clear.
