### ISSUE TITLE
Question: best way on how to organize CRUD schema objects with marshmallow

### ISSUE THREAD

**Issue by nikoladsp** [marshmallow-code/marshmallow#1028]
Hi,
one question on what is the best practice to organize marshmallow schema objects for CRUD methods. Say, I have a simple class in SqlAlchemy:
```python
class Order(Base):
    __tablename__ = 'Orders'
    
    id = Column(Integer, primary_key=True)
    name = Column(String)
    quantity = Column(Integer)
    placed_at = Column(DateTime)
```
Now, when creating new Order, I need schema that has **name** field only (and eventually **placed_at** automatically set to ```datetime.utcnow()```). When updating, my endpoint for example should allow to change only **name** and **quantity** fields. On reading (and delete) however I want all fields: **id**, **name**, **quantity** and **placed_at** to be serialized (dumped).

What is the best/recommended way to do this: shall I crate one _base_ class, containing the smallest set of attributes and then extend it (subclass it) and add additional fields? Or, shall I simply create different classes with no common class. I prefer using the base class approach whenever possible, but I am not sure will this complicate managing of _dump_only_ and _exclude_fields_ in sub-classes and make code hard to maintain?

Thank you in advance

**Comment by lafrech** [comment]
Quick and partial answer. If you're looking for a DRY approach, you could be interested by https://github.com/marshmallow-code/marshmallow-sqlalchemy.

**Comment by nikoladsp** [comment]
Thanks, I use it already to define schemes automatically from the model, but same question applies regardless. In project I am working on, there are really many SA model objects and I jut want to make proper decision in order to maintain things a bit easier later on, since currently its a bit mess and I dont want to make it worse.

Best regards

**Comment by scottwernervt** [comment]
You can filter schema attributes when loading and dumping using the `only`, `exclude`, and `partial` arguments.

- https://marshmallow.readthedocs.io/en/3.0/quickstart.html#filtering-output
- https://marshmallow.readthedocs.io/en/3.0/quickstart.html#partial-loading
- https://marshmallow.readthedocs.io/en/3.0/api_reference.html#schema

```python
from datetime import datetime

from marshmallow import Schema
from marshmallow.fields import DateTime, Integer, String

class Order(Schema):
    id = Integer(dump_only=True)
    name = String(required=True)
    quantity = Integer()
    # Use sqla default attribute to set timestamp
    placed_at = DateTime(dump_only=True)


order_schema = Order()
create_order_schema = Order(only=('name',))
update_update_schema = Order(only=('name', 'quantity'))

# post
create_order_schema.load({'name': 'Candy', 'quantity': 5})
# {'name': 'Candy'}

# get/delete: dump model
order_schema.dump({'id': 1, 'name': 'candy', 'quantity': 5, 'placed_at': datetime.utcnow()})
# {'id': 1, 'placed_at': '2018-10-29T14:48:37.969904+00:00', 'quantity': 5, 'name': 'candy'}

# patch: only name and quantity are allowed
update_update_schema.load({'quantity': 10}, partial=True)
# {'quantity': 10}
```

**Comment by nikoladsp** [comment]
Thanks, this is exactly what I wanted to do, but needed an advice/second opinion. Dilemma is shall I maybe use one base 'API parameter' class that can be attached to e.g. **create_order_schema** or **update_order_schema**; so it can be used as single parameter in each API endpoint, something like:
```python
class ApiParam(object):
    def __init__(schema, json_data):
        schema.dump(json_data)
        self.validate()

    def validate():
        pass

@blueprint.route('/orders', methods=['POST'])
def create_order():
    service = OrderService()
    service.create(ApiParam(create_order_schema, request.get_json(silent=True)))
```

Does this makes sense?

Thank you kindly

**Comment by scottwernervt** [comment]
It is a preference if you want to simplify your endpoints with wrapped classes like your `ApiParam`. I have done this in the past but always end up struggling to debug it as my business logic gets complicated. I now prefer to make my endpoints verbose so I can easily see the data flow from start to finish.

```python
@blueprint.route('/orders', methods=['POST'])
@roles(('customer', 'staff'))
def create_order():
    input_data = request.get_json()
    
    if current_user.is_staff:  # staff can create a new order on behalf of the customer
        data = order_schema.load(input_data)
    else:  # customer directly ordering
        data = create_order_schema.load(input_data)
   
    # service class has common CRUD operations on sqlalchemy models
    order_record = order_service.create(data)

    result = order_schema.dump(order_record)
    return result, HTTPStatus.CREATED, {}
```

**Comment by nikoladsp** [comment]
Yes, I am thinking the same, but trouble is that service code should be used both in endpoints and console application doing some administrative stuff directly  (without usage of REST), so it seems I will have to keep validation inside service itself in order not to duplicate it. Second option is to use schema instance and perform validation inside service, but somehow this look more as the job for some 'parameter' class that will be instantiated within the service and raise an exception in **\_\_init\_\_** automatically, or via separate **validate()** method that should be called upon creation of 'param' object
