### ISSUE TITLE
Cannot have multiple fields use the same attribute

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#1038]
#992 prevents two fields from using the same `attribute`. The intent was prevent user error.

However, there might be a legitimate use case where a user might want to serialize an attribute in two different ways. This was brought to my attention in https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/121 .

To illustrate: say I have SchoolSchema which serializes both student_ids *and* nested representations of students.

```python
from marshmallow import Schema, fields

class StudentSchema(Schema):
    id = fields.Int()

class SchoolSchema(Schema):
    student_ids = fields.Pluck(
        StudentSchema,
        'id',
        many=True,
        attribute='students',
    )
    students = fields.List(fields.Nested(StudentSchema))

schema = SchoolSchema()
# ValueError: The attribute argument for one or more fields collides with another field's name or attribute argument. Check the following field names and attribute arguments: ['students']
```

Is this a use case we want to support?

cc @lafrech

**Comment by lafrech** [comment]
It works if `dump_only` is specified.

```py
class SchoolSchema(Schema):
    student_ids = fields.Pluck(
        StudentSchema,
        'id',
        many=True,
        attribute='students',
        dump_only=True
    )
    students = fields.List(fields.Nested(StudentSchema))
```

At the time, we thought this was an acceptable compromise. If not, we may revert #992.

**Comment by sloria** [comment]
Yeah, and I still think it's an acceptable compromise. I just hadn't seen anyone try to do the above until I saw https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/121 , which made me think it *could* be a legit use case.

**Comment by sloria** [comment]
Closing for now. Seems that the use case mentioned in https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/121 was not broken. We can always reopen if this pops up again.

**Comment by song-william** [comment]
Hey @sloria , I actually have nested fields that use the same attribute names, and they are not  `dump_only=True` or `load_only=True`. My current work around is just to use `data_key` for loading and `post_dump` to manually change the field to the conflicting attribute name.

**Comment by song-william** [comment]
@sloria, I have a use case where nested schemas share an attribute field and the field is not `dump_only` or `load_only`. To work around this, I am just giving slightly different attribute names, but this is not ideal.  Perhaps it is worth reconsidering multiple fields on the same attribute?
