### ISSUE TITLE
How to deal with a field with both required and missing?

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow#1040]
@taion (https://github.com/marshmallow-code/marshmallow/pull/756#issuecomment-436054072):
> [Since #756], missing now has no effect if required is specified, as the required check is made before the missing logic is applied.
>
> I think it would make more sense to restore the old behavior – as with missing implicitly overriding allow_none, it should also override required.

This is debatable.

Another option could be to raise an Exception.

If we keep current behaviour, we should at least document it.

**Comment by taion** [comment]
It is a bit of a silly edge case given that this does involve specifying two logically incompatible non-default options.

Raising an exception is a little tricky, though – currently callables are supported for `missing`, so one could do something like `missing=lambda: marshmallow.missing`.

Then again, anybody who does that deserves what they get. I'm on board with raising an programmer-facing exception.
