### ISSUE TITLE
Question: Is there an approximate Marshmallow 3.0 Release Date?

### ISSUE THREAD

**Issue by kenjiwongAPV** [marshmallow-code/marshmallow#1041]
I just wanted to start off with that this project has been EXTREMELY helpful to me and appreciate all the support that the community has given. A special thanks to everyone that has contributed to it. 

There are some really nice features in the pre-release version (v3) that I've been using. Is there an approximate date of release e.g end of 2018? Any insight would be appreciated and again thank you.

**Comment by lafrech** [comment]
https://opencollective.com/marshmallow/updates/how-your-donations-are-used (2018-11-03)

> A stable release of marshmallow 3 is on the horizon! marshmallow 3 is already a massive improvement on version 2, and we're focused on cutting the final release as soon as we can. I estimate that we'll have the a release candidate within the next month. You can follow our progress here: https://github.com/marshmallow-code/marshmallow/milestones .

**Comment by deckar01** [comment]
Check out https://github.com/marshmallow-code/marshmallow/issues/928 for a recent discussion on the topic. The scope of the 3.0 milestone narrowed significantly after that discussion. The remaining issues are mostly edge cases, a little tech debt, and a couple enhancements.

https://github.com/marshmallow-code/marshmallow/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0

I encourage you to participate in the discussions on these issues. Any contribution would be greatly appreciated.
