### ISSUE TITLE
Combine  schema definition with object definition

### ISSUE THREAD

**Issue by rainmanwy** [marshmallow-code/marshmallow#1043]
This is a great library, i like it:)

I have tried to find a python library to convert json to object and vise versa(like gson, fastjson in java). And i have tried this library and want to use it.

One question is i have to define schema class and object class. For example:
class User:
    pass

class UserSchema(Schema):
    pass

I have tried to solve it myself, and below is my implementation:

```py
class _MetaClass(SchemaMeta):

    def __call__(self, **kwargs):
        inst = super(_MetaClass, self).__call__()
        for attr in inst.declared_fields:
            if hasattr(inst.declared_fields[attr], 'many'):
                setattr(inst, attr, [])
            else:
                setattr(inst, attr, None)
        for k, v in kwargs.items():
            if k in inst.declared_fields:
                setattr(inst, k, v)
        return inst


class BaseClass(Schema, metaclass=_MetaClass):

    @post_load
    def create(self, data):
        return self.__class__(**data)

    def __repr__(self):
        return str(self.to_json())

    def to_json(self):
        out = {}
        for key in self.declared_fields:
            v = getattr(self, key)
            if isinstance(v, BaseClass):
                out[key] = str(v)
            elif isinstance(v, (int, float)) or v is None:
                out[key] = v
            else:
                out[key] = str(v)
        return out
```

I am not sure whether there is common solution for that. And with my implementation, i met a problem when use Nest with many

```py
class Student(BaseClass):
    name = fields.String()
    birthday = fields.DateTime()
    age = fields.Integer()
    money = fields.Decimal()


class Class(BaseClass):
    class_name = fields.String()
    students = fields.List(fields.Nested(Student))  # type: List[Student]
    # students = fields.Nested(Student, many=True)  # type: List[Student]
```

when using "students = fields.Nested(Student, many=True)", lib will report schema verify failed. I am not sure whether i made some mistakes.

Again, thank you to develop this greate library.

**Comment by SVilgelm** [comment]
Hi @rainmanwy, take a look at my wrapper for Marshmallow: https://github.com/SVilgelm/marshmallow-objects

**Comment by deckar01** [comment]
The documented strategy is to add a `post_load` hook to each schema that constructs the object. This is very flexible and doesn't require that much boilerplate.

https://marshmallow.readthedocs.io/en/3.0/quickstart.html#deserializing-to-objects

---

I think the main issue in your example is that `self.__class__` is a schema, not a data model.

```py
from marshmallow import Schema, fields, post_load


class GenericModel():
    def __init__(self, schema, **kwargs):
        self.__schema__ = schema
        for attr in schema.declared_fields:
            if hasattr(schema.declared_fields[attr], 'many'):
                setattr(self, attr, [])
            else:
                setattr(self, attr, None)
        for k, v in kwargs.items():
            if k in schema.declared_fields:
                setattr(self, k, v)
    
    def __repr__(self):
        return str(self.to_json())
    
    def to_json(self):
        out = {}
        for key in self.__schema__.declared_fields:
            v = getattr(self, key)
            if isinstance(v, GenericModel):
                out[key] = str(v)
            elif isinstance(v, (int, float)) or v is None:
                out[key] = v
            else:
                out[key] = str(v)
        return out

class BaseSchema(Schema):
    @post_load
    def create_object(self, data):
        return GenericModel(self, **data)

class Student(BaseSchema):
    name = fields.String()


class Class(BaseSchema):
    class_name = fields.String()
    students = fields.Nested(Student, many=True)  # type: List[Student]


data = dict(class_name='Science', students=[dict(name='Jody')])
result = Class().load(data).data

print result
```

**Comment by rainmanwy** [comment]
@SVilgelm , thank you.
I have tried your lib, so it is not compatible with v3 right, it raise exception in my env.
I have checked your code, i think your solution is what i expected.

marshmallow==3.0.0b20
marshmallow-objects==1.0.17

@deckar01 , thank you. Now  " students = fields.Nested(Student, many=True)" works.
yes, i know that "post_load" is flexible. 
What i want is a python lib which similiar with gson and fastjson in java.
I do not want to define schema and data model in separate class( for me, fields definition and init are duplicate code )

for the error i met, after change the code in "__call__" method, it works.

`
class _MetaClass(SchemaMeta):

    def __call__(self, *args, **kwargs):
        keys = ['only', 'exclude', 'many', 'context', 'load_only', 'dump_only', 'partial', 'unknown']
        if len(kwargs)>0 and list(kwargs.keys())[0] in keys:
            inst = super(_MetaClass, self).__call__(*args, **kwargs)
        else:
            inst = super(_MetaClass, self).__call__()

        for attr in inst.declared_fields:
            if hasattr(inst.declared_fields[attr], 'many'):
                setattr(inst, attr, [])
            else:
                setattr(inst, attr, None)
        for k, v in kwargs.items():
            if k in inst.declared_fields:
                setattr(inst, k, v)
        return inst
`
and @deckar01 , your solution looks cleaner than mine:)
