### ISSUE TITLE
`render_module` not used in nested Schemas when dumps used on containing Schema

### ISSUE THREAD

**Issue by mlittlej** [marshmallow-code/marshmallow#1044]
Example code:
```
class RenderUpper(object):
    @staticmethod
    def dumps(val):
        return str(val).upper()

class AddrJSONSchema(Schema):
    address = fields.String()

    class Meta:
        render_module = RenderUpper

class UserJSONSchema(Schema):
    name = fields.String()
    various_data = fields.Nested(AddrJSONSchema)
various_data = {'address': '1600 Pennsylvania Ave, Washington, DC 20006'}

user = User('Joe', various_data=various_data)
s = UserJSONSchema()
result = s.dumps(user)
```
Expectation:
```
'{"various_data": {"address": "1600 PENNSYLVANIA AVE, WASHINGTON, DC 20006"}, "name": "Joe"}'
```
Disappointing reality:
```
'{"various_data": {"address": "1600 Pennsylvania Ave, Washington, DC 20006"}, "name": "Joe"}'
```

Question is whether this is expected behaviour or not? Personally, not.

As an end-user, my expectation was that the `render_module` setting of my Nested class would be honoured and when I used `dumps` on the parent; thinking that each Nested class would be rendered in the way I've specified.

Alas, not to be.

I'm having a look at the code responsible, trying to get a grip on how the code flows, where might be a good place to start introducing the changes.

Any interest on this being worked through? Or does someone have something for this already?

---

Edit: Fix the expected/actual results. They weren't properly formatted, and didn't reflect what I actually wanted.

**Comment by mlittlej** [comment]
Actually, I can achieve the effect I was looking for using the `pre_load` and `post_dump` decorators respectively, which makes this a bit moot.

Feel free to close, but it may be something somebody else might want to look into.

**Comment by lafrech** [comment]
`render_module` can only be passed as `Meta` and not as a Schema init parameter. I guess it was not meant to be _that_ dynamic. I'd suggest to let all schemas inherit from a base schema specifying the custom render module:

```py
class CustomBaseSchema(Schema):
    class Meta:
        render_module = RenderUpper

class AddrJSONSchema(CustomBaseSchema):
    class Meta(CustomBseSchema.Meta):  # Don't forget to inherit the base schema Meta class
        only = ...                     # when adding Meta attributes
```

There may be use cases for dynamic setting of `render_module`. If we want to support those, it would be consistent to not only propagate it but also allowing it to be set at Schema init.
