### ISSUE TITLE
Problem assigning validates_schema to dynamic created model

### ISSUE THREAD

**Issue by diegopedroza** [marshmallow-code/marshmallow#1047]
I'm creating a model in a dynamic way like this:

```py
schema = type(
	'ModelSchema',
	(UserSchema,),
	dict(Meta=type('Meta', tuple(), {
			 'strict': True,
			 'model': model,
			 'fields': [field for field in self.api_model_spec]
		 })
	))

class UserSchema(ModelSchema):
    @validates_schema
    def validate_schema(self, data):
        if len(data['name']) >= 10:
            raise ValidationError('the name field must have only 10 characters', ['name'])
        if 'email' not in data:
            raise ValidationError('the email field is required', ['email'])
```

Problem is that validates_schema function is not dispatched, never works

**Comment by GLRenderer** [comment]
I'm quite new at marshmallow and I've been looking at documentation on using the fields.Dict object, not too many examples on its usage out there.  I checked the issue #483 where there's a proposal to make use nested objects in dictionaries. I think this example complements the issue introduced by Diego, I was about to open an issue, but this fits with the exact problem I'm finding in marshmallow myself.


    from marshmallow import Schema, fields, post_load, pprint

    class UserSchema(Schema):
        name = fields.String()
        email = fields.Email()
        friends = fields.List(fields.String())

    class AddressBookSchema(Schema):
        contacts =fields.Dict(keys=fields.String(),values=fields.Nested(UserSchema))

    @post_load
    def trans_friends(self, item):
        for name in item['contacts']:
            item['contacts'][name]['friends'] = [item['contacts'][n] for n in item['contacts'][name]['friends']]


    data = """
        {
        "contacts": { 
            "Steve": {
                "name": "Steve",
                "email": "steve@example.com",
                "friends": ["Mike"]
           },
            "Mike": {
                "name": "Mike",
                "email": "mike@example.com",
                "friends": []
            }
      }
   }
   """

    deserialized_data = AddressBookSchema().loads(data)
    pprint(deserialized_data)

It returns a Nonetype and never marshalls the dynamic object.

**Comment by deckar01** [comment]
@GLRenderer That doesn't sound related. Would you mind starting a new issue?

**Comment by deckar01** [comment]
I made the minimal changes necessary to get that example running and it seems to be working fine on version 2.16.3 and 3.0.0b16 for me.

```py
from marshmallow import Schema, validates_schema, ValidationError


ModelSchema = type(
    'ModelSchema',
    (Schema,),
    dict(Meta=type('Meta', tuple(), {
             'strict': True,
             'fields': ['name', 'email']
         })
    ))

class UserSchema(ModelSchema):
    @validates_schema
    def validate_schema(self, data):
        if len(data['name']) >= 10:
            raise ValidationError('the name field must have only 10 characters', ['name'])
        if 'email' not in data:
            raise ValidationError('the email field is required', ['email'])

UserSchema().load({'name': 'teefkjqhwekfwekfwkest', 'email': 'test@test.com'})
```

**Comment by diegopedroza** [comment]
For me is not working, and actually I just notice if I use a simple example validates schema function is never dispatched also. I'm using:
Python 3.6.7
flask-restplus==0.11.0
marshmallow==3.0.0b18
marshmallow-mongoengine==0.9.1

**Comment by deckar01** [comment]
Your original code doesn't work for you, or my example doesn't?

The example I posted above proves to me that the `@validates_schema` decorator is working correctly with a dynamic schema using just `marshmallow`. This does not appear to be a marshmallow issue.

It looks like you are dynamically extending the `ModelSchema` from `marshmallow-mongoengine` and that is what is breaking. I would recommend opening an issue on https://github.com/touilleMan/marshmallow-mongoengine.

**Comment by diegopedroza** [comment]
Actually the problem was `@validates_schema` decorator so I think is more for marshmallow, but somehow changing some stuff in my code now is working.
Thanks so much for your help
