### ISSUE TITLE
Pre/Post processors  returning None don't pass models to Methods

### ISSUE THREAD

**Issue by dutchmo** [marshmallow-code/marshmallow#1055]
In b12, a change was made so that pre/post processors returning "None" prevent data passing to Methods/Functions. 

For example:

```
    @marshmallow.pre_dump
    def my_pre_dump(self, user: User):
        print("running predump")
```

means that the role_to_str method below won't be passed the model.

`roles = marshmallow.fields.Method('role_to_str')`

But this isn't obvious, so should probably either be documented, or throw a warning/error if the pre/post processors return None.

**Comment by deckar01** [comment]
https://github.com/marshmallow-code/marshmallow/blob/dev/docs/upgrading.rst#prepost-processors-must-return-modified-data

I think this is only an issue when migrating from v2 to v3 and it is documented. It should either break or cause the program's output to be noticeably wrong.
