### ISSUE TITLE
Unintuitive validation order in Field.deserialize

### ISSUE THREAD

**Issue by DrPyser** [marshmallow-code/marshmallow#1056]
Hi.

The order of validation in `Field.deserialize` doesn't really make sense to me.

I would think the intention of specifying validators on a field is to validate the "input", that is, the serialized data we're loading from/deserializing. Instead, in [`Field.deserialize`](https://github.com/marshmallow-code/marshmallow/blob/03fbd92870018260cda71a3d8a476ffc40971801/marshmallow/fields.py#L283), `self._validate` is applied not on the input value, but on the output of the field's `_deserialize` method.
It seems to me, in most cases, the schema/field author knows and control the deserialization output. What is unknown and needs to be validated is the external data which will be passed to the field/schema. 

Validating the deserialization output of the field is equivalent to an `assert`, and is not the expected purpose of field validators IMHO.

Currently, this behavior prevents me from using field validators to validate deserialization input in my custom field implementation, since deserialization output is different from expected input.

I propose simply moving the call to `self._validate` (currently line 283) one line above the call to `self._deserialize`, and call it on `value`(the raw `deserialize` input) instead. 

Thanks!

**Comment by lafrech** [comment]
Discussed in https://github.com/marshmallow-code/marshmallow/issues/399.

**Comment by DrPyser** [comment]
Does anyone else have an opinion on this? 

To resume my arguments:

* Validating deserialization result is equivalent to asserting expected properties of the deserialization process output, instead of guarding the deserialization boundary(i.e. component/layer where deserialization occurs) against invalid input data. Both are valid use cases, but in my opinion, the second is the most common and intuitive use of validators. The former can be accomplished using `postload` methods, directly in the field `_deserialize` method implementation, or through a new extension to the `Field` api for "output validators".  
* Currently, the field validator api doesn't support validating deserialization input("raw" data). This is a significant missing feature, I think. This can be accomplished using `preload` methods, but again, I think(and intuitively expect) this should be the primary use case of validators.

**Comment by deckar01** [comment]
I don't think the proposal of moving `self._validate` before deserialization is feasible. The current behavior of validating deserialized data is convenient and it is a common use case. Changing it would break validators for fields that manipulate the type of the input value, which is all too common.

Can you provide an example of why a field validator would need access to raw data? What information is in the raw data that you need? I can only imagine it is information about the type. If this is the case, then you are not performing validation on the field value, you are performing validation on the field type. That is the field class's job and the behavior can be changed by creating a custom field.

**Comment by DrPyser** [comment]
> Changing it would break validators for fields that manipulate the type of the input value, which all too common

Yeah, I guess this would be a breaking change, since current usages of validators for fields which change the type of the data have to work on the output value(whether that was desired or not). I proposed adding a new type of validators for the use case of validating the output value, but if you really don't want to introduce a breaking change in this case, I guess the current validation api could remain unchanged, with an extension to cover my use case(e.g. `validate_input`). However, as I explained, I believe changing the behavior of the current api would make more sense, making it more intuitive.

> Can you provide an example of why a field validator would need access to raw data? What information is in the raw data that you need? I can only imagine it is information about the type.

Why would you imagine that?   
Validators don't validate the type of the value, but other properties of the value itself. For example, `fields.validate.OneOf(choices=[1,2,3])` checks that the value is one of the specified choices. In this case, the input could be expected to be an int, but its value constrained to either 1,2 or 3.
 
My main use case was to implement an `Enum` custom field, which handles serialization/deserialization and validation of a enum type. I intuitively thought of making use of the `fields.validate.OneOf` validator to check that the input corresponds to a valid representation of the enumeration type associated with the field instance(given as an init parameter). The deserialization output of such a field would be known to be a valid instance of the enum type; it is the input value that has to be validated, constrained to a set of values, given that the serialized representation of an enum type is usually expressed as a set of string or integer values.

In the issue linked by @lafrech , the use case mentioned is to validate a string input which is expected to be a valid date string in the `iso` format. The field then converts the input into a datetime, but the validation needs to occur before the conversion is attempted by the field, otherwise the field itself will raise a `ValidationError`, or produce a bad `datetime` output that cannot be validated easily. 

In the end, for my use case, I implemented the validation directly into the `_deserialize` implementation. I see this as a DRY violation, as the validation logic is already expressed by the `OneOf` validator, and I now have to make the `_deserialize` implementation more complicated(admittedly only marginally), when the job could have been done simply by adding the right validator in the `__init__`, had the validation behavior been as I expected.

**Comment by DrPyser** [comment]
Also, could you present me examples of use cases that really require the current behavior? In my intuition, a validation that can be done on the deserialized value can be done equivalently on the input value. 

The output domain is necessarily smaller or equivalent to the input domain. Deserialization can only convert to a different representation, constrain input values to a smaller subset, or both. At least, for "pure function" deserializers which do not rely on external or mutable state.

**Comment by DrPyser** [comment]
Sorry to spam, I think I answered my own question, and managed to see it the other way. 
"output validators" are desired when the field converts the input to a better representation that can be more easily validated. For example, an integer serialized as a string(for some reason) needs to be greater than 5. A `Integer` field would convert the string to an int, and the `GreaterThan(5)` validator would validate the int.

After some thinking, I guess I can also see how the use cases I mentioned can be implemented directly as part of the field's deserialization. Maybe an additional "validate_input" extension would still be valuable, if only to make such use cases easier for field implementors?

**Comment by lafrech** [comment]
You could be interested in https://github.com/justanr/marshmallow_enum.

**Comment by deckar01** [comment]
It's still unclear to me why you need to validate the raw data for **a specific field instance**. The decorator you are proposing customizes per field validation. You should only need to validate the post deserialization value of a field instance's data. Please provide an example schema to illustrate your use case.

**Comment by DrPyser** [comment]
I think you're right. My intended use was to hook into the `self._validators` during the `__init__` of my custom Enum field, to implement the field's validation. I somehow got it in my head that this was the intuitive way to use the validator mechanism, but I can see how that doesn't make much sense now. 
Anyway, I think its ok to close this issue.

**Comment by deckar01** [comment]
If you run into any issues making a custom field or think the docs can be improved in any way let us know.

**Comment by DrPyser** [comment]
@deckar01 Cool, thanks. And yes, in fact, looking at the [documentation for the `validate` parameter of Field](https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.fields.Field), it seems to support my first intuition, that the validator will be called on the *input value* of the field during deserialization. So I guess that should be corrected.
