### ISSUE TITLE
Loading nested schema is throwing an unknown error.

### ISSUE THREAD

**Issue by Samratkashipathi** [marshmallow-code/marshmallow#1057]
```py
class RolesMarshmallow(ModelSchema):
    class Meta:
        model = Roles
        sqla_session = db_session

class UserRolesMarshmallow(ModelSchema):
    role_details = fields.Nested(RolesMarshmallow, many=True)

    class Meta:
        model = UserRoles
        sqla_session = db_session

class UserDataMarshmallow(ModelSchema):
    roles = fields.Nested(UserRolesMarshmallow, many=True)

    class Meta:
        model = UserData
        sqla_session = db_session
```

**Above is my nested schema** 

```py
data = {
'name':'xyz',
'email':'xyz'
'roles'[{
     'name' : 'one'
},{
    ' name' : 'two'
}
]}
```

When i run 
```py
UserDataMarshmallow(strict=False, many=True).load(data).errors
```

 I am getting

```py
{'_schema': ['Invalid input type.']}
```
Error

**Comment by lafrech** [comment]
Since you set many=True, the schema expects a list and you feed it a dict, hence the invalid input type error.

What about this?

```py
UserDataMarshmallow().load(data)
```

**Comment by Samratkashipathi** [comment]
```roles``` is a nested field in ```UserDataMarshmallow``` , therefore i am passsing list of dict's

**Comment by lafrech** [comment]
I might be missing the obvious but you already set `many=True` in `roles = fields.Nested(UserRolesMarshmallow, many=True)` to account for this.

You'd need `many=True` in 

```py
UserDataMarshmallow(strict=False, many=True).load(data)
```

if you passed

```py
data = [
    {
        'name':'xyz',
        'email':'xyz'
        'roles'[{'name' : 'one'},{'name' : 'two'}]
    },
    {
        'name':'xyz',
        'email':'xyz'
        'roles'[{'name' : 'one'},{'name' : 'two'}]
    },
]
```

**Comment by Samratkashipathi** [comment]
I am sorry it was my mistake, I should not given ```many=True``` in ```UserDataMarshmallow(strict=False, many=True).load(data)```
It is working fine now

**Comment by Samratkashipathi** [comment]
Just for my reference, can we add validations foreign key's columns?

**Comment by lafrech** [comment]
I wouldn't validate foreign keys in marshmallow. Rather than that, I'd try/catch the write to database to capture foreign key errors. It is easier, it avoids multiple calls to DB, and it is not subject to race conditions (foreign key being deleted between validation and DB write).
