### ISSUE TITLE
Order of executing for many validates_schema 

### ISSUE THREAD

**Issue by CompadreP** [marshmallow-code/marshmallow#1068]
Hello!

What is the order of executing if I have several methods decorated with `validates_schema`?

**Comment by lafrech** [comment]
It is undefined as there is currently no way to set an order.

See https://github.com/marshmallow-code/marshmallow/pull/600.

It would be really nice to introduce a priority mechanism in 3.0 and the one proposed in #600 looks good enough for me on the principle.
