### ISSUE TITLE
support Dotted syntax for attribute

### ISSUE THREAD

**Issue by DrPyser** [marshmallow-code/marshmallow#1073]
It'd be cool if the `attribute` `Field` parameter could accept a dotted attribute path, such as what is accepted by `operator.attrgetter`, so that a field could get its value deeper in the object, without having to specify intermediary schemas. 

As for motivation, I sometimes have to deal with data that are wrapped in an additional, unnecessary layer of object. All I want to do is get a value from an attribute of the wrapper object. But if I have to define a schema for any such object, I'll have a lot of such schemas laying around.   
I can make a custom field for that purpose, but I feel my proposition is simpler and cleaner for marshmallow users. It shouldn't be hard to implement either(simply rely on `attrgetter` to implement attribute access), and it is backward compatible.

Thanks!

**Comment by scottwernervt** [comment]
Unless I am misunderstanding the question, dotted attribute paths are supported for fields:

```python
from marshmallow import Schema
from marshmallow.fields import String

class Address:
    def __init__(self, city):
        self.city = city

class User:
    def __init__(self, fullname, city):
        self.fullname = fullname
        self.address = Address(city)

class Account:
    def __init__(self, fullname, city):
        self.user = User(fullname, city)

account_record = Account('John Doe', 'Raleigh')

class AccountSchema(Schema):
    fullname = String(attribute='user.fullname')
    city = String(attribute='user.address.city')

serialized = AccountSchema().dump(account_record)
# {'city': 'Raleigh', 'fullname': 'John Doe'}
```

**Comment by DrPyser** [comment]
Oh, sorry, thought otherwise. Anyway, I realized I can override `get_attribute` at the schema level as well if it wasn't.

Thanks!
