### ISSUE TITLE
Why does the validate function not raise a ValidationError?

### ISSUE THREAD

**Issue by eliasjuanpablo** [marshmallow-code/marshmallow#1080]
I really like the fact that serialization and deserialization now raise a ValidationError instead of the former duple of data and errors, but why didn't "Schema.validate()" comply with this new decision?
I think it would be more consistent if they all worked the same way, but it's just my humble opinion.

Thanks in advance.

**Comment by sloria** [comment]
See https://github.com/marshmallow-code/marshmallow/issues/598#issuecomment-355238115 . The idea was that the user probably just wants the validation messages when calling `validate`. If you want an error to be raised, use `load`.
