### ISSUE TITLE
implementing fields.OrderedDict or fields.Dict(ordered=True)

### ISSUE THREAD

**Issue by sayanarijit** [marshmallow-code/marshmallow#1085]
Hi
Is the any inbuilt implementation of this field? if yes, please let me know. If no, what would be the best workaround and also if there is any plan to add it in future?

**Comment by sayanarijit** [comment]
for now what I did is implement class OrderedDictField(fields.Dict) overriding _serialize and _deserialize methods.

**Comment by sloria** [comment]
There is no built-in `OrderedDict` field at the moment, and we don't have plans to add it in the immediate future.

For now, your approach of creating a `fields.Dict` subclass is your best bet.
