### ISSUE TITLE
Using dictionaries in ValidationError when using validate()

### ISSUE THREAD

**Issue by ksesong** [marshmallow-code/marshmallow#110]
Calling ValidationError with a dictionary-type argument is not properly propagated to the resulting errors dictionary when using the `validate()` method from a `Schema instance`, despite the [documentation](http://marshmallow.readthedocs.org/en/dev/api_reference.html#marshmallow.exceptions.ValidationError).

The problem originates from the use of [`extend()`](https://github.com/sloria/marshmallow/blob/dev/marshmallow/fields.py#L391) when gathering the different errors. A solution is to wrap each dictionary within a list, i.e. change [how dictionaries are parsed](https://github.com/sloria/marshmallow/blob/dev/marshmallow/exceptions.py#L54), but I don't know how this would entail for the other methods.

Thanks!

**Comment by sloria** [comment]
Yes, the current behavior may be incorrect when raising passing a dict to `ValidationError`. That said, passing a `dict` to a `ValidationError` was meant to be an in internal API, i.e. not used for user validators. What is your use case? What would expect the output to be?

``` python
def validator(val):
    raise ValidationError({'bar': 'err'})

class MySchema(Schema):
    foo = fields.Field(validate=validator)

s = MySchema()
s.validate({'foo': 42})   # what should this return?
# {'foo': ['err']}  ?
# OR
# [{'foo': ['err']}]  ?
```

**Comment by ksesong** [comment]
Supposing I have a list of examples as an input (i.e. in use `schema.validate({'examples': ['random string', 'another random 2 string'...]})`), and I would like to know which elements are not validated: (here with a set of validators):

```
'errors': {
    'examples': [
        {
            'code': 'example_too_long',
            'message': 'Some of the examples are too long.'
            'indexes': [1, 4, 5]
        },
        {
            'code': 'example_containing_a_number',
            'message': 'Some of the examples contain invalid characters.'
            'indexes': [2, 5]
        },
    ]
} 
```

I thought I would raise the error directly with the dictionary, but I had to wrap it within a list.

**Comment by ksesong** [comment]
Another remark which is still related to this issue: when registering some [schema-level validation functions](http://marshmallow.readthedocs.org/en/dev/extending.html#schema-level-validation), if I try to raise a ValidationError with a dict or a list, the argument is transformed to a string:

```
raise ValidationError([{'a':'bb'}], field='language')
```

gives:

```
"errors": {
    "language": [
      "[{'a': 'bb'}]"
    ]
}
```

**Comment by sloria** [comment]
Thanks for the clarification @ksesong . I will work on a fix for the next release.

**Comment by sloria** [comment]
Should now be fixed.
