### ISSUE TITLE
Can I use 3.0 now?

### ISSUE THREAD

**Issue by zohucen** [marshmallow-code/marshmallow#1105]
Hi,

I just learned it, I have been fascinated by him.
However, I see 3.0 coming soon, I don't want to upgrade from 2.x in the future, is it pre-released for production now?
I very much hope to get your advice.

**Comment by lafrech** [comment]
We can't promise any release date. However, it is close to complete, so don't expect many breaking changes.

https://github.com/marshmallow-code/marshmallow/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0

If you're starting a new project, go for 3.0.
