### ISSUE TITLE
Field deserialize should permit object type being returned for value

### ISSUE THREAD

**Issue by wschmrdr** [marshmallow-code/marshmallow#1113]
In trying to load a schema I have that has both DateTime and Time fields, I noticed that, when I try to load an object of type datetime.datetime into my DateTime field, and an object of type datetime.time into my Time field, I am met with a validation error on each that it is not a valid input, despite the fact that, upon completion of the utils function in the line referenced, that specific type is returned. For some reason, these specific ones are only accepting a string. I imagine there are other types with the same setup, including but not limited to Date.

For all fields where the value ends up as some sort of an object, I would think there should be an isinstance check to see if the value being input is already of the final type, and if it is, accept it as a valid object pending any additional custom validations the schema has described.

https://github.com/marshmallow-code/marshmallow/blob/9aeedc8c78bb0fb5edb5be71a98e19d1af0682ec/marshmallow/fields.py#L1070

Using marshmallow 2.18.0

**Comment by deckar01** [comment]
`DateTime` and `Time` instances are not serialized values. I suspect this falls outside the intended use case of the provided fields.

Where are these objects coming from that you are trying to load?

**Comment by wschmrdr** [comment]
After accepting a JSON input from a request object, I am transposing the data via dictionaries and lists of dictionaries into the format for my model objects, and subsequently, DB. There are a number of date and time dependencies, so it is imperative, during transposition, that these be objects from the datetime library.

It seems there are unnecessary extra steps being added to pre_load the data back to the string format that for some reason you only accept only to have it go back to the data type it was before the pre_load, and to then post_load it, especially when your attribute value creations are dropping needed data, as referenced in issue #1109 .

**Comment by deckar01** [comment]
Instead of parsing the dates/times before you load the data into the schema you should use custom fields to tell the schema how to load them your way.

https://marshmallow.readthedocs.io/en/3.0/custom_fields.html#creating-a-field-class

**Comment by sloria** [comment]
DateTime is implemented to deserialize strings. For now, you should use a custom field if you want to deserialize other types, as Jared suggested.
