### ISSUE TITLE
How do you correctly use fields in the Meta class with other explicit field declarations?

### ISSUE THREAD

**Issue by symonk** [marshmallow-code/marshmallow#1118]
Could someone explain the correct way to mix field declarations inside the Meta class of a Schema, along with other explicit field declarations, lets take an example here:

```python
class SomeSchema(Schema):
          class Meta:
               fields = (''o_type', 'state_prov')
               load_only = ('eid')
               ordered = True
               many = True
               strict = True
               partial = True (seems to not function either)

          o_type = fields.String(data_key='type')
          state_prov = fields.String(data_key="stateprov")
```

My code has suddenly stopped working, after changing versions of python, I'm wondering how on python 3.7.2 with marshmallow 2.18.0 I can have my json correctly use the data_key types on these 2 fields? it used to work but no longer does

**Comment by scottwernervt** [comment]
`data_key` is a new argument for Marshmallow 3.X which is currently in beta. If you are using 2.18 you need to use `load_from` and `dump_to`.

`partial` parameter is used when initiating your `SomeSchema` class `some_schema = SomeSchema(partial=True)` or when loading `some_schema.load(data, partial=True)`.

`('eid')` returns a `str`, add a comma to make it a tuple `('eid',)`.

Check out [2.x documentation](https://marshmallow.readthedocs.io/en/2.x-line/api_reference.html#marshmallow.Schema.Meta) on Meta options vs Schema options.

**Comment by deckar01** [comment]
`Meta.fields` is for implicit field creation. If you are declaring the types on the schema you don't need that.

https://marshmallow.readthedocs.io/en/2.x-line/quickstart.html#refactoring-implicit-field-creation

`eid` isn't declared on your schema, but it's used in `Meta.load_only`.

**Comment by symonk** [comment]
Sorry I actually ended up reverting from 3.0 to 2.0 somehow, fixed by upgrading again.  derp apologies!
