### ISSUE TITLE
Serializing Flat Object Into Nested Object?

### ISSUE THREAD

**Issue by dperconti** [marshmallow-code/marshmallow#1119]
Hi there! I'm trying to serialize a flat dict into a schema that is not flat, and am wondering what the best practice is for doing so? For example, I get a flat object back from the datastore:

```
{
    "name": "string",
    "address1": "string",
    "address2": "string",
    "type: "string",
    "id": "string",
    "country": "string"
}
```

But need to validate it as this Schema:

```
class AttributesSchema(Schema):
    name = fields.Str(attribute="attributes.name")
    address1 = fields.Str(attribute="address1")
    address2 = fields.Str(attribute="address2")
    country = fields.Str(attribute="country")


class StoresSchema(Schema):
    type = fields.Str(default="stores")
    id = fields.Str(attribute="uid")
    attributes = fields.Nested(AttributesSchema(strict=True))


class StoresDataSchema(Schema):
    data = fields.Nested(StoresSchema(strict=True))
```

Which would yeild an object like this:

```
{
  "data": {
    "type": "string",
    "id": "string",
    "attributes": {
      "name": "string",
      "address1": "string",
      "address2": "string",
      "country": string
    }
  }
}
```

Is it best practice to just do that "translation" first manually? Or is there a way to use `attribute` or something else to have marshmallow automatically change the format?

**Comment by sloria** [comment]
You could use a `post_dump` method to format the nested output. This is the approach that [marshmallow-jsonapi](https://github.com/marshmallow-code/marshmallow-jsonapi) uses.

https://github.com/marshmallow-code/marshmallow-jsonapi/blob/866ad771afa6bb6319fded30fba6603d7f4f8a01/marshmallow_jsonapi/schema.py#L122-L132
