### ISSUE TITLE
partial in schema definition or in load

### ISSUE THREAD

**Issue by RosanneZe** [marshmallow-code/marshmallow#1124]
The documentation seems to suggest there is no difference between specifying partial in the schema initialization or in the actual load. For one of my pre_load functions, I need to know if loading should be partial or not. If you look at this example, you can see where my problem lies:

```python
class A(Schema): 
    b = fields.String() 
    @pre_load 
    def test_partial(self, data):
        print(self.partial) 
        return data 
```
```python
>>> A().load({}, partial=True)                                              
False
{}

>>> A(partial=True).load({})                                                
True
{}
```
Is this a bug? If not, how can I check for partial loading that catches all cases?

**Comment by deckar01** [comment]
> **partial** ... If **None**, the value for **self.partial** is used.

https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.Schema.load

This does not appear to be a bug. The value of `partial` during schema construction becomes the default value. Calling `load` with a different value for `partial` only changes the behavior for that call, and it is not intended to change the default value for `partial` on the schema.

Can you provide an example of what you are doing with the `partial` value in the `@pre_load` hook? The per-call `partial` value gets passed around to a few different functions, so the solution is likely to override one of these methods in a custom schema/field with the desired logic.

**Comment by RosanneZe** [comment]
Thanks for looking into it. It's for dealing with this: https://github.com/marshmallow-code/marshmallow/issues/1042. I'm going to make a new nested field and override the load function instead.
