### ISSUE TITLE
[question] can't set JIT in 3.0.0rc4

### ISSUE THREAD

**Issue by CalebSchwartz** [marshmallow-code/marshmallow#1133]
Hi, I am wanting to utilize toastedmarshmallow and their documentation states to do
`class Meta:
      jit = toastedmarshmallow.Jit
`
however, using the rc4 I get the following import error. I've read through the marshmallow docs and I don't see anything about changing the jit there. Was this option taken away or am I missing something?

ImportError: cannot import name 'SchemaJit' from 'marshmallow' 
(/lib/python3.7/site-packages/marshmallow/__init__.py)

**Comment by CalebSchwartz** [comment]
I solved my own question, toastedmarshmallow hasn't been updated to work with marshmallow3.

**Comment by tramora** [comment]
A PR exists but is blocked https://github.com/lyft/toasted-marshmallow/pull/24
