### ISSUE TITLE
Adding a parameter to allow 'conditional' attributes

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/marshmallow#114]
In my models I have a `Event` that has a `leader` attribute, which is just a `User`. Not all Events have leaders though.
In the schema I have something like

```
class EventSchema(ma.Schema):
    location = ma.String()
    href = ma.URLFor('event_ep', event_id = '<id>')
    host = ma.Hyperlinks({
        'href': ma.URLFor('user_ep', user_id = '<host_id>')
    })
```

If there's no host (i.e., host_id is None) I'd like for EventSchema.host to be an empty dictionary, in effect skipping over the 'href' attribute.
Right now I've added a HostedEventSchema class that has the host attribute and inherits from EventSchema. When I serialize the event I check whether it has a host or not and then select the right schema.
1) Is there a more elegant way to do this in the current Marshmallow?
2) If not, does it make sense to add a parameter that would skip over an attribute if serializing either resulted in None or an Error?
I'll try looking into option 2) if nothing like that exists. Thanks.

Edit: I looked into the source code and I came upon the skip_missing parameter. However this still does not fix my problem because an AttributeError still results in an error with skip_missing = True. However I restructured my schema to use a nested HostSchema (with the href) and skip_missing = True. Still didn't work.

The bug seems to be that it would try to serialize a null object even if it didn't exist and skip_missing was true. For example, if Event.host didn't exist and skip_missing was True, it would try to serialize the nested object (None) without checking if host itself is none.

My proposed fix after line 581 in marshmallow/fields.py (https://github.com/sloria/marshmallow/blob/dev/marshmallow/fields.py#L581):

```
if getattr(obj, attr) is None:
     return {}
```

I didn't submit a pull request because I'd like feedback on this solution before writing tests.  Thoughts?

**Comment by sloria** [comment]
This actually appears to be a bug in Flask-Marshmallow, which I've reported in https://github.com/sloria/flask-marshmallow/issues/10 . Serializing `None` with `URLFor` or `Hyperlinks` results in an `AttributeError`, which is incorrect. I will fix this shortly.

**Comment by sloria** [comment]
I've fixed the related issue with serializing objects whose attributes may return a falsy value in https://github.com/sloria/flask-marshmallow/commit/4d3acfb6af2848b8ee085deed729b2f37cc5d546 .

However, I now realize that this doesn't completely solve your problem, which is that if the nested object passed to a `Nested` field is `None`, don't want to serialize it.

To solve this problem, you can pass `allow_null=True`, which will cause the `Nested` field to serialize `None` to `None`. If you instead want to an empty dict, then just pass `default=dict()`.

I've confirmed that the following code is working:

``` python
import random
from flask import Flask, url_for
from flask_marshmallow import Marshmallow

app = Flask(__name__)
ma = Marshmallow(app)

@app.route('/users/<int:user_id>')
def user_ep(user_id):
    return 'representation of user {}'.format(user_id)

class User:
    def __init__(self, name=None):
        self.name = name
        self.id = random.randint(0, 1000)

class Event:
    def __init__(self, location=None, host=None):
        self.location = location
        self.host = host

    @property
    def host_id(self):
        if self.host:
            return self.host.id
        return None

class HostSchema(ma.Schema):
    id = ma.Int(default=None)
    href = ma.URLFor('user_ep', user_id='<id>')

class EventSchema(ma.Schema):
    location = ma.Str()
    host = ma.Nested(HostSchema, allow_null=True, default=dict())

ctx = app.test_request_context()
ctx.push()

host = User('steve')

evt_with_host = Event(host=host)
evt_wo_host = Event(host=None)

schema = EventSchema()

print(schema.dump(evt_with_host).data)  # {'location': '', 'host': {'href': '/users/504', 'id': 504}}
print(schema.dump(evt_wo_host).data)  # {'location': '', 'host': {}}

ctx.pop()
```

**Comment by sloria** [comment]
@raj-kesavan Does the above meet your use case?

**Comment by ghost** [comment]
Yes, thank you.
I don't know how the development for marshmallow works but is it possible to push these changes to pip so other people don't have the same problem?

**Comment by sloria** [comment]
@raj-kesavan No change was necessary to make the above example work. And the fix to flask-marshmallow has been released to the PyPI.
