### ISSUE TITLE
RFC: Remove FormattedString field

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#1141]
`fields.FormattedString` only exists because it was [ported from Flask-RESTful](https://github.com/flask-restful/flask-restful/blob/b30a408b64acd167cba3a09e649d6c97e415af6b/flask_restful/fields.py#L250). It has a couple peculiarities:

1. It [converts the object to a dict](https://github.com/marshmallow-code/marshmallow/blob/cfb09de0c3048e1c416ba7f34b7b703c6098003f/src/marshmallow/fields.py#L1034) in a way that is error-prone and inefficient.
2. Its deserialization behavior is no-op, making it asymettrical with its serialization behavior.

`fields.Function` and `fields.Method` achieve the same use case in a more performant way.

```python
from dataclasses import dataclass
from marshmallow import Schema, fields


class MySchema(Schema):
    formatted = fields.FormattedString("{first_name} {last_name}")
    function = fields.Function(lambda u: f"{u.first_name} {u.last_name}")


@dataclass
class User:
    first_name: str
    last_name: str


u = User(first_name="Steve", last_name="Loria")
data = MySchema().dump(u)
assert data["formatted"] == data["function"]
```

**Comment by lafrech** [comment]
https://github.com/marshmallow-code/marshmallow/issues/1046

>  This field achieves a function that could be achieved otherwise (property, pre_dump,...). I think it could be dropped without too much collateral damage.

**Comment by sloria** [comment]
If there are no objections to this proposal, I'll plan on merging https://github.com/marshmallow-code/marshmallow/pull/1142 at the end of next week.
