### ISSUE TITLE
required=True depending on the presence of other fields

### ISSUE THREAD

**Issue by lupodellasleppa** [marshmallow-code/marshmallow#1143]
Hello,

I was wondering whether there is a way in marshmallow to have a field to be required depending on the value of another field.

e.g.:
```python
{ 'name':'John', 'status':'unoccupied' }
{ 'name':'Martha', 'status':'occupied', 'job':'waitress' }
```

I'd like to know if there is a way to make the field `job` required if `status == 'occupied'`

Thanks

**Comment by deckar01** [comment]
I don't think there is a way to compute the value of `required` based on the data, but this behavior can be achieved with schema-level validation.

https://marshmallow.readthedocs.io/en/3.0/extending.html#schema-level-validation

```py
from marshmallow import Schema, fields, validates_schema, ValidationError

class TestSchema(Schema):
    field_a = fields.Integer(required=False)
    field_b = fields.Integer(required=False)

    @validates_schema
    def validate_b_requires_a(self, data):
        if 'field_b' in data and 'field_a' not in data:
            raise ValidationError('field_a is required when field_b is set')

TestSchema().load({'field_b': 2})
# marshmallow.exceptions.ValidationError: {'_schema': ['field_a is required when field_b is set']}
```

**Comment by deckar01** [comment]
Side note: `vuelidate` has a dedicated `requiredIf` validator (which I use), so it seems to be a common use case.

https://monterail.github.io/vuelidate/#sub-builtin-validators

**Comment by lupodellasleppa** [comment]
Thank you very much, it worked like a charm, I made something more in the line of:
```python
@validate_schema
def validate_requires(self, data):
    if data['field_b'] == 'foo' and 'field_a' not in data :
        raise ValidationError('field_a is required when field_b is of type foo')
```

**Comment by RichardsonWTR** [comment]
Nevermind. It is already called.  
But by default, it's skipped when there are other errors. 
My solution is to add the `skip_on_field_errors=False`.  

[Reference](https://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.validates_schema:~:text=If%20skip_on_field_errors%3DTrue,to%20True.)

__________
Is it possible to make the `validates_schema` be called by using the `validate` method?

https://stackoverflow.com/a/40900980/9990676

**Comment by tHyenigmatiC** [comment]
> Nevermind. It is already called. But by default, it's skipped when there are other errors. My solution is to add the `skip_on_field_errors=False`.
> 
> [Reference](https://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.validates_schema:~:text=If%20skip_on_field_errors%3DTrue,to%20True.)
> 
> Is it possible to make the `validates_schema` be called by using the `validate` method?
> 
> https://stackoverflow.com/a/40900980/9990676

If you are still looking for solution. This is the solution.
https://github.com/marshmallow-code/marshmallow/issues/1546#issuecomment-602112248
