### ISSUE TITLE
How to pass parameters to a nested schema which is referred by name

### ISSUE THREAD

**Issue by Kamforka** [marshmallow-code/marshmallow#1146]
I would like to refer to a schema by its name when I use it as a nested one, but still I'd like to pass custom arguments to its constructor.

For example instead of doing this:
```python
class AuthorSchema(Schema):
    books = fields.Nested(BookSchema(enveloped=True, many=True))
    class Meta:
        fields = ('id', 'name', 'books')
```

I'd like to use something like this:

```python
class AuthorSchema(Schema):
    books = fields.Nested('BookSchema', enveloped=True, many=True)
    class Meta:
        fields = ('id', 'name', 'books')
```

Please note that in this case the `BookSchema`'s `__init__` method is looking for a custom parameter called `enveloped`.

Is there any official way that I can achieve this using only the native `Nested` field?

I'm using the following versions of marshmallow:
`marshmallow==2.16.3`
`flask-marshmallow==0.9.0`

**Comment by deckar01** [comment]
There is currently not a way to pass custom arguments when the nested schema is referenced as a string. What you can do instead is subclass the schema with the custom `Meta` properties and use that schema name instead.

```py
class NestedBookSchema(BookSchema):
    class Meta:
        enveloped = True

...
    books = fields.Nested('NestedBookSchema', many=True)
```

I'm not exactly sure where `enveloped` comes from, so if this is not part of the `Meta` then you might have to get a little creative with passing the arg through the constructor.

It seems like this could be made a lot more convenient by adding an argument that passes schema constructor args through the nested field constructor.

**Comment by Kamforka** [comment]
@deckar01 
Thanks for your reply!

Yeah I know I can do that, but I was looking for an inbuilt solution, as I thought I might overlook something. 

But still I feel like this feature would be a nice to have when you want to tweak nested schemas which are referenced by name.

**Comment by lafrech** [comment]
> It seems like this could be made a lot more convenient by adding an argument that passes schema constructor args through the nested field constructor.

Absolutely.

**Comment by Kamforka** [comment]
I've made some changes needed for this feature, however when I try to push it I receive back an unauthorized error message. Can you help me with that please?

**Comment by lafrech** [comment]
I you want to propose a change to the code, you may fork the repository in Github, checkout a branch with your changes, push that branch in your fork, then create a pull-request to ask us to merge your changes in the dev branch here.

**Comment by sloria** [comment]
I wonder if we should instead allow for a callable, [like in SQLAlchemy](https://docs.sqlalchemy.org/en/13/orm/relationship_api.html#sqlalchemy.orm.relationship).

```python
class AuthorSchema(Schema):
    books = fields.List(fields.Nested(lambda: BookSchema(enveloped=True)))
```

Thoughts?

**Comment by Kamforka** [comment]
@sloria Actually I like this idea, it would open up possibilities for directed schema factories as well, which is always nice.
