### ISSUE TITLE
[Question] Correct way to handle 'Null' values from an api response? (marshmallow 3)

### ISSUE THREAD

**Issue by symonk** [marshmallow-code/marshmallow#1152]
I have a custom schema that is built up from a few fields.Nested(CustomSchema()), occassionally the api will return 'Null' for some of these values, is there a simple way in marshmallow 3 to skip fields for deserialization if their value is None?  I'm reading the documentation and it looks as if `skip if` was removed?

```
(Pdb) pp err.messages
{'op_settings': ['Field may not be null.'],
 'send_welcome_email': ['Field may not be null.']}
```

my schema looks like this:

```
    op_settings  = fields.Nested(UserOpSettingsSchema())
    send_welcome_email = fields.Boolean()
```

These fields won't always be null/none, how can I handle it easily when they are? from the HTTP response

is it also possible to ignore post_load decorators under some instances of creating a schema() ? I'd like the post_load stuff I'm using to only execute as and when I need it, sometimes I don't want a object instantiated and actually want the data instead

**Comment by sloria** [comment]
You can pass allow `allow_none=True` to allow `None` to pass validation. You could then use a `post_load` method to remove the `None` values if you want.

> is it also possible to ignore post_load decorators under some instances of creating a schema() ?

You can pass `context` to the schema, then read `self.context` in your `post_load` methods.


```python
@pre_load
def do_something(self, data):
    if self.context['dont_do_something']:
        return data
    #...
```

**Comment by symonk** [comment]
allow_none=True seems to then pass 'None' into object instantiation which has problematic outcomes when for example, the default state of the value is another object instantiation.  I managed to solve it using this:

```
    @pre_load()
    def strip_null_values(self, data):
        return {key: value for key, value in data.items() if value is not None}

    @post_load
    def make_user(self, data):
        return User(**data)
```

tho in theory i could just allow none to stop the ValidationError and strip out the Nones before objects are actually instantiated I guess :) . (I missed out your second part during post_load() to strip out the None values, hence why it didn't seem to work!

**Comment by symonk** [comment]
merged both my pointless methods into the @post_load, thanks again!
