### ISSUE TITLE
How Nested Fields Dynamically Set Schema？

### ISSUE THREAD

**Issue by zohucen** [marshmallow-code/marshmallow#1161]
Hi, 
I have a question.

class PaginationSchema:
        items = fields.Nested('schema_name', many = True, dump_only = True)
        count = fields.Integer()
        page = fields.Integer()

 'schema_name' is dynamically incoming.  
 I don't know what to do.  i need help
 Thanks!

**Comment by deckar01** [comment]
It sounds like you need a function to dynamically declare the schema class. You probably don't need to use the schema name / schema registry. Simply passing in the schema class to the function should work. The schema registry is mainly needed for circular/self-referencing schema.

https://marshmallow.readthedocs.io/en/latest/nesting.html#nesting-schemas

```py
def paginate_schema(schema):
    class PaginationSchema(Schema):
        items = fields.Nested(schema, many = True, dump_only = True)
        ...
    return PaginationSchema
```

This pattern also works nicely as a decorator.

**Comment by zohucen** [comment]
> It sounds like you need a function to dynamically declare the schema class. You probably don't need to use the schema name / schema registry. Simply passing in the schema class to the function should work. The schema registry is mainly needed for circular/self-referencing schema.
> 
> https://marshmallow.readthedocs.io/en/latest/nesting.html#nesting-schemas
> 
> ```python
> def paginate_schema(schema):
>     class PaginationSchema(Schema):
>         items = fields.Nested(schema, many = True, dump_only = True)
>         ...
>     return PaginationSchema
> ```
> 
> This pattern also works nicely as a decorator.

This good . i want to know what should i do.

**Comment by deckar01** [comment]
> i want to know what should i do.

I'm not sure if this is a question. If you need anything else, feel free to continue the discussion here. I am closing this issue for now since you seem to indicate that your original question has been answered.
