### ISSUE TITLE
Multiple attribute fields for the class attribute

### ISSUE THREAD

**Issue by LaserPhaser** [marshmallow-code/marshmallow#1162]
Like it shown in the example:
```py
class UserSchema(Schema):
    name = fields.String()
    email_addr = fields.String(attribute="email")
    date_created = fields.DateTime(attribute="created_at")

user = User('Keith', email='keith@stones.com')
ser = UserSchema()
result = ser.dump(user)
pprint(result)
# {'name': 'Keith',
#  'email_addr': 'keith@stones.com',
#  'date_created': '2014-08-17T14:58:57.600623+00:00'}
```
It would be great to be able to specify multiple attributes like it done in golang tags.
https://stackoverflow.com/questions/18635671/how-to-define-multiple-name-tags-in-a-struct

something like this:
```py
class UserSchema(Schema):
    name = fields.String()
    email_addr = fields.String(attributes=("email", "e-mail"))
    date_created = fields.DateTime(attribute="created_at")

user = User('Keith', email='keith@stones.com')
ser = UserSchema()
result = ser.dump(user)
pprint(result)
# {'name': 'Keith',
#  'email_addr': 'keith@stones.com',
#  'date_created': '2014-08-17T14:58:57.600623+00:00'}

user = User('Keith', e-mail='keith@stones.com')
ser = UserSchema()
result = ser.dump(user)
pprint(result)
# {'name': 'Keith',
#  'email_addr': 'keith@stones.com',
#  'date_created': '2014-08-17T14:58:57.600623+00:00'}
```

Marshmallow already extensively used in testing, but this addition will open a new horizon for testing (especially in comparators related area)

If it sounds reasonable I could dig into it.

**Comment by lafrech** [comment]
>     user = User('Keith', e-mail='keith@stones.com')

This is not valid Python. You could pass it as 

```py
    user = User('Keith', **{'e-mail': 'keith@stones.com'})
```

-----------------------------------------------------------------------------

I can understand how this feature would work when loading but the results when dumping is undefined.

What output would you expect from this?

```py
    user = User('Keith', **{'e-mail': 'keith@stones.com', 'email': 'bob@stones.com'})
```

**Comment by LaserPhaser** [comment]
Let me explain it in details

```py
from marshmallow import Schema, fields
from marshmallow import pprint

# UserObject that we get from API
class User(object):
    def __init__(self, name, email):
        self.name = name
        self.email = email

# User Object that we get from DB
class UserDB(object):
    def __init__(self, name, mail):
        self.name = name
        self.mail = mail

# Single user schema for them both
class UserSchema(Schema):
    name = fields.String()
    email_addr = fields.String(attribute="email")
    date_created = fields.DateTime(attribute="created_at")

user = User('Keith', email='keith@stones.com')
userdb = UserDB('Keith', mail='keith@stones.com')

user_schema = UserSchema()
result = user_schema.dump(user)
pprint(result)
>{'email_addr': 'keith@stones.com', 'name': 'Keith'}

user_schema = UserSchema()
result = user_schema.dump(userdb)
pprint(result)
> {'name': 'Keith'}
```

All I want is to be able to have single scheme that could work with multiple objects.

**Comment by lafrech** [comment]
OK, but what would be the logic from the `Field` point of view? Pick the first attribute of the list that holds a value?

The feature you're asking for would have an undefined behaviour when dumping if both attributes are in the object.

You should use different schemas for this use case.

**Comment by deckar01** [comment]
It does seem unusual to have that much uncertainty about the structure of your model. It's not really clear to me why this would be useful or how it relates to testing.

**Comment by LaserPhaser** [comment]
In testing, you usually have to map the data from different sources like databases/API. 
This proposal is like some kind of such mapper.

>The feature you're asking for would have an undefined behaviour when dumping if both attributes are in the object. 

Actually, we can just throw a custom exception.

>You should use different schemas for this use case.

I've got your point if it will break marshmallow ideology let's just close this issue.
