### ISSUE TITLE
2.x: Nested(many=True) eats first element from generator value when dumping

### ISSUE THREAD

**Issue by khvn26** [marshmallow-code/marshmallow#1163]
As reproduced in Python 3.6.8:

```py
from marshmallow import Schema, fields

class O(Schema):
    i = fields.Int()

class P(Schema):
    os = fields.Nested(O, many=True)

def gen():
    yield {'i': 1}
    yield {'i': 0}

p = P()
p.dump({'os': gen()})
# MarshalResult(data={'os': [{'i': 0}]}, errors={})
```

Problematic code is here:

https://github.com/marshmallow-code/marshmallow/blob/2.x-line/src/marshmallow/fields.py#L447

And here:

https://github.com/marshmallow-code/marshmallow/blob/2.x-line/src/marshmallow/schema.py#L832

The easiest solution would be to cast `nested_obj` to list before calling `schema._update_fields`, just like a normal Schema with `many=True` does.

**Comment by deckar01** [comment]
I confirmed that this is no longer an issue in marshmallow 3. I was able to reproduce this with python 2 and 3 using the latest version of marshmallow 2.

**Comment by deckar01** [comment]
`next(iter(...))` is not a safe operation for generators.

```py
def gen():
    yield 1
    yield 2

x = gen()
next(iter(x))
# 1
list(x)
# [2]
```

I suspect `list` would be an acceptable solution. If it was a performance concern we could use `itertools.tee` to copy the generator before peeking at the first item.

**Comment by khvn26** [comment]
`next(iter(...))` is apparently fine because `obj` is guaranteed to be a list here:

https://github.com/marshmallow-code/marshmallow/blob/2.x-line/src/marshmallow/schema.py#L489

It's just that usage of `Schema._update_fileds` in `Nested` ignores the requirement.

**Comment by deckar01** [comment]
> `obj` is guaranteed to be a list here

The code is explicitly expecting other types of iterables.

```py
try:  # Homogeneous collection
    # Prefer getitem over iter to prevent breaking serialization
    # of objects for which iter will modify position in the collection
    # e.g. Pymongo cursors
```

[schema.py#L822-L825](https://github.com/marshmallow-code/marshmallow/blob/5b89e43/src/marshmallow/schema.py#L822-L825)

If the solution is to cast all collections to list, then we should document that and get rid of this dead iterator handling code.

**Comment by khvn26** [comment]
Thank you. Updated the PR.
