### ISSUE TITLE
utils.py checks for dateutil but not version

### ISSUE THREAD

**Issue by rscottweekly** [marshmallow-code/marshmallow#1167]
So, this is a bit niche, so feel free to close if not a bigger issue. I wonder if it was actually an issue with my environment setup. 

When the utils.py checks for dateutil to be present it does:

```
dateutil_available = False
try:
    from dateutil import parser
    dateutil_available = True
except ImportError:
    dateutil_available = False
```

But dateutil only introduced isoparse in 2.7.0 - so somehow I ended up having an older dateutil installed. This didn't get upgraded or an error when upgrading to Marshmallow's latest RC. 

Then when I tried to deserialize a date, it would fail as in invalid date when trying to parse the date. Is it worth adding a check to see if the isodate function exists?

**Comment by deckar01** [comment]
That dependency is listed in `setup.py` as a recommended package with the correct version range. I guess setuptools doesn't check for outdated extras when installing without them. This is a little surprising considering setuptools offers no guidance on how to actually use the optional dependency in the code.

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

We could use the `__version__` that dateutil exposes to enforce the version range in that utility method.

**Comment by rscottweekly** [comment]
Yeah - I don't really understand what to do? Should I do a PR to check the version? Seems a bit silly given, as you say, 2.7.0 is in `setup.py`. 
I am happy to close the issue otherwise?

**Comment by sloria** [comment]
Yeah, I'd rather not add version checks in the code when we can avoid it. It would be nice if setuptools could enforce version ranges on optional dependencies installed without extras.

For now, closing this issue.
