### ISSUE TITLE
fields.Constant does not provide validation?

### ISSUE THREAD

**Issue by alexandersoto** [marshmallow-code/marshmallow#1175]
Hi! Thanks for a great library.

I'm confused about the purpose of `fields.Constant`. I thought it was meant to provide strict validation and require a field to be equal to a given value. Instead what I'm finding is that it accepts and overrides whatever is given, replacing it with the constant. Is that the expected behavior?

What I'm trying to do is say "this field can only contain value X". I can do that with a validator of course, but the notion of a constant makes more sense to me.

**Comment by lafrech** [comment]
Indeed, `Constant` is what you think it is, not what you thought it was.

What you're looking for is [`marshmallow.validate.Equal`](https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.validate.Equal).
