### ISSUE TITLE
Validate pandas DataFrame

### ISSUE THREAD

**Issue by ralbertazzi** [marshmallow-code/marshmallow#1181]
Is there a way to make the library work with pandas dataframes?

This is my use case:
- Serialized object can be either a dict of lists or a pandas dataframe
- Deserialized object is a pandas dataframe

When loading, if the serialized object is a dict of lists the task is easy: first validate each list/column, then create the dataframe in a post_load method. But what if the object passed is already a dataframe? I could serialize to a dict before validation (pre_load), but I'm afraid of performance issues; I also would have to convert the dataframe twice..

Any ideas or solutions? Thanks!

**Comment by lafrech** [comment]
Typically, validation is done on deserialized objects.

You could craft a `DataFrame` field that would load a dict of lists into a dataframe, then the validation would apply on the dataframe whatever the input format.

You'd have to catch all exceptions that can occur when loading into a dataframe to return an appropriate failure message.

You can add a condition to pass the input transparently if it is already a dataframe.

The limit of this approach is that wrong inputs will raise an exception that may not be helpful.

Another approach, perhaps more marshmallish, would be to specify your input schema using `Dict` and `List` and then load in a dataframe in a later step after validation (schema `post_load` method). But you'd lose the ability to receive dataframes as inputs.

Maybe you can get the best of both methods by creating the `DataFrame` field as a child of `Nested` and specifying the expected input format with `List` and `Dict` inside the `Nested` field. Then override `_deserialize` method of `DataFrame` to 1/ accept dataframes and 2/ load dict/list in a dataframe on deserialization.

I hope this helps.

**Comment by deckar01** [comment]
> Serialized object can be either a dict of lists or a pandas dataframe

Do you intend the top level object, that the schema consumes, to be a `DataFrame`? Or is the data frame an attribute in a larger data structure?

**Comment by ralbertazzi** [comment]
> > Serialized object can be either a dict of lists or a pandas dataframe
> 
> Do you intend the top level object, that the schema consumes, to be a `DataFrame`? Or is the data frame an attribute in a larger data structure?

In my case it's part of a larger data structure (a dict that contains two dataframes), but I prefer to make it a schema instead of a field so I can sometimes use it as-is without passing a dataframe inside a dict.

**Comment by ralbertazzi** [comment]
@lafrech I ended up subclassing a Schema that transforms the dataframe to dict in the `pre_load` phase, then validates the dict, and finally creates back a dataframe in the `post_load` phase.

Although this is not optimal I understand that it's probably the only way to make it work with marshmallow. The good thing is that it allows me to perform serialization (e.g. from string to datetimes).

What I wanted was something that interfaces directly with numpy/pandas dtypes but I guess this is not part of marshmallow, since it is intended to be pure Python. Maybe in future I could work on a plugin that works for pandas dataframes :)
