### ISSUE TITLE
Help understanding deserializing & serializing object

### ISSUE THREAD

**Issue by dperconti** [marshmallow-code/marshmallow#1182]
I have an Schema that looks like this;

```
    ...
    longitude = fields.Decimal(
        required=False,
        as_string=False
    )

    longitude_cos = fields.Function(
        # deserialize/load
        data_key='longitude',
        deserialize=Trigonometry.cos,

        # serialize/dump
        attribute="longitude_cos",

        allow_none=True
    )
    ...
```

What I want to happen is, when deserializing/loading, a function (Trigonometry.cos), would calculate the `cos` of the `longitude` field, and add it as a new field (longitude_cos). Then, when serializing/dumping, the `longitude` field and `longitude_cos` would be returned as a Decimal. The above example works for deserializing/loading, but the `longitude_cos` field is missing after serializing/dumping. Is there a solution for this?

**Comment by sloria** [comment]
You can pass a `serialize` function to the `Function` field:

```python
class MySchema(Schema):
    longitude_cos = fields.Function(
        data_key="longitude",
        deserialize=Trigonometry.cos,
        serialize=lambda d: decimal.Decimal(d['longitude_cos']),
    )
```

That should give you the desired result:

```python
loaded = schema.load({"longitude": ...})
print(f"loaded: {loaded}")
# loaded: {'longitude_cos': 0.992197667229329}
dumped = schema.dump(loaded)
print(f"dumped: {dumped}")
# dumped: {'longitude': Decimal('...')}
```

If you need the serialized output to include `longitude_cos`, I would just copy `'longitude'` in a `post_dump` method:

```python
    @post_dump
    def add_longitude(self, data, *args, **kwargs):
        data["longitude_cos"] = data["longitude"]
        return data
```

Does that meet your use case @dperconti ?

**Comment by dperconti** [comment]
hm... not quite, I don't think. 

On deserializing, I want:

```
longitude _______> longitude
            \
             \___> Calculated longitude cosine 
```

On serializing, I want:

```
longitude _________> longitude

longitude_cos______> longitude_cos
```

The above solution has the value of `longitude` as the calculated `longitude_cos`, instead of there being both `longitude` and `longitude_cos` keys/values.

**Comment by deckar01** [comment]
`deserialize` assumes the value already exists and allows you to transform it. It does not synthesize values like `serialize` does.

A good way to handle computed data is to encapsulate the computation in a data model. This avoids the pitfall of function fields not being able to customize serialization of the underlying type declaratively. It also keeps the data from getting out of sync between mutations by defining the property as a relationship rather than a procedural step.

```py
class Foo:
    def __init__(self, longitude, ...):
        self.longitude = longitude
        ...

    @property
    def longitude_cos(self):
        return Trigonometry.cos(self.longitude)

class FooSchema(Schema):
    longitude = fields.Decimal(...)
    longitude_cos = fields.Decimal(..., dump_only=True)

    @post_load
    def make_object(self, data):
        return Foo(**data)
```

https://marshmallow.readthedocs.io/en/3.0/extending.html#example-enveloping

**Comment by dperconti** [comment]
The `@post_load` tactic seems to work best for my use case:

```
    @post_load
    def _add_trig_values(self, data):
        return Trigonometry.calculate_trigonometry_values(data)
```

Thanks, everyone!!
