### ISSUE TITLE
RFC: Remove `attribute` parameter from fields

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#1187]
With `data_key` to designate the serialized key and the field name to designate the deserialized attribute, I can't think of a use case for `attribute`. Are there cases where the field name would need to be different from the deserialized attribute?

h/t @taion 

cc @lafrech @deckar01

**Comment by lafrech** [comment]
There could be cases where the attribute name is not a valid Python variable name.

Currently, [get_value](https://github.com/marshmallow-code/marshmallow/blob/dev/src/marshmallow/utils.py#L287) first tries to access by index, then by attribute, so I assume something like `object['my-attribute']` is expected, but you couldn't write

```py
class MySchema:
    my-attribute = fields.Int()
```

I don't have a real-life use case for that. Nor do I have a real-life use case for the "access by index"  feature.

**Comment by sloria** [comment]
@lafrech You can use `include` for that use case:

```python
class MySchema(Schema):
    class Meta:
        include = {
            "my-attribute": fields.Int()
        }
```

**Comment by sloria** [comment]
There's some code in `List` and `Tuple` to for accessing attributes on the inner objects. This test demonstrates the use case:

```python
    def test_list_field_respect_inner_attribute(self):
        now = dt.datetime.now()
        obj = DateTimeList([now])
        field = fields.List(fields.Int(attribute='day'))
        assert field.serialize('dtimes', obj) == [now.day]
```

This use case can still be met by using `fields.Pluck`, though.

```python
    def test_list_field_respect_inner_attribute(self):
        now = dt.datetime.now()
        obj = DateTimeList([now])

        class DateTimeSchema(Schema):
            day = fields.Int()
        field = fields.List(fields.Pluck(DateTimeSchema, 'day'))
        assert field.serialize('dtimes', obj) == [now.day]
```

This seems like a more consistent API anyway.

**Comment by sloria** [comment]
Ah, removing attribute would break use cases where you want multiple output fields based on a single attribute:

```python
class UserSchema(Schema):
    created = fields.DateTime()
    created_formatted = fields.DateTime(format='%Y-%m-%d', attribute='created', dump_only=True)
    created_iso = fields.DateTime(format='iso', attribute='created', dump_only=True)
```

**Comment by lafrech** [comment]
> removing attribute would break use cases where you want multiple output fields based on a single attribute

This could be achieved using `pre_dump` to duplicate the value.

**Comment by sloria** [comment]
> This could be achieved using pre_dump to duplicate the value.

I guess, but that's awkward. It feels wrong to set arbitrary attributes on an object.

**Comment by taion** [comment]
It could make more sense just to discourage the use of `attribute` (and instead recommend `data_key`) in most cases, just to make the effective API surface area smaller.
