### ISSUE TITLE
Default nested schema

### ISSUE THREAD

**Issue by ralbertazzi** [marshmallow-code/marshmallow#1197]
Say I have these two schemas:

```
class InnerSchema(Schema):
    a = fields.Integer(missing=10)

class OuterSchema(Schema):
    inner = fields.Nested(InnerSchema)
```

I'd like to achieve the following behavior:

```
OuterSchema().load({}) == {'a': 10}
```

I found two ways of doing that:

1. Repeating myself:
```
class OuterSchema(Schema):
    inner = fields.Nested(InnerSchema, missing={'a': 10})
```

(I don't want to move the missing value into `OuterSchema` since I might want to use `InnerSchema` independently and still have the missing value automatically added)

2. Forcing an empty dict during pre_load phase:

```
class OuterSchema(Schema):
    ....
    @pre_load
    def add_empty_dict(self, data):
        if 'inner' not in data:
            data['inner'] = {}  
        return data
```

Unfortunately setting `fields.Nested(InnerSchema, missing={})` returns an empty dictionary after validation.

Is there a better way to do that than method 2? Thanks!

**Comment by lafrech** [comment]
We need to find a nice solution to this.

This is discussed in https://github.com/marshmallow-code/marshmallow/issues/1042. Let's continue discussion there.
