### ISSUE TITLE
Unknown INCLUDE dump

### ISSUE THREAD

**Issue by lhmatt** [marshmallow-code/marshmallow#1198]
I can't seem to find this behaviour documented anywhere so feel free to point me in the right direction, but this also feels like a bug.

Version: `3.0.0rc5`

In the example below we have a config dict. The `MethodConfigSchema` is set to allow unknown values because the method config will vary greatly. 

When loading the config these additional unknown values are preserved (the first assert statement). However, when dumping the the loaded config the values are removed; only `method_id` remains as that is defined in the schema.

``` python
from uuid import uuid4
from marshmallow import Schema, fields, INCLUDE, ValidationError
import calendar
from datetime import datetime


STATUS_INITIALIZED = 0


class MetaSchema(Schema):
    class Meta:
        unknown = INCLUDE

    createdTime = fields.Int(default=calendar.timegm(datetime.utcnow().utctimetuple()))


class UserIdentifierSchema(Schema):
    class Meta:
        unknown = INCLUDE

    uid = fields.Str(required=True)
    email = fields.Email(required=True)
    displayName = fields.Str(required=True)


class MethodConfigSchema(Schema):
    class Meta:
        # Methods can include any number of additional config options so we just pass those through as well
        unknown = INCLUDE

    # The validation here is simply an attempt at importing the method module. (overloaded for test)
    # method_id = fields.Str(required=True, validate=lambda s: importlib.import_module(f"package.methods.{s}"))
    method_id = fields.Str(required=True, validate=lambda s: True)


class NotificationManagerConfigSchema(Schema):
    notification_uuid = fields.Str(default=str(uuid4()), dump_only=True)
    meta = fields.Nested(MetaSchema, default=MetaSchema().dump(MetaSchema()), dump_only=True)
    status = fields.Int(default=STATUS_INITIALIZED, dump_only=True)
    status_description = fields.Str(default='New notification manager instance created', dump_only=True)

    target = fields.Nested(UserIdentifierSchema, required=True)
    methods = fields.Nested(MethodConfigSchema, many=True, required=True)
    payload = fields.Dict(keys=fields.Str(), values=fields.Str(), required=True)
    initiator = fields.Nested(UserIdentifierSchema, required=True)
    purpose = fields.String(required=True)


TEST_CONFIG = {
    "target": {
        "uid": "xc9b86xcb96xcb86xcb",
        "displayName": "Test User",
        "email": "user.email@example.com"
    },
    "methods": [
        {
            "method_id": "email",
            "template_id": "verify_account"

        }
    ],
    "payload": {
        "example": "key",
        "test": "data"
    },
    "initiator": {
        "uid": "ad0974w608735653680",
        "displayName": "Admin User",
        "email": "admin.email@example.com"
    },
    "purpose": "Verify User Account"
}


try:
    parsed_config = NotificationManagerConfigSchema().load(TEST_CONFIG)
except ValidationError as err:
    """
    err.messages  # => {'email': ['"foo" is not a valid email address.']}
    valid_data = err.valid_data  # => {'name': 'John'}
    """
    raise ValueError(err.messages)

assert 'template_id' in parsed_config['methods'][0]

serialized_config = NotificationManagerConfigSchema().dump(parsed_config)

assert 'template_id' in serialized_config['methods'][0]

print('Example finished')

```

If this is expected behaviour, is there any way to work around it? Or should I simply avoid using `dump` in this instance?

**Comment by lafrech** [comment]
Indeed, the `unknown` parameter only applies on load, not on dump.

This is in line with the fact that validation only happens on load. The rationale is that serialized data is outside world and can be invalid, while deserialized data is application objects that should be of known structure.

Your use case (loosely defined data) does not really fit here.

`dump` can act on dictionaries or on objects. On dictionaries, it could be modified to pass all keys, but how would that work for objects? You can't pass all attributes. You need schemas to define which attributes must be serialized.

**Comment by lhmatt** [comment]
Thanks @lafrech, appreciate you taking the time to explain why it works this way.

I do actually have a definition for each method's config. The challenge is that each method config will be different. I suppose I'd need a strategy for verifying each method config separately using specific schemas.

**Comment by sloria** [comment]
Closing for now, though feel free to carry on discussion if need be.
