### ISSUE TITLE
Question: How can I programmatically add fields to a Schema?

### ISSUE THREAD

**Issue by mcgfeller** [marshmallow-code/marshmallow#1201]
While working on my proposed [Schema Protocol](https://github.com/mcgfeller/py-schemas), I need to add fields programmatically to a Schema class (or object). 

The only way I found was to add the fields to `schema.declared_fields`, and then call `schema._init_fields()`. As this is an internal API, is there a better official way to programmatically create a Schema and populate it with fields? 

Whereas declaring the Schema in a class, creating it dynamically adds much flexbility.

Thank you and best regards,
Martin

**Comment by lafrech** [comment]
Those may help:

- https://github.com/marshmallow-code/marshmallow/issues/585
- https://stackoverflow.com/questions/42231334/define-fields-programmatically-in-marshmallow-schema

**Comment by sloria** [comment]
There is also a `get_declared_fields` hook on `SchemaMeta` which is used by e.g. marshmallow-sqlalchemy to generate fields for a model/table: https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/287f5b8541bff6037a2bcc04681cb05d9ef7c6ea/src/marshmallow_sqlalchemy/schema.py#L54

**Comment by mcgfeller** [comment]
Thanks for your replies. Adding a field to an existing Schemas class (or an already instantiated Schema) seems to be more complicated than I originally thought, but I respect that this is not how Marshmallow is intended to be used.

**Comment by sloria** [comment]
Yes, at the moment it's not a common enough use case case to justify the complexity of exposing more API.

**Comment by aonamrata** [comment]
if you are like me and stumble upon this looking for a solution. Ref https://stevenloria.com/dynamic-schemas-in-marshmallow/ it is much easier and neat.

**Comment by mcgfeller** [comment]
@aonamrata : Thanks, this looks good. It is important to be able to update an existing Schema, so it can be built incrementally. This is hard to do in Pydantic (to which I switched, because the basic declaration is easier).
