### ISSUE TITLE
How to serialize the objects in a list, which have different types but derive from the same base class?

### ISSUE THREAD

**Issue by apepkuss** [marshmallow-code/marshmallow#1202]
I got a case when I used marshmallow. I don't know how to deal with the case and need your help.  For convenience to illustrate the case, I give some sample code first.

**Step 1 - Define a base class and two derived classes from it.**

```python
class MyBase(object):
    def __init__(self, name: str):
        self.name = name

class DerivedA(MyBase):
    def __init__(self, name: str):
        MyBase.__init__(self, name)
        self.alpha: float = 0.0

class DerivedB(MyBase):
    def __init__(self, name: str):
        MyBase.__init__(self, name)
        self.message: str = "some message"

class SomeClass(object):
    def __init__(self):
        self.alist: List[MyBase] = []
```

**Step 2 - Create objects from the classes defined above.**
```python
# first create DerivedA and DerivedB instances; 
# then create a SomeClass instance;
# finally append da and db to alist of my_class
da = DerivedA('a')
db = DerivedB('b')
my_class = SomeClass()
my_class.alist.append(da)
my_class.alist.append(db)
```
**Step 3 - I would like to serialize the container object (_my_class_, here), so I defined the following schemas.**
```python
class MyBaseSchema(Schema):
    """Schema for MyBase class"""
    name = fields.String()

class DerivedASchema(MyBaseSchema):
    """Schema for DerivedA class"""
    alpha = fields.Float()

class DerivedBSchema(MyBaseSchema):
    """Schema for DerivedB class"""
    message = fields.String()

class SomeClassSchema(Schema):
    """Schema for SomeClass class"""
    alist = fields.Nested(MyBaseSchema, many=True)
```

**Step 4 - Serialize the target object.**
```python
schema = SomeClassSchema()
data = schema.dump(my_class)
pprint(data)
```

The printing output is _{'alist': [{'name': 'a'}, {'name': 'b'}]}_.

**My question is how to get 'alpha' and 'beta' in the printing result?** I just concern that my schema definitions could be incorrect. I noticed similar issues #195 and #42, but failed to get the final answer to my question. Please give me some tips. Thanks a lot!

**Comment by lafrech** [comment]
The keyword here is polymorphism.

See https://github.com/marshmallow-code/marshmallow/issues/1196#issuecomment-482974016.

**Comment by lafrech** [comment]
Polymorphism is definitely a recurrent request. I created a new label to tag all related issues: https://github.com/marshmallow-code/marshmallow/labels/polymorphism. I tagged those I could find with a quick search but there may be others. Plus those in apispec bugtracker.

We should perhaps reconsider introducing such a feature in marshmallow core. Not saying we need to do this for MA 3.0.

It would help polymorphism support in apispec: currently, it is hard to support because we don't want to depend on one or several third-party libs.

**Comment by apepkuss** [comment]
@lafrech Thanks for the quick reply. I tried **fields.Method** based on the answer from https://github.com/marshmallow-code/marshmallow/issues/195#issuecomment-415456392, and it works for my case. In addition, I think it would be better to provide some sample code for this case in the docs for future users. Anyway, thank you for your help.
