### ISSUE TITLE
dict of dicts with unknown key names

### ISSUE THREAD

**Issue by fenchu** [marshmallow-code/marshmallow#1203]
I have endpoints returning dict of dicts where keys are not known upfront.

I havent managed to get marshmallow to pass this.

I believed this was a variant of https://github.com/marshmallow-code/marshmallow/issues/120
but the key is unknown "service" from DictField example is unknown.
```
import json
from marshmallow import Schema, fields
myjson = """
{
    "ssh.service": { 
        "info": "OpenBSD Secure Shell server",
        "status": "running"
    },
    "rsyslog.service": {
        "info": "System Logging Service",
        "status": "running"
    }
}
"""

class ServiceSchema(Schema):
    info = fields.Str()
    status = fields.Str()

class ServicesSchema(Schema):
    service = fields.Nested(ServiceSchema, many=True)

struct = json.loads(myjson)
schema = ServicesSchema()
result = schema.load(struct)
```
Giving:
`marshmallow.exceptions.ValidationError: {'ssh.service': ['Unknown field.'], 'rsyslog.service': ['Unknown field.']}`

Those fields are not know upfront. I have tons of rest apis returning dict of dicts.
How can service be a variable text?

**Comment by deckar01** [comment]
@fenchu Thanks for your interest in this topic. It is a gap in marshmallow's functionality that has been on my mind also. Let's continue this discussion on #972.
