### ISSUE TITLE
2.x: if a field has the same name as a dict method, and you dump a dict missing that field, the method gets called

### ISSUE THREAD

**Issue by rascalking** [marshmallow-code/marshmallow#1205]
With the proviso that this is an edge-case, and changes on the `dev` branch (#811 and #1063) seem to resolve this inadvertently, I'm seeing the following behavior on `2.x-line`.

If you have a schema where the field name is the same as a `dict` method, and you dump a dict that is missing that field, marshmallow 2.x will call that method when you attempt a dump.  Here's a minimal repro case:
```python
from marshmallow import Schema, fields

class Repro(Schema):
    bar = fields.String(allow_none=True)
    items = fields.String(allow_none=True)

schema = Repro()
result = schema.dump({})
assert result.data == {}, repr(result.data)
```

Calling this should get you something like:
```
Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    assert result.data == {}, repr(result.data)
AssertionError: {'items': 'dict_items([])'}
```

Since `utils._get_value_for_key` will [call anything that looks like a callable](https://github.com/marshmallow-code/marshmallow/blob/ac9ff95432f929fb0fa2394c29b94d1f804a1504/src/marshmallow/utils.py#L347), if you change the field name from `items` to `get` and run that repro case again, the call to `dump` will fail with a `TypeError` before we even get to the assert, since `dict.get` expects a positional argument.

If you're still accepting PRs for the `2.x-line` branch, I'm happy to back-port the current `dev` version of `utils._get_value_for_key` to fix this.

**Comment by sloria** [comment]
Yes, 2.x is still being supported, so I'd definitely appreciate a PR!

**Comment by rascalking** [comment]
Okay, so I was wrong about this being fixed on `dev`.  On `dev` it's no longer checking to see if the attribute was a callable and then calling it, so the `TypeError` doesn't get thrown when the field is named `get`.  But now you get back the `dict.get` method instead.

We could return `default` if the `getattr` result is callable, but it looks like (judging by #430) the decision was made that the 2.x line should continue to call callables here.  That might be a valid solution on the `dev` branch, though.

On this branch, short of doing something like "if it's a callable, return `default` if it's also a callable on `dict` proper", I can't think of anything that solves this without also being a regression for #1060.

**Comment by sloria** [comment]
I'm not sure there's a good way to handle this without introducing a performance regression. I'd rather not add a performance penalty for such a corner case.

For now, you can override `get_attribute` for Schemas that serialize dictionaries.

```python
from marshmallow import Schema, fields


class Repro(Schema):
    items = fields.Str()

    def get_attribute(self, obj, key, default):
        return obj.get(key, default)


schema = Repro()
result = schema.dump({})
assert result == {}, repr(result)
```
