### ISSUE TITLE
Add strict min/max Range validator

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow#1214]
`Range` only offers "greater than or equal" (min) and "lower than or equal" (max).

We could add "greater than" and "lower than".

How should we call the new parameters?

- `min_strict` and `max_strict`?
- `strict_min` and `strict_max`?
- ...?

**Comment by sloria** [comment]
Not sure this is necessary or desirable. We've had issues in the past with the "strict" verbiage, and I think we should avoid it when we can.

**Comment by lafrech** [comment]
Example use case:

In my API, a resource allows to POST a building with an area. The area must be positive (a negative area doesn't make sense). And I want it to be not zero because it can't be zero either (and because I want to avoid zero division errors when computing ratios).

I can't express "> 0" with marshmallow so as a workaround I set ">= 0.01" which does the job in my use case but might not be that great if the dynamic was greater and the value could be arbitrary small.

I can live with the 0.01 trick but it looks like a sorry workaround for an issue that seems simple to fix.

**Comment by sloria** [comment]
That makes sense. Perhaps we could use `greater_than`, `greater_than_eq`, `less_than`, `less_than_eq`. for parameter names.

**Comment by kdop** [comment]
I have a similar problem. I think if we simply add `min_inclusive`, `max_inclusive` we can achieve all the scenarios described above.

So the signature will become:

`class marshmallow.validate.Range(min=None, max=None, error=None, min_inclusive=True, max_inclusive=True)`

so the default behavior will remain unchanged.

**Comment by lafrech** [comment]
@kdop, would you like to propose a PR for this?

@sloria, any preference (`greater_than_eq` vs. `min_inclusive`)? We're allowed to introduce breaking changes and I find `min_inclusive` a slight bit more awkward.

~OTOH, `max`/`min` are more in line with `min`/`max_length`~ Scratch that, `Lengh` validator also uses `min`/`max` parameters. We should change them too.

**Comment by kdop** [comment]
@lafrech sure, assign to me.

**Comment by sloria** [comment]
Sure, `min_inclusive` and `max_exclusive` seem fine to me.

**Comment by lafrech** [comment]
@kdop I didn't manage to assign you with the assign function, but please go for it!

Thanks!

**Comment by kdop** [comment]
PR https://github.com/marshmallow-code/marshmallow/pull/1221
