### ISSUE TITLE
Fields with a period in them get auto-converted to a nested dict, how do you avoid this behavior?

### ISSUE THREAD

**Issue by nickjj** [marshmallow-code/marshmallow#1225]
Hi,

I have 2 fields in my schema that must be `request.year` and `request.month`.

I tried doing this:

```py
request_year = fields.Integer(allow_none=True, attribute='request.year',
                              validate=validate.Range(min=2000, max=3000))
request_month = fields.Integer(allow_none=True, attribute='request.month',
                               validate=validate.Range(min=1, max=12))
```

But it returns the data back like this:

```json
        "request": {
          "month": 5,
          "year": 2019
        }
```

Where as I'm trying to get it back like this:

```json
        "request.year": 2019,
        "request.month": 5
```

I even went as far as trying this:

```py
    class Meta:
        include = {
            'request.year': fields.Integer(allow_none=True,
                                           validate=validate.Range(min=2000,
                                                                   max=3000)),
            'request.month': fields.Integer(allow_none=True,
                                            validate=validate.Range(min=1,
                                                                    max=12))
        }
```

But it produces the same output as using `attribute` from before.

How can I configure it to stop auto-nesting fields with a period in them?

**Edit**: This is with v3.0.0RC6.

**Comment by deckar01** [comment]
I was able to repro this in marshmallow 2 and 3. Here is a minimal example:

```py
from marshmallow import Schema, fields

class Test(Schema):
    foo = fields.Str(attribute='bar.baz')

Test().load({'foo': 'test'})
# {'bar': {'baz': 'test'}}
```

This behavior doesn't seem to be documented. The docs only define how `attribute` affects serialization.

@nickjj I think the feature you need is `data_key`. It defines an alternate key to use for the field in its serialized form.

https://marshmallow.readthedocs.io/en/3.0/quickstart.html#specifying-serialization-deserialization-keys

```py
from marshmallow import Schema, fields

class Test(Schema):
    foo = fields.Str(data_key='bar.baz')

Test().dump({'foo': 'test'})
# {'bar.baz': 'test'}
```

If that doesn't work could you post an example of your input data, the operation you are performing, and explain what you are doing with the output?

**Comment by nickjj** [comment]
If I follow what I think you're saying, I tried this:

```py
request_year = fields.Integer(allow_none=True, data_key='request.year',
                              validate=validate.Range(min=2000, max=3000))
request_month = fields.Integer(allow_none=True, data_key='request.month',
                               validate=validate.Range(min=1, max=12))
```

But it still came out like this:

```json
        "request_month": 1,
        "request_year": 2019
```

However, it was able to accept `request.year` as valid input which is good news.

But in the end, I want to accept `request.year` as valid input and also have the valid data object come back as `request.year` instead of `request_year`. Ultimately I need to send this data as `request.year` to another API and I didn't want to have to manually swap the key names later (last resort).

The exact data structure of what I want to receive and send back looks like this:

```json
        "params": {
            "request.year": 2019,
            "request.month": 1
         }
```

Minimal example looks like this:

```py
class ParamsSchema(Schema):
    request_year = fields.Integer(allow_none=True, data_key='request.year',
                                  validate=validate.Range(min=2000, max=3000))
    request_month = fields.Integer(allow_none=True, data_key='request.month',
                                   validate=validate.Range(min=1, max=12))
```

This is really something I'm nesting into another Schema but I don't think the parent Schema comes into play here.

The way I'm calling it is like this: `payload = ParamsSchema().load(data)` where `data` is getting JSON from a POST request. If I use `dump(data)` instead of `load(data)` then those fields don't even get returned back in the `payload`. It ends up being valid (no validation error was thrown) but both request fields are 100% stripped out from the output.

**Comment by deckar01** [comment]
What is the other API you are sending it to? Normally you need to serialize the data before sending it. `data_key` will use the right key if you call `dump()`.

```py
# Validate input
data = schema.load(request_data)
# Manipulate values if needed
...
# Serialize the data for external APIs
output = schema.dump(data)
```

**Comment by nickjj** [comment]
I haven't gotten to sending the data to that API yet. For now I was just loading it and then returning it as a response with Flask using `jsonify(data)`. That `jsonify` function ends up calling `json.dump(data)` I think.

When I use `dump()` those 2 request keys aren't a part of the output. Any thoughts on why that happens? In fact, when I call `ParamsSchema().dump(data)` a ton of other fields are gone too, especially when I put invalid data (on purpose).

**Comment by deckar01** [comment]
> When I use dump() those 2 request keys aren't a part of the output.

The second example in https://github.com/marshmallow-code/marshmallow/issues/1225#issuecomment-497425818 allowed me to dump to a key with a period in it.

> when I put invalid data (on purpose) ... a ton of other fields are gone too

Did you load the data first? Marshmallow 3 should raise an error when you try to load invalid data.

**Comment by nickjj** [comment]
I was loading it first, and then `jsonify` dumps it behind the scenes as part of the Flask response.

The issue I was having with the output was related to a test. Yeah, it seems I need to `.dump(data)` it in order to get the fields with the period in it, otherwise they come out as `request_year` and `request_month` and since `jsonify` dumps, it wasn't happening when I hit the endpoint directly.

So it is all working now, thanks. Although I wonder if things should be changed to avoid nesting it by default like that. What do you think?

**Comment by deckar01** [comment]
After looking into it a little more I think the behavior is intended. Most of the arguments that reference field names are allowed to use dot delimiters to access nested data. This needs to be documented for `attribute`. It also makes sense for the `attribute` argument to be used during deserialization, because all operations should ideally by symmetric to ensure idempotency through multiple de/serialization rounds.

**Comment by nickjj** [comment]
So you're saying I should set both `attribute` and `data_key` to the same value? If one changes, so does the other?

**Comment by deckar01** [comment]
No, you need this custom key when you serialize to JSON, so you should just do that with marshmallow's `dumps` instead of `jsonify`. You have to do this if you use any rich data types in your schema to take advantage of marshmallow's serialization features. `attribute` is for a different use case. Its behavior is correct, it just isn't fully documented.

**Comment by sloria** [comment]
Closing this for now, but feel free to carry on the discussion.
