### ISSUE TITLE
DateTime timezone management rework

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow#1234]
There are various issues I'd like to address in `DateTime` timezone management.

- ~Different behaviour depending on whether dateutil is installed (https://github.com/marshmallow-code/marshmallow/issues/497). Explicit would be better than implicit.~ (Fixed in #1265)
- Awareness not enforced (https://github.com/marshmallow-code/marshmallow/issues/520).

I begun work on this in #933 a while ago but I never got this through. I'd like to come up with a good design before getting back to it.

----------------------------------------------------------------------------------------

~AFAIU, the only action for which dateutil is required is deserializing iso formatted aware datetimes with non-utc timezones.~ Nope. dateutil is never needed (See below and #1265).

~Only iso requires dateutil. rfc format has timezones (https://tools.ietf.org/html/rfc822) but those are not as complex as iso timezones so they don't need dateutil.~ We don't use dateutil for RFC datetimes anymore (https://github.com/marshmallow-code/marshmallow/pull/1246 and https://github.com/marshmallow-code/marshmallow/pull/1248).

----------------------------------------------------------------------------------------

I've been thinking of using two field classes: `NaiveDateTime` and `AwareDateTime`.

Here's what they could do when deserializing:

Input | `NaiveDateTime` | `AwareDateTime`
-- | - | -
Naive | Pass | Fail
Aware UTC | Fail | Pass
Aware non UTC | Fail | Pass unless `utc_only` is `True`

We could add a `utc_only` flag to `AwareDateTime`. An exception would be raised at instantiation time if it is `False` and dateutil is not installed. (This may not be at import time if fields are declared programmatically, but it is better than deserialization time.) `utc_only` would default to `False`. Basically, this means the user who do not want to install dateutil would have to opt-in for `utc_only`. If it's too much pain, he could subclass the field to avoid providing the parameter on each instance.

----------------------------------------------------------------------------------------

There may be other aspects to consider:

- Could `NaiveDateTime` accept an aware datetime? Should it drop the TZ? I don't think so. Should it convert it to a specified TZ before dropping the TZ? It could accept a `timezone` argument specifying a target tz. An exception would be raised if target TZ is not UTC and dateutil is not installed.

`timezone` | Deserialization of aware datetimes in `NaiveDateTime`
-- | -
`None` | Fail
`'UTC'` | Convert to UTC then drop TZ
Some other TZ | Convert to UTC then drop TZ, raise at init if format is iso and no dateutil

- Could `AwareDateTime` accept a naive datetime? It could consider UTC by default. Or we could add a `default_tz` argument.

`default_tz` | Deserialization of naive datetimes in `AwareDateTime`
-- | -
`None` | Fail
`'UTC'` | Add UTC TZ
Some other TZ | Add TZ, raise at init if format is iso and no dateutil

Should this argument be used upon serialization as well? (We could also have `default_tz` and `missing_tz` for serialization/deserialization, copied on the `default`/`missing` logic, but I'd rather avoid this kind of complexity.)

- Could `AwareDateTime` provide a TZ conversion feature? We could add a `convert_to_tz` argument to specify a TZ to convert to (and raise if TZ not UTC and no dateutil)?

`convert_to_tz` | Post-deserialization of datetimes in `AwareDateTime`
-- | -
`None` | Keep TZ
`'UTC'` | Convert to UTC TZ
Some other TZ | Convert to TZ, raise at init if format is iso and no dateutil

Should this argument be used upon serialization as well? I'd say no. But maybe there's a use case for this. AFAIU, the point of `LocalDateTime` is to keep datetime TZ on serialization while `DateTime` converts to UTC implicitly.

- Should we keep `DateTime` as an alias? To which field and with which options?

**Comment by sloria** [comment]
@lafrech Maybe this can wait til 4.0, unless you think this is quick work.

**Comment by lafrech** [comment]
I wouldn't say it is a quick work but I'd really like this to be part of MA3.

Current behaviour is not well defined IMHO.

The docstring in DateTime field reads:

    `Schema.load <marshmallow.Schema.load>` returns `datetime` objects that are timezone-aware.

which is false.

In fact, while working on it right now, I realized things differ between RFC and ISO, as `rfcformat` dumps as naive when `localtime` is False. I'd like to harmonize RFC and ISO.

I could change `rfcformat` to match `isoformat` (don't remove TZ when dumping aware datetime even if `localtime` is `False`) and I probably will for now, but we need another parameter to express that we want to dump as naive/aware, which is not the `localtime` parameter which means "keep local" vs. "turn into UTC".

Hence this whole rework.

In a first step, we could forget about the `utc_only` parameter. It can be added later as a non-breaking change.

Input | `NaiveDateTime` | `AwareDateTime`
-- | - | -
Naive | Pass | Fail
Aware non UTC | Fail | Pass

The other parameters I mentioned above could also be added later.

**Comment by lafrech** [comment]
Last time I checked, I concluded that Django relied on pytz (equivalent to dateutil) to parse datetimes.

Reading again the source code (https://docs.djangoproject.com/en/2.2/_modules/django/utils/dateparse/#parse_datetime), I might have been wrong. pytz is imported but maybe not necessary. This is worth investigating.

Copying Django's code may allow us to get rid of the python-dateutil dependency. This dependency is not a big deal by itself, but supporting both with and without makes our API more complicated to the user.

**Edit**: Indeed: https://github.com/marshmallow-code/marshmallow/pull/1265.

**Comment by lafrech** [comment]
With dateutil out of the way, things are much simpler.

Here's the plan:

- [x] Remove `LocalDateTime`.

- [x] Leave TZ info unchanged in `DateTime` ([aware|naive] datetimes are [|de]serialized as [aware|naive]). This fixes a few inconsistencies.

 - [x] Introduce `NaiveDateTime` and `AwareDateTime`. Those fail on deserialization if the datetime is not naive/aware. They don't check awareness on serialization. I assumed it would be consistent with the other fields. Is that fine?

 - [x] Add an optional `timezone` parameter to `NaiveDateTime` to allow it to convert aware to naive datetimes (rather than fail). Apply on serialization as well? (Done. Deserialization only.)

 - ~[ ] Add an optional `timezone` parameter to `AwareDateTime` to allow it to convert aware datetimes to a specific timezone. Apply on serialization as well?~ We can do that later on if someones needs it.

- [x] Add an optional `default_timezone` parameter to `AwareDateTime` to allow it to convert naive to aware datetimes (rather than fail).  Apply on serialization as well? (Done. Deserialization only.)

I think those parameters allow the user to recreate behaviours of old `DateTime` and `LocalDateTime`, with more flexibility and consistency.
