### ISSUE TITLE
Propouse add one_of in types

### ISSUE THREAD

**Issue by heckad** [marshmallow-code/marshmallow#1255]
I want to describe this schema
```
{
    "count": same_int>=0,
    "items": one_of(ItemSchema, HouseShemas, CountrySchema ...)
}
```
Concreate type should be couse when creating instanse of shema of this model.
For example 
```
houses = HouseShcema(many=True)
resp = RestfulRespounse(items_type=houses)
```
Fild name for choise type shuld be like name of var + `_type`. 
For example, the schema is
```
class RestfulRespounse(Shema):
     items = Nested(one_of(...))
```
then when create instance need write `res = RestfulRespounse(items_type=...)`. If you don`t specify type should raise an exception(I didn't come up with a type, you can offer in the comments)

**Comment by sloria** [comment]
We likely won't be adding this functionality to marshmallow core in the near future. Please take a look at https://github.com/marshmallow-code/marshmallow-oneofschema or https://github.com/Bachmann1234/marshmallow-polyfield .

**Comment by heckad** [comment]
This no question. This is my solution that I want to make. How do you like it?

**Comment by sloria** [comment]
As I mentioned above, we won't be adding this to marshmallow core.

**Comment by heckad** [comment]
Why? If this is not in the core, then the libraries for generating documentation will not support this type field at all, because authors don't want to add a new dependency.

**Comment by sloria** [comment]
We're not willing to take on the added code complexity at this time. Also, it's not clear what the ideal API looks like. Having used both marshmallow-oneofschema and marshmallow-polyfield, each has their own pros and cons.

**Comment by heckad** [comment]
For discusses this, I created this issue and propose my variant. Is there a list of pros and cons of the proposed solutions and what problems do you see in my?

**Comment by deckar01** [comment]
Previous discussion:

- https://github.com/marshmallow-code/marshmallow/issues/973
- https://github.com/marshmallow-code/apispec/pull/182
