### ISSUE TITLE
Document validate.Regexp's usage of re.match

### ISSUE THREAD

**Issue by macdonaldezra** [marshmallow-code/marshmallow#1285]
Hi,

Currently the Regexp validator uses the regex match function, which will only match the first indexed value in the string (unless you add the .* at the front of the regex). Using search instead would ensure that the entire length of the string is searched for a match and as far as I can tell would match the behavior users are looking for when using the validator. Thoughts?

Ezra

**Comment by sloria** [comment]
Not sure about this one. A quick review shows that [colander](https://github.com/Pylons/colander/blob/141263a3f61bed7c3af92c3a8d293ca7e10732e8/colander/__init__.py#L376), [wtforms](https://github.com/wtforms/wtforms/blob/277a437db29e36db3e211f47c93675eb544d6443/src/wtforms/validators.py#L332), and [cerberus](https://github.com/pyeve/cerberus/blob/c0f53a3535ac490a29119ff57b5eb3566d81bdfa/cerberus/validator.py#L1384) use `.match`, but [schema](https://github.com/keleshev/schema/blob/cfefb8cef9b9a07ed7fbc91cdbd99a9ffdf58bd2/schema.py#L217) and [django](https://github.com/django/django/blob/858cfd74e958b63e81657e5a9fc5f751c19e8192/django/core/validators.py#L58) use `.search`.

**Comment by macdonaldezra** [comment]
Thanks for looking into it!

The below stackoverflow response, describes the difference between the two functions a little better than I did... if you're interested:

https://stackoverflow.com/questions/180986/what-is-the-difference-between-re-search-and-re-match

**Comment by sloria** [comment]
I'm aware of the difference, but I'm not sure which is more intuitive for users of `validate.Regexp`. Given that both ways may be argued w/ equal validity, I don't think it's worth the breaking change to switch.

**Comment by macdonaldezra** [comment]
Fair point, probably not worth it then.

Would it be worth indicating in future documentation that match is the underlying function that is used, so users have a better idea of how to write their regular expressions?

**Comment by sloria** [comment]
Yes, we should definitely document this. PRs welcome!

**Comment by sloria** [comment]
Closed by #1308 . Thanks again!
