### ISSUE TITLE
Stop using name manging self.__schema in Nested class

### ISSUE THREAD

**Issue by robvdl** [marshmallow-code/marshmallow#1289]
I've got a case where I want to subclass Nested and do some special logic.

The bit that is getting in the way is that marshmallow has decided to use self.__schema with double underscores rather than a single one.

Using a single underscore is usually more than enough, it shows intent that this should be private, but in the case you do need to use an internal property when doing subclassing, it won't get in your way.

Now I have no choice but to copy half of the methods in this class into mine, which sort of defeats the purpose of subclassing. This is not ideal at all.

Really please stop using name mangling, it's not good in Python, it's just annoying. Just use single underscore, it's enough. Or use a cached_property decorator.

**Comment by robvdl** [comment]
Half of the reason it uses name mangling is that it is repeating the @cached_property decorator logic probably in multiple places which is not very dry. Why not make a decorator then:

```python
class cached_property(object):
    def __init__(self, func):
        self.func = func

    def __get__(self, obj, cls):
        if obj is None:
            return self
        value = obj.__dict__[self.func.__name__] = self.func(obj)
        return value

class Nested(Field):
    @cached_property
    def schema(self):
        # do your thing
```

**Comment by sloria** [comment]
I'm open to this; it's probably fine to just use a single underscore. 

I think the reason we don't use a cached_property decorator is that we only do this caching in this one place.

**Comment by robvdl** [comment]
Ah yeah that is fair enough, I should have actually looked how many times it was used.

I have seen people repeat the cached property "recipe" multiple times in other codebases, in which case I usually introduced @cached_property because it reads nice, pythonic

But if there is only one place I get that.

In the end I worked around it in my own codebase by using the mangled name to set the internal properties:

 self._Nested__schema = ....

Though that feels hacky, which was my reasoning for perfering a single underscore.

**Comment by deckar01** [comment]
The original commit doesn't seem to indicate that the name mangling was required.

https://github.com/marshmallow-code/marshmallow/commit/55f79801f29c554412a5dca8974a82de698a6f37

**Comment by robvdl** [comment]
A bit OT, but in case you're wondering why I am doing something crazy like this in the first place, subclassing Nested and needing to access it's internal properties in our codebase is that we have special subclasses of Nested, the field types ToOne('SomeResource') and ToMany('AnotherResource'). These link to other API resources not to other schemas. The idea came from TastyPie but we use SQLAlchemy not Django. We can still get to the schema through the resource and use 99% of the logic from the Nested base class.

Our API resources define which schema to use in their Meta class, but we were running into import loops when doing things in the field constructor, where the resource imports the schema, the schema imports the resource, the resource imports the schema, looping forever etc, etc.. our resources look something like this.

```python
class SomeResource(ModelResource):

    class Meta:
        model = SomeSQLAlchemyModel
        schema = SomeSchema
```

So we had to get a little clever, got it working in the end, but the only ugly bit was that mangled name which I had to set in our constructor like follows.

```python
self._Nested__schema = ...
```

It works but is a bit ugly, if the mangled name is fixed it would improve that bit in our code. I don't know how many other people would ever want to do this though, it is an edge case.

**Comment by sloria** [comment]
Sure, I think it'd be fine to change.  I used `__` originally because it was meant to be private as opposed to protected, which we use `_`  for in the rest of the codebase (e.g. `_serialize`, `_deserialize`). That said, the intention was to communicate, "users reeeally shouldn't be accessing this unless they know what they're doing". The intention was not to make it impossible. Python's name mangling always struck me as awkward...

**Comment by sloria** [comment]
Actually, would it make more sense to just add a setter for `schema`?

**Comment by sloria** [comment]
Using a setter should simplify implementation of e.g. polymorphic fields as well.

**Comment by robvdl** [comment]
@sloria, basically what I already posted to me is already perfect and very Pythonic. The idea is that this is a property that gets evaluated only once and then the cached value returned when called again. It's quite a common pattern in Python libraries, Django calls it @cached_property, Pyramid calls it @reify.

e.g. this is how it is now:

```python
    @property
    def schema(self):
        """The nested Schema object.
        .. versionchanged:: 1.0.0
            Renamed from `serializer` to `schema`
        """
        if not self.__schema:
            # Inherit context from parent.
            context = getattr(self.parent, "context", {})
            if isinstance(self.nested, SchemaABC):
                self.__schema = self.nested
                self.__schema.context.update(context)
            else:
                if isinstance(self.nested, type) and issubclass(self.nested, SchemaABC):
                    schema_class = self.nested
                elif not isinstance(self.nested, (str, bytes)):
                    raise ValueError(
                        "Nested fields must be passed a "
                        "Schema, not {}.".format(self.nested.__class__)
                    )
                elif self.nested == "self":
                    ret = self
                    while not isinstance(ret, SchemaABC):
                        ret = ret.parent
                    schema_class = ret.__class__
                else:
                    schema_class = class_registry.get_class(self.nested)
                self.__schema = schema_class(
                    many=self.many,
                    only=self.only,
                    exclude=self.exclude,
                    context=context,
                    load_only=self._nested_normalized_option("load_only"),
                    dump_only=self._nested_normalized_option("dump_only"),
                )
        return self.__schema
```

That just becomes:

```python
    @cached_property
    def schema(self):
        """The nested Schema object.
        .. versionchanged:: 1.0.0
            Renamed from `serializer` to `schema`
        """
        # Inherit context from parent.
        context = getattr(self.parent, "context", {})
        if isinstance(self.nested, SchemaABC):
            schema = self.nested
            schema.context.update(context)
        else:
            if isinstance(self.nested, type) and issubclass(self.nested, SchemaABC):
                schema_class = self.nested
            elif not isinstance(self.nested, (str, bytes)):
                raise ValueError(
                    "Nested fields must be passed a "
                    "Schema, not {}.".format(self.nested.__class__)
                )
            elif self.nested == "self":
                ret = self
                while not isinstance(ret, SchemaABC):
                    ret = ret.parent
                schema_class = ret.__class__
            else:
                schema_class = class_registry.get_class(self.nested)
            schema = schema_class(
                many=self.many,
                only=self.only,
                exclude=self.exclude,
                context=context,
                load_only=self._nested_normalized_option("load_only"),
                dump_only=self._nested_normalized_option("dump_only"),
            )
        return schema
```

What I have done is replace self.__schema with a local variable in that method just called schema and return it as normal, don't bother storing it as self.__schema and just decorate the method with @cached_property, easy.

I'm not sure what you mean with a setter, but to me the quick and easy fix is just to rename the double underscore to single underscore, the nicer fix however is to use a @cached_property decorator pattern which is re-usable.

**Comment by sloria** [comment]
Right. I guess my point is that we should just make `schema` settable instead of renaming `self.__schema` to `self._schema`. I only proposed using a setter because it's a smaller diff:

```diff
diff --git a/src/marshmallow/fields.py b/src/marshmallow/fields.py
index cf8b2b6..9cf211c 100644
--- a/src/marshmallow/fields.py
+++ b/src/marshmallow/fields.py
@@ -479,6 +479,10 @@ class Nested(Field):
                 )
         return self.__schema
 
+    @schema.setter
+    def schema(self, value):
+        self.__schema = value
+
     def _nested_normalized_option(self, option_name):
         nested_field = "%s." % self.name
         return [
```

I realize your cached_property implementation achieves the same goal. I don't have a strong preference either way.

**Comment by deckar01** [comment]
I am leaning toward renaming since it preserves the overall line count and doesn't increase the complexity.

**Comment by lafrech** [comment]
FWIW, werkzeug also provides `cached_property`.

Doc: https://werkzeug.palletsprojects.com/en/0.15.x/utils/#werkzeug.utils.cached_property
Code: https://github.com/pallets/werkzeug/blob/master/src/werkzeug/utils.py#L53

It is a bit different from the code in https://github.com/marshmallow-code/marshmallow/issues/1289#issuecomment-509044937 due to https://github.com/pallets/werkzeug/pull/617.

Since we only use this caching only once, we can indeed leave it as it is, I guess, although I don't object to using the common `cached_property` mechanism.

I'd change to `_schema` (single underscore). We could also add a setter but since the use case is marginal, letting the OP assign the single underscore variable is probably fine.

**Comment by sloria** [comment]
I'm not completely convinced that setting the schema should be private API. That said, changing to `_schema` is certainly the most conservative change, and it meets the OP's needs. We can always revisit if/how we implement the setter later.

**Comment by robvdl** [comment]
Yes I am happy with the convervative change of just renaming it to _schema
and does solve my problem, adding a setter seems overkill to me.

**Comment by lafrech** [comment]
FWIW, a `cached_property` decorator was added to Python 3.8: https://docs.python.org/3/library/functools.html.
