### ISSUE TITLE
Is there any way to update field‘s option  such as 'required', 'load_only' in subclass?

### ISSUE THREAD

**Issue by Bryant-Yang** [marshmallow-code/marshmallow#1296]
I found the following code works, but I'm not sure  it's a correct way.

eg. :

```
class UserSchema(Schema):
    user_id = fields.Integer()
    user_name = fields.String()
    # many other fields

class CreateUserSchema(UserSchema):
    def __init__(self):
        super().__init__(self)
        self.fields['user_name'].required = True
        self.fields['user_id'].required = True
        self.fields['user_id'].dump_only = True

class GetUserSchema(UserSchema):
    def __init__(self):
        super().__init__(self)
        self.fields['user_id'].required = True
        self.fields['user_name'].dump_only = True

```

When create user, user_name is required, and user_id is dump_only, and when get user info, the user_id is required, and for both load and dump.

I want to change require, dump_only ...,  without redefining the entire fields.

**Comment by lafrech** [comment]
You can use [class Meta options](https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.Schema.Meta) for this kind of things. But I don't see `required` in there.

In my APIs, I use the same schema but the ID for the PUT is in the URL, so it is injected in the view func (by webargs) as a path parameter. Therefore the id field is always dump_only.

**Comment by deckar01** [comment]
This topic came up yesterday in https://github.com/marshmallow-code/marshmallow/issues/1280#issuecomment-509678660. For simple fields without much customization I prefer overriding the field in the subclass. If the field had tons of custom parameters I did not want to repeat I would probably either make a custom field class or a factory function that let me create custom instances without duplicating the common attributes.

```py
# Override

class UserSchema(Schema):
    user_id = fields.Integer()
    user_name = fields.String()

class CreateUserSchema(UserSchema):
    user_id = fields.Integer(required=True)
    user_name = fields.String(required=True, dump_only=True)

class GetUserSchema(UserSchema):
    user_id = fields.Integer(required=True)
    user_name = fields.String(dump_only=True)
```

```py
# Custom field

class UserName(fields.String):
    def __init__(self, **kwargs):
        super().__init__(missing=get_random_username, validate=[username_length, allowed_characters, unique, no_profanity], **kwargs)

class UserSchema(Schema):
    user_id = fields.Integer()
    user_name = UserName()

class CreateUserSchema(UserSchema):
    user_id = fields.Integer(required=True)
    user_name = UserName(required=True, dump_only=True)

class GetUserSchema(UserSchema):
    user_id = fields.Integer(required=True)
    user_name = UserName(dump_only=True)
```

```py
# Field factory

def user_name(**kwargs):
    return fields.String(missing=get_random_username, validate=[username_length, allowed_characters, unique, no_profanity], **kwargs)

class UserSchema(Schema):
    user_id = fields.Integer()
    user_name = user_name()

class CreateUserSchema(UserSchema):
    user_id = fields.Integer(required=True)
    user_name = user_name(required=True, dump_only=True)

class GetUserSchema(UserSchema):
    user_id = fields.Integer(required=True)
    user_name = user_name(dump_only=True)
```

**Comment by heckad** [comment]
> You can use [class Meta options](https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.Schema.Meta) for this kind of things. But I don't see `required` in there.

I have proposed this feature in [this](https://github.com/marshmallow-code/marshmallow/issues/1280#issuecomment-509678660). Put your finger up if you think you need to add it.

[Here](https://github.com/marshmallow-code/marshmallow/pull/1297) is a pull request.
