### ISSUE TITLE
Dotted paths for fields do not work (eg data_key="foo.bar")

### ISSUE THREAD

**Issue by davidlouis** [marshmallow-code/marshmallow#1299]
Not entirely sure if bug or feature but I would expect to be able to use a dotted path as a data_key which would traverse the dictionary so I could load data from an nested location in source data.

See test with example of how I expected it to work in the following pull request:
https://github.com/marshmallow-code/marshmallow/pull/1298

**Comment by sloria** [comment]
Let's continue discussion on #1315
