### ISSUE TITLE
Serializing None with fields.Integer yields 0.0 float

### ISSUE THREAD

**Issue by kalasjocke** [marshmallow-code/marshmallow#13]
When serializing a `None` with a field specified as `Integer` you get a 0.0. `float` back. I think this is kind of strange, I think that you either shall get 0 back, or perhaps `None`. I will be happy to submit a patch after discussing a bit first.

I suspect that the behavior comes from this line, as `Integer` inherits from `Number`, which has the defaults of 0.0 in here:

https://github.com/sloria/marshmallow/blob/dev/marshmallow/fields.py#L348

What do you think @sloria? I would think that serializing None would yield None back.

**Comment by sloria** [comment]
Serializing None as an Integer to `0.0` is certainly a bug. It should return `None`. This should be true of all Number fields.

If you send a PR for this, I will gladly review and merge it!
