### ISSUE TITLE
Serialize/Deserialize to other formats

### ISSUE THREAD

**Issue by ecarreras** [marshmallow-code/marshmallow#130]
What do you think about the possibility of using other formats? such as XML? I don't like it but some APIs require this format.

Maybe a solution would be defining the [json_module](https://github.com/marshmallow-code/marshmallow/blob/30ec6b8f8efdd5d7ef38b81a18ef13c3ba54ebb3/marshmallow/schema.py#L112) attribute with a class which implements dumps and loads but for now I think is very linked with json.

If you or other users would like this feature I can try to work with it.

**Comment by sloria** [comment]
> Maybe a solution would be defining the json_module attribute with a class which implements dumps and loads...

Perhaps `json_module` is a misnomer, but you can use any object which implements `dumps` and `loads`. Maybe we'll rename it to `render_module` or something similar for the next release.

**Comment by traut** [comment]
+1 for this. Would love to have a pluggable serialization modules

**Comment by sloria** [comment]
@ecarreras @traut Does the `json_module` option meet your use case (ignoring the misnomer)? Can this issue be closed?

**Comment by ecarreras** [comment]
Yes for me

**Comment by sloria** [comment]
Thanks. Closing this for now.

**Comment by lafrech** [comment]
Just curious. Anyone managed to [|de]serialize XML with Marshmallow?

What would you use as a render module? One would need a piece of code to turn XML into Python objects and back. A quick search didn't bring much. Mostly old stuff.

**Edit**: Just found out about [xmltodict](https://github.com/martinblech/xmltodict). Sounds promising.
