### ISSUE TITLE
Validation Error When Using Pluck Field

### ISSUE THREAD

**Issue by a3huang** [marshmallow-code/marshmallow#1311]
I get a weird validation error when I try to deserialize an object using a nested schema. When I run the following:
```
from marshmallow import Schema, fields

class User(Schema):
    name = fields.String()
    book = fields.Pluck(Book, "name")

class Book(Schema):
    title = fields.String()
    number = fields.Number()

event = {
    "name": "Bob",
    "book": {"title": "My Book", "number": 1}
}

User().load(event)
```

I get:
```
ValidationError: {'book': {'name': ['Not a valid string.']}}
```

but what I'm confused about is that the value of the "title" field in the nested "book" object seems to be a valid string.

---

What I'm trying to do is to validate the following event coming in:
```
event = {
    "name": "Bob",
    "book": {"title": "My Book", "number": 1}
}
```

and then after validation, output it as:
```
event = {
    "name": "Bob",
    "title": "My Book"
}
```
i.e. with the "title" field "plucked" out.

I am running Python version 3.6.4 and Marshmallow version 3.0.0rc8.

**Comment by deckar01** [comment]
I was writing [this comment](https://github.com/marshmallow-code/marshmallow/pull/1298#issuecomment-513354502) when you posted this issue. The naming is confusing without the context of the issue that inspired it. `Pluck` describes the operation during serialization. This issue is a better place for that comment, so I will copy it here:

https://github.com/marshmallow-code/marshmallow/pull/1298#issuecomment-513354502

> My confusion with the behavior of `Pluck` concerns me a little. Currently `Pluck = flat -> nested -> flat`, but it is easily confused with this use case `nested -> flat -> nested`. `Pluck` describes the operation during serialization which is similar to `Function` and `Method`, but it is really the opposite operation during deserialization. Would it make sense to provide a field that performs the opposite operation? `Nest`?
> 
> ---
> 
> Side note: (way off topic) Some of the recent discussion about multiple schemas per model have got me thinking about what it would look like to decouple field mapping from schema declaration. You only ever need one deserialized data structure and one way to validate it, but there are potentially multiple ways you need to load into or dump from it (API versioning, nested views, etc).
> 
> <details>
> <summary>Example</summary>
> 
> ```py
> class AuthorSchema(Schema):
>     name = fields.Str()
> 
> class BookSchema(Schema):
>     title = fields.Str()
>     length = fields.Int()
>     author = fields.Nested(AuthorSchema)
> 
> class BookRequest(Interface):
>     length = Pluck('stats', 'length')
>     author = {'name': 'author'}
> 
> schema = UserSchema()
> interface = UserRequest()
> data = {'title': 'Example', 'author': 'Arthur', 'stats': {'length': 256}}
> schema.load({'username': 'example'}, interface)
> ```
> </details>

**Comment by sloria** [comment]
@a3huang Indeed, I think `Pluck` isn't what you want here. You could try the `Reach` recipe I posted [here](https://github.com/marshmallow-code/marshmallow/pull/1298#issuecomment-513314792).

```python
from marshmallow import Schema, fields
from marshmallow.utils import get_value, set_value


class Reach(fields.Field):
    def __init__(self, inner, path, **kwargs):
        super().__init__(**kwargs)
        self.inner = inner
        self.path = path

    def _deserialize(self, value, attr, data, **kwargs):
        val = get_value(value, self.path)
        return self.inner.deserialize(val, **kwargs)

    def _serialize(self, value, attr, obj, **kwargs):
        val = self.inner._serialize(value, attr, obj, **kwargs)
        ret = {}
        set_value(ret, self.path, val)
        return ret


class User(Schema):
    name = fields.String()
    title = Reach(fields.Str(), data_key="book", path="title")


event = {"name": "Bob", "book": {"title": "My Book", "number": 1}}
print(User().load(event))  # => {'name': 'Bob', 'title': 'My Book'}
```

@deckar01 I agree that `Pluck` is easily misunderstood. I improved the documentation a bit in #1314. Perhaps we could improve the naming to make it more clear, as well as provide a field for the reverse operation (`Nest`? `Deep`?) as you suggested. I'll make a new issue for us to discuss.
