### ISSUE TITLE
Add a way to generate a Schema from a dictionary

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#1312]
Generating schemas at runtime is a fairly common use case that I've run into a handful of times at this point ([webargs](https://github.com/marshmallow-code/webargs/blob/de061e037285fd08a42d73be95bc779f2a4e3c47/src/webargs/core.py#L50-L63), [environs](https://github.com/sloria/environs/blob/91b32a0e4bdf40281fab3978368164b27ce65e39/environs.py#L83-L95) , form builders...). 

It might make sense to incorporate this into marshmallow core.

## Proposed API

```python
>>> MyDynamicSchema = Schema.from_dict({"foo": fields.Str()})
>>> MyDynamicSchema
<class 'marshmallow.schema.GeneratedSchema'>
```

```python
class AlbumSchema(Schema):
     artist = fields.Nested(Schema.from_dict({"name": fields.Str()})
```

**Comment by sakshiaroras** [comment]
AttributeError: type object 'Schema' has no attribute 'from_dict'

i am importing Schema from marshmallow but facing issue while importing from_dict

**Comment by sloria** [comment]
Are you using marshmallow>=3.0.0?

**Comment by sakshiaroras** [comment]
No i am not using marshmallow 3
because it is not supported by python 2.6 . i have to use this only

**Comment by sloria** [comment]
.from_dict is only available on marshmallow 3. You can adapt the implementation in https://github.com/marshmallow-code/marshmallow/pull/1322 to your schema if you're stuck with marshmallow 2.

**Comment by sakshiaroras** [comment]
i have one field email.headers = json.dumps(self.email.unused_headers)
this i wan to serialise so that out put i get in dict()
defining class like
class HeaderSchema(Schema):
	Received = fields.Str(attribute="Recieved")
	X_Priority = fields.Str(attribute="X-Priority")

as nested :
headers = fields.Nested(HeaderSchema)
but its not refecting in out put

**Comment by sakshiaroras** [comment]
is there any way to handle elements like 
mail.headers = json.dumps(self.email.unused_headers)

**Comment by sloria** [comment]
It's a bit difficult to diagnose your issue without more detail. Can you provide a minimal script to reproduce the issue?

**Comment by sakshiaroras** [comment]
ok
class Email:
       email.headers = json.dumps(self.email.unused_headers)
schema:
class HeaderSchema(Schema):
         Received = fields.Str(attribute="Recieved")
         X_Priority = fields.Str(attribute="X-Priority")

class ESchema:
         headers = fields.Nested(HeaderSchema)

nested_json,errors = EmailSchema().dump(self.email,many='true')

**Comment by sloria** [comment]
That's still not a runnable script. Can you please post a minimal script that can be run on its own (i.e. `python repro.py`)?

**Comment by deckar01** [comment]
@sakshiaroras It looks like you are new to GitHub. You can use 3 back ticks \`\`\` before and after your code to preserve the white space. You can learn more about this by reading GitHub's [Mastering Markdown](https://guides.github.com/features/mastering-markdown/) guide.

You may also want to learn more about minimal repro cases to help get your problem solved more efficiently. I recommend StackOverflow's guide on the subject: [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

From what I can tell, your issue does not seem to be related to this closed issue. You might consider opening a new issue to avoid sending unrelated notifications to the original participants of this discussion.
