### ISSUE TITLE
Validate `missing`?

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#1318]
Follow-up from #1316:

Should we validate the `missing` value?

from @kissgyorgy :

> I'm not sure about this. Validating a value that is entered by the developer--not by clients--feels a bit odd. I don't think it's worth the performance penalty to validate something that should be validated by the developer.

I agree, but there are some use cases which make sense, for example, getting a value from a dynamic location, when that value come from a user input like a database, or an environment variable.

The other alternative would be to make it optional, for example with a `validate_missing` argument.

Here is what I'm currently doing to work around this:
```python

from flask.helpers import get_env
from marshmallow import fields, Schema
from marshmallow.validate import OneOf
from marshmallow.utils import missing

class ValidateMissingField(fields.Field):
    def __init__(self, field_cls, *, missing, **kwargs):
        super().__init__(**kwargs)
        self._wrapped_field = field_cls(**kwargs)
        self._missing = missing

    def serialize(self, *args, **kwargs):
        return self._wrapped_field.serialize(*args, **kwargs)

    def deserialize(self, *args, **kwargs):
        output = self._wrapped_field.deserialize(*args, **kwargs)
        if output is missing:
            output = self._missing() if callable(self._missing) else self._missing
            self._validate(output)
        # if not missing, it has been already validated
        return output


class ConfigSchema(Schema):
    env = ValidateMissingField(
        fields.String,
        attribute="ENV",
        validate=OneOf(["production", "development"]),
        missing=get_env,
    )
```

This is a lot of code for such a simple use case.

Also, I think what the following code does is not intuitive at all:
```python
    env = ValidateMissingStringField(
        attribute="ENV", missing=get_env, validate=OneOf(["production", "development"])
    )
```
because the `OneOf` validator is simply ignored. I expected it to work.

_Originally posted by @kissgyorgy in https://github.com/marshmallow-code/marshmallow/pull/1316#issuecomment-513575162_

**Comment by kissgyorgy** [comment]
I think at the very minimum, the current behavior should be documented and a `ValueError` should be raised when `missing` and `validate` are used together, [the same way as for `required` and `missing`](https://github.com/marshmallow-code/marshmallow/blob/d52c76a4c19a1cf90ed26eb1f8ad1b431c70c559/src/marshmallow/fields.py#L181-L182).

**Comment by sloria** [comment]
Yeah, I've no problem with documenting the current behavior. But raising an error when `missing` and `validate` are used together seems incorrect. They aren't mutually exclusive like required and missing are.

**Comment by kissgyorgy** [comment]
> They aren't mutually exclusive like required and missing are.

Validators will not run when `missing` is specified. I think this means they are mutually exclusive; You either use validators or specify `missing`.

**Comment by sloria** [comment]
Validators will still run as long as a value is provided, even if `missing` is specified. 

```python
from marshmallow import Schema, fields

class MySchema(Schema):
    foo = fields.Int(missing=42, validate=lambda n: n > 0)


MySchema().load({'foo': -1})  # marshmallow.exceptions.ValidationError: {'foo': ['Invalid value.']}
```

**Comment by kissgyorgy** [comment]
> Validators will still run as long as a value is provided, even if `missing` is specified.

Oh yes, you are right, sorry. I was fixated to the `missing` code path.

**Comment by edelooff** [comment]
An additional consideration: when validating default values for missing fields, the client will now potentially get an error on data they did not provide or have actual control over.

Ensuring that correct defaults are set is a real concern, but I'm not sure runtime input validation is the correct place for it.

**Comment by deckar01** [comment]
Providing the `missing` value in deserialized form was a feature added in 3.0.

https://github.com/marshmallow-code/marshmallow/issues/378

We have also been removing validation on serialized data recently for performance reasons, so adding validation to `missing` probably wouldn't be consistent. It should be possible to use a `@pre_load` hook.

```py
@preload
def set_defaults(self, data, **kwargs):
    data['env'] = data.get('env', None) or get_env()
    return data
```

https://marshmallow.readthedocs.io/en/3.0/extending.html#pre-processing-and-post-processing-methods

**Comment by sloria** [comment]
Yeah, `pre_load` seems a good place if you need to do validation on dynamically-computed defaults. `ValidationError`s raised there will get collected just like field errors.

Closing for now.

**Comment by kissgyorgy** [comment]
Thanks for the comments! Seems like validating in `@pre_load` will be good enough.

**Comment by kissgyorgy** [comment]
> ValidationErrors raised there will get collected just like field errors.

I tried this and it works perfectly and very simple, thanks!
