### ISSUE TITLE
Nested schemas render None strangely

### ISSUE THREAD

**Issue by nickretallack** [marshmallow-code/marshmallow#132]
This is very similar to [the other bug I reported](https://github.com/marshmallow-code/marshmallow/issues/64).  Turns out None renders strangely even when there's no `many=True` option specified.

```
from marshmallow import Schema, fields, pprint

class ChildSchema(Schema):
    name = fields.String()

class ParentSchema(Schema):
    child = fields.Nested(ChildSchema)

schema = ParentSchema()
result = schema.dump(object())
pprint(result.data)
```

Output:

```
{u'child': {u'name': u''}}
```

Expected:

```
{u'child': None}
```

**Comment by sloria** [comment]
Pass `allow_null=True` and you will get the expected result.

``` python
class ParentSchema(Schema):
    child = fields.Nested(ChildSchema, allow_null=True)
```

http://marshmallow.readthedocs.org/en/latest/api_reference.html#marshmallow.fields.Nested

**Comment by nickretallack** [comment]
Ok, that helps, but I still find the default behavior nonsensical.  Would anyone want it to do what it is doing?  I think allow_null should be the default behavior.

**Comment by sloria** [comment]
@nickretallack I will consider making `allow_null=True` the default in 2.0-a. Thanks for the suggestion.

**Comment by sloria** [comment]
Decided to change the default to `allow_null=True`. This will make `None` serialize to `None`.
