### ISSUE TITLE
how  to  marshmallow serialization elasticsearch-dsl-py

### ISSUE THREAD

**Issue by LiuG-lynx** [marshmallow-code/marshmallow#1325]
请问是否未来会对 elasticsearch 进行支持

**Comment by lafrech** [comment]
Reported as spam.

**Comment by deckar01** [comment]
Google translate says that is Chinese and means "Will you support elasticsearch in the future?".

We don't explicitly add support for 3rd party software like this. Marshmallow should be flexible enough for any data structure. If you think marshmallow is not compatible with elastic search, the issue you create should contain specific information about the data structures you are using and the marshmallow features that are failing.

**Comment by LiuG-lynx** [comment]
Sorry. My English is terrible
