### ISSUE TITLE
Field type is forced to identify with the first data

### ISSUE THREAD

**Issue by zjqzero** [marshmallow-code/marshmallow#1326]
```python
from marshmallow import Schema, fields

class DataSchema(Schema):
    class Meta:
        additional = ('a', 'b')

data = [{
    'a': 1,
    'b': 0.5
}, {
    'a': 0.5,
    'b': 0.33
}]

DataSchema(many=True).dump(data)[0] # [{'b': 0.5, 'a': 1}, {'b': 0.33, 'a': 0}]
# field "a" is identified as Integer type according to the type of the first "a", 
# so the second "a" got zero. Actually it should be float

data = [{
    'a': 0.5,
    'b': 0.33
},{
    'a': 1,
    'b': 0.5
}]

DataSchema(many=True).dump(data)[0] # [{'b': 0.33, 'a': 0.5}, {'b': 0.5, 'a': 1.0}]
```

to avoid the problem I should declare all fields explicitly, but not convenient if there are many fields.

**Comment by deckar01** [comment]
Python can tell the difference between a float and an int. You may need to enforce specific types before letting marshmallow infer fields from them.

```py
type(1) # <class 'int'>
type(1.0) # <class 'float'>
```

Inferring a generic type based on a polymorphic set of inputs is probably outside the scope of this feature. In your use case, treating an integer as a float could lose information/precision, so it is a decision that needs to be made explicitly after considering the implications for the allowed range of input.

**Comment by zjqzero** [comment]
ok. thank you.
