### ISSUE TITLE
Setting only fields after class instantiation does not run normalize options function

### ISSUE THREAD

**Issue by yradchen** [marshmallow-code/marshmallow#1334]
Running into issues when a schema is instantiated then properties, like exclude and only, are set afterwards.

For example;
When a schema is first instantiated with the following

```
class PlayerSchema(ModelSchema):
    age = fields.Integer()
   user = fields.nested(UserSchema)

# some api
PlayerSchema(only=('age', 'user.name'))
```
A method "self._normalize_nested_options()" is run from the init which sets nested fields. e.g. we will now only get age from the player and name from the user.

However if the only field is set after the fact;

```
schema = PlayerSchema()
schema.only = ('age', 'user.name')
```

self._normalize_nested_options() is NOT run and an error occurs;

AttributeError: "user.name" is not a valid field for ...

I found this to be very confusing because there are some api like context which the docs give an example of setting after the schema is instantiated.

Right from
https://marshmallow.readthedocs.io/en/3.0/custom_fields.html
```
class UserSchema(Schema):
    name = fields.String()
    # Function fields optionally receive context argument
    is_author = fields.Function(lambda user, context: user == context["blog"].author)
    likes_bikes = fields.Method("writes_about_bikes")

    def writes_about_bikes(self, user):
        return "bicycle" in self.context["blog"].title.lower()


schema = UserSchema()

user = User("Freddie Mercury", "fred@queen.com")
blog = Blog("Bicycle Blog", author=user)

schema.context = {"blog": blog}
result = schema.dump(user)
result["is_author"]  # => True
result["likes_bikes"]  # => True
```

I believe the .only field should either be underscored to denote it being a private method or it should function as intended. This also includes the exclude field which runs into issues if it is instantiated after with a list rather than a set.

**Comment by sloria** [comment]
Let's continue discussion on the linked issues above.
