### ISSUE TITLE
[regression 2.20] pass None for @validates_schema instead empty dictionary

### ISSUE THREAD

**Issue by sirkonst** [marshmallow-code/marshmallow#1345]
I found another regression after update from 2.19.5 to 2.20.1.

```python
from marshmallow import Schema, fields, validates_schema


class Bar(Schema):
    value = fields.String()

    @validates_schema
    def validate_schema(self, data: dict) -> None:
        assert isinstance(data, dict), type(data)  # before 2.20 data is {} after None


class Foo(Schema):
    bar = fields.Nested(Bar)


sch = Foo()

sch.validate({
    'bar': 'invalid',
})
```

**Comment by sloria** [comment]
Thank again for reporting. Would you like to investigate and send a PR?

**Comment by deckar01** [comment]
I'm surprised `validate_schema()` gets called considering the structure of the input is invalid.

**Comment by sirkonst** [comment]
@deckar01 - yes it's strange but I think it have a sense in some cases. And method was not called if using @validates_schema(skip_on_field_errors=True).

**Comment by codebind-luna** [comment]
@sloria is anyone working on this? If not I would like to investigate on this

**Comment by sloria** [comment]
I don't think anyone is working on this. Would be glad if you sent a PR, @codebind-luna !

**Comment by codebind-luna** [comment]
@sloria I have started looking into it. I hope soon will raise a PR

**Comment by sloria** [comment]
@codebind-luna Are you still looking into this? No worries if not--just let us know and someone else can pick it up.

**Comment by LukeMarlin** [comment]
Hi there @sloria. I wanted to give this a look, and using version 3.8.0, `validate_schema` seems to have changed quite a bit. First, `skip_on_field_errors` is `True` by default now, so I changed the sample code to this:

```python
from marshmallow import Schema, fields, validates_schema


class Bar(Schema):
    value = fields.String()

    @validates_schema(skip_on_field_errors=False)
    def validate_schema(self, data: dict, *args, **kwargs) -> None:
        assert isinstance(data, dict), type(data)  # before 2.20 data is {} after None


class Foo(Schema):
    bar = fields.Nested(Bar)


sch = Foo()

sch.validate({
    'bar': 'invalid',
})
```

And as far as I could see, data is indeed `dict` again, so I guess this issue does not exist anymore, right?

**Comment by sloria** [comment]
Correct. This is no longer an issue on marshmallow 3.

Closing, since marshmallow 2 is EOL.
