### ISSUE TITLE
SomeField(many=True) vs List(SomeField())

### ISSUE THREAD

**Issue by jtrakk** [marshmallow-code/marshmallow#1346]
I've always used `List(SomeField())` and haven't really understood the purpose of `SomeField(many=True)`. Is there a guideline for when I'd want to use `SomeField(many=True)` instead of  `List(SomeField())`? Thanks.

**Comment by sloria** [comment]
See https://github.com/marshmallow-code/marshmallow/issues/779 ; we are considering deprecating `Nested(many=True)` in favor of `List(Nested())`. It used to be `Nested(many=True)` had better error reporting behavior and was more performant, but in marshmallow 3 they will be in parity with each other.

**Comment by jtrakk** [comment]
> See #779 ; we are considering deprecating Nested(many=True) in favor of List(Nested()). 

I see. What does that mean for the future of `Integer(many=True)` and other fields?
