### ISSUE TITLE
Deprecate the Select field

### ISSUE THREAD

**Issue by philtay** [marshmallow-code/marshmallow#135]
I propose to deprecate the `Select` field in favor of a `OneOf` validator. Reasons:
- The `Select` field is just a validator masked as a field. It doesn't perform any real (de)serialization.
- It works only with basic data types. The field's `choices` argument can't be a list of "complex" objects (e.g. dates).
- Currently there is no built-in way to validate a field against a fixed set of values.
- A convenience method to associate choices to labels (e.g. to populate a form select field) would be quite useful. The validator could implement it in a generic way (i.e. not tied to any data type in particular).

Please let me know your opinion.

**Comment by sloria** [comment]
+1 to adding a `OneOf` validator. 

I'm not sure about the point about handling "complex" objects. As long a class implements `__contains__` (which `date` does) , the the `in` operator will work. Am I missing something?

A `OneOf` validator is more flexible than the `Select` field, so we can probably deprecate `Select` for 2.0-a.

**Comment by philtay** [comment]
@sloria I meant something else, but it doesn't matter anymore now that we have the `OneOf` validator.

Do you want a `ContainsOnly` validator?

http://docs.pylonsproject.org/projects/colander/en/latest/api.html#colander.ContainsOnly

It's the natural extension of `OneOf` to sequences. Colander implements it using the set's method `issubset`, but I want to make it more generic (i.e. without the requirement of hashable items). I need it especially in combination with the `List` field.

Another thing. I'm starting to think we should decouple (de)serialization logic and validation logic as a general rule. Fields like `Url` and `Email` are just `String` with a validator. In general the `ValidatedField` class should go away.

**Comment by sloria** [comment]
Sure. I think a `ContainsOnly` validator would be useful.

> I'm starting to think we should decouple (de)serialization logic and validation logic as a general rule. 

Agreed. That's a good rule of thumb moving forward. Though I probably won't remove `Url` and `Email` very soon, as it would break a lot of existing applications. Also, the `validate.URL` and `validate.Email` validators only make sense with `String` fields, so at the very least, those fields serve as a convenient shorthand.

**Comment by philtay** [comment]
Ok, I'll implement `ContainsOnly` ASAP.

**Comment by davidism** [comment]
Rather than separate validators for `OneOf` and `ContainsOnly`, one `Choices` validator that takes a `multi=True` argument seems more straightforward.

**Comment by philtay** [comment]
My idea is to subclass `OneOf` and override `__call__`. I prefer to not put too much logic in a single validator. They must be very robust and thus very easy to debug. Anyway your idea is certainly doable. @sloria please let us know your opinion
