### ISSUE TITLE
question: Regexp only matches first character?

### ISSUE THREAD

**Issue by f0cker** [marshmallow-code/marshmallow#1353]
Since validate.Regexp appears to only match the first character of a string (re.match), what is the correct way to ensure the whole string conforms to a regex?

Hope this is possible. Thanks.

**Comment by lafrech** [comment]
FWIW, related to https://github.com/marshmallow-code/marshmallow/issues/1285.

**Comment by sloria** [comment]
You can use a custom validator that uses `re.search`.

```python
from marshmallow import validate, ValidationError


class StringContains(validate.Regexp):
    default_message = 'String does not contain expected pattern.'

    def __call__(self, value):
        if self.regex.search(value):
            raise ValidationError(self._format_error(value))
        return value
```

Edit: fix typo with _format_error.

**Comment by f0cker** [comment]
Thanks for that, just for completeness if anyone else looks at this 'format_error' should be '_format_error'

It turns out what I needed was something that would reject any special characters etc., using a whitelist approach, so re.search didn't work for me. I used the below instead, with the regex \W in this case to check for any characters not matching \w which is equivalent to [a-zA-Z0-9_]:

```
class StringContains(validate.Regexp):
    default_message = "String does not contain expected pattern."

    def __call__(self, value):
        if len(self.regex.findall(value)) > 0:
            raise ValidationError(self._format_error(value))
            return value
```

**Comment by sloria** [comment]
Fixed the typo. Glad you got it working.
