### ISSUE TITLE
Help Wanted: AttributeError: 'list' object has no attribute 'data' on schema.dump(model).data in 3.0.0

### ISSUE THREAD

**Issue by phalbert** [marshmallow-code/marshmallow#1358]
Deserializing a model in marshmallow `3.0.0` seems to have changed. I have been using `v2.19.5` with `schema.dump(model).data`. However, this no longer works and the following error is now thrown:

```python
AttributeError: 'list' object has no attribute 'data'
```
What is the alternative then?

**Comment by lafrech** [comment]
Please read the *upgrade to 3.0* section of the docs.

You don't need to access `.data` attribute, `dump` already returns the data.

**Comment by phalbert** [comment]
thanks @lafrech
