### ISSUE TITLE
Allow blank for all string types (url, email, ...) on dumping too

### ISSUE THREAD

**Issue by rastikerdar** [marshmallow-code/marshmallow#136]
`allow_blank` works only on load for `fields.URL` or `fields.Email` not dump:

``` python
from marshmallow import Schema, fields
class Test(Schema):
    url = fields.URL(allow_blank=True)

# '2.0.0-dev'
Test().dump({'url': ''})
```

returns:
`MarshalResult(data={u'url': None}, errors={u'url': [u'"" is not a valid URL.']})`

I think it should return:
`MarshalResult(data={u'url': u''}, errors={})`

**Comment by sloria** [comment]
+1. I think you are correct about the desired behavior here. Will fix this.

**Comment by lucasvo** [comment]
@sloria This doesn't seem to be fixed. Was this change reverted? I tried to find any evidence of this in the master branch but I can't find the changes in this commit or any evidence of allow_blank as valid argument for validators.Email

**Comment by lucasvo** [comment]
I just found this PR: https://github.com/marshmallow-code/marshmallow/issues/167 

But the change to remove allow_blank is missing from the changelog here: http://marshmallow.readthedocs.io/en/latest/changelog.html#changelog - would probably be helpful. (I was on 2.3 and used allow_blank extensively, this now just failed silently).

**Comment by erichaus** [comment]
Any update on this? I just hit it with latest in July 2021 where an empty string throws error despite allow_blank=True

**Comment by deckar01** [comment]
It looks like `allow_blank` was removed while 2.0 was still in alpha. https://github.com/marshmallow-code/marshmallow/issues/167

https://marshmallow.readthedocs.io/en/2.x-line/search.html?q=allow_blank

**Comment by erichaus** [comment]
@deckar01 nice find, so what's the way to tell validator to accept empty string? write own validator?

**Comment by deckar01** [comment]
Marshmallow 3.x no longer validates on dump, so the original issue no longer applies. https://github.com/marshmallow-code/marshmallow/issues/713 is a similar use case, and includes some examples that could work around this in marshmallow 2.x.

```py
class OptionalUrl(fields.Url):
    def _serialize(self, value, attr, obj):
        if value == '':
            return ''
        return super()._serialize(value, attr, obj)
```
