### ISSUE TITLE
many is passed through to pre/post_dump/load method even when pass_many=False

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#1368]
>Here's a sample project showing my issue:
https://github.com/phrfpeixoto/marshmallow_bug/tree/master

> It works ok o 2.x Branch. I'm holding to that version for now.

_Originally posted by @phrfpeixoto in https://github.com/marshmallow-code/marshmallow/issues/1150#issuecomment-523160159_

**Comment by sloria** [comment]
I'm not sure that this is a bug. In v3, `many` *always* gets passed to `post_dump` methods, and it will be equal to the value of `many` upon calling `dump`.

`pass_many` controls whether your post_dump method receives the original input list or if it handles single items. It does *not* control whether or not the `many` argument passed.

https://marshmallow.readthedocs.io/en/latest/extending.html#passing-many

@phrfpeixoto What use case is broken for you? Is it fixed by adding `**kwargs` to your post_dump method, as suggested [here](https://marshmallow.readthedocs.io/en/latest/upgrading.html#decorated-methods-and-handle-error-receive-many-and-partial)?

---

Sidenote: perhaps `pass_collection` would be a better name than `pass_many`. We should consider this for 4.0.

**Comment by lafrech** [comment]
I'm not sure I have the whole picture.

In the diff I propose in https://github.com/marshmallow-code/marshmallow/issues/1150#issuecomment-525496932, my idea was that since we iterate on the input to pass it to the decorated processor one item at a time, it made sense, intuitively, to pass many=False on each call.

I tried it and it broke no test but I didn't investigate any further.

**Comment by sloria** [comment]
It's debatable whether `many` should equal the "dump-time" value of `many` or always be `False` when `pass_many=False`. I think the current behavior is fine, tbh.

I think the confusion in the OP was that `pass_many=False` would cause `many` to not be passed to the method (which was the 2.x behavior).

**Comment by lafrech** [comment]
OK, I don't know and don't mind either way. I have no example of case where the decorated processor actually uses `many`.

Since it is swallowed by `**kwargs`, it shouldn't make any difference.

The issue is people who upgrade without reading the upgrading docs first (like my colleague just did, just like I would have done myself as well) get the error about `many` and get confused.

**Comment by sloria** [comment]
Yeah. I think renaming `pass_many` to `pass_collection` might clarify things a bit.

**Comment by phrfpeixoto** [comment]
Thanks for replying, both of you.

> pass_many controls whether your post_dump method receives the original input list or if it handles single items. It does not control whether or not the many argument passed.

That's what the documentation says. It's at least confusing:

>By default, pre- and post-processing methods receive one object/datum at a time, transparently handling the many parameter passed to the schema at runtime.
> 
> In cases where your pre- and post-processing methods need to receive the input collection when many=True, add pass_many=True to the method decorators. The method will receive the input data (which may be a single datum or a collection) and the boolean value of many.

That last sentence suggests that _the boolean value_ is passed when `pass_many` is `True`.
It should say something like "... datum or a collection) along a `True` value on the `many` parameter."

On top of that, the fact the the parameter are called `pass_many` and `many` really does not help. Strongly suggest that `many` should NOT be passed. I do agree that always passing the parameter is more consistent.

I also agree it should be renamed to something like `pass_collection` or even better, have different decorators and different processor signatures, like `@post_dump_many`

**Comment by sloria** [comment]
We decided in https://github.com/marshmallow-code/marshmallow/pull/1034#issuecomment-436556833 to move away from conditionally passing arguments based on the decorator arguments and that users should add `**kwargs` to PPDL (pre/post-dump/load) methods for forward-compatibility.

I agree that the docs you quoted are misleading; looks like we forgot to update that part. PRs welcome =)

**Comment by phrfpeixoto** [comment]
Also, this current behaviour suggests this should not crash. Didn't try, though.

```python
@post_load(pass_many=False)
def post_load(data, many):
    if many:
        assert type(data) is not list, "Data should not be a collection, since pass_many is False"
    return data
...

schema.dump([{
    "name": "Ann"
},{
    "name": "Joe"
}], many=True)
```

UPDATE:
Tried it, and it indeed does not fail. Consistent, but not really beautiful.

**Comment by phrfpeixoto** [comment]
> PRs welcome =)

Will do that once I get home from work.

**Comment by phrfpeixoto** [comment]
Posted PR #1370 for improving the documentation.

**Comment by sloria** [comment]
Thanks for the docs PR. I think this can be closed now.

When we add type annotations to the decorators, the signatures will become even more clear.
