### ISSUE TITLE
schema.validate returns errors for the example in the documentation

### ISSUE THREAD

**Issue by mdkess** [marshmallow-code/marshmallow#1372]
In the documentation, there is the following example:

```python
from datetime import date
from marshmallow import Schema, fields, pprint

class ArtistSchema(Schema):
    name = fields.Str()

class AlbumSchema(Schema):
    title = fields.Str()
    release_date = fields.Date()
    artist = fields.Nested(ArtistSchema())

bowie = dict(name="David Bowie")
album = dict(artist=bowie, title="Hunky Dory", release_date=date(1971, 12, 17))

schema = AlbumSchema()
result = schema.dump(album)
pprint(result, indent=2)
# { 'artist': {'name': 'David Bowie'},
#   'release_date': '1971-12-17',
#   'title': 'Hunky Dory'}
```

However, if we add the line `print(schema.validate(album))` we get that the `release_date` is not a valid date: `{'release_date': ['Not a valid date.']}`

What is the expected behavior here?

This seems related to https://github.com/marshmallow-code/marshmallow/issues/656

I'm using Python 3.7 with Marshmallow 3.0.1.

**Comment by lafrech** [comment]
Validation is only meant to be applied to serialized data, during a load.

Marshmallow does not validate object data before dump.

You get this error because the `Date` field is expecting a serialized date.
