### ISSUE TITLE
Smart way of getting all SQLAlchemy Fields

### ISSUE THREAD

**Issue by cancan101** [marshmallow-code/marshmallow#138]
Is there some trick to set the `fields` in the `Meta` class to all of the columns in a [SQLAlchemy model](http://marshmallow.readthedocs.org/en/latest/examples.html#quotes-api-flask-sqlalchemy)?

Right now I am using [get_columns](http://sqlalchemy-utils.readthedocs.org/en/latest/orm_helpers.html#get-columns) like this:

```
    class Meta:
        additional = get_columns(Model).keys()
```

but this doesn't seem ideal or the very least would be cool to be included in marshmallow.

**Comment by sloria** [comment]
@cancan101 I think your solution is fine. Marshmallow will not have first-class support for SQLalchemy (or any other ORM).

That said, if we decide to implement something like the `add_fields` option discussed in https://github.com/marshmallow-code/marshmallow/issues/139#issuecomment-73638482 , you would be able to generate fields from a Model, like so:

``` python
from marshmallow import Schema

# function adapted from lima docs: https://lima.readthedocs.org/en/latest/advanced.html
def fields_for_model(model):
    result = {}
    for name, col in model.__mapper__.columns.items():
        field_class = Schema.TYPE_MAPPING[col.type.python_type]
        result[name] = field_class()
    return result

class MySchema(Schema):
    class Meta:
        add_fields = fields_for_model(MyModel)
```

**Comment by sloria** [comment]
I've added the `include` class Meta option, which means you can now do:

``` python
class MySchema(Schema):
    class Meta:
        # use fields_for_model from previous comment
        include = fields_for_model(MyModel)
```
