### ISSUE TITLE
The `strict` parameter for fields.Integer is not documented

### ISSUE THREAD

**Issue by jceresini** [marshmallow-code/marshmallow#1389]
The strict parameter for fields.Integer defaults to False, which was a surprise because I thought all fields defaulted to strict=True. That may belong in a separate issue, but either way, the documentation doesn't include any details about  the `strict` parameter:

https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.fields.Integer

https://marshmallow.readthedocs.io/en/stable/_modules/marshmallow/fields.html#Integer

**Comment by sloria** [comment]
Good catch. Would you like to send a PR? =)
