### ISSUE TITLE
Support field names that aren't valid Python identifiers

### ISSUE THREAD

**Issue by nickretallack** [marshmallow-code/marshmallow#139]
I want to support a field called "from", but I can't do this in marshmallow because it would cause a syntax error:

``` python
class MySchema(Schema):
    from = fields.Nested(OtherSchema, attribute="my_attribute")
```

This got me thinking -- marshmallow is kind of backwards, isn't it?  The field that comes in from the outside world is the one that has to be specified as a valid Python identifier, and the field that you're actually going to work with in your code is specified as a string.  Shouldn't they be swapped?  I'm sure other folks are going to want to parse in or write out a value that isn't a valid Python identifier sometimes.

``` python
class MySchema(Schema):
    my_attribute = fields.Nested(OtherSchema, field="from")
```

This could even be made backward compatible with existing Marshmallow stuff, like so:
- If neither "field" nor "attribute" are specified, the field and attribute values are both the same as the lvalue, so there's no issue.
- If "attribute" is specified, the lvalue is used for "field"
- if "field" is specified, the lvalue is used for "attribute"

Probably harder for you to actually implement this sorta thing though, but it's a thought.

**Comment by sloria** [comment]
Another possible solution would be to allow adding fields in a dict. Something like:

``` python
class MySchema(Schema):
    class Meta:
        add_fields = {'from': fields.Nested(OtherSchema, attribute='my_attribute')
```

Would have to think harder about what to name the option, but I believe this can be implemented without adding too much complexity.

**Comment by sloria** [comment]
The `include` option has been added in https://github.com/marshmallow-code/marshmallow/commit/41b8ed395fd39eb17e75bd73608824bfd2bd901e . You can now do:

``` python
class MySchema(Schema):
    class Meta:
        include = {
            'from': fields.Nested(OtherSchema, attribute="my_attribute")
        }
```

**Comment by taion** [comment]
BTW, this is very helpful for anybody who wants to follow the JSON API recommendations of dasherizing all attribute names as well.

**Comment by retr0h** [comment]
Is there a way to disallow fields which are  python identifiers when allowing unknown keys?

```
class OrderLabelSchema(marshmallow.Schema):
    class Meta:
        unknown = marshmallow.INCLUDE

    discriminator = marshmallow.fields.Str(
        required=True, validate=marshmallow.validate.OneOf(base.TYPES)
    )

class OrderSchema(marshmallow.Schema):
    class Meta:                                                                                                                                                    fields = (
            'created_at',
            'updated_at',
            'id',
            'labels',
            'status',
        )

    labels = marshmallow.fields.Nested(OrderLabelSchema)

    status = marshmallow.fields.Str(
        validate=marshmallow.validate.OneOf(STATUSES)
    )
```

I ended up writing my own validator, but I was thinking this might not be the correct approach:

```
    @marshmallow.pre_load
    def validate_keys(self, data, **kwargs):
        errors = {
            k: ['Invalid identifier provided.']
            for k, _ in data.items()
            if not k.isidentifier()
        }
        if errors:
            raise marshmallow.exceptions.ValidationError(errors)

        return data
```
