### ISSUE TITLE
Validation before serializtion difficult when using `data_key`

### ISSUE THREAD

**Issue by ramshaw888** [marshmallow-code/marshmallow#1393]
I'm in the process of upgrading to marshmallow 3 and I'm having some difficulty with this change "Remove Dump Validation" #1304. 

`docs/upgrading.rst` recommends doing a `load` before `dump` to ensure it's valid:
```
    class WidgetSchema(Schema):
        created_at = fields.DateTime()

    # 3.x
    WidgetSchema().dump(invalid_data)
    # AttributeError: 'str' object has no attribute 'isoformat'
     # Instead, validate before dumping
    schema = WidgetSchema()
    try:
        widget = schema.load(invalid_data)
    except ValidationError:
        print("handle errors...")
    else:
        dumped = schema.dump(widget)
```

The problem I'm having is that `load` expects a "serialized" object. This works in the given example since the serialized and deserialized objects have symmetrical keys. When using the `data_key` field option this fails.

For example, if `WidgetSchema` was defined as:
```
    class WidgetSchema(Schema):
        created_at = fields.DateTime(data_key='createdAt')
```
the above `schema.load` example would fail with an "Unknown field" error on both valid and invalid inputs since `schema.load` will always look for a value in the `createdAt` key.

The best workaround I can come up with is something like this:
```
try:
    serialized = schema.dump(widget)
except AttributeError:
    # handle invalid
else:
    try:
        re_deserialised = schema.load(serialized)
    except ValidationError:
        # handle invalid again
    else:
        # Valid!
```
which seems kind of inelegant...

So I guess I'm looking for a way to validate a "deserialized" python object easily. Any help appreciated!

**Comment by lafrech** [comment]
Validation on dump is something that was never really supported IIUC and we decided to remove it completely. The rationale is that objects are supposed to be valid. It's a design choice.

Indeed the recommendation in the docs is kinda wrong. Your workaround is the first that came to my mind.

**Comment by sloria** [comment]
Validating deserialized objects isn't supported out-of-box. Serializing your object before passing it to `schema.validate` or `schema.load` is your best option.
