### ISSUE TITLE
Attribute name in fields

### ISSUE THREAD

**Issue by thekantian** [marshmallow-code/marshmallow#140]
So I'm having an issue with using an attribute name in a field definition - seems like the expected behavior for getting the item using that attribute works, but then in the serialized data dict instead of ending up at the fields's name, they key in the serialized data for that field is the attribute name.

tldr, i'm expecting:

```
class MySchema(Schema):
    cancellation_policy = fields.String(
          required=False, attribute='default_cancellation_policy')

input = { 'default_cancellation_policy': 'foo'}
schema = MySchema()
output = schema.dump(input).data
output = { 'cancellation_policy': 'foo'}
```

but i get instead:

```
output = { 'default_cancellation_policy': 'foo'}
```

Anyone seen this or have any leads for a workaround? Thanks!

**Comment by sloria** [comment]
@thekantian I am unable to reproduce this. I've copied your example, and I get the expected output. What version of marshmallow are you using?

**Comment by thekantian** [comment]
@sloria sorry for the delayed response here. I am on version 1.2.1.

For now, I've added a property to the object I am serializing so that I do not need to use the "attribute" kwarg for my field.
