### ISSUE TITLE
Implicit field creation type

### ISSUE THREAD

**Issue by russelldavies** [marshmallow-code/marshmallow#141]
In the [Implicit Field Creation](http://marshmallow.readthedocs.org/en/latest/quickstart.html#refactoring-implicit-field-creation) section of the docs, it states:

> Note that name will be automatically formatted as a String and created_at will be formatted as a DateTime.

However, if looking at the `fields` attribute on the instantiated object, they are all of type `fields.Field`. There doesn't seem to be any expression matching, like `email` and `e-mail` gets mapped to `fields.Email`, in the code either so I'm presuming that the statement is erroneous and should be removed.

**Comment by davidism** [comment]
Works for me.  The auto-detection happens when dumping an object, not when instantiating the schema.  See the `update_fields` argument.  Maybe the Field instances you observed are placeholders.

**Comment by russelldavies** [comment]
Ah, I understand now. I thought the text was implying that there is some type detection, and validation, during serialization (not type detection during deserialization). Thanks.
