### ISSUE TITLE
serialize values of aggregate results from sqlalchemy using marshmallow

### ISSUE THREAD

**Issue by jibinmathew69** [marshmallow-code/marshmallow#1412]
I am performing a `count()` and `group_by()` operation on a table as follows:

    db.session.query(func.count(Tag.name), Tag.name).group_by(Tag.name).limit(limit)

and serialize it using marshmallow:

    class TagSchema(ma.ModelSchema):
        class Meta:
            model = Tag
        name = fields.String(validate=validate.Length(min=1))

which gives me result as :

    [{"name" : "asdf"},{"name":"qwer"}]

but I don't see the count value, how should I update the schema to get count value in the output.

**Comment by sloria** [comment]
You'll need to add a field for the count

```python
class TaggedObjectSchema(Schema):
    name = fields.Pluck(TagSchema, "name", many=True)
    # rename to whatever you're labeling the count in your query
    count = fields.Int(dump_only=True)
```

**Comment by jibinmathew69** [comment]
`name = fields.Pluck(TagSchema, "name", many=True)`

Throws error, says `{keyError}'name'`

**Comment by sloria** [comment]
See https://github.com/marshmallow-code/marshmallow/issues/1413#issuecomment-533797716
