### ISSUE TITLE
Convert single key object into array using marshmallow schema

### ISSUE THREAD

**Issue by jibinmathew69** [marshmallow-code/marshmallow#1413]
I have a table which has only 1 column,and the marshmallow schema looks like this:

    class TagSchema(ma.ModelSchema):

        class Meta:
            from .models import Tag
            model = Tag
        name = fields.String(validate=validate.Length(min=1))

right now on dump it gives result as:

    [{"name":"asdf"},{"name":"qwer"}]
I want it as `{"name" : ["asdf","qwer"]}`

**Comment by sloria** [comment]
You can use the [Pluck](https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.fields.Pluck) field for this.

Something like

```python
class TaggedObjectSchema(Schema):
    name = fields.Pluck(TagSchema, "name", many=True)
```

**Comment by jibinmathew69** [comment]
`name = fields.Pluck(TagSchema, "name", many=True)`

Throws error, says `{keyError}'name'`

is this the right way to invoke the dump:

```
tag_schema = TaggedObjectSchema(many=True)
result = tag_schema.dump(tags)
```

**Comment by sloria** [comment]
The input data need to match the shape of the schema, so you'll need to wrap your query set like so:

```python
from types import SimpleNamespace

from marshmallow import Schema, fields, pre_dump


class TagSchema(Schema):
    name = fields.Str()


class TaggedObjectQuerysetSchema(Schema):
    name = fields.Pluck(TagSchema, "name", many=True)
    count = fields.Int()


mock_queryset = [SimpleNamespace(name="foo"), SimpleNamespace(name="bar")]

print(
    TaggedObjectQuerysetSchema().dump(
        {"name": mock_queryset, "count": len(mock_queryset)}
    )
)
# {'count': 2, 'name': ['foo', 'bar']}
```

Alternatively, you could use `pre_load` to do this in the schema

```python
class TaggedObjectQuerysetSchema2(Schema):
    name = fields.Pluck(TagSchema, "name", many=True)
    count = fields.Int()

    @pre_dump
    def wrap_queryset(self, obj, **kwargs):
        return {"name": obj, "count": len(obj)}


print(TaggedObjectQuerysetSchema2().dump(mock_queryset))
# {'count': 2, 'name': ['foo', 'bar']}
```

**Comment by sloria** [comment]
Closing for now. Feel free to comment with follow-up questions.
