### ISSUE TITLE
@validates_schema doesn't return '_schema' key when ValidationError receives a dict parameter in versions > 3.x.  Feature or bug?

### ISSUE THREAD

**Issue by mamalos** [marshmallow-code/marshmallow#1414]
Hi there,

Sorry for the long subject, I couldn't think of something shorter and descriptive enough...:)

Since **marshmallow** v.3.x, **marshmallow** integration with **cornice** has been a bit cumbersome, so I'm trying to resolve the issues that have been risen.

One of these issues is that some code fails in cornice when a **ValidationError** is raised from within a `@validates_schema` decorator and instead of passing a string when calling **ValidationError**, a `dict` is passed.

More specifically let's consider the following code:
```python
from marshmallow import Schema, validates_schema

class UserSchema(Schema):  
     email = fields.Str(required=True)  

     @validates_schema  
     def validate_email(self, data, **kwargs):  
         if len(data['email']) < 15:  
             raise ValidationError({'email': 'Email should be greater than 15'})

_user = {'email': 'a@c', 'name': 'babakis'}
UserSchema().validate(_user)
```

When using marshmallow v.2.20.5 the above returns:
```{'_schema': [{'email': 'Email should be greater than 15'}]}```

whereas when using marshmallow v.3.2  it returns:
```{'email': 'Email should be greater than 15'}```

This might be sort-of documented in recent documentation, where it mentions that `If a dict, the keys are subitems and the values are error messages.`, but since I'm not exactly sure if that's the meaning of the documentation, and since this breaks some cornice tests, I would like to verify
if this difference is expected behaviour in order to change the relevant code in cornice.

Thanks.

**Comment by sloria** [comment]
> whereas when using marshmallow v.3.2 it returns:
> {'email': 'Email should be greater than 15'}

This is the expected and desired behavior. `_schema` is reserved for schema-level validation errors, not field-level errors. See https://github.com/marshmallow-code/marshmallow/pull/1026 for more context on this change.

**Comment by sloria** [comment]
Closing for now. Feel free follow up with further questions.

**Comment by mamalos** [comment]
> Closing for now. Feel free follow up with further questions.

Thanks a lot, will follow up if needed!
