### ISSUE TITLE
List(Pluck()) raises while Pluck(many=True) works

### ISSUE THREAD

**Issue by altendky** [marshmallow-code/marshmallow#1424]
For completeness, below is my example where I noticed this but a PR with at least a test added is on it's way and I'll see if I can figure out how to fix it.  This was broken by https://github.com/marshmallow-code/marshmallow/commit/a6fd2b6f759c1b99275f949b7663295f85cc7f27.

https://repl.it/@altendky/UnluckyInfiniteUnits-5
```python3
import attr
import marshmallow


@attr.s
class Member:
    name = attr.ib()
    other = attr.ib()


class MemberSchema(marshmallow.Schema):
    name = marshmallow.fields.String()
    other = marshmallow.fields.String()


@attr.s
class Holder:
    members = attr.ib()

class HolderSchema(marshmallow.Schema):
    members = marshmallow.fields.List(marshmallow.fields.Pluck(MemberSchema, field_name='name'))
    # members = marshmallow.fields.Pluck(MemberSchema, field_name='name', many=True)


def main():
    my_holder = Holder(
        members=[
            Member(name='name_0', other='other_0'),
            Member(name='name_1', other='other_1'),
        ],
    )

    dumped = HolderSchema().dump(my_holder)
    print(dumped)

main()
```
```python-traceback
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 42, in main
    dumped = HolderSchema().dump(my_holder)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/marshmallow/schema.py", line 553, in dump
    result = self._serialize(processed_obj, many=many)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/marshmallow/schema.py", line 517, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/marshmallow/fields.py", line 325, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/marshmallow/fields.py", line 695, in _serialize
    return self.inner._serialize(value, attr, obj, many=True, **kwargs)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/marshmallow/fields.py", line 635, in _serialize
    return ret[self._field_data_key]
TypeError: list indices must be integers or slices, not str
```
`requirements.txt`
```
attrs==19.2.0
marshmallow==3.2.1
```

**Comment by deckar01** [comment]
If `Pluck` has this problem, then so will any user subclasses of `Nested` that need to reach into the data `super` returns. I don't really like the idea of this implementation detail affecting the API required to subclass `Nested`. On the other hand, you already had to probe `self.many` in `_serialize()`/`_deserialize()` before this change and that isn't really documented anywhere.

**Comment by altendky** [comment]
Is your concern related to my patch that adds a check against a passed parameter?  Or to the existing code?  I think the latter but wanted to make sure I am understanding.

**Comment by deckar01** [comment]
Existing code. I didn't want to start making more work for anyone until I got some feedback about the effect my changes had on the API for subclassing `Nested`.

I suspect it's acceptable in which case your PR has the right idea, but we might want to consider just reverting the optimization. It was kind of the shotgun optimization approach. We might be better off tackling the overhead of `Schema._do_load` piecemeal, which would improve the performance of all calls and not just this special case.

**Comment by deckar01** [comment]
@sloria @lafrech What do you think about this?

I think the options are:

1. Require subclasses of `Nested` to handle the `many` kwarg in de/serialize (#1425)
    1. Document the interface
    1. Ignore it like `self.many` caveats are already ignored
2. Roll #1306 back

**Comment by deckar01** [comment]
Technically the `many` argument is already in the API docs for `Nested`, so I think 1.ii would be fine. I'm not sure we need dedicated docs explaining how to subclass the builtin fields.

On the other hand, forcing this constraint on subclasses was not intentional, and it seems like it should be possible to optimize this path without API changes.

**Comment by lafrech** [comment]
I agree.

If we find a better way to improve the perfs, great. Meanwhile, I think 1.ii is reasonable. To subclass a field, a user would copy the signature of the field and notice `many` is passed as kwargs. I don't think this deserves a red flag in the docs.

And I don't think we need to revert #1306. Subclassing `Nested` may be tricky but it can be achieved. No use case is blocked.

#1425 is on the right track.

**Comment by lafrech** [comment]
We might want to mention the `many` parameter in `Nested._deserialize` docstring, along with `partial`.

**Comment by lafrech** [comment]
I'm trying to port umongo to marshmallow 3 and I just got pawned by the `many` optim.

In umongo, `EmbeddedField` inhertits from `Nested`. And in umongo, fields accept deserialized data. We're thinking or doing this in marshmallow as well: #1415.

Consider the case of a `List(Nested(Inner()))`. When deserializing, that field may receive a list of either serialized or deserialized data, perhaps even a mixed list. You can't do the `isinstance` check in `_deserialize` since at this stage you have a collection, not an instance, and schema is not capable of loading a mixed collection. You need to deal with each element one by one.

I might be able to workaround this by adding more logic into umongo but I wanted to point this as a potential limitation if/when implementing #1415.

**Comment by lafrech** [comment]
I did workaround this by overriding `List._serialize` and `List._deserialize` but this comes with a bit of duplication.

https://github.com/Scille/umongo/pull/154/commits/19fa7eb05b09cec464e916c7a3c10be7adc412b5

This makes me lean towards removing the optim. We could make it an opt-in, but the benefit from the optim might not be worth the extended API surface.

> We might be better off tackling the overhead of `Schema._do_load` piecemeal, which would improve the performance of all calls and not just this special case.

Yes, improving the perf there would be ideal.
