### ISSUE TITLE
Question about Nested

### ISSUE THREAD

**Issue by mayku00** [marshmallow-code/marshmallow#1435]
I have two Schemas:

class SonSchema(Schema):
	paramter1 = fields.String()
	parameter2 = fields.String()

class FatherSchema(Schema):
	son = fields.Nested(SonSchema)

	
Then I trie to load some json into the FatherSchema:

schema = FatherSchema().load(response)

What I need is depending on a external param, I want to make some validation in the SonSchema, for example if extertal param = True then parameter1 needs to be in the response (with a @validation_schema).

Any ideas??

**Comment by deckar01** [comment]
What do you mean by "external param"?

**Comment by mayku00** [comment]
Sorry, let me explain, I'm using load() function to validate an api response in json.
by external param I mean an param that its not depending on the schema.

Example:
Depending on "param" in my request I expect in the response that I'm validating with marshmallow, some expecific behaviour

If I send "param"=BIG to my service, the respone that I want to validate its in the SonSchema.paramter1==BIG

To validate I call FatherSchema().load(response), and I dont know if there any way to validate in the SonSchema (Nested in the FatherSchema) that parameter1 have some value depending on my "external param"

Regards

**Comment by deckar01** [comment]
You have a value in the request data that you don't want to keep in the serialized output, but that you do want to check in the validation method, is that right?

**Comment by mayku00** [comment]
yeah its right

**Comment by deckar01** [comment]
Check out the `pass_original=True` feature of `@validates_schema`.  It should allow you to peek at the raw value during validation without including it in your final output.

https://marshmallow.readthedocs.io/en/stable/extending.html?highlight=pass_original#using-original-input-data

**Comment by mayku00** [comment]
Hi,
It's not working beacause I need to use a variable external to the class. I was trying with the constructor but without sucess

¿any other idea?

**Comment by deckar01** [comment]
I'm not sure what class you are talking about. `pass_original` should include keys that don't have fields in the schema. Can you provide an example of what your data looks like?

**Comment by mayku00** [comment]
Hi,

This its my code:

```py
from marshmallow import Schema, fields, ValidationError

class TestSchema(Schema):
    parametro1 = fields.String()

class ErrorSchema(Schema):
    date = fields.String(required=True)
    status = fields.Integer(required=True)
    error_code = fields.String(required=True)
    developer_message = fields.String(required=True)
    more_info = fields.String()
    test = fields.Nested(TestSchema,many=true,required=True)
```

EXECUTION EXAMPLE

```py
custom_param="no_custom"
example_json = {"date": "2019-10-30T09:02:11", "status": 404, "error_code": "ERROR-00003",
                "developer_message": "No product available", "test": [{"parametro1": "custom"}]}
error = ErrorSchema().validate(example_json)
print(error)
```


What I want to do it's validate that all TestSchema.parametro1 == custom_param, I can not find the way to use custom_param inside the TestSchema


Regards

**Comment by deckar01** [comment]
So, the value is not in the request data (`example_json`), but in some other variable? Where does that variable get its value in your app? When does the value change?

**Comment by deckar01** [comment]
This may be related to #1361.

**Comment by mayku00** [comment]
Hi,
I find a way finally jeje, 
thanks!
