### ISSUE TITLE
Duplicate chunk in src/marshmallow/schema.py

### ISSUE THREAD

**Issue by huornlmj** [marshmallow-code/marshmallow#1436]
Sonarqube flags duplication in src/marshmallow/schema.py.
Lines 1200 to 1203 are duplicated in the same if statement at lines 1213 to 1216.
Is this intentional ?

**Comment by deckar01** [comment]
It looks like a recent change normalized that interface. We can simplify the condition to avoid the duplicate blocks.

https://github.com/marshmallow-code/marshmallow/commit/35f6f4c286241e7dec1fcbeb9912b02b3b4887ba

@huornlmj If you are interested in opening a PR feel free to ping me for review. If you are busy I will pick it up when I get a chance.

**Comment by lafrech** [comment]
Fixed in #1444.
