### ISSUE TITLE
Potential logically dead code in error_store.py

### ISSUE THREAD

**Issue by huornlmj** [marshmallow-code/marshmallow#1440]
According to a recent Coverity scan, there is potential logically dead code beginning at [error_store.py line 34.](https://github.com/marshmallow-code/marshmallow/blob/dev/src/marshmallow/error_store.py#L34).  Is this correct or is the flow part of some defensive error control? 

```
34    if not errors1:
35        return errors2
  	**cond_cannot_single: Condition errors2, taking true branch. Now the value of errors2 cannot be equal to 0.
  	cond_true: Condition errors2, taking true branch. The truth value of errors2 must be true.
  	cond_types: Condition errors2, taking true branch. Now the type of errors2 cannot be any of undefined and null.**
36    if not errors2:
37        return errors1
38    if isinstance(errors1, list):
39        if isinstance(errors2, list):
40            return errors1 + errors2
41        if isinstance(errors2, dict):
42            return dict(errors2, **{SCHEMA: merge_errors(errors1, errors2.get(SCHEMA))})
43        return errors1 + [errors2]
44    if isinstance(errors1, dict):
45        if isinstance(errors2, list):
46            return dict(errors1, **{SCHEMA: merge_errors(errors1.get(SCHEMA), errors2)})
47        if isinstance(errors2, dict):
48            errors = dict(errors1)
49            for key, val in errors2.items():
50                if key in errors:
51                    errors[key] = merge_errors(errors[key], val)
52                else:
53                    errors[key] = val
54            return errors
55        return dict(errors1, **{SCHEMA: merge_errors(errors1.get(SCHEMA), errors2)})
56    if isinstance(errors2, list):

**cannot_single: At condition errors2, the value of errors2 cannot be equal to 0.
  	truth: At condition errors2, the truth value of errors2 must be true.
  	possible_types: At condition errors2, the type of errors2 cannot be any of undefined and null.
  	dead_error_condition: The condition errors2 must be true.
CID 1406512: Logically dead code (DEADCODE)
dead_error_line: Execution cannot reach the expression errors1 inside this statement: return errors2 ? {errors1} ....** 
```
![dead-code](https://user-images.githubusercontent.com/28444739/67959559-dec9ca00-fbf0-11e9-8e70-0608abd02f0f.jpg)

**Comment by deckar01** [comment]
It looks like the issue is really on line 57. `if errors2` will always be true due to line 36-37.

**Comment by edelooff** [comment]
Looking at the code, it seems that line 57 there should indeed drop the ternary expression and be simply `return [errors1] + errors2`

The conditional at line 36 already establishes that `errors2` is logically true (or we'd never get where we are), so testing it again on line 57 is redundant. And there is no code that modify `errors2` in the interim. My guess is that this is a check left over from a refactor.

**Comment by lafrech** [comment]
It is something I introduced myself when I added the function in b2e5a7da74d2f62a4d3694a43bc31248eb14be24.

I didn't write it from scratch, though. I adapted a PR. Perhaps it made sense in the original code.

> Looking at the code, it seems that line 57 there should indeed drop the ternary expression and be simply `return [errors1] + errors2`

Yes. Thanks @huornlmj for reporting. Would you like to send a fix?

**Comment by huornlmj** [comment]
I'm just happy to identify it.  I'll leave the work to someone closer to the code.

**Comment by lafrech** [comment]
No pb. Thanks for reporting.

PR: #1443
