### ISSUE TITLE
Old documentation links are dead

### ISSUE THREAD

**Issue by lovasoa** [marshmallow-code/marshmallow#1441]
The documentation URLs have changed and all old links now return a 404 status.

Example: `https://marshmallow.readthedocs.io/en/3.0/api_reference.html`

Maybe there should be a redirection from the old URLs to the new ones, since there are existing links to the old URLs...

**Comment by sloria** [comment]
https://marshmallow.readthedocs.io/en/3.0 redirects to https://marshmallow.readthedocs.io/en/stable , but AFAIK there's not a good way to redirect all paths within a version to a different version. This is a limitation imposed by ReadTheDocs, I'm afraid.

**Comment by lovasoa** [comment]
Maybe you can just upload a small html file that contains a meta redirect tag ?

**Comment by sloria** [comment]
Ah, just discovered that you can use `$rest` with Exact Redirects: https://docs.readthedocs.io/en/latest/user-defined-redirects.html#exact-redirects

**Comment by sloria** [comment]
All 3.0 docs should redirect to stable now.
