### ISSUE TITLE
How to raise an exception if json parameter is not having value (empty string) ? 

### ISSUE THREAD

**Issue by vvksahoo** [marshmallow-code/marshmallow#1447]
I want to raise an exception if my input json will look like :
{
	"username":"user",
	"password": ""	
}
if i am passing password as null then i want to raise an exception . May i know how does it handle by marshmallow .
I dont want to check explicitly like below : 
------------------------
request_jsn = request.get_json()
if 'password' in request_jsn.keys() :
 if request_jsn['password'] : 
   password = request_jsn['password']
------------------------------
from marshmallow import Schema, fields
class UserSchema(Schema):
    username = fields.String(required=True)
    password = fields.String(required=True)

    def post(self):

        if not request.json:
            return jsonify( {'msg':"Unsupported media type,Requests must be JSON",'code': 415})
        try:
           request_jsn =  Schema().load(request.get_json())
        except ValidationError as e:
            return jsonify(error_dict(current_request_id(), str(e), 400))

**Comment by deckar01** [comment]
This looks similar to #713

Adding a length validator with min set to 1 should raise an error when the field is an empty string.

https://marshmallow.readthedocs.io/en/stable/quickstart.html#validation

**Comment by vvksahoo** [comment]
Thanks for your reply . what if the filed is an Integer type , and passing null value ?  its giving error.

**Comment by deckar01** [comment]
I assume by "null" integer you mean zero. Setting min to 1 on a `Range` validator should work for integer fields.

https://marshmallow.readthedocs.io/en/stable/api_reference.html#module-marshmallow.validate

**Comment by vvksahoo** [comment]
Thanks a lot . It worked for me. 
name = fields.Str(required=True,allow_none=False)
this way its not working . Do you have any idea about allow_none=False?

**Comment by deckar01** [comment]
Could you provide a complete example of what you are trying to do and what the output is? allow_none=False should behave according to the documentation.

https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.fields.Field

**Comment by lafrech** [comment]
Answered on SO : https://stackoverflow.com/questions/58692350/how-to-raise-an-exception-if-json-parameter-is-not-having-value-empty-string

@deckar01 was spot on: 
> Adding a length validator with min set to 1 should raise an error when the field is an empty string.
