### ISSUE TITLE
Use Abstract Base Classes to define FieldABC and SchemaABC

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow#1449]
https://docs.python.org/3/library/abc.html

https://stackoverflow.com/questions/44315961/when-to-use-raise-notimplementederror/44316506#44316506

**Comment by sloria** [comment]
I'm fine with this. I think I avoided ABCs long ago to avoid metaclass conflicts with `SchemaMeta`, but it's probably not an issue any more.

**Comment by lafrech** [comment]
BTW the docstring is outdated. There is no core.py anymore.
