### ISSUE TITLE
Bug / Feature request: allow DateTime object be deserialized if trailing Z indicates UTC

### ISSUE THREAD

**Issue by mirko** [marshmallow-code/marshmallow#1451]
Currently a string like `2008-01-01T00:00:00.000Z` - generated from JavaScript - via `toISOString()` is considered invalid by the `DateTime()` definition within marshmallow.

That is, because `datetime.fromisoformat()` does only support timezones declared in the format of `+AB:CD` (for UTC that would `+00:00`).

While it is clear, that the trailing `Z` indicating UTC is valid according to ISO8601, the maintainer of the datetime package (currently) refuses to add supporting that format of TZ-indication.

There's a lengthy discussion about that: https://discuss.python.org/t/parse-z-timezone-suffix-in-datetime/2220

Putting that aside, I'd really be in favour of marshmallow accepting that part of ISO8601 and not consider above format as invalid.

**Comment by lafrech** [comment]
The discussion says that fromisoformat is not meant to parse datetimes in ISO format, but only to parse datetimes output by datetime.isoformat.

> As of today, if you are not parsing the output of a dt.isoformat() call or a string guaranteed to be in an equivalent format, you should not be using datetime.fromisoformat, and if it works it only does so by accident.

Looks like we should not be using fromisoformat and we should either use something else or do everything we can to ensure the input data is coerced into something that could have been output by isoformat. Bummer.

**Comment by mirko** [comment]
My apologies for the noise: this bug report is invalid.

1) datetime.fromisoformat() is not even used by marshmallow for validation, but a custom regexp which does indeed take the trailing 'Z' into account
2) I fed marshmallow with a date*time*-string while the schema-field was of type `Date()`. Apparently I draw wrong conclusions, as this happened to work with a previous version of marshmallow (just upgraded and hit that)

**Comment by lafrech** [comment]
I didn't even check we actually used fromisoformat...

But thanks for the link. I learned something today.
