### ISSUE TITLE
Intellisense autocomplete plugin or similiar

### ISSUE THREAD

**Issue by DavidM42** [marshmallow-code/marshmallow#1454]
I think it would be a really nice tool/addition for this library if a plugin for vscode allowed devs to have intellisense auto complete on loaded dicts. Standard python intellisense sadly doesn't know about the static defined dict keys of marshmallow loaded objects so it's easy to misspell keys.
As I don't know anything about vscode plugins and linting/autocomplete/... I still wanted to throw the idea into the room if anyone is interested

**Comment by sloria** [comment]
I think https://github.com/marshmallow-code/marshmallow/issues/1411 might address this. Let's continue discussion there
