### ISSUE TITLE
How do we validate a dynamic json schema in python flask marshmallow?

### ISSUE THREAD

**Issue by vvksahoo** [marshmallow-code/marshmallow#1455]
In db there is a table called X. X having json column in it and it has some data. In one of my post api call passing josn input like:

INPUT JSON:
{
'x_id':1;
'json':{
      'id':1,
      'name':'jack',
      'address':'Newyork'
       }
}
X-table:
id:1
json:{
     'id':2,
      'name':'some',
       'address':'somewhere'

 }

i want to validate input 'json' keyword schema with x-table json schema based on x_id. x-table json schema will vary so against that json schema my api json schema will validate.

Some example:
if API input json:
{
'x_id':1;
'json':{
     'id':1,
     'Country':'USA',
     'address':'Newyork'
      }
}
And in db X-table look like:
id:1
json:{
    'id':2,
     'name':'some',
      'address':'somewhere'

   }
In this scenarios i want to throw error saying that 'Country' parameter is in-valid and 'name' parameter is missing . 
Second Example: 
if API input json:
{
'x_id':2;
'json':{
'id':1,
'Country':'USA',
'address':'Newyork'
}
}
And in db X-table look like:
id:2
json:{
'id':1,
'Country':'some',
'address':'somewhere'

}
For this case i wont get any error message . Look like both json schema same here. 
So how to do this using marshmallow?

**Comment by lafrech** [comment]
I don't understand the question.

Also, please edit your message to make it more readable.

Use backticks to summon the syntax highlighter:

    ```python
    Python code goes here
    ```

**Comment by sloria** [comment]
Closing this, as it has gone stale. Feel free to re-open if this is still relevant.
