### ISSUE TITLE
How to Pluck multiple values from the same object?

### ISSUE THREAD

**Issue by ThiefMaster** [marshmallow-code/marshmallow#1456]
I have this schema:

```python
class EditingRevisionFileSchema(Schema):
    uuid = fields.Pluck(FileSchema, 'uuid', attribute='file')
    filename = fields.Pluck(FileSchema, 'filename', attribute='file')
    size = fields.Pluck(FileSchema, 'size', attribute='file')
    content_type = fields.Pluck(FileSchema, 'content_type', attribute='file')
    download_url = fields.Constant('#')  # TODO
```

But it fails because I'm using `file` in multiple places.

> ValueError: The attribute argument for one or more fields collides with another field's name or attribute argument. Check the following field names and attribute arguments: [u'file']

Is there a solution for this besides using `uuid = Function(lambda x: x.file.uuid)` etc.?

**Comment by ThiefMaster** [comment]
OK, looks like I can just do this

```python
    uuid = fields.String(attribute='file.uuid')
    filename = fields.String(attribute='file.filename')
    size = fields.String(attribute='file.size')
    content_type = fields.String(attribute='file.content_type')
```

So I guess there's no need to Pluck here at all.

**Comment by jrevah** [comment]
Any idea why pluck wouldn't do this? I'm having trouble understanding why you would ever use pluck.
