### ISSUE TITLE
Can `loads` return a dict with all the properties of the schema ?

### ISSUE THREAD

**Issue by sirrocco** [marshmallow-code/marshmallow#146]
Hi,

Is there a way to return a dict that contains all the properties from the schema, regardless of if the property was present in the JSON input? 

Example:

```
class JobEventSchema(Schema):
    name = fields.String(required=True)
    id = fields.Integer()
```

If the json is: {"name": "Some Name"}, I get back a dict that contains only the name key. 
I'd like for it to also have the id field even if it's the default value of 0 (or whatever default value I set it to).

I couldn't find anything like this in the documentation - is it possible? 

Thanks.

**Comment by sloria** [comment]
@sirrocco 2.0-a (which is currently on the `dev` branch) has a `missing` parameter, which is the value that is used in deserialization when a field is missing in the input data.

There is also a workaround described in https://github.com/marshmallow-code/marshmallow/issues/45#issuecomment-68168663 which described how you can mimic the behavior of `missing` in pre-2.0 versions.

Does this meet your use case?

**Comment by sirrocco** [comment]
Yes, that looks like what I need. Thanks.
