### ISSUE TITLE
missing parameter is not working 

### ISSUE THREAD

**Issue by sakshiaroras** [marshmallow-code/marshmallow#1460]
I am trying to deserialise data with schema as :

```py
class EmailSchema(Schema):
    attachment_id = fields.Int(missing=0)
    recipient_id = fields.Int(missing=0)
    return_path_recipient_id = fields.Int(missing = 0)
    reply_to_recipient_id = fields.Int(missing = 0)
  ```

Now when i am dumping it as 

```py
nested_json, errors = EmailSchema().dump(pars_email)
```

here pars_email is email object which contains data as {attachment_id = null, recipient_id=1,..}
here i am defining missing = 0 but still i am getting null 

I am using marshmallow version 2.20.7

**Comment by lafrech** [comment]
`dump` is meant to serialize, use `load` to deserialize.
`missing` is used on loading, `default` on dumping

|operation|function|argument|
|-|-|-|
| deserialization | load | missing |
| serialization | dump | default |

**Comment by sakshiaroras** [comment]
if i am doing dump and i will use default it will work ?

**Comment by deckar01** [comment]
> **default** – If set, this value will be used during serialization if the input value is missing.

https://marshmallow.readthedocs.io/en/2.x-line/api_reference.html#module-marshmallow.fields

**Comment by sakshiaroras** [comment]
in_nod = fields.Boolean(default=False)
i tried even this is not working

**Comment by lafrech** [comment]
Again, please provide a minimal reproducible example.

https://stackoverflow.com/help/minimal-reproducible-example

In other words, show us your code.

**Comment by sakshiaroras** [comment]
i cant recreate minimal code . but full code is at https://github.com/Infoblox-CTO/cyberint-malspam-processor/pull/110 .

**Comment by deckar01** [comment]
That repo appears to be private. Do you mean you can't reproduce the issue when running a simple example, or you can't write a simple example?

**Comment by sakshiaroras** [comment]
i cant reproduce the issue as i am getting class objects to be dump in schema . You also cant help me as i am not able to evident issue . so you can close it
