### ISSUE TITLE
How to validate boolean value in request json ?

### ISSUE THREAD

**Issue by vvksahoo** [marshmallow-code/marshmallow#1464]
I want to validate request json where some fields are Boolean value . So i  am looking ,is there any validate() which will make sure Boolean fields are not empty in request json body.
example :
user_id = fields.Integer(required=True, validate=validate.Range(min=0,
                                                                      error="user_id is invalid, it should be a positive integer.")) 
Above i am using Range to make sure that user_id should not be empty in request body for that i am sending appropriate error message also "user_id is invalid, it should be a positive integer."

So i have one more filed called 'is_joined" basically it will take a Boolean value .

**Comment by lafrech** [comment]
What about

```py
is_joined`= ma.fields.Boolean(required=True)
```

?

**Comment by vvksahoo** [comment]
In request json we can pass boolean value as string also right ?
like:
{
"is_join":"true"
}
or
{
"is_json":true
}

**Comment by lafrech** [comment]
Yes, and I think it should work.

https://github.com/marshmallow-code/marshmallow/blob/e06e9ca3aac1b7389eda488b0627340c5cb3782d/src/marshmallow/fields.py#L1042-L1091

**Comment by vvksahoo** [comment]
Yeah , its working man thanks a lot.
