### ISSUE TITLE
Pandas-like orient parameter?

### ISSUE THREAD

**Issue by smallstepman** [marshmallow-code/marshmallow#1465]
Hi! Awesome work, thanks for putting you time into this ting, it serves me very well.

I'd like to know if marshmallow can output my data in different shape (kinda like [**orient** parameter](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_json.html) in pandas)?
 e.g., following code (I'm using marshmallow+flask+sqlalchemy):
```python
data = SQLAModel.query.all()
data_schema = DataSchema(many=True)
return jsonify(data_schema.dump(data))
```
will output:
```json
[
  { 
    "a" : "asd",
    "b" : "bsd"
  },
  { 
    "a" : "das",
    "b" : "sdb"
  }
]
```

whereas I'd like to have:

```json
{
    "a": ["asd", "das"],
    "b": ["bsd", "sdb"]
}
```

I skimmed over documentation but didn't find built-in way to do it.
Is there marshmallow'ic way to do it or should I stick to manipulating python objects to produce my result?

**EDIT**: [seems like skimming the docs doesnt serve me at all](https://marshmallow.readthedocs.io/en/stable/extending.html)

nevertheless, I still think it's a cool idea 😃

**Comment by ruskimarcin** [comment]
[seems like skimming over docs doesn't serve me](https://marshmallow.readthedocs.io/en/stable/extending.html)

nevertheless, I still think it's a cool idea 😃

**Comment by deckar01** [comment]
`@post_load` would be a good place to put this kind of transformation. If this data wasn't a list of schemas at the top level, you could make a custom field to encapsulate this transformation.
