### ISSUE TITLE
Schema.from_dict cannot be pickled

### ISSUE THREAD

**Issue by smith-kyle** [marshmallow-code/marshmallow#1468]
The schema returned from `Schema.from_dict` cannot be pickled because of the way that the schema class is created

Example:
```python
pickle.dumps(Schema.from_dict({ 'a': fields.Integer() }))
_pickle.PicklingError: Can't pickle <class 'marshmallow.schema.GeneratedSchema'>: attribute lookup GeneratedSchema on marshmallow.schema failed
```

Is this something that should be addressed in marshmallow? If so, I'm happy to help

**Comment by lafrech** [comment]
I guess so. Does this also affect `deepcopy`?

**Comment by smith-kyle** [comment]
`copy.deepcopy` and `copy.copy` work fine

**Comment by sloria** [comment]
Closing, since we decided in https://github.com/marshmallow-code/marshmallow/pull/1469 that this isn't something we should handle
