### ISSUE TITLE
How to Validate ENUM field using marshmallow ?

### ISSUE THREAD

**Issue by vvksahoo** [marshmallow-code/marshmallow#1470]
I have been using marshmallow for API's request json validation ,Its a great Library . Now i came across a situation where i have to validate ENUM filed . I have a ENUM field called 'gender' which will expect 3 values ('Male', 'Female', 'Others'). So here how do i add this validation field to Schema. Below i have mentioned one example .

from marshmallow import Schema, fields, validate
class UserDetails(Schema):
    user_id = fields.Integer(required=True, validate=validate.Range(min=0,
                                                                  error="user_id is invalid, it should be a positive integer."))
   user_name = fields.String(required=True, validate=validate.Length(min=1, error="Field should not 
                                                 be empty."))

  user_gender = ?

Thanks in Advanced .

**Comment by lafrech** [comment]
See the docs:

https://marshmallow.readthedocs.io/en/stable/quickstart.html#validation

```py
permission = fields.Str(validate=validate.OneOf(["read", "write", "admin"]))
```

**Comment by vvksahoo** [comment]
Thanks a lot @lafrech
