### ISSUE TITLE
Add error to nested schema

### ISSUE THREAD

**Issue by adamrt** [marshmallow-code/marshmallow#1472]
I have the following nested schemas. The parent schema validates that there aren't duplicate children. This works decently as I can show the error at the top of the form. But this form can grow to 150-200 children, so if you see the error at the top or bottom of the form its not very useful if the child is the 100th element down.

Is there a way for the `ParentSchema.validate_object()` to add/append an error to a specific child element? Then I could highlight the child that is at fault.

I've been hunting this down for a while and couldn't find anything in the existing issues. I may be using the wrong terminology, and if so, sorry for the new ticket.

```py
from marshmallow import Schema, fields, validates_schema, ValidationError

class ChildSchema(Schema):
    id = fields.Int(required=True)
    sku = fields.Str()

class ParentSchema(Schema):
    children = fields.Nested(ChildSchema, many=True)

    @validates_schema
    def validate_object(self, data, **kwargs):
        existing = []
        for child in data["children"]:
            if child["sku"] in existing:
                raise ValidationError(f"Duplicate SKU #{child['sku']}.")
            existing.append(child["sku"])
```

**Comment by lafrech** [comment]
I don't see a simple way to do that I could recommend.

IMHO, this is an interface issue. I would let the validator return all duplicate fields (original + duplicates), not only the first duplicate. And I'd let the interface highlight all of them. But I understand this may mean more work in the interface.
