### ISSUE TITLE
Pass context to schema if class name provided as string

### ISSUE THREAD

**Issue by Finn10111** [marshmallow-code/marshmallow#1473]
I am using the context of a schema to decide if I want to wrap the data or not. It looks something like this:
```
    @post_dump(pass_many=True)
    def wrap_with_envelope(self, data, many, **kwargs):
        if 'noenvelope' in self.context and self.context['noenvelope']:
            return data
        else:
            key = self.opts.plural_name if many else self.opts.name
            return {key: data}
```

With this I have an easy way to decide if I want to have an envelope or not:
```
orderSchema = OrderSchema()
orderSchema.context['noenvelope'] = True
order = ma.Nested(orderSchema, exclude=('transactions',))
```

This works fine but sometimes I need to reference the schema via the class name as string instead the class itself:
```
transactions = ma.Nested('TransactionSchema', many=True, exlude=('orders',))
```

Am I missing something in the docs (https://marshmallow.readthedocs.io/en/stable/nesting.html#two-way-nesting) or is there no way to pass the context to the schema?

**Comment by sloria** [comment]
As of 3.3.0, you can pass a callable to `Nested`, so perhaps you could do

```python
transactions = ma.Nested(lambda: TransactionSchema(context={"noenvelope": True}))
```

**Comment by Finn10111** [comment]
That seems to work in general, thank you. But it does not solve my problem regarding the circular imports. I have read that one way to solve this is to put both classes in a single file but this does not seem to be a proper solution to me.

**Comment by sloria** [comment]
It's a bit ugly, but you could do the import in the callable

```python
def get_transaction_schema():
    from .transactions.schemas import TransactionSchema

    return TransactionSchema(context=....)

class MySchema(Schema):
    # ...
    transactions = ma.Nested(get_transaction_schema)
```

**Comment by Finn10111** [comment]
Oh thank you very much, this works fine! I didn't think about the callable, sure it is a little bit ugly but it works.
