### ISSUE TITLE
Recommended way to set specific field on a Schema instance

### ISSUE THREAD

**Issue by vzts** [marshmallow-code/marshmallow#1487]
Hello, I have a question. Given that I have below schema,
```
class UserSchema(Schema):
    email = fields.Str()
    role = fields.Str()
```
and simple model
```
@dataclass
class UserModel:
    email: str
```
and I want to add a role to the initialized schema later.
What is the official way to do it? I've looked over the doc and code, and I couldn't find an answer.
```
user = UserModel('some@email.com')
schema = UserSchema(user)
???  # update this schema to have role field set?
```

**Comment by lafrech** [comment]
I don't understand what you are trying to achieve.

Your schema has a `role` field. Your input has no `role` attribute. If you dump the input with the schema, there will be no `role`. This has nothing to do with the schema but with the `user` object.

**Comment by vzts** [comment]
Hi @lafrech. Sorry, maybe I wasn't clear enough. What I meant was that there is another source for `role` data.
Given the below code:
```python
user = UserModel.objects.get(pk=1)  # e.g. UserModel is a django orm model
role = role_manager.get(user_id=user.id) # say role_manager is a in-memory instance that has all role data
schema = UserSchema(user)
schema.role = role.name  # something like this?
```
, is it necessary to have a combining container model for those two models? I was wondering what's the best way to mutate the field data of a schema instance.

**Comment by sloria** [comment]
@vzts You may want to look into `context`: https://marshmallow.readthedocs.io/en/stable/extending.html#using-context . That would allow you to set the role on the schema instance's context, which you could in turn use to alter [de]serialization behavior.

**Comment by vzts** [comment]
Thanks, @sloria. So I should add a hook to alter the serialization behavior of schema. That can be neater.
Sorry that I just realized that I was posting schema usage syntax with [drf-marshmallow](https://github.com/marshmallow-code/django-rest-marshmallow) wrapper, which may have caused some confusion. Thank you guys anyway!
