### ISSUE TITLE
ContainsOnly validator

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#149]
From the thread in https://github.com/marshmallow-code/marshmallow/issues/135#issuecomment-74391484 (trimmed for brevity):

@philtay 

> Do you want a ContainsOnly validator? [...] It's the natural extension of OneOf to sequences. Colander implements it using the set's method issubset, but I want to make it more generic (i.e. without the requirement of hashable items). I need it especially in combination with the List field.

Further comments

@davidism 

> Rather than separate validators for OneOf and ContainsOnly, one Choices validator that takes a multi=True argument seems more straightforward.

@philtay 

> My idea is to subclass OneOf and override **call**. I prefer to not put too much logic in a single validator. They must be very robust and thus very easy to debug. Anyway your idea is certainly doable.

**Comment by philtay** [comment]
@sloria what approach do you prefer?

**Comment by sloria** [comment]
I agree with @philtay on having separate validators. The meaning of `ContainsOnly` seems clearer than `Choices(multi=True)` and better to keep the validators small and focused.

**Comment by sloria** [comment]
Closed by #159
