### ISSUE TITLE
Typing issue in `Schema.load`

### ISSUE THREAD

**Issue by mehdigmira** [marshmallow-code/marshmallow#1492]
Hello,

The signature of `Schema.load()` is the following:
``` 
    def load(
        self,
        data: typing.Mapping,
        *,
        many: bool = None,
        partial: typing.Union[bool, types.StrSequenceOrSet] = None,
        unknown: str = None
    ):
```

while `data` can be of type `List`, if many=True is used. Is this intentional or is it a bug ?

**Comment by lafrech** [comment]
Would #1488 fix this?

**Comment by mehdigmira** [comment]
Yes, but It would be better to use `@overload` to have a finer typing, and to only allow List if many=True and Mapping if many=False.

**Comment by sloria** [comment]
Closing this for now, since #1488 fixes this. Feel free to send a PR improving the typing with `@overload`.
