### ISSUE TITLE
Validate JSON

### ISSUE THREAD

**Issue by GabrielFiel** [marshmallow-code/marshmallow#1496]
Hi

I have this json:

```
data = {
    "company": "Google",
    "members": [
        {
            "type": 2,
            "name": "James",
            "age": 25
        },
        {
            "type": 1,
            "name": "Maria",
            "age": 22
        },
        {
            "type": 2,
            "name": "George",
            "age": 44
        }
    ]
}
```
I just don't know how to validate the members **age**, because the number of members is not fixed, it could be 1, 2 or more and it needs to be validated by the **type** field.

For example:
George's age must return an error because his type (2) needs to be between 18 and 30

**Comment by lafrech** [comment]
Looks ilke you're trying to achieve [polymorphism](https://github.com/marshmallow-code/marshmallow/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Apolymorphism+).

**Comment by deckar01** [comment]
Validating a relationship between two fields can also be accomplished using schema level validation. With schema validation, you end up writing the polymorphism discriminator in the validator and writing the validation procedurally. If you have more than one field that needs to customize validation based on the type, it is more practical to use a library like marshmallow-polyfield to avoid duplicating the discriminator and allow using the declarative validators marshmallow provides.

https://marshmallow.readthedocs.io/en/stable/extending.html#schema-level-validation

https://github.com/Bachmann1234/marshmallow-polyfield

**Comment by GabrielFiel** [comment]
I will take a look. Thanks @deckar01  and @lafrech

**Comment by GabrielFiel** [comment]
@deckar01 Do you know if it is possible to do this schema-level validation with **webargs** using a dictionary instead of a Marshmallow schema?

**Comment by deckar01** [comment]
> The full arguments dictionary can also be validated by passing validate to `Parser.parse`, `Parser.use_args`, `Parser.use_kwargs`.
> 
> ```py
> from webargs.flaskparser import parser
> 
> argmap = {"age": fields.Int(), "years_employed": fields.Int()}
> 
> # ...
> result = parser.parse(
>     argmap, validate=lambda args: args["years_employed"] < args["age"]
> )
> ```

https://webargs.readthedocs.io/en/latest/quickstart.html#validation

**Comment by GabrielFiel** [comment]
I managed to make using Marshmallow Schema. Thank you
