### ISSUE TITLE
[Question] Is it possible to override a load_only=True field for a one off?

### ISSUE THREAD

**Issue by symonk** [marshmallow-code/marshmallow#1504]
lets say we have:

```
 identity_number = fields.Integer(load_only=True)
```

This is great, the server never accepts one in the payload; however theres a bug and we want to write a simple test that actually includes the identity_number value in the json payload; this is a minority case, how can we dump through the schema and have it include this field as if it is not load_only=True? for a one off use case

**Comment by sloria** [comment]
You could use a subclass that with `load_only=False`.

You could even `from_dict` for convenience:

```python
from marshmallow import Schema, fields


class MySchema(Schema):
    identity_number = fields.Integer(load_only=True)


assert MySchema().dump({"identity_number": 42}) == {}

MySchemaWithINum = MySchema.from_dict({"identity_number": fields.Integer()})
assert MySchemaWithINum().dump({"identity_number": 42}) == {"identity_number": 42}
```
