### ISSUE TITLE
Is This An Acceptable Way to Pass Arguments to post_dump?

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [marshmallow-code/marshmallow#1513]
I want to be able to treat my marshmallow post_dump differently based on the wishes of the user, but there seems to be no way to pass arguments to the a post_dump decorated method. i.e. I'm trying to avoid something like this 
```python
query = db.sessions.query(MyModel)

if group_output:
    outputSchema = GroupedOutputSchema(many=True)
else:
    outputSchema = OutputSchema(many=True)

allOutput = outputSchema.dump(query.all())
```
In favour of something like this
```python
query = db.sessions.query(MyModel)

outputSchema = FlexibleOutputSchema(many=True, group_output=group_output)
allOutput = outputSchema.dump(query.all())
```
As the latter allows me to avoid having to write one output schema for every type of post processing I available.

My current 'solution' is to pass my own keyword arguments to the constructor of the ModelSchema
```python
class FlexibleOutputSchema(ModelSchema):
    def __init__(self, *args, **kwargs):
        self._group_output = kwargs.pop('group_output')
        super().__init__(*args, **kwargs)

    @post_dump(pass_many=True)
    def postProcess(self, data, many):
        if self._group_output:
           # Do grouping
        else:
           # Do other stuff
```
So, my question is: Is there anything wrong with this approach? It feels quite hacky to me and that's usually a path that leads to bad times.

**Comment by Anti-Distinctlyminty** [comment]
I ended up using the `self.context` dict to store such parameters. One benefit being that the information is easily accessible by nested schemas.

**Comment by sloria** [comment]
Correct, `context` is the preferred way to change post-processing behavior at runtime.
