### ISSUE TITLE
post_load: no attribute data

### ISSUE THREAD

**Issue by ssimontacchi** [marshmallow-code/marshmallow#1520]
From [the docs][1] under 'Deserializing to Objects':

```
from marshmallow import Schema, fields, post_load


class UserSchema(Schema):
    name = fields.Str()
    email = fields.Email()
    created_at = fields.DateTime()

    @post_load
    def make_user(self, data, **kwargs):
        return User(**data)

```
But I when I run this code, I get: 
`AttributeError: 'User' object has no attribute 'data'`

What am I missing?

  [1]: https://marshmallow.readthedocs.io/en/stable/quickstart.html

**Comment by sloria** [comment]
What does the User constructor look like? 

Edit: Also, what code is triggering the exception? Can you post the full stack trace?

**Comment by ssimontacchi** [comment]
I'm an idiot. Thanks so much for you time and attention  🙏🎖
