### ISSUE TITLE
2.10.2 -> 2.10.3 breaks certain number fields 

### ISSUE THREAD

**Issue by epicfaace** [marshmallow-code/marshmallow#1526]
There appears to be a breaking change from version 2.10.2 to 2.10.3 (d81cab413e231ec40123020f110a8c0af22163ed, which was supposed to fix #538).

We have a field, `id = fields.Integer(as_string=True, dump_only=True)`. However, this field appears to be omitted upon serialization after upgrading from 2.10.2 to 2.10.3. I'm not exactly sure why the above change caused this, but reverting that particular change fixed the issue for us (our codebase's complete fix is available at https://github.com/codalab/codalab-worksheets/pull/2042).

Do you have any idea why the above commit might have caused this breaking change in behavior?

**Comment by lafrech** [comment]
The fix is very simple and I don't see how it could be causing this.

Can you reproduce the issue on a minimal example?

**Comment by deckar01** [comment]
I am unable to repro this issue on 2.10.3 or 2.15.1. Maybe the source of this issue was `marshmallow_jsonapi`?

```py
>>> from marshmallow import Schema, fields
>>> 
>>> class Test(Schema):
...     foo = fields.Integer(as_string=True, dump_only=True)
... 
>>> Test().dump({'foo': 123})
MarshalResult(data={u'foo': '123'}, errors={})
```

**Comment by epicfaace** [comment]
Yeah, I'd need to walk through our code for the existing project to isolate what exactly caused it -- it might have called other functions than just `serialize()`, such as functions from `marshmallow_jsonapi`. There is no doubt, though, that the issue occurred upon upgrade from 2.10.2 to 2.10.3. I'll try to isolate and create a reproducible example.

**Comment by sloria** [comment]
Closing this, as it has gone stale. Feel free to re-open if this is still relevant.
