### ISSUE TITLE
Feature Suggestion: Add ContainsNoneOf validator

### ISSUE THREAD

**Issue by Resinderate** [marshmallow-code/marshmallow#1528]
### Background
There is a `ContainsOnly` validator which can be thought of as the iterable version of the `OneOf` validator. I propose the addition of a `ContainsNoneOf` sibling (or some other succinct name) which would be the iterable version of the `NoneOf` validator.

I see the `ContainsOnly` as the whitelist side of the coin, and a `ContainsNoneOf` as the blacklist side of the coin.

### User Story
As a developer I have a simple schema for a user complaint, which validates what kind of letters they can have in their reason:
```
class Complaint(Schema):
    ALLOWED = string.ascii_letters + string.digits
    reason = fields.Str(validate=validate.ContainsOnly(ALLOWED))
```
Users keep asking for more characters the be allowed so I continue to update my whitelist of characters.
```
class Complaint(Schema):
    ALLOWED = string.ascii_letters + string.digits + "!?£@"
    reason = fields.Str(validate=validate.ContainsOnly(ALLOWED))
```

We keep getting asked to update the allowed characters so I decide to implement a blacklist instead of a whitelist. I would like to be able to do something like:
```
class Complaint(Schema):
    NOT_ALLOWED = "><$;"
    reason = fields.Str(validate=validate.ContainsNoneOf(NOT_ALLOWED))
```
### Implementation
The idea would be to support not just string, but all iterables similarly to `ContainsOnly`. For example, I should be able to declare:
```
class Sentence(Schema):
    words = fields.List(fields.Str(), validate=validate.ContainsNoneOf(["baloney"]))
```

I've already implemented this in my project following the `OneOf` -> `ContainsOnly` style, so would be happy to contribute the work for this. Mostly trying to gauge for interest or feedback as to why it might be a bad idea before starting a PR.

Thanks,
Ronan

**Comment by deckar01** [comment]
The proposed use case seems reasonable, and I generally advocate making the API symmetrical.

I wonder if the implementation could be decomposed into a more generic interface to cover more use cases? `ContainsNoneOf(choices)` could be `Not(Contains(choices))` or `Contains(choices, max=0)`. I personally lean towards functional composition for declarative APIs since it avoids branching in the implementation, but reusing the `Length` constructor to validate the results of a `Contains` filter would cover a lot more use cases without adding much code.

**Comment by Resinderate** [comment]
I like the idea of `Not(Contains(choices))`. Some others that might be interesting/useful are `Not(Equal(something))` or `Not(Regexp(pattern))`.

I guess a high level implementation would be to call the underlying validator and pass if we see a `ValidationError`, and error when it doesn't.

The main downside I see is that the error messages might be quite hard to format and potentially a bit incoherent, which for me would be a bit of a deal breaker. One of my favourite features of marshmallow is the great error messages where possible.

For example formatting the `ContainsOnly` error message, `One or more of the choices you made was not in: {choices}.` to mean the opposite externally in a generic way would be messy/tough.

**Comment by deckar01** [comment]
Ah, I didn't think about the error messages. Nothing an NLP NN can't solve :smile:. That seems like a pretty strong argument to go with `ContainsNoneOf`.
