### ISSUE TITLE
Troubles with validating nested values

### ISSUE THREAD

**Issue by Jonyorker** [marshmallow-code/marshmallow#1529]
I am looking to add validation to my api endpoint using Marshmallow.

I am running into the problem of how to get this chunk properly validated. The end goal is to make sure impressions is a positive number.

I would greatly appreciate any help or insight you can provide. First time using Marshmallow.

**Sample JSON:**
```
{
    "mode": [
        {
            "type": "String",
            "values": {
                "visits": 1000,
                "budget": 400
            },
            "active": true
        }
    ]
}
```

**Sample code attempting to validate**

```
class ValidateValues(BaseSchema):
    visits = fields.Int(allow_none=True, validate=[validate.Range(min=0, error="Value must be greater than 0")])
    budget = fields.Int(allow_none=True, validate=[validate.Range(min=0, error="Value must be greater than 0")])


class ModeSchema(BaseSchema):
    type = fields.String(required=True)
    active = fields.Boolean(required=True)
    values = fields.Nested(ValidateValues)


class JsonSchema(BaseSchema):
    mode = fields.List(fields.Dict(fields.Nested(ModeSchema, many=True)))
```

**Current result**

```
{
    "mode": {
        "0": {
            "type": {
                "key": [
                    "Invalid type."
                ]
            },
            "values": {
                "key": [
                    "Invalid type."
                ]
            },
            "active": {
                "key": [
                    "Invalid type."
                ]
            }
        }
    }
}
```

**Comment by Resinderate** [comment]
I think your `JsonSchema` is not doing as you expect.

The `fields.Nested(ModeSchema..` is already expecting a dictionary, so you don't need the `fields.Dict` wrapper. I also don't think you need the `many=True` piece, as you're already describing the modes correctly as a list with `fields.List`. So you might end up with something like:
```
class JsonSchema(BaseSchema):
    mode = fields.List(fields.Nested(ModeSchema))
```
I've tested that locally with your input and it seems to come through fine.

**Comment by Jonyorker** [comment]
That worked perfect!
