### ISSUE TITLE
Errorhandler not work for ValidationError from marshmallow

### ISSUE THREAD

**Issue by cheban96** [marshmallow-code/marshmallow#1530]
### Expected Behavior
When happens exeption ValidationError i waiting that be handled function handle_exception

### Actual Behavior
```pytb
  File "/usr/lib/python3.7/site-packages/marshmallow/schema.py", line 892, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'active': ['Not a valid boolean.']}
```

### Environment

* Python version: 3.8
* Flask version: 1.1.1
* Werkzeug version: 0.16.1
* Marshmallow: 3.5.0
```
@app.errorhandler(marshmallow.exceptions.ValidationError)
def handle_exception(e):
    return {'message': e.normalized_messages()}, 400
```

**Comment by Cheban1996** [comment]
I fix this problem with help set low version werkzeug
