### ISSUE TITLE
Value Error when parsing data, error to user_schema

### ISSUE THREAD

**Issue by brightmaraba** [marshmallow-code/marshmallow#1531]
The code
` data, errors = user_schema.load(data=json_data)`
works perfectly in marshmallow==2.19.5 but throws a Value Error: too many variables in later versions.

**Comment by deckar01** [comment]
This behavior changed in version 3.

> Schema().load ... [doesn't] return a `(data, errors)` tuple any more. Only `data` is returned.

https://github.com/marshmallow-code/marshmallow/blob/dev/docs/upgrading.rst#schemas-are-always-strict
