### ISSUE TITLE
Nested schemas result in a "nasty" error message. 

### ISSUE THREAD

**Issue by Drvanon** [marshmallow-code/marshmallow#1544]
Maybe I am understanding this wrong or am I looking over something but this is my scenario:

```python
class IntervalSchema(Schema):
    days = fields.Int()
    hours = fields.Int()

    @validates_schema
    def check_nonzero(self, in_data, **kwargs):
        if in_data["days"] <= 0 and in_data["hours"] <= 0:
            raise ValidationError("Interval must be nonzero.")


class MovementSchema(Schema):
    name = fields.Str(required=True, validate=Length(min=4, max=50))
    short_description = fields.Str(required=True, validate=Length(min=10, max=100))
    description = fields.Str(data_key="long-description", validate=Length(max=1000))
    interval = fields.Nested(IntervalSchema(), required=True)
```
If now the user provides a movement like:
```json
{
    "name": "movement",
    "short_description": "Hi, this is a test",
    "interval": {"days": 0, "hours": 0},
}
```
I get an error that looks like:
```json
{"interval": {"_schema": ["Interval must be nonzero."]}}
```
which is of course much less nice then 
```json
{"interval":  ["Interval must be nonzero."]}
```
As far as I understand it this is something that is not really possible right now. Is this correct, or is this a future request?

**Comment by lafrech** [comment]
You can have both schema-level errors and field-level errors in the same schema. Errors are namespaced by field name and the namespace for schema-level errors is `_schema`.

Do you see another way to return both field and schema-level errors? I don't really like the `_schema` namespace either, but I couldn't come up with a better option.

More or less related discussions in #441, #879, #1026.

**Comment by Drvanon** [comment]
It is a day later and I have been able to sleep over it. 

I think that in part what you are doing is fairly logical. My initial thought was that a problem with the "hours" field would show up as

```json
{"interval": ["Something is missing here."]}
```

But your logic is better, because you want to be able to point with a dict to which field is 'breaking'. 

I don't know if I like or dislike "_schema". I also do not really see a better solution. Maybe if I sleep another night over it will.

**Comment by crossonrose-at-yahoo-dot-com** [comment]
![ssh-banner-home-mobile](https://user-images.githubusercontent.com/61810389/77269785-f412c400-6c77-11ea-9f68-64c607685f96.png)
Why are you so nasty?

**Comment by lafrech** [comment]
Further discussion should happen in #879.
