### ISSUE TITLE
Formatting error messages on validation

### ISSUE THREAD

**Issue by Jonyorker** [marshmallow-code/marshmallow#1547]
Hi,

Currently, when I encounter a schema validation error I get this as output

```
{
  "mode": {
    "0": {
      "values": {
        "sov": [
          "Value must be greater than 0"
        ]
      }
    }
  }
}
```

Is it possible to modify something to get this as output? (notice the square brackets around the value)

```
{
  "mode": {
    "0": {
      "values": [
        {
          "sov": [
            "Value must be greater than 0"
          ]
        }
      ]
    }
  }
}
```

**Comment by sloria** [comment]
You could do something similar to marshmallow-jsonapi does and modify the error messages in `_do_load`: https://github.com/marshmallow-code/marshmallow-jsonapi/blob/efa67732f4640a97bce2a51198746a8eb5a17684/marshmallow_jsonapi/schema.py#L249
