### ISSUE TITLE
Feature request: Add Meta definition to "Schema.from_dict"

### ISSUE THREAD

**Issue by t-bittarn** [marshmallow-code/marshmallow#1548]
**Problem:**
Currently, we cant define Schema Meta in from_dict method.
**Reason**
Meta data is hard coded in from_dict method.
```python
attrs["Meta"] = type(
            "GeneratedMeta", (getattr(cls, "Meta", object),), {"register": False}
        )
```
**Possible solutions**
Use user input meta data instead.
```python
meta_data = attrs.pop("Meta", {})
meta_data["register"] = False
attrs["Meta"] = type(
            "GeneratedMeta", (getattr(cls, "Meta", object),), meta_data
        )
```
**Why this feature helpful**
I'm a webargs user. If I can't define "unknown" in schema dict definition, I need define a Schema class for every web route, that waste a lot of code. This feature can also let from_dict method more powerful in other places.

Thanks.

**Comment by sloria** [comment]
You can always use a Schema subclass if you need to set any non-field attributes, including `Meta`.

```python
class MyBaseSchema(Schema):
    class Meta:
        unknown = EXCLUDE

MyBaseSchema.from_dict({...})
```

Does that meet your use case?

**Comment by t-bittarn** [comment]
> You can always use a Schema subclass if you need to set any non-field attributes, including `Meta`.
> 
> ```python
> class MyBaseSchema(Schema):
>     class Meta:
>         unknown = EXCLUDE
> 
> MyBaseSchema.from_dict({...})
> ```
> 
> Does that meet your use case?

Yes. My current solution is using subclass of Schema, but I think the `from_dict` method should construct a Schema from a dict. Meta is also a part of Schema, maybe we should consider using Meta info in dict instead hard code it in code, that will make from_dict more powerful.
Anyway, it's just my opinion of the interface design. Thank you for your reply.

**Comment by sloria** [comment]
I wanted to reduce the API surface for `from_dict` as much as possible, which is why I omitted `Meta`. At the point that you need to override more than just fields, you should probably use a custom base class. I think many projects end up using a custom base `Schema` class to encapsulate common `Meta` options, etc. anyway.

Closing for now, but feel free to continue discussion here
