### ISSUE TITLE
Reference one Schema in another

### ISSUE THREAD

**Issue by Spothedog1** [marshmallow-code/marshmallow#1556]
```
class SerieId(Schema):
    serieId = fields.Str(location='view_args', required=True)

class Version(Schema):
    version = fields.Str(location='view_args', required=False)

class ChartGetRequest(Schema):
    serieId = SerieId()
    version = Version()
```

Hello - I'm trying to build a bunch of schemas up into one schema. The reason for this is the ChartGetRequest is used for validating the input of my API, while SerieId and Version are used for Swagger API Documentation purposes and are separate path parameters. I was wondering if there was a way to do what I'm trying to do above. When I call this I get an error saying SerieId is the wrong type. I tried a couple of other ways also such as 

`serieId = SerieId._declared_fields['serieId']`

but this isn't working either.

**Comment by Spothedog1** [comment]
Nevermind I figured it out. 

`serieId = SerieId._declared_fields['serieId']`

actually works.

**Comment by lafrech** [comment]
I'm not sure I understand what you are trying to achieve.

Your use case should be covered by inheritance.

```py
class ChartGetRequest(SerieId, Version):
    pass
```
