### ISSUE TITLE
Suggestions for patterns for the following user flow

### ISSUE THREAD

**Issue by aronchick** [marshmallow-code/marshmallow#1561]
I'm building a strongly typed schema for data scientists who want to work at a higher level of abstraction than understanding marshmallow schema tools.

So the flow would look like the following:

1. Data scientist decides she wants to create a new 'model package' object that has three fields: `framework`, `framework_version`, `model_uri`
2. Data scientist instantiates an object from a library - e.g. MLSpec.model_package() - that has no data in it.
3. Data scientist attempts to assign to the field `frame_work` but this fails (at runtime) because the attribute is `framework`
4. The data scientist assigns values for `framework_version` and `model_uri`.
5. Data scientist uses a method to `.validate()` the object against the schema.
6. Data scientist executes `.save(<path>)` to serialize and save the object.

Any thoughts here? Nothing seems terribly difficult - my biggest challenges would be catching misassigned fields, I believe (and ensuring the data scientist isn't accidentally writing to a Schema variable).

Extra credit if I could make the schema show up for doc-string and/or code completion in VSCode & Jupyter.

Extra extra credit if I could deserialize all objects so I don't have to load the schemas from disk on every import of the library.

**Comment by deckar01** [comment]
Since there is no validation on dump, you need to `dump()` then `load()` or `validate()`. Related discussion: https://github.com/marshmallow-code/marshmallow/issues/1127#issuecomment-603435348

**Comment by aronchick** [comment]
Thanks!
