### ISSUE TITLE
Adding validation programatically?

### ISSUE THREAD

**Issue by aronchick** [marshmallow-code/marshmallow#1569]
I'm trying to add validation to a field after creating field. So the code might look like (forgive the simplistic example):

```
my_field = fields.Str()

if type_of_field = 'allowed':
	my_field.validate = validate.OneOf(allowed_list)
```

But this doesn't seem to work. Did I get this wrong?

**Comment by lafrech** [comment]
This is not meant to be changed after init.

See what happens at field init:

https://github.com/marshmallow-code/marshmallow/blob/76196abf35ff9ec58f3dc2377ea7a8a9bf23712a/src/marshmallow/fields.py#L161-L167

We could make this more clearly [private API](https://github.com/marshmallow-code/marshmallow/issues/1281). Or change our mind about this and decide all those attributes are public but ensure it works.

**Comment by aronchick** [comment]
Ok - I guess i'll just build the list of options and instantiate in the end then. This makes sense - I think either of your solutions (make it obviously private, or make it editable after instantiation) would be helpful!

(feel free to close or add to a list of items to evaluate in the future)

**Comment by sloria** [comment]
You can achieve conditional validation by using `validates("some_field")` and reading `self.context`, or doing the validation in a `post_load` method.
