### ISSUE TITLE
Only array/list

### ISSUE THREAD

**Issue by mirecl** [marshmallow-code/marshmallow#1571]
Hi guys.
Pls to suggest how to create `schema` with list, without key.
My code:
```python
class Template(Schema):
    data = fields.List(fields.Int(), required=True, example=[1,2,3])
```
how to hidden ``data``?
My POST request
```json
[1,2,3,4,5]
```
not
```json
{
  data: [1,2,3,4,5]
}
```

**Comment by lafrech** [comment]
What about using `many=True` and a schema with only an `Int` field, no `List`?

https://marshmallow.readthedocs.io/en/stable/quickstart.html#handling-collections-of-objects

**Comment by mirecl** [comment]
Not working((
![Screenshot 2020-04-18 at 14 50 23](https://user-images.githubusercontent.com/28476324/79636932-fe938100-8183-11ea-9c08-ab7a87794141.png)

**Comment by lafrech** [comment]
Yes, you're right, sorry for the confusion.

Indeed I'm afraid it can't be achieved.

I blurrily remember a comment by @deckar01 about this but I can't find it anymore.

The discussion was about a refactor sort of merging `Schema` and `Field`, allowing `List` to be called directly.

**Comment by sloria** [comment]
It's a bit clunky, but you could work around the issue using pre- and post-load method:

```python
from marshmallow import Schema, fields, pre_load, post_load


class Template(Schema):
    data = fields.List(fields.Int(), required=True, example=[1, 2, 3])

    @pre_load
    def wrap(self, raw_data, **kwargs):
        return {"data": raw_data}

    @post_load
    def unwrap(self, data, **kwargs):
        return data["data"]


print(Template().load(["1", "2", "3"]))  # [1, 2, 3]
```

**Comment by sloria** [comment]
Closing for now, as there isn't anything immediately actionable. Feel free to comment if you'd like to discuss further

**Comment by mirecl** [comment]
Ok, thanks!

**Comment by sloria** [comment]
You could look at https://github.com/and-semakin/marshmallow-toplevel . I don't personally have any experience with it, but looks like it was built for this use case
