### ISSUE TITLE
Field validation based on other fields in the document?

### ISSUE THREAD

**Issue by aronchick** [marshmallow-code/marshmallow#1580]
I'm trying to validate a field based on other fields in the document. So, for example:

```
schema_version: 0.0.1
input:
	type: data_object
```

When I validate the `type` of `input`, I'd like to know that this was in a document who's schema was 0.0.1. 

When I look at custom validators, though, it looks like I only get information about the specific field. Is this possible?

**Comment by lafrech** [comment]
It could work with a schema-level validator (search the docs for @validates_schema).

**Comment by sloria** [comment]
Yes, `@validates_schema` is probably what you want. You could also look into https://github.com/marshmallow-code/marshmallow-oneofschema, which allows you to have a polymorphic schema that selects concrete schemas based on the value of a field.

**Comment by aronchick** [comment]
Thank you!
