### ISSUE TITLE
get labels or get superclasses name

### ISSUE THREAD

**Issue by lazarocosta** [marshmallow-code/marshmallow#1584]
Good Morning,
I would like to get labels for the schema super classes, but I haven't found how I can do that.
In Neomodel, I use the self.labels () method to obtain the names of the superclass .

I would like you to help me with this problem.

best regards
Lázaro Costa

**Comment by sloria** [comment]
I'm not sure what you're referring to. What do you mean by `labels` in this context? Can you clarify? Maybe post a code snippet showing what you're trying to achieve.

**Comment by deckar01** [comment]
It looks like that library uses the class names as labels in their registry key.

https://neomodel.readthedocs.io/en/latest/extending.html#automatic-class-resolution

As far as I can tell, in neo4j labels are user defined independently of model names.

https://neo4j.com/docs/getting-started/current/graphdb-concepts/#graphdb-labels

If you need introspect class inheritance, I would recommend learning more about `__class__.__mro__` and `__class__.__name__`.

**Comment by lazarocosta** [comment]
I want to get the names of the superclass and the class itself, but I don't want to save the node in neo4j.

https://neo4j.com/docs/getting-started/current/graphdb-concepts/ 
In neoj4 I need to save the node in the database and then get the names of the superclasses and the name of the class itself.

E52_Time_span is subclass of E1_CRM_Entity
I want get **E1_CRM_Entity** and **E52_Time_span**

![Captura de ecrã de 2020-05-06 19-32-49](https://user-images.githubusercontent.com/15108618/81214896-6fce9300-8fd0-11ea-9b19-59e9e6827d80.png)

This function gets class labels, but this is in the neomodel I only can invoke this function when i saved node in ne4j.
![Captura de ecrã de 2020-05-06 19-53-18](https://user-images.githubusercontent.com/15108618/81216735-495e2700-8fd3-11ea-816c-27412506ba68.png)



```

    def get_superclasses_name(self):
        return list(set(self.labels()))
```



My class E52_Time_SpanSchema has the same superclass as E52_Time_Span
If i can get **E1_CRM_Entity** and **E52_Time_span** from marshmallow I solve my problem because i can invoke functions of created schema without save nothing in the database.

**Comment by deckar01** [comment]
Python provides access to the class MRO, so you just need to filter it to match your use case.

```py
def get_labels(target, base_class):
    return (
        c.__name__
        for c in target.__mro__
        if issubclass(c, base_class)
    )
```

```py
class Test(Schema):
    pass

get_labels(Test, Schema)
# ('Test', 'Schema')
```

**Comment by lazarocosta** [comment]
Thank you
