### ISSUE TITLE
Include excluded fields for serializing

### ISSUE THREAD

**Issue by tyre** [marshmallow-code/marshmallow#1592]
Searched for other open issues around this but didn't find anything.

Many APIs have permissions models that conditionally allow fields or limit the base response for performance. Removing these fields with `exclude` in `Meta` keeps those out of serialization.

When a user _does_ have high enough permissions or if an api endpoint supports including additional information via parameters, we want to un-exclude certain fields.

Something like `UserSchema(include=["excluded_property", "excluded_nested_schema"]).dump(object)`.

What's the recommended way of accomplishing this?

What doesn't fit: specifying every field via `only` on each variation. This requires keeping the schema fields duplicated and kept in sync for every call, which is one of the benefits of having schemas in the first place.

**Comment by jamesharding** [comment]
I am curious to find the solution to this same question. @tyre What did you come up with in the end for this?

**Comment by sloria** [comment]
You could do something along the lines of https://github.com/marshmallow-code/marshmallow/issues/614#issuecomment-450177491 to add an `include` parameter.

Alternatively, you could use `from_dict` to add the fields at runtime (see  https://github.com/marshmallow-code/marshmallow/issues/1504).

Closing for now, but feel free to continue discussion.
