### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by DeaconDesperado** [marshmallow-code/marshmallow#16]
I can't seem to find in the docs if there is a way to make certain fields required?  Is there no present implementation that marks the `is_valid` call as invalid if a certain field is missing?  Would be willing to contrib :smile:

**Comment by DeaconDesperado** [comment]
It seems this can be accomplished with validators that simply check truthiness for values (I'm simulating it with `lambda v: bool(v)` for string fields just to reject empty strings.)  Perhaps it would be cool to reify this into a special `required=True` flag, with more detailed check cases for different field types?

**Comment by sloria** [comment]
You are correct that there is no special `required` field, but checking the truthiness of the value works.

That said, I think a `required` param is a fine idea. Pull requests would be welcome. =)

**Comment by DeaconDesperado** [comment]
I'll have a go at it then, thanks!

**Comment by sloria** [comment]
Thank you!

**Comment by DeaconDesperado** [comment]
Style question for you:

Some of the field types have potential falsy values that still could be considered "filled" for the purposes of the marshaller.  For example, number fields set to `0` by an incoming object should be considered "filled in" by the verification for a required flag.  A zero length string, if passed to the serializer, should probably be considered "filled in" as well.  Really only a `None` from `format` or `output` should fail.

Because many of the types have default values that are evaluated in after the `validated` decorator is applied, I'm thinking an additional decorator to check `self.required` would be the cleanest way to do this, to check the value upstream before the default is applied and `MarshallError` out if the flag was required and failed.  Thoughts about another decorator?  Seems preferable to checking in each individual field's logic...

**Comment by sloria** [comment]
My initial thought was to modify `fields.Raw#get_value`, which defines how values are pulled from the objects. You could perform the extra validation here.

However, if you think a decorator-based solution would be cleanest, I say go for it, and I'll review it.
