### ISSUE TITLE
Documentation: include a table summarizing built in Field types

### ISSUE THREAD

**Issue by mivade** [marshmallow-code/marshmallow#1603]
Right now when I want to check if a field type is pre-defined by Marshmallow (or I want to check the parameters a field takes) I have to scroll through the API documentation. It would be nice if there was a quick reference table that has as columns the field class and a quick description. The class itself should then link to the API docs for that particular class.

**Comment by sloria** [comment]
This is available in the `latest` docs. They'll be in the stable docs as well the next time we cut a new release.

https://marshmallow.readthedocs.io/en/latest/marshmallow.fields.html

**Comment by mivade** [comment]
Awesome, thanks!
