### ISSUE TITLE
CONTRIBUTING.rst Reference to Quick reStructuredText not valid

### ISSUE THREAD

**Issue by HenkVanHoek** [marshmallow-code/marshmallow#1605]
CONTRIBUTING.rst contains an not working reference.

"Contributions to the documentation are welcome. Documentation is written in reStructured Text (rST). A quick rST reference can be found here. Builds are powered by Sphinx."

The link in _here_ is referencing **https://docutils.sourceforge.net/docs/user/rst/quickref.html**, 
but it should be **https://docutils.sourceforge.io/docs/user/rst/quickref.html**
The _.net_ must be replaced with _.io_

**Comment by sloria** [comment]
Good catch. It's fixed now.
