### ISSUE TITLE
Preprocessing before dumping to leave out invalid datetime

### ISSUE THREAD

**Issue by thombou** [marshmallow-code/marshmallow#1615]
Hi,
I have null dates in my database that are returned as a python string "0000-00-00" by sqlalchemy (and not a datetime object). 
This causes a fail when I try to dump my object as marshmallow expects a Date type. 
How to leave out the date fields containing null dates when dumping my object? or Even better, how to return 'null' for those fields?

**Comment by sloria** [comment]
You might want to create a subclass of `fields.Date` that overrides `_serialize` to serialize `"0000-00-00"` as `None`.

**Comment by lafrech** [comment]
Closing for now. Feel free to re-open if this is still relevant.
