### ISSUE TITLE
Update fields.Nested documentation

### ISSUE THREAD

**Issue by Enola-guy** [marshmallow-code/marshmallow#1625]
Hello, I've tried to use `fields.Nested(nested="self")` as the  [documentation for the nested parameter said](https://marshmallow.readthedocs.io/en/stable/_modules/marshmallow/fields.html#Nested) only to have errors.

After checking the code it seems that this is no longer supported according to the [internal code](https://marshmallow.readthedocs.io/en/stable/_modules/marshmallow/fields.html?highlight=MySchema(...)#Nested) I saw:

```
        if nested == "self":
            warnings.warn(
                "Passing 'self' to `Nested` is deprecated. "
                "Use `Nested(lambda: MySchema(...))` instead.",
                DeprecationWarning,
            )
```
I think it would be nice to update the doc on **readthedocs** meanwhile I'll stick to the one in the repo.

Thanks !

**Comment by sloria** [comment]
Good catch; fixed
