### ISSUE TITLE
Deserialization of nested fields

### ISSUE THREAD

**Issue by stephenfin** [marshmallow-code/marshmallow#163]
I am using marshmallow for serializing/deserializing requests/responses in a REST API. I'm having difficulty how to distinguish between the two without defining multiple serializers.

Given a serializer like so:

``` python
class AuthorSchema(Schema):
    class Meta:
        fields = ('id', 'name')

class BookSchema(Schema):
    author = fields.Nested(AuthorSchema, only='id')
    class Meta:
        fields = ('id', 'title', 'author')
```

When serializing, you'd likely expect something like so:

``` json
{
  "id": 1,
  "title": "The Bourne Identity",
  "author": {
    "id": 1,
    "name": "Robert Ludlum",
  }
}
```

However, when deserializing, you'd likely expect something like this for deserializing:

``` json
{
  "id": 1,
  "title": "The Bourne Identity",
  "author": 1,
}
```

I see an [example here](http://marshmallow.readthedocs.org/en/latest/examples.html#todo-api-flask-peewee) that uses the `make_object` function to handle this corner case. However, the `validate` function still returns errors (as it should) here. Any ideas on how this can be achieved?

**Comment by sloria** [comment]
What is wrong with using multiple schemas? You can use a base class for the shared fields.

**Comment by stephenfin** [comment]
There's nothing wrong with it at all. I had just hoped there would be a clever way to achieve this without adding separate serialization/deserialization models.
