### ISSUE TITLE
TypeError: pre_load() got an unexpected keyword argument 'many'

### ISSUE THREAD

**Issue by lungati** [marshmallow-code/marshmallow#1630]
Hello,

I'm using Marshmallow 3.0.0b8 and I'm trying to upgrade but I get the error `TypeError: pre_load() got an unexpected keyword argument 'many'`
These are the related packages:

` marshmallow==3.0.0b8
-marshmallow-enum==1.4.1
-marshmallow-sqlalchemy==0.14.1
+marshmallow-enum==1.5.1
+marshmallow-sqlalchemy==0.23.1
`

**Comment by lafrech** [comment]
Add **kwargs to your pre_load (and such) functions to silently swallow unknown kwargs.

https://marshmallow.readthedocs.io/en/stable/upgrading.html#decorated-methods-and-handle-error-receive-many-and-partial

**Comment by lungati** [comment]
@lafrech That worked. Thanks

**Comment by ewitz** [comment]
@lafrech, thanks, this also worked for me when defining @pre_dump:
`def _pre_dump(self, object, **kwargs):`
