### ISSUE TITLE
Partial for un-listed fields

### ISSUE THREAD

**Issue by azzamsa** [marshmallow-code/marshmallow#1637]
I have some schema with a huge number of attributes.

```python
class AwesomeSchema(Schema):
    foo = fields.Str()
    bar = fields.Str()
    baz = fields.Str()
    blah = fields.Str()
    so = fields.Str()
    many = fields.Str()
    of = fields.Str()
    them = fields.Str()
    ...


```

and most of my EDIT/PUT operation requires many fields to be `partial` and some fields to be `required`.

Eg:

- **Required**: foo, bar
- **Partial**: the rest of attributes

The only way I can do, is by putting *all the rest of attribute* and leaving *foo, and bar*. such as:

```python
AwesomeSchema(partial=("baz", "blah", "so", "many", "of", "them"))
```

---

Is there any simple / better way to do this? some thing like `AwesomeSchema(reverse_partial=("foo","bar",))`

Thank you for marshmallow

**Comment by deckar01** [comment]
The schema instance's `fields` attribute can be `.keys()`ed to get a list of the field names. Once you have that you can perform set operations on it.

https://marshmallow.readthedocs.io/en/stable/marshmallow.schema.html#marshmallow.schema.Schema.fields

```py
awesome_schema = AwesomeSchema()
awesome_fields = awesome_schema.fields.keys()
awesome_update_schema = AwesomeSchema(partial=awesome_fields - ('foo', 'bar'))
```

**Comment by azzamsa** [comment]
nice idea, it works.

But, don't forget to add `comma` in after las value `('foo', 'bar',)`
