### ISSUE TITLE
How to specify type for a method field, if type is a class/schema?

### ISSUE THREAD

**Issue by kettenbach-it** [marshmallow-code/marshmallow#1638]
This works:

```
pricerange = ma.fields.Method("get_pricerange")
@classmethod
    def get_pricerange(cls, obj: Sample):
        .... do some things ....
        return PricerangeSchema().dump(the_things_I_calculated)
```

but the apispec will not contain a type for "pricerange". How can I supply the type/schema "PricerangeSchema" for pricerange

**Comment by deckar01** [comment]
You should be able to override a field descriptor for apispec.

https://apispec.readthedocs.io/en/latest/special_topics.html#adding-additional-fields-to-schema-objects

```py
spec.components.schema("Product", component={"pricerange": "PricerangeSchema"}, schema=ProductSchema)
```

**Comment by kettenbach-it** [comment]
Thx!
