### ISSUE TITLE
Performance improvement: cache results of inspect

### ISSUE THREAD

**Issue by diwu1989** [marshmallow-code/marshmallow#164]
These two lines showed up in my profile to find ways to speed up marshmallow

```
inspect.py:804(getargspec)         <-  100000    0.211    0.979  utils.py:343(get_func_args)
inspect.py:744(getargs)            <-  100000    0.360    0.555  inspect.py:804(getargspec)
```

I think it's possible to LRU cache the inspect results so that when we serialize a list of objects with the same functions, it doesn't have to pay the inspection cost over and over again.

**Comment by sloria** [comment]
@diwu1989 Are you using a Method field? The call to `get_func_args` was removed from `fields.Method._serialize`, so performance should be much improved.

**Comment by sloria** [comment]
The usage of `get_func_args` has also been removed from deserialization.

**Comment by sloria** [comment]
As of 2.0.0b3, the only place `utils.get_func_args` is used is in `Function` fields. To save those calls, use a `Method` field instead.

Closing this for now, since the proposed optimization is no longer necessary.
