### ISSUE TITLE
Why validation does not occur on serialization in 3.X?

### ISSUE THREAD

**Issue by hurcy** [marshmallow-code/marshmallow#1646]
Hi,

I'm trying to upgrade to version 3.X.
I've used different naming conventions for variables in serialization.
For example, 
latestAdmission = fields.DateTime(attribute="latest_admission")

Since I have different variable names, I can't validate using the load function.
https://marshmallow.readthedocs.io/en/stable/upgrading.html#validation-does-not-occur-on-serialization
Can I use `validate` instead of `load`?

**Comment by lafrech** [comment]
I'm afraid the example in the docs only works in simple cases (e.g. no field renaming, no default value,...).

**Comment by sloria** [comment]
A core assumption is that validation happens prior to serialization. Validating on serialization just adds significant performance overhead. More discussion in this issue: https://github.com/marshmallow-code/marshmallow/issues/1132
