### ISSUE TITLE
Schema parameter 'only' overrides other options

### ISSUE THREAD

**Issue by lustdante** [marshmallow-code/marshmallow#165]
Is this intended behavior?

I made RESTful API so that customer can make request with customize fields.

Despite setting exclude to hide sensitive properties, providing the field in only still allowed schema to dump the properties.

**Comment by sloria** [comment]
Indeed, `only` takes precedence over `exclude`. You raise a valid point, though; the `only` parameter is typically used for filtering in HTTP APIs, and I don't see any reason `exclude` should not be respected.

Will look into this further.
