### ISSUE TITLE
It seems better changing the validate module to "validators"

### ISSUE THREAD

**Issue by looker53** [marshmallow-code/marshmallow#1650]
suggestion:

change marshmallow.validate.py   to   marshmallow.validators.py

I got confused when I used the module and the "validates" decorator.

**Comment by sloria** [comment]
I'm not sure it's worth a breaking change. I think the original idea was to follow English "verb-object" grammar ("validate Email"->`validate.Email()`).

More info on the naming of `validates=` here: https://github.com/marshmallow-code/marshmallow/issues/645
