### ISSUE TITLE
Access schema fields on class level

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/marshmallow#1652]
Hi all,
I tried some stuff with this library and had the requirement to dynamically get the the data key of a field in a schema. This would avoid duplicate strings as shown below:

```python
from marshmallow import Schema, fields, validates_schema
class Sample(Schema):
  foo = fields.Str(data_key="bar")

  @validates_schema
  def validate(self, data, **_):
    # id data[Sample.foo.data_key]
    if data["bar"]:
      pass
```

If I use the direct access _Sample.foo.data_key_ the access fails with _AttributeError: type object 'Sample' has no attribute 'foo'_.
Is this blocked by purpose?

Best regards,
Kai

**Comment by lafrech** [comment]
See #1628.

**Comment by ghost** [comment]
Thanks
