### ISSUE TITLE
How can I use the default value instead of None?

### ISSUE THREAD

**Issue by FRiMN** [marshmallow-code/marshmallow#1655]
I have schema like this:
```python
class ContentData(Schema):
    links_in_count = fields.Int(allow_none=True)
```
And data for loading like this:
```python
{'links_in_count':None}
```
How do i get `0` (like default value) instead of `None`?
Expected dump:
```py
{'links_in_count':0}
```

`default` and `missing` dont work.

I have tried using `post_dump` decorator, but it looks like it is not being executed:
```python
class NullProcessingSchema(Schema):
    @post_dump
    def null_to_default_value(self, data: dict):
        return {
            key: 0 for key, value in data.items()
            if key == 'links_in_count' and value is None
        }

class ContentData(NullProcessingSchema):
    links_in_count = fields.Int(allow_none=True)
```

**Comment by lafrech** [comment]
`allow_none` and `missing` are used on load.

`default` is used on dump

`missing` and `default` are used if there is no value in the input. Not `None`, just no value.

You need a custom processor for what you're trying to achieve. You're on the right track.

It's unclear whether you're loading or dumping. If dumping, I think your code should work. Although I'd add a

    else key: value

statement for the other fields.

**Comment by FRiMN** [comment]
> It's unclear whether you're loading or dumping

I loading.

**Comment by lafrech** [comment]
Then you should use a `post_load` decorator.

**Comment by FRiMN** [comment]
Yes, I tried `post_load` instead `post_dump` and its work!
Thanks!
