### ISSUE TITLE
drop invalid nested schema

### ISSUE THREAD

**Issue by tvallois** [marshmallow-code/marshmallow#1660]
Hello,

Thanks for the job done with Marshmallow !

I'm trying to delete every schema invalid in a nested schema instead of raising a `ValidationError` but i don't know if it's possible "natively" with Marshmallow.

```python
class PlayerSchema(Schema):
    email = fields.String(required=True, validate=my_class_to_validate_email)

class TeamSchema(Schema):
    players = fields.Nested(PlayerSchema, many=True)
```

I'd like to drop every player from the team that don't have a valid email address.
A workaround i've found is just to validate data on a `post_load` method like:

```python
class PlayerSchema(Schema):
    email = fields.String(required=True, validate=my_class_to_validate_email)

class TeamSchema(Schema):
    players = fields.List(fields.Dict)

    @post_load
    def remove_invalid_players(self, data, **kwargs):
        """ my logic to remove keys from data """
```

Thanks !

**Comment by lafrech** [comment]
Depending on your use case, another option could be to catch the ValidationError, inspect the errors and use the valid data attached to the exception.

**Comment by tvallois** [comment]
Ok thanks for the answer @lafrech . I close the issue.
