### ISSUE TITLE
Multiple aliases for field

### ISSUE THREAD

**Issue by loscil06** [marshmallow-code/marshmallow#1667]
I know you can specify the name of name of the dict key in the external representation i.e `data_key`. My question is: is it possible to declare multiple aliases for argument `data_key`?
Example:
```
from marshmallow import Schema, fields

class Item(Schema):
    """Schema definition for Item."""

    sku = StringRelaxed(required=True, data_key='SKU')
    stock = fields.Integer(required=True, data_key='Stock')
    price = fields.Float(required=True, data_key='Precio')
   state = fields.String(required=True, data_key=['State', 'Region', 'region', 'locality'])
```
I checked the source code and `data_key` accepts `str`.
I think this would be pretty neat for translating similarly payloads that differ slightly from one another.

**Comment by sloria** [comment]
This isn't currently supported by marshmallow and not something we'll likely add in the future because it would add significant complexity to the codebase for a usage pattern that isn't common.

I imagine you could use a `pre_load` to pre-preprocess the input data to meet this use case.
