### ISSUE TITLE
Limit output when the are too many validation errors on schemas with many=True

### ISSUE THREAD

**Issue by pgp** [marshmallow-code/marshmallow#1671]
Do not know if there's already some way to do it. Ideally, if I have a schema, with an array nested field (many=True), and this array has a huge number of items (kilos to Millions), I'd like to show only the first or the first few error occurrences in case of validation errors.

**Comment by lafrech** [comment]
I'd say this belongs to client code, the layer above marshmallow that prints / returns errors to the users.

The benefit of doing it in marshmallow could be to avoid adding the errors to the error structure in the first place rather than truncating it afterwards, but I'm not sure the use case is worth the added complexity and API surface.

**Comment by pgp** [comment]
Surely one can do any kind of postprocessing on the resulting json string, from trivially truncating it to n bytes, to deserializing the json and limiting the array content.. But, talking about performance, this is terrible in the described scenario (a lot of items - high memory footprint), w.r.t. having this feature available in the library, and avoiding creating one such big response at all.

**Comment by lafrech** [comment]
You don't have to deserialize the json string. Marshmallow returns the errors as dict, not string.

How would you expect the feature to work? What would happen after N errors? Stop loading? Continue loading without storing errors? Continue loading without storing errors but incrementing an errors counter?

**Comment by pgp** [comment]
Well, in my scenario the best option would be to stop loading at all... If I expose a service and someone sends a lot of garbage (and, since there are a lot of people who don't even bother to read API docs, this scenario is much less rare than one could imagine), a hint about first errors is more than enough... Just in the same way GCC does with the switch -fmax-errors=N

**Comment by sloria** [comment]
I don't think this belongs in marshmallow core. It's the responsibility of user code to decide which data to validate and ultimately display the validation errors.
