### ISSUE TITLE
Undocumented behavior of Nested field

### ISSUE THREAD

**Issue by danields761** [marshmallow-code/marshmallow#1677]
Hello,

Recently i noticed, that writing `foo = Nested(lambda: BarSchema)` is incorrect according to documentation, but still working. I am proposing to make it legal and documented behavior, no further changes is required except docs and type hints.

Consider such example as main rationale for this change:

```python
class BarSchema(Schema):
    foo = Nested(lambda: FooSchema)

class FooSchema(Schema):
    ...
```

**Comment by sloria** [comment]
Right, that usage works but is intentionally undocumented because I'm not sure it's something we want to support in the future.

This should work just as well:

```python
class BarSchema(Schema):
    foo = Nested(lambda: FooSchema())

class FooSchema(Schema):
    ...
```

While we don't necessarily have plans to drop support for `Callable[[], Type[Schema]]`, support may be dropped in a future release without a major version bump.

**Comment by danields761** [comment]
@sloria, thank for response!

My first message wasn't clear: you can pass callable which returns a `Schema` type to resolve forward reference issue. You can also use string to specify future declared schemas, but it is not right in my opinion for number of reasons. 

Your example resolves this issue as well, but there is readability concern. You must pass schema arguments to constructor right in callable, but when schema reference is available, you can pass arguments in `Nested` constructor. That just doesn't look consistent. Consider following example showing this inconsistency:

```python
class FooSchema(Schema):
    nested1 = Nested(AboveDeclaredSchema, many=True)
    nested2 = Nested(lambda: FutureDeclaredSchema(many=True))
```
