### ISSUE TITLE
Callable as a Field

### ISSUE THREAD

**Issue by amin-nejad** [marshmallow-code/marshmallow#1681]
I am trying to add a function/callable as a field in and of itself. Not a `fields.Function` where the function returns the value, I want the value to be the callable function, e.g.:

```python
def foo(a, b):
    return a + b
```
The only related issue I've found on this is #662 where `fields.Constant` is used but this method no longer appears to work. I just get the error `TypeError: Object of type function is not JSON serializable`.

Is there a way to do this?

Thanks

```
python==3.7.6
marshmallow==3.7.1
```

**Comment by lafrech** [comment]
The point of a marshmallow field is to express a way to serialize a Python object into JSON.

Serializing a float is straightforward. Serializing a datetime requires defining how to express it in plain JSON (e.g. "ISO8601 2020-10-20T21:45:50Z").

To serialize your function, you'd need to craft a custom field implementing some kind of coding of your choice. For instance, to encode second degree polynomial functions ("y = ax + b"), you could decide to encode the function using its coefficients ("a,b").

I don't see a reasonably simple way to serialize any arbitrary function.

The question you need to ask yourself is what JSON output you expect.

(But maybe this is not what you're trying to achieve. It's not perfectly clear to me.)

**Comment by amin-nejad** [comment]
Thanks very much for the info @lafrech . I think this means it can't be done the way I wanted as the function I want to encode is not trivial like a polynomial. I will have to find another way
