### ISSUE TITLE
Setting only= after instantiation

### ISSUE THREAD

**Issue by newtoniumx3** [marshmallow-code/marshmallow#1688]
I'm using dependency injection so I receive an instance of the schema in my codebase and can't pass any parameters during instantiation.

I'm trying to do this
```
summary_schema = UserSchema(only=("name", "email"))
summary_schema.dump(user)
```
How could I set the only= after the instance was already setup?
```
summary_schema = UserSchema()
summary_schema.only=("name", "email") # doesnt work
# ...
```

**Comment by sloria** [comment]
This is expected--`only` is not meant to be passed to the ctor. There's an open issue to reify this in https://github.com/marshmallow-code/marshmallow/issues/1281 . So perhaps for your use case you'll probably need to inject schema classes rather than schema instances.
