### ISSUE TITLE
Get current index when using `fields.Nested`

### ISSUE THREAD

**Issue by johachi** [marshmallow-code/marshmallow#1691]
I have an object that I have to deserialize into a Python data type, but to do it all in one go, I think I need to know the index of the current item being processed in the `filed.Nested` method. Please let me try to explain with an example. The example below is simplified and do not convey the "why", but only the "what".

The original JSON looks something like this:
```json
{
    "marsh": [
        {"source": "some text"},
        {"source": "some other text"},
        {"source": "yet some other text"},
    ],
    "mallow": [
        {"source": "hello there"},
        {"source": "general"},
        {"source": "Kenobi"},
    ],
}
```

The python data structure will look something like this
```python
dto.Data(
    dto.Marsh=[
        dto.MagazineSource(magazine="some text"),
        dto.MagazineSource(magazine="some other text"),
        dto.BookSource(book="yet some other text")
    ],
    dto.Mallow=[
        dto.MagazineSource(magazine="hello there"),
        dto.MagazineSource(magazine="general"),
        dto.BookSource(book="Kenobi")
    ]
)
```
I get what data type the object should transform to from a config:

```python
json_data = {
    "first":[ {"source": "some text"}, {"source": "some other text"}, {"source": "yet some other text"}],
    "second": [{"source": "hello there"}, {"source": "general"}, {"source": "Kenobi"}],
}
source_config = ["magazine", "magazine", "book"]
schema = SourceSchema(source_config)
result = schema.load(json_data)
```

I have been able to do this by first changing the keys from `"source"` to correspond to the value in the config and then pass it to `schema.load()`. But I was wondering if there is any way to do this only using marshmallow? I think I know how to do it if I can know where in the list the current item is when being processed in`.Nested` and have the logic there. But I can't really figure out how to get the current index. Is it possible at all?

As I said in the start, the example above is not my real code, and don't translate the "why" someone would want to do it. Only "what" I want to do.

**Comment by lafrech** [comment]
An approach could be tu use a Tuple of Nested fields rather than a List of Nested fields, and to build the schema with a schema factory with the source_config as input. In other words, write a function that reads the source_config and builds the schema accordingly using a Tuple of Nested fields.

**Comment by johachi** [comment]
> An approach could be to use a Tuple of Nested fields rather than a List of Nested fields, and to build the schema with a schema factory with the source_config as input. In other words, write a function that reads the source_config and builds the schema accordingly using a Tuple of Nested fields.

Thank you very much for your reply and suggestion! This solution required quite a lot of refactoring of my original code but I was able to get it working!

I also had to add a `@post_load` to change the tuple to a list. But I will probably refactor some more to keep everything as a tuple the whole way (it is not being modified so using a tuple might actually be more appropriate).

I will close this issue now since I got a solution.
Thanks again!
