### ISSUE TITLE
Where should I put my validation when using Marshmallow?

### ISSUE THREAD

**Issue by theodoresi** [marshmallow-code/marshmallow#1692]
I wonder what is the best practice for validating input and use the data to create some application model?
E.g. I have the following example code, and I want to make sure all the `User` objects created are valid.

Let's say I have the following 2 arbitrary requirements:
1. The city must be `NY` or `ny`
1. the name must be less than 10 characters.

I can think of 2 ways
1. Define `@validates` decorators on `UserSchema` to validate the data (or use `validate` argument on each field, or some other way), and do not instantiate `User` directly. Instead, always create `User` object using the `user_schema` (e.g. write a `create_user` function, and `User` must be created by calling that function, whether the data comes from REST API, CSV files, or command line input)
2. Write validation code inside the `User` class, e.g. make the fields `@property` or write the code directly in `__init__`.

I can see pros & cons from both solutions.

If the `User` class is a SQLAlchemy model, the I can also write the validation code `the SQLALchemy way`.
I wonder is there a preferred way?

```python
from marshmallow import Schema, fields, post_load
import io
import csv
import datetime as dt


class User:
    def __init__(self, name, city, birthday):
        self.name = name
        self.city = city
        self.birthday = birthday

    def __repr__(self):
        return f'User(name={self.name}, city={self.city}, birthday={self.birthday})'


class UserSchema(Schema):
    name = fields.Str()
    city = fields.Str()
    birthday = fields.DateTime()

    @post_load
    def make_user(self, values, **kwargs):
        return User(**values)


user_schema = UserSchema()
users_schema = UserSchema(many=True)


def create_users_from_api():
    post_user_json = '''{
        "name": "Frank",
        "city": "NY",
        "birthday": "1970-07-07T00:00"
    }'''
    return user_schema.loads(post_user_json)


def create_users_from_csv():
    user_csv = io.StringIO(
        'name,city,birthday\n'
        'Lack,NY,1980-08-08\n'
        'Luke,NY,1990-09-09\n'
    )
    csv_reader = csv.DictReader(user_csv)
    return [User(
        each['name'],
        each['city'],
        dt.datetime.strptime(each['birthday'], '%Y-%m-%d'))
        for each in csv_reader
    ]


if __name__ == '__main__':
    user = create_users_from_api()
    print(user)

    users = create_users_from_csv()
    print(users)
```

**Comment by deckar01** [comment]
The builtin field validators should cover most use cases.

https://marshmallow.readthedocs.io/en/stable/quickstart.html#validation

`@validates` is for custom, one-off field validation.

https://marshmallow.readthedocs.io/en/stable/quickstart.html#field-validators-as-methods

I recommend putting this functionality in your schema, not your model. Most of what marshmallow does is check that the type and value of incoming data matches the schema. SQLAlchemy handles translating data between a database and your application. Marshmallow is generally used to translate the data between network requests and your application (or other external IO).
