### ISSUE TITLE
It's not clear how to create method on a field

### ISSUE THREAD

**Issue by kaldown** [marshmallow-code/marshmallow#1698]
According to this manual, it's not clear how to attach a method on an exact field:
https://marshmallow.readthedocs.io/en/stable/custom_fields.html

For some reason "method" expect the whole object to be feed.

How to deal if I need to cover all the date fields in an object with the custom deserialization mechanism all at once?
Why does Method get a high-level object, but returns a field?

```
class D(Shema):
  date1 = Method("m1")
  date2 = Method("m2")
  date3 = Method("m3")

  def m1(self, obj):
    return obj.date1.timestamp()

  def m2(self, obj):
    return obj.date2.timestamp()
 ...
```

How to avoid that?
Other than creating custom Field class:
```
class T(fields.Field):
    def _serialize(self, value, attr, obj, **kwargs):
        if not value:
            return None
        return int(value.timestamp())
```

**Comment by sloria** [comment]
A custom `Field` class is the proper way to meet your use case, since it allows you to reuse common formatting behavior across field instances.
