### ISSUE TITLE
How do I use existing objects when deserializing, instead of creating new ones?

### ISSUE THREAD

**Issue by egor83** [marshmallow-code/marshmallow#1707]
I have a model (RequestObj) which has a many-to-many relationship with another model (Tag):
```python
class RequestObj(db.Model):  # type: ignore
    id = db.Column(db.Integer, primary_key=True)
    #...
    # many-to-many relationship
    tags = relationship(
        "Tag", secondary=association_table, back_populates="request_objs",
    )


class Tag(db.Model):  # type: ignore
    __tablename__ = "tags"
    id = db.Column(db.Integer, primary_key=True)

    name = db.Column(db.String(40), nullable=False, server_default="", unique=True)
    color = db.Column(
        db.String(40), nullable=False, server_default="000000"
    )  # HEX representation

    request_objs = relationship(
        "RequestObj", secondary=association_table, back_populates="tags",
    )
```

I managed to make it work in such a way, that deserializing creates new Tags, but that's not what I want - I want RequestObject to use existing Tags.
I tried many different approaches, the last two are here:
https://dpaste.com/5TER6KU4L
https://dpaste.com/8LZCN37EP

Thanks in advance for any help or advice!

**Comment by deckar01** [comment]
I think the main constraint here is that tags that are queried from the database don't need to be deserialized. You could make this a `@post_load` hook that maps the tag names to tag objects and use the string field for tags in the request schema. If you also plan to dump from this request schema you will need a corresponding `@pre_dump` hook to reverse the mapping.

https://marshmallow.readthedocs.io/en/stable/marshmallow.decorators.html#marshmallow.decorators.post_load

If you are trying to make something reusable I would recommend looking into making a custom field to encapsulate these operations. If you still need the tag schema for some reason you can make the tag field a wrapper around the tag schema implementation similar to how the `Nested` field wraps schemas.

https://marshmallow.readthedocs.io/en/stable/custom_fields.html

**Comment by egor83** [comment]
Thanks a million, that worked!

For posterity, the working version is as follows:

```python
class UpdateRequestObjSchema(Schema):  # type: ignore
    #...
    tags = fields.List(fields.Nested(TagIdSchema))

    @post_load
    def load_tags(self, data, **kwargs):
        tags = []
        for tag_id in data["tags"]:
            tag = Tag.get_tag_by_id(tag_id["id"])
            tags.append(tag)
        data["tags"] = tags
        return data

class TagIdSchema(Schema):
    id = fields.Int(required=True)
```

=====================

And the code that called it:

```
def edit_req_obj():
    json_data = {
        # ...
        "tags": [
            {"id": 1},
            {"id": 2},
            {"id": 3},
            ]
        }
    r = requests.patch('http://localhost:5000/requests/1', json = json_data)
```
