### ISSUE TITLE
Add compatiblility layer

### ISSUE THREAD

**Issue by harlowja** [marshmallow-code/marshmallow#171]
It'd be pretty nice to have versions associated with objects and have marshmallow be able to handle the request for an older version; similar to what this code is doing @ https://github.com/openstack/oslo.versionedobjects/blob/master/oslo_versionedobjects/base.py#L452 (that code is openstack specific, and it seems quite similar to marshmallow in general); 

Maybe there is room for this kind of feature in marshmallow?

**Comment by harlowja** [comment]
Some other examples of this similar to marshmallow library:

https://github.com/openstack/nova/tree/master/nova/objects

**Comment by sloria** [comment]
Object versioning is outside of marshmallow's scope and will not be added in the near future. Thank you for the suggestion, though.
