### ISSUE TITLE
[Question] how to define a generic schema

### ISSUE THREAD

**Issue by will-beta** [marshmallow-code/marshmallow#1710]
Here is the codes I write:

```python
T=TypeVar('T')
class Wrap(Schema, Generic[T]):
    error_code=fields.Int()
    error_msg=fields.Str()
    data=fields.Nested(T)
```
Received following error messages:
```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

Thanks in advance.

**Comment by sloria** [comment]
Schemas should not subclass `Generic`. Eventually we may add support for type arguments to `Schema` (e.g. `Schema[LoadType, DumpType]`, but no plans for that in the near-ish future.

**Comment by FeryET** [comment]
Is there still no plan to support this feature? I think this can help us get rid of a good deal of boilerplate code. I can contribute if there was any need.

**Comment by deckar01** [comment]
https://github.com/daniil-berg/marshmallow-generic

**Comment by YaoJusheng** [comment]
Are there any updates currently?
