### ISSUE TITLE
Metadata dict is shared between all field instances

### ISSUE THREAD

**Issue by veyu** [marshmallow-code/marshmallow#1711]
I stumbled upon behaviour which is really confusing for me and I am not sure is it intended or is it a bug...

When I declare my schema I am adding `unique` parameter which is telling me that this field should be unique across all rows/entries which I am validating (this check is done by my custom code). I wanted something stored in schema and `metadata` looked like I could use them for it.
But when I started writing tests for my app (and changing `unique` parameter for these tests) all tests after ones which changed `metadata` went wrong. I discovered that even if there are two `Schema` objects created, fields share their `metadata` with all other instances of the same field (I was using `id()` built-in to check object addresses).

Could you help me with this? Is this correct behaviour? Did I mess something? Or miss some crucial information?

Here are my observation based on code from reproduction steps (below):
```
------ a ------
4403674848 # id(a)
4403685376 # id(a.fields)
4403674704 # id(a.fields['id'])
4403311360 # id(a.fields['id'].metadata)
------ b ------
4403674656 # id(b)
4403514496 # id(b.fields)
4403674512 # id(b.fields['id'])
4403311360 # id(b.fields['id'].metadata)

------ malicious behaviour ------
a.fields['id'].metadata={'unique': True}
b.fields['id'].metadata={'unique': True}
change metadata > a.fields['id'].metadata['unique'] = False
a.fields['id'].metadata={'unique': False}
b.fields['id'].metadata={'unique': False}
```

**Steps to reproduce:**
```python
from marshmallow import Schema, fields, validate

class MySchema(Schema):
    id = fields.Str(
        required=True,
        validate=validate.Length(1, 36),
        unique=True,
    )

a = MySchema()
b = MySchema()

print(f"{a.fields['id'].metadata=}")  # {'unique': True}
print(f"{b.fields['id'].metadata=}")  # {'unique': True}

# change metadata for object `a`
a.fields['id'].metadata['unique'] = False

print(f"{a.fields['id'].metadata=}")  # {'unique': False}
print(f"{b.fields['id'].metadata=}")  # {'unique': False}
```

**Environment:**
```
marshmallow=3.9.1
python=3.9.0
```

**Comment by lafrech** [comment]
I think this is intended.

Metadata is meant to be set at class level and not modified at instance level.

You may subclass a schema class to provide custom metadata to a new schema by overriding its Meta class (make sure to let the child Meta inherit from parent Meta if any, otherwise meta from parent is lost).

```py
class ChildSchema(ParentSchema):
    class Meta(ParentSchema.Meta):
        unique = True
```

**Comment by veyu** [comment]
Thanks for really quick answer @lafrech !
I am not sure if I understood your advice. When I will do inheritance like you did, it will give me `unique` parameter in metadata for `Schema` instances, right? It won't be per field?

I want to define Schema where I will be able to add `unique` parameter per field. And I would like it to be tied to instance of Field (not class, like it is right now).

**Comment by lafrech** [comment]
My answer was quick but totally off-topic. I misread your question. Scratch that.

Still, metadata is relative to a class, not instance, for fields as well. It is not meant to be modified.

From the description of the problem, it looks like this is only a problem for your tests. You could rewrite the tests to create a different schema. Or make the metadata change in a context manager that would restore the initial value at the end of the test.

If you really need to customize this at runtime, you could use a schema factory to build a new schema class on the fly. This way, each schema would have a different field instance. This sounds a bit like too much trouble but it depends on the use case.

Do you see this behaviour as a real blocker or did you just find it surprising and wanted to share it here in case it would be a bug?

**Comment by veyu** [comment]
No worries. I will try different way of implementing this functionality - probably will switch to using class field to store list of fields which should be unique. I do not implement my functionality as extension of Schema but use composition so will just rewrite list of unique fields defined in schema to container object as instance variable. That way it should be easy to modify it for test purpose.

About behaviour itself - I don't think it's blocker. Like you wrote - it's surprising and at first I thought it could be bug.
Maybe would be good to mention it in documentation, but if I am first person which found this as a problem then it's not so critical.

Anyway, thanks for explaining this to me :) I will close issue now.
