### ISSUE TITLE
How to ignore validate missing value?

### ISSUE THREAD

**Issue by byte-voyager** [marshmallow-code/marshmallow#1717]
```
class PutUsersProfile(BaseSchema):
    password = fields.Str(required=False, missing='', validate=validate.Length(min=8, max=16))
```

I want check the length when the password exists, ignore the check when it does not exist?

**Comment by lafrech** [comment]
I think it works if you remove the `missing` argument. Then the field will be left empty and not validated.

It looks like you want the field to be either an empty string or a 8-16 length string. If you really want this (a string of length 0 or 8, 9, 10,... 15, 16), you need to create a custom validator.

You may take inspiration in or even subclass `Length`.

https://github.com/marshmallow-code/marshmallow/blob/dev/src/marshmallow/validate.py#L267-L330

**Comment by byte-voyager** [comment]
when i remove missing, it still validate the length
```
password = fields.Str(required=False, validate=validate.Length(min=8, max=10))
```
got a length exception

**Comment by byte-voyager** [comment]
Often when submitting a form on the front end, if it is not passed, then set the default to a blank string. If it is passed, then I need to verify this parameter. Many times I need to do this. Marshmallow will automatically verify the missing value, and there seems to be no option. Can control not to check the missing value. But it seems that I need to implement the validator myself. Is there a better way?
Example Code:

Schema:
```
class PutUsersProfile(BaseSchema):
   nickname = fields.Str(required=False, missing='', validate=validate.Length(min=2, max=10))
    password = fields.Str(required=False, validate=validate.Length(min=8, max=10))
```

```
nickname = get_schama_data('nickname')
password = get_schama_data('password')
if nickname:
    user.nickname = nickname
if password:
    user.password = password
...
user.save() # update database
```

**Comment by lafrech** [comment]
If a field is missing, it is not validated. I just checked.

You case is different. The empty string is added by the front-end, not by the `missing` attribute.

What you need to do is remove empty strings.

There's been discussion about this before.

https://github.com/marshmallow-code/marshmallow/issues/543
https://github.com/marshmallow-code/marshmallow/issues/583
https://github.com/marshmallow-code/marshmallow/issues/713

**Comment by byte-voyager** [comment]
> If a field is missing, it is not validated. I just checked.
> 
> You case is different. The empty string is added by the front-end, not by the `missing` attribute.
> 
> What you need to do is remove empty strings.
> 
> There's been discussion about this before.
> 
> #543
> #583
> #713

yes, the empty string is added by the front-end. Thanks

**Comment by byte-voyager** [comment]
My temporary solution
```
class PutUsersProfile(BaseSchema):
    password = fields.Str(required=False, missing='')

    @validates('password')
    def validate_password(self, value):
        if not value:
            return
        if 6 <= len(value) <= 16:
            return
        raise ValueError('length error')
```

**Comment by sloria** [comment]
You could also pass `validate=validate.Length(min=6, max=16)` to your field to do the length validation.
