### ISSUE TITLE
Finding a way to "partial update" a nested dictionary using schemas

### ISSUE THREAD

**Issue by cyberpion-yotam** [marshmallow-code/marshmallow#1723]
Hey,
I was wondering if there are built-in/known ways of updating nested dictionaries, using the schema structure in Marshmallow.
For example:
```python
class NestedSchema(Schema):
    field_c = fields.String()
    field_d = fields.String()

class SchemaA(Schema):
    field_a = fields.String()
    field_b = fields.Nested(NestedSchema())

dictionary = {
    "field_a": "value1",
    "field_b": {
        "field_c": "value2",
        "field_d": "value3"
        }
    }
}

# This operation results in losing "field_d" (overwrites the nested dictionary)
dictionary.update({"field_b": {"field_c": "new_value"}})
```

Coming from Django, where the "update" is implemented in the serializer, I was wondering if there are any known ways of using the Schema to allow for "patching" fields?

Thanks!

**Comment by lafrech** [comment]
I don't know Django and I don't think there's anything related to this in marshmallow.

We use a dedicated utils func to do this in apispec and flask-smorest:

https://github.com/marshmallow-code/apispec/blob/16690aea218c70b4fd59caa5cfeff2be820a6bc7/src/apispec/utils.py#L161-L172

https://github.com/marshmallow-code/flask-smorest/blob/c230420c5ee37684950b6f00ac2ff4167ecad3e7/flask_smorest/utils.py#L10-L23

See related SO question and answers: https://stackoverflow.com/questions/3232943/.

**Comment by cyberpion-yotam** [comment]
Thanks for the quick reply!
What I was wondering, is because Marshmallow "knows" the object/dictionary, it could help update non-nested fields - overwrite Dict() fields and others, but leave Nested() fields to have their own update() method.
Just a thought. 
If you don't think this could be helpful feel free to close this issue (and thanks for the great reply).

**Comment by sloria** [comment]
Unlike DRF serializers, marshmallow `Schema` classes are not responsible for updating your business objects. This is by design. Your controller logic should do this after deserializing.
