### ISSUE TITLE
String field should support case transform

### ISSUE THREAD

**Issue by b0urb0n** [marshmallow-code/marshmallow#1724]
I would like the ability to define a `marshmallow.fields.String` that supports case transformation during (de)serialization.

Sometimes I've found it necessary to convert input/output to uppercase and lowercase.  Most commonly, I convert all hash digests to lowercase regardless of the case I get from a user.

I generally solve this with something simple:
```python
class StringLower(fields.String):
    """
    A ``marshmallow.field.String`` that is converted to lowercase
    """
    case = 'lower'

    def _deserialize(self, value, attr, data, **kwargs) -> AnyStr:
        try:
            return getattr(value, self.case)()
        except AttributeError as e:
            raise fields.ValidationError("Input must be a string") from e

    def _serialize(self, value, attr, obj, **kwargs) -> AnyStr:
        try:
            return getattr(value, self.case)()
        except AttributeError as e:
            raise fields.ValidationError("Input must be a string") from e


class StringUpper(StringLower):
    """
    A ``marshmallow.field.String`` that is converted to uppercase
    """
    case = 'upper'

```

It would be nice to be able to define a `String` field that did this automatically:
```python
class SomeSchema(Schema):
    upper_str = fields.String(transform='upper')
    lower_str = fields.String(transform='lower')
```

**Comment by sloria** [comment]
I don't think this needs to be added to core. You can use custom fields or even write wrapper fields. See [here](https://github.com/marshmallow-code/marshmallow/issues/1391#issuecomment-530357070) for an example.
