### ISSUE TITLE
schema.py module type annotations

### ISSUE THREAD

**Issue by vemikhaylov** [marshmallow-code/marshmallow#1728]
Is there a reason why type annotations are missing for some methods in `schema.py` (e.g. return types of `dump` and `load` methods)?

https://github.com/marshmallow-code/marshmallow/blob/4ee651014205155292249667fe70b1e646ec6d5d/src/marshmallow/schema.py#L530

However, there are some good old docstrings:

https://github.com/marshmallow-code/marshmallow/blob/4ee651014205155292249667fe70b1e646ec6d5d/src/marshmallow/schema.py#L538

Which can actually mislead IDEs and novices:

<img width="584" alt="marshmallow_dump_type_annotation" src="https://user-images.githubusercontent.com/38596482/105756325-80a7a600-5f5d-11eb-98c7-71df2df041ee.png">

Sphinx maintain the following [thing](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#python-signatures) if it's the reason:

> Multiple types in a type field will be linked automatically if separated by the word “or”

If it's just a bug, I would be happy to create the PR.

**Comment by deckar01** [comment]
What type checker are you using?

> Any function without annotations should be treated as having the most general type possible, or ignored, by any type checker.

https://www.python.org/dev/peps/pep-0484/#the-meaning-of-annotations

Sphinx notation is listed as a "rejected alternative" to annotations.

https://www.python.org/dev/peps/pep-0484/#other-backwards-compatible-conventions

I believe the correct return type is `Any`, because the `@post_dump` decorator does allow the user to return anything. The sphinx docstring should probably be removed or corrected.

**Comment by vemikhaylov** [comment]
> What type checker are you using?

That's the PyCharm's one.

**Comment by deckar01** [comment]
I would recommend removing the 2 `:rtype:` declarations since they aren't used anywhere else in the code base. That should cause PyCharm to fall back to assuming the return type is `Any`. Can you test this theory in PyCharm?

> If it's just a bug, I would be happy to create the PR.

That would be greatly appreciated. Thank you!

**Comment by vemikhaylov** [comment]
> Can you test this theory in PyCharm?

Yes, the warning went when I removed the `:rtype:` declaration. Review the PR, please :)
