### ISSUE TITLE
Question: Is this an undocumented feature? Double underscore (`__x`) field name to append its class name

### ISSUE THREAD

**Issue by den4uk** [marshmallow-code/marshmallow#1734]
I have been looking for a way to record instance's own class, and accidentally made this undocumented discovery:

```python
import marshmallow
from dataclasses import field
import marshmallow_dataclass


@marshmallow_dataclass.dataclass
class MD:
    # Example with dataclass
    name: str
    __klass: str = field(default=None, repr=False)


class MS(marshmallow.Schema):
    # Example with pure marshmallow
    name = marshmallow.fields.String()
    __klass = marshmallow.fields.String(default=None)


i = MD(name='Denis')
d = i.Schema().dump(i)
# {'_MD__klass': None, 'name': 'Denis'}

s = MS().dump({'name': 'Denis'})
# {'_MS__klass': None, 'name': 'Denis'}
```

> From example to note: when a field is created with a double underscore in front of it, it gets appended with what seems like `f"_{self.__class__.__name__}"`.

Interestingly, I needed a _unique_ key in the payload, which would work with deserializing against multiple schemas with Union, and finding a matching class to deserialize my objects with. This behaviour works perfectly for my case (linked issue https://github.com/marshmallow-code/marshmallow/issues/1705).

- However I am unsure if this is an intended behaviour or not? I would like it to remain please 😄 
- Are you able to point me to the source code where this happens? I would like to understand how this is done.
- Could this be added to the documentation?

Many thanks!

**Comment by lafrech** [comment]
I think what you're seeing is the consequence of how Python deals with double underscores.

https://stackoverflow.com/questions/1301346/what-is-the-meaning-of-single-and-double-underscore-before-an-object-name

And I think what you're trying to achieve is polymorphism.

https://github.com/marshmallow-code/marshmallow/issues?q=is%3Aissue+label%3Apolymorphism

You may want to try [marshmallow-oneofschema](https://github.com/marshmallow-code/marshmallow-oneofschema).

**Comment by den4uk** [comment]
Thanks @lafrech for your answer, I will look into that.

I tried `marshmallow-oneofschema`, however it doesn't seem to work with `marshmallow-dataclass`, that is primarily used in my case.
