### ISSUE TITLE
Question: How to deserialization [(obj, “str”), (obj, “str”), (obj, “str”), …]

### ISSUE THREAD

**Issue by thp44** [marshmallow-code/marshmallow#1736]
I'm working with an existing mssql database, where I'm not able to make any changes. Trying to make an API using Flask and Marshmallow. I have some issues deserializing the following query returning all people working on a project.

```
query = (
        sa.session.query(Employee, sa.func.sum(JobEntry.number_registered).label("total"))
        .join(JobEntry, Employee.employee_hashkey==JobEntry.employee_hashkey)
        .filter(JobEntry.project_number==f'{project_number}')
        .group_by(Employee)
    ).limit(3).all()
```
The query returns
```
print(query)
[(<Employee 188ED6A858997A48FDA53A404779A16F>, 229.0), (<Employee 1D40AB9C2A973C2BD33B1EF6108D2A70>, 2.0), (<Employee 38584E42E883131DC35151E4922A8094>, 176.75)]
```
The Employee contains the name, id, etc. How would I create a marshmallow schema returning, the following example.

```
[
    {"name": "somename a", "total" 229.0, "id": 11},
    {"name": "somename b", "total" 2.0, "id": 22},
    {"name": "somename c", "total" 176.75, "id": 33}
]
```
Being a noob, I have experimented a bit... The following code returns almost what I want. But I get "Employee." in my keys ...

```
class ProjectUsersSchema(Schema):
class Meta:
    model = Employee

    fields = (
        "Employee.name",
        "Employee.id"
        "total"
    )

# returns "[{"Employee.name": "somename a", "total" 229.0, "Employee.id": 11}, ..."
```

**Comment by lafrech** [comment]
Sounds like a job for [Pluck](https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Pluck) field.

Please try

```py

class ProjectUsersSchema(Schema):
    class Meta:
        model = Employee

    fields = (
        "Employee.name",
        "Employee.id"
    )

class EmployeeSchema(Schema):
    name = fields.Pluck(ProjectUsersSchema, "name")
    id = fields.Pluck(ProjectUsersSchema, "id")
    total = fields.Float()
```

**Comment by thp44** [comment]
@lafrech Thanks for the quick answer! 

Unfortunately, it didn't do the trick. I tried different variations. 

Is it maybe be possible to add 'total' to the Employee object in the sqlalchemy query?

**Comment by thp44** [comment]
Okay... I made a temporary fix using nested schemas where I also convert snake_case to PascalCase. 
I don't close this. This seems too much of a hack and I hope someone may know a proper solution. :-) 

PascalCaseSchema with added fix:  .split(".")[-1]
```
def pascalcase(s):
    part_lst = s.split(".")[-1].split("_") # todo fix split(".")[-1] 
    if len(s) <= 2:
        return "".join(i.upper() for i in part_lst)
    return "".join(i.title() for i in part_lst)


class PascalCaseSchema(ma.SQLAlchemyAutoSchema):

    def on_bind_field(self, field_name, field_obj):
        field_obj.data_key = pascalcase(field_obj.data_key or field_name)`
```
ProjectUsersSchema:
```
class ProjectUsersSchema(PascalCaseSchema):
    class Meta:
        model = Employee
    
        fields = (
            "Employee.name",
            "Employee.id"
            "total"
        )
# returns "[{"Name": "somename a", "Total" 229.0, "ID": 11}, ..."
```

**Comment by thp44** [comment]
[Defining the schema explicit solves the problem](https://github.com/marshmallow-code/marshmallow/issues/1748#issuecomment-796703431). Would still like a solution to an implicitly defined schema... 
But I'm closing this issue.
