### ISSUE TITLE
Mathematical validation for Fields.Number (greater than, lesser than, etc.)

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [marshmallow-code/marshmallow#1740]
First thank you for this project, very useful, 

I'm in a somewhat sciency environment and I would need more validation on number in order to really use marshmallow to the fullest. I'm thinking about maybe adding multiple arguments (greater, lesser, greater_or_equal, lesser_or_equal) to `fields.Number`

    power_kw = fields.Float(default=1e10, greater_than=1e5)

Or maybe a condition field 

    power_kw = fields.Float(default=1e10, condition=">=1e5")

Would you merge this kind of change if I open a merge request for it ? Do you have an opinion on the design ?

Thanks in advance.

**Comment by lafrech** [comment]
This is already possible with validators.

See [Range](https://marshmallow.readthedocs.io/en/stable/marshmallow.validate.html#marshmallow.validate.Range) validator.

From https://marshmallow.readthedocs.io/en/stable/quickstart.html#validation

```py
from pprint import pprint

from marshmallow import Schema, fields, validate, ValidationError


class UserSchema(Schema):
    name = fields.Str(validate=validate.Length(min=1))
    permission = fields.Str(validate=validate.OneOf(["read", "write", "admin"]))
    age = fields.Int(validate=validate.Range(min=18, max=40))
```

It is more verbose than your example, though.

**Comment by deckar01** [comment]
If you are interested in creating a project to share your validators, we can add it to the ecosystem wiki to help users discover them.

https://github.com/marshmallow-code/marshmallow#ecosystem

**Comment by Pierre-Sassoulas** [comment]
Thank you for all the examples, I should have read the documentation better :)

I'll keep that in mind if I do some custom field, thank you.
