### ISSUE TITLE
String field does not accept 1:00:00

### ISSUE THREAD

**Issue by hanwen-pcluste** [marshmallow-code/marshmallow#1741]
Hello,

When we use `1:00:00` as the value of a field that is defined as `fields.Str()` in a schema, I will get validation error: Not a valid string. Therefore we would like to know if this is considered as a bug or you imposed stricter rules for `fields.Str()`?

With some basic debugging we found that when arriving at the code [here](https://github.com/marshmallow-code/marshmallow/blob/dev/src/marshmallow/fields.py#L840), the `1:00:00` has been converted to `3600`, resulting in incompatible type.

If this is the expected behavior, is there a way I can read `1:00:00` as a string?

Thank you!
Hanwen

**Comment by lafrech** [comment]
Please provide a reproducible example.

```py
import marshmallow as ma


class S(ma.Schema):
    f = ma.fields.Str()


print(S().load({"f": "1:00:00"}))
# {'f': '1:00:00'}
```

**Comment by hanwen-pcluste** [comment]
Thank you for replying. It is indeed a bug on my side.
When we use `yaml_content = yaml.load(conf_file, Loader=yaml.SafeLoader)` to read a `yaml` file, it automatically converts `1:00:00` to an integer 3600. And there is the error when trying to do `S().load(yaml_content)`.
Thank you!
