### ISSUE TITLE
Is there support for list of lists?

### ISSUE THREAD

**Issue by pchtsp** [marshmallow-code/marshmallow#1753]
Hello and thanks for this great library.

We're managing some kind of jsonschema-marshmallow compatibility code and we're having troubles with some cases. For example consider the following jsonschema:

```json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "pairs": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "integer"
                }
            }
        }
    },
    "required": [
        "pairs"
    ]
}
```

It consists of a list of lists of integers.
So the data would look like:
```{"pairs": [ [1, 2], [1, 3], [2, 5] ]}```

Is this something that can be handled by marshmallow ? is there an example?

I was thinking of something like:

```python
from marshmallow import Schema, fields
class Pairs(Schema):
    pairs = fields.List(fields.List(fields.Int))
```

This code does appear to work:

```python
Pairs().load(dict(pairs=[[1, 3], [1, 4, 6]]))
```

But I'm not sure if it's something that's contemplated / supported / etc.

Of course, an alternative is to convert the list of lists into a list of objects:

```
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "nodes": {
            "type": "array",
            "items": {
                "type": "integer"
            }
        },
        "pairs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "n1": {
                        "type": "integer"
                    },
                    "n2": {
                        "type": "integer"
                    }
                },
                "required": ["n1", "n2"]
            }
        }
    },
    "required": ["nodes", "pairs"]
}

```

In this second example the translation is direct. But I do prefer the first example.

**Comment by lafrech** [comment]
> Hello and thanks for this great library.

Hi. Thanks.

```py
from marshmallow import Schema, fields
class Pairs(Schema):
    pairs = fields.List(fields.List(fields.Int))
```

> But I'm not sure if it's something that's contemplated / supported / etc.

It is the way to go. No pb.

**Comment by pchtsp** [comment]
thanks for the response!
