### ISSUE TITLE
a jsonschema importer to marshmallow?

### ISSUE THREAD

**Issue by pchtsp** [marshmallow-code/marshmallow#1754]
I was wondering if this is something that is seen as interesting for the marshmallow package or is too niche.

We're trying to store all our schemas in jsonschema (to be able to share between front-end / back-end and maybe store schemas in a database as json). On the other hand we already use marshmallow for our backend validation and it would be coherent to keep all the validation of the backend with marshmallow.

As of now, we have a *very* hacky migration (https://github.com/baobabsoluciones/cornflow-client/blob/master/cornflow_client/schema_manager.py) from one to the other. Is it something that you see developing inside marshmallow in the future? Is this something that has any interest for you? With some guidelines on where to start, maybe I could prepare a PR with a first version...

I'm aware there is a [marshmallow -> jsonschema project](https://github.com/fuhrysteve/marshmallow-jsonschema). I also created an issue [there](https://github.com/fuhrysteve/marshmallow-jsonschema/issues/136) so I'm guessing you're not planning on including those links inside the core marshmallow code?

thanks again!

**Comment by mrfroebi** [comment]
@pchtsp while building a flask app, I was also hitting the same obstacle, that we are handling all our schemas as JSON files. 

In case, this is something the maintainers think could be a useful enhancement, I would like to support the development.

Thanks for the request, and thanks to the developers for this useful package.

**Comment by lafrech** [comment]
This is definitely not on the roadmap. In any case, it would be a third-party lib.

Of course, anyone coming up with something is more than welcome to share it here.
