### ISSUE TITLE
Question: How best to override/patch the serialization of a schema

### ISSUE THREAD

**Issue by john-bodley** [marshmallow-code/marshmallow#1756]
I'm trying to determine the "best" way of serializing an object for a secondary use case (logging) where the serialization differs slightly from the primary use case (RESTful API). More specifically the schema is using the [inflection](https://marshmallow.readthedocs.io/en/stable/examples.html#inflection-camel-casing-keys) logic (for serializing to camel-case) and [`marshmallow-enum`](https://github.com/justanr/marshmallow_enum) to serialize enums by name, though for the secondary case the schema needs to be dumped using snake-case and enums by value respectively. 

Ideally I don't want to define two near identical schemas and started to venture down the monkey patching route (using mocking) whilst logging,

```python
from unittest.mock import patch

from marshmallow import Schema
from marshmallow_enum import EnumField


def serialize_enum(self, value, attr, obj):
    return value.value if value is not None else None


@patch.object(MySchema, "on_bind_field", Schema.on_bind_field)
@patch.object(EnumField, "_serialize", serialize_enum)
def log(obj):
    send(MySchema().dump(obj))
```  

This kind of worked, though the issue seems to be that I'm using this in a multithreaded environment (Flask with `gevent`) and `unittest.mock` is inherently non-threadsafe) resting a a number of issues.

I also looked into patching actual instances, though this requires actual traversal of nested schemas and requires re-engineering a lot of the existing `dump` logic. Additionally I'm using [`marshmallow-oneofschema`](https://github.com/marshmallow-code/marshmallow-oneofschema) and [`marshmallow-dataclass`](https://github.com/lovasoa/marshmallow_dataclass) which potentially adds another layer of complexity.

My current approach is instead of using the `on_bind_field` approach I reverted to using the `pre_load` and `post_dump` constructs per [here](https://github.com/marshmallow-code/marshmallow/issues/1295#issuecomment-509736493) and leveraging/abusing the `self.context` to determine how the field names are formatted. For enum handling I'm simply monkey patching the `EnumField._serialize` method to take advantage of the same contextual information.

```python
import marshmallow_enum
from marshmallow import post_dump, pre_load, Schema
from marshmallow_enum import LoadDumpOptions
from stringcase import camelcase, snakecase


class BaseSchema(Schema):
    @pre_load
    def to_snakecase(self, data, **kwargs):
        return {snakecase(key): value for key, value in data.items()}

    @post_dump
    def to_case(self, data, **kwargs):
        case = snakecase if self.context.get("to_log") else camelcase
        return {case(key): value for key, value in data.items()}


def serialize_enum(self, value, attr, obj):
    if value is None:
        return None

    dump_by = LoadDumpOptions.value if self.context.get("to_log") else self.dump_by
    return value.value if dump_by == LoadDumpOptions.value else value.name


marshmallow_enum.EnumField._serialize = serialize_enum
```

Is there a better/cleaner way of achieving this?

**Comment by sloria** [comment]
I recommend using the `on_bind_field` pattern, as described here: https://marshmallow.readthedocs.io/en/latest/examples.html#inflection-camel-casing-keys

Something like

```python
class LogSchema(Schema):
    def on_bind_field(self, field_name, field_obj):
        if isinstance(field_obj, EnumField):
            field_obj._serialize = serialize_enum
        field_obj.data_key = snakecase(field_obj.data_key or field_name)

class MySchema(Schema):
    #...

class MyLogSchema(MySchema, LogSchema):
    pass
```

You could even write a helper for generating the log schema classes if you want

```python
class LogSchema(Schema):
    def on_bind_field(self, field_name, field_obj):
        if isinstance(field_obj, EnumField):
            field_obj._serialize = serialize_enum
        field_obj.data_key = snakecase(field_obj.data_key or field_name)

    @classmethod
    def from_schema(cls, schema_cls):
        name = f"Log{schema_cls.__name__}"
        attrs = fields.copy()
        attrs["Meta"] = type(
            "GeneratedMeta", (getattr(cls, "Meta", object),), {"register": False}
        )
        schema_cls = type(name, (schema_cls, cls), attrs)
        return schema_cls


class MySchema(Schema):
    #...

MyLogSchema = LogSchema.from_schema(MySchema)
```

Closing this, but feel free to continue discussing if the above doesn't meet your use case.
