### ISSUE TITLE
Exclude object from List for Schema

### ISSUE THREAD

**Issue by LKS007** [marshmallow-code/marshmallow#1762]
Hello! I faced this issue. I should exclude an object from the list of objects if `object.name` is not equal for one of the variants

For example, I should filter list and stay only objects with name in `[school, university]`
```
[
  {
    name: 'school',
    value: 'Middle School',
  },
 {
   name: 'library',
   value: 'Library №2',
  },
  {
   name: 'university',
   value: 'bad option',
  }
]
```

I can't modify this list to objects, like 
```
{
  'school`: { name...},
  `library': {name...},
  `university`: {name...},
}
```
because the list can contain a lot of school values

Looks like it's very simple, but I can't find the correct way.

**Comment by lafrech** [comment]
`OneOf` validator will fail validation if an object has a name not in a specified list. You can even catch the valid data in the exception object.

But if you want to pass validation and exclude some elements, this is better done in a post_load method that returns the object with only the elements you want.

This is not really a marshmallow feature, apart from the post_load thing (see docs for more details).

**Comment by sloria** [comment]
Yes, see the docs for pre- and post-processing here: https://marshmallow.readthedocs.io/en/stable/extending.html#pre-processing-and-post-processing-methods for more info on how to format your data how you want it.
