### ISSUE TITLE
Can't fill empty fields with default value

### ISSUE THREAD

**Issue by thmsklngr** [marshmallow-code/marshmallow#1765]
Hi,
I'm currently  out of ideas. I try to get rid of None's in my schema, but nothing seems to work.

Here's the schema:
```python
class ContactSchema(Schema):
    """Scheme for path `contacts`."""
    links = fields.List(fields.Nested(LinksSchema))
    contact_id = fields.Str(data_key='contactId')
    name = fields.Str()
    email = fields.Str(data_key='emailAddress')
    phone = fields.Str(
        data_key='phoneNumber',
        default='(no number available)',
        missing='(no number available)',
        allow_none=True
    )
    archived = fields.Boolean()
```
Regardless what I try, neither the value of missing or default it taken. I also tried to use only either default or missing. If I set `allow_none=True` the schema is validated in any case, but the field `phone` is unset or None. marshmallow is 3.10.0

Any ideas on how to solve this? According the docs this is supposed to work, or am I wrong?

Regards, Thomas

**Comment by thmsklngr** [comment]
Update: solved my issue by adding a post_load activity:
```python
class ContactSchema(Schema):
    """Scheme for path `contacts`."""
    links = fields.List(fields.Nested(LinksSchema))
    contact_id = fields.Str(data_key='contactId')
    name = fields.Str()
    email = fields.Str(data_key='emailAddress')
    phone = fields.Str(
        data_key='phoneNumber',
        missing='(no number available)',
        default='(no number available)',
        allow_none=True
    )
    archived = fields.Boolean()
    
    @post_load
    def no_number(self, item, *args, **kwargs):
        if not item['phone'] or item['phone'] == '':
            item['phone'] = '(no number available)'
        return item
```
Still open is the question why default or missing is not handled at all, when allow_none is set to False.

**Comment by sloria** [comment]
The `missing` value is only used if the key is actually missing from the input data. `None` is not considered missing.

Using `post_load` as you have is a good solution.

I proposed an API for customizing the values that are considered "missing" in https://github.com/marshmallow-code/marshmallow/pull/1381 . But that will require some thought...I'm still not sure it's a good idea.

**Comment by thmsklngr** [comment]
`missing` is just half of the truth, I added it here just for my interest. In my case `phoneNumber` is coming with my JSON anyway, so from my point of view the value of `default` should take place if `phoneNumber` is empty - but it actually does not work. I can get the deserialization working only, whenever I add `allow_none=True`. 
Am I getting something wrong here or shouldn't `default` be in place if a key does not have a value?

**Comment by lafrech** [comment]
Just to be sure it is clear. missing is for deserialization, default for serialization.

**Comment by thmsklngr** [comment]
Ahaa! Got it, I just read the docs a thousand times, but I did not stumble over that parts, for any unknown reason. Thx, sorry for the inconveniences.
