### ISSUE TITLE
Take default value when value is None

### ISSUE THREAD

**Issue by dormeiri** [marshmallow-code/marshmallow#1766]
I would like to specify fields that will use the default value if their value is `None` (even if they are not missing), something similar to the following field declaration will match perfectly to my case:
```python
fields.Pluck(MySchema, 'x', default={'x': 0}, take_default_on=[None])
```

Is there any way doing this without `@post_dump` or overriding `get_attribute` method?

**Comment by lafrech** [comment]
Discussed in #1381.

**Comment by sloria** [comment]
Yep, let's continue discussion on that PR or on its linked issue.
