### ISSUE TITLE
Change default behaviour of unkown field

### ISSUE THREAD

**Issue by anandtripathi5** [marshmallow-code/marshmallow#1796]
Recently I realized that the unknown field is included and the default value is `RAISE`. I want to change the default behaviour to let's say `INCLUDE` in my case. 

I can do that using the specific Schema class meta property but that is quite not feasible if I want to change all the instances of the Schema class.

Can we introduce some global configuration where we can change the default behaviour of an unknown field for the whole project?

PS: cannot create a custom class also to override the default behaviour cause for that also I need to import the custom class everywhere(the change I cannot afford)

**Comment by lafrech** [comment]
I think the good practice here is to have all your schemas inherit a custom base schema class.

In fact, when starting a dev, I often find myself doing it even if I don't need to customize right now, just in case I'd need to do it later.

When you say "cannot afford", does it mean

- you're in a situation where you absolutely can't use a custom class (schemas generated by a third-party lib where you can't specify a base class, in which case that lib should be improved to allow that)

- or just you have many schemas / files and that would be too much work to apply the change to all the code base (I don't think this is enough to have us introduce the change you're asking for)

?
