### ISSUE TITLE
__eq__ not making sense for types

### ISSUE THREAD

**Issue by ysangkok** [marshmallow-code/marshmallow#1798]
Using v3.11.1:

```
>>> from marshmallow.fields import Int , List
>>> List(Int) == List(Int)
False
```

Meanwhile for typing, it works, and it is even reference equal:

```
>>> from typing import List
>>> List[int]
typing.List[int]
>>> List[int] is List[int]
True
>>> List[int] == List[int]
True
```

I am writing a script that verifies that I have consistent types in my dataclasses and my Swagger, and it would be useful to compare the specified type in the schema.

**Comment by deckar01** [comment]
Handling all the arguments that can make these instances behave differently would probably require a lot of fragile `__eq__` methods.

Having multiple implementations of the same schema seems like the underlying problem. Would the apispec generator solve your use case? https://github.com/marshmallow-code/apispec

**Comment by ysangkok** [comment]
It would, but I don't have the authority to introduce it. But thanks for the quick response, sounds like this is expected.
