### ISSUE TITLE
Suggestion: Include schema name in ValidationErrors

### ISSUE THREAD

**Issue by SHxKM** [marshmallow-code/marshmallow#1799]
Example schema:

```
class JobConfigurationSchema(Schema):
    resource_name = fields.Str(data_key="resourceName", required=True)
```

Example input: any JSON that doesn't include `resourceName` key.

Current output:

```
marshmallow.exceptions.ValidationError: {'resourceName': ['Missing data for required field.']}
```

But with many schemas it isn't instantly clear *which* schema is missing this, a nicer output would be something along the lines of:

```
marshmallow.exceptions.ValidationError: JobConfigurationSchema: {'resourceName': ['Missing data for required field.']}
```

**Comment by deckar01** [comment]
I suspect the stack trace provides enough context for most use cases. `Schema.handle_error()` should allow you to customize this behavior.

https://marshmallow.readthedocs.io/en/stable/extending.html#custom-error-handling

To make it the default behavior you could use a base schema.

```py
import marshmallow

class Schema(marshmallow.Schema):
    def handle_error(self, exc, data, **kwargs):
        raise marshmallow.ValidationError(
            {self.__class__.__name__: exc.messages},
            exc.field_name,
            exc.data,
            exc.valid_data,
            **exc.kwargs,
        )

class Foo(Schema):
    bar = marshmallow.fields.Int()

foo = Foo()
foo.load({'bar' : 'err'})
# Traceback (most recent call last):
# ...
# marshmallow.exceptions.ValidationError: {'Foo': {'bar': ['Not a valid integer.']}}
```

**Comment by SHxKM** [comment]
Thanks @deckar01! So much more useful and readable, especially with nested schemas. I personally think this should be the default, but I don't know much about the project/use-cases so I will close this now.
