### ISSUE TITLE
Validate record and drop non validated fields

### ISSUE THREAD

**Issue by griseau** [marshmallow-code/marshmallow#1803]
Hello, 

I looked for a solution to validate records but drop fields if they don't respect the constraints. 
For example let's say I have a record like this : 
```
{"id": 1, "name": "super_name", "zip_code": "wrong_zip_code"}
```
But in the definition of my records the field "zip_code" is not mandatory but is supposed to be an int. 
Do I have any option to retrieve the following record : 
```
{"id": 1, "name": "super_name"}
```

Thanks a lot for your help

**Comment by lafrech** [comment]
The [ValidationError](https://marshmallow.readthedocs.io/en/stable/marshmallow.exceptions.html#marshmallow.exceptions.ValidationError) contains the valid data.

```py
try:
    MySchema().load({"id": 1, "name": "super_name", "zip_code": "wrong_zip_code"})
except ma.ValidationError as exc:
    print(exc.valid_data)

# {"id": 1, "name": "super_name"}
```

**Comment by griseau** [comment]
Awesome, thanks for your quick answer ! Closing the issue
