### ISSUE TITLE
Generate JSON schema definition

### ISSUE THREAD

**Issue by traut** [marshmallow-code/marshmallow#181]
It would be great if classes extended from `marshmallow.Schema` could generate json schema definitions (http://jsonschema.net). This is very useful if the components that are communicating in json are implemented in different languages (python and java, for example)

I suspect everything needed for json schema is already there: hierarchy definition, type specification, required fields, etc.

**Comment by sloria** [comment]
Thanks @traut. This has been implemented to some degree in [smore](https://github.com/marshmallow-code/smore). In particular, the [smore.swagger](https://github.com/marshmallow-code/smore/blob/dev/smore/swagger/__init__.py) module has functions for generating Swagger 2.0 definitions from marshmallow schema. AFAIK, the Swagger spec is compliant with the JSON Schema.

JSON schema generation will not be added to marshmallow core, but I welcome your feedback on the smore repo.
