### ISSUE TITLE
Validation Messages are not valid json

### ISSUE THREAD

**Issue by stanton-eric** [marshmallow-code/marshmallow#1813]
Validation messages appear to be json, but use single quotes (which is not valid json).

Current invalid json example: {'email': ['Not a valid email address.']}

Valid json equivalent: {"email":["Not a valid email address."]}

**Comment by lafrech** [comment]
Those are not JSON but Python dicts. How they are represented as strings when serialized into JSON depends on the lib used to do it. Python's `json` does it correctly AFAIK.

Do you have a specific issue you'd like to tell us more about?

**Comment by stanton-eric** [comment]
That makes sense lafrech.  Thank you.

I would love to see it as json for the flask-marshmsllow library considering the primary usage, but your answer makes sense.  Thank you.
