### ISSUE TITLE
Datetime format in flask marshmallow schema

### ISSUE THREAD

**Issue by Deep-sea-boy** [marshmallow-code/marshmallow#1820]
I want to apply a custom DateTime format for the data retrieved from model using the Schema in flask marshmallow.

Currently using the schema like:

```
class ScheduleListSchema(ma.Schema):
    class Meta:
        fields = ('id', 'start_time', 'end_time')
```

In this `start_time` in format of `2018-12-05T03:00:00+00:00`

So I want to create a custom format for the start_time value in schema , like `'%Y-%m-%d %H:%M:%S'`

**Comment by sloria** [comment]
You can explicitly declare the format for a specific `DateTime` field.

```python
import datetime as dt

from marshmallow import Schema, fields


class ScheduleListSchema(Schema):
    start_time = fields.DateTime(format="%Y-%m-%d %H:%M:%S")

    class Meta:
        fields = ("id", "start_time", "end_time")


serialized = ScheduleListSchema().dump(
    {"id": "123", "start_time": dt.datetime.utcnow(), "end_time": dt.datetime.utcnow()}
)
print(serialized)
# {'start_time': '2021-07-10 15:49:34', 'id': '123', 'end_time': '2021-07-10T15:49:34.990278'}
```

If you want to apply the format to all `DateTime` fields on the Schema, there's the `datetimeformat` class Meta option.

```python
class ScheduleListSchema(Schema):
    class Meta:
        fields = ("id", "start_time", "end_time")
        datetimeformat = "%Y-%m-%d %H:%M:%S"
```
