### ISSUE TITLE
Strip fields that are None from output on serialization

### ISSUE THREAD

**Issue by plondino** [marshmallow-code/marshmallow#1823]
Is there an easy way to strip fields that have a `None` value on serialization? It's very common in Python to have `None` for class attributes that are optional (but you still want them to exist for introspection, etc.), but in JSON it makes more sense for optional attributes to be omitted from the payload rather than set them to `null`.

I thought about a custom field, but it wasn't clear to me how you could return a value from `_serialize` that would omit the value from the schema.  It could be done in `post_dump`, but wondering if this was a common enough use case to warrant a feature (or if there's a better way to do this that I'm missing).

**Comment by lafrech** [comment]
See #229.
