### ISSUE TITLE
Is a JSON-list of primitives supported?

### ISSUE THREAD

**Issue by SHxKM** [marshmallow-code/marshmallow#1831]
I've a JSON that looks like this:

```
["xxx-yyy", "zzzz-aaaa", ....]
# yes, there is no key-value here - neither within the list, nor outside of it. 
```

It doesn't seem like marshmallow supports this use-case, unless I've missed something in the documentation.

**Comment by deckar01** [comment]
You can initialize a field without a schema and call its `deserialize` method.

https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Field.deserialize

You should be able to add custom validation on the list and the items using the fields' `validate` parameters.

https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Field

```py
from marshmallow import fields

schema = fields.List(fields.String())
schema.deserialize(["xxx-yyy", "zzzz-aaaa"])
# ['xxx-yyy', 'zzzz-aaaa']
```
