### ISSUE TITLE
How to dump with indentation

### ISSUE THREAD

**Issue by johanvergeer** [marshmallow-code/marshmallow#1832]
We use Marshmallow to write json to file, and at this moment it is not very readable because all data is on a single line. 

`json.dumps()` in the standard library has an `indent` parameter that can be used to indent the output before writing it to a json file.

Does Marshmallow have a similar functionality?

**Comment by lafrech** [comment]
`kwargs` passed to `schema.dumps()` are passed to `json.dumps` internally.

Pass `indent` to `schema.dumps()`.
