### ISSUE TITLE
Cannot serialize string to Integer field when the string is in float format

### ISSUE THREAD

**Issue by ericsouza** [marshmallow-code/marshmallow#1836]
Hey! Thanks for this library. I tried to find something about this but couldn't find anything similar. 

Well, a have a data in my database with the format `"1.0"` and I have to serialize as Integer so can become just `1` (if it is `"2.0"` then should be just `2` and so on...)

When I try this I got a error because python cannot convert a string in float format directly to int, it needs to first convert to a float object. Is there any way I can pass a information to first serialize to float and after to integer when using Integer field type? (Similar to what happens in Decimal field)

**Comment by sloria** [comment]
This can be achieved with a custom field.

The field names generally describe the internal (i.e. deserialized) data type, so it probably makes sense to implement a `fields.Decimal` subclass that serializes to an int.

```python
from marshmallow import Schema, fields


class DecimalInt(fields.Decimal):
    """Field that is internally represented as a ``decimal.Decimal``
    and externally represented as an int.
    """

    def _serialize(self, value, attr, obj, **kwargs):
        ret = super()._serialize(value, attr, obj, **kwargs)
        return int(ret)


class MySchema(Schema):
    num = DecimalInt()


schema = MySchema()
deserialized = schema.load({"num": 1.0})
print(deserialized)
# {'num': Decimal('1.0')}
serialized = schema.dump(deserialized)
print(serialized)
# {'num': 1}
```
