### ISSUE TITLE
List schema fields

### ISSUE THREAD

**Issue by caseydm** [marshmallow-code/marshmallow#1850]
I have a schema that I am filtering using query attributes. I want to remove invalid field names before dumping the schema, but I cannot figure out how to properly list the fields that are part of my schema. I tried JournalListSchema.__dict__.keys() which worked on my local machine, but when I deployed it to production the fields were not listed. Any ideas on how to do this?

Here is my example code:

```
# schema
class JournalListSchema(ma.Schema):
    issn = fields.String()
    title = fields.String()

# view
attrs = request.args.get("attrs")
only = attrs.split(",")


for field in only:
    if field not in JournalListSchema.__dict__.keys():
        only.remove(field)

journal_list_schema = JournalListSchema(only=only)
journals_dumped = journal_list_schema.dump(journals.items, many=True)
```

**Comment by lafrech** [comment]
Fields are accessible as `fields` attribute on schema instance and `_declared_fields` attribute on schema class.

We should probably provide a better API.

**Comment by caseydm** [comment]
Perfect thanks! I was able to do it with:

```
schema_fields = [j for j in JournalListSchema._declared_fields]
for field in only:
    if field not in schema_fields:
        only.remove(field)
```

**Comment by lafrech** [comment]
Good. I suppose you could write something like

```py
only = set(only) & set(JournalListSchema._declared_fields)
```

**Comment by lafrech** [comment]
Another thing you could to is use webargs to validate the inputs in the first place. You'd have to to declare explicitly which fields you allow the user to select, which may involve duplication, though.

**Comment by caseydm** [comment]
> Another thing you could to is use webargs to validate the inputs in the first place. You'd have to to declare explicitly which fields you allow the user to select, which may involve duplication, though.

Yes I did consider that but thought it's a bit too much overhead for now.
