### ISSUE TITLE
Strict Integer validation not called during serialization (dump)

### ISSUE THREAD

**Issue by iamlost127** [marshmallow-code/marshmallow#1851]
When `strict=True` is set in  `fields.Integer`, the validation is only called during deserialization. During serialization, float values are converted to int.

```python
class MySchema(Schema):
    some_int = fields.Integer(strict=True)

s = MySchema()
result = s.dump({'some_int': 10.01})
print(result)
```

output:
```
{'some_int': 10}
```

Expected output:
Marshmallow should raise a validation error:
```
marshmallow.exceptions.ValidationError: Not a valid integer.
```

**Comment by vivekkr12** [comment]
Hi @iamlost127 ,

Raised a PR to fix this. PR #1852

**Comment by lafrech** [comment]
It is a design choice in marshmallow to only validate on deserialization (load).

See for instance #1127, #682.
