### ISSUE TITLE
How do I create a field that can be renamed  or it's value replaced.

### ISSUE THREAD

**Issue by SanketDG** [marshmallow-code/marshmallow#1854]
Right now in one of my schemas, I have:

```
    parent = fields.Str(allow_none=False, required=True)
```

I have a field in the DB that is a Foreign Key, and is called `parent_id`, but I don't want to take in input from a `parent_id`, and instead use "parent" as an "input" field (load only) and that is a slug, another field in the DB.

I then use this slug to find the ID of any row and then store this parent_id when saving to the database
Vice-versa when loading from the database.

How can I use this parent and parent_id fields in my Schema in this fashion interchangeably?

What I have looked at till now:

- Function fields
- Load/Dump Hooks `pre_dump`, `pre_dump`
- Custom Fields (Can this be done in a generic way?)

I am looking for any other approaches here.
Thanks!

**Comment by deckar01** [comment]
I would start with `@post_load` and `@pre_dump` on a couple schemas. Once you have it working you can refactor it into a custom field as `_deserialize()` and `_serialize()`.
