### ISSUE TITLE
[RFC] Drop Python 3.5

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow#1856]
We dropped Python 3.4 in #1525 because it was EOL (and not provided by our CI service anymore).

We could drop Python 3.5 since it is EOL too.

https://endoflife.date/python

> Ended 10 months ago (13 Sep 2020)

I remember people being caught by the CI due to some improvement in 3.6 in the typing syntax. Other than this, the changes affecting marshmallow seem minor to me. Basically, f-strings.

[Python 3.6 news](https://docs.python.org/3/whatsnew/3.6.html)

> New syntax features:
>     PEP 498, formatted string literals.
>     PEP 515, underscores in numeric literals.
>     PEP 526, syntax for variable annotations.
>     PEP 525, asynchronous generators.
>     PEP 530: asynchronous comprehensions.

No rush, but I'm fine doing it.

webargs and apispec are already 3.6+.

**Comment by sloria** [comment]
No objections from me. I think we can and should drop support for EOL versions going forward.

**Comment by sirosen** [comment]
Since `python_requires` is being set, I think there's very little harm in a policy of only supporting the current versions of python3.

Since python2 is behind us, I doubt anyone would object to "we drop EOL python versions at our discretion".
