### ISSUE TITLE
TimeDelta serialization precision

### ISSUE THREAD

**Issue by yarsanich** [marshmallow-code/marshmallow#1865]
Hi there!

I just found quite strange behaviour of `TimeDelta` field serialization

```python3
from marshmallow.fields import TimeDelta
from datetime import timedelta

td_field = TimeDelta(precision="milliseconds")

obj = dict()
obj["td_field"] = timedelta(milliseconds=345)

print(td_field.serialize("td_field", obj))
```

Output of this snippet is `344`, but it seems that `345` is correct.

Looks like a rounding issue here: https://github.com/marshmallow-code/marshmallow/blob/dev/src/marshmallow/fields.py#L1474

**Comment by deckar01** [comment]
> For interval units other than seconds, use the division form directly (e.g. `td / timedelta(microseconds=1))`.

https://docs.python.org/3/library/datetime.html#datetime.timedelta.total_seconds

The docs don't provide any guidance on rounding. `round()` seems to provide the desired behavior.

**Comment by deckar01** [comment]
It looks like we would need to convert the floats to `Decimal`, round to the float precision limit (16), then perform the division on the decimals.

https://docs.python.org/3/tutorial/floatingpoint.html#representation-error

```py
int(round(Decimal(0.345), 16) / round(Decimal(0.001), 16))
# 345
```

This seems like a better option than going back to a long if chain that explicitly multiplies and adds the integer values together.

**Comment by deckar01** [comment]
That actually caused the 86401000001 microsecond test to fail. It looks like rounding to 9 decimal places to match the max precision of timedelta might be the safest option.

**Comment by deckar01** [comment]
> This seems like a better option than going back to a long if chain that explicitly multiplies and adds the integer values together.

I assumed the introduction of additional time resolutions in #691 corresponded to `timedelta` also splitting the times across these units internally, but it actually doesn't. The intermediate units get packed into the original 3 integers (days, seconds, microseconds). Cpython's `timedelta` has a private method named [`_to_microseconds()`](https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Lib/datetime.py#L665-L667) with a simple formula that we can borrow.

**Comment by yarsanich** [comment]
@deckar01 thanks for fixing this!
