### ISSUE TITLE
bad guide

### ISSUE THREAD

**Issue by Yourun-proger** [marshmallow-code/marshmallow#1866]
i want to contribute on marshmallow and i begin run the command on contributing guide:
```bash
pip install -e '.[dev]'
```
But i get this:
```
ERROR: '.[dev]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
```
Please help me and thanks!

**Comment by deckar01** [comment]
What version of python and pip are you using? I am able to install a fresh dev environment with Python `3.9.5` and pip `21.1.1`.

**Comment by Yourun-proger** [comment]
@deckar01, thank you. I forgot update pip. Sorry(

**Comment by Yourun-proger** [comment]
@deckar01,ahhh... i update pip in my venv, but i get:
```
ERROR: '.[dev]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```
how i can improve this

**Comment by Yourun-proger** [comment]
i have python 3.8.2 and pip 21.2.4 , this is a problem?

**Comment by Yourun-proger** [comment]
@deckar01 ,can you give me list of reqs.txt if this problem cannot resolve, please

**Comment by deckar01** [comment]
Does installing the project without the dev extras work?

```sh
pip install -e .
```

**Comment by Yourun-proger** [comment]
@deckar01, yeah! IT IS WORK. Thank you very-very much)

**Comment by Yourun-proger** [comment]
@deckar01, sorry it is me again. i put:
```bash
git checkout -b fix-typehints 2.x-line
```
and i get:
```
fatal: '2.x-line' is not a commit and a branch 'fix-typehints' cannot be created from it
```

**Comment by Yourun-proger** [comment]
@deckar01, I did exactly what is written in the guide. Why is there a mistake?

**Comment by Yourun-proger** [comment]
@deckar01, probable i need to:
```bash
git checkout 2.x-line
git branch fix-typehints
```
But im not sure. Can you get me some intstructions?

**Comment by deckar01** [comment]
If you run `git branch --list -v` I suspect you will not see `2.x-line`, because you have never fetched it. `git fetch origin 2.x-line` would fix that.

Based on your feature branch name, you probably should not base your branch off of `2.x-line`. Use `git checkout -b fix-typehints dev` if you want to make changes to the latest major version.

**Comment by Yourun-proger** [comment]
@deckar01, thank for suggestion! But in guide said, if this change for bugfix, need branch based of 2.x-line. And i don't what is the typing fix: it is a bugfix or not? If it isn't a bugfix, my branch will base of dev branch. Please, say me what i must choose

**Comment by lafrech** [comment]
marshmallow 2 is no longer supported as of 2020-08-18.

We could probably update the contributing guide.

Whatever it is, branch on dev. Fixing typing is definitely not a bugfix anyway.

No need to ping us on each reply, we watch the bugtracker.

**Comment by Yourun-proger** [comment]
Sorry for tagging and thank you for resolving my dilemma)

**Comment by Yourun-proger** [comment]
aah. this guide is very-very-very old...
i put:
```bash
git push origin fix-typehints
```
and i get:
```
remote: Permission to marshmallow-code/marshmallow.git denied to Yourun-proger.
fatal: unable to access 'https://github.com/marshmallow-code/marshmallow.git/': The requested URL returned error: 403
```

**Comment by Yourun-proger** [comment]
what i must do?..

**Comment by Yourun-proger** [comment]
my plan
1. del `marshmallow` dir
2. `git clone https://github.com/marshmallow-code/marshmallow.git`
3. `git add remote fork https://github.com/yourun-proger/marshmallow.git`
4. create venv and install reqs
5. `git checkout -b fix-typehints dev`
6. i do changes and index and commit and push
7. create PR
this looks good or not?

**Comment by Yourun-proger** [comment]
and pre-commit not work. on activate venv i put:
`pre-commit install --allow-mising-config`
and get typical error: 
"pre-commit" is not internal or external command, e.t.c

**Comment by deckar01** [comment]
> this guide is very-very-very old...

The target audience for this document is expected to be familiar with git and GitHub already.

> what i must do?..

I would recommend reading more about these tools. Since you are an inexperienced developer, you should assume that there is a solution to your problem online and try to find it before asking a project maintainer.

**Comment by Yourun-proger** [comment]
My miscalculation. It is unnecessary to ask basic questions here. I'm just scared to ruin your commit history. Sorry one more time. I will fix everything shortly and send a PR! But im not newbie to programming)
