### ISSUE TITLE
Unexpected behaviour when loading data with an schema

### ISSUE THREAD

**Issue by franciscovelez** [marshmallow-code/marshmallow#1871]
Hi everybody,

First of all, I have been using this library for the last year or two and I wanted to thank you for all the work and effort you have put into this library.

Now my question. I'm currently working with Marshmallow 3.13 and I have noticed something that I didn't expect. For the sake of simplicity, let's say we have the following schema:

```python
from marshmallow import fields, Schema

class DateAddress(Schema):
    dt = fields.DateTime()
    ip = fields.IPv4()
```
the following code should load in `my_address` the input data:
```python
data_to_load = {
    "dt": "2021-08-27T07:23:38.128Z",
    "ip": "127.0.0.1"
}

my_address = DateAddress().load(data_to_load)
```
which is fine because I get the expected `dict` with the `IPv4Address` & `datetime` objects :
![imagen](https://user-images.githubusercontent.com/5020683/131336021-5c345f83-8b01-4736-9553-cf5c04622818.png)

now, if I take the `my_address` var and try to load the schema again:
```python
my_new_address = DateAddress().load(my_address)
```
 I get the unexpected result:
```
marshmallow.exceptions.ValidationError: {'dt': ['Not a valid datetime.']}
```
I say that this is an unexpected behaviour because I could expect both fields failing because none of them are `strings` or both passing because each class type belongs to its respective class.

So my question is: what is it happening below to allow the `IPv4` field but not the `DateTime`? Is this a bug? Because, in my opinion, I think that both fields should behave in the same way.

Thanks!

**Comment by lafrech** [comment]
Marshmallow doesn't support loading objects that are already in deserialized form. This is discussed in #1415.

However, nothing is done to prevent it either if it happens to work. Hence the difference you've noticed.

**Comment by franciscovelez** [comment]
I see, so the "solution" to our problem, as I supposed, is building custom fields with a custom deserialize method. 

Thanks for the clarification.
