### ISSUE TITLE
Issues deserializing to objects

### ISSUE THREAD

**Issue by danben** [marshmallow-code/marshmallow#1872]
I'm having a couple of issues with what feels like a fairly vanilla use case: deserializing from a JSON string to one or more Python objects, possibly with custom fields. The version I'm using is 3.13.0. Not sure if I'm doing something wrong or if there are any bugs present.

1. When using @post_load, the data argument contains strings that have not been processed by their respective fields' _deserialize methods. If I remove the @post_load-decorated method, the strings in the resulting dictionary are correctly processed.

Example (stripped of everything unnecessary):

```
class Dollar_string(fields.Field):
    def _serialize(self, value, attr, obj, **kwargs):
        return f"${value}"

    def _deserialize(self, value, attr, obj, **kwargs):
            # Putting a print statement here reveals that this method does not get called. In the absence
            # of My_schema.load, that is no longer true.
            return Decimal(value[1:])


class My_schema(Schema):
    number_of_dollars = Dollar_string(required=True)

    @post_load
    def load(self, data, **kwargs):
        return My_object.init(**data)


@attr.s
class My_object:
    number_of_dollars = attr.ib()

    @staticmethod
    def init(*, number_of_dollars):
        # Here number_of_dollars is the raw string given, ie "$10" including the dollar sign.
        return My_object(number_of_dollars)


    @staticmethod
    def load_file(file):
        with open(file, 'r') as f:
            schema = My_schema()
            return schema.loads(f.read())
```

2. Passing many=True to a schema constructor appears to have no effect. In the following example I have a file with a JSON list of objects corresponding to the provided schema. In the presence of many=True I would have expected schema.loads() to apply the schema to each element of the list and give me back a list of objects. (I've also tried passing many=True to schema.loads and that doesn't change anything.)

Example:

```
@attr.s
class My_object:
    my_field = attr.ib()

    @staticmethod
    def init(*, my_field):
        return My_object(my_field)


class My_schema(Schema):
    my_field = fields.String()

    @post_load
    def load(self, data, **kwargs):
        # Here I get data as a list, resulting in the comprehension below. I would have expected that
        # this method would instead get a dict representing a single object. As a result I'm not able
        # to reuse this schema if I have another use case where I want to deserialize a single object.
        return [My_object.init(**inner) for inner in data]


def load_file(file):
    with open(file, 'r') as fd:
        schema = My_schema(many=True)
        return schema.loads(fd.read())
```

**Comment by deckar01** [comment]
You are overriding `load` on the schema. That method is being called directly rather than being called as part of marshmallow's hook life cycle.
