### ISSUE TITLE
Serialize empty list as default value rather than null?

### ISSUE THREAD

**Issue by caseydm** [marshmallow-code/marshmallow#1874]
I have a jsonb array that sometimes is None:

```
class Magazine(db.Model):
    __tablename__ = "magazines"

    id = db.Column(db.Integer, primary_key=True)
    other_titles = db.Column(JSONB)

class MagazineSchema(ma.Schema):
    other_titles = fields.List(fields.String)
```

What I want to do is display an empty list if the other_titles field is null. Is there a way to do this without reverting to field.Method or adding a property to the model?

**Comment by deckar01** [comment]
I would recommend creating a custom field.

http://marshmallow.readthedocs.io/en/latest/custom_fields.html

```py
from marshmallow import fields, Schema

class DefaultList(fields.List):
    def _deserialize(self, value, attr, obj):
        value = value or []
        return super()._deserialize(value, attr, obj)

class MagazineSchema(Schema):
    other_titles = DefaultList(fields.String)
```

**Comment by caseydm** [comment]
Awesome idea, thank you. I need to serialize my value so I ended up using this:

```python
from marshmallow import fields

class DefaultList(fields.List):
    """
    Displays an empty list if value is None.
    """
    def _serialize(self, value, attr, obj, **kwargs):
        if value is None:
            return []
        return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
```

Does that look right?

**Comment by deckar01** [comment]
I would recommend `super()._serialize()` over copying the internal implementation. It is less code and more compatible with future features. Otherwise :+1:.

**Comment by caseydm** [comment]
Good idea. Perfect, thank you!
