### ISSUE TITLE
Possible bug for Marshmallow fields

### ISSUE THREAD

**Issue by SLey3** [marshmallow-code/marshmallow#1875]
I've been having trouble setting up default values for the Integer field. I tried using both `load_default` and `default` parameters to no avail. It still resulted in the following error message:
```
{
  "Code": 422, 
  "errors": {
    "query": {
      "page": [
        "Not a valid integer."
      ]
    }
  }
}
```
In the Schema, I also have a string field. As I am using [webargs](https://github.com/marshmallow-code/webargs), I removed the user parameter from the url, and I did get an error message coming from the string field that was similar to the integer one. I'm not sure whether I did something wrong when assigning default values but if I didn't, then there might be a potential bug with the source code for marshmallow.

Schema:
```python

class AccountUserManagementWebArgs(Schema):
    """
    account user management schema
    """

    user = fields.String(required=True)
    page = fields.Integer(default=1)
    actions = fields.Nested(_account_user_management_webargs_nested, many=True)
```

**Comment by SLey3** [comment]
FYI, I see this as a potential solution to my problem: [Schema Factories](https://webargs.readthedocs.io/en/latest/advanced.html#schema-factories). But I need more explanation on what;s going on with the example provided. Would I need to set a different query parameter before the ones I normally use for my website (e.g. `?fields=user=John%20Green`)? Do I even need it? or Is there another way without using that example or something similar to it?
*This is assuming that there is not bugs with marshmallow*

**Comment by lafrech** [comment]
It's unclear to me that you're trying to achieve. I suspect you don't need complicated schema factories patterns and the solution should be simpler.

It would help if you provided a larger piece of your code, including the request you send. And if you specified your marshmallow version, just in case.

No, you shouldn't need `fields=`.

`Nested` field in query arguments is a red flag to me. Probably unrelated, but here again, I'm curious about the query you're sending.

**Comment by SLey3** [comment]
> It's unclear to me that you're trying to achieve. I suspect you don't need complicated schema factories patterns and the solution should be simpler.
> 
> It would help if you provided a larger piece of your code, including the request you send. And if you specified your marshmallow version, just in case.
> 
> No, you shouldn't need `fields=`.
> 
> `Nested` field in query arguments is a red flag to me. Probably unrelated, but here again, I'm curious about the query you're sending.

I am using the latest version of marshmallow.

The request you state is not really a request per say but I use a custom parser that I made using the FlaskParser object from the webargs library to get the url parameters of both nested and non-nested types, located in a url string (e.g. something.com/prof/view/?name=John&action.id=1).
Below contains the source code for the custom parser:
https://pastebin.com/PZSrdgFi

In order for that parser to properly parse the url parameter, it needs to be called as the following:
```python
@parser.use_args(AccountUserManagementWebArgs)
```

thus the Schema provided above needs to be provided as the argument for `use_args`.

The main goal is that the default value for a schema item should be returned as None if it isn't found in the url parameter (like a nested parameter for example.

I do think that due to the error I received, something is not right, as I did pass in a default value of 1 to the Integer field but the field raised the error shown above.

**Comment by SLey3** [comment]
@lafrech Do I need to clarify more in order to help you?

**Comment by lafrech** [comment]
I won't dig through the whole code sample but

> The main goal is that the default value for a schema item should be returned as None if it isn't found in the url parameter

+

>       "page": [
>         "Not a valid integer."
>       ]

Could it be you parser sets `None` as default for all query args, including pagination query args and then you get `None` for page, which is invalid?

(You may try to send a request with a value for page and see what happens.)

**Comment by SLey3** [comment]
@lafrech based on what you said, I made a functionality were the parser now takes a default argument during initialization and after creating the dictionary just based on the querystring, it will add the key (e.g. page) and it's value (e.g. 1) to the dictionary.
This works and I do not seem to get the errors that come from the parser right now.
But that same functionality seems to be discluding an empty dictionary that I want it to set as a default for a parameter.
So I wish to keep this issue open until I fix the current issue and check whether I get errors from the parser or not after retesting it.

**Comment by SLey3** [comment]
so I partially found why it was removing the default key: "actions". I fixed it through making a check in the function below used by the subclassed parser:
```python
    def _update_args_kwargs(
        self,
        args: Tuple,
        kwargs: Dict[str, Any],
        parsed_args: temp_save,
        as_kwargs: bool,
    ) -> Dict[Dict, Mapping]:
        """Update args or kwargs with parsed_args depending on as_kwargs"""
        for k in self.defaults.keys():
            # even though _setdefaults made for _structureddict sets the defaults values, some of those values may be removed by the main Parser
            # so this serves as a double check to make sure all values are in the temp_save dict
            if k not in parsed_args:
                parsed_args[k] = self.defaults[k]
        return super()._update_args_kwargs(args, kwargs, parsed_args, as_kwargs)
```
I would like to thank you for your help. My parser works great now.

**Comment by lafrech** [comment]
Great. Closing this, then.
