### ISSUE TITLE
how to handle incoming json object if one of the fields can't be a valid attribute

### ISSUE THREAD

**Issue by shalakhin** [marshmallow-code/marshmallow#1876]
In the json I receive there is `@timestamp`.

```json
"actions": [
    {
      "@timestamp": "2021-09-10T13:59:01.500",
      "timestamp": "2021-09-10T13:59:01.500",
```

how to properly process that? I think there must be some way to map it to the different attribute say "_timestamp"? But data_key, load_from, dump_to does not help

**Comment by lafrech** [comment]
Doesn't this do what you want?

```py
class ActionSchema(ma.Schema):
    _timestamp = ma.fields.DateTime(data_key="@timestamp")
    timestamp = ma.fields.DateTime()
```

**Comment by shalakhin** [comment]
@lafrech I think you are right. I have tried to use it with marshmallow-dataclass and it didn't take it properly. I think plain marshmallow usage processes `data_key` in a right way.

**Comment by lafrech** [comment]
I guess we can close this, then. Feel free to comment if still stuck.
