### ISSUE TITLE
Question: Can I generate a dictionary of expected fields for documentation?

### ISSUE THREAD

**Issue by Elysium1436** [marshmallow-code/marshmallow#1881]
I'm using flask-restx for my rest-api creation, and in there, you can specify a dictionary of expected parameters and their specifications (type, required, etc.). I was wondering if there's either a function that can do exactly that, or if there's something similar that I can hack my way into making it possible.

**Comment by lafrech** [comment]
[apispec](https://github.com/marshmallow-code/apispec)?

**Comment by lafrech** [comment]
Closing for now. Please comment if you need more.
