### ISSUE TITLE
Better handling of "two-way" nesting

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#19]
Having two serializers that nest each other is quite awkward. For example, for many-to-one relationship between `Book`s and `Author`s, you'd have to do something like the following:

``` python
class BaseBookMarshal(Serializer):
    date_created = fields.DateTime()
    isbn = fields.String()

class AuthorMarshal(Serializer):
    created = fields.DateTime(attribute='date_created')
    books = fields.Nested(BaseBookMarshal, many=True)

class BookMarshal(BaseBookMarshal):
    author = fields.Nested(AuthorMarshal, allow_null=True)
```

While this certainly works, having to create the extra `BaseBookMarshal` class is a bit clunky. It would be nice if you could declare nested serializers without having to worry about declaration order, and just pass class names into the `Nested` field

``` python
class AuthorMarshal(Serializer):
    created = fields.DateTime(attribute='date_created')
    books = fields.Nested('BookMarshal', many=True)

class BookMarshal(Serializer):
    author = fields.Nested('AuthorMarshal', allow_null=True)
    date_created = fields.DateTime()
    isbn = fields.String()
```

I'm still undecided on whether this is a good idea. Not only with this require more metaclass magicks, but it would necessarily involve implicit removal of fields in order to prevent infinite recursion.

**Comment by gdiscry** [comment]
I'm interested in this feature.

Personally, the infinite recursion problem is not an issue for my use case if we could also use hierarchical `only`/`exclude` parameters which would look like:

``` python
serialized = BookMarshal(book, only=('isbn', 'date_created', 'author.created'))
```

or

``` python
serialized = BookMarshal(book, exclude=('author.books',))
```

I use marshmallow when generating CSV files from SQLAlchemy objects with `csv.DictWriter`. I serialize the SQLAlchemy object with marshmallow, flatten the resulting dict (keys are joined with `.`) and pass that dict to `csv.DictWriter`. As DictWriter already requires a list of `fieldnames`, using the same list with the serializer would be great.

Anyway, that's another feature. The conclusion is that explicit is better than implicit.

**Comment by DeaconDesperado** [comment]
:+1: for proposed API, even though it's a big change.  The resolution by string name is a pretty common pattern for situations like this, where it's important to make definition order have no effect on lookup.

**Comment by sloria** [comment]
@gdiscry I like the explicitness of your proposed hierarchical filtering. 

I'm leaning towards going ahead with this. Will likely starting prototyping it for the next release.

**Comment by justanr** [comment]
I'm going to say that this is a big thumbs up, as well. If you're doubting on if they should be passed as strings or not, you could take a page from SQLAlchemy's book and allow a callable (such as a lambda) instead.

**Comment by DigTheDoug** [comment]
Glad to hear it, this is definitely a plus in my book. Using mongodb we use ReferenceFields often and  being able to match that pattern when we serialize them would be great.

**Comment by sloria** [comment]
This has been implemented on develop. Feel free to try it out and give feedback.

``` sh
pip install -U git+https://github.com/sloria/marshmallow.git@dev
```
