### ISSUE TITLE
many=True only working with load not with loads TypeError: the JSON object must be str, bytes or bytearray, not list with 

### ISSUE THREAD

**Issue by justintim-es** [marshmallow-code/marshmallow#1901]
So according to my previous issue
https://github.com/marshmallow-code/marshmallow/issues/1900
i thought lets first get the proper output and then use ```loads(blocks, many=True)``` but it turns out many only works with load and not with loads see the error in the title

**Comment by deckar01** [comment]
`loads` parses a JSON string. `many=True` indicates that the JSON string contains a list.

https://marshmallow.readthedocs.io/en/stable/api_reference.html?highlight=loads#marshmallow.Schema.loads
