### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by decaz** [marshmallow-code/marshmallow#1902]
```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. 
Use setuptools or check PEP 632 for potential alternatives
```
https://github.com/marshmallow-code/marshmallow/blob/35225039900be03536cfde7abf121d11066e3183/src/marshmallow/__init__.py#L14

Environment:
- CPython 3.10.0
- marshmallow 3.14.0

**Comment by deckar01** [comment]
> `distutils.version` — use the `packaging` package

https://www.python.org/dev/peps/pep-0632/#toc-entry-6

All of our previous version tags comply with [PEP 440](https://www.python.org/dev/peps/pep-0440/), so it should be safe to switch to `packaging.version.Version`.

https://packaging.pypa.io/en/latest/version.html#packaging.version.Version

<details><summary>Version Check</summary>

```py
from subprocess import check_output
from packaging.version import Version


tags = check_output(['git', 'tag', '-l']).decode('utf-8')
for n in tags.splitlines():
    try:
        Version(n)
    except:
        print(n)
```

</details>

**Comment by kkirsche** [comment]
#1903 submitted with the updated use of packaging.version
