### ISSUE TITLE
How to remove an item from fields.List in marshmellow

### ISSUE THREAD

**Issue by yanxg** [marshmallow-code/marshmallow#1906]
There are two schemas

```py
from marshmallow import Schema

class AuthorSchema(Schema):
    name = fields.Str(required=True)
    birthdate = fields.Str(required=True)

class BookSchema(Schema):
    id = fields.Int(required=True)
    authors = fields.List(fields.Nested(AuthorSchema), allowed_none=True)
```

If a book's authors data field has an author whose name is "yanxg", I want to delete the "yanxg" author from the book's authors data field. How could achieve this?

**Comment by deckar01** [comment]
Marshmallow provides decorators to register methods so they can modify the data at certain points in the schema life cycle.

https://marshmallow.readthedocs.io/en/stable/extending.html#pre-processing-and-post-processing-methods

If you wanted to modify the data after it is dumped you can use `@post_dump`:

```py
from marshmallow import Schema, post_dump

class BookSchema(Schema):
    ...
    @post_dump
    def remove_yanxg(self, data, many, **kwargs):
        data['authors'] = [a for a in data['authors'] if a['name'] == 'yanxg']
        return data
```
