### ISSUE TITLE
cannot serialize IPv4 field 

### ISSUE THREAD

**Issue by tomer2141** [marshmallow-code/marshmallow#1931]
I'm tiring to serialize an object according to a Schema that contains an IPv4 field.

validate works fine but when I'm trying to dump the object it raises an AttributeError: 'str' object has no attribute 'compressed'

using: flask, flask_restful

**Comment by lafrech** [comment]
I guess what you're serializing is not an [IPv4Address](https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv4Address) object but the string representation of an IP address.

**Comment by tomer2141** [comment]
Yes, but isn't it the responsibility of marshmallow?

**Comment by lafrech** [comment]
Well, marshmallow loads an IP as string into a Python IPv4Address and dumps an IPv4Address into a string.

The same applies to datetimes, for instance. Marshmallow serializes `datetime.datetime` objects, not string representations.

**Comment by tomer2141** [comment]
Oh, I see. Got confused here, but thanks! you made it clear for me :)
