### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by severinsimmler** [marshmallow-code/marshmallow#1943]
I'm using `marshmallow` with Falcon and have observed a quite strange memory leak. This minimal application does nothing but provide a GET endpoint serializing a dictionary and profiling the memory usage with `memory_profiler`:

```python
from falcon import App, Request, Response
from marshmallow import fields, Schema
from memory_profiler import profile


class ArtistSchema(Schema):
    name = fields.Str()


class ArtistResource:
    @profile
    def on_get(self, request: Request, response: Response):
        response.text = ArtistSchema().dumps({"name": "David Bowie" * 10000})


application = App()
application.add_route('/artist', ArtistResource())
```

Sending now 100,000 requests like:

```python
import requests


for _ in range(100000):
    requests.get("http://127.0.0.1:8000/artist")
```

will slowly increase the memory footprint from 53.0 MiB to 54.5 MiB (and would apparently continue to increase like this).

I'm constructing a new `ArtistSchema` object for every request. But if I do this only once an reuse it for every request:

```python
ARTIST_SCHEMA = ArtistSchema()

class ArtistResource:
    @profile
    def on_get(self, request: Request, response: Response):
        response.text = ARTIST_SCHEMA.dumps({"name": "David Bowie" * 10000})
```

the memory usage does not increase. How is this possible? Or is this even a `marshmallow` issue?

My setup:
- Python 3.9.6
- `marshmallow` 3.14.1
- `falcon` 3.0.1
- `gunicorn` 20.1.0
- `memory-profiler` 0.60.0

**Comment by lafrech** [comment]
See #660 (and #732).

**Comment by deckar01** [comment]
`class_registry` does not grow, because the new schemas all have the same module path.

Here is a minimal repro:

```py
#! mprof run
from marshmallow import fields, Schema

class ArtistSchema(Schema):
    name = fields.Str()

for _ in range(100000):
    ArtistSchema().dumps({"name": "David Bowie"})
```

![test1](https://user-images.githubusercontent.com/3108007/153030796-37531a63-987d-49d2-9afd-3e9e3faac9e5.png)

If you remove the field, the leak goes away.

```py
#! mprof run
from marshmallow import fields, Schema

class ArtistSchema(Schema):
    pass

for _ in range(100000):
    ArtistSchema().dumps({"name": "David Bowie"})
```

![test2](https://user-images.githubusercontent.com/3108007/153030833-6345feb6-5c04-4463-9b21-4726d34815f1.png)

I suspect this is caused by circular references between the schema and the field. The schema has a list of fields. The field has a parent attribute. We would need to use a weakref proxy for the schema reference in the field to ensure that the tree unravels when the schema is ready to be released.

https://docs.python.org/3/library/weakref.html

**Comment by deckar01** [comment]
I confirmed that `field_obj._bind_to_schema(field_name, proxy(self))` fixes the memory leak. Unfortunately wekrefs break a couple of tests that use lambdas and I believe that is fundamentally unfixable.

The garbage collector is supposed to be able to detect circular references, but we are probably doing something dynamic that it can't infer. Clearing the circular references in `Schema.__del__` and `Field.__del__` causes the garbage collector to behave correctly.

![test1](https://user-images.githubusercontent.com/3108007/153066222-031e656f-8d06-49da-a9e9-745a89ee53e7.png)

![test2](https://user-images.githubusercontent.com/3108007/153066228-f2a5f227-7ffc-49d6-a3a3-522ac3692518.png)

**Comment by deckar01** [comment]
I just ran the longer profile test on the dev branch and realized that the garbage collector does eventually cleanup these circular references on its own. I should have noticed that the memory usage leveled off around 3s in my very first test. I suspect the garbage collector has a strategy based on the percent of currently used memory. Everything appears to be working as intended.
