### ISSUE TITLE
"raise from" ValidationError missing stack trace

### ISSUE THREAD

**Issue by diogofernandesc** [marshmallow-code/marshmallow#1944]
Hi Guys

First of all thanks for a great library, marshmallow is amazing.

I'm encountering an issue where when catching and using `raise from` from Marshmallow's ValidationError, the stack trace (cause) expected is missing, any ideas where I am going wrong?

Thanks in advance

**Comment by deckar01** [comment]
Marshmallow's validation errors get aggregated into an object and the error that bubbles to the user comes from one line of code in the base schema. The stack trace would not point you to a line in your schema. The structure of the data in the validation error should provide you with all the information you need to identify the field that failed validation.

**Comment by diogofernandesc** [comment]
Yep, that’s fine, are you saying it’s by design that the raise from doesn’t work? Just to be clear my issue is around doing something like

```
except ValidationError as e:
   raise NewException from e
```

this would typically include the stacktrace of the cause exception (validation error) (which includes the field that failed) but its not the case with the validationError so wondering if anyone has any ideas

**Comment by lafrech** [comment]
I guess the stack trace shows the line in marshmallow code that raises the `ValidationError`.

It's unclear to me what you expect. Would you like to paste here the stack trace and point where you think something is missing?
