### ISSUE TITLE
_deserialize() got an unexpected keyword argument 'partial'

### ISSUE THREAD

**Issue by nissou91** [marshmallow-code/marshmallow#1948]
I am getting this error during my tests, I am using Marshmallow 3.10.0 and already updated all the decorated methods signatures (decorated with pre_load, post_load, pre_dump, post_dump, validates_schema, in addition to _deserialize) by adding '''**kwargs'''. However, I am still getting this error:
```
Traceback (most recent call last):
  File "/usr/src/wazo-confd/wazo_confd/helpers/common.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/xivo/auth_verifier.py", line 167, in wrapper
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/xivo/auth_verifier.py", line 125, in wrapper
    return func(*args, **kwargs)
  File "/usr/src/wazo-confd/wazo_confd/plugins/ha/resource.py", line 28, in put
    form = self.schema().load(request.get_json())
  File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 728, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 866, in _do_load
    unknown=unknown,
  File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 674, in _deserialize
    index=index,
  File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 496, in _call_and_store
    value = getter_func(data)
  File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 667, in <lambda>
    val, field_name, data, **d_kwargs
  File "/opt/venv/lib/python3.7/site-packages/marshmallow/fields.py", line 356, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
TypeError: _deserialize() got an unexpected keyword argument 'partial'
2022-02-21 13:49:01,354 [1] (INFO) (flask.app): response: (172.29.0.1) PUT http://127.0.0.1:49227/1.1/ha 500
2022-02-21 13:49:01,362 [1] (DEBUG) (flask.app): response body: ["Unexpected error: _deserialize() got an unexpected keyword argument 'partial'"]
```

the code for '''/usr/src/wazo-confd/wazo_confd/plugins/ha/resource.py''' where the error seems to be raisen:

```
# Copyright 2019-2021 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

from flask import request

from wazo_confd.auth import required_acl, required_master_tenant
from wazo_confd.helpers.restful import ConfdResource

from .schema import HASchema


class HAResource(ConfdResource):

    schema = HASchema

    def __init__(self, service):
        self.service = service

    @required_master_tenant()
    @required_acl('confd.ha.read')
    def get(self):
        model = self.service.get()
        return self.schema().dump(model)

    @required_master_tenant()
    @required_acl('confd.ha.update')
    def put(self):
        ----> (error here from trace):  form = self.schema().load(request.get_json())
        self.service.edit(form)
        return '', 204

```

and the schema is defined as:

```
# Copyright 2019 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

from marshmallow import validates_schema
from marshmallow.exceptions import ValidationError
from marshmallow.validate import OneOf
from xivo.mallow import fields

from wazo_confd.helpers.mallow import BaseSchema


class HASchema(BaseSchema):

    node_type = fields.String(
        validate=OneOf(['disabled', 'master', 'slave']), required=True
    )
    remote_address = fields.IP()

    @validates_schema
    def check_remote_if_enabled(self, data, **kwargs):
        if 'node_type' not in data:
            return
        if data['node_type'] == 'disabled':
            return

        if not data.get('remote_address'):
            raise ValidationError('remote_address cannot be empty')

```

Any idea of what is causing the issue? thanks.

**Comment by deckar01** [comment]
Did you add `**kwargs` to `handle_error` in `BaseSchema`?

https://github.com/wazo-platform/wazo-confd/blob/master/wazo_confd/helpers/mallow.py#L21

**Comment by nissou91** [comment]
> Did you add `**kwargs` to `handle_error` in `BaseSchema`?
> 
> https://github.com/wazo-platform/wazo-confd/blob/master/wazo_confd/helpers/mallow.py#L21

Yes I did

**Comment by nissou91** [comment]
> Did you add `**kwargs` to `handle_error` in `BaseSchema`?
> 
> https://github.com/wazo-platform/wazo-confd/blob/master/wazo_confd/helpers/mallow.py#L21


```py
        if handle_error:

            def handle_error_fn(error, data, **kwargs):
                # Ugly hack to keep the same error message from python2 to python3
                # The message can be a dictionary and we do not want to cast it to string,
                # because there are some logic with the `type` in common.py
                if len(error.args):
                    message = error.args[0]
                else:
                    message = str(error)
                return abort(400, message=message)

            self.handle_error = handle_error_fn

    def on_bind_field(self, field_name, field_obj):
        # Without this, the nested schema handle error and abort. So the error
        # message will not include parent key and the rest of the parent schema
        # will not be validated
        self._inherit_handle_error(field_obj)

    def _inherit_handle_error(self, field_obj, **kwargs):
        if isinstance(field_obj, fields.Nested):
            field_obj.schema.handle_error = super().handle_error
        if isinstance(field_obj, fields.List):
            if hasattr(field_obj, 'inner'):
                self._inherit_handle_error(field_obj.inner)
            elif hasattr(field_obj, 'container'):
                self._inherit_handle_error(field_obj.container)

```

**Comment by deckar01** [comment]
What about `_deserialize` on custom fields?

https://marshmallow.readthedocs.io/en/stable/upgrading.html#custom-fields

https://github.com/wazo-platform/wazo-confd/blob/a4092d8090494edc0cf6ad2b41bc922cf2308d6c/wazo_confd/helpers/mallow.py#L70

https://github.com/wazo-platform/wazo-confd/blob/a4092d8090494edc0cf6ad2b41bc922cf2308d6c/wazo_confd/plugins/application/schema.py#L27

**Comment by nissou91** [comment]
> https://github.com/wazo-platform/wazo-confd/blob/a4092d8090494edc0cf6ad2b41bc922cf2308d6c/wazo_confd/plugins/application/schema.py#L27

Yes, I did a grep on the whole project:

```
grep -rn --include=\.*py . -e 'deserialize'
```

and I added ```**kwargs``` to all the results definitions (signatures).

I am really confused...

**Comment by nissou91** [comment]
> What about `_deserialize` on custom fields?
> 
> https://marshmallow.readthedocs.io/en/stable/upgrading.html#custom-fields
> 
> https://github.com/wazo-platform/wazo-confd/blob/a4092d8090494edc0cf6ad2b41bc922cf2308d6c/wazo_confd/helpers/mallow.py#L70
> 
> https://github.com/wazo-platform/wazo-confd/blob/a4092d8090494edc0cf6ad2b41bc922cf2308d6c/wazo_confd/plugins/application/schema.py#L27

I don't know if it is related; but I was thinking, is it maybe because of version collision? like in the original project; we were using Marshmallow 3.0.0b14 and now we are migrating the project to 3.10.0.

```
https://github.com/wazo-platform/wazo-lib-rest-client/archive/master.zip
https://github.com/wazo-platform/wazo-auth-client/archive/master.zip
https://github.com/wazo-platform/wazo-provd-client/archive/master.zip
https://github.com/wazo-platform/xivo-bus/archive/master.zip
https://github.com/wazo-platform/xivo-dao/archive/master.zip
https://github.com/wazo-platform/xivo-lib-python/archive/master.zip
cheroot==6.5.4
flask-cors==3.0.7
flask-restful==0.3.7
flask==1.0.2
kombu==4.6.11
marshmallow==3.10.0
netifaces==0.10.4
psycopg2==2.7.7  # from xivo-dao
python-consul==0.7.1
pytz==2019.1
pyyaml==3.13
requests==2.21.0
sqlalchemy==1.2.18  # from xivo-dao
stevedore==1.29.0
unidecode==1.0.23  # from xivo-dao
werkzeug==0.14.1

```

**Comment by deckar01** [comment]
```py
from xivo.mallow import fields
...
remote_address = fields.IP()
```

```py
class IP(_String):
    ...
    def _deserialize(self, value, attr, data):
```

https://github.com/wazo-platform/xivo-lib-python/blob/master/xivo/mallow/fields.py#L246

That library would need to be upgraded to marshmallow 3 also.

**Comment by nissou91** [comment]
> 

Yes, I also did that:

```py
def _deserialize(self, value, attr, data, **kwargs):
        deserialized = super(IP, self)._deserialize(value, attr, data, **kwargs)
        return self._validated(deserialized)
```

**Comment by deckar01** [comment]
It looks like [the PR for that dependency](https://github.com/wazo-platform/xivo-lib-python/pull/93) hasn't been merged, so [the `requirements.txt` in your PR](https://github.com/wazo-platform/wazo-confd/pull/245/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) are still installing the old version.

You could point the requirements URL to that feature branch to test it before merging, otherwise you will need to merge the dependency PR and restart your CI pipeline.

**Comment by nissou91** [comment]
> It looks like [the PR for that dependency](https://github.com/wazo-platform/xivo-lib-python/pull/93) hasn't been merged, so [the `requirements.txt` in your PR](https://github.com/wazo-platform/wazo-confd/pull/245/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) are still installing the old version.
> 
> You could point the requirements URL to that feature branch to test it before merging, otherwise you will need to merge the dependency PR and restart your CI pipeline.

you mean like this?

```
git+https://github.com/wazo-platform/xivo-lib-python/pull/93/merge

```

**Comment by deckar01** [comment]
https://stackoverflow.com/questions/13561618/pip-how-to-install-a-git-pull-request

**Comment by deckar01** [comment]
It looks like you could just change `master` to `Wazo-2638` in the existing URL though. I believe GitHub automatically generates those archives for all branches. Not sure if that is a requirement or just a preference.

**Comment by nissou91** [comment]
> It looks like you could just change `master` to `Wazo-2638` in the existing URL though. I believe GitHub automatically generates those archives for all branches. Not sure if that is a requirement or just a preference.

thanks @deckar01 , it really fixed the error that I was getting 👍
