### ISSUE TITLE
Serializing a mixed list

### ISSUE THREAD

**Issue by kishinmanglani** [marshmallow-code/marshmallow#195]
I have a list with two types of objects A and B with two different Schemas, ASchema and BSchema. I want to serialize this list, so that depending on the type of object it serializes it using the correct schema. Is this possible?

**Comment by sloria** [comment]
@kishinmanglani You could define a `Field` that is able to handle both types `A` and `B` and pass that to the `List` field.

**Comment by justanr** [comment]
@kishinmanglani I ran into this problem a while back while trying to handle serializing an object that could have two different kind of "owners". Luckily, @sloria provided a base recipe in a [similar issue](https://github.com/marshmallow-code/marshmallow/issues/42#issuecomment-54719736).

I have a [spin on it](https://github.com/justanr/owa/blob/dbaefee80d812a676c3d172818783552559caae7/owa/utils/schema.py#L79) in one of my projects, too. [Example usage](https://github.com/justanr/owa/blob/dbaefee80d812a676c3d172818783552559caae7/owa/schemas.py#L40)

**Comment by sloria** [comment]
Support for polymorphic fields won't be added to marshmallow core. See the implementations suggested above, as well as [marshmallow-polyfield](https://github.com/Bachmann1234/marshmallow-polyfield).

**Comment by ramnes** [comment]
For anyone out there that would like something simpler than marshmallow-polyfield, I overloaded `Nested` so that it also accept a list of schemas and iterates through them to check the data until it find a corresponding schema. It's kind of dumb (and almost surely very bad on performances), but it does the job.

https://gist.github.com/ramnes/89245fbd9f2dfff52a78

**Comment by jkryanchou** [comment]
Awesome Job I have do a lot research on the issue. Thanks all

**Comment by sampart** [comment]
I had a similar problem and solved it using the [Function](https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.fields.Function) field type and creating appropriate serialisation/deserialisation methods which checked the types.  Thought it worth mentioning in case it helps anyone - it's simpler than making your own field subclass.

**Comment by jkryanchou** [comment]
Cool

**Comment by kathur2rain** [comment]
finally I solved this problem by override fields.nested.  but I just find here's a, plugin? called marshmallow-oneofschema. which just might help.

**Comment by sloria** [comment]
Yes, https://github.com/Bachmann1234/marshmallow-polyfield and https://github.com/marshmallow-code/marshmallow-oneofschema are the two libraries I know that implement polymorphism.

I can't really recommend one over the other--we're using both in production (in different services), and both seem to work as advertised.
