### ISSUE TITLE
Why is it necessary to add missing=True when Required=False? Why is the error message "Field may not be null" instead of "Field may not be missing" ?

### ISSUE THREAD

**Issue by mkmoisen** [marshmallow-code/marshmallow#1950]
Assume the following schema:

```
from marshmallow import Schema, fields

class FooSchema(Schema):
    a = fields.Int(required=True)
    b = fields.Int(required=False)  # Forgot to include missing=None
```

This will not raise an error when the payload is missing the `b` field:

```
# No error, makes sense:
FooSchema().load({'a': 1})
```
However, it will raise an error when the payload contains a `b` field set to `None`:

```
# Raises ValidationError {'b': ['Field may not be null.']}
FooSchema().load({'a': 1, 'b': None})
# Why? What use case is this supposed to handle?
# Regardless, why is the  error "Field may not be null" instead of "Field may not be missing"?
```

The solution to this problem if to add `missing=None`:

```
class FooSchema(Schema):
    a = fields.Int(required=True)
    b = fields.Int(required=False, missing=None)

# No error
FooSchema().load({'a': 1})

# No error
FooSchema().load({'a': 1, 'b': None})
```

--

I have two questions about this behavior:

1) What use case is this behavior supposed to support? In what situation would I want an error to be raised if `required=False` but `missing` is not set to None?

I agree that if someone has this use case, the reasoning for this implementation is sensible in that this is the only non ambiguous way to support it.

That is understandable. But what I'm a bit confused about is the error message: `Field may not be null.`

2) Wouldn't `Field may not be missing` make more sense? The field absolutely may be null- so long as the field is included in the payload.

**Comment by lafrech** [comment]
`missing` (now deprecated, replaced with `load_default`) is a default value to use when the payload doesn't contain the field.

If `required` is `False` (which is the case by default), the field may be missing. But `None` is not accepted. It is not the same as a missing value. To allow `None`, you may set `allow_none=True`.

Also, setting `load_default=None` implies `allow_none=True`.

https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Field

**Comment by mkmoisen** [comment]
@lafrech Thanks, I will change to load_default.  FYI, the current documentation still suggests using `missing` [here](https://marshmallow.readthedocs.io/en/stable/quickstart.html#specifying-defaults).

For my knowledge, would you be able to give an example of a use case that just `required=False` is supposed to support, where I would want to raise an error if my field was set to None, but not raise an error if the field was missing?

```
class FooSchema(Schema):
    bar = fields.Int(required=False)

# No error
FooSchema().load({})

# ValidationError Field may not be null
FooSchema().load({'bar': None})
```

**Comment by lafrech** [comment]
> FYI, the current documentation still suggests using missing [here](https://marshmallow.readthedocs.io/en/stable/quickstart.html#specifying-defaults).

Oops. I guess we ought to update this.

> For my knowledge, would you be able to give an example of a use case that just required=False is supposed to support, where I would want to raise an error if my field was set to None, but not raise an error if the field was missing?

This is the default case. The value is not required, so load won't complain if it is missing. But `None` is not an integer, so unless you specify `allow_none=True` you get an error.

If the data is meant to be loaded in a SQL database, `None` may be fine, as ultimately, the column will end up being written as `NULL` in DB. But it may not always be the case. For instance, in MongoDB, missing value is different from null.

**Comment by lafrech** [comment]
> > FYI, the current documentation still suggests using missing [here](https://marshmallow.readthedocs.io/en/stable/quickstart.html#specifying-defaults).
> 
> Oops. I guess we ought to update this.

Done in #1952.

**Comment by mkmoisen** [comment]
@lafrech Thank you.
