### ISSUE TITLE
Why is Python 3.6 not the minimum supported version?

### ISSUE THREAD

**Issue by mkmoisen** [marshmallow-code/marshmallow#1954]
Hi, I was just curious why Python 3.6 was not the minimum supported version. 

Which features of Python 3.7 are used in Marshmallow that would make it incompatible with Python 3.6?

**Comment by lafrech** [comment]
Not much. Mainly the removal of the uses of `OrderedDict`. See #1923.

We don't support EOLed Python versions. https://endoflife.date/python
