### ISSUE TITLE
Use "data_key" only for loading

### ISSUE THREAD

**Issue by vanHoi** [marshmallow-code/marshmallow#1955]
Hello,

I have a question regarding the `data_key` parameter. I want to load (deserialize) a response from an API, using a key which is different from the field name in my schema. Then I want to use the field name in my code, and then also dump (serialize) the response with the field name.

For example given this API response:

```python
api_response = {
    "arrival": "2022-03-05T11:00:00+01:00",
    "departure": "2022-03-08T15:00:00+01:00"
}
```

And this schema:
```python
class UpdateBookingSchema(Schema):
    ArrivalDate = fields.AwareDateTime(required=True, data_key="arrival")
    DepartureDate = fields.AwareDateTime(required=True, data_key="departure")

    @validates_schema
    def validate_dates(self, data, **kwargs):
        if data["DepartureDate"] <= data["ArrivalDate"]:
            raise ValidationError("Departure date must be greater then arrival date.")
```

Should be dumped / serialized to:
```python
parsed_response = UpdateBookingSchema().load(api_response)
# Do some stuff
UpdateBookingSchema().dump(parsed_response)
{
    "ArrivalDate": "2022-03-05T11:00:00+01:00",
    "DepartureDate": "2022-03-08T15:00:00+01:00"
}
```

Can this be done? 

I did see in issue #1235 that this was supported in Marshmallow V2, but I can't get it to work, also not with the `attribute` property.

**Comment by deckar01** [comment]
Asymmetric mappings like this may require two schemas.

`A -> B -> B'` requires `A -> B (-> A)` and `(B' ->) B -> B'`

See https://github.com/marshmallow-code/marshmallow/issues/837#issuecomment-396491153

If you don't use integrations like apispec you could use a mixin. `pre_load`/`post_dump`can be used to map the keys using the original `load_from`/`dump_to` syntax.

See https://github.com/marshmallow-code/marshmallow/issues/717#issuecomment-428893346

**Comment by vanHoi** [comment]
Thanks for the super quick reply!

I've solved it with a `post_dump`, like you suggested. 

```python
    @post_dump
    def map_keys(self, data, **kwargs):
        return {
            "ArrivalDate": data["arrival"],
            "DepartureDate": data["departure"],
        }
```

I was hoping there was a nice(er) way to do it but this also works. After reading the discussion you mentioned I also get why this feature was removed.

Thanks for the help!
