### ISSUE TITLE
How to define a schema with dynamic field names

### ISSUE THREAD

**Issue by aflopes** [marshmallow-code/marshmallow#1959]
Hi all,

I have the need to define a schema that basically represents a `dict` object where I know that the `keys` are going to be strings and the `values` are all going to have the same object format.

I know that having this defined as a field of a schema can be done by using the `fields.Dict` just like
```
class ValueSchema(Schema):
    att_1 = fields.String()
    att_2 = fields.String()

class RootSchema(Schema):
    root = fields.Dict(keys=fields.String(), values=fields.Nested(ValueSchema))

# dict conforming to the schema
 {
    "root": {
        "id-1":{"att_1":"a", "att_2":"b"},
        "id-2":{"att_1":"c", "att_2":"d"}
    }
}
```

But what I want is to have a schema that represents just the `root` object, i.e. without the `root` field, just like
```
{
    "id-1": {"att_1":"a", "att_2":"b"},
    "id-2": {"att_1":"c", "att_2":"d"},
    (...)
    "id-N": {"att_1":"x", "att_2":"y"},
}
```

Is this something that can be done with marshmallow?

Thanks in advance

**Comment by deckar01** [comment]
```py
RootSchema = Schema.from_dict({key: fields.Nested(ValueSchema) for key in dynamic_data})
```

https://github.com/marshmallow-code/marshmallow/issues/972#issuecomment-517541656

**Comment by aflopes** [comment]
Thanks for the quick reply.

That should do it when you know the `dynamic_data`, but I want to define a Schema subclass, that is able to validate `dynamic_data` without knowing the key values that it will contain.

I've also noticed the post mentioned on #972 (https://stevenloria.com/dynamic-schemas-in-marshmallow/), and it gave me some ideas regarding other approaches to fix my problem.

**Comment by aflopes** [comment]
Either way this question is a duplicate of the #972, so if you feel that this issue does not make sense, feel free to close it!

**Comment by deckar01** [comment]
You can use `Schema.from_dict()` after you receive the data, only use the generated schema for that data, then generate a new schema when you get new data.

**Comment by aflopes** [comment]
I know!

Basically i'm using a decorator to do the schema validation of the bodies on HTTP requests, and I was passing the concrete `Schema` classes to it. This way I need to be able to pass also a factory of Schemas that will get built at runtime with the body that is to be validated.

**Comment by deckar01** [comment]
The only remaining issue seems to be preferred syntax. I would make a new decorator for `from_dict` rather than trying to overload a schema class so that you can pass it into a decorator expecting a schema class. Feedback on how you ended up working around it would be appreciated.

I am closing this for now. If you have a proposal that wasn't already discussed in #972 I am happy to reopen. I still promote unifying the `load`/`dump` schema interface with the field interface since it improves many other use cases, but the scope of that would probably justify a new issue.
