### ISSUE TITLE
Documentation states that dump validates data

### ISSUE THREAD

**Issue by andrewbaxter** [marshmallow-code/marshmallow#196]
The documentation states `Schema.dump() also validates the format of its fields and returns a dictionary of errors.` at http://marshmallow.readthedocs.org/en/latest/quickstart.html#validation

However, it doesn't appear to do any validation:

``` python2
from marshmallow import Schema, fields, pprint

class ASchema(Schema):
    x = fields.Int(required=True)

schema = ASchema()
begin = {}
end = schema.dump(begin)
print('begin: {}'.format(begin))
print('end: {}'.format(end))
```

Output:

```
begin: {}
end: MarshalResult(data={u'x': 0}, errors={})
```

Is this expected behavior?  Are there some types of errors that it will catch?

**Comment by sloria** [comment]
Perhaps the documentation can be clearer, but certain fields have built-in validation behavior on serialization, e.g. `fields.URL` and `fields.Email`. Also, any fields that can raise an `MarshallingError` (or a `ValidationError` in 2.0) can place errors in the errors dict. 

The validators passed as the `validate` argument , however, are only invoked on deserialization.

> validate (callable) – Validator or collection of validators that are called during deserialization.

https://marshmallow.readthedocs.org/en/latest/api_reference.html#marshmallow.fields.Field

**Comment by sloria** [comment]
Hopefully the documentation I've added in a739a1c helps to clarify this. https://marshmallow.readthedocs.org/en/dev/quickstart.html#validation

**Comment by andrewbaxter** [comment]
Yeah, that's awesome, thanks!
