### ISSUE TITLE
Support union type syntax as defined in PEP 604 and implemented in Python 3.10

### ISSUE THREAD

**Issue by zyv** [marshmallow-code/marshmallow#1962]
A new syntax for union types has been introduced in [PEP 604](https://peps.python.org/pep-0604/) and implemented in Python 3.10:

```python
dict[str, Union[str, bool]] == dict[str, str | bool]
```

Unfortunately, it is not currently supported in Marshmallow:

> UserWarning: Unknown type str | bool at XXX: list[dict[str, str | bool]] It's advised to pass the correct marshmallow type to `YYY`.

Because of that, we can't ban `Union` in our linter.

**Comment by sirosen** [comment]
> Unfortunately, it is not currently supported in Marshmallow
> ...
> Because of that, we can't ban `Union` in our linter.

Could you clarify what you mean by this? I don't think anything that marshmallow does should impact annotations you have in your own code.

---

Looking to see if we can remove marshmallow's own explicit `Union`s, I see them being used in type aliases in `marshmallow.types`. That means that without runtime support for unions -- meaning the removal of support for python3.9 and below -- we can't just substitute the nicer `|` syntax.

Today we have:
```python
# in types.py
StrSequenceOrSet = typing.Union[typing.Sequence[str], typing.Set[str]]
Tag = typing.Union[str, typing.Tuple[str, bool]]
```

We can pull in `typing_extensions` and do this
```python
from typing_extensions import TypeAlias

StrSequenceOrSet: TypeAlias = "typing.Sequence[str] | set[str]"
Tag: TypeAlias = "str | tuple[str, bool]"
```

but I don't feel great about requiring `typing_extensions;python_version<3.10` just for this purpose.
And I'm not sure how a stringified type alias is treated with and without the explicit TypeAlias annotation.

**Comment by zyv** [comment]
> Could you clarify what you mean by this? I don't think anything that marshmallow does should impact annotations you have in your own code.

Unfortunately, yes, it does: `dataclasses_json` uses `marshmallow` under the hood - type annotations of data classes are passed to `marshmallow` to perform validation. However, if `marshmalllow` cannot work with those type annotations it issues the warning like posted above.

This means that in our code for dataclasses, we are forced to use type annotations, which `marshmallow` can understand. So we can't simply ban `from typing import Union` in our linter, because we must still use `Union` on dataclasses, which will go through `marshmallow`.

Hope that clears it up!

**Comment by sirosen** [comment]
Hi, thanks for the detail. Are you sure that `marshmallow` is responsible? This sounds like a `dataclasses_json` issue.

`marshmallow` itself doesn't parse type annotations at all. If something is annotated as `Union`, and that has runtime implications for your code, something else has to be happening.

**Comment by zyv** [comment]
Thank you very much for your support! I have found the source of the warning in `dataclasses_json`:

https://github.com/lidatong/dataclasses-json/blob/3264a0046e1aa3c0a813335286ebdbc651f58b13/dataclasses_json/mm.py#L271

I have re-reported this issue to them as lidatong/dataclasses-json#349.

Please feel free to close this issue, if in your opinion there is nothing to be done in `marshmallow` and sorry for the noise!

**Comment by lafrech** [comment]
I don't think this is a marshmallow issue. Closing this for now.

Let's see what comes out of https://github.com/lidatong/dataclasses-json/issues/349.
