### ISSUE TITLE
fields.Integer requires both data_key and attribute to work

### ISSUE THREAD

**Issue by pjaol** [marshmallow-code/marshmallow#1978]
Using marshmallow 3.15.0

Finding that fields.Integer requires both data_key and attribute to handle different key names.
Which is inconsistent with other fields and documentation

From the quickstart docs 
Specifying Serialization/Deserialization Keys[¶](https://marshmallow.readthedocs.io/en/stable/quickstart.html#specifying-serialization-deserialization-keys)
```python
In [26]: class UserSchema(Schema):
    ...:     name = fields.String()
    ...:     email = fields.Email(data_key="emailAddress")
    ...: 
    ...: 
    ...: s = UserSchema()
    ...: 
    ...: data = {"name": "Mike", "email": "foo@bar.com"}
    ...: result = s.dump(data)

In [27]: result
Out[27]: {'emailAddress': 'foo@bar.com', 'name': 'Mike'}
```
Ok data_key works for email - does as it should, lets try Integer

```python
In [30]: class UserSchema(Schema):
    ...:     name = fields.String()
    ...:     email = fields.Email(data_key="emailAddress")
    ...:     id = fields.Integer(data_key="i-d")

In [31]: s = UserSchema()

In [32]: data = {"name": "Mike", "email": "foo@bar.com", "i-d": 123}

In [33]: result = s.dump(data)

In [34]: result
Out[34]: {'emailAddress': 'foo@bar.com', 'name': 'Mike'}
```

Fails to dump Integer with data_key "i-d" , add the attribute parameter ( tested and requires both to work ) 

```python
In [35]: class UserSchema(Schema):
    ...:     name = fields.String()
    ...:     email = fields.Email(data_key="emailAddress")
    ...:     id = fields.Integer(data_key="i-d", attribute="i-d")

In [36]: s = UserSchema()

In [37]: data = {"name": "Mike", "email": "foo@bar.com", "i-d": 123}

In [38]: result = s.dump(data)

In [39]: result
Out[39]: {'emailAddress': 'foo@bar.com', 'i-d': 123, 'name': 'Mike'}
```

Now works ; But is inconsistent with other fields and documentation.

**Comment by lafrech** [comment]
`data_key` is JSON side, `attribute` is object side. When dumping, marshmallow searches in the objet for `attribute` or field name and serializes as `data_key` or field name.

There is nothing specific to `Integer`. You're doing it right for the email field: you're using the field name in the object and `data_key` appears in the dump as expected.

The only use case where you need to set the same value to both `attribute` and `data_key` is when you want the same name in both the object and the serialized data, but this name is not a valid Python name, like `i-d` so you can't use it as field name.

**Comment by pjaol** [comment]
Ahh I see so if i used emailAddress in the dict for dump
```
data = {"name": "Mike", "emailAddress": "foo@bar.com", "i-d": 123}
```
then it would behave the same. 

I think my confusion comes from the wording in the quick start

> If you are **consuming and producing** data that does not match your schema, you can specify the output keys via the 
> data_key argument.

Would it be correct to update the wording to say 

>  If you are **consuming** data that does not match your schema you can use `attribute`
> If you are **producing** data that does not match your schema, you can specify the output keys via the data_key argument.
```python
In [13]: class UserSchema(Schema):
    ...:     name = fields.String()
    ...:     email = fields.Email(data_key="emailAddress")
    ...:     id = fields.Integer(attribute="i-d")
    ...: 

In [14]: s = UserSchema()

In [15]: data = {"name": "Mike", "email": "foo@bar.com", "i-d": 123}

In [16]: result = s.dump(data)

In [17]: result
Out[17]: {'emailAddress': 'foo@bar.com', 'id': 123, 'name': 'Mike'}
```

**Comment by lafrech** [comment]
I think the idea is that the typical use case is using marshmallow to build an API that consumes / produces JSON to load / dump from objects.

We don't see consume as object -> schema and produce as schema -> dump, but rather

```
                     Consume <--
                     Produce  -->
Object   <->  Schema  <-> JSON
      attribute     data_key
```

**Comment by pjaol** [comment]
People always find a way to use things "not how they were designed" :-) 
The use case I'm using it for is to thame an API from a BI tool that's very unwieldy and hyper-verbose. 

Marshmallow is able to help me take just the essentials and produce them in a format that just works.
Essentially a client, and it does it very neatly!
