### ISSUE TITLE
Confusing Meta option in examples

### ISSUE THREAD

**Issue by marekradecki** [marshmallow-code/marshmallow#1980]
In  [one of the examples](https://github.com/marshmallow-code/marshmallow/blob/5f7e6172acdadc6221b21faf921fcf3fe8f1aa23/examples/peewee_example.py#L42)  there is `Meta.order_by` defined, however I don't see trace of support for something like this in codebase after all.

**Comment by lafrech** [comment]
Yeah. Looks like it could be removed.

The sort is explicit at https://github.com/marshmallow-code/marshmallow/blob/5f7e6172acdadc6221b21faf921fcf3fe8f1aa23/examples/peewee_example.py#L173

**Comment by sirosen** [comment]
Looks like peewee removed order_by in v3.0:
http://docs.peewee-orm.com/en/latest/peewee/changes.html#model-meta-options

I was just putting together a PR to remove this, but I realize that the OP might be confused about peewee models vs marshmallow schemas. I'm going to go ahead with the PR, but wanted to make sure this was clarified. That example code is using marshmallow + another library.
