### ISSUE TITLE
Default field values

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/marshmallow#199]
Most typed fields (`String`, `Integer`, `Decimal`) have default values of the corresponding type: `String` defaults to `''`, `Integer` to `0`, etc. This has the desirable effect of making serialized types predictable, but also introduces some potentially counter-intuitive behavior: attributes set to `None` are serialized as `''`, `0`, etc:

``` python
class Model(Base):
    id = sa.Column(sa.Integer, primary_key=True)
    count = sa.Column(sa.Integer, nullable=True)

class Schema(ma.Schema):
    count = ma.fields.Integer()

row = Model(id=1)
Schema().dump(row).data    # {"id": 1, "count": 0}
```

In this example, using SQLAlchemy, `count` is a nullable column: `None` values are allowed, and probably mean something different from `0`. I wasn't expecting `None` to be serialized to `0`--I actually only noticed because I was refactoring some code to use Marshmallow, and I broke some tests.

In this case, I can get the behavior I want by explicitly setting a `default` value for the schema field: `count = ma.fields.Integer(default=None)`. But I'm wondering whether that should be the default behavior of Marshmallow. It makes fewer assumptions about developers' intentions, and I think it would be less [surprising](http://en.wikipedia.org/wiki/Principle_of_least_astonishment). It would also make behavior a little more consistent across field subclasses: most subclasses use a non-`None` default value, but `DateTime` actually defaults to `None`.

Proposal: All fields (other than `List`, or with `many` set to `True`) should default to `None` unless a different default is provided by the developer.

**Comment by sloria** [comment]
Thanks for the feedback @jmcarp . Your point re: nullable fields is convincing and a common enough use case to justify making `None` the default.

Also, `None` is semantically distinct from a missing value, so I agree that "converting" `None` to a different value may be unintuitive.

**Comment by sloria** [comment]
If we move forward with this, I'm not sure that `List` fields should be special-cased. Thoughts, @jmcarp?

**Comment by jmcarp** [comment]
Seems like the simplest thing is to have all fields default to `None`, including `List`. There are use cases for defaulting to `[]`, but I think it's all right for developers to specify that manually. Seems like the same issue also applies to `Nested` fields with `many=True`.

**Comment by sloria** [comment]
Upon further consideration, I think allowing `None` to be serialized to `None` is the most sensible thing to do, given that `allow_none=True`. This goes for List fields and Nested fields.

@jmcarp Would you like to a send PR? Otherwise, I can work on this over the next few days.

I thinks this issue brings up a related issue: what should the default output be if the `default` argument is not provided and the field's input value is missing?

``` python
class MySchema(Schema):
    non_required = fields.Str(required=False)  # no default specified

sch = MySchema()
sch.dump({})
```

Should the output include the missing value? Default to `None`?

``` python
{}
# or
{'non_required': None}
```

**Comment by sloria** [comment]
I think I lean towards excluding the value in the dumped output if the attribute/key is missing in the input and no `default` was provided. 

So how about the following proposal:

All fields default to `marshmallow.missing`. Effectively, a default value is only used when the user explicitly sets it. Remove any "special" defaults on `String`, `Number`, `List`, `Nested(many=True)`, etc.

**Comment by jmcarp** [comment]
:+1:

**Comment by sloria** [comment]
Moving forward with the proposal in https://github.com/marshmallow-code/marshmallow/issues/199#issuecomment-95026519 . I will implement this soon.
