### ISSUE TITLE
Bug: outdated docstring type annotation at get_decalred_field

### ISSUE THREAD

**Issue by krepysh** [marshmallow-code/marshmallow#2004]
Actual name of argument is `dict_cls`, but docstring refer to `dict_class`

https://github.com/marshmallow-code/marshmallow/blob/e48dfc5e5020b2f4aeefdc343e1a48c9a6d34621/src/marshmallow/schema.py#L130-L147

**Comment by lafrech** [comment]
Good catch.

Fixed in b9e1511.
