### ISSUE TITLE
`pytest` on v3.17.0 failing with `TypeError`

### ISSUE THREAD

**Issue by xylar** [marshmallow-code/marshmallow#2007]
On our build of the latest release (v3.17.0) on conda-forge, we're seeing:
```
_______ ERROR collecting tests/mypy_test_cases/test_validation_error.py ________
tests/mypy_test_cases/test_validation_error.py:20: in <module>
    d: dict = err.messages_dict
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages/marshmallow/exceptions.py:53: in messages_dict
    raise TypeError(
E   TypeError: cannot access 'messages_dict' when 'messages' is of type list
```
See https://github.com/conda-forge/marshmallow-feedstock/pull/61

**Comment by deckar01** [comment]
In your build `python -m pytest tests` is collecting the mypy test in `tests/mypy_test_cases`. I can't reproduce that behavior locally using python 3.10 and pytest 7.1.2.

**Comment by deckar01** [comment]
It looks like we explicitly added `tests/mypy_test_cases` to `[tool:pytest]norecursedirs` in `setup.cfg`. It looks like you may need to configure your project to do the same.

https://github.com/marshmallow-code/marshmallow/pull/1976/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R11

**Comment by deckar01** [comment]
I suspect changing `source_files: tests/*` to `source_files: tests/*.py` would avoid the recursive globbing. We should probably consider moving the tests elsewhere instead of fighting against the default pytest behavior though.

**Comment by lafrech** [comment]
You beat me to it. Yes, that's the reason of the build failure.

I can't reproduce this locally either, though. Python 3.9.2, pytest 6.2.5.

**Comment by xylar** [comment]
@deckar01, thank you!  Limiting our testing to `source_files: tests/*.py` did, indeed, take care of this.
