### ISSUE TITLE
@pre_load function and fields.Datetime() unexpected behavior

### ISSUE THREAD

**Issue by matiasrebori** [marshmallow-code/marshmallow#2009]
Serialization of a model doesnt work as expected because of a `@pre_load` function name that is the same as the field.
Schema:
```python
class MarcasSchema(SQLAlchemyAutoSchema):
    fecha_reg = fields.DateTime(format='%d/%m/%Y')
    
    class Meta:
            model = Marcas
            load_instance = True

    @pre_load
    def fecha_reg(self, data, **kwargs):
        data['fecha_reg'] = datetime.now().isoformat()
        return data
```

fecha_reg saves the moment when the data is created, in the db(postgres) fecha_reg it's a timestamp
### The problem
The problem arises when trying to serialize the schema, fecha_reg is serialized as a iso string not as the custom format.
Expected value: 04/05/2022
Actual: 2022-06-13T10:52:39.643999
### Solution
changing the `@pre_load` function to a name that is not the field name i.e. from `def fecha_reg` to `def step1`, fecha_reg is serialized correctly.
**I'm submitting this issue because I couldn't find anything that talks about this in the documentation.** [extending schemas](https://marshmallow.readthedocs.io/en/stable/extending.html)
**i dont know if i couldt find it in the docs, maybe it isn´t in the docs at all, or it could be an unexpected behavior.**

**Comment by lafrech** [comment]
This is not a marshmallow issue. The definition of the method hides the field.

```py
class MyClass:

    attribute = None

    def attribute(self):
        print("This method shadows the attribute above")
```

A static analysis tool like pylint warns about this (`function-redefined`).

**Comment by matiasrebori** [comment]
thanks, I hadn't noticed, I thought it was a Marshmallow problem but it was much simpler.
