### ISSUE TITLE
Add useful `__repr__` methods for validators

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#204]
When inspecting a `Field`, it's useful to have a human-friendly representation of the field's validators, e.g. seeing the `min` and `max` values for a `Range` or `Length` validator.

**Comment by philtay** [comment]
What about something like this?

``` python
class Validator(object):
    """Base abstract class"""

    def __repr__(self):
        return (
            '<validate.{ClassName}({_args}, error={self.error!r})>'
            .format(ClassName=self.__class__.__name__, self=self)
        )


class Range(Validator):
    def __repr__(self):
        rep = 'min={0!r}, max={1!r}'.format(self.min, self.max)
        return super(Range, self).__repr__().format(_args=rep)
```

P.S. Is it time to start removing deprecated fields and validator functions? I could open some PR, just  to speed up a bit the final release of 2.0

P.P.S Don't forget to tag 2.0.0b1 here: https://github.com/marshmallow-code/marshmallow/releases

**Comment by sloria** [comment]
@philtay Maybe make a slight modification to make the `super` call unnecessary:

``` python
class Validator(object):
    """Base abstract class"""
    def __repr__(self):
        return (
            '<validate.{ClassName}({args}, error={self.error!r})>'
            .format(ClassName=self.__class__.__name__, self=self, args=self._repr_args())
        )

class Range(Validator):
    def _repr_args(self):
        return 'min={0!r}, max={1!r}'.format(self.min, self.max)
```

> Is it time to start removing deprecated fields and validator functions? I could open some PR, just to speed up a bit the final release of 2.0

My plan was to remove deprecated fields/validators in a minor release, e.g. 2.1.0, in order to ease migration to 2.0.0. 

When that time comes, I was also thinking of turning the lowercased validator functions into aliases of the class validators. I'm not committed to it, but I think it'd make the validator implementation (function factory vs. callable class) more transparent.

> Don't forget to tag 2.0.0b1 here

Thanks. Just pushed the tag.

**Comment by philtay** [comment]
Agreed, without `super` is better. I still have a doubt however. What `args` should be for a validator like `Email`? There are no `args` other than `error`.

**Comment by sloria** [comment]
@philtay We could do something like

``` python
def __repr__(self):
    args = self._repr_args()
    class_name = self.__class__.__name__
    if args:
        return (
            '<validate.{ClassName}({args}, error={self.error!r})>'
            .format(ClassName=class_name, self=self, args=args)
        )
    else:
        return (
            '<validate.{ClassName}(error={self.error!r})>'
            .format(ClassName=class_name, self=self)
        )


```

**Comment by philtay** [comment]
Ok, let me know if this is ok with you:

``` python
class Validator(object):
    """Base abstract class for validators."""

    def __repr__(self):
        class_name = self.__class__.__name__
        args = self._repr_args()
        args = '{0}, '.format(args) if args else ''

        return (
            '<validate.{ClassName}({args}error={self.error!r})>'
            .format(ClassName=class_name, self=self, args=args)
        )

    def _repr_args(self):
        return ''
```

Anyway there is another thing to discuss. The error message is created/interpolated during validation, so the repr string can be something like this:

`<validate.URL(relative=False, error='"{input}" is not a valid URL.')>`

or worse:

`<validate.Range(min=3, max=5, error=None)>`

Note that, even if error is None, a message will be present in the ValidationError exception.

EDIT: Python code

**Comment by sloria** [comment]
@philtay I think it is fine to show `error=None` or `error='"{input}"...`. The usefulness of `repr` is that it gives information about how to reconstruct the object (e.g. by showing the original arguments passed to the constructor). It doesn't necessarily need to show the final output error message.

**Comment by philtay** [comment]
Yes, I know. It's just that it feels a bit "ugly", at least to me. Anyway, I'll implement this during the weekend as I can't come up with a better idea.

When do you think 2.0 will be released? Is there any release blocker?

**Comment by sloria** [comment]
@philtay There is no set release date for 2.0.0, though the API has stabilized and is ready to use. Next pypi release will likely be a release candidate. 

I would like to make a decision on https://github.com/marshmallow-code/marshmallow/issues/198, as it is a potentially breaking change.

I would also like to see the the `validates` decorator proposed in https://github.com/marshmallow-code/marshmallow/issues/116#issuecomment-87404697 , though it isn't absolutely necessary before 2.0.0-final.
