### ISSUE TITLE
Must a Schema be instantiated for each Serialization?

### ISSUE THREAD

**Issue by mkmoisen** [marshmallow-code/marshmallow#2052]
Not a bug, just a question.

Is it OK to instantiate a schema one time and use the instance for all serialization, or is the schema supposed to be instantiated once for each serialization?

For example, most examples I see do the following where the schema is instantiated once per serialization. This makes me think that I'm supposed to instantiate it each time I want to serialize data.

```
class Foo(Schema):
    bar = fields.Str()

@app.post('/api/foos/')
def post_foo():
    foo_schema = Foo()
    return foo_schema.load(request.json)
```

Is it OK to do this instead:

```
foo_shema = Foo()

@app.post('/api/foos/')
def post_foo():
    return foo_schema.load(request.json)
```

Thanks and best regards,

Matthew

**Comment by lafrech** [comment]
An instance may be used many times. No need to instantiate each time.
