### ISSUE TITLE
Replace field with default value if is null

### ISSUE THREAD

**Issue by filipecmedeiros** [marshmallow-code/marshmallow#2060]

**Comment by lafrech** [comment]
You may specify `load_default` to indicate a default value for missing fields.

If your point is to consider null as missing, then this is what #1381 would allow you to customize.

**Comment by filipecmedeiros** [comment]
I would like to turn a field sent as null into a default value, for example:

`"some_field": null` -> `"some_field": 0`

But I believe that https://github.com/marshmallow-code/marshmallow/pull/1381 would make it possible.

Thanks!
