### ISSUE TITLE
Unexpected `TypeError` raised using `Function` fields with list-like objects

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/marshmallow#207]
The following example raises an uncaught, and unexpected, `TypeError`:

``` python
import marshmallow as ma

class SumSchema(ma.Schema):
    sum = ma.fields.Function(lambda obj: sum(obj))

SumSchema().dump([1,2,3])
```

The error is raised in `_get_value_for_key`, which implicitly assumes that objects that are indexable, not strings, and not dictionaries will only raise a `KeyError` when we look up a value using square brackets. This isn't the case for lists and list-like objects: a list isn't a dict or a string, and it is indexable, but indexing into it with a string key raises `TypeError`, not `KeyError`.

It seems like the intention of `_get_value_for_key` is to look up keys in mappings, not in any indexable object. If that's the case, I think it would make sense to explicitly check whether the object is a mapping, like this:

``` python
import collections

def _get_value_for_key(key, obj, default):
    if isinstance(obj, collections.Mapping):
        return obj.get(key, default)
    if isinstance(key, basestring) and hasattr(obj, key):
        return getattr(obj, key)
    return default
```

Otherwise, if this helper is meant to be able to index into sequences as well, I think we need a more general exception check:

``` python
def _get_value_for_key(key, obj, default):
    if isinstance(obj, dict):
        return obj.get(key, default)
    if isinstance(key, basestring) and hasattr(obj, key):
        return getattr(obj, key)
    if is_indexable_but_not_string(obj):
        try:
            return obj[key]
        except KeyError, IndexError, TypeError:
            return default
    return default
```

**Comment by sloria** [comment]
Good catch. I believe this is related to the bug reported in https://github.com/marshmallow-code/marshmallow/issues/28#issuecomment-98202504. 

Currently, `_get_value_for_key` handles both mappings and collections. I think the fixes you're proposing (both checking `isinstance(obj, collections.Mappng)` and making the exception handling more generic) are correct. Would you like to send a PR with those?
