### ISSUE TITLE
Download the latest documentation

### ISSUE THREAD

**Issue by 4l1fe** [marshmallow-code/marshmallow#2075]
Hey. On the [readthedocs page](https://readthedocs.org/projects/marshmallow/downloads/) i can download only **2.x** version.

Where can i find the latest version doc to download?

**Comment by deckar01** [comment]
The PDF builds were explicitly disabled in https://github.com/marshmallow-code/marshmallow/commit/bad5f3368c2bec3056c6f3bae8e9379cb88cf5ef. Apparently "PDF builds are rather flaky". I can't get sphinx to generate a PDF on my machine, but your milage may vary.

https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.latex.LaTeXBuilder
