### ISSUE TITLE
Unnecessary call to `get_value` for `Function`, `Method` fields

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/marshmallow#208]
Related to #207.

On serializing, `Function` and `Method` fields make a call to `Field#get_value`. The result of this call is then discarded, because the `_serialize` method of both fields ignores the `value` parameter that gets passed in. In most use cases, this won't have any meaningful performance penalty, but it's still unnecessary work. And incidentally, the issue I ran into in #207 wouldn't have come up if `Field#serialize` could skip the call to `Field#get_value` where that value won't be used.

How about skipping the call to `get_value` when `_CHECK_ATTRIBUTE` is `False`? It seems like that would be more consistent with the naming of the flag than the current behavior, and it would save the extra call.

**Comment by sloria** [comment]
+1 to removing the unnecessary call when `_CHECK_ATTRIBUTE = False`. In that case, we can just pass `None` or `missing` as the `value` argument.
