### ISSUE TITLE
Facing issue in loading JSON in List

### ISSUE THREAD

**Issue by indiVar0508** [marshmallow-code/marshmallow#2082]
Hi, 

i have a usecase where i am trying to load a parameter coming to my app using marshmallow schema via get call, my app uses `SmorestBlueprint` to parse arguments.

`sort: [{"selector":"Id","desc":false}]`

my schema is 

```py
from marshmallow import Schema
from marshmallow import fields

class MySchema(Schema):
    
    class InternalSchema(Schema):

        selector = fields.Str()
        desc = fields.Boolean()

    sort = fields.List(fields.Nested(InternalSchema))

sort='[{"selector":"createdDate","desc":true}]'

MySchema().load(sort)
``` 

**output**
```py
Traceback (most recent call last):
  File "temp.py", line 15, in <module>
    SortQuerySchema().load(sort)
  File "venv/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "venv/lib/python3.8/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'_schema': ['Invalid input type.']}
```

can you help me with this?

**Comment by deckar01** [comment]
1. `sort` is a JSON encoded string, but `load()` expects a dict. If your JSON has not been parsed you must use `loads()`.

https://marshmallow.readthedocs.io/en/stable/marshmallow.schema.html#marshmallow.schema.Schema.loads

2. The schema expects a `sort` key to contain the list.

```py
sort={"sort": [{"selector":"createdDate","desc":True}]}
```

You can use the `many` flag of `Schema.load()` to deserialize each item with one schema.

https://marshmallow.readthedocs.io/en/stable/marshmallow.schema.html#marshmallow.schema.Schema.load

```py
sort = [{"selector": "createdDate", "desc": True}]
InternalSchema().load(sort, many=True)
```

**Comment by indiVar0508** [comment]
Hi @deckar01 , 

thanks for quick response, but when using `SmorestBlueprint` i am not explicitly loading the data as of now as part of workaround i used `feilds.Method` to load the data with my own custom function defined in schema.

I tried this and it works!, but but how do i get it working with blueprint?
```py
sort = [{"selector": "createdDate", "desc": True}]
InternalSchema().load(sort, many=True)
```


above code i kept to reproduce the error, currently this is what i am getting in error message in my application.
```py
marshmallow.exceptions.ValidationError: {'sort': {0: {'_schema': ['Invalid input type.']}}}
```

i printed the arguments that are coming in my application using request module in flask

```py
ImmutableMultiDict([('sort', '[{"selector":"createdDate","desc":true}]'), ('param3000', 'val3000'), ('paramn', 'valn'), ('param1', 'val1')])
```

i have defined my route like this, 
```py
@blueprint.arguments(MySchema, location='query', as_kwargs=True)
def get(xyz):
   ...
```

based on app logs i see this is the call that i am getting
`GET /my_api/e_point?sort=%5B%7B%22selector%22:%22createdDate%22,%22desc%22:true%7D%5D&`

can you help me on how should i define my schema so `SmorestBlueprint` is able to parse the value on it's own?


thanks you

**Comment by indiVar0508** [comment]
i modified my Schema to this
```py
from marshmallow import Schema
from marshmallow import fields

class InternalSchema(Schema):

    selector = fields.Str()
    desc = fields.Boolean()

class MySchema(Schema):

    sort = fields.Nested(InternalSchema, many=True)
sort='[{"selector":"createdDate","desc":true}]'

a = InternalSchema().loads(sort, many=True)
print(a)

sort='{"sort": [{"selector":"createdDate","desc":true}]}'

a = MySchema().loads(sort)
print(a)

a = MySchema().load(sort)  ## gives error as it should
print(a)
```
I think issue is that internally SmorestBlueprint is invoking `load` instead of `loads` to deserialise the parameters not sure though, couldn't find exact location where loading happens

**Comment by deckar01** [comment]
Right, there is currently no way to declare that parsed data contains serialized JSON values. Per, https://github.com/marshmallow-code/flask-smorest/issues/435#issuecomment-1365951467, you will have to customize a field to explicitly parse the encoded string as a dict.

This API pattern is generally discouraged, so we probably would not add any API features to cater to this use case. You may want to reconsider JSON encoding query parameters if that is an option.

https://softwareengineering.stackexchange.com/questions/403251/is-it-a-bad-idea-to-pass-json-objects-on-the-query-string-for-an-api-search-op
