### ISSUE TITLE
Feature request: Latest version 2 compatible with version 3 to ease the migration

### ISSUE THREAD

**Issue by matejsp** [marshmallow-code/marshmallow#2087]
We would like to migrate from 2 to 3, but are having a lot of difficulties because this library is not backwards compatible and we have really huge code base.

I mean it is fine to break compatibility but I would expect older version to emit a warning helping migrate the project in a small steps. But this library upgrade is living nightmare. I like the Django way of upgrading. Next version is compatible with previous with warnings how to migrate to latest syntax. This way you can iterate and not a big bang approach that breaks everything.

For example v2 emits a warning:
The dateformat option is renamed to datetimeformat in marshmallow 3
The json_module option is renamed to render_module in marshmallow 3

But why does not already accept also new format in v2 if it emits a warning. You need to work around the warning because it is not even solvable in v2 version.

Next thing is load_from and dump_to that is migrated to data_key, but last version 2 is not accepting new format and not even emitting a warning. Or meta data on a field.

Or inside v3 have SchemaOpts field to support v2 behaviour and then migrate functionality schema by schema.

**Comment by lafrech** [comment]
We could have done a bit of this. In fact, we've been introducing v4 changes in v3 with deprecation warnings already. But we can't do this 100%. I mean all changes in v3 can't be backported in v2 without breaking it. Breaking changes in v3 allowed us to do a lot of refactoring and provide new features we couldn't have produced without them.

We could have added more deprecation warnings in v2, perhaps, but that wouldn't help so much. The upgrading guide should be quite complete. You might be able to do the upgrade more gradually through to v3 beta versions but I wouldn't bother if I were you.

v3 has been out for a while and v2 is long gone so don't expect anything to happen with regard to v2 compatibility.
