### ISSUE TITLE
No PDF download option for docs?

### ISSUE THREAD

**Issue by falloutphil** [marshmallow-code/marshmallow#2113]
Hi,

On the readthedocs page there is no PDF download option:

![image](https://user-images.githubusercontent.com/15717136/227710213-c8003100-3f0e-4dbd-853f-1b335789fa8b.png)

Any chance you could enable this - for example so it looks like this?

![image](https://user-images.githubusercontent.com/15717136/227710184-b34e2bc7-1b7b-4657-bb35-aaaee2dd3ad6.png)

Cheers!

**Comment by sloria** [comment]
The `latest` branch now has PDF builds enabled. https://readthedocs.org/projects/marshmallow/downloads/

`stable` will also have PDF downloads after the next pypi release
