### ISSUE TITLE
Null Booleans Deserialize to False

### ISSUE THREAD

**Issue by cmanallen** [marshmallow-code/marshmallow#213]
I have a boolean field that is required only if some other field is filled in (I cannot specify `required=True` on the dependent field).  So I've written a schema validator to check: if first_field is True then second_field is required.

This dependent boolean field is not something that can default to `true` or `false`.  If a user does not fill in the boolean field, I would like Marshmallow to throw a validation error.  However, because null booleans automatically deserialize to `False`, I cannot check if the boolean came in as `None` or `False`.

Is there a way to prevent this behavior?

**Comment by sloria** [comment]
Thanks for reporting, @cmanallen . This is indeed a bug; all fields should serialize `None` to `None`. I've made the change in 077e071, and the patch will be released in 2.0.0b3
