### ISSUE TITLE
Validating fields across schemas with Schema.validator

### ISSUE THREAD

**Issue by cmanallen** [marshmallow-code/marshmallow#214]
I have two schemas.  `SchemaA` (primary) and `SchemaB` (nested through fields.Nested).

If `field` from `SchemaA` is in input_data, I would like to throw a validation error if `other` field from `SchemaB` is not in input_data.  However, `ValidationError` seems to only support appending errors to fields within the current schema.  How can I append an error to a field in another schema, not referenced by the `@SchemaA.validator` decorator.

Sample code if the above isn't explicit enough:

``` python
class SchemaA(Schema):
    field = fields.Boolean()
    links = fields.Nested(SchemaB)

class SchemaB(Schema):
    other = fields.String()

@SchemaA.validator
def validate_other_field(schema, input_data):
    # some conditional
    raise ValidationError('Error', 'other')
```

Desired output:

``` json
"errors": {
    "field": "Must fill in required field.",
    "links": {
        "other": ['Error']
    }
}
```

**Comment by philtay** [comment]
This a problem that, IMO, falls in the "dot notation" class of problems. Ref. #151, #180.
I think we should implement `flatten` and `unflatten` like [Colander does](http://docs.pylonsproject.org/projects/colander/en/latest/manipulation.html#flattening-a-data-structure).
Any subfield should be referenceable from a parent schema no matter how deep it is.

**Comment by cmanallen** [comment]
I used the `@Schema.error_handler` decorator to manually move the error into the appropriate nesting.  I raised the error initially by passing a `dict` as the only parameter to `ValidationError`.  

```
raise ValidationError({'field': 'error message'})
```

Then I just moved the field error from `_schema` to `links`.
