### ISSUE TITLE
3.20.0 seems to break marshmallow_sqlalchemy

### ISSUE THREAD

**Issue by Cheaterman** [marshmallow-code/marshmallow#2152]
As you can see in the title, my CI just broke:
```
/env/lib/python3.11/site-packages/marshmallow_sqlalchemy/schema.py:143: in <module>
    class SQLAlchemySchema(
/env/lib/python3.11/site-packages/marshmallow/schema.py:116: in __new__
    klass._declared_fields = mcs.get_declared_fields(
E   TypeError: SQLAlchemySchemaMeta.get_declared_fields() missing 1 required positional argument: 'dict_cls'
```
Possibly an issue on their end more than yours, but someone had to report it somewhere. :-)

**Comment by alissonpelizaro** [comment]
Same here:

```
../../../.cache/pypoetry/virtualenvs/alertmanager-N7xkbwbh-py3.10/lib/python3.10/site-packages/marshmallow_sqlalchemy/__init__.py:9: in <module>
    from .schema import (
../../../.cache/pypoetry/virtualenvs/alertmanager-N7xkbwbh-py3.10/lib/python3.10/site-packages/marshmallow_sqlalchemy/schema.py:143: in <module>
    class SQLAlchemySchema(
../../../.cache/pypoetry/virtualenvs/alertmanager-N7xkbwbh-py3.10/lib/python3.10/site-packages/marshmallow/schema.py:116: in __new__
    klass._declared_fields = mcs.get_declared_fields(
E   TypeError: SQLAlchemySchemaMeta.get_declared_fields() missing 1 required positional argument: 'dict_cls'
```

Downgrading to 3.19 solve that.

**Comment by Cheaterman** [comment]
Yeah I also downgraded temporarily ; but on second thought (and as opposed to what I originally wrote) I suppose this is part of public API given the lack of leading underscore, and probably something that shouldn't have broken on marshmallow's side?

**Comment by lafrech** [comment]
Yep, my bad. Fix released.

Adding a default value to `get_declared_fields` is not a breaking change in itself. The issue was the removal of the `dict_cls` parameter used to call it from `__new__` , which broke class overriding `get_declared_fields`.

Sorry about that.

Thanks for reporting immediately.

**Comment by techguydave** [comment]
Thanks for fixing this so quickly! 🚀
