### ISSUE TITLE
fields.DateTime - add precision to timestamp 

### ISSUE THREAD

**Issue by alv000h** [marshmallow-code/marshmallow#2154]
Hi,

I am reading timestamp from postgres database and by default it comes with only 3 decimals (miliseconds precision) and you expect 6 decimals with %f formatter in marshmallow.

that is why I am unable to parse datetimes from postgres in an easy way.. default format is like this:

- **'%Y-%m-%d %H:%M:%S.%f'[:-3]**  

- 2023-03-08 07:24:45.**108**

Finally I have had to change my query to force timestamp with 6 decimals (microseconds precision) this is undesirable in several ways (think about using ORM like sqlalchemy).

Please, could you add a precission parameter like in other field types?

**Comment by deckar01** [comment]
This is a constraint imposed by the core `datetime` module.

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

If you need to deviate from this I would recommend making a custom field.

https://marshmallow.readthedocs.io/en/stable/custom_fields.html#creating-a-field-class
