### ISSUE TITLE
post_dump: where are the raw data ?

### ISSUE THREAD

**Issue by gouyou** [marshmallow-code/marshmallow#216]
I've read #153 and I'm missing something, where do we get the raw data?

My specific use case is a bit borderline:
I have an object A which contains a list of object Bs, and each object B has a dictionary. I wanted to do something like:

``` python
class ASchema(Schema):
    bs = fields.Nested('BSchema', many=True)

class BSchema(Schema):
    @postdump
    def f(self, data, obj):
        for k, v in obj.extra_data.iteritems():
            data[k] = v
        return data
```

Quickly reading through the documentation I tried it with data_handler to be running into issues with A containing a collection of B instances. Looking into dump_data, I thought that raw meant I would have access to the raw data, but it just let you know if it's a collection or not. So it doesn't loo like post_dump works for me...
Any other solution for my use case?

**Comment by sloria** [comment]
One simple solution would be to pass the `extra` argument:

``` python
BSchema(extra=obj.extra_data).dump(obj)
```

Alternatively, you could add object to the Schema's context so that it is accessible to your `post_load` handler:

``` python
class BSchema(Schema):
    @post_dump
    def add_extra_data(self, data):
        obj = self.context.get('obj', None)
        for key, value in getattr(obj, 'extra_data', {}).items():
            data[key] = value
        return data

thing = Thing()
sch = MySchema()
sch.context['obj'] = thing
sch.dump(thing)
```

Does this meet your use case?

**Comment by sloria** [comment]
I am considering adding a `pass_object` parameter to the `pre/post_load/dump` decorators that would add the target object to the signature of the methods.

**Comment by sloria** [comment]
The `pass_original` parameter has been added to `post_dump` and `post_load` in https://github.com/marshmallow-code/marshmallow/commit/1463a61d1bb6fa5b0c18acdfdb1ec4c4a003fb3f
