### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [marshmallow-code/marshmallow#2167]
Is it possible next time on release new version make the github release to have entry on https://github.com/marshmallow-code/marshmallow/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://pgjones.dev/blog/trusted-plublishing-2023/
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by lafrech** [comment]
I don't intend to create manual releases, but I understand the need and I'm open to automatic releases (using GH actions, for instance). Can't look at it right now but if someone is willing to look at it, they are very welcome.

**Comment by deckar01** [comment]
https://github.com/elgohr/Github-Release-Action looks like a nice option if we are only concerned with mirroring the tags as releases. Some of the [new release actions promoted by the old official action](https://github.com/actions/create-release) have options for automatically generating release notes.

**Comment by kloczek** [comment]
If you are publishing over pypi actions https://pgjones.dev/blog/trusted-plublishing-2023/ contains hint how to add gh release to such process.

**Comment by kloczek** [comment]
Updated list of useful links:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by sloria** [comment]
Did you script out these github issues? 😅 

![CleanShot 2024-02-28 at 10 22 23@2x](https://github.com/marshmallow-code/marshmallow/assets/2379650/bbb82252-e014-4a62-9885-5dbdbb1d2261)

I don't really have a strong opinion on this, but I lean towards simplicity in our release pipeline. After all, GH releases are redundant with PyPI releases and git tags.

For users who want to automatically get notified about new releases, I'd recommend using an automated dependency upgrade service like renovate or dependabot.

Closing for now
