### ISSUE TITLE
Exception when serializing SQLAlchemy query results.

### ISSUE THREAD

**Issue by romabysen** [marshmallow-code/marshmallow#217]
I'm trying to serialize the result of an SQLAlchemy query (that is, not a model) but it only works if I don't use func.Method or func.Function. When I try to use either of those in my schema I get this exception when dump'ing:

TypeError: tuple indices must be integers, not unicode

**Comment by sloria** [comment]
This is the same issue reported in https://github.com/marshmallow-code/marshmallow/issues/207. This has been fixed in the latest `develop`/`2.0.0b3`. You can either install the latest development version or set a custom accessor to correctly account for collections.

**Comment by romabysen** [comment]
Oh nice, that does fix it. Any plans on releasing 2.0.0b3 soon?
