### ISSUE TITLE
Feature request: immutable schemas and context passing

### ISSUE THREAD

**Issue by matejsp** [marshmallow-code/marshmallow#2173]
When using context passing into schema you have to always create new instance making schema not immutable.
```
sch = SomeSchema(context=http_request)
data = {"ac1": {"a": 1}, "ac2": {"a": 1}}
sch.load(data)
```

I would prefer a bit different syntax to pass context inside load.
```
sch = SomeSchema()
data = {"ac1": {"a": 1}, "ac2": {"a": 1}}
sch.load(data, context=http_request1)
sch.load(data, context=http_request2)
```

This would make Schema definition immutable, thread safe and faster since you don't have to initialise fields for each and every request.

**Comment by lafrech** [comment]
Related to #1826.

**Comment by matejsp** [comment]
This looks like possible solution. I will follow the discussion in related issue.
