### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Nagaraj4896** [marshmallow-code/marshmallow#2183]
I am getting `RecursionError: maximum recursion depth exceeded while calling a Python object` error for following code, Is there any other way to selecting the schema based on a value

```py
import marshmallow
from marshmallow import fields, post_load

class FoodSchema(marshmallow.Schema):
    food_type = fields.String()

    @post_load
    def make_food(self, data, **kwargs):
        food_type = data.get('food_type', '').lower()
        if food_type == 'fruit':
            return FruitSchema().load(data)
        elif food_type == 'vegetable':
            return VegetableSchema().load(data)
        elif food_type == 'meat':
            return MeatSchema().load(data)
        else:
            raise ValueError("Invalid food type")

class FruitSchema(FoodSchema):
    # Add fields specific to the Fruit class here

class VegetableSchema(FoodSchema):
    # Add fields specific to the Vegetable class here

class MeatSchema(FoodSchema):
    # Add fields specific to the Meat class here

print(FoodSchema().load({'food_type':'fruit'}))
```

**Comment by lafrech** [comment]
You may want to have a look at marshmallow-oneofschema, although I'm not sure it works at schema top-level. It might be limited to polymorphic fields.

**Comment by lafrech** [comment]
Obviously, the `post_load` method is inherited and therefore executed when the child classes load, therefore the loop.

You could overwrite it in child classes to avoid that. It might even work if you double underscore it, I didn't try.

But this doesn't sound like a great approach anyway. I'd try to use marshmallow-oneofschema for this.
