### ISSUE TITLE
sdist is missing `tox.ini`

### ISSUE THREAD

**Issue by mtelka** [marshmallow-code/marshmallow#2186]
The sdist package at PyPI is missing `tox.ini`.  Please add the missing file to sdist to make downstream testing easier.  Thank you.

**Comment by deckar01** [comment]
I'm not sure what the goal of this issue is. To run the unit tests from the installed package?

**Comment by mtelka** [comment]
I'm [packaging marshmallow for OpenIndiana](https://github.com/OpenIndiana/oi-userland/tree/oi/hipster/components/python/marshmallow) and missing `tox.ini` is causing that we need to use github tarball instead of sdist to create the package and to run tests for it.  We run tests for packages to make sure they works properly once installed.

The need to use github tarball causes two (minor) issues for us:
- the tarball url cannot be automatically obtained from PyPI, so we need to [configure it manually](https://github.com/OpenIndiana/oi-userland/blob/7461b90b2c8c13862df4741d8df812a4f01124d6/components/python/marshmallow/python-integrate-project.conf#L17),
- github tarballs are [not reliable](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/) and this causes problems for reproducible builds.

Thank you.

**Comment by lafrech** [comment]
I have no packaging experience. I believe Debian does the packaging work in a "fork":

https://salsa.debian.org/debian/python-marshmallow

I guess they don't work on a tarball but on the source repo itself.

**Comment by sloria** [comment]
This is fixed by this line: https://github.com/marshmallow-code/marshmallow/pull/2226/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R57 , so tox.ini will be included in the sdist for the next release
