### ISSUE TITLE
Serializing a wrapped object and preserve additional fields

### ISSUE THREAD

**Issue by justanr** [marshmallow-code/marshmallow#219]
Not a very good title. Anyways, I have a use case to serialize a Flask-SQLA pagination object. I'm sure this is common and we all see the question a mile away.

I'd like to serialize the pagination object, preserving the metadata, and get at the list of objects inside. 

The obvious answer is to build a PaginationSchema and use a polymorphic field that'll map my models to the proper schemas. But adding a new schema and model becomes cumbersome (maybe that speaks more to my architecture than the problem).

Maybe taking advantage of the pre_dump decorator would lead to a more elegant solution, but the issue of mapping objects to schemas remains in that case. 

However, I'd like to pick someone's brains about it.

**Comment by sloria** [comment]
I recommend taking a look at [marshmallow-pagination](https://github.com/jmcarp/marshmallow-pagination). It's in its early days, but it's worth evaluating its approach.

**Comment by justanr** [comment]
I'd completely forgot about this. Thanks for pointing that out. I'll check it out and see what's up with it.

**Comment by aguilera51284** [comment]
That has happened with this?
