### ISSUE TITLE
The data_key argument for one or more fields collides with another field's name or data_key argument.

### ISSUE THREAD

**Issue by jmontanag** [marshmallow-code/marshmallow#2200]
I would like to know more about this error. Is it not possible to have same data_key for different fields ?

**Comment by lafrech** [comment]
- https://marshmallow.readthedocs.io/en/stable/upgrading.html#attribute-or-data-key-collision-triggers-an-exception
- https://github.com/marshmallow-code/marshmallow/pull/1008

**Comment by jmontanag** [comment]
Thank you for your response, add `load_only=True` works for me.
