### ISSUE TITLE
Question/docs suggestion: Context for deserialization

### ISSUE THREAD

**Issue by martinstein** [marshmallow-code/marshmallow#224]
The docs currently mention the `context` attribute, but only for serializing values:
http://marshmallow.readthedocs.org/en/latest/custom_fields.html#adding-context-to-method-and-function-fields

Let's say I want to deserialize some data and have a validation method that additionally depends on the currently logged in user-object. Is this the proper way to pass the user into the schema?

``` python
schema.context = {'user': user}
data, errors = schema.load(input_data)
```

If yes, perhaps it would be nice to have another, tiny section in the docs that mentions that `context` can also be used for deserialization (currently it looks like `context` is for serialization only).

**Comment by sloria** [comment]
Yes, that is the correct usage. I am open to adding more documentation to clarify that `context` can be used in deserialization. PRs welcome!

**Comment by martinstein** [comment]
Okay, thanks for the fast reply. By the way, I really like the implicit field (`class Meta: fields = (...)`) and nesting functionality. Those two features in combination are great for serializing SqlAlchemy-models.

**Comment by sloria** [comment]
Good to hear. Since you're using SQLAlchemy, I recommend using [marshmallow-sqlalchemy](https://github.com/marshmallow-code/marshmallow-sqlalchemy); it will more reliably and efficiently generate Schemas based on models.

**Comment by sloria** [comment]
Added a brief section that explains that `context` is available to Schema and Field methods. Closing this for now.
