### ISSUE TITLE
Question/docs suggestion: Schema inheritance

### ISSUE THREAD

**Issue by martinstein** [marshmallow-code/marshmallow#225]
Originally coming from colander, I was used to the feature 'schema inheritance':
http://docs.pylonsproject.org/projects/colander/en/latest/basics.html#inheriting-schemas

I've tried and it seems that marshmallow supports this as well:

``` python
class EmployeeSchema(Schema):
    name = fields.String()
    email = fields.Email()

class DriverSchema(EmployeeSchema):
    car = fields.String()

class ManagerSchema(EmployeeSchema):
    title = fields.String()

manager_input = {
    "name": "Mike",
    "email": "bad_email",
    "title": "CIO"
}
data, errors = ManagerSchema().load(manager_input)
print("data:", data)
# data: {'title': 'CIO', 'name': 'Mike'}

print("errors:", errors)
# errors: {'email': ['"bad_email" is not a valid email address.']}
```

So, is this the correct/intended usage of marshmallow? If yes, another small section in the docs about this would probably be helpful, because schema inheritance as a feature is really nice. If you agree, feel free to reuse the code-sample above for the docs (I've written it with that in mind).

**Comment by sloria** [comment]
That is the correct usage. I guess I haven't considered documenting schema inheritance since it's not as much a feature of marshmallow as it is a feature of the language. That said, I am open to adding documentation if it clarifies usage.

**Comment by martinstein** [comment]
Okay, cool. I can't promise anything, but in case I get around to writing some documentation: Which section would you prefer for this: Quickstart or Extending Schemas?

**Comment by sloria** [comment]
Hm, I don't have strong feelings about it, but I think Extending Schemas makes sense.

**Comment by martinstein** [comment]
I was just going to write a small section for the docs, but `invoke` doesn't seem to be ready for Windows yet:

```
invoke.exceptions.PlatformError: You seem to be on Windows, which doesn't support ptys!
```

So at the moment it's kind of hard for me to contribute. Maybe someone else wants to claim this?

**Comment by sloria** [comment]
FWIW, I've removed the `pty` arguments from the docs task, so it should now work on Windows. You can also run the `sphinx-build` command manually:

```
sphinx-build docs docs/_build
# Then open docs/_build/index.html in your web browser
```

**Comment by juanrossi** [comment]
Hey guys, I added a small PR (#288) with docs regarding schema inheritance. If you think it's not enough or it should be explained better let me know.

**Comment by sloria** [comment]
I'm still undecided on this; it seems gratuitous to document a core feature of the language.

**Comment by juanrossi** [comment]
I kind of agree, but I think it's helpful for the unexperienced developer or just to let people know that it's a possible think to do and done intentionally (which is what started the issue).

**Comment by sloria** [comment]
There is already an example of inheritance in the Extending page: https://marshmallow.readthedocs.org/en/latest/extending.html#custom-class-meta-options . We could provide another example by revising the enveloping example:

``` python

class BaseSchema(Schema):
    # Custom options
    __envelope__ = {
        'single': None,
        'many': None
    }
    __model__ = User

    def get_envelope_key(self, many):
        """Helper to get the envelope key."""
        key =  self.__envelope__['many'] if many else self.__envelope__['single']
        assert key is not None, "Envelope key undefined"
        return key

    @pre_load(pass_many=True)
    def unwrap_envelope(self, data, many):
        key = self.get_envelope_key(many)
        return data[key]

    @post_dump(pass_many=True)
    def wrap_with_envelope(self, data, many):
        key = self.get_envelope_key(many)
        return {key: data}

    @post_load
    def make_object(self, data):
        return self.__model__(**data)


class UserSchema(BaseSchema):
    __envelope__ = {
        'single': 'user',
        'many': 'users',
    }
    __model__ = User
    name = fields.Str()
    email = fields.Email()
```

**Comment by juanrossi** [comment]
Ok, I will implement that code, do you consider necessary to have a comment regarding schema inheritance?

**Comment by sloria** [comment]
I don't think any text about inheritance is necessary with the above example.

**Comment by juanrossi** [comment]
Updated docs, let me know if they are ok.

**Comment by sloria** [comment]
Looks good. Thanks!

**Comment by egberts** [comment]
falcon_marshmallow seems to successfully extended the schema at API levrel, just from reading the doc.
