### ISSUE TITLE
when a new request, schema context not reset !!!

### ISSUE THREAD

**Issue by LionSniper** [marshmallow-code/marshmallow#2253]
class TestStrSchema(ma.Schema):

    test_str = fields.String()

    @pre_load
    def test_str_schema_pre_load(self, data, *args, **kwargs):
        a2 = self.context
        test_str = data['test_str']
        self.context['_test_str'] = test_str
        a3 = self.context
        return data
        
 in a flask project, when i first request, test_str is 'abc'，and set test_str 'abc' to context, when i second request test_str is 'abcd', but a2 will get {'_test_str': 'abc'} , not is {}, why? thanks!

**Comment by sloria** [comment]
you'll need to make sure a new `Schema` instance is created for each request to ensure that `context` is clear.

**Comment by sloria** [comment]
Closing for now
