### ISSUE TITLE
Questions about Copilot + Open Source Software Hierarchy

### ISSUE THREAD

**Issue by liaochris** [marshmallow-code/marshmallow#2254]
Hi! My name is Chris and I'm writing a thesis on Open Source Software. I'm trying to collect/validate my data and I have two questions for the maintainers of this project.
1) Did maintainers of this project receive free github copilot access on June 2022? If you don't recall, it might be helpful to check if maintainers are currently elgiible ([https://github.com/github-copilot/free_signup](https://github.com/github-copilot/free_signup))
2) My thesis is especially focused on understanding hierarchical structures. Is there a publicly available list of of individuals in this project with triage/write/maintain/admin access in this project?

Happy to chat further if you have questions, and thank you for your time!

**Comment by deckar01** [comment]
This appears to be a bot which has duped issues after they were closed.

https://github.com/python-pillow/Pillow/issues/7902

**Comment by liaochris** [comment]
Hi! Not a bot, just trying to validate the data that I have for my thesis.

**Comment by sloria** [comment]
1. not that I know of
2. the current maintainers are myself, @lafrech, and @deckar01 . you can see a list of contributors here: https://github.com/marshmallow-code/marshmallow/blob/dev/AUTHORS.rst
