### ISSUE TITLE
validation fails when combining load_from and required=True

### ISSUE THREAD

**Issue by thomasbhatia** [marshmallow-code/marshmallow#226]
Not sure if by design but combining load_from and required=True results in validation failing.

```
class UserSchema(Schema):
    name = fields.String()
    email = fields.Email(load_from='emailAddress', required=True)

data = {
    'name': 'Mike',
    'emailAddress': 'foo@bar.com'
}
s = UserSchema()
result, errors = s.load(data)
```

{'email': [u'Missing data for required field.']}

**Comment by sloria** [comment]
Good catch. That is certainly a bug. PR's welcome!

**Comment by thomasbhatia** [comment]
Sorry, was using marshmallow 1.2.6 from pypi which does not have load_from. Using v2.0.0b3 without problems.

**Comment by Kobnar** [comment]
Using marshmallow 2.12.2 and I'm definitely running into this bug. Maybe I'm doing something wrong?

```python
class CreateSource(Schema):
    source_type = fields.String(load_from='type', default='SOURCE', required=True)
    title = fields.String(required=True)
    # ...
```

Relevant test case:
```python
    # ...
    def test_source_type_default_is_source(self):
        data = {'title': 'Test Source'}
        schema = CreateSource()
        result, errors = schema.load(data)
        test_result = result.get('source_type')
        self.assertEqual('SOURCE', test_result)
```

* Test fails with `AssertionError: 'SOURCE' != None`
* `print(errors)` outputs `{'type': ['Missing data for required field.']}`.

Fearing a namespace conflict with `type` (which is why I'm using `load_from` to begin with) I tried renaming the `load_from` field, but the problem persisted.

**Comment by maximkulkin** [comment]
This is a common error when defining default values with Marshmallow. `default` is for default value when dumping, for loading you have to use `missing`:
```python
class CreateSource(Schema):
    source_type = fields.String(load_from='type', required=True, missing='SOURCE')
    # ...
```

**Comment by Kobnar** [comment]
Ah...

Sorry to waste your time.
