### ISSUE TITLE
RFE: use `zoneinfo` instead of `pytz`

### ISSUE THREAD

**Issue by kloczek** [marshmallow-code/marshmallow#2273]
Switch to standard `zoneinfo` module.
Below may help  https://github.com/pydantic/pydantic-core/commit/fd262933

```console
[tkloczko@pers-jacek marshmallow-3.21.2]$ grep -r pytz
.pre-commit-config.yaml:    additional_dependencies: [types-simplejson, types-pytz, packaging]
tests/base.py:import pytz
tests/base.py:central = pytz.timezone("America/Chicago")
pyproject.toml:tests = ["pytest", "pytz", "simplejson"]
```

**Comment by sloria** [comment]
fwiw pytz is only used for tests. i don't feel strongly about migrating to zoneinfo instead (esp since we're still supporting python 3.8) but i'd gladly review and merge a PR.

**Comment by kloczek** [comment]
In that patch is implemented fallback to 3.8 support.
BTW 3.8 will be EOLed Oct this year.

**Comment by sloria** [comment]
i saw that. it meant: i'm slightly less keen on migrating until we drop 3.8 support. but the workaround to support 3.8 isn't too bad, so i'd still merge a PR before then

**Comment by lafrech** [comment]
This was achieved in #2318.

**Comment by kloczek** [comment]
Thank you 👍
