### ISSUE TITLE
OSS Fuzz Integration

### ISSUE THREAD

**Issue by ennamarie19** [marshmallow-code/marshmallow#2304]
My name is McKenna Dallmeyer and I would like to submit marshmallow to OSS-Fuzz.

If you are not familiar with the project, OSS-Fuzz is Google's platform for continuous fuzzing of Open Source Software.

In order to get the most out of this program, it would be greatly beneficial to be able to merge-in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

Thank you!

**Comment by sloria** [comment]
Thanks for the offer. Iirc, we evaluated adding fuzz tooling in the past but ultimately decided that it was more maintenance overhead than it's worth. Given marshmallow's rather limited scope and high test coverage, I think that's still true today. Going to close this for now
