### ISSUE TITLE
Support sqlalchemy 2+

### ISSUE THREAD

**Issue by reuvenstr** [marshmallow-code/marshmallow#2308]
Hi, I got a warning during the upgrade of sqlalchemy

```
marshmallow/utils.py:293: RemovedIn20Warning: Retrieving row members using strings or other non-integers is deprecated; use row._mapping for a dictionary interface to the row (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    return obj[key]
```

To reproduce it's enough to query some columns from a model, and try to serialize it. The main difference is that before 1.4 sqlalchemy it was a tuple, and currently it's named tuple(Row)
Can you confirm that it's related to marshmallow, or do I need to pass a different object to the dump method?

**Comment by deckar01** [comment]
I am unable to reproduce this with `marshmallow 3.20.1` and `sqlalchemy 2.0.23`.

<details><summary>minimal (non-)repro for reference</summary>

```py
from sqlalchemy import Integer, create_engine, Column, String, text
from sqlalchemy.orm import sessionmaker, declarative_base
from marshmallow import Schema, fields


engine = create_engine('sqlite:///:memory:')
Base = declarative_base()

class Person(Base):
    __tablename__ = 'people'
    id = Column(Integer, primary_key=True)
    name = Column(String)

class PersonSchema(Schema):
    id = fields.String(dump_only=True)
    name = fields.String()

Base.metadata.create_all(engine)
Session = sessionmaker(engine)
session = Session()

schema = PersonSchema()
person = Person(name="Alice")
session.add(person)
session.commit()

row = session.execute(text('select name from people')).first()
data = schema.dump(row)
print(data)
# {'name': 'Alice'}
```

</details>

It sounds like `sqlalchemy.engine.Row` exposed `__getitem__` in some version, deprecated it, and it has been removed already. Marshmallow is expected to probe objects to determine the type and sqlalchemy seems to have made some odd typing choices they have since corrected.

**Comment by reuvenstr** [comment]
Looks like you are right, the problem is in my implementation. I just wanted to let you know that I didn't get any warning..

**Comment by lafrech** [comment]
@reuvenstr you may be interested in https://github.com/marshmallow-code/marshmallow-sqlalchemy.

**Comment by reuvenstr** [comment]
@deckar01 
Hi again, it looks like the problem only occurs in pytest, if -Werror flag is used

<details><summary>minimal repro for reference</summary>

```python
from sqlalchemy import Integer, create_engine, Column, String, text
from sqlalchemy.orm import sessionmaker, declarative_base
from marshmallow import Schema, fields


engine = create_engine('sqlite:///:memory:')
Base = declarative_base()

class Person(Base):
    __tablename__ = 'people'
    id = Column(Integer, primary_key=True)
    name = Column(String)

class PersonSchema(Schema):
    id = fields.String(dump_only=True)
    name = fields.String()

Base.metadata.create_all(engine)

def test_error():
    Session = sessionmaker(engine)
    session = Session()

    schema = PersonSchema()
    person = Person(name="Alice")
    session.add(person)
    session.commit()

    row = session.query(Person.name).all()
    data = schema.dump(row, many=True)
    print(data)
```
</details>

then run `pytest file.py`

`E           sqlalchemy.exc.RemovedIn20Warning: Retrieving row members using strings or other non-integers is deprecated; use row._mapping for a dictionary interface to the row (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)`

I have used `marshmallow==3.20.2` and `SQLAlchemy==1.4.50`, I can confirm that from version 2.0 there is no such warning from SQLAlchemy
Should it be mitigated from marshmallow side, or mine?

**Comment by deckar01** [comment]
It’s an sqlalchemy bug. AFAIK the only way around it is to upgrade sqlalchemy or ignore the warning.

https://docs.python.org/3/library/warnings.html#the-warnings-filter
