### ISSUE TITLE
One variable name causes parsing failure

### ISSUE THREAD

**Issue by DanielArmyrConversy** [marshmallow-code/marshmallow#2316]
Here is the file in question:

```py
from marshmallow import Schema, RAISE, fields

class SegmentVoiceprintWithSpeakerSchema(Schema):
    class Meta:
        unknown = RAISE

    file_speaker: fields.Str(required=True)
    file_speaker_2 = fields.Str(required=True)

input = {

    "file_speaker": "dev",
    "file_speaker_2": "dev",
}

parsed = SegmentVoiceprintWithSpeakerSchema().load(input)
print(parsed)
```

This should run fine, but I get the following error:
marshmallow.exceptions.ValidationError: {'file_speaker': ['Unknown field.']}

If I remove the file_speaker lines and then rename the fine_speaker_2 lines to file_speaker, things work. But not any other combination. I have checked the code and cannot find anything strange with the encoding or any wierd whitespaces or similar. I can also reproduce the issue on Mac M2 and Linux X64 with completely separately generated environments.

I run this on Python 3.10.13  and Marshmallow 3.22.0

**Comment by DanielArmyrConversy** [comment]
As a double-check, I have verified that I can reproduce the issue by copy-pasting the above code snippet into my editor.

**Comment by lafrech** [comment]
Looks like a typo.

```py
    file_speaker: fields.Str(required=True)   # typo: semicolon instead of equal sign
    file_speaker_2 = fields.Str(required=True)
```

**Comment by DanielArmyrConversy** [comment]
ROTFL. And to think that two senior devs stared at it together for 10 minutes.....
