### ISSUE TITLE
Schema Nesting: how to load everything but avoid dumping everything

### ISSUE THREAD

**Issue by Neah-Ko** [marshmallow-code/marshmallow#2317]
Hello,

I have the two following two way nested Schemas.

```python
class UserSchema(Schema):
    username = String()
    password = String(load_only=True)
    email = String()
   
    groups = List(Nested('GroupSchema', exclude=['users', 'children', 'parent']))

class GroupSchema(Schema):
    path = String()
    users = List(Nested('UserSchema', exclude=['groups']))
    children = List(Nested('GroupSchema', exclude=['users', 'children', 'parent']))
    parent = Nested('GroupSchema', exclude=['users', 'children', 'parent'])
```

I would like to be able to allow unrestricted `loading`, such that passing in nested dicts is fine, but take into account the `exclude` on `dumping` only. 

reason for this is that I'm using (async) `sqlalchemy` behind that and when directly serializing those objects, it triggers more DB queries to fetch the fields. moreover in such cases of two way nesting and self-referential nesting I end up with `RecusionError`.

Is there a way to do this from a single Schema class to keep this neat ? Being able to pass a `dump_only` list of fields to `Nested` would do it for instance.
I havn't tried yet the lambda way as described here: https://marshmallow.readthedocs.io/en/latest/nesting.html#two-way-nesting
However, I'm expecting to bump into import issues for my case above. Where each schema class lies in its separate file.

Overall, I would like to limit serialization depth to 1. Meaning one top level object and its relationships with their fields but not their own relationships. Is there a way to configure that ?

Best,

**Edit:**
I've tried the following, where `group.py` and `user.py` each contain their respective schema in the same directory.
In some cases I'm preferring a function over a lambda in order to delay the import and avoid circular import errors.

```python
# group.py
class GroupSchema(Schema):
    path = String()
    def dump_user():
        from user import UserSchema
        return UserSchema(exclude=['groups'])

    users = List(Nested(dump_user))
    children = Nested(lambda: GroupSchema(dump_only=['path']))
    parent = Nested(lambda: GroupSchema(dump_only=['path']))

# user.py
class UserSchema(Schema):
    username = String()
    password = String(load_only=True)
    email = String()

    def dump_group():
        from group import GroupSchema
        return GroupSchema(dump_only=['path'])
    groups = List(Nested(dump_group))
```

Then from the console, the following test case fails:

```
>>> from user import UserSchema
>>> user_with_groups = {
...     "username": "u_test_wg",
...     "password": "1234",
...     "groups": [
...         {"path": "g_test_wg1"},
...         {"path": "g_test_wg2"},
...     ]
... }
>>> UserSchema().validate(user_with_groups, partial=True)
{'groups': {0: {'path': ['Unknown field.']}, 1: {'path': ['Unknown field.']}}}
```

**Comment by deckar01** [comment]
Have you tried marshmallow-sqlalchemy?

https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#smart-nested-field

**Comment by Neah-Ko** [comment]
I'm sorry, I've been too prompt to open an issue about it. The solution from my edit works. I got mixed up about the `dump_only/load_only` arguments when applied on a `Schema`.

They have to be interpreted as a list of fields onto which this flag will be enabled. Not as a parameter applied on the Schema.
In my example, the following Schema works as I intend for groups:

```python
class GroupSchema(Schema):
    path = String()
    def dump_user():
        from user import UserSchema
        return UserSchema(load_only=['groups'])
    users = List(Nested(dump_user))
    children = Nested(lambda: GroupSchema(load_only=['users', 'children', 'parent']))
    parent = Nested(lambda: GroupSchema(load_only=['users', 'children', 'parent']))
```

@deckar01 Thanks for the suggestion. Yes I've considered this package, but ultimately decided not to use in. Mainly because it doesn't seem to support well async sqla and that I preferred keeping a finer grained control over schema configuration and database operations.
