### ISSUE TITLE
Implicit collection handling Warning when serializing DynamoDb Item

### ISSUE THREAD

**Issue by equake** [marshmallow-code/marshmallow#236]
Hi!
I'm using Marshmallow to serialize some DynamoDb objects using Boto2. 
Marshmallow seems to think that <boto.dynamodb2.items.Item object> is a list, but it's not...

I'm getting this error in the console:
/env/local/lib/python2.7/site-packages/marshmallow/schema.py:451: DeprecationWarning: Implicit collection handling is deprecated. Set many=True to serialize a collection. category=DeprecationWarning)

Thanks.

**Comment by sloria** [comment]
That is expected; we duck-type the object to be serialized to see if it is a collection. If the object appears to be a collection and many=False, the warning appears. You can safely ignore the warning in your case.

Perhaps we will remove this warning in 2.0, though it protects against a sneaky gotcha that can be hard to debug.
