### ISSUE TITLE
A limit to the amount of data for nested fields

### ISSUE THREAD

**Issue by jonaprieto** [marshmallow-code/marshmallow#238]
This is more like a question, because I didn't find out in the documentation. 
I have something like that:

``` python
class PSchema(Schema):
   ... 
    ...
    qs = fields.Nested(QSchema, many=True)
```

All works fine. But the issue is that `qs` field contains a large amount of the `QSchema`. So, are there the possibility to limit the amount to show or render of a nested schema?, something like take the first ones or send function like a filter?

``` python
class PSchema(Schema):
   ... 
    ...
    qs = fields.Nested(QSchema, many=True, limit=5)
```

I'm working to deal with this requirement, Thanks in advance.

**Comment by sloria** [comment]
There is no built-in way to do limiting or filtering of nested objects. I don't think it is the responsibility of marshmallow to do this; any filtering should be done before (de)serialization.

**Comment by IceBearZero** [comment]
@sloria digging this up, as Im having a similar issue. I agree that it may not be the responsibility of marshmallow, but I don't quite understand how to filter the nested objects before hand?

For example, if you have `stores` and each has several (lets say hundreds) `items` as a nested relationship. When you call the Serializer on `stores` (even filtering down to a few stores, you stil get all the items. Maybe there is some limit function in sqlalchemy/other that Im overlooking on associations?

@jonaprieto did you ever resolve this? What was your strategy?

Any thoughts appreciated --

**Comment by IceBearZero** [comment]
I think I get it now, Marshmallow isnt doing the DB queries, those are handled by the ORM, and hence, with some sort of lazy load, the records are there, so when passed into Marshmallow it treats those as the nested. 

Ill need to work through how to limit the returned nested relations from SQLAlchemy -- I think that was what you were saying 

Thanks
