### ISSUE TITLE
AttributeError when using extra alongside a collection

### ISSUE THREAD

**Issue by joealcorn** [marshmallow-code/marshmallow#24]
Say I pass in a list of objects as well as `many=True` as the `obj`, if I also pass in `extra` it treats it as it would a dict, calling `update`.

https://github.com/sloria/marshmallow/blob/b0f8da7ce8987cbf389b306ac35e992abade812a/marshmallow/serializer.py#L187-L188

**Comment by sloria** [comment]
Fixed. Thanks for reporting
