### ISSUE TITLE
Improve documentation for make_object data validation

### ISSUE THREAD

**Issue by kissgyorgy** [marshmallow-code/marshmallow#243]
I took me a long time to realize if I want to use strictly valid data in `make_object`, I need to use `strict=True` option.

Something like this:

``` python
class LoginRequestSchema(Schema):
    login_name = fields.Str(required=True)
    password = fields.Str(required=True)

    def make_object(self, data):
        return UserLogin(data['login_name'], data['password'])

    class Meta:
        strict = True
```

because if I don't use strict, I got `KeyError` instead of the desired `errors` dict filled with messages on `.load()` call.
This should be emphasized in the documentation.
Or do I need to check for data validity in `make_object`? Also should I use something else instead make_object?

**Comment by sloria** [comment]
Yes, I agree that the current behavior isn't intuitive. Ideally, `make_object` would not need to check for data validity--that should happen in the validators.

Some possible solutions:
1. Don't call `make_object` unless the data are valid.
2. Pass the `errors` dict to `make_object`.

Feedback welcome.

**Comment by kissgyorgy** [comment]
How do I not call `make_object` if it is defined? AFAIK it is automatically called on `Schema().dump()`. Does it have a second parameter errors? It's even more confusing for me then.

**Comment by sloria** [comment]
Sorry for the confusion--the above were _proposals_ for a solution; they are not yet implemented.

**Comment by sloria** [comment]
I've decided to go with #1 (only call make_object if data are valid) in order to minimize breaking API changes. This is now documented in the API reference.

Closing this for now.

**Comment by kissgyorgy** [comment]
This is great, thank you!
