### ISSUE TITLE
How do I add only to dump?

### ISSUE THREAD

**Issue by LeoJavaAI** [marshmallow-code/marshmallow#246]
I have gone to the docs and saw that I can use the only attribute only when declaring the UserSchema(), but I have a requirement where I only want to dump a certain fields for one call and all fields for the other call, So how do I go about doing this? Do I need to declare another instance of the UserSchema?

**Comment by sloria** [comment]
Yes, just instantiate a new `UserSchema`. In general, `Schema` constructor is used for configuring behavior at application runtime.
