### ISSUE TITLE
DateTime ignores date formatting string

### ISSUE THREAD

**Issue by bartaelterman** [marshmallow-code/marshmallow#248]
The documentation for the `marshmallow.fields.DateTime` says:

```
Parameters: 
    * format (str) – Either "rfc" (for RFC822), "iso" (for ISO8601), or a date format string. If None, defaults to “iso”.
```

But the part `or a date format string` is not true. I would've expected this to accept date formatting strings as defined in the [`time` module](https://docs.python.org/2/library/time.html#time.strftime), however, if the `format` parameter is a date formatting string, it is ignored and the parsing is done using `dateutil` (I noticed this [here in the source code](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L771).

It looks like the documentation is not consistent with the code here. I think it would be very valuable if you could indeed provide a date formatting string and that marshmallow will use it with (`time.strptime`](https://docs.python.org/2/library/time.html#time.strptime) to parse it instead of letting `dateutil` do a guess about the format.

I am willing to edit this in the source code, but I would like to discuss the desired behaviour first.

Cheers

**Comment by sloria** [comment]
I agree; if a string other than `'rfc'` or '`iso'` is passed as the `format` argument, it should be assumed to be a date format, even if `dateutil` is installed.

I would welcome a PR for this.
