### ISSUE TITLE
requesting standard support of Dict fields type

### ISSUE THREAD

**Issue by Dowwie** [marshmallow-code/marshmallow#251]
Please accept this request to adopt native support of a dictionary field type

**Comment by sloria** [comment]
What would a `Dict` field support that isn't already supported by a `Nested` field?

**Comment by Dowwie** [comment]
Nested is sufficient for dicts whose schema is known in advance of use, but what about cases where the elements to serialize aren't known in advance?

**Comment by imhoffd** [comment]
Sounds like `Dict` would just be `Raw` with a type check.

**Comment by mcandre** [comment]
+1

**Comment by sloria** [comment]
I would be open to a PR adding this. So would the interface be similar to DRF, where you can pass an inner field for validating values?

``` python
foo = fields.Dict(fields.Int())
```

**Comment by imhoffd** [comment]
But, as @Dowwie said, there are cases where the schema of the elements inside the dict aren't known in advance. I could take a look at creating a PR.

**Comment by sloria** [comment]
The Dict field has been added on `dev`.
