### ISSUE TITLE
How to specify a field that is a JSON object (dict/hashmap)?

### ISSUE THREAD

**Issue by mcandre** [marshmallow-code/marshmallow#258]
How should I specify that one of the fields in my Schema is a JSON object / dict / hashmap? I can't find a fields.Dict(), etc. in the current documentation.

**Comment by mcandre** [comment]
https://github.com/marshmallow-code/marshmallow/issues/120#issuecomment-125379887 would implement a proper fields.Dict.

For now, I'm working around this missing type by using `fields.Raw()`.

**Comment by CaravelKit** [comment]
Still no support of JSON?
