### ISSUE TITLE
handle complex object from joins

### ISSUE THREAD

**Issue by ferask** [marshmallow-code/marshmallow#26]
Based on your example
https://github.com/sloria/marshmallow/blob/dev/examples/flask_example.py

What if we get Authors from the db along with all quotes related!
something like this query:
authorQuotes = session.query(Author, Quote).join(Quote.author ).filter(Author.id == 1).all()

How would we serialize this object?

**Comment by sloria** [comment]
As of 0.6.0, you can nest serializers by passing the string name of the serializer class. Therefore, to have "two-way" nesting of Authors and Quotes, you could do this:

``` python

class AuthorSerializer(Serializer):
    # nested quote representation
    quotes = fields.Nested('QuoteSerializer', exclude=('author', ), many=True)
    formatted_name = fields.Method("format_name")

    def format_name(self, author):
        return "%s, %s" % (author.last, author.first)

    class Meta:
        fields = ('id', 'first', 'last', "formatted_name")

class QuoteSerializer(Serializer):
    author = fields.Nested(AuthorSerializer)

    class Meta:
        fields = ("id", "content", "posted_at", 'author')
```

Does that answer your question?
