### ISSUE TITLE
deserialize() throws exception even if strict=False

### ISSUE THREAD

**Issue by density** [marshmallow-code/marshmallow#261]
See https://github.com/marshmallow-code/marshmallow/blob/2.0.0b4/marshmallow/marshalling.py#L254

Instead of adding the validation error to self.errors, `Unmarshaller` throws an exception directly at this line. This can happen, for example, if the data you're trying to deserialize is a list instead of a dictionary. I think this should be treated like any other validation error and not actually throw the exception here.

**Comment by sloria** [comment]
Thanks for reporting @density . I will fix this shortly.

**Comment by sloria** [comment]
Fixed. The current behavior is now:

``` python
from marshmallow import Schema, fields, ValidationError

class MySchema(Schema):
    foo = fields.Field()

MySchema().load([]).errors
# {'_schema': ['Data must be a dict, got a list']}
```
