### ISSUE TITLE
Clarification: Providing a custom dict class to Schema

### ISSUE THREAD

**Issue by justanr** [marshmallow-code/marshmallow#268]
Just wanting to see if I'm understanding this correctly: If I need to provide a custom mapping class to put the serialized data into, I should override the `dict_class` property on Schema. 

A simple example: Using Marshmallow to serialize response for display in a View.

``` python
class DottedDict(dict):
    "Preserve dotted access to pretend we're accessing the original object"
    __getattr__ = dict.__getitem__


# use this class as the base for all my schema
class ViewModelSchema(Schema):
    dict_class = DottedDict

# when dump is called, result.data will be a DottedDict
class UserSchema(ViewModelSchema):
    class Meta:
        fields = ['username', 'email', 'registered_at']
```

Is this considered a "public API" or am I backdooring. I understand that setting `ordered` wouldn't affect anything now -- but that's not a concern if I'm simply serializing data down to use in a template instead of shoving it off into a JSON API.

I'd hope that I could provide the `dict_class` keyword directly to dump, but since it already provides the argument to the Marshaller, a TypeError multiple values for dict_class pops out.

If this is a public API, would a PR for documentation on this be accepted?

**Comment by sloria** [comment]
Why not use a `post_dump` method?

``` python
class ViewModelSchema(Schema):

    @post_dump
    def dotdictify(self, data):
        return DottedDict(data)
```

**Comment by justanr** [comment]
Hm. I hadn't considered post dump actually. And that'd be inherited by all the children classes as well, correct?

The only issue I'd see is that the pre/post decorators are applied none deterministically if there's more than one. But I don't see that biting me.  

I guess the question of "Is dict_class supposed to be a public API" is a moot point now.  Still curious though.

**Comment by sloria** [comment]
Yes, decorated `post_dump` methods will get inherited as expected.

`dict_class` is not meant to be public API. That said, you can count on it being stable for the foreseeable future. It seems like `post_dump` meets your use case, though.

**Comment by justanr** [comment]
I'll play with both and see which works the best. I could run into an issue needing multiple post_dump operations. But I'll cross that bridge later. Thanks.
