### ISSUE TITLE
Django REST framework compat

### ISSUE THREAD

**Issue by lovelydinosaur** [marshmallow-code/marshmallow#271]
I'm considering a package to allow users to use marshmallow as alternative serializers for Django REST framework. There's barely any work needed there - wrapping marshmallow's schema in the `BaseSerializer` class (or simply replicating its interface) to provide the compat layer.

I wanted to open the issue here first to check if you folks would prefer something like that directly in your package, or if I should instead tackle this independently.

Cheers!

  Tom

**Comment by sloria** [comment]
This would be excellent.

marshmallow's philosophy is to remain agnostic towards other frameworks and libraries; compat layers are built outside of marshmallow core.

I'd be happy to help in any way with this. Thanks for reaching out.

**Comment by lovelydinosaur** [comment]
Gotcha thanks! I'll try to remember to ping back when there's something to show.

**Comment by lovelydinosaur** [comment]
Done... http://tomchristie.github.io/django-rest-marshmallow/

:smile:
