### ISSUE TITLE
Serialized SQLAlchemy Query resulting in empty dictionaries or an error 

### ISSUE THREAD

**Issue by xYDanTheManYx** [marshmallow-code/marshmallow#28]
Using sqlalchemy, flask & marshmallow.
I have an issue when Serializing an sqlalchemy query.
I seem to get empty dictionaries when I serialize the query result.
If I try to specify column names to serialize then it errors.
Using a query such as:

modules = db.session.query(Hosts.hostname, Modules.name, HostMatrix.enabled).filter(Hosts.hostname == host).all()

To recreate:

import sqlalchemy
from marshmallow import Serializer

modules = [sqlalchemy.util._collections.KeyedTuple((u'HostA', u'Backup', 1)), sqlalchemy.util._collections.KeyedTuple((u'HostA', u'Backup', 0)), sqlalchemy.util._collections.KeyedTuple((u'HostA', u'Backup', 0)), sqlalchemy.util._collections.KeyedTuple((u'HostA', u'Backup', 1))]

Serializer(modules, many=True).data

[OrderedDict(), OrderedDict(), OrderedDict(), OrderedDict()]

Serializer(modules, only=('name', 'enabled'), many=True).data

Traceback (most recent call last):
File "", line 1, in 
Serializer(modules, only=('name', 'enabled'), many=True).data
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marshmallow/serializer.py", line 193, in init
self._update_fields(obj)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marshmallow/serializer.py", line 294, in _update_fields
ret = self.__filter_fields(self.only)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marshmallow/serializer.py", line 359, in __filter_fields
attribute_type = type(obj_dict[key])
TypeError: tuple indices must be integers, not str

I also created a class to specify the fields to include but that results in the same error.

**Comment by xYDanTheManYx** [comment]
Using sqlalchemy, flask & marshmallow.
I also seem to have an issue when a sqlalchemy query result is as below:

Query: Hosts.query.orderby(Hosts.hostname).all()

> > > hosts
> > > [<**main**.Hosts object at 0x102b710d0>, <**main**.Hosts object at 0x102b6ea10>]
> > > 
> > > Serializer(hosts, many=True).data
> > > [collections.OrderedDict({}), collections.OrderedDict({})]
> > > 
> > > Serializer(hosts, only=('hostname'), many=True).data
> > > [collections.OrderedDict({'h': None, 'o': None, 's': None, 't': None, 'n': None, 'a': None, 'm': None, 'e': None  }), collections.OrderedDict({'h': None, 'o': None, 's': None, 't': None, 'n': None, 'a': None, 'm': None, 'e': None  })]

**Comment by sloria** [comment]
Can you post the code for your `Serializer` class?

**Comment by xYDanTheManYx** [comment]
from marshmallow import Serializer

I am not using any other classes, from the docs it appears to be optional.

**Comment by sloria** [comment]
It is absolutely necessary to subclass `Serializer`; it is how you define the output fields for the serializer. Can you point to the section of the documentation that was misleading?

Here is a working example using your above data:

``` python
import sqlalchemy
from marshmallow import Serializer, fields, pprint

labels = ['host', 'name', 'enabled']
modules = [sqlalchemy.util._collections.KeyedTuple((u'HostA', u'Backup', 1), labels=labels), 
           sqlalchemy.util._collections.KeyedTuple((u'HostA', u'Backup', 0), labels=labels), 
           sqlalchemy.util._collections.KeyedTuple((u'HostA', u'Backup', 0), labels=labels), 
           sqlalchemy.util._collections.KeyedTuple((u'HostA', u'Backup', 1), labels=labels)
           ]


class MySerializer(Serializer):
    name = fields.String()
    kind = fields.String()
    enabled = fields.Boolean()

serialized = MySerializer(modules, many=True, only=('name', 'enabled'))
serialized.data
# {"name": "HostA", "enabled": true}
# {"name": "HostA", "enabled": false}
# {"name": "HostA", "enabled": false}
# {"name": "HostA", "enabled": true}
```

**Comment by xYDanTheManYx** [comment]
I have tried it like you have specified and it worked.
After rereading the docs it appears I have completely overlooked having to subclass Serializer.

Previously I had tried subclassing like this:

class MySerializer(Serializer):
    class Meta:
        fields = ('id', 'name', 'enabled')

But received an error when using the class:
TypeError: tuple indices must be integers, not str

As I now have it working I will keep it to how  you have specified.

Thanks very much for your assistance!

**Comment by sloria** [comment]
Glad I could help.

Your issue actually brings up an issue that I had not found before: using the `fields` option in `class Meta` does not work for keyed tuples such as sqlalchemy's `KeyedTuple` and `collections.namedtuple`. Thanks for finding this! I will issue a fix soon.

**Comment by makmanalp** [comment]
Hey @sloria - I just ran into this again, with the fields & KeyedTuple. I think the issue is that it uses dir(). Here's a debugger session from that error, in marshmallow/utils.py:to_marshallable_type():

``` python
>>> obj
sqlalchemy.util._collections.KeyedTuple((3278477.5500000003, 29700, 0.04472251026943858, 0.8179699425486985, 0.4208957237122138, 0.8067728413148435, 2479, 3,  ... ))

>>> dir(obj)
Traceback (most recent call last):
File "<debugger>", line 1, in <module>
dir(obj)
TypeError: unorderable types: NoneType() < str()

>>> obj.__dict__.keys()
dict_keys(['year', 'product_id', 'import_value', None, 'department_id', 'cog', 'coi', 'export_rca', 'export_value', 'id', '_labels'])

```

Sort of ...

I'm using class Meta: fields=[], and still seems to break.

**Comment by makmanalp** [comment]
And oddly specifying only=() doesn't seem to fix it for me as it did for you guys.

**Comment by sloria** [comment]
Thanks for reporting @makmanalp. I will look into this soon.

**Comment by makmanalp** [comment]
@sloria no, thank /you/!

**Comment by makmanalp** [comment]
:tada: :balloon: :+1: !!
