### ISSUE TITLE
Set name of an attribute to a value that is not a valid Python string

### ISSUE THREAD

**Issue by jomag** [marshmallow-code/marshmallow#281]
Hi. I use marshmallow to serialize/deserialize JSON and need to set the name of an attribute to include characters that are not allowed in Python (typically "#"). Example:

```
{ "#foo": 123, "100bar": 234 }
```

While I can override the attribute of a field, I have not found any way to change the name of a field in the output. I've tried using setattr, but that did not work for some reason:

```
class X(ma.Schema):
    #foo = ma.fields.Integer()   <---- this does obviously not work
    ...

setattr(X, "#foo", ma.fields.Integer())  <----- not sure why this doesn't work?
```

Is there any way to do this?

**Comment by sloria** [comment]
You can use the `include` option for fields that aren't valid Python variable names.

``` python
import marshmallow as ma

class X(ma.Schema):
    class Meta:
        include = {
            '#foo': ma.fields.Int()
        }

X().dump({'#foo': '42'}).data  # {'#foo': 42}
```

**Comment by jomag** [comment]
Thanks! The syntax could be a bit cleaner, but it solves my problem.
