### ISSUE TITLE
Documentation Example doesn't work

### ISSUE THREAD

**Issue by marcstreeter** [marshmallow-code/marshmallow#283]
The examples on this documentation example don't work: http://marshmallow.readthedocs.org/en/latest/examples.html#quotes-api-flask-sqlalchemy.  

Changing the import statement from 
   `from marshmallow import Schema, fields, ValidationError, decorators`
to
    `from marshmallow import Schema, fields, ValidationError`
   `from marshmallow.decorators import pre_load`

got it to run but the 'valid' inputs provided give the following

```
$ http POST :5000/quotes/ author="Tim Peters" content="Beautiful is better than ugly."
HTTP/1.0 422 UNPROCESSABLE ENTITY
Content-Length: 62
Content-Type: application/json
Date: Mon, 21 Sep 2015 22:28:35 GMT
Server: Werkzeug/0.9.4 Python/2.7.10

{
    "author": [
        "Data must be a dict, got a unicode"
    ]
}
```

**Comment by marcstreeter** [comment]
here are my deets

```
>>> import sys
>>> sys.version
'2.7.10 (default, Jul 13 2015, 15:46:49) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.57.2)]'
```

**Comment by marcstreeter** [comment]
and 

```
Flask==0.10.1
Flask-SQLAlchemy==1.0
marshmallow==1.2.6
```

**Comment by sloria** [comment]
The examples are compatible with the marshmallow 2. I confirmed that the example works with marshmallow 2.0.0rc2.

**Comment by marcstreeter** [comment]
I'm going crazy.  I must have had an old version already installed when I thought I'd only successfully 'installed' it that day.
