### ISSUE TITLE
Make error handler and accessor methods

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#284]
In 2.0.0rc2, `error_handler` and `accessor` are `class Meta` options. I propose making them instance methods instead.
### Why?
- `error_handler` and `accessor` already behave like instance methods; they take the `Schema` instance as their first argument
- Defining a user-defined base `Schema` class is a common pattern with marshmallow. Inheritance of instance methods is more straightforward than `class Meta` options.
### Proposed API

``` python
from marshmallow import Schema, missing

class CustomError(Exception):
    pass

class MySchema(Schema):

    def handle_errors(self, error, obj):
        raise CustomError(error.messages)

    def get_value(self, attr, data):
        return data.get(attr, missing)
```

**Comment by sloria** [comment]
Another proposed change: `handle_errors` will receive the `ValidationError` instance rather than the dictionary of errors. This will allow for other information to be stored on the error. 

Example use case:

``` python
class CustomValidationError(ValidationError):
    def __init__(self, messages, code, **kwargs):
        self.code = code
        ValidationError.__init__(self, messages, **kwargs)

def validate_password(val):
    if len(val) <= 8:
        raise CustomValidationError('Must be > 8 characters', code=422)

from webframework import HTTPError

class MySchema(Schema):

    def handle_errors(self, error, obj):
        raise HTTPError(error.messages, code=error.code)
```

**Comment by philtay** [comment]
+1

**Comment by sloria** [comment]
Done. 

Supporting the use case above, with custom `ValidationErrors` that take additional arguments won't work quite yet; it's tricky to get it right with marshmallow's error bundling (which will reraise ValidationError)--we'll save this for a future release.

**Comment by MrLokans** [comment]
What is possible to do is to set all of the meta-data you need into ValidationError kwargs field, basically somewhat like this:
```
class HTTPValidationError(ValidationError):
    def __init__(self, message, code=400, **kwargs):
        ValidationError.__init__(self, message, **kwargs)
        self.kwargs['code'] = code

```
