### ISSUE TITLE
fields.Constant is confusing

### ISSUE THREAD

**Issue by fayazkhan** [marshmallow-code/marshmallow#291]
`fields.Contsant` only works for fields which are already present in the object.

``` python
from marshmallow import fields, Schema, pprint

class Test(Schema):
    field = fields.Constant(0)
    field2 = fields.Constant(1)

pprint(Test().load({'field': 1}))
```

I'd expect this code to give me:

```
UnmarshalResult(data={'field': 0, 'field2': 1}, errors={})
```

But this is what I get:

```
UnmarshalResult(data={'field': 0}, errors={})
```

If this is the expected behavior, it isn't really clear from the docs.
So either the docs or the behavior ought to be changed.

**Comment by sloria** [comment]
This is indeed a bug. Fixed in https://github.com/marshmallow-code/marshmallow/commit/a69622cbfffa342daa5a737cd85c700bb925ca93. Thanks @fayazkhan for reporting.
