### ISSUE TITLE
Avoid validation on dumping

### ISSUE THREAD

**Issue by jjvattamattom** [marshmallow-code/marshmallow#292]
I am using marshmallow for a web API. I appreciate the validation at load-time, but I wish there is an option to avoid validation at dump-time, since there are database accesses. I have to make my own deserialization methods or create separate schema for dumping alone.

Is there a way to reuse the same classes to do loading with validation and dumping without validation?

**Comment by sloria** [comment]
`Email` and `URL` are the only fields that perform validation upon serialization. Validators passed to the `validate` argument are also run on deserialization only.

Can you please clarify what validation is being run on serialization?

**Comment by jjvattamattom** [comment]
My bad. I tried to dump an object against a schema with an email. I noticed a validation error against email, so I assumed/extrapolated that all validators, including `validate`, `@validates` and `@validates_schema` are run during serialization. 

I can certainly afford a few regex checks! But why are only these very specific validations performed at serialization? I expected no validation to happen at all. I even checked if a `@validates` is triggered against email at serialization, which is a no.

The only information of serialization-time validation is:

> Schema.dump() also returns a dictionary of errors, which will include any ValidationErrors raised during serialization

Perhaps it should include:

> The only validations that occur at serialization-time are checks for Email and URL fields. All other validation occurs at deserialization time only.

I appreciate marshmallow even more highly now and will integrate it for serialization needs too!

**Comment by sloria** [comment]
You make a fair point re: documentation of `Email` and `URL` fields. I am considering deprecating validation-on-serialization for those two fields to make them consistent with the rest of the API.

If you don't want validation on serialization for emails and URLs, you can always do:

``` python
from marshmallow import fields, validate

email = fields.Str(validate=validate.Email())
```

**Comment by jjvattamattom** [comment]
I look forward to both!

**Comment by kiptoomm** [comment]
@sloria, I know this is an old topic, but what is the justification for performing validation only during deserialization? I would think that we want to verify correct fields before dumping them into the database (with a POST, for example)...

**Comment by lafrech** [comment]
> I would think that we want to verify correct fields before dumping them into the database (with a POST, for example)...

I guess what people do is validate API input using marshmallow, then consider that their model objects are valid, then write in database using their database driver. In this case, marshmallow is used for deserialization, so it does validation.

There can be cases where marshmallow is also used to serialize the data to feed the database, but in this case, validation may be considered unneeded because the model objects are supposed to be valid.
