### ISSUE TITLE
How to handle heterogenous collections?

### ISSUE THREAD

**Issue by mark-anders** [marshmallow-code/marshmallow#294]
I'm trying to deserialize collections where each object could be any one of a number of different types.  In my schema, each dictionary has a "type" field that denotes the type of object that has been serialized.  Is this something that can be defined with Marshmallow schema? 

 What I've done so far is to have the collections specified as fields.List(fields.Dict()), after which I can run through, select the correct schema and validate/deserialize.  

Just wondering if there's a better way.

**Comment by sloria** [comment]
See https://github.com/marshmallow-code/marshmallow/issues/195, which includes a number of solutions.

**Comment by mark-anders** [comment]
Thanks for the pointer, and sorry I missed these - I actually did look!

One question - your proposed solution looks like what I want.  However, the meat of it is done in the output method, which seems to no longer be used.  Would you recommend doing this in the _serialize/_deserialize methods?

**Comment by mark-anders** [comment]
@sloria - Actually, I went with Polyfield and got it working.  I'm not sure why you decided to not support this scenario in Marshmallow core, but it's complicated enough that I think it would be a great thing to support out of the box, or at least have an official sample that's maintained with the current architecture.
