### ISSUE TITLE
dump doesn't validate @validates_schema

### ISSUE THREAD

**Issue by bpicolo** [marshmallow-code/marshmallow#295]
It's pretty surprising that there's no way to marshal + validates_schema at the same time, here's a setup:

```
class Scheme(Schema):
    num = fields.Integer(default=1)
    num2 = fields.Integer(default=2)
    @validates_schema
    def _valid(self, data):
        if not 'num' in data and not 'num2' in data:
            raise ValidationError('Either num or num2 must be supplied')

Invalid Data:
>>> data = {}
>>> schema = Scheme()
>>> schema.dump(data)
MarshalResult(data={'num2': 2, 'num': 1}, errors={})
>>> schema.validate(data)
{'_schema': ['Either num or num2 must be supplied']}
>>> schema.load(data)
UnmarshalResult(data={}, errors={'_schema': ['Either num or num2 must be supplied']})


Valid Data:
>>> data = {'num': 1}
>>> schema.dump(data)
MarshalResult(data={'num2': 2, 'num': 1}, errors={})
>>> schema.validate(data)
{}
>>> schema.load(data)
UnmarshalResult(data={'num': 1}, errors={})



What I expect (that doesn't currently happen):
>>> schema.dump({})
MarshalResult(data={}, errors={'_schema': ['Either num or num2 must be supplied']})
>>> schema.dump({'num': 1})
MarshalResult(data={'num2': 2, 'num': 1}, errors={})
```

None of these methods validate both fields + validates_schema and also apply default values (through marshalling).

I guess the baseline issue is I want to properly validate something that's dependent on > 1 field.

This sort of gets at the whole defaults-not-applied-for-serialize thing probably...

**Comment by sloria** [comment]
This is by design. Primarily for performance reasons, validation only happens on deserialization (`load` and `validate`). The data passed to `dump` is assumed to be valid. See #45 and #47 for a rather dated but relevant discussion on this.

**Comment by sloria** [comment]
Added a note in the docs to clarify that `@validates_schema` (as well as `required`, `allow_none`, `@validates`...) only apply during deserialization.
