### ISSUE TITLE
Recipe needed for a serializable object containing a dict of sets containing serializable objects

### ISSUE THREAD

**Issue by Dowwie** [marshmallow-code/marshmallow#296]
Does a recipe exist to solve the following problem I'm having--  serialize an object that contains a dict of sets of serializable objects?

I've created a real world example to illustrate what I'm trying to achieve and why.  In this example, people are indexed based on the city of where they live.  Each city has a number of zip codes.  I query for people based on city.

here's my gist:  https://gist.github.com/Dowwie/24de24ab751c4cbdd618#file-gistfile1-txt

I do not know how to define the Schema(s) for the PeopleIndex class. I realize that sets aren't supported and that I'd have to convert/revert to lists-- that's not a problem.  The major challenges I'm dealing with relate to that the cities and people aren't known until run-time.  
## In pseudo code, I'm trying to do this:

``` python
class PeopleIndex(Schema):
    people_index = Dict(Nested(PeopleSchema, many=True))
```

**Comment by sloria** [comment]
A rather quick hack that might meet your use case:

``` python
class CollectionDict(fields.Dict):

    def __init__(self, child, *args, **kwargs):
        self.child = child
        super().__init__(*args, **kwargs)

    @staticmethod
    def accessor(key, obj, default=missing):
        """Custom accessor that only handles list and tuples.
        """
        try:
            return obj[key]
        except IndexError:
            return default

    def _serialize(self, value, attr, obj):
        ret = super()._serialize(value, attr, obj)
        for key, collection in ret.items():
            lvalue = list(collection)
            ret[key] = [
                self.child.serialize(i, lvalue, accessor=self.accessor)
                for i in range(len(lvalue))
            ]
        return ret

    def _deserialize(self, value, attr, data):
        ret = super()._deserialize(value, attr, data)
        for key, collection in value.items():
            ret[key] = set([
                self.child.deserialize(each, i, collection)
                for i, each in enumerate(collection)
            ])
        return ret
```

Full example: https://gist.github.com/sloria/1d1c679afc5b4e5d65b2 . 

One limitation of this approach is that validation errors won't be indexed.

**Comment by Dowwie** [comment]
This is great!  Thank you very much for the thoughtful, quick response.

**Comment by Dowwie** [comment]
FYI-- Until there's a better repo, I've created a public repo to illustrate these sorts of recipes:  https://github.com/Dowwie/marshmallow_recipes

I didn't want this kind of value-added stuff to reside in a gist

**Comment by Dowwie** [comment]
Steve-- why is it that this line works when it shouldn't?  Instead, I should be referencing the schema class rather than an instance, correct?
https://github.com/Dowwie/marshmallow_recipes/blob/master/people_zipcodes.py#L118

**Comment by sloria** [comment]
@Dowwie `fields.Nested` can be passed either a Schema instance or a Schema class.

**Comment by Dowwie** [comment]
Hey Steve

I found a bug in this recipe during unit testing.  The CollectionDict mutates the instance of the object that is serialized.  Using the example we built on, I illustrate the changes with a few additional debugging lines.

If I make a local copy of "value", such as follows, it seems to clear up the issue.  Would you confirm that this is a correct approach?

``` python

    def _serialize(self, value, attr, obj):
        ret = super()._serialize(copy.copy(val), attr, obj)
        for key, collection in ret.items():
            lvalue = list(collection)
            ret[key] = [
                self.child.serialize(i, lvalue, accessor=self.accessor)
                for i in range(len(lvalue))
            ]
        return ret
```

https://gist.github.com/Dowwie/177ed0a4f37fa833c156

**Comment by sloria** [comment]
@Dowwie Yes, that looks correct.
