### ISSUE TITLE
validates_schema(pass_many=True) does not pass many

### ISSUE THREAD

**Issue by d-sutherland** [marshmallow-code/marshmallow#297]
See: https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/schema.py#L800

Decorator `validates_schema(pass_many=True)` does not actually pass the whole collection to the decorated method but still passes them one at time. The reason is at the linked line above (whenever `many==True` objects are passed one by one). Replacing that line with `if many and not pass_many` appears to fix the problem. Also notice the test for this functionality, [here](https://github.com/marshmallow-code/marshmallow/blob/dev/tests/test_decorators.py#L313), still passes because the dictionary passed has 2 items so `len(data) == 2` (even though it is only one data entry, not a collection).

**Comment by sloria** [comment]
Thanks for reporting, @d-sutherland. This indeed appears to be a bug. 

I would welcome a PR addressing this. Otherwise, I'll investigate this later today.
