### ISSUE TITLE
Opposite functionality of 'load_from' needed. Perhaps 'dump_to'?

### ISSUE THREAD

**Issue by ShayanArmanPercolate** [marshmallow-code/marshmallow#310]
Currently, there is an attribute on the Field class called load_from. This is useful when a schema pythonic style fields, but the service could accept CamelCase field names.

ex.
class JobSchema(Schema):
    pipeline_id = fields.Str(load_from='PipelineId', load_only=True, required=True)

This is a great solution for deserialization. However, when serializing, it would be great to change the key from pipeline_id back to PipelineId. My current solution is to have a dump_only field that uses the attribute parameter to take the value of pipeline_id:

class JobSchema(Schema):
    pipeline_id = fields.Str(load_from='PipelineId', load_only=True, required=True)
    PipelineId = fields.Str(dump_only=True, attribute='pipeline_id')

Is there a better way to do this? 

Thanks a lot!
Shayan
@sloria

**Comment by franciscod** [comment]
Your current solution seems okay; althought maybe adding a `dump_to` attribute might be useful...

**Comment by ShayanArmanPercolate** [comment]
I definitely think it would! If there is a load_from attribute, logically a dump_to attribute would clean up the code a lot. Right now I have to double up on every field I write. One for loading and one for dumping. One of the main positives of using marshmallow is using the same schema for both loading and dumping.
@sloria what do you think?

**Comment by franciscod** [comment]
Started progress here, needs tests and probably more documentation: https://github.com/franciscod/marshmallow/tree/dump_to

**Comment by franciscod** [comment]
``` python
from marshmallow import Schema, fields

class Person(Schema):
    name = fields.String(load_from="LegacyNameField", dump_to="LegacyNameField")
    age = fields.Integer(dump_to="HowOld")

```

``` python
>>> Person().load({'name': 'Francisco', 'age': 123})
UnmarshalResult(data={'age': 123, 'name': 'Francisco'}, errors={})

>>> Person().load({'name': 'Francisco', 'HowOld': 123})
UnmarshalResult(data={'name': 'Francisco'}, errors={})

>>> Person().load({'LegacyNameField': 'Francisco', 'HowOld': 123})
UnmarshalResult(data={'name': 'Francisco'}, errors={})

>>> Person().dump({'name': 'Francisco', 'age': 123})
MarshalResult(data={'HowOld': 123, 'LegacyNameField': 'Francisco'}, errors={})

```

(disclaimer: not sure if using the load() and dump() methods in _The Right Way™_)

**Comment by ShayanArmanPercolate** [comment]
Yes! This is exactly what I was talking about. Thanks :+1: 
@sloria

**Comment by sloria** [comment]
This seems like a good idea. I would gladly review a PR implementing this.

**Comment by franciscod** [comment]
I'm not sure about where to add the tests: `test_marshalling.py` or `test_deserialization.py`? (and why?)

**Comment by franciscod** [comment]
there you go!

**Comment by franciscod** [comment]
What about `attribute`? Would using a combination of `attribute` and `load_from` be equivalent to using `dump_to` and `load_from` or I'm missing something?

If that was the case, `dump_to` maybe is somewhat redundant...

**Comment by ShayanArmanPercolate** [comment]
Its not. dump_to is extremely useful for dumping to a new key value, basically moving from pythonic style on the schema to a non pythonic style using the dump_to attribute. However, using the 'attribute' parameter, you have to make double copies of every field.

class JobSchema(Schema):
    pipeline_id = fields.Str(load_from='PipelineId', load_only=True, required=True)
    PipelineId = fields.Str(dump_only=True, attribute='pipeline_id')

with dump_to->

class JobSchema(Schema):
    pipeline_id = fields.Str(load_from='PipelineId', dump_to='PipelineId', required=True)

In this simple case its not that big of a deal, but having an API with multiple fields can get very confusing, and therefore hard to maintain.

Also, attribute takes the value of a field and assigns it to a different field. It is different from what dump_to does, which is basically renaming a field upon dump.
@sloria @franciscod

**Comment by franciscod** [comment]
Following your examples:

``` python
from marshmallow import Schema, fields

schemas = []
class JobSchemaActualSolution(Schema):
    pipeline_id = fields.Str(load_from='PipelineId',
                             load_only=True, required=True)
    PipelineId = fields.Str(attribute='pipeline_id',
                            dump_only=True)

schemas.append(JobSchemaActualSolution)


class JobSchemaLoadFromDumpTo(Schema):
    pipeline_id = fields.Str(load_from='PipelineId',
                             dump_to='PipelineId',
                             required=True)

schemas.append(JobSchemaLoadFromDumpTo)


class JobSchemaLoadFromAttribute(Schema):
    pipeline_id = fields.Str(load_from='PipelineId',
                             attribute='PipelineId',
                             required=True)

schemas.append(JobSchemaLoadFromAttribute)


class JobSchemaAttribute(Schema):
    pipeline_id = fields.Str(attribute='PipelineId',
                             required=True)

schemas.append(JobSchemaAttribute)


data = {'PipelineId': 'abc123'}

for schema in schemas:
    print()
    print(schema.__name__)

    s = schema()
    l = s.load(data)
    print(l)
    res, errors = l

    d = s.dump(res)
    print(d)
    res, errors = d

    print(res)
    print(data)
    print('--')


```

```
JobSchemaActualSolution
UnmarshalResult(data={'pipeline_id': 'abc123'}, errors={})
MarshalResult(data={'PipelineId': 'abc123'}, errors={})
{'PipelineId': 'abc123'}
{'PipelineId': 'abc123'}
--

JobSchemaLoadFromDumpTo
UnmarshalResult(data={'pipeline_id': 'abc123'}, errors={})
MarshalResult(data={'PipelineId': 'abc123'}, errors={})
{'PipelineId': 'abc123'}
{'PipelineId': 'abc123'}
--

JobSchemaLoadFromAttribute
UnmarshalResult(data={'PipelineId': 'abc123'}, errors={})
MarshalResult(data={'pipeline_id': 'abc123'}, errors={})
{'pipeline_id': 'abc123'}
{'PipelineId': 'abc123'}
--

JobSchemaAttribute
UnmarshalResult(data={}, errors={'pipeline_id': ['Missing data for required field.']})
MarshalResult(data={}, errors={})
{}
{'PipelineId': 'abc123'}
--

```

I expected JobSchemaAttribute and JobSchemaLoadFromAttribute would work the same way than the first two... I definitely don't get how `attribute` works :)

**Comment by sloria** [comment]
`attribute` is the attribute (or key) that is used to populate a field upon serialization. It is accessed off of the _target object_ to serialize. `dump_to` is the key on the _serialized result_.

**Comment by franciscod** [comment]
got it :+1:
