### ISSUE TITLE
`prefix` not respected when `dump_to` is set

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#317]
Applies only to the latest `dev` version.

From https://github.com/marshmallow-code/marshmallow/pull/311#issuecomment-152202176:

> So here's an issue that I just noticed.
> https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/marshalling.py#L134
> 
> if field_obj.dump_to:
> key = field_obj.dump_to
> elif not self.prefix:
> key = attr_name
> else:
> key = ''".join([self.prefix, attr_name])
> 
> What if there's a case where field_obj.dump_to is set AND self.prefix is set. Then, do we want key = ''.join([self.prefix, field_obj.dump_to])?
> 
> so maybe:
> 
> key = "" if not self.prefix else self.prefix
> if field_obj.dump_to:
> key += field_obj.dump_to
> else:
> key += attr_name
> 
> What do you think?
> @sloria @franciscod

**Comment by ewang** [comment]
Added a PR for this.

**Comment by ShayanArmanPercolate** [comment]
@sloria @ewang thanks for taking care of this.
