### ISSUE TITLE
Dont run validates_schema if individual fields were invalid

### ISSUE THREAD

**Issue by jjvattamattom** [marshmallow-code/marshmallow#323]
I just discovered that validates_schema runs if individual fields have failed validation. I kinda expected otherwise.

I want a way to prevent validates_schema from being run if individual fields have failed validation. Please confirm if my way of comparing original and processed data is sufficient or that there is a simpler alternative.

```
@validates_schema(pass_original=True)
def validate_schema(self, data, original):
    # dont run below tests if validation on individual fields failed:
    if sorted(data.keys()) != sorted(original.keys()):
        return
    ...tests that presume individual fields are valid
```

**Comment by sloria** [comment]
Sorry for the delayed response. I'm not sure there is a clean way to achieve this at the moment. I don't think we should change the default behavior; there are use cases where you want schema validators to run even if field validators fail. That said, I am open to suggestions for supporting the OP's use case.

**Comment by DamianHeard** [comment]
Perhaps an alternative would be to properly expose the errors that have been captured during unmarshalling. At the moment you have to go through `self._unmarshal.errors`. Individual validate_schema methods would either check for errors before running of the decorator could be modified to automatically do this check if configured. Of course, I could be missing something and these errors might be already getting exposed at a more desirable location.

**Comment by d-sutherland** [comment]
Another simple alternative would be to provide this as an argument to the validation decorators, allowing full backwards compatibility. 
Yet another alternative is to call validates_schema methods when a field has already failed only if strict mode is off. As such when strict mode is on the errors are propagated immediately (or at least it appears so to the user), which follows the same pattern users would be familiar with for exceptions. This would also follow the principle of least astonishment - if an error is raised (as occurs when strict is True) then the user can expect that code further down the pipeline won't be reached.

**Comment by maximkulkin** [comment]
I just hit the same issue which got me surprised. IMO the most sane behavior is to:
- Deserialize fields and let field validations to run
- For each field run validations declared with `validates(field_name)` decorator only if that field does not have errors
- If there are no errors, run validations declared with `validates_schema` decorator.

**Comment by sloria** [comment]
The `skip_on_field_errors` parameter has been added to `validates_schema` in 2.4.0.
