### ISSUE TITLE
fields.Function deserialization should support contexts

### ISSUE THREAD

**Issue by DamianHeard** [marshmallow-code/marshmallow#324]
This is a relatively minor change to `fields.Function` which would allow de deserialization access to the marshmallow context. I think this is relatively non-controversial but if that's not the case I'm happy to provide and more solid case for this change.

If this change passes the sniff test them I'm happy to provide a PR.

**Comment by sloria** [comment]
Yes, this would be a good change. I'd appreciate the PR.

**Comment by sloria** [comment]
Closed by #327
