### ISSUE TITLE
Function and Method fields: set dump_only and load_only based on passed arguments?

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#328]
Proposal:

`Function(serialize=f)` -> automatically set `dump_only` to `True`
`Function(deserialize=f2)` -> automatically set `load_only` to `True`
`Function(serialize=f, deserialize=f2)` -> `dump_only` is `False`, `load_only` is `False`

**Comment by justanr** [comment]
I think this is a good rationale. If only one of the attributes is set, the intention is probably to only load or dump depending on which it is.

**Comment by deckar01** [comment]
@sloria It looks like #460 was merged, which moved the implementation of this proposal to `3.0`. Is there anything else you still needed to add?
