### ISSUE TITLE
Exclude certain fields based on a field?

### ISSUE THREAD

**Issue by jjvattamattom** [marshmallow-code/marshmallow#331]
I have the fields:

```
type
person1
person2
common1
common2
```

If the type is say, 0, all fields are required. If the type is 1, common1 and common2 is required, person1 and person2 wont be loaded/validated at all. Could I do this in a single schema?

**Comment by justanr** [comment]
You're best bet would be to use `validates_schema`, however if you're wanting to preemptively do it, some sort of schema factory might be a good idea.

**Comment by jjvattamattom** [comment]
@justanr could you explain the schema factory thing?

**Comment by justanr** [comment]
I think I may have misunderstood you, so let's try a different example. Let's say we have this schema:

``` python
class EmployeeSchema(Schema):
    name = String()
    pay = Integer()
    department = String()
    boss = Nested('self')
```

Then two classes: `Employee` and `Intern`. When you pass an `Employee` you want all the fields, but if you pass `Intern` you don't want to see `pay`. Maybe there's a `CEO` class and `boss` shouldn't be seen then. Is this right?

In this case, you can imagine we have some sort of function that'll map a type/class to the fields we want to exclude, or maybe list in `only`, the idea is the same either way, you could actually attach this _onto_ the schema as a classmethod or staticmethod.

``` python
class EmployeeSchema(Schema):
    # field definitions

    @classmethod
    def from_employee(cls, employee):
        excluded_fields = {
            Intern: ['pay']
            CEO: ['boss']}
        return cls(exclude=excluded_fields[type(employee)]).dump(employee)
```

It's not _ideal_ but it'd get the job done. If you're running 3.4 or can install the `singledispatch` package, you could look into that for more robust type handling.

Other than something like this, I can't think of a good way to dynamically do this other wise.

**Comment by sloria** [comment]
I think @justanr 's comment above is a fine solution.
