### ISSUE TITLE
Terminology -- clarification needed

### ISSUE THREAD

**Issue by Dowwie** [marshmallow-code/marshmallow#333]
Is it correct to say that marshmallow _marshals_ objects into dicts which can then be _encoded_ using msgpack, json, protobuf, etc?  Further, the marshalling and encoding are both part of the serialization process?

**Comment by sloria** [comment]
Sounds correct. The marshmallow docs use "marshal" and "serialize" interchange-ably, but I think your definitions above make sense.

serialization = marshalling + encoding
deserialization = unmarshallng + encoding

One could also argue that validation is part of the deserialization process.

**Comment by sloria** [comment]
Closing this for now unless. Feel free to reopen if any more clarification is needed.

**Comment by Dowwie** [comment]
thanks for confirming, Steve
