### ISSUE TITLE
can I read a csv with marshmallow??

### ISSUE THREAD

**Issue by dhararon** [marshmallow-code/marshmallow#335]
Hi, i was trying to read a csv file, but i can't find a solution, so, i wrote this little method. i don't know if works really good and i would like to help me to improve it.

**Code with example**

``` python
from marshmallow import Schema
from marshmallow.schema import UnmarshalResult

class NumerationNationalPlan(Schema):
    def csv(self, data, many=None, partial=None):
        from itertools import izip_longest
        many = self.many if self.many is not None else (False if many is None else True)

        if many == True:
            data = [dict(izip_longest(self.opts.fields, d)) for d in data]
        else:
            data = dict(izip_longest(self.opts.fields,data))

        result, errors = self._do_load(data, many, partial=partial, postprocess=True)
        return UnmarshalResult(data=result, errors=errors)

    class Meta:
        fields = ('poblacion','municipio','estado','inicio','fin',
            'tipo','modalidad','proveedor','fecha_asignacion','fecha_consolidacion',
            'fecha_migracion','nir')


csv = [["1","2","3","4","5","6","7","8","9","10","11","12",],
["1","2","3","4","5","6","7","8","9","10","11",]]

cake = NumerationNationalPlan(many=True)
cake = cake.csv(csv)

print "cake: {}".format(cake)
```

**Comment by justanr** [comment]
Are you trying to use Marshmallow to read the actual CSV? If that's the case, look into the `csv` module included in Python. Included there is a `DictReader` class as well that can take the whole CSV file and use either your provided headers or the headers included in the CSV file.

On the other hand, if you're trying to use Marshmallow to transform the CSV into a more palatable internal representation, that's totally possible. I'd just feed the result of whichever CSV reader you use into Marshmallow.

**Comment by dhararon** [comment]
@justanr ok, thank you i didn't know that csv has a class for readed as dictionary, those solve the problem that i have.  Thank you so much.
