### ISSUE TITLE
How to systematically convert a marshmallow schema to an html form on the client?

### ISSUE THREAD

**Issue by fuhrysteve** [marshmallow-code/marshmallow#336]
I want to use marshmallow to represent, serialize, and deserialize various "types" of a schema. My specific use case is building forms for users to configure integration between their account on my application with their account on various other remote applications, each of which have a small handful of their own proprietary configuration details.

Ideally, I'd like to have a number of declarative schemas whose basic definitions could be passed via an API method to the client, which would intelligently render the form based on the schema definition (rather than writing each form in `HTML` by hand, and having to keep it in sync with marshmallow).

I was thinking of making a `marshmallow-jsonform` (see [ulion/jsonform](https://github.com/ulion/jsonform)) extension to accomplish this, but want to get a little feedback before re-inventing the wheel if there is some other better way to do what I am trying to do.

Does anyone have any suggestions?

**Comment by sloria** [comment]
This is interesting!

I found https://github.com/podhmo/marshmallow-form, but haven't looked much into it. 

I like the idea of targeting a spec like jsonform. A tangentially-related project is [apispec](https://github.com/marshmallow-code/apispec). It generates a Swagger spec (which, if I recall correctly, is a subset of JSON Schema) from marshmallow Schemas. You might be able to draw ideas from that.

**Comment by fuhrysteve** [comment]
Thanks for taking a look at this.

Marshmallow form is interesting - I came across it as well. One limitation of marshmallow-form, though, is that it makes assumptions about the client: i.e. it assumes that the client understands HTML (what if the client is a mobile device and has its own form builders & validation?)

apispec is an interesting project as well, but if I understand it correctly, its scope seems to be somewhat limited: it describes API endpoints.

I suppose you _could_ describe what I'm trying to do as _n_ API endpoints (i.e. `/sometype/<string:specific_schema>/`) - but it still only solves half the problem: there doesn't seem to be a straightforward way to render forms on the client side.

**Comment by fuhrysteve** [comment]
Swagger seems interesting, but it really seems to be doing a lot; I'm hesitant to buy into it.

I wonder if `json-schema` is a more prudent choice for a "language / system agnostic schema describer." It seems to be more closely aligned with the zen of marshmallow.

http://json-schema.org/documentation.html

**Comment by sloria** [comment]
Yes, I think targeting JSON Schema could be useful. The reason I mentioned Swagger is because it has tooling--namely, Swagger UI--which generates forms, though it is specifically used for documenting HTTP APIs.
