### ISSUE TITLE
Why marshmallow use its own ordered set

### ISSUE THREAD

**Issue by xsuchy** [marshmallow-code/marshmallow#337]
I wonder why there is own copy of marshmallow/orderedset.py, when we can use
  https://pypi.python.org/pypi/ordered-set

Is some reason for that or I can prepare PR which use orderedset as 3rd party module?

**Comment by ewang** [comment]
I think it's for marsmallow to have no required external dependencies.

**Comment by xsuchy** [comment]
Well it already require and use external dateutil.

**Comment by ewang** [comment]
The python-dateutil is not strictly required unless you use certain functions. In others, it will fall back to using the built in datetime library.

**Comment by sloria** [comment]
@ewang is correct. OrderedSet is required, while python-dateutil is optional.
