### ISSUE TITLE
Allow Field's `validate` argument to be a list

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#34]
You may want to do:

``` python
some_strict_field = fields.String(validate=[func1, func2]
```

**Comment by Ketouem** [comment]
Quick question, should this enhancement be put in the `Raw(FieldABC)` class ?

**Comment by Ketouem** [comment]
Jumped on it => https://github.com/sloria/marshmallow/pull/36

**Comment by sloria** [comment]
Closed by #37
