### ISSUE TITLE
Improve the consistence of the `utils.get_value()`

### ISSUE THREAD

**Issue by stas** [marshmallow-code/marshmallow#341]
`utils.get_value()` is the entry-point for most of the fields accessor methods.

Its interface (aka. arguments order on a call) is different from a generic and common interface of a getter, be that for a `dict` or an `object`. This means that you can not overwrite this method with a simple assignment of `Field.get_attribute = dict.get` or `Field.get_attribute = getattr`. Instead you will need to create a new method that properly maps the arguments. This needs to be fixed... hopefully in 3.0.

This started here:
https://github.com/marshmallow-code/marshmallow/commit/7cba47481cbfb0f7e8b3fd36b303a419e236812a#commitcomment-14486377

Lets keep this task to remind us fixing it in the next major release.

**Comment by deckar01** [comment]
This would be nice to have. @sloria Is there anything blocking a PR for `3.0`?
