### ISSUE TITLE
Access index of Nested object in @validates decorator.

### ISSUE THREAD

**Issue by ShayanArmanPercolate** [marshmallow-code/marshmallow#342]
I have a field:
notifications = fields.Nested(
        NotificationsSchema,
        allow_none=True, load_from='Notifications', dump_to='Notifications', many=True)

and let's say the Schema is a simple:
class NotificationsSchema(Schema):
    progressing = fields.Str(
        allow_none=True, load_from='Progressing', dump_to='Progressing')
    @validates('progressing')
    def validate_progressing(self, value):
       raise ValidationError("Error found in {index}".format(self.index))

Is there a way currently to access the index of a nested schema? In the creation of the validationError dict, marshmallow currently has a notion of indexes. But is there a way of accessing the indexes in a many=True scenario?

**Comment by sloria** [comment]
The indexes are reported in the error output. A simple example:

```python
from marshmallow import Schema, fields


class Inner(Schema):
    foo = fields.Str(required=True)

class Outer(Schema):
    inners = fields.Nested(Inner, many=True)


in_data = {
    'inners': [{'foo': 'valid'}, {}]
}

schema = Outer()
print(schema.load(in_data).errors)
# {'inners': {1: {'foo': ['Missing data for required field.']}}}
```

Validators don't have access to indexes, however, so you'll likely have to postprocess the error output if you want to more complex things.

We don't plan on adding API to support indices in error messages, so I'm closing this for now. Feel free to reopen this if you have suggestions though.
