### ISSUE TITLE
Handle `required` (list/set) attribute of a Meta-class in Schema-inherited classes

### ISSUE THREAD

**Issue by frol** [marshmallow-code/marshmallow#344]
The rationale behind the subject is that when I use webargs in combnation with marshmallow-sqlalchemy, I can only change `dump_only`, `load_only` options of the fields. I workaround this now in an overloaded `__init__` method, but I think it would be great if it is supported out-of-the-box.

``` python
class MyParameters(ModelSchema):
    class Meta:
        model = MyModel
        dump_only = ('id', )
        required = ('name', )
```

Note, while I see that my usecase is mostly valid for marshmallow-sqlalchemy `ModelSchema`, I found that `dump_only` logic is handled here, in marshmallow base project.

**Comment by frol** [comment]
BTW, some switch for all-fields-required, or even make this the default behaviour (though this was discussed in #112 earlier) would be also helpful.

**Comment by sloria** [comment]
I would have to give this more thought. 

There is a proposal/PR on marshmallow-sqlalchemy for customizing marshmallow fields by passing kwargs to SQLA fields: https://github.com/marshmallow-code/marshmallow-sqlalchemy/pull/22 .

**Comment by lanzafame** [comment]
I am not sure that I entirely understand @frol's use case but my own sent me looking for a solution similar to what @frol describes.

My use case looks like the following:

``` python
class FooSchema(Schema):
    name = fields.Str(required=True)
    country = fields.Str(required=True)
    city = fields.Str(required=True)
    operator = fields.Str(required=True)
    campus = fields.Str(required=True)
    facility = fields.Str(required=True)
```

I would like to refactor the above to following:

``` python
class FooSchema(Schema):
    class Meta:
        required = ("name", "country", "city", "operator", "campus", "facility")
```

Just my 2 cents.

**Comment by dbrumley** [comment]
+1 for Lanzafame's use case and idea; this is what I was thinking as well. Feels like `Str` is duplication.

**Comment by sloria** [comment]
We don't plan on adding this in the near future, as it adds complexity to the API (> 1 way to do things), so closing this for now. Feel free to reopen an issue if you feel further discussion is necessary.

**Comment by frol** [comment]
@sloria it is not the >1 way to do things, it might be the only way to do things when it comes to Marshmallow-SQLAlchemy, where the schema is inferred. Currently, we implement this support ourselves in our own base Schema class patching the auto-generated fields in `__init__`...

**Comment by sloria** [comment]
@frol It's not clear that these class Meta options (`required`, `dump_only`...) belong in marshmallow core, since they are only relevant for libraries that auto-generate fields. This has been pointed out [here](https://github.com/marshmallow-code/marshmallow/issues/453#issuecomment-280951726). So for now we won't add `required` as a class Meta option and leave it up to consuming libraries to add it.

**Comment by luhn** [comment]
Gonna pitch in here with my usecase.  Let's say this is my schema:

```python
class AlbumSchema(Schema):
    title = fields.Str()
    release_date = fields.Date()
    artist = fields.Nested(ArtistSchema())
```

I want to add a create album endpoint and an update album endpoint to my app.  If I'm creating an album, all the fields are required.  If I'm updating an album, fields can be absent and the value will be left as-is.  So I'd like to do something like:

```python
new_album = AlbumSchema(required=['title', 'release_date', 'artist'])
```

Or perhaps:

```python
class NewAlbumSchema(AlbumSchema):
    class Meta:
        required = ['title', 'release_date', 'artist']
```

Would be nice.

Right now I don't see a way besides redefining all the fields for NewAlbumSchema or enforcing the required fields in my application code, neither of which seem ideal.

I'm brand new to Marshmallow, so perhaps I'm approaching this from the wrong angle?  Is there an alternative way to achieve this?

**Comment by luhn** [comment]
After learning some more, it looks like I've got it backwards.  I should be declaring fields as required and then using `partial` to allow them to be missing.
