### ISSUE TITLE
Incorrect implementation of List field deserialization

### ISSUE THREAD

**Issue by maximkulkin** [marshmallow-code/marshmallow#345]
Problem explanation:

``` python
from marshmallow import Schema, fields, validate, validates, validates_schema, ValidationError


class IntRangeSchema(Schema):
    first = fields.Integer(required=True)
    last = fields.Integer(required=True)


class PoolSchema(Schema):
    name = fields.String(required=True)
    ranges = fields.List(fields.Nested(IntRangeSchema))

    @validates('ranges')
    def validate_ranges(self, ranges):
        print 'validate_ranges %s' % repr(ranges)
```

When I load valid data, the validate_ranges() is called with a list of dictionaries (which is expected):

``` python
schema = PoolSchema(strict=True)
data = {
    'name': 'pool1',
    'ranges': [
        {'first': 1, 'last': 10},
        {'first': 11, 'last': 20},
    ],
}
print repr(schema.load(data).data)
# => validate_ranges [{'last': 10, 'first': 1}, {'last': 20, 'first': 11}]
# => {'ranges': [{'last': 10, 'first': 1}, {'last': 20, 'first': 11}], 'name': u'pool1'}
```

But when I load an invalid data, then the validates_ranges() receives only a non-valid dictionary, not a list:

``` python
data = {
    'name': 'pool2',
    'ranges': [
        {'first': 1, 'last': 10},
        {'last': 10},
    ],
}            
print repr(schema.load(data).data)
# => validate_ranges {'last': 10}
# => ... ValidationError
```

Moreover, if I add complete schema validation (via `validates_schema`), this is what passed to it:

```
{'ranges': {'last': 10}, 'name': u'pool2'}
```

I see multiple problems here:
1) naive deserialization in List field type
2) running validations for fields that have already failed by other means.

The second issue is addressed in https://github.com/marshmallow-code/marshmallow/issues/323, so I'll focus on the first one.

Let's take List field as example. Deserialization of list types is basically:

``` python
def _deserialize(self, value, attr, data):
    return [self.container.deserialize(each) for each in value]
```

By definition container is a field type which will report deserialization/validation errors by raise ValidationError exceptions. That means that you will get an error for the first invalid item in the list and the rest of items won't be validated at all. The proper way would be to accumulate all errors:

``` python
def _deserialize(self, value, attr, data):
    if not utils.is_collection(value):
        self.fail('invalid')
    result = []
    errors = {}
    for idx, each in enumerate(value):
        try:
            result.append(self.container.deserialize(each))
        except ValidationError as e:
            result.append(e.data)
            errors.update({str(idx): e.message})

    if errors:
        raise ValidationError(errors, data=result)

    return result
```

**Comment by touilleMan** [comment]
+1
I was about to submit the same issue

**Comment by immerrr** [comment]
+1 on this one

**Comment by chekunkov** [comment]
Hi @maximkulkin 

why do you use 

```
ranges = fields.List(fields.Nested(IntRangeSchema))
```

instead of the recommended (see [note](http://marshmallow.readthedocs.org/en/latest/nesting.html#nesting-schemas))

```
ranges = fields.Nested(IntRangeSchema, many=True)
```

?

See also #319 which discusses `fields.Nested(..., many=True)` validation drawbacks.

**Comment by maximkulkin** [comment]
1) (although I didn't know that you could do that) it is very non-intuitive. What is intuitive is having a field type for each of your container types which actually do the job correctly.
2) This works only for creating fields that are collections of other objects (which are described with another Schema class derivatives). If you want to create a list of simple, non-object types (e.g. IPAddress field which actually is just a customized string), you can not (or at least, should not) use fields.Nested.

**Comment by justanr** [comment]
The reason for the nested field accepting many is because it's nesting a full schema inside of another schema, not just a single field.

It's like saying `SomeSchema(many=True).dump(list_of_stuff)`

**Comment by justanr** [comment]
I will add I'm +1 on collecting all the errors in List though.

**Comment by maximkulkin** [comment]
@justanr Thank you for pointing that out

**Comment by sloria** [comment]
@maximkulkin Thank you for the detailed report.

I think collecting errors is the desired and expected behavior. I would gladly review and merge a PR for this.
