### ISSUE TITLE
add python-dateutil as a required package for marshmallow

### ISSUE THREAD

**Issue by Dowwie** [marshmallow-code/marshmallow#349]
Using marshmallow v2.3.0:

You mention this in documentation:
The python-dateutil package is not a hard dependency, but it is recommended for robust datetime deserialization.

I ran into a really confusing, time consuming problem where datetime deserialization lost millisecond precision.  It wasn't until Alex Gronholm (@agronholm) helped determine the cause was a missing python-dateutil package from my environment.

If you want to reproduce this issue, create a fresh venv, install marshmallow and pytz and then run the first gist.  The pytest results are at the bottom of the gist.  
https://gist.github.com/Dowwie/231d9369341fa574a673

**Comment by agronholm** [comment]
The ideal solution would be to have a conditional dependency on old Python versions that don't have `datetime.timezone.utc`. Newer Python versions should use that then.

**Comment by mark0978** [comment]
And the gist above is now gone 404.....  Why not include the gist in the bug report itself, at least then it would still be here for others reading the bug report.

**Comment by sloria** [comment]
Going to hold off on adding dateutil as a dependency for now. Closing, but feel free to open if these needs further discussion.
