### ISSUE TITLE
Request for feedback: marshmallow-jsonschema

### ISSUE THREAD

**Issue by fuhrysteve** [marshmallow-code/marshmallow#351]
After some discussion on #336, I created a prototype `marshmallow-jsonschema`.

Please let me know if you have any feedback:
https://github.com/fuhrysteve/marshmallow-jsonschema

**Comment by sloria** [comment]
Looks like a good start. Feedback should be sent to the issue tracker for marshmallow-jsonschema.

**Comment by fuhrysteve** [comment]
Sounds great - thanks!
