### ISSUE TITLE
Make skip_on_field_errors default to True?

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#352]
As a follow-up to https://github.com/marshmallow-code/marshmallow/pull/346, we may make `skip_on_field_errors` default to True.

**Comment by immerrr** [comment]
I don't think it's good to omit a check that verifies that `data['x'] < data['y']` if `data['foobar']` is invalid, so I'd say I'd expect `@ma.validates_schema` validator to run by default. However I'd expect the validator to not run by default for `@ma.validates('foobar')` if `foobar` validation failed.

Thinking it deeper, it might be better to enable the user to specify the list of pre-requisite fields validated by a certain `@ma.validates_schema`-validator and don't run that validator if some of the pre-requisite fields failed to validate on their own. Even better would be to have an auto-detection mechanism for such fields, but none comes to mind at this moment. And it doesn't seem that much of a user chore to "declare interest" in certain fields by adding `skip_on_field_errors=['x', 'y']` when writing the validator.
