### ISSUE TITLE
Serialization drops first item of custom iterators

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/marshmallow#353]
```
from marshmallow import Schema, fields

class Range:

    def __init__(self, max):
        self.value = 0
        self.max = max

    def __iter__(self):
        return self

    def __next__(self):
        self.value += 1
        if self.value > self.max:
            raise StopIteration
        return {'value': self.value}

class RangeSchema(Schema):
    value = fields.Int()

RangeSchema(many=True).dump(Range(5)).data
# [{'value': 2}, {'value': 3}, {'value': 4}, {'value': 5}]

list(Range(5))
# [{'value': 1}, {'value': 2}, {'value': 3}, {'value': 4}, {'value': 5}]
```

I'm guessing this is the same problem described in #343, but this should be easier to reproduce. This could be solved by detecting that the value is an iterator and casting to a list, as for generators (which might not be straightforward), or using something like `itertools.tee` to get separate iterators (one for serializing, one for inspecting the first item). Or maybe this is all overkill--maybe values serialized with `many` should have to be eager sequences, so that it isn't marshmallow's responsibility to cast to lists or inspect iterators without advancing them.

**Comment by sloria** [comment]
Ideally, marshmallow would handle iterators and generators transparently. Maybe we disallow implicit field creation if serializing a generator?

**Comment by jmcarp** [comment]
I think generators are handled correctly already because of this:

``` python
if isinstance(obj, types.GeneratorType):
    obj = list(obj)
```

The problem is with non-generator iterables like the example in the issue. Some iterables should probably be cast to lists and eagerly evaluated, like the example, but others shouldn't--strings, dicts, namedtuples, etc. What if `dump` cast list-like iterables to lists, but only when `many` is true? That might be a bit more intuitive than always listifying generators.

Another option would be to peek into the iterable without advancing it, which could be done using `itertools.tee`.

**Comment by sloria** [comment]
Both of those solutions sound reasonable.
