### ISSUE TITLE
@post_dump return obj

### ISSUE THREAD

**Issue by aguilera51284** [marshmallow-code/marshmallow#354]
its possible in the method @post_load return one native object  the python?

**Comment by sloria** [comment]
There is no restriction on what type of object `post_load` returns.

**Comment by tdevelioglu** [comment]
Not true, None values are substituted with the original input data.
Very annoying when dealing with nested objects and relationships.

See also, https://github.com/marshmallow-code/marshmallow/issues/347

**Comment by sloria** [comment]
Closing this for now. Further discussion should happen on #347
