### ISSUE TITLE
No docs on how to use a custom JSON serializer library?

### ISSUE THREAD

**Issue by jeffwidman** [marshmallow-code/marshmallow#357]
Just checking out this library... looks useful. However, I couldn't find any docs on how to use a custom json serialization library? 

I haven't poked deeply, but I assume Marshmallow uses `simplejson` under the covers to serialize to json. If I wanted to switch to a different lib that's a drop-in replacement for simplejson, what do I need to do to Marshmallow so the `dumps()` and `loads()` methods use my custom lib instead?

**Comment by jperras** [comment]
Set the class as the value of the [`json_module` attribute of the schema meta information](http://marshmallow.readthedocs.org/en/latest/api_reference.html#marshmallow.Schema.Meta):

``` python
class UserSchema(Schema):
    name = fields.String()
    email = fields.Email()

    class Meta:
        json_module = MyCustomJSONEncoderDecoder
```

**Comment by sloria** [comment]
@jperras is correct; use the `json_module` class Meta option.

**Comment by jeffwidman** [comment]
Thanks @jperras --much appreciated!

**Comment by gergelypolonkai** [comment]
It’s still not documented, as it seems… or at least not correctly. There is a `render_module` in the docs, but no `json_module`. Which one is true? :)

**Comment by jperras** [comment]
@gergelypolonkai My comment was from 2 years ago, and it seems the API has changed with regards to this functionality. The [current documentation](http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.Schema.Meta) describes `render_module` as what you are looking for.

**Comment by sloria** [comment]
@jperras  correct-- `render_module` is the the new option in version 3 . If you are using version 2, use `json_module`.
