### ISSUE TITLE
Parameter `only` doesn't take `load_from` into account

### ISSUE THREAD

**Issue by CausticYarn** [marshmallow-code/marshmallow#362]
I have a timecode object which has a method called "display" which creates a string representation of the object. I want to serialize and deserialize it to/from a dictionary that has a key called "timecode" with the string representation. I created a field called "display" with an attribute of "load_from=timecode" and "dump_to=timecode" which works great, except when I use the "only attribute" (e.g. I want the serialized version to only contain the timecode string). In this case I get an AttributeError for "timecode".

Does it make sense for `only` to consider the field to exist if it can be pulled from the "load_from" value? Is there a better way to do what I'm trying to do?

**Comment by deckar01** [comment]
It looks like the `AttributeError` is coming from [`Schema.__filter_fields()`](https://github.com/marshmallow-code/marshmallow/blob/4c2354c/marshmallow/schema.py#L739).

``` py
        attribute_type = type(getattr(obj, key))
except (AttributeError, KeyError) as err:
    err_type = type(err)
    raise err_type(
        '"{0}" is not a valid field for {1}.'.format(key, obj))
```

It should probably be handled more like [`Marshaller.deserialize()`](https://github.com/marshmallow-code/marshmallow/blob/4c2354c/marshmallow/marshalling.py#L269) which falls back to `load_from`.

``` py
if raw_value is missing and field_obj.load_from:
    field_name = field_obj.load_from
    raw_value = data.get(field_obj.load_from, missing)
```

**Comment by sloria** [comment]
Closing this for now. Feel free to reopen if this is still an issue.
