### ISSUE TITLE
Change SchemaOpts.json_module to more generic name

### ISSUE THREAD

**Issue by justanr** [marshmallow-code/marshmallow#364]
Seeing as it's not really limited to _just_ json, even if that's most common use case. A more generic name would need to be decided on (raw_handler??) and a deprecation warning could be issued if json_module is set as opposed to the new name.

Use case: I feel silly giving a yaml loader/dumper to json_module.

**Comment by sloria** [comment]
Yep, this was also suggested in #130 , and I think it's a good idea. We just need to settle on a new name.

So far we have:
- `render_module`
- `raw_handler`

**Comment by dirkdevriendt** [comment]
I would vote for `render_module`

Though I might actually prefer to be able to pass in a `serialize_function` and `deserialize_function` instead of a module that needs to provide functions called "dumps" and "loads".

I don't think pyyaml follows this convention, for instance. And adding a proxy module or including a separate definition for which functions to call may seem overkill?

**Comment by maximkulkin** [comment]
@dirkdevriendt Originally it uses interface that JSON modules provide. For modules that do not support given interface (loads/dumps) you can easily create adapters:

```python
import yaml

# json adapter
class MyJsonSerializer:
    @staticmethod
    def loads(data):
        return yaml.load(data)

    @staticmethod
    def dumps(obj):
        return yaml.dump(data)

# or shorter version
class MyJsonSerializer:
    loads = staticmethod(yaml.load)
    dumps = staticmethod(yaml.dump)


class MySchema(marshmallow.Schema):
    class Meta:
        json_module = MyJsonSerializer
    # rest of schema
```

**Comment by dirkdevriendt** [comment]
Thanks for the example, I totally understand. I just thought that if the signature is going to be changed anyway, there could be something to say for making the methods themselves configurable. This would enable:
```python
class MySchema(marshmallow.Schema):
    class Meta:
        serialize_function = yaml.dump
        deserialize_function = yaml.load
    # rest of schema
```
... or any other two methods that may or may not be in the same module.

**Comment by sloria** [comment]
Since the "render module" decides the behavior of "dumps" and "loads", I think it is simpler to have just one option that assumes a "dumps" and "loads" method.

As for the name, I am leaning towards `render_module`.
