### ISSUE TITLE
Serializing an OrderedDict -- order matters

### ISSUE THREAD

**Issue by Dowwie** [marshmallow-code/marshmallow#372]
I'm trying to figure out the best approach to serializing an OrderedDict attribute.  

One solution that comes to mind is pre_dump converting it to a tuple of tuples where the first element of each tuple is the key, and pre_load converting this structure back into an OrderedDict at deserialization.

Is there a better approach?

**Comment by sloria** [comment]
Sorry for not getting to your question sooner. If you found a solution, feel free to post it. Closing this issue for now.
