### ISSUE TITLE
Newbie question: How to handle undeclared fields?

### ISSUE THREAD

**Issue by rmiJ8a3bcbQPh87vHFg6xiWYBcRcQnNM** [marshmallow-code/marshmallow#374]
I am trying to validate a dict which contains stringified integers as keys. These ints are arbitrary numerical IDs, and out of my control.

How could I declare this in a schema?

Thanks!

**Comment by sloria** [comment]
Not sure if this is what you're looking for, but you could dynamically generate a schema based on input data using a factory.

Something like:

``` python
from marshmallow import Schema, fields


def schema_factory(data):
    schema_fields = {
        key: fields.Field(required=True) for key, value
        in data.items()
    }

    class MySchema(Schema):
        class Meta:
            include = schema_fields

    return MySchema


data = {'1': 'foo', '2': 'bar'}
schema_cls = schema_factory(data)
schema = schema_cls()
print(schema.load({'1': 'foo'}).errors)
# {'2': ['Missing data for required field.']}
```

**Comment by ergo** [comment]
That approach will not work for for nested structures that we may not know upfront.
Use case for me: For App Enlight (where I use colander for validation), I have logs and error reports that may have arbitrary tags and request variables attached, to create a factory for that would be tricky.

Is there a way to maybe allow for something like `preserve_unknown=True` for Schema class?
Turning this on would make the schema.load() attach fields it finds on the structure.

http://docs.pylonsproject.org/projects/colander/en/latest/api.html#colander.Mapping - in colander this functionality is controlled by `unknown` argument.

**Comment by ergo** [comment]
@sloria do you think its possible to use similar solution?

**Comment by sloria** [comment]
@ergo It sounds like you are describing a different use case than the OP. In order to preserve key-value pairs that aren't declared in your schema, you could use a `post_load` method and pass the original data. 

Something like

``` python
from marshmallow import Schema, fields, post_load

class MySchema(Schema):
    known = fields.Field()

    @post_load(pass_original=True)
    def _add_unknown(self, data, original):
        """Preserve unknown keys during deserialization."""
        for key, val in original.items():
            if key not in self.fields:
                data[key] = val
        return data

data = {'known': 42, 'unknown': 24}
schema = MySchema()
print(schema.load(data).data)
# {'known': 42, 'unknown': 24}
```

@ergo Does this meet your use case?

**Comment by ergo** [comment]
@sloria yes that meets my use case I think. Thanks
