### ISSUE TITLE
Deserializing only specific fields from a schema in fields.Nested?

### ISSUE THREAD

**Issue by joshfriend** [marshmallow-code/marshmallow#375]
The `only` parameter for [`fields.Nested`](http://marshmallow.readthedocs.org/en/latest/api_reference.html#marshmallow.fields.Nested) only applies to serialization.

Since you can only pass the schema class or name string to `fields.Nested`, there is currently no way to limit which fields are deserialized. `Schema.__init__()` allows use of `dump_only` and `load_only`, but these cannot currently be used with `fields.Nested`.

Is there a way to limit which fields are deserialized from a nested schema?

**Comment by justanr** [comment]
You're not talking about excluding fields when you call the parent schema, just when you register the child?

If I'm right, then pass an exclude keyword with an iterable.

``` python
class ParentSchema(Schema):
    child = Nested(ChildSchema, exclude=['field'])
```

If I'm wrong, and you're talking about doing:

``` python
class ParentSchema(Schema):
    child = Nested(ChildSchema)

ParentSchema(exclude=['child.field'])
```

Then that's not supported right now.

**Comment by repole** [comment]
So just to be clear, there's no way to set which fields in a nested field are to be excluded other than in the parent class definition?

**Comment by joshfriend** [comment]
> You're not talking about excluding fields when you call the parent schema, just when you register the child?

Right.

> If I'm right, then pass an exclude keyword with an iterable.

The `exclude` option is getting at what I need to do, but is kindof the inverse. I want `only` certain fields, but that option only works for serializing and I don't want to explicitly exclude all the fields I don't need.

I wanted this:

``` python
class IDSchema(Schema):
    id = fields.Integer()

class ChildSchema(IDSchema):
    name = fields.Str(allow_none=False, required=True)

class ParentSchema(BaseSchema):
    # only load the ID of the nested objects
    children = fields.Nested(
        ChildSchema,
        many=True,
        required=True,
        load_only=True,
        only=('id',)
    )
```

But ended up with this:

``` python
class ParentSchema(BaseSchema):
    # only load the ID of the nested objects
    children = fields.Nested(
        IDSchema,
        many=True,
        required=True,
        load_only=True,
        only=('id',)
    )
```

Which works, but then I am unable to use the same schema for both serializing _and_ deserializing.

**Comment by justanr** [comment]
Ah. I see what you're getting at. Something like being able to say: `fields.Nested(SomeSchema, partial=True)`? @sloria Would you be open to a PR for this?

**Comment by joshfriend** [comment]
I'm more interested in using `only` to ignore any extra info the client might send, rather than accepting however many fields the client wants to send. I think `partial` will already apply to nested schemas if it is given on the parent.

**Comment by sloria** [comment]
I believe the desired behavior is already implemented--the `only` parameter is respected upon deserialization. I've verified that @joshfriend 's code example works in both marshmallow 2.13.3 and 3.0.0b1.

```python
from marshmallow import Schema, fields

class IDSchema(Schema):
    id = fields.Integer()

class ChildSchema(IDSchema):
    name = fields.Str(allow_none=False, required=True)

class ParentSchema(Schema):
    # only load the ID of the nested objects
    children = fields.Nested(
        ChildSchema,
        many=True,
        required=True,
        load_only=True,
        only=('id',)
    )

    class Meta:
        strict = True


sch = ParentSchema()
data = sch.load({'children': [{'id': 1, 'name': 'foo'}]}).data
assert data == {'children': [{'id': 1}]}
```
