### ISSUE TITLE
validators are run before missing values are acquired

### ISSUE THREAD

**Issue by chadrik** [marshmallow-code/marshmallow#376]
The following code fails to validate:

``` python
class BookSchema(Schema):
    author = fields.String(required=True)
    setting = fields.String(
        missing='this',
        validate=validate.ContainsOnly(['this', 'that', 'other'])
    )

print BookSchema(strict=True).load({'author': 'chad'}).data
```

The error is:

```
marshmallow.exceptions.ValidationError: {'setting': [u'One or more of the choices you made was not acceptable.']}
```

without the validator, I get the expected result:

``` python
{'setting': u'this', 'author': u'chad'}
```

It seems that the `missing` value should be acquired before validation for this to work as expected.  Or is this user error?

Thanks!
-chad

**Comment by chadrik** [comment]
and it was user error!  sorry...

**Comment by javiersanp** [comment]
I have a Issue similar to this one with this code:
```
class DateRange(Schema):
    date_from = fields.DateTime(missing=date(2019,1,1))

print(DateRange().load({}))
```

get:

`UnmarshalResult(data={}, errors={'date_from': ['Not a valid date.']})`

while expected: 

`UnmarshalResult(data={'date_from': date(2019, 1, 1)}, errors={})`

Please could any one show me where is the user error?

**Comment by javiersanp** [comment]
Forgive me! The answer is here #378
