### ISSUE TITLE
missing and default values should be specified in deserialized form

### ISSUE THREAD

**Issue by chadrik** [marshmallow-code/marshmallow#378]
Marshmallow expects `missing` and `default` values to be specified in a pre-serialized form, which is inconvenient and unintuitive.

Here is a schema which I would expect to work:

``` python
import datetime
import uuid

class TestSchema(Schema):
    id = fields.UUID(
        missing=uuid.uuid1)
    ts = fields.DateTime(
        format='rfc',
        missing=datetime.datetime.now)
```

However, it does not:

``` python
schema = TestSchema()
pprint.pprint(tuple(schema.load({})))
({}, {'id': [u'Not a valid UUID.'], 'ts': [u'Not a valid datetime.']})
```

Instead, I have to convert my `default` and `missing` values to primitive types, which undermines the purpose of a library like marshmallow that already knows how to do this.  For data types like datetimes, which have many possible serialized formats, I have to keep the formatting of my `default` and `missing` values in sync with my field properties, which is fragile and convoluted:

``` python
from email.Utils import formatdate

class TestSchema(Schema):
    id = fields.UUID(
        missing=lambda: str(uuid.uuid1()))
    ts = fields.DateTime(
        format='rfc',
        missing=formatdate)
```

In the case of `default` values, marshmallow does not attempt to validate them, so no error is raised, but the resulting document is not deserializable.

**Comment by immerrr** [comment]
I have hit this working with comma-delimited parameters in webargs.

**Comment by costrouc** [comment]
I had this exact same error. I find it unintuitive that `missing=datetime.now` does not work but instead requires `missing=lambda: str(datetime.now())`

**Comment by sloria** [comment]
I think the OP makes sense. I would gladly review and merge a PR for this.

**Comment by lafrech** [comment]
I just sent a PR to achieve this.

@chadrik, @costrouc, @sloria, feedback welcome.

**Comment by Kareeeeem** [comment]
That workaround works but then context is not there. I get the idea for the change but the defaulting nested schemas just became a hell of a lot more convoluted.
