### ISSUE TITLE
Allow Marshmallow Schema definitions to be written in JSON Schema

### ISSUE THREAD

**Issue by MichalKononenko** [marshmallow-code/marshmallow#381]
I'm writing a REST API, and I want to use Marshmallow as an input validator. For the 3.0 release, could we add some methods to expose `Marshmallow.Schema` objects using [JSON Schema](http://json-schema.org/). This way, sending an OPTIONS request to the API would allow much greater discoverability of the available resources.

The [Heroku API](https://devcenter.heroku.com/articles/platform-api-reference#overview) provides an interesting example of how to apply JSON schema to describe their API, but I'm not sure how it was coded on the back end. Providing methods to dump Marshmallow Schemas as JSON schema would be great as the schemas would then travel with the API endpoints.

**Comment by sloria** [comment]
JSON Schema is outside the scope of marshmallow core and will not be added. This belongs in a separate library. Some of this work has started here: https://github.com/fuhrysteve/marshmallow-jsonschema
