### ISSUE TITLE
Why marshmallow is so slow?

### ISSUE THREAD

**Issue by frogcjn** [marshmallow-code/marshmallow#387]
I have a local json file contains 10000+ objects.
firstly I load the file contents into list of dictionary. Then loading them into advanced class.

when doing it with marshmallow Schema, it needs 10-20 seconds, 
but if I use old methods, it only needs 1.x seconds.

My old method:
`self.__dict__.update(dictionary)`, and modify the attributes as needs.

**Comment by sloria** [comment]
Not sure where you are hitting bottlenecks, but this might just be a case of "more code = slower code". `self.__dict__.update` is about as little code as you can get, so it will of course be much faster.

It would be great to do profiling to see where we can improve, but I haven't been able to put the time investment. I would be grateful to anyone who would look into this.

Closing this issue for now as it is unspecific. We can open up more specific, actionable issues if someone looks into profiling.
