### ISSUE TITLE
Getting field list in a `SchemaMeta` extension

### ISSUE THREAD

**Issue by bereal** [marshmallow-code/marshmallow#389]
The title might be a sort of XY-problem, so I'll explain the X-part first.
I want to generate data classes automagically from the Schema class, so that the following would work without writing redundant code:

```
class UserSchema(MySmartSchemaExtension):
    firstName = fields.Str(attribute='first_name')
    lastName = fields.Str(attribute='last_name')

user = UserSchema.DataType('John', 'Doe')
assert user.first_name == 'John'
assert user.last_name == 'Doe'
```

That seems trivial by extending `SchemaMeta` and generating a `namedtuple` or anything similar within `__new__`. However, for that purpose I'd need a full list of declared fields, which is available only as a protected field. Is there any workaround, or am I out of the right track completely? Would it be even better to generate such a type per schema instance (`UserSchema().DataType`) rather than per class?

**Comment by sloria** [comment]
`_declared_fields` is the correct way to access all declared fields. I think either setting `DataType` in a metaclass or on an instance is fine. I could see an advantage to setting it per-instance if you wanted to generate `DataType` based on any of the constructor arguments (e.g. `only`, `exclude`).
