### ISSUE TITLE
How to declare required field "name"?

### ISSUE THREAD

**Issue by citizen-stig** [marshmallow-code/marshmallow#393]
I have a following schema:

```
class KidSchema(Schema):
    name_field = fields.String(attribute='name', dump_to='name', required=True)
    gender = fields.String(required=True,
                           validate=validate.OneOf(choices=(models.MALE, models.FEMALE)))
    birthday = fields.DateTime(required=True, format='iso8601')
```

When I try to load schema from json, I've got an error:

`marshmallow.exceptions.ValidationError: {'name_field': ['Missing data for required field.']}`

I could define it just as `name` instead of `name_field`, but I override some name attribute, that could be used somewhere and I could get some weird errors then.

What should I do?

**Comment by justanr** [comment]
Are you loading from `name` as well? If so, add `load_from='name'`

**Comment by sloria** [comment]
@justanr is correct; `load_from` looks like it meets your use case.

**Comment by citizen-stig** [comment]
@justanr, thank you
