### ISSUE TITLE
Required field custom error message doesn't work as documented

### ISSUE THREAD

**Issue by grimzy** [marshmallow-code/marshmallow#396]
According to the documentation (http://marshmallow.readthedocs.org/en/latest/quickstart.html#required-fields), a custom error message can be set by passing `required='My custom message'` to the field definition but it always returns the default message: `'Missing data for required field.'`.

In the following example, if we omit both the email and password, we get the custom message for the missing password, but not for the email.

```
class LoginSchema(Schema):
    email = fields.Email(
        required='E-mail address is required.'
    )
    password = fields.String(
        required=True,
        error_messages={
            'required': 'Password is required.',
        }
    )
```

I'm using marshmallow 2.6.0 on python 2.7.6

It's almost 2 am here but I'll look into this issue in more details in a couple of days.
Thank you!

**Comment by sloria** [comment]
Sorry for the confusion; passing a string to `required` was removed in version 2.2. See the changelog here: https://marshmallow.readthedocs.org/en/latest/changelog.html#id14 . Instead, use the `error_messages` argument. I've updated the documentation accordingly. Thanks for reporting this!
