### ISSUE TITLE
Keep fields order

### ISSUE THREAD

**Issue by zerodivisi0n** [marshmallow-code/marshmallow#40]
Fields are returned in a random order after marshalling. I would not pay attention to it, if the return type was not `OrderedDict`. Why use `OrderedDict`, if the fields are still returned in random order?

I think the problem for this is the use of unordered `set` [here](https://github.com/sloria/marshmallow/blob/62e5cebd9326db504a485e87e677e1a00a5e814c/marshmallow/serializer.py#L323).

It would be great if the fields returned in the order in which they are declared in serializer. It is much prettier for RESTful APIs.

**Comment by sloria** [comment]
You are correct; using the `fields` or `additional` class Meta options does not preserve order in the final output. 

Will push a patch to this soon.

Thanks for reporting!

**Comment by zerodivisi0n** [comment]
It's great! Thank you for this library!

**Comment by zerodivisi0n** [comment]
Ok, just checked it.
But it does not work with declaring serializer like so:

``` python
class PersonSerializer(Serializer):
    id = fields.String()
    created_at = fields.DateTime()
    name = fields.String()
    phone = fields.String()
    email = fields.String()
```

The result looks like this:

``` json
{"name": "Guido van Rossum", "created_at": "2014-08-20T23:17:31.705290+00:00", "id": "125", "phone": "", "email": "a@b.com"}
```

I did not have much time to sort out what is the reason, but I think the problem in method [get_declared_fields](https://github.com/sloria/marshmallow/blob/8df06d3c6a10ea6138c7c403679bab77e90b247b/marshmallow/serializer.py#L37):

``` python
>>> s = PersonSerializer()
>>> s.declared_fields
OrderedDict([('name', <String Field>), ('created_at', <DateTime Field>), ('id', <String Field>), ('phone', <String Field>), ('email', <String Field>)])
```

**Comment by sloria** [comment]
Thanks for catching that. Ordering of declared fields has been fixed as well.
