### ISSUE TITLE
Naming of `invalid_guid` error type for UUID field

### ISSUE THREAD

**Issue by imhoffd** [marshmallow-code/marshmallow#401]
I'm wondering why the choice was made to call this `invalid_guid` https://github.com/marshmallow-code/marshmallow/blob/1da951c0474f9af393a6736c13abf6cbcca85cee/marshmallow/fields.py#L578

GUID classically refers to Microsoft's implementation, and the code is using the `uuid.UUID` constructor, so my question is why deviate from the naming scheme, as GUID isn't mentioned at all in the Python docs?

**Comment by sloria** [comment]
Good catch; this was indeed a typo. I've fixed it in  78551b3, maintaining backwards compat. `invalid_guid` will be removed in marshmallow 3.0

**Comment by imhoffd** [comment]
:+1: Perfect. Thanks for the quick response as always.
