### ISSUE TITLE
Dynamically specify 'only' parameter for nested fields

### ISSUE THREAD

**Issue by Archelyst** [marshmallow-code/marshmallow#402]
I'm able to specify the `only` parameter when instantiating a schema (`MySchema(only=('field1', 'field2')`), however, this does not work for nested fields. I'd like to be able to have something like `MySchema(only=('field1', ('field2', ('subfield1', 'subfield3'))))` where _field2_ is a nested field of which only _subfield1_ and _subfield2_ should be serialized.

I'd be willing to implement it, however, first I wanna know if it has a chance to get into marshmallow. Secondly, it seems to not be a straight forward addition; instead of (or additionally to) during instantiation of the nested schema, the _only_ parameter needs to be passed when serializing. So I'd appreciate any hints of how to implement this properly.

The motivation behind this are APIs like [JSONAPI](http://jsonapi.org/) which allow to dynamically specify fields like so: `GET /articles?include=author&fields[articles]=title,body&fields[people]=name`. One could argue that resources are not really rendered in a nested fashion in JSONAPI responses. So lets assume, we use a (not yet implemented) `IncludeSchema` instead. That will, however, leave us with the same challenges of specifying the _only_ parameter dynamically.

**Comment by deckar01** [comment]
After working on a new project with marshmallow, I started using the `Method` field more heavily, and realized that it is a really powerful abstraction that could potentially bridge the gap here.

https://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.fields.Method

``` py
from marshmallow import fields

import utils

class PetShopSchema(NamedSchema):
    pet = fields.Nested('PetSchema', only=('name', 'url'))
    foo = fields.Method(serialize='get_nested_fields', only=('foo', ('bar', ('baz', ))))

    def get_nested_fields(self, obj, field_names):
        return utils.get_nested_fields(obj, field_names)
```

It doesn't help at schema instantiation time, but it does give you the freedom to nest however you please.

**Comment by Archelyst** [comment]
Nice idea, thanks for sharing.
