### ISSUE TITLE
method field is not called

### ISSUE THREAD

**Issue by norbertpy** [marshmallow-code/marshmallow#403]
Why the method field is not called when loading a dict?

``` python
from marshmallow import Schema, fields

class UserSchema(Schema):
    first_name = fields.Str(load_from='name')
    email = fields.Email()
    custom = fields.Method('yo')

    def yo(self, obj):
        return 'custom'

schema = UserSchema()
result = schema.load({'name': 'j', 'email': 'j@j.jom'})
print result.data # prints {'first_name': u'j', 'email': u'j@j.jom'}   
```

**Comment by norbertpy** [comment]
Never mind. It's only called when `dumping` not `loading`. But why?

**Comment by brettdh** [comment]
@norbertpy did you figure this out? I'm in a similar situation of confusion.

**Comment by norbertpy** [comment]
@brettdh Nope. I think there should be another function for when you're loading but I couldn't find it. Maybe some contributors can chime in.

**Comment by brettdh** [comment]
#409 might help.

**Comment by brettdh** [comment]
To elaborate: I needed to use the `deserialize` kwarg to `Method()` to get what I wanted, and the field had to be present to get processed.
