### ISSUE TITLE
generate fake data from schema

### ISSUE THREAD

**Issue by jo-tham** [marshmallow-code/marshmallow#404]
Hi,

had a look at the [ecosystem](https://github.com/marshmallow-code/marshmallow/wiki/Ecosystem) and searched the issues and didn't find anything on this topic.

does anyone have strategies for generating data from marshmallow schema?
any appetite for another library that does this?

my other thought was using the ORM libraries (factory_boy or mixer) and then using the schema to serialize... but it seems a round-about way of faking data for testing a web api.

**Comment by deckar01** [comment]
The field base class allows specifying a [`default` value](https://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.fields.Field) for serialization.

> **default** – If set, this value will be used during serialization if the input value is missing. If not set, the field will be excluded from the serialized output if the input value is missing. May be a value or a callable.

The main incompatibility between Factory Boy and Marshmallow is that Factory Boy expects models to be instantiated by passing named arguments to the model's constructor to return a model instance, but Marshmallow schema instances have a `dump()` method that transforms dictionaries into other dictionaries (or strings with `dumps()`).

It should be possible to implement a similar wrapper for marshmallow `Schema` classes. I would name the library "Marshmallow Factory _()¯) ()¯) ()¯)_". :wink: 

``` py
from marshmallow_factory import Factory

from my_schemas import ExampleSchema

exampleFactory = Factory(schema=ExampleSchema(), defaults={'field1': 'foo', 'nested': {'field2': 'bar'}})
exampleFactory.dump({'field1': 'baz'})
# {'field1': 'baz', 'nested': {'field2': 'bar'}}
```

**Comment by deckar01** [comment]
Actually, with that interface the implementation could be as simple as:

``` py
# marshmallow_factory.py

class Factory(object):

    def __init__(self, schema, defaults={}):
        self.schema = schema
        self.defaults = {}
        self.defaults.update(defaults)

    def complete(self, data={}):
        complete_data = {}
        complete_data.update(self.defaults)
        complete_data.update(data)
        return complete_data

    def dump(self, data={}, *args, **kwargs):
        return self.schema.dump(self.complete(data), *args, **kwargs)

    def dumps(self, data={}, *args, **kwargs):
        return self.schema.dumps(self.complete(data), *args, **kwargs)
```

**Comment by sloria** [comment]
@deckar01 Slick and simple. I like it!

**Comment by justanr** [comment]
@deckar01 Be careful with those default `{}` -- it's only evaluated once so you could end up affecting the actual state from call to call if it's not overridden.

**Comment by deckar01** [comment]
@justanr Good call. Although I am never mutating the `defaults` attribute, I can see someone being tempted to reach in and update it.

I changed

``` py
def __init__(self, schema, defaults={}):
    self.schema = schema
    self.defaults = defaults
```

to

``` py
def __init__(self, schema, defaults={}):
    self.schema = schema
    self.defaults = {}
    self.defaults.update(defaults)
```

This should act as a shallow copy to also prevent mutations to the supplied dictionary from mutating the default values. A deep copy is probably out of scope for this example.

The rest of the dictionary arguments are only used to update temporary dictionaries.

Maybe this should be moved to a gist.
