### ISSUE TITLE
Docs: requesting example of deserialization with fields.Method

### ISSUE THREAD

**Issue by brettdh** [marshmallow-code/marshmallow#409]
From #394:

> `Method` and `Function` callbacks are not called if the field is missing in JSON

This was quite surprising to me, which told me that I had fundamentally misunderstood what these field types were for on the deserializing side.

For instance, going by the [custom fields `Method` example](http://marshmallow.readthedocs.org/en/latest/custom_fields.html#method-fields), I had 1) missed that this example was only about serializiation; 2) thought that a `Method` field would pull data from an already-deserialized object, and that doing so would create a new field; and 3) therefore thought that the `Method` field would never be expecting to parse data given by its field name; only to generate it from some other supplied data.. I now see that this is more like a transformation - it takes data present in the input and transforms it with the given method, storing the result in the deserialized object.

You can see how this misunderstanding led to me reporting this issue: sloria/webargs#94. I now realize that that case is probably better handled with a `@post_load` method. However, I'd like to request that examples be added showing deserialization with `Method` and `Function` fields, so that someone might not make this mistake in the future.

**Comment by sloria** [comment]
I can understand your confusion. I've added a brief section in the docs here: https://marshmallow.readthedocs.org/en/dev/custom_fields.html#method-and-function-field-deserialization which will hopefully clarify deserialization behavior for `Method` and `Function`.

**Comment by gstryjew** [comment]
If in your data and schema fields have different names you need to add load_from param to your field to apply deserialized method to this field, otherwise the method will not be execute.

**Comment by sloria** [comment]
That is correct @gstryjew . Feel free to send a PR updating the docs =)
