### ISSUE TITLE
remove root, parent, and name from SchemaABC

### ISSUE THREAD

**Issue by Archelyst** [marshmallow-code/marshmallow#410]
In the `SchemaABC` class there are three attributes which I don't see used anywhere:

```
class SchemaABC(object):
    """Abstract base class from which all Schemas inherit."""

    root = None
    parent = None
    name = None
```

Also they make it awkward when adding fields with the very common (even in the tutorials) names `parent` and `name` to a schema. If there is consensus that they can be removed, I can provide a PR.

**Comment by sloria** [comment]
Yes,  I think these can be removed. I would gladly merge a PR. Thanks!

**Comment by Archelyst** [comment]
What is `Field.root` supposed to accomplish? Is that just for cases like

```
class MySchema(schema.Schema):
    foo = fields.Field()
    bar = fields.List(fields.Str())
```

where the string field might wanna know that it's attached to `MySchema`? Or is "topmost" also to be understood in the context of nested fields like so

```
class ParentSchema(schema.Schema):
    child = fields.Nested(MySchema)
```

where `MySchema.foo` might wanna know that it's attached to `ParentSchema`? Then the string container in `MySchema` would also have `ParentSchema` as root.

**Comment by sloria** [comment]
Yes and yes. `root` allows arbitrarily nested fields to access the `Schema` they are bound to.

**Comment by Archelyst** [comment]
Hm, those two options were meant as being exclusive :) The question is: should `root` point to the immediate schema (that's how it's implemented right now in dev and this branch) or to the top-most schema?

**Comment by Archelyst** [comment]
It's just one additional line to achieve the latter. It's just the question if that counts as API break.

**Comment by sloria** [comment]
I would consider that a backwards-incompatible change. Is that what you have implemented in your PR?

**Comment by Archelyst** [comment]
No, the PR is current behavior.
