### ISSUE TITLE
ValidationError i18n support?

### ISSUE THREAD

**Issue by repole** [marshmallow-code/marshmallow#419]
Is there any established way or best practice to handle internationalization of validation error messages? Is there anything built in to support this? The only way I can see to handle this is to subclass each and every field, which seems less than ideal.

EDIT: It seems adding callables for error messages would make this possible, as mentioned in #334. Consider this a vote for moving forward with the suggestion outlined there.

**Comment by sloria** [comment]
There is no current built-in i18n, and I've not decided on whether to take on the maintenance burden of adding it to marshmallow core.

I agree that implementing #334 could be an iterative steps towards this.

You might also look at [marshmallow-validators](https://marshmallow-validators.readthedocs.org/en/latest/#module-marshmallow_validators.wtforms), which allows you to use validators from WTForms and colander, which have 1189 support.

**Comment by repole** [comment]
Makes sense, can certainly understand the hesitation to add that sort of complexity in.

As for marshmallow-validators, my understanding is there are certain ValidationErrors in marshmallow ([like trying to pass a non collection to a Nested many=True field](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L429)) that are basically unavoidable. So even if I provide my own validators that translate errors using marshmallow-validators, bad input would still trigger an error that doesn't get translated.

Thanks for the help, appreciate it!

**Comment by sametmax** [comment]
Funny, I was going to ask the same. What you could do is to allow passing a callable where you usually pass a string. This way we would pass 'Error message {foo}' or _('Error message {foo}'), with _() returning an callable. The if the message is a callable and not a string, you pass it the context, and it returns a string and just just display that. This delegates to us the work to do the translation machinery, you just provide the hooks so we can do so.

**Comment by sloria** [comment]
Closing this for now. Addressing #334 should meet this use case.
