### ISSUE TITLE
Is it possible to get JSON-representation of a marshmallow schema?

### ISSUE THREAD

**Issue by efibutov** [marshmallow-code/marshmallow#421]
The result JSON should contain all the info present in the schema's description
(e.g, **required** values, **nested** fields (in recursive manner), **enum** fields (lists) etc.)

I need it mainly to send the JSOn schema to a client-side  in order to render it on HTML page and fill the fields

**Comment by sloria** [comment]
You should look into using marshmallow-jsonschema for this functionality: https://github.com/fuhrysteve/marshmallow-jsonschema
