### ISSUE TITLE
Schema.declared_fields should be set by metaclass

### ISSUE THREAD

**Issue by xlotlu** [marshmallow-code/marshmallow#426]
Since the deepcopy is going to happen anyway, I think it should be done under `SchemaMeta.__new__`. This way one could have access to the final fields from the schema class without the need for instantiation.

**Comment by justanr** [comment]
[See this comment thread](https://github.com/marshmallow-code/marshmallow/pull/368#issuecomment-186911800), specifically my comment a few down.

I'm not 100% sure what the actual ramifications for doing this are - the Schema is an instance of SchemaMeta and can have instance variables set on it that _are not_ accessible from the instance at all (well, from my testing and prodding) which makes serialization more complicated.

I think it's an interesting quirk (feature?) of the type system, but I'm not sure what the practical applications are.

**Comment by sloria** [comment]
Closing this for now, as this has gone stale and we don't have immediate plans to implement this. Feel free to re-open if there's more to discuss here.
