### ISSUE TITLE
Better namespacing in class registry.

### ISSUE THREAD

**Issue by justanr** [marshmallow-code/marshmallow#43]
_"Namespaces are one honking great idea -- let's do more of those!"_

Currently, class registry uses a global dictionary. This works. However, when developing a versioned API (my current situation), this will potentially lead to schema names like `V1_SomeSchema` or `SomeSchema_V2`.

I understand why the class registry was implemented in this fashion. However, I'm proposing one of two changes.

**Easy**: Add a `schema_group` or similar named attribute on schemas that groups schemas into...well, groups. With `schema_group` defaulting to something sane (such as `default` or `base`). This could be implemented on either the actual schema or (even better) on the Meta options for the Schema.

Example

```
# v1/schemas/__init__.py:
SomeSchema(BaseSchema):
    class Meta:
        schema_group = 'v1'

# v2/schemas/__init__.py:
SomeSchema(BaseSchema):
    class Meta:
        schema_group = 'v2'
```

And then `_registry` would resemble:

```
{
    'v1' : 
        { 'SomeSchema' : [v1.schemas.SomeSchema] },
    'v2' : 
        { 'SomeSchema' : [v2.schemas.SomeSchema] }
}
```

Of course, `class_registry.get_class` and how it's implemented with things such as `fields.Nested` will also have to change to accommodate this change as well.

**Harder:** Some how create instances of the registry and explicitly pass them around or some how tie them to Schemas (think SQLAlchemy's metadata object). This would be more difficult to implement as things like `class_registry` would need to change completely. Again, the most likely home for this would be on the Meta class:

```
v1_reg = Registry()
SomeSchema(BaseSchema):
    class Meta:
        registry = v1_reg
```

**Comment by sloria** [comment]
When a class is registered, both the class's name and its fully-qualified module path are added to the registry. Therefore, given your directory structure above, you can do:

``` python
fields.Nested('v2.schemas.SomeSchema')
```

This allows you to have schemas of the same name (but in different modules). Is there a need for another level of namespacing on top of a module path?

**Comment by justanr** [comment]
Hm. I guess I never noticed that aspect of it, only that the class name was stored (I don't believe this is explicitly shown in code examples, though it's been a _very_ long day). Well, I feel silly now. :/

Assuming the file path to the schema was `app/api/v1/schema.py` the import path stored would be `app.api.v1.SomeSchema`?

**Comment by sloria** [comment]
Yes, that looks correct.

I've just added a note in the quickstart guide about this. Thanks for reporting this!

**Comment by justanr** [comment]
Thanks for clarifying. :) I suppose this can be closed now.
