### ISSUE TITLE
Deserialization fails when using @pre_load(pass_many=True) on a nested Schema

### ISSUE THREAD

**Issue by rubendura** [marshmallow-code/marshmallow#431]
I've found a case where deserialization seems to fail when I try to use a @pre_load method on a nested schema. The following code fails with `marshmallow.exceptions.ValidationError: {'a2': ['Invalid type.']}`

``` python
from marshmallow import Schema, fields
from marshmallow.decorators import pre_load


class ASchema(Schema):
    field = fields.Integer()

    @pre_load(pass_many=True)
    def remove_envelope(self, data, many):
        if many:
           return data['items']
        else:
           return data

class BSchema(Schema):
    a = fields.Nested(ASchema)
    a2 = fields.Nested(ASchema, many=True)


data = {
    'a': {'field': 1},
    'a2': {
        'total': 1,
        'items': [{'field': 2}]
    }
}

BSchema(strict=True).load(data)
```

The problem seems to be in `marshmallow/fields.py:Nested._deserialize`. In this method there is a check where if self.many = True and value is a dict it will fail. The pre_load processor is not called until after that check, making it impossible as far as I know to remove envelopes on nested fields.

Also as far as I know load_from can't be used to traverse multiple keys when declaring fields, so this option wouldn't work either.

**Comment by Lacrymology** [comment]
I have a similar issue, I have a model that has references to other objects, so in my `pre_dump` I basically do `if obj.is_key(): return obj.get()`. This schema marshalls keys okay, but when I try to marshall the parent object, which has a list of keys in that field, it fails. I'm being forced to manually call the `pre_dump` method of the child schema in the parent's `pre_dump`

**Comment by lafrech** [comment]
I just tested with 

```python
class BSchema(Schema):
    a = fields.Nested(ASchema)
    a2 = fields.List(fields.Nested(ASchema))
```

and the same happens for the same reason (same check in `List._deserialize`):

    marshmallow.exceptions.ValidationError: {'a2': ['Not a valid list.']}

Fixing this in `Nested` involves reworking the link between `Nested.deserialize` and `Schema.load` and it conflicts with the `only` feature (which looks like an edge case feature anyway, IMHO).

I'm not sure the `List(ChildSchema)` case is even fixable.

Maybe the whole `many` case of the processors is limited/broken by design.

Obviously, you can add the `pre_load` processor to the parent `Schema`.

```python
class ASchema(Schema):
    field = fields.Integer()

class BSchema(Schema):
    a = fields.Nested(ASchema)
    a2 = fields.Nested(ASchema, many=True)

    @pre_load()
    def remove_envelope(self, data):
        # TODO: check items exist
        data['a2'] = data['a2']['items']
```

**Comment by deckar01** [comment]
`only` and `exclude` support dot delimited nested keys. `load_only` and `dump_only` (or `data_key` for v3) could too. There is another bug in 2.x that would prevent using the same key for the data and the schema. Adding this feature to v3 would work though. The implementation should be significantly simpler than it was for `only` and `exclude`.

```py
class ASchema(Schema):
    field = fields.Integer()

class BSchema(Schema):
    a = fields.Nested(ASchema)
    a2 = fields.List(fields.Nested(ASchema), data_key='a2.items')
```

**Comment by sloria** [comment]
Closing this, as it has gone stale. Feel free to re-open if this is still relevant.
