### ISSUE TITLE
How to immediately stop deserializing if 1 validation fail?

### ISSUE THREAD

**Issue by trungduyvu** [marshmallow-code/marshmallow#436]
Hi,

New user of marshmallow here so please let me know if I'm missing something obvious. Is there a way to immediately stop deserializing and raise ValidationError if just 1 validation fail. The most obvious way I can see from looking at the source is to change deserialize to break the for loop if call_and_store adds an error.

Why it'd be a nice to have feature: right now I have to validate some field using built in validation and some in request handler code (after deserialize was called). That way, the deserialize would throw Validation error and the validation code in request handler would not be reached.

**Comment by maximkulkin** [comment]
Why would you want to do that? The validations themselves should be effect free (like you shouldn't do http requests in your validators), so why does it matter if you will run only one validation or all of them?

As of your request handler, I think it is pretty trivial:

``` python
def my_http_handler():
    data, errors = MySchema().load(request.json())
    if errors:
        raise SomeError(errors)

    # rest processing
```

or you can use `strict=True`:

``` python
def my_http_handler():
    data, _ = MySchema(strict=True).load(request.json())
    # rest processing
```

**Comment by sloria** [comment]
We don't currently plan to support this feature. As @maximkulkin is suggesting, keep your validation logic free of side-effects and you won't have problems.

If you need to do postprocessing and validation after deserialization is finished, you can use a `post_load` method. NOTE: `post_load` methods are only run if all the input data are valid, and you can raise `ValidationErrors` in the `post_load` method itself.
