### ISSUE TITLE
validation optional fields

### ISSUE THREAD

**Issue by ammurphy** [marshmallow-code/marshmallow#440]
Our shop is taking a hard look at using Marshmallow for data validation and serialization.

One issue we've come across is how to correctly handle validating optional fields where the passed field value is None.  For Django forms, this is OK.  e.g. if field_a is optional and the passed data structure either has no key for field_a or the key for field_a points to None, the form will still validate (at least for this field).  In the case of Marshmallow, only former works.  i.e. for all optional keys currently set to None, we must removed them from the dictionary before attempting to pass to the Schema object.  This seems a bit cludgey and I wonder if there's a better way to handle this situation with Marshmallow.

a few examples below further illustrate my point.

``` python
class AdamSchema(Schema):
    field_a = fields.Integer(required=False, 
                             validate=lambda n: n > 40)
    field_b = fields.Integer()

#1
# works (i.e. throws expected validation error correctly)
schema = AdamSchema()
result, errors = schema.load({'field_a': 2, 'field_b': 12})

#2
# passes (i.e. field_a not passed and schema validates)
schema = AdamSchema()
result, errors = schema.load({'field_b': 12})

#3
# fails (i.e. field_a passed as None and schema doesn't validate)
schema = AdamSchema()
result, errors = schema.load({'field_a': None, 'field_b': 12})


#possible solution via @pre_load and @post_load

from marshmallow import Schema, pre_load, post_load

class AdamSchema2(Schema):
    field_a = fields.Integer(required=False, 
                             validate=lambda n: n is None or n > 40)
    field_b = fields.Integer()

    @pre_load
    def remove_nones(self, in_data):
        "get rid of fields set to None that may not validate correctly"
        self.nones = []
        for key in in_data.keys():
            if in_data[key] is None:
                self.nones.append(key)
                del in_data[key]
        return in_data


    @post_load
    def replace_nones(self, item):
        "put back in the None fields, so serialized_output = expected_output"
        for key in self.nones:
            item[key] = None
        return item

schema = AdamSchema2()
result, errors = schema.load({'field_a': None, 'field_b': 12})
# passes (no validation errors)
```

**Comment by sloria** [comment]
If you pass `allow_none=True` to a field, `None` will be considered a valid value. Does this meet your use case?

**Comment by ammurphy** [comment]
Yes, it does.  I should have rtfm before coding up a work around.

Thanks.
