### ISSUE TITLE
Missing source distribution for v2.7.1 on PyPI

### ISSUE THREAD

**Issue by dgilland** [marshmallow-code/marshmallow#443]
Currently on PyPI, there is no source dist for v2.7.1 (only wheel): https://pypi.python.org/pypi/marshmallow/2.7.1

![screenshot from 2016-04-27 18 31 05](https://cloud.githubusercontent.com/assets/1251349/14870154/55edbf8a-0ca6-11e6-91e7-869be1e2275c.png)

But there is a source dist for v2.7.0: https://pypi.python.org/pypi/marshmallow/2.7.0

![screenshot from 2016-04-27 18 37 21](https://cloud.githubusercontent.com/assets/1251349/14870257/1ce92084-0ca7-11e6-9118-cca18b8cc235.png)

I use my package's `setup.py` file to run tests via `python setup.py test` using `setuptools.setup`. However, for whatever reason because there is no source dist for v2.7.1, setuptools is unable to find a suitable distribution for `marshmallow==2.7.1`. When I specify `marshmallow==2.7.0`, setuptools is able to install it without issue.

So my questions are:
1. Was it intentional to not include a source dist release with 2.7.1?
2. If it was intentional and going forward there will be no more source dist releases, do you know of a way to make setuptools find wheels when it installs dependencies during `python setup.py test`?

**Comment by sloria** [comment]
It was not intentional. Unfortunately, PyPI was having problems with sdist uploads when 2.7.1 was released: https://github.com/pypa/packaging-problems/issues/83 . Future releases will have source dists. I'll go ahead and upload a new version--this one _should_ have an sdist.

**Comment by sloria** [comment]
Success! 2.7.2 has an source dist.

**Comment by dgilland** [comment]
Awesome! Thanks! :+1:
