### ISSUE TITLE
sqlalchemy marshmallow avoid loading data into session

### ISSUE THREAD

**Issue by ShankarGanesh** [marshmallow-code/marshmallow#445]
Is there a way to avoid inserting the data into session while using Marshmallow - sqlalchemy .load()

Because we tried to manage the objects by ourself (adding them into session if required) . Will add into the session if required , but for only validation I need to use load () method which is provided by marshmallow-sqlalchemy

Load Code for marshmallow-sqlalchemy

def load(self, data, session=None, instance=None, _args, *_kwargs):
        """Deserialize data to internal representation.
        :param session: Optional SQLAlchemy session.
        :param instance: Optional existing instance to modify.
        """
        self.session = session or self.session
        self.instance = instance or self.instance
        if not self.session:
            raise ValueError('Deserialization requires a session')

**Comment by sloria** [comment]
Please do not post duplicates of marshmallow-sqlalchemy-related issues here. https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/62
