### ISSUE TITLE
Missing OpenAPI Validators

### ISSUE THREAD

**Issue by deckar01** [marshmallow-code/marshmallow#448]
The following OpenAPI validators have no corresponding validator in marshmallow:

| Marshmallow Validator | OpenAPI Validator |
| --- | --- |
|  | exclusiveMinimum |
|  | exclusiveMaximum |
|  | uniqueItems |
|  | multipleOf |

Encountered when mapping marshmallow validators for OpenAPI in https://github.com/marshmallow-code/apispec/issues/66.

I could see this being implemented as custom marshmallow validators in `apispec`, but I am curious if it is within scope for marshmallow to support an equivalent set of OpenAPI validators.

**Comment by sloria** [comment]
Closing this for now. Let's hold off on adding these validators to marshmallow core for now. If someone wants to send a PR adding these to apispec, I would gladly review and merge.
