### ISSUE TITLE
Poor validator inheritance

### ISSUE THREAD

**Issue by deckar01** [marshmallow-code/marshmallow#455]
The inheritance model for [`Range`](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/validate.py#L159) and its subclass [`Length`](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/validate.py#L201) does not seem semantically valid. This issue arose when [attempting to differentiate the two](https://github.com/marshmallow-code/apispec/pull/73) by duck typing the validators.

`Length` is not really a type of `Range`. `Range` validates numbers, and `Length` validates sequences and collections. This indicates that their domains are disjoint.

It would be more appropriate for the `Length` validator to have an attribute named something like `lengthRange` which is an instance of the `Range` validator.

This issue is equivalent to extending an `Engine` class to create a `Car` class. A `Car` has an `Engine`, but it is not a type of `Engine` itself.

**Comment by sloria** [comment]
I agree. This was an oversight.

This change could technically break users' code, so this will probably have to go in 3.0. That said, I would welcome PR!

**Comment by deckar01** [comment]
#458 keeps the class interface the same so the only user code that could break is `isinstance(validator.Length(), validator.Range)` is now `False`.

**Comment by sloria** [comment]
Thanks @deckar01 . While the change is minimal, it's a potentially breaking change nonetheless. I'll go ahead and merge it into the 3.0 branch for now.

**Comment by deckar01** [comment]
@sloria Thanks for reviewing the PR.

Closing this issue since #458 was [merged into the `3.0` branch](https://github.com/marshmallow-code/marshmallow/commit/dc59cd729d964445fdc27ce77a11d228056abc6b).
