### ISSUE TITLE
Partial loading issues

### ISSUE THREAD

**Issue by krodyrobi** [marshmallow-code/marshmallow#456]
``` python
class VolumeAttributeSchema(Schema):
    class Meta:
        ordered = True

    reserved_size = fields.Integer(required=True, validate=[validate.Range(min=0)])
    constraints = fields.List(fields.String(validate=[validate.Length(min=1)]), required=True)


class PackerSchema(Schema):
    class Meta:
        ordered = True

    state = fields.String(default='registered', missing='registered')
    name = fields.String(default='', missing='registered')
    error = fields.String(default='', missing='')
    error_count = fields.Integer(default=0, missing=0)

    meta = fields.Dict(default={}, missing={})

    actual = fields.Nested(VolumeAttributeSchema, required=True)
    requested = fields.Nested(VolumeAttributeSchema, required=True)


class VolumeSchema(PackerSchema):
    class Meta:
        ordered = True

    id = fields.String(required=True)

    def get_attribute(self, attr, obj, default):
        if attr != 'id':
            return utils.get_value(attr, obj.unpacked_value, default)

        etcd_key = super(VolumeSchema, self).get_attribute('key', obj, default)
        id = Volume.get_id_from_key(etcd_key)

        return id


data = {
    "name": "test",
    "state": "blah",
    "error": "asdfadsf",
    "error_count": 1,
    "meta": {
        "test": 1
    },
    "actual": {
        "reserved_size": 1,
        "constrants": ["test"]
    },
    "requested": {
        "reserved_size": 2,
        "constrants": ["test2"]
    }
}

volume, errors = volume_schema.load(data, partial=('name', 'meta', 'requested',))
print(volumes)
#OrderedDict([('state', 'blah'), ('name', 'test'), ('error', 'asdfadsf'), ('error_count', 1), ('meta', {'test': 1}), ('actual', OrderedDict([('reserved_size', 1), ('constraints', [])])), ('requested', OrderedDict([('reserved_size', 2), ('constraints', [])]))])
print(errors)
#{'id': ['Missing data for required field.']}
```

I'd expect that the volumes dict not to contain anything else that is not specified in `partial`.
And that the id should not be validated.

Note: version used marshmallow==2.7.3

**Comment by krodyrobi** [comment]
The get_attribute can be removed as I needed it for something else. The issue still remains.

**Comment by sloria** [comment]
Try using the `only` parameter, which is used for specifying which subset of fields you want to (de)serialize. `partial` is used for switching off required validation.

**Comment by krodyrobi** [comment]
I've retested and re-read the api and it seems I've inverted the logic for the partial parameter -> it specifies which fields to ignore not which fields to accept :D, my bad.

Also noticed that `only` can only be set at a schema level maybe it would be practical to have it like `partial`?

And a final question: How could I reference a field in `partial`, `only` using something like `nested.field` and have it ignored, field only and not the entire group or this isn't currently possible?

Thanks for the assistance, much appreciated!

**Comment by sloria** [comment]
> Also noticed that only can only be set at a schema level maybe it would be practical to have it like partial?

`Schema.__init__` parameters are the preferred way to configure a schema at runtime. `many` and `partial` are included in the signature for `load`/`dump` for convenience, but I'd rather not add all `__init__` parameters to load/dump.

> How could I reference a field in partial, only using something like nested.field and have it ignored, field only and not the entire group or this isn't currently possible?

Are you referring to something like the proposed API in https://github.com/marshmallow-code/marshmallow/pull/405?

**Comment by krodyrobi** [comment]
Yes a dot notation would be wonderful, but any other implementation would work as well.

**Comment by krodyrobi** [comment]
Is the `load` function only working on dicts? as I can't get it to work with an object.
`PackerSchema` / `VolumeSchema` are the ones in the previous message.

``` python
class Test:
  def __init__(self):
    self.key = '/volumes/1'
    self.unpacked_value = {
      "name": "ok",
      "requested": {
        "reserved_size": 10,
        "constraints": []
      },
      "actual": {
         "reserved_size": 2,
         "constraints": []
      },
      "meta": {
          "instance.name": "test_instance"
      }
   }

test = Test()
expected, errors = VolumeSchema().load([test], many=True)
print(errors)
# {0: {}, '_schema': ['Invalid input type.']}
expected, errors = PackerSchema().load([test.unpacked_value], many=True)
# This ones ok
```

**EDIT**

``` python
from marshmallow import Schema, fields


class As(Schema):
  test = fields.Integer()

class test:
  def __init__(self, a):
    self.test = a


t = test(1)

data, errors = As().load([t], many=True)
print('load', type(data), data, errors)
data, errors = As().load([{'test': 1}], many=True)
print('load dict', type(data), data, errors)
data, errors = As().loads('[{"test": 1}]', many=True)
print('loads', type(data), data, errors)
data, errors = As().dump([t], many=True)
print('dump', type(data), data, errors)
data, errors = As().dump([{'test': 1}], many=True)
print('dump dict', type(data), data, errors)
data, errors = As().dumps([t], many=True)
print('dumps', type(data), data, errors)

# Results:
# load <class 'list'> [{}] {0: {}, '_schema': ['Invalid input type.']}
# load dict <class 'list'> [{'test': 1}] {}
# loads <class 'list'> [{'test': 1}] {}
# dump <class 'list'> [{'test': 1}] {}
# dump dict <class 'list'> [{'test': 1}] {}
# dumps <class 'str'> [{"test": 1}] {}
```

I'm not quite sure if this is what is expected:

```
Schema.load(data, many=None, partial=None) ->
Deserialize a data structure to an object defined by this Schema’s fields and make_object()
```

A python object is a data structure :D, maybe further clarification is needed, or I'm just not thinking straight. 

```
Schema.dump(obj, many=None, update_fields=True, **kwargs)
Serialize an object to native Python data types according to this Schema’s fields.
```

**Comment by sloria** [comment]
Yes, `load` expects a `dict` as input. From the [docs](https://marshmallow.readthedocs.io/en/latest/quickstart.html#deserializing-objects-loading):

> The opposite of the dump method is the load method, which deserializes an input dictionary to an application-level data structure.

Perhaps this needs to be made more clear in the docs. I'd certainly accept a docs PR =).

If you need to deserialize an object, you can use a [@pre_load](https://marshmallow.readthedocs.io/en/latest/extending.html#extending-schemas) method which takes your object as input and outputs a dictionary representation of it.
