### ISSUE TITLE
skip_on_fields_errors doesn't work for validates_schema

### ISSUE THREAD

**Issue by martinstein** [marshmallow-code/marshmallow#461]
Here's a simple test case to reproduce the problem based on the example in the docs

``` python
from marshmallow import Schema, fields, validates_schema, ValidationError

class NumberSchema(Schema):
    field_a = fields.Integer()
    field_b = fields.Integer()

    @validates_schema
    def validate_numbers(self, data, skip_on_field_errors=True):
        if data['field_b'] >= data['field_a']:
            raise ValidationError('field_a must be greater than field_b')

schema = NumberSchema()
result, errors = schema.load({'field_a': 2, 'field_b': "bbbb"})
```

The `validate_numbers` method should be skipped because validation of `field_b` fails (since field_b contains a string). However, it is not skipped (which of course causes problems since that method expects `data['field_b']` to exist).

**Comment by martinstein** [comment]
I feel like I'm missing something trivial here. This is literally just the example from the docs with `skip_on_field_errors` added, so this should work. Can anybody reproduce the problem?

**Comment by sloria** [comment]
Make sure you are passing `skip_on_field_errors=True` to the decorator, not to the method.

**Comment by martinstein** [comment]
Ha, you're right. Clear case of PEBKAC on my side. Thanks for the fast reply!
