### ISSUE TITLE
Time field wrong result with microseconds

### ISSUE THREAD

**Issue by Archelyst** [marshmallow-code/marshmallow#464]
I have a schema with a `Time` field. When it serializes a value with microseconds, e.g. `2016-05-27T11:02:35.267899`, it results in  `2016-05-27T1`.

The reason are those lines:

```
if value.microsecond:
    return ret[:12]
```

https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L911

I have no idea what your idea was behind that, @sloria . `ret[:19]` would do it in my case, don't know if there might be other cases.

**Comment by sloria** [comment]
Certainly looks like a bug. I'd gladly review and merge a PR fixing this.
