### ISSUE TITLE
Method fields with allow_none=False should be absent from serialization

### ISSUE THREAD

**Issue by Epitrochoid** [marshmallow-code/marshmallow#467]
I'm working on a json schema serializer and an issue that I keep running into is that a method field returning 'None' serializes to 'null' even with allow_none set to false.

``` Python
class TestSchema(Schema):
    test_field = fields.Method('test_method', allow_none=False)

    def test_method(self, obj):
        pass

> s = TestSchema()
> s.dump('')
# Result currently returned
MarshalResult(data={u'test_field': None}, errors={})
# Result expected
MarshalResult(data={}, errors={})
```

Currently I am getting around the issue by including 'delattr(self, 'field')' in the method, but it feels a bit hacky.

**Comment by sloria** [comment]
`allow_none` applies to deserialization (`load`), not serialization (`dump`). If you want to validate on serialization, you can raise a `ValidationError` in the method for the field.
