### ISSUE TITLE
[feature] Schema-level validation

### ISSUE THREAD

**Issue by philtay** [marshmallow-code/marshmallow#47]
- I couldn't find any way to do Schema level validation in the docs. I mean something to do the sort of validations that involve multiple fields (e.g. if field A is less than 10 then field B must be greater than 50). Any suggestion?
- I found Schema.data_handler for data post-processing. Is there something for data pre-processing? For instance: remove all the spaces from a string before validation, or more generally, apply a function to the data before validation (but after deserialization).

Thanks

**Comment by sloria** [comment]
> I couldn't find any way to do Schema level validation in the docs.

Currently, there isn't built-in support for schema-level validation, but I think it would be a useful feature. I imagine the API would be similar to the `error_handler` and `data_handler`. Something like:

``` python
@MySchema.validator
def validate_schema(schema_obj, input_values):
    if input_values['A'] < 10:
        return input_values['B'] > 50
    return True
```

> I found Schema.data_handler for data post-processing. Is there something for data pre-processing? ..or more generally, apply a function to the data before validation (but after deserialization)

Just for clarification: validation occurs upon deserializing an object, so why do you say the preprocessing function would be applied _after_ deserialization? It would necessarily have to be applied before deserializing the object, though I may be misunderstanding your question.

**Comment by philtay** [comment]
> Currently, there isn't built-in support for schema-level validation, but I think it would be a useful feature.

It would be better to have the schema validation method directly in the schema's class. The decorator could be left as an option.

> Just for clarification: validation occurs upon deserializing an object, so why do you say the preprocessing function would be applied after deserialization?

I mean:

JSON -> Python object -> pre-processing -> validation

**Comment by sloria** [comment]
As with `error_handler` and `data_handler`, validation functions could be registered using a decorator _or_ as class members. http://marshmallow.readthedocs.org/en/dev/extending.html#error-handlers-and-data-handlers-as-class-members 

This pattern would allow multiple validation functions to be registered, if necessary.

Re: preprocessing after deserialization:  There is a discussion on #45 about whether to do validation upon serializing an object. Do you have a use case for validating your app-level Python object after it has been validated on deserialization? Perhaps the preprocessing should occur before deserializing.

```
JSON -> preprocessing -> validation -> Python object
```

Thank you for your feedback.

**Comment by philtay** [comment]
Validation is useful only on deserialization. There is no need to validate something that must be already valid by construction.

Probably we are talking about the same thing but using different words. For Python objects I don't mean app-level objects, but the objects you get using simplejson or built-in json.
For instance, you have this JSON:

``` json
{
  'foo': 'bar',
  'moo': 5
}
```

The Python object I'm talking about is the dictionary you get with json.load, i.e.:

``` python
>>> my_dict = {'foo':'bar', 'moo':5}
```

As soon as you have my_dict you will pass it to the pre-processor method (or methods if you have both field level and schema level pre-processors).
Now, pretend your pre-processor method changes 'moo' from 5 to 10 and your dict will be:

``` python
>>> my_dict = {'foo':'bar', 'moo':10}
```

You can now pass my_dict to the validation methods (both field and schema level). If the validation succeeds you can pass my_dict to the make_object method and your app-level Python object will be created.

**Comment by sloria** [comment]
Thank you for the clarification. Indeed, we were thinking the same thing: apply preprocessing functions before validating and before deserializing.

I will work on prototyping these ideas once I do some reworking of the validation code (which will be soon).

**Comment by sloria** [comment]
@philtay Both schema-level validation and pre-processing have been added as of 7f231840a6aa1520d. See the docs here: http://marshmallow.readthedocs.org/en/dev/extending.html

Thanks for your suggestions!

**Comment by philtay** [comment]
Thank you for implementing it so quickly. This library could become the standard de facto for (de)serialization. A complete and friendly library to do this is currently lacking in the Python world.

For schema-level validation to be perfect we need:
- ability to set a custom error message in errors['_schema'] instead of the default one
- ability to attach a custom error message to a specific field instead of putting it in errors['_schema']
- errors['_schema'] should support multiple errors messages (coming from different schema level validation methods). i.e. it should be a nested dictionary

**Comment by sloria** [comment]
Thank you for your continued feedback.

> ability to set a custom error message in errors['_schema'] instead of the default one

I have been considering dallowing validation functions to return either a boolean or raise a ValidationError with a custom error message.

``` python
@MySchema.validator
def validate_schema(schema, data):
    if data['start_date'] and data['end_date'] < data['start_date']:
        # Custom message will be stored on `errors['_schema']`
        raise ValidationError('End date must be after start date.')
    return True
```

This would obviate the need for the `Field.error` attribute.

---

> ability to attach a custom error message to a specific field instead of putting it in errors['_schema']

One possibility would be to change the `__validators__` class attribute to be a dictionary with field names keyed to a list of validation functions and allow `Schema.validator` to take an optional `field_name` argument.

``` python
class MySchema(Schema):
    __validators__ = {'start_date': [validate_dates], '_schema': [validate_schema]}
    # ...

# OR, equivalently 

@MySchema.validator('start_date')
def validate_dates(schema, data):
     # ...

@MySchema.validator()
def validate_schema(schema, data):
    # ...
```

---

> errors['_schema'] should support multiple errors messages (coming from different schema level validation methods). i.e. it should be a nested dictionary

I agree that the errors dict should be able to handle multiple errors per field. However, why a nested dictionary rather than a list of error messages? What would the nested dictionary be keyed on?

**Comment by philtay** [comment]
> I have been considering dallowing validation functions to return either a boolean or raise a ValidationError with a custom error message.

Good. Note that you don't need to return a boolean. If the validation function doesn't raise an exception then the validation is considered successful. It doesn't matter what the function returns.

> allow Schema.validator to take an optional field_name argument

Uhm, no. Implement it in the ValidationError exception. raise ValidationError('my error message', 'my_field')

> However, why a nested dictionary rather than a list of error messages? What would the nested dictionary be keyed on?

Key it to the name of the validation function. It's useful to know what is the validator that caused the error. It would come handy in several occasions, especially to implement client side validation errors logic. E.g. you pass the errors dictionary as a JSON object to frameworks like AngularJS or Ember.

**Comment by sloria** [comment]
> Implement it in the ValidationError exception.

I don't much like the idea of having the `ValidationError` define where it's message gets stored. However, I do see the advantage that a single validation function would be able to store different errors on different fields.

> Key it to the name of the validation function.

Possibly, but what about unnamed functions? Also, what happens if two validators share the same name?

**Comment by philtay** [comment]
> I don't much like the idea of having the ValidationError define where it's message gets stored.

Well, ValidationError is where you define your error message, so it just makes sense to specify in the same place where it will get stored. However it doesn't matter so much where you specify it, the important thing is that you can, somewhere.

> Possibly, but what about unnamed functions? Also, what happens if two validators share the same name?

This is a classic case of one size doesn't fit all. You could give the optional opportunity to specify a key for each validator (here a decorator would perfectly fit). If there are duplicate names raise an exception. Generate a name yourself if one is missing (like '_missing1', '_missing2', etc.) and maybe spit out a warning. However these are edge cases, a clean application won't face these problems.

**Comment by sloria** [comment]
Validation functions are now expected to raise a `ValidationError` with the message that is to be stored in the `errors` dictionary, as described in previous comments.

I think specifying field names on the ValidationError is a fine solution. I will implement this soon.

Keying errors on function names complicates the common use case, where the user wants to iterate over all the errors for a given field. It would also complicate the validation API and add complexity to internal APIs. I have decided not to add this functionality at this moment.

**Comment by philtay** [comment]
> I think specifying field names on the ValidationError is a fine solution. I will implement this soon.

Thanks.

> I have decided not to add this functionality at this moment.

Ok, just keep in mind this is something you can't implement later without breaking backward compatibility.

**Comment by sloria** [comment]
> I have been considering dallowing validation functions to return either a boolean or raise a ValidationError with a custom error message.

---

> I think specifying field names on the ValidationError is a fine solution.

The above features have been implemented and are now on the `dev` branch. Closing this issue, as the original issue has been addressed.
