### ISSUE TITLE
question: why is post_load not called during Schema.loads?

### ISSUE THREAD

**Issue by iainctduncan** [marshmallow-code/marshmallow#470]
If I have a post_load method, it appears to get called as I expect during Schema.load, but not if calling Schema.loads. Is this intended? And if so, can anyone tell me why for better understanding? 

I realize I can do a second pass, but am not sure if that's the intended use.
thanks

**Comment by sloria** [comment]
That is certainly not the intended behavior. Can you please post a code snippet to reproduce the bug?

**Comment by iainctduncan** [comment]
Ah my mistake, I was confused by the behaviour of validation failing when not strict and now see that in one case validation was failing, so post_load was not being called. I see I need to add strict=True to get the validation behaviour I was thinking of. thanks!
