### ISSUE TITLE
question: marshmallow equiv of if_missing and if_empty?

### ISSUE THREAD

**Issue by iainctduncan** [marshmallow-code/marshmallow#471]
Perhaps I just haven't been able to find it in the docs. Is there a marshamallow equiv of formencode's if_missing and if_empty args? I found these really useful in some cases. For example, right now I want to say that 'id' must be an int, but if it's empty string in the incoming submission, use and accept the value of None. Is that possible with Marshmallow? Marshmallow looks great so far, really happy to find it.

**Comment by sloria** [comment]
You can use a custom field that accepts empty strings as input. From https://github.com/marshmallow-code/marshmallow/issues/583#issuecomment-285249535 : 

```python
from marshmallow import Schema, fields

class StrInt(fields.Int):

    def _deserialize(self, value, attr, data):
        if value == '':
            if not self.allow_none:
                self.fail('null')
            return None
        return super()._deserialize(value, attr, data)

class MySchema(Schema):
    id = StrInt(allow_none=True)


schema = MySchema(strict=True)

print(schema.load({'id': ''}).data)  # {'id': None}
```

**Comment by iainctduncan** [comment]
Thanks! Marshmallow is awesome btw. I love having a framework agnostic sqlalchemy friendly layer that can go in any python context. :)
