### ISSUE TITLE
Allow errors to be created in post processors

### ISSUE THREAD

**Issue by dbertouille** [marshmallow-code/marshmallow#472]
First a little bit of background in case there is a better way to do this. I'm working with marshmallow, sqlalchemy and marshmallow-sqlalchemy. I'd prefer to have validation done when creating the sqlalchemy models since that is where the fields are defined. The marshmallow schemas are simply using the ModelSchema from marshmallow-sqlalchemy to dynamically populate the fields.

Perhaps we could optionally pass a reference of the errors dictionary to post processors so that they could populate it with validation (or other) errors. 

Thoughts?

**Comment by sloria** [comment]
Raising validation errors in a pre/post-processor is certainly a valid use case. I would certainly review and merge a PR for this.
