### ISSUE TITLE
How to use different nested schema based on a condition?

### ISSUE THREAD

**Issue by norbertpy** [marshmallow-code/marshmallow#473]
Imagine I have 3 different Schemas. `Parent`, `ChildA` and `ChildB`. I'm using the parent schema to serialize its child. How can I tell parent schema to use different schema for child based on a property on parent? Like:

``` python
class Parent(Schema):
    code = fields.Str(required=True)
    child = fields.Nested(ChildASchema) # Here use ChildBSchema if "code" is "B"
```

**Comment by sloria** [comment]
Take a look at [marshmallow-polyfield](https://github.com/Bachmann1234/marshmallow-polyfield) ; it seems like it would fit your use case.
