### ISSUE TITLE
[Question] Many-to-many relationships

### ISSUE THREAD

**Issue by smheidrich** [marshmallow-code/marshmallow#481]
Is there a standard way to handle many-to-many Python object relationships with this library? Nested fields obviously won't work because they would create duplicate objects where you want just one object that is referred to by several others.

It is possible to handle this manually, for example by using some sort of unique `key` (or `name` or `id`) field and translating lists of objects into lists of these keys, but this is kind of awkward.

I'm thinking of something like a `Linked` field type that works like the `Nested` one, except it doesn't lead to the construction of anything and only validates that the linked object exists - sorry, I don't know enough about the library to assess whether this is possible at all. In the output dictionary, the link could be represented by the method I mentioned above.

Thank you in advance for your input.

**Comment by sloria** [comment]
@smheidrich This feature is best left to other libraries or your application code. marshmallow-json does something close to what I think you're describing. See https://marshmallow-jsonapi.readthedocs.io/en/latest/quickstart.html#compound-documents .

**Comment by smheidrich** [comment]
@sloria The ``Relationship`` field from that library definitely looks very close to what I wanted, I'll look into it, thank you very much!
