### ISSUE TITLE
`Eqaul(False)` can't validate correctly

### ISSUE THREAD

**Issue by pktangyue** [marshmallow-code/marshmallow#484]
```
online = fields.Bool(required=True, attribute='active', validate=Equal(False))
```

I add this field to my Schema to accept a `False` value, but when I pass a `False`, it will raise `{'online': [u'Invalid value.']}` error.

**Comment by sloria** [comment]
Thanks @pktangyue for reporting. This seems to be a bug. I would gladly review and merge a PR for this!
