### ISSUE TITLE
Provide a default method name for the `Method` field

### ISSUE THREAD

**Issue by kevinlondon** [marshmallow-code/marshmallow#485]
I love using Marshmallow and, in many ways, it reminds me of working with Django Rest Framework. One area where they differ is that DRF offers a default method name for Method fields, which reduces the boilerplate needed.

Could we specify a default value of `get_{field_name}` for Method fields, as in DRF?
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1609

For example, it would change definitions from something like `my_field = fields.Method('get_my_field')` to `my_field = fields.Method()`.

Would you like me to prepare a PR with this?

**Comment by sloria** [comment]
Thanks for the suggestion. I am aware of that API in DRF, but I do not like the implicitness of a default method name. Explicitly specifying the name of the method makes the code much more readable.
