### ISSUE TITLE
debian package

### ISSUE THREAD

**Issue by alvesadrian** [marshmallow-code/marshmallow#486]
Hello Steve,
am trying to build a debian pkg and am getting this error:
writing manifest file 'marshmallow.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 63, in <module>
    test_suite='tests'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_utils'
E: pybuild pybuild:274: test: plugin distutils failed with: exit code=1: python2.7 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 2.7 returned exit code 13
debian/rules:9: recipe for target 'build' failed
make: **\* [build] Error 25

**Comment by deckar01** [comment]
@alvesadrian I am new to building debian packages. I am unable resolve an issue finding `debhelper` on openSUSE. It occurs just before "running build_ext".

```
dpkg-query: no packages found matching debhelper
ERROR running: /usr/bin/dpkg-query --show --showformat=${Version} debhelper
```

I have `9.20150101-1.4` installed, but there is a previous warning that seems to suggest it is expecting version 7.

```
WARNING: a Makefile exists in this package. stdeb will tell debhelper 7 to use setup.py to build and install the package, and the Makefile will be ignored.
```

Sorry that I am not much help.

**Comment by asmodehn** [comment]
I am also trying to build a package, specifically for http://www.ros.org/ since it s what I need right now, and since there is no deb package on ubuntu yet. My attempt is [there](https://github.com/asmodehn/marshmallow-rosrelease) (using git-buildpackage + some custom ROS tools ) 
So I am also interested to help a bit here...

I am wondering which tools you are using to build a deb ? 
There are the (nice user friendly) options I am aware about : 
- [git-buildpackage](https://wiki.debian.org/PackagingWithGit)
- [fpm](https://github.com/jordansissel/fpm)

Maybe they can make the job a bit easier ?

**Comment by alvesadrian** [comment]
@asmodehn i have a prototype working can you contact me at aalves(at)gmail(dot)com
if you need the deb right away

**Comment by asmodehn** [comment]
@alvesadrian No worries, my deb package also works for my use case.

What I meant, is that if the deb was included in ubuntu, I wouldnt have to build it for ROS.

**Comment by adrian-gluu** [comment]
send me yours so i can compare it with mine for debian if you want course

**Comment by adrian-gluu** [comment]
@asmodehn send me yours so i can compare it with mine for debian if you want course

**Comment by alvesadrian** [comment]
@asmodehn send me your deb changes so i can compare it with my for debian, if you can course it will be a good practice in case i miss something to include it in debian repos

**Comment by asmodehn** [comment]
The deb files generated by ROS tools are there : https://github.com/asmodehn/marshmallow-rosrelease/tree/debian/indigo/trusty/python-marshmallow?files=1

But usually these are not following debian guidelines ( for some complex reason ), so it might not be a good reference.

For testing if your package is somehow standard you should probably test it on travis : http://travis.debian.net
