### ISSUE TITLE
No ValidationError on invalid data

### ISSUE THREAD

**Issue by incognick** [marshmallow-code/marshmallow#487]
Given the following schema, how can I raise a validation error without knowing the invalid argument specified?  

``` python
from marshmallow import Schema, fields

class TestSchema(Schema):
    name = fields.String()

    class Meta:
        strict = True

schema = TestSchema()
data = schema.load({'invalid_argument': 5})
print(data)
```

Outputs:

``` bash
UnmarshalResult(data={}, errors={})
```

**Comment by incognick** [comment]
Actually, I see how this can be accomplished from the docs. Would you merge a PR that would provide this functionality via the Meta class such as "ignore_invalid"?

**Comment by sloria** [comment]
Yes, you can use `@validates_schema(pass_original_True)` for this. An example is in https://github.com/marshmallow-code/marshmallow/issues/273:

``` python
class MySchema(Schema):
    foo = fields.Int()
    bar = fields.Int()

    @validates_schema(pass_original=True)
    def check_unknown_fields(self, data, original_data):
        for key in original_data:
            if key not in self.fields:
                raise ValidationError('Unknown field name', key)
```

I'd rather leave it up to the user to implement this rather than supporting in marshmallow core.

**Comment by incognick** [comment]
Sounds good. Thanks
