### ISSUE TITLE
Field value incorrect with many=True option.

### ISSUE THREAD

**Issue by ScottSturdivant** [marshmallow-code/marshmallow#49]
Hi there,

First let me apologize by stating that my attempts to create a small, reproducible example have failed.  I'm hoping to instead provide examples of what I'm seeing and perhaps you'll be able to tell me what I'm doing incorrectly!

Serialize two items of a list, individually:

```
(Pdb) EventSerializer(events[0]).data
OrderedDict([('event_id', 11), ('index', None), ('contact_id', 1), ('profile_id', None), ('action', 'updated'), ('type', 'contact')])
(Pdb) EventSerializer(events[1]).data
OrderedDict([('event_id', 13), ('index', None), ('contact_id', None), ('profile_id', 2),('action', 'added'), ('type', 'profile')])
```

Notice how the 'contact_id' key is 1 in the first, and None in the second.  This is as I'd expect.  Now, when I serialize the entire list as a whole:

```
(Pdb) EventSerializer(events, many=True).data
[OrderedDict([('event_id', 11), ('index', None), ('contact_id', 1), ('profile_id', None),  ('action', 'updated'), ('type', 'contact')]), OrderedDict([('event_id', 13), ('index', None), ('contact_id', 0), ('profile_id', 2), ('action', 'added'), ('type', 'profile')])]
```

Notice that now the 'contact_id' of the second list element is now 0 and not None.  Odd!

My serializer definition looks like this:

```
class EventSerializer(Serializer):
    action = fields.Method('action_to_text')
    type = fields.Method('type_to_text')
    event_id = fields.Integer(attribute='id')

    class Meta:
        fields = ['event_id', 'action', 'profile_id', 
                  'index', 'contact_id', 'type']

    def action_to_text(self, obj):
        return ActionType.to_text(obj.action)

    def type_to_text(self, obj):
        return EventType.to_text(obj.type)
```

I'm probably missing something obvious...

Thank you for your time!

**Comment by sloria** [comment]
Odd indeed. Do you see the correct output when you explicitly specify the field type for `contact_id`?

``` python
class EventSerializer(Serializer):
    action = fields.Method('action_to_text')
    type = fields.Method('type_to_text')
    event_id = fields.Integer(attribute='id')
    contact_id = fields.Integer()
    # ...
```

**Comment by ScottSturdivant** [comment]
Unfortunately, no, the second element still has `0` instead of `None` even when explicitly specifying the field type.

**Comment by sloria** [comment]
What type of object is an `event`?

**Comment by ScottSturdivant** [comment]
Hi there,

Thanks for your patience, I was able to come up with a simple example that demonstrates the problem. 

```
class Foo(object):
    def __init__(self, id, other):
        self.id = id
        self.other_id = other

 class FooSerializer(Serializer):
     class Meta:
         fields = ['id', 'other_id']
```

Serialized singularly, with 'other_id' not set:

```
>>> FooSerializer(Foo(1,None)).data
OrderedDict([('id', 1), ('other_id', None)])
```

When multiple, with 'other_id' set in one, but not in another:

```
>>> lots_of_foo = [Foo(1,1), Foo(1,None)]
>>> FooSerializer(lots_of_foo, many=True).data
[OrderedDict([('id', 1), ('other_id', 1)]), OrderedDict([('id', 1), ('other_id', 0)])]
```

For what it's worth, changing the order (putting the instance with None in it first), results in correct serialization:

```
>>> lots_of_foo = [Foo(1,None), Foo(1,1), Foo(2,None)]
>>> FooSerializer(lots_of_foo, many=True).data
[OrderedDict([('id', 1), ('other_id', None)]), OrderedDict([('id', 1), ('other_id', 1)]), OrderedDict([('id', 2), ('other_id', None)])]
```

Hope that you're able to reproduce and that it helps track it down!

Thanks!

**Comment by ScottSturdivant** [comment]
Sorry, here's an update with an even more simple example:

```
class Foo(object):
    def __init__(self, id):
        self.id = id

class FooSerializer(Serializer):
    class Meta:
        fields =['id']

 >>>  FooSerializer([Foo(None), Foo(1)], many=True).data
 [OrderedDict([('id', None)]), OrderedDict([('id', 1)])]

 >>> FooSerializer([Foo(1), Foo(None)], many=True).data
 [OrderedDict([('id', 1)]), OrderedDict([('id', 0)])]
```

**Comment by sloria** [comment]
Oh, I see now. When you use `Meta.fields` option without explicitly declaring a field on the class, there is no way for the Serializer to "know" what `Field` class to use for serializing `id` until you serialize the first object in the list.

When you use implicit field creation (i.e. `Meta.fields` with no explicit field declaration) together with `many=True`, the Serializer will inspect the first element of the list to serialize and choose which `Field` classes to use according to this mapping: https://github.com/sloria/marshmallow/blob/4e14f192ac478f0f0a46c671a53dc55fc5831c41/marshmallow/serializer.py#L113-127 .

Because the first `Foo` in the list has an `id` of `None`, the `Serializer` defaults to using the `Raw` field to format `id`.

The fix here is to use _explicit_ field declaration for the `id` field.

``` python
from marshmallow import Serializer, fields

class Foo(object):
    def __init__(self, id):
        self.id = id

class FooSerializer(Serializer):
    id = fields.Integer()
    class Meta:
        fields =['id']

FooSerializer([Foo(None), Foo(1)], many=True).data
# [OrderedDict([('id', 0)]), OrderedDict([('id', 1)])]
```

Hope that helps!

**Comment by ScottSturdivant** [comment]
Hey, sorry for being a bit slow here, but even in that case, it's not giving the result I might expect (that the value for 'id' in the first element is `None`, not `0`.

My real class looks like:

``` python
class Event(db.Model):
    id = db.Column(db.Integer, nullable=True)
```

Since I didn't declare an explicit field type, and because of the ordering of my data, it chose a 'Raw' field type.  But it really is an Integer, and is nullable, and instead of returning 0, I'd like it to just return None.

Should I just make my own NullableInteger field type?

``` python
class NullableInteger(fields.Raw):
    def format(self, value):
        if value is None:
            return value
        return int(value)

class FooSerializer(Serializer):
    id = NullableInteger()
    class Meta:
        fields =['id']

FooSerializer([Foo(None), Foo(1)], many=True).data
# [OrderedDict([('id', None)]), OrderedDict([('id', 1)])]
```

Thanks...going ahead and closing this issue since it's definitely just my misunderstanding!

**Comment by sloria** [comment]
You should just be able to set `default=None` if you want `None` to serialize to `None`.

``` python
class FooSerializer(Serializer):
    id = fields.Integer(default=None)
    class Meta:
        fields =['id']
```

**Comment by ScottSturdivant** [comment]
Indeed, that works great.  Sorry for all of the noise!

**Comment by sloria** [comment]
No need to apologize. Happy I could help!
