### ISSUE TITLE
Add ability to exclude specific fields from fields.Dict during de-/serialization

### ISSUE THREAD

**Issue by traut** [marshmallow-code/marshmallow#494]
Some data structures are semi-defined, sitting in-between `fields.Dict()` and `fields.Nested()`. It would be helpful to be able to exclude specific fields by name from de-/serialization

**Comment by deckar01** [comment]
> **load_only (tuple)** – A list or tuple of fields to skip during serialization
> **dump_only (tuple)** – A list or tuple of fields to skip during deserialization

https://marshmallow.readthedocs.io/en/latest/api_reference.html#schema

Do these two `Schema` arguments satisfy your use case?

**Comment by traut** [comment]
@deckar01 I believe `dump_only`/`load_only` are `booleans` on the field level and using schema instead of `fields.Dict` is not always possible

**Comment by deckar01** [comment]
They are also lists attributes on the `Schema` `Meta` class that allow specifying the field names to skip.

Can you provide an example of when you have to use a `Dict` instead of a `Schema`?

**Comment by traut** [comment]
imagine I have schema

```
class Car(Schema):

    manufacturer = fields.String()
    metadata = fields.Dict()
```

`metadata` field here can have any keys/values inside.
Lets imagine that I need to write car records into a file but `car.metadata["owner_name"]` should never be serialized. How do I do that?
- `load_only` field for `fields.Dict` is boolean, so that will not help
- I can not define a schema for `metadata` because it can have any fields

**Comment by lafrech** [comment]
You could add a pre_dump or post_dump method to Car class to remove those fields.

**Comment by traut** [comment]
@lafrech I can but property in `fields.Dict` constructor would be much prettier, hence this request

**Comment by deckar01** [comment]
Only knowing the fields you want to exclude seems like an unusual use case. I would not recommend adding this functionality into the core `Dict` field. The nicer syntax you are looking for could be accomplished by subclassing `Dict`.

```py
class BlacklistedDict(fields.Dict):
    def __init__(self, blacklist, **kwargs):
        super(BlacklistedDict, self).__init__(**kwargs)
        self.blacklist = blacklist

    def _serialize(self, value, attr, obj):
        value = super(BlacklistedDict, self)._serialize(value, attr, obj)
        return {key: value[key] for key in value if key not in self.blacklist}

    def _deserialize(self, value, attr, obj):
        value = super(BlacklistedDict, self)._deserialize(value, attr, obj)
        return {key: value[key] for key in value if key not in self.blacklist}
```
