### ISSUE TITLE
Different date deserialisation behaviour when dateutil present

### ISSUE THREAD

**Issue by mafrosis** [marshmallow-code/marshmallow#497]
We ran into an issue with date deserialisation - which is different depending on the presence of `python-dateutil`.

Our API does not accept UK/US style date formats (eg. `13/12/2016` or `12/13/2016`). The `fields.Date`  [type](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L934]) says it only supports ISO8601 format, yet when `python-dateutil` is present it actually accepts ISO and the examples above.

I don't think this changing behaviour at runtime is A Good Thing. I suppose we could write our own strict ISO8601 validator?

Making `python-dateutil` required as in #349 would fix this - except for the misleading comments in `fields.Date`.

Thoughts?

**Comment by deckar01** [comment]
I'm not sure making `dateutil` a hard dependency would solve the problem. The date parsing utilities in marshmallow all accept an argument for enabling the use of `dateutil` and it defaults to true. Currently the `Date` field omits this argument during deserialization, but it seems like you want the ability to set this argument to false.

Another fix might be to change the offending marshmallow date utility method to match the docs.

**Comment by mafrosis** [comment]
> The date parsing utilities in marshmallow all accept an argument for enabling the use of `dateutil` and it defaults to true.

I'd say that this ought to be `False` by default, but that's now an API breaking change. If we had some way to set this to false ourselves, that would be my preferred solution. For example:

```
date_from = fields.Date(allow_none=True, no_dateutil=True)
```

**Comment by lafrech** [comment]
This is fixed in Marshmallow 3 because we rely on regexes (copied from Django) to validate the datetime / date / time strings before deserialization.

Besides, we don't use python-dateutil anymore (https://github.com/marshmallow-code/marshmallow/pull/1265).
