### ISSUE TITLE
doctests for Schema

### ISSUE THREAD

**Issue by asmodehn** [marshmallow-code/marshmallow#506]
I was struggling to get some Schema working as expected today, so I was thinking that it would be good to have an example in the doc somewhere that explains how to doctest a Schema.

It would be a quick way to check that the Schema is behaving as expected.

**Comment by maximkulkin** [comment]
Like writing unit tests?

``` python
import pytest  # Not actually needed but shows that we are using pytest test framework

def make_payload(foo='hello', bar=123):
    """Returns my schema payload. With default args
    returns valid schema. Fields can be customized."""
    return {'foo': foo, 'bar': bar}

def test_default_payload_is_valid():
    assert MySchema().validate(make_payload()) == {}

def test_requires_foo():
    errors = MySchema().validate(make_payload(foo=None))
    assert 'foo' in errors
```

**Comment by asmodehn** [comment]
I was thinking for something more documenting along the lines of : 

``` python
class TestSchema(Schema):
    """
    This schema can validate
    >>> sch = TestSchema()
    >>> sch.validate({'answer': 42})
    {}

    and (de)serialize from/to python objects
    >>> sch.loads('''{ "answer": 42}''')
    UnmarshalResult(data={'answer': 42}, errors={})
    >>> sch.load({ 'answer': 42})
    UnmarshalResult(data={'answer': 42}, errors={})
    >>> sch.dump({'answer': 42})
    MarshalResult(data={u'answer': 42}, errors={})
    >>> sch.dumps('''{ "answer": 42}''')
    MarshalResult(data='{}', errors={})
    """
    answer = fields.Int()
```

But I am not sure what is the best way to test a schema (validating, converting app -> python messages, converting python -> app data), and show what it is used for...
Which methods are best to use here ?

**Comment by maximkulkin** [comment]
You should start with generic documentation first (https://marshmallow.readthedocs.io/en/dev/index.html).

**Comment by sloria** [comment]
Yes, please consult the official documentation to understand Schema's expected behavior. There is nothing special about writing doctests for Schemas.
