### ISSUE TITLE
Could How To Run Tests Be Added To the Readme?

### ISSUE THREAD

**Issue by eligundry** [marshmallow-code/marshmallow#508]
Hi all, I'm loving Marshmallow and would love to contribute. I have but one issue and that is getting the test suite running on my machine. Looking at the README, there is no contributing section outlining how to actually run the tests, like most libraries do. Examples of other projects that have clear contributing sections outlining how to run the tests are [Flask](https://github.com/pallets/flask), [httpie](https://github.com/jkbrzt/httpie/blob/master/CONTRIBUTING.rst), and, everyone's favorite, [Requests[(https://github.com/kennethreitz/requests#how-to-contribute) (though he doesn't say explictly how to run tests, but that's whatever).

Thoughts? Also, how do you run the tests? All I'm getting is flake checking external dependencies for style.

**Comment by sloria** [comment]
Hi, I'd be glad to help you get started contributing to marshmallow. The contributing guidelines are in the official docs here: http://marshmallow.readthedocs.io/en/latest/contributing.html . There you'll find how to run the tests. If you have any further questions, feel free to open another issue.
