### ISSUE TITLE
What's the difference between only and partial?

### ISSUE THREAD

**Issue by svenstaro** [marshmallow-code/marshmallow#509]
They seem to be accomplishing the same thing. It doesn't become apparent to me from the current docs how `only` and `partial` are different.

**Comment by sloria** [comment]
They differ in how they affect serialization. `only` is used to filter serialized output. `partial` has no effect on serialization; it only allows missing fields to pass validation (and deserialization) on required fields.

``` python
from marshmallow import Schema, fields

class MySchema(Schema):
    foo = fields.Field(required=True)
    bar = fields.Field(required=True)


only_schema = MySchema(only=('foo', ))

print(only_schema.dump({'foo': 42, 'bar': 24}))

partial_schema = MySchema(partial=True)

print(partial_schema.dump({'foo': 42, 'bar': 24}))
```

Output:

``` python
MarshalResult(data={'foo': 42}, errors={})
MarshalResult(data={'bar': 24, 'foo': 42}, errors={})
```

**Comment by svenstaro** [comment]
Thanks for the quick answer! I think this would be very useful to have in the documentation.

**Comment by sloria** [comment]
I would certainly accept a PR adding docs to clarify this. =)

**Comment by redlamb** [comment]
This answer makes sense with respect to serialization, but how do these fields affect deserialization. Based on the response (and the docs), I take this to mean that ```only``` applies to serialization and ```partial``` applies to deserialization. However, in testing, it looks like ```only``` also affects deserialization.
```python
print(only_schema.load({'foo': 42}))
print(partial_schema.load({'foo': 42}))
```
Output:
```python
UnmarshalResult(data={u'foo': 42}, errors={})
UnmarshalResult(data={'foo': 42}, errors={})
```
I expected deserialization using ```only_schema``` to result in an error similar to the example below. 
```python
MySchema().load({'foo':42})
```
Output:
```python
UnmarshalResult(data={'foo': 42}, errors={'bar': [u'Missing data for required field.']})
```
