### ISSUE TITLE
deserialize method for fields.Method should be able to receive the whole raw data too

### ISSUE THREAD

**Issue by shaumux** [marshmallow-code/marshmallow#514]
The deserialize method from fields.Method only receives the value for its own fields. It would be convenient to have the whole raw_input alongside.
My use case is I have to select a Schema from available schemas and nest it inside the original schema based on another value in the original schema which is validated by a Oneof validator.
Something like this:
{
    "version": "1",
    "criteria": {
        "criteria1": "value"
    }
}
or 
{
    "version": "2",
    "criteria": {
        "criteria2": "value"
    }
}

**Comment by maximkulkin** [comment]
Hey, as far as I know it is not possible in Marshmallow itself, but there is a https://github.com/maximkulkin/marshmallow-oneofschema extension library that allows to do that

**Comment by shaumux** [comment]
oneofschema didn't exactly fit my needs so i just rolled my own schemaselector

**Comment by maximkulkin** [comment]
@shaumux What are your needs?
