### ISSUE TITLE
Add option to fail on unexpected fields

### ISSUE THREAD

**Issue by maxgrenderjones** [marshmallow-code/marshmallow#515]
Per the [docs](https://marshmallow.readthedocs.io/en/latest/extending.html#schemavalidation):

> Normally, unspecified field names are ignored by the validator. If you would like access to the original, raw input (e.g. to fail validation if an unknown field name is sent), add `pass_original=True` to your call to `validates_schema`.

If I'm trying to use marshmallow to do validation that the input is what I expect and I want to fail if I get unexpected data, is there really no way to have it fail without writing your own validator? (Apologies if I'm just missing something obvious in the docs - this seems very surprising as someone new to marshmallow).

If not, feature request: please could you add a `fail_on_unexpected` flag to accompany `strict` (which would have to default to `False` for backwards compatibility reasons? (I guess `strict` is some combination of hypothetical `fail_on_missing` and `validate` keywords?)

**Comment by sloria** [comment]
Let's continue discussion of this in #524
