### ISSUE TITLE
Email Field validation not working for Schema.dump()

### ISSUE THREAD

**Issue by h0st1le** [marshmallow-code/marshmallow#53]
Email field type validation does not appear to work when using Schema.dump() but works fine for Schema.load(). Working example included below:

```
from datetime import datetime
from marshmallow import Schema, fields, pprint

# model
class Person(object):
    def __init__(self, name, email):
        self.name = name
        self.email = email
        self.date_born = datetime.now()

# serializer schema
class PersonSchema(Schema):
    name = fields.String()
    email = fields.Email()
    date_born = fields.DateTime()

person = Person(name='Guido van Rossum', email='invalid-email')
schema = PersonSchema()
dumps = schema.dump(person)

print '--DUMPS--'
pprint(dumps.data)
pprint(dumps.errors)

loads = schema.load({'name': 'Guido van Rossum', 'email': 'invalid-email'})

print '--LOADS--'
pprint(loads.data)
pprint(loads.errors)
```

**Comment by sloria** [comment]
`Email` and `URL` fields have built-in "user validators" (stored in each field's `validators` attribute. User validators are only applied during deserialization, i.e. when calling `Schema#load`. `Schema#dump` only validates against field types (e.g. a valid integer is passed to `fields.Int`).

See https://github.com/sloria/marshmallow/issues/45#issuecomment-57367254 and https://github.com/sloria/marshmallow/issues/47#issuecomment-57947092 for related discussion.

That said, one could argue that the email format validation defines `fields.Email`'s "type" and that it _should_ be validated on serialization. Perhaps this would make `fields.Email` and `fields.URL` more consistent with the behavior of the other fields.

**Comment by h0st1le** [comment]
Thanks for the clarification, the related discussions also helped to better understand the reasoning behind this. That being said I do still like the idea of the `fields.Email` and `fields.URL` "type" being used for validation on serialization. As pointed out it would make their behavior more consistent with that of other fields. At the very least maybe an addition to the documentation that points out the current behavior?

**Comment by sloria** [comment]
I have decided to restore validation upon serialization for `Email` and `URL` fields. Thank you for raising the issue!
