### ISSUE TITLE
Unknown format code 'f' for object of type 'unicode'

### ISSUE THREAD

**Issue by jessemyers** [marshmallow-code/marshmallow#538]
After the upgrade to `2.10.2`, our application schemas that use float and decimal value fields are breaking.

Here's a simple case that now breaks (and doesn't in `2.10.1`):

```
from marshmallow import fields, Schema


class MySchema(Schema):
    test = fields.Decimal(allow_none=True, as_string=True, places=2)

schema = MySchema()
schema.dump({})
```

**Comment by sloria** [comment]
Thanks for reporting. I will look into fixing this today.

**Comment by sloria** [comment]
I've just release 2.10.3, which should fix this bug. Let me know if you have any further issues.

**Comment by jessemyers** [comment]
Looks good so far. Thanks.
