### ISSUE TITLE
Validating value is unique

### ISSUE THREAD

**Issue by jomag** [marshmallow-code/marshmallow#541]
Hi

I have a user schema with an email field. The email is validated to be unique:

```
class UserSchema(ma.Schema):
    def validate_email(value):
        return User.query.filter(User.email == value).first() is None

    username = ma.fields.String()
    email = ma.fields.Email(validate=validate_email)
```

This works great when creating users, but when updating a user with same email address it fails because there is already a user with same email address: the same user as the one being updated!

The validator unfortunately only has access to the email value so I can't check if the user found is the same as the one being updated.

How do I best handle this?

**Comment by maximkulkin** [comment]
I would suggest moving such validation outside of schema:

```
class UserSchema(ma.Schema):
    username = ma.fields.String()
    email = ma.fields.Email()

def user_exists(email):
    return User.query.filter(User.email == email).first() is not None

def user_create(payload):
    user_data, _ = UserSchema(strict=True).load(payload)
    if user_exists(user_data['email']):
        return {'error': 'User with this email already exists'}, 422
    user = User(**user_data)
    user.save()
```

**Comment by sloria** [comment]
@maximkulkin 's solution is valid; just do the validation after loading the data.

Alternatively, you could add the user to the schema's context. See https://github.com/marshmallow-code/marshmallow/issues/542#issuecomment-256520229 .

**Comment by aryaniyaps** [comment]
@sloria @maximkulkin however this leads to inconsistent responses from the api. Regular validation errors are in the format

```
{ email: ["error"] }
```
By moving the checks outside, the unique error becomes
```
{ email: "error unique" }
```

It would be nice to have an api to report errors even outside the schema, at least, so that central exception handlers can return consistently formatted errors (in web frameworks like flask, fastapi).

**Comment by lafrech** [comment]
Not really a marshmallow issue.

Schema validations return errors under the `_schema` key so you may use this for those errors as well.

**Comment by kazitanvirahsan** [comment]
You can use another schema for update.
