### ISSUE TITLE
Empty string optionally interpreted as None

### ISSUE THREAD

**Issue by brainless** [marshmallow-code/marshmallow#543]
Hello,
Thank you for all the great work in this library. I would like to ask if optionally interpreting empty string as `None` will be helpful for others. For our project it makes sense, using a flag like `empty_string_as_none` which if set to `True` will convert empty string (`""`) to `None`.

The parameter `allow_none` will still come into action as it already works, just that empty strings will behave as `None` if `empty_string_as_none=True`.

Thanks,
Sumit

**Comment by maximkulkin** [comment]
IMO it is very wrong to support that kind of behavior. JSON has special value for None - null - and empty strings are actually strings. Optionally you can treat missing values as None. However, it is bad to encourage your clients to disregard all that and do things like treating empty strings as None, treating integer 0 as None and stuff like that (integer example is supposed to amplify how ridiculous it sounds).

**Comment by brainless** [comment]
@maximkulkin thank you for your response. I see your point. In our app the empty strings are coming from JavaScript code that handles forms and blank inputs come into the API as empty strings. Handing them in the form handling JavaScript is then a better idea.
Cheers!
