### ISSUE TITLE
`Nested(some_schema_instance, only=('a', 'b'))` is broken

### ISSUE THREAD

**Issue by ThiefMaster** [marshmallow-code/marshmallow#544]
```python
from marshmallow import Schema
from marshmallow.fields import Nested


class FooSchema(Schema):
    class Meta:
        fields = ('a', 'b', 'c')


foo_schema = FooSchema()


class BarSchema(Schema):
    foo = Nested(foo_schema, only=('a', 'b'))


bar_schema = BarSchema()


class Foo(object):
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)


class Bar(object):
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)



bar = Bar(id=123, foo=Foo(a=1, b=2, c=3))
print bar_schema.dump(bar).data
```

This returns `{u'foo': {u'a': 1, u'b': 2, u'c': 3}}` instead of the expected `{u'foo': {u'a': 1, u'b': 2}}`

**Comment by ThiefMaster** [comment]
It seems to work fine when using `Nested(FooSchema, only=('a', 'b'))` but if it's not OK to pass a schema instance it should probably fail or cause a warning instead of silently ignoring the `only` argument.

**Comment by maximkulkin** [comment]
I think that fool-proofs like that clutter the code so much that it makes it hard to read and contribute to the project. I think stating this behavior in documentation should be sufficient.

**Comment by sloria** [comment]
I agree with @maximkulkin ; documenting this should suffice. I've added a note in the API docs for `Nested`. Thanks @ThiefMaster  for reporting and thanks @maximkulkin for the suggestion.
