### ISSUE TITLE
Refactoring validators

### ISSUE THREAD

**Issue by Shir0kamii** [marshmallow-code/marshmallow#545]
Hi all,

I suggest a refactorization of validators in marshmallow.

By browsing the code in marshmallow/validatate.py, you can see that a lot of
validators share their internal methods. What I suggest exactly is putting all
this shared behavior in the `Validator` class and override it where necessary.

For example, the handling of error is almost the same in all subclasses. It
would reduce the duplication of code to implement it in `Validator`.

Admitting most of the community agree with this refactorization, there is at
least one caveat I can think of. Since these implementations are not exactly
the same (for instance signature), should we stay retro-compatible with
internal methods? One could argue we shouldn't break old code, but these methods are internals and shouldn't be used.

If this refactorization is kept for the next major version, we can also
standardize public methods.

So here is my proposition, feel free to give some feedback.

**Comment by maximkulkin** [comment]
Could you provide some examples of before and after code? I'm looking at marshmallow/validate.py and can't find any functionality that can be shared.

**Comment by Shir0kamii** [comment]
Sure! First, the `_format_error` can easily be merged inside the `Validator` class. There are two form of it (with and without input) and it used mainly to raise exceptions. Why not make a public function which handles all the error formatting and raise the exception ? It would yield something like this : 

``` python
    def fail(self, input=None, message=None):
        msg = message or self.error_message
        if input:
            msg = msg.format(input=input, **self.__dict__)
        else:
            msg = msg.format(**self.__dict__)
        raise ValidationError(msg)
```

It would bring consistency in the error handling even in subclasses of users.

To be honest, I also think a default `__init__` method can be provided as most of them only set an attribute and the error message.

**Comment by maximkulkin** [comment]
Well, yes, I agree that Validators could have the same interface as Fields have: there is `default_error_messages` class field, there is a `error_messages` constructor argument and there is `fail()` method (although I think it should be `_fail()` as it is not intended to be called outside of validator object).
I recall I had exactly same concern when I was designing validators in my own validation library ([shameless plug](https://github.com/maximkulkin/lollipop/blob/master/lollipop/validators.py)), ther are some consequences, which might be not easy/elegantly solved.

**Comment by Shir0kamii** [comment]
Yup, that's the kind of things I'd like to implement if my refactorization is
accepted. What are those consequences you're talking about ?

Could anyone else give us feedback before I begin implementing something ?

**Comment by maximkulkin** [comment]
Mostly, it's about having two ways to define errors: either through `error_messages` constructor argument (which should be a dictionary of different error names(keys) to error message), or through `error` argument. Most validators check one particular thing and it's mostly sufficient to specify just one error without bothering with it's error key. That's why I have `error` argument: if it is set, I populate proper keys in error_messages dict with this value. Thus, this is manual code and I need manually do it in every validator constructor. Thus, no cutting corners.
