### ISSUE TITLE
Include Ordered Set as a package instead of writing it yourself?

### ISSUE THREAD

**Issue by sabinem** [marshmallow-code/marshmallow#546]
I studied marshmellows code, since I was looking for a project, that I understand well enough, in order to start contributing to it. I really like marshmellow and I feel that its code and documentation are very well written. One thing, that I noticed though are the custom written collectibles. I understand that marshmellow takes its custom OrderedDict only for Python 2.6, where there is no other choice, but for the custom OrderedSet there would be other choices: I found two packages: 
1. the first is very similar to the function used now: https://pypi.python.org/pypi/ordered-set. It is written in pure Python, but has some improvements that are all stated on the projects github page. It seems more clean and performs better.
2. the second is written in Cython: https://pypi.python.org/pypi/orderedset. It comes with better documentation then the first package and differs more form the current solution.
Both are based on Raymond Hettinger's OrderedSet recipe, just as the one used now is. I would suggest to use one of these two options instead of the custom OrderedSet. 
If the community agrees I would be happy to work on this. What do you think about this suggestion?

**Comment by sloria** [comment]
Thanks for taking the time to study marshmallow, @sabinem . Marshmallow currently has no hard external dependencies, which keeps the codebase self-contained. This is not to say marshmallow will never have external dependencies--sufficiently stable dependencies that add value will certainly be considered.

Re: OrderedSet--marshmallow already exposes a way to change the set class:

``` python
from myorderedset import OrderedSet

class MySchema(Schema):
    @property
    def set_class(self):
        return OrderedSet if self.ordered else set
```

As long we have this hook, I don't think adding a dependency is necessary. It's the same as the `Meta.json_module` option: though there are alternative JSON encoding/decoding libaries (e.g. simplejson, ujson), it suffices to expose an option that lets the user choose.

**Comment by sabinem** [comment]
@sloria, fair enough, I understand that. Then I would suggest to consider coping the more mature recipe from LuminosoInsight: [https://github.com/LuminosoInsight/ordered-set/blob/master/ordered_set.py](https://github.com/LuminosoInsight/ordered-set/blob/master/ordered_set.py). This recipe is very similar to the one used now, but the code looks a lot nicer and the reasons why he changed the original recipe seem convincing to me:

> Based on a recipe originally posted to ActiveState Recipes by Raymond Hettiger,
> and released under the MIT license.
> Rob Speer's changes are as follows:
>     - changed the content from a doubly-linked list to a regular Python list.
>       Seriously, who wants O(1) deletes but O(N) lookups by index?
>     - add() returns the index of the added item
>     - index() just returns the index of an item
>     - added a **getstate** and **setstate** so it can be pickled
>     - added **getitem**

I tested both solutions, since I am quite curious on collections, and I also felt that the doubly linked list was kind of ugly. If there is a better way to do it, why not do it. 

What do you think?  Would be worth considering switching to  the other recipe?

**Comment by sloria** [comment]
True, we could vendorize LuminosoInsight's implementation. Is its API completely compatible with the ActiveState recipe?

**Comment by sabinem** [comment]
I think it is, but I will check it out and get back to you. I would like to work on this, if that is okay with you. I was looking for a library where I can start contributing to open source and I settled for marshmellow, since I feel it is just the right size of a project for my current skill level. Would that be fine with you?

**Comment by sloria** [comment]
@sabinem Sounds great. Thank you for helping out!

**Comment by maximkulkin** [comment]
C'mon.. None of this improvements look vital to me:
- Changed implementation from double linked list to simple list. OK, it gets O(1) index at cost of O(n) deletes. Srsly? The main three operations on sets are addition, removal and check for inclusion. All three operations are O(1) in current implementation. Iteration is O(n) which is expected, no overhead here. Now it adds indexing. Why we should care about indexing at all?
- Pickling. I tried existing one and it does support pickling as well. It might not be the most optimal one, but it does work if you will need that (although the use case is also obscure: it's a strange idea to pickle schema descriptors).
- getitem is probably from the same use case as indexing which I do not understand.

Given OrderedSet is used to hold filed names and there are no removals used, the proposed implementation will not make it worse. But I still consider it to be a worse implementation (because it degrades removal time complexity) than original implementation with no apparent value added.

**Comment by sabinem** [comment]
@maximkulkin: thank you for your insights on this, I agree, that this should be an informed decision rather then replacing something hastily against something else. Anyway, I read through the comment thread of the original recipe: http://code.activestate.com/recipes/576694-orderedset/. This topic is very interesting to me and I want to put some more time into studying the different solutions and then come back, when I know more and can propose something concrete. That might take a while, though. Does that sound okay to you?

**Comment by sloria** [comment]
Closing this for now. I am open to changes if someone wants to investigate alternative ordered set implementations, but it's not a priority at the moment.
