### ISSUE TITLE
Store errors on Schema().load() if excluded fields are present

### ISSUE THREAD

**Issue by HaraldNordgren** [marshmallow-code/marshmallow#547]
I want the option (or changed default behaviour) to inherit a Schema, specify certain fields as excluded, and then have Marshmallow give back errors if any of those fields are in the data.

**Comment by lafrech** [comment]
I believe if you set `strict=True` in `class Meta`, you'll get this validation. However, you'll also get errors for any unknown field, not only for excluded fields.

I don't know of a way to get errors for excluded fields only, and I'm not sure it would be that useful.

**Comment by sloria** [comment]
Take a look at this recipe from the docs: https://marshmallow.readthedocs.io/en/latest/extending.html#validating-original-input-data . It should meet your use case with minor modifications (i.e. checking `self.exclude`).

**Comment by HaraldNordgren** [comment]
Thanks for that. Worked nicely!
