### ISSUE TITLE
field related nested schema

### ISSUE THREAD

**Issue by z333d** [marshmallow-code/marshmallow#553]
I want to create such schema:
`
class XSchema(Schema):
    type = String()
    query = Nested(YSchema)
`
different type will have corresponding YSchema, for example:
when type is 'a', YSchema will be ASchema, and type is 'b', YSchema will be BSchema, and so on.

Is there any solution to achieve this? Thanks

**Comment by lafrech** [comment]
You may be interested by OneOfSchema:

https://github.com/marshmallow-code/marshmallow/issues/412
https://github.com/maximkulkin/marshmallow-oneofschema

**Comment by z333d** [comment]
@lafrech thank you. I have solved this problem with help of a friend.
the solution is:
```
from marshmallow import Schema, validates_schema, ValidationError
from marshmallow.fields import String

class ASchema(Schema):
    q = String(required=True)

class BSchema(Schema):
    name = String(required=True)

class XSchema(Schema):
    type = String(required=True)
    query = Dict(required=True)
    
    @validates_schema
    def validate_query(self, data):
        try:
            globals()['%sSchema' % data['type'].capitalize()](strict=True).load(data['query'])
        except:
            raise ValidationError('type must be provided')


x_schema = XSchema(partial=False)

x_schema.load(dict(type='a', query={'q': 'python'}))
# UnmarshalResult(data={'query': {'q': 'python'}, 'type': u'a'}, errors={})
x_schema.load(dict(type='b', query={'name': 'schema'}))
# UnmarshalResult(data={'query': {'name': 'schema'}, 'type': u'b'}, errors={})
```

**Comment by lafrech** [comment]
OneOfSchema is more generic, but if your solution suits your use case, fine.

You can close this issue, then.
