### ISSUE TITLE
load Nested field problem?

### ISSUE THREAD

**Issue by DormyMo** [marshmallow-code/marshmallow#554]
https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L451

when the value is a list , should be like this ? 

`data, errors = self.schema.load(value,many=self.many)`

**Comment by lafrech** [comment]
No need to pass `self.many`: `shema.load` uses `self.many` by default.

https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/schema.py#L628
