### ISSUE TITLE
Rationale behind fields.DateTime().deserialize('1916') returning datetime(1916, 11, 30, 0, 0)?

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow#556]
I just noticed that when I deserialize a date expressed as a 'YY' or 'YY-mm' string, I get a datetime with month defaulting to 11 and day defaulting to 30 (except for february).

```py
f = fields.DateTime()
f.deserialize('1916')
# datetime.datetime(1916, 11, 30, 0, 0)
f.deserialize('1916-2')
# datetime.datetime(1916, 2, 29, 0, 0)
f.deserialize('1916-3')
# datetime.datetime(1916, 3, 30, 0, 0)
```

Is this intended?

Shouldn't this be either rejected or default to a documented value (could be january 1st)?

To prevent this seemingly non-deterministic behavior (it seems reproducible, but I don't get the rationale), as a workaround, it is possible to set a format explicitly, which rejects such incomplete inputs, but this might not always be desired (be loose on inputs / strict on outputs).

```py
f = fields.DateTime(format='%Y-%m-%d')
f.deserialize('1916-05-04')
# datetime.datetime(1916, 5, 4, 0, 0)
f.deserialize('1916')
# marshmallow.exceptions.ValidationError: Not a valid datetime.
```

**Comment by jacquerie** [comment]
This looks like the (somewhat puzzling) default behavior of `python-dateutil`: https://labix.org/python-dateutil#line-1275. It uses today's date as a default. Tomorrow you're going to see `1916-12-1`, `1916-2-1` and `1916-3-1` for your first three examples.

**Comment by lafrech** [comment]
Oh, right. I had read about this trap, already, but I didn't notice it was today's date...

Great, so now we have an explanation.

I think my point still remains. It's a bit weird to get this as a "default" and I'd rather have either a `ValidationError` or a more "natural" default value (like 1 for each field). Or has this `dateutil` behaviour become a _de facto_ standard?

Technically, that would be a breaking change, but relying on today's behaviour doesn't sound so wise, does it?

**Comment by maximkulkin** [comment]
Technically, it is not a breaking change. That functionality is not a public API or part of contract. It's like using private API and then blaming authors for changing it.

**Comment by lafrech** [comment]
You mean "not part of contract" because current behaviour is not documented? (I'm not trying to argue about it being a breaking change or not. I'd just like to be sure I understand your point correctly.)

**Comment by maximkulkin** [comment]
Exactly

**Comment by sloria** [comment]
@maximkulkin is correct; this is not a breaking change and goes against user expectation. I would gladly review and merge a PR for this.

**Comment by lafrech** [comment]
Deadlines coming, I won't be able to work on this in the near future, I'm afraid.

What would be your preference ?

- Should those inputs be rejected (`ValidationError`)?
- Should the deserializer default to `1` (January 1st)?
- ...?

**Comment by maximkulkin** [comment]
I would say that those inputs should be rejected (ValidationError)

**Comment by sloria** [comment]
I agree; rejecting invalid formats should result in a ValidationError

**Comment by lnielsen** [comment]
Just for the record - this is a breaking change which should have been introduced in 2.14 instead. One of our public APIs broke, when we just bumped marshmallow from 2.13.4 to 2.13.5:

```console
$ pip install "marshmallow==2.13.4"
>>> from marshmallow import fields
>>> f = fields.DateTime()
>>> f.deserialize('2017-05-29')
datetime.datetime(2017, 5, 29, 0, 0)
```

vs.

```console
$ pip install "marshmallow==2.13.5"
>>> from marshmallow import fields
>>> f = fields.DateTime()
>>> f.deserialize('2017-05-29')
Traceback (most recent call last):
...
ValueError: Not a valid ISO8601-formatted string
```

**Comment by sloria** [comment]
@lnielsen See the discussion on https://github.com/marshmallow-code/marshmallow/pull/605 : 

> I'm sorry for any inconvenience this change may have caused you. This was, however, a bug fix--DateTime was accepting invalid input, and this fixes that.
