### ISSUE TITLE
Field serialize default arguments

### ISSUE THREAD

**Issue by asmodehn** [marshmallow-code/marshmallow#560]
Currently [Field.serialize()](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L233) takes self and 2 arguments (attr and obj).

However in basic use cases, attr is not needed.

- [Nested](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L427)
- [List](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L547) -> depends on self.container
- [String](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L582)
- etc.

so I think the `attr` argument of `Field.serialize()` should be optional.

my current workaround is
```python
mybfield = Boolean()
wire_format = mybfield.serialize(0, [True])
assert mybfield.deserialize(wire_format)
```
but this would be nicer : 
```python
mybfield = Boolean()
wire_format = mybfield.serialize(True)
assert mybfield.deserialize(wire_format)
```

Also in term of API design this should make the `deserialize` function the exact inverse of `serialize` function.

**Comment by maximkulkin** [comment]
Fields are not meant to be used standalone thus their API is not that polished.

**Comment by sloria** [comment]
@maximkulkin is correct re: fields being used standalone, so we don't intend to change the API for now. Feel free to reopen and elaborate on your use case if you feel strongly about changing the API.
