### ISSUE TITLE
The value type is not checked

### ISSUE THREAD

**Issue by divanovGH** [marshmallow-code/marshmallow#561]
```
from marshmallow import Schema
from marshmallow.fields import Float
schema = {'field': Float()}
data = {'field': '1'}
errors = type('ValidationSchema', (Schema,), schema)().validate(data)
```

errors is None! Why??? The field value is "string" type. Validator trying to cast: float('1'). It's wrong! Need to check the type.

**Comment by maximkulkin** [comment]
Although there are use cases for that behavior (e.g. you are validating posted form: in that case everything is strings), I think it should be customizable. All numeric fields have "as_string" option which if enabled serializes numbers to string representation. But on deserialization it doesn't check that option and just relies on standard conversion functions to handle incorrect input. Numeric fields could be extended to account for "as_string" option and check that input value is of proper type.

**Comment by divanovGH** [comment]
```
from marshmallow import Schema
from marshmallow.fields import Float
schema = {'field': Float()}
data = {'field': 'www'}
errors = type('ValidationSchema', (Schema,), schema)().validate(data)
```
errors is None!   'www' is float type  (((
