### ISSUE TITLE
Is there a specific way to format datetime in json to conform to?

### ISSUE THREAD

**Issue by rlam3** [marshmallow-code/marshmallow#566]
Is there a specific way to format datetime in json?

Some of my json dates come out as "Tue, 22 Sep 2015 10:17:00 GMT" and some come out as "2015-02-03T15:40:36.078358+00:00"

data in database all look the same. I'm not sure how to get rid of the GMT way of formatting...

**Comment by sloria** [comment]
Resolved in marshmallow-code/flask-marshmallow#55
