### ISSUE TITLE
"dump_only" field attribute not working

### ISSUE THREAD

**Issue by rajeshbk042** [marshmallow-code/marshmallow#568]
Hi All,

I have used that "**dump_only**" field attribute for a field in "**ModelSchema**" schema and passed values for that filed, its writing or updating into database. Its not taking account of **dump_only**.

Please help me to figure it out....

**Comment by maximkulkin** [comment]
Post your code. Maybe you're doing it wrong.

**Comment by rajeshbk042** [comment]
`class Profile(ma.ModelSchema):`
     ` user_id= fields.Int(dump_only=True)`

**Comment by maximkulkin** [comment]
It works for me:
```python
import marshmallow as m
import marshmallow.fields as mf

class Profile(m.Schema):
    user_id = mf.Int(dump_only=True)

print Profile().load({'user_id': 123})
# => UnmarshalResult(data={}, errors={})
```

**Comment by rajeshbk042** [comment]
You are saying about **"m.Schema"** but I am asking about  **ma.ModelSchema**

**Comment by maximkulkin** [comment]
There is no `ModelSchema` in Marshmallow library.

**Comment by rajeshbk042** [comment]
Yes, there is **ModelSchema** in marshmallow and I have created serializers using this , its worked for me. Check this [https://flask-marshmallow.readthedocs.io/en/latest/]( https://flask-marshmallow.readthedocs.io/en/latest/)

**Comment by rajeshbk042** [comment]
Okay, its in [https://flask-marshmallow.readthedocs.io/en/latest/](https://flask-marshmallow.readthedocs.io/en/latest/)

**Comment by maximkulkin** [comment]
It's in [flask-marshmallow](https://github.com/marshmallow-code/flask-marshmallow) adapter library. Looks like the problem is in that library. You should report it there.
