### ISSUE TITLE
"Should" marshmallow be used for form validation not related to database?

### ISSUE THREAD

**Issue by italomaia** [marshmallow-code/marshmallow#570]
Hi folks. Quick question. Should marshmallow be used to validate data sent by ajax when that given data is not model related? Example: imagine you have a search form with a few fields used to fine grain your search query. Would it be a good use case for marshmallow to parse that given data or should the fields be validated using another way?

**Comment by maximkulkin** [comment]
Sure. Why not?

**Comment by sloria** [comment]
Yes, this is a common use case. You might be interested in the [webargs](https://github.com/sloria/webargs) project, which uses marshmallow to validate request data (including form data).
