### ISSUE TITLE
Domain name validation in Email validator

### ISSUE THREAD

**Issue by bow** [marshmallow-code/marshmallow#579]
Hello developers,

This is more of a question (possibly an issue). I was trying to validate some email addresses using the `Email` validator class, when I stumbled on it not validating this particular email address: `test@domain.c`

I then looked into [the code](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/validate.py#L119) and found that the part after the `.` in the domain name must be at least 2 characters.

May I ask what the reasoning behind this is?

I know email validation (and by extension domain name validation) can be a complicated issue, so I tried looking up if there are formal specifications that can be relied upon. I found that the format of the domain name is specified in [this RFC, section 2.1](https://tools.ietf.org/html/rfc1123#page-13) and by extension [this RFC, section B](https://www.ietf.org/rfc/rfc952.txt). There seems to be no restrictions there on limiting the part after the `.` to 2 characters.

I am on Python 3.5.2, running marshmallow version 2.10.3. Thanks in advance!

**Comment by rgant** [comment]
I don't believe there are any TLDs with less than two characters. That is probably the reasoning behind that check.
https://en.m.wikipedia.org/wiki/List_of_Internet_top-level_domains

**Comment by lafrech** [comment]
Not yet, but according to [this SO post](http://stackoverflow.com/questions/7411255/is-it-possible-to-have-one-single-character-top-level-domain-name#21872376) (2014) there could be. It would be valid as per the RFC.

I understand the fact that there is currently none and we don't expect any to appear in the future could justify that behavior. But even then, it would be debatable. Marshmallow should probably stick to the RFC and let the user override for more checks. Anyway, I don't mind at all, I just wanted to add that link I considered relevant.

**Comment by maximkulkin** [comment]
[RFC](https://tools.ietf.org/html/rfc3696#section-2) states that top-level domain validation should check for all existing TLDs at the moment and be updated whenever TLD list changes. The validation regexp in Marshmallow is a simplified version that is commonly used. So, as of now it pretty consistent with RFCs. When 1 letter domain will be introduced, then it can be updated. As of now `test@domain.c` is incorrect email address.

**Comment by justanr** [comment]
@maximkulkin To be the devil's advocate, it's only invalid when talking across the web but local DNS could resolve `.c` as a valid in network domain. Since it's an invalid TLD according to current standards, it's a pretty good in network TLD to prevent accidentally talking to some out of network service.

Not that I'm saying the regex should be changed to support it, merely presenting a valid use case that this *could* trample.

**Comment by bow** [comment]
@maximkulkin I'm not in a position to decide any one change, though I tend to agree with @justanr. The RFC itself mentions validating using a DNS service, which may be local to specific users.

But anyway, I think this answers my initial question already. I'll close this issue for now and leave it for reopening in a possible future where we have ICANN-approved single-letter TLDs :).

Thank you!
