### ISSUE TITLE
Add "on" and "off" values to Boolean truthy/falsy sets

### ISSUE THREAD

**Issue by marcellarius** [marshmallow-code/marshmallow#580]
Rationale: Checkboxes in HTML forms use the value "on" when checked. This would be convenient as it would allow checkbox fields to be parsed as booleans when using Webargs with HTML forms.

**Comment by podhmo** [comment]
this is work-around solution.

```python
from marshmallow import Schema, fields


class MyBoolean(fields.Boolean):
    truthy = fields.Boolean.truthy.union({"on"})
    falsy = fields.Boolean.falsy.union({"off"})


class S(Schema):
    v = MyBoolean()


print(S().load({"v": True}))
print(S().load({"v": False}))
print(S().load({"v": "on"}))
print(S().load({"v": "off"}))

# UnmarshalResult(data={'v': True}, errors={})
# UnmarshalResult(data={'v': False}, errors={})
# UnmarshalResult(data={'v': True}, errors={})
# UnmarshalResult(data={'v': False}, errors={})
```

**Comment by justanr** [comment]
A better solution might to allow iterables of truthy and falsey values in the constructor. Or using the function/method field to pipe the value through a custom truth check

**Comment by sloria** [comment]
I am open to this. Looks like this was implemented in Django-REST-framework's BooleanField (https://github.com/tomchristie/django-rest-framework/commit/276ed80fd302184dddb3af01e53d43be4aef15e4).

PRs welcome.
