### ISSUE TITLE
Question: Deserializing HTML form nullable fields

### ISSUE THREAD

**Issue by alexmic** [marshmallow-code/marshmallow#583]
I'm using Marshmallow for HTML form deserialization with Flask. I have an integer field which is nullable but the value received from the HTML form is obviously the empty string. I'm trying to figure out how to handle that without writing anything on top of marshmallow but I'm failing to see how. If I use `Integer` then it will fail to cast the empty string. If I use `String` then I need to write something to cast it to integer (possibly a `post_load` processor) but then I need to handle validation as well. Any pointers?

**Comment by rgant** [comment]
You can use the `as_string` setting for Integers to make it handle empty strings better.

```python
>>> from marshmallow import Schema, fields
>>> class ArtistSchema(Schema):
...   id = fields.Integer(as_string=True)
... 
>>> schema = ArtistSchema()
>>> schema.load({'id': '15'}).data
{'id': 15}
>>> schema.load({'id': ''}).data
{}
>>> schema.load({'id': None}).data
{}
>>> schema.load({'id': 15}).data
{'id': 15}
```

**Comment by sloria** [comment]
`as_string` only applies to serialization.

I think the correct solution is to use a custom field that deserializes empty strings to `None`.

```python
from marshmallow import Schema, fields

class StrInt(fields.Int):

    def _deserialize(self, value, attr, data):
        if value == '':
            if not self.allow_none:
                self.fail('null')
            return None
        return super()._deserialize(value, attr, data)

class MySchema(Schema):
    id = StrInt(allow_none=True)


schema = MySchema(strict=True)

print(schema.load({'id': ''}).data)  # {'id': None}
```

Hope that meets your use case.
