### ISSUE TITLE
whishlist: add a simple check to avoid name clashes

### ISSUE THREAD

**Issue by silenius** [marshmallow-code/marshmallow#584]
Hello,

I just lost one hour of work with a stupid thing, I had the following (simplified for example):

```python
class ContentSchema(Schema, PyramidContextMixin):
    tags_id = List(Integer(), load_only=True)
    tags = Nested(TagSchema, many=True, dump_only=True)

    @post_load
    def load_tags(self, item):
        if 'tags_id' in item:
            item['tags'] = self.dbsession.query(Tag).filter(
                Tag.id.in_(item['tags_id'])).all()
        return item

    @post_dump
    def tags_id(self, data):
        data['tags_id'] = [i['id'] for i in data['tags']]
        return data
```
and in the wrapped `post_dump` function I had a stupid `KeyError` exception for the `tags_id` key. Obviously it was because the `tags_id = List(Integer(), load_only=True)` field was overriden by `def tags_id(self, data):` function later...

It would (maybe) be good to have a quick check in the constructor which checks that no field is overriden by any `pre_*` `post_*` decorator at later stage :)

Thanks!

**Comment by maximkulkin** [comment]
This is not a framework problem and yes, it is hard to implement. By the time constructor is executed, it already doesn't have reference to `tags_id` as a field. The class dictionary contains only "tags", "load_tags" and "tags_id". I guess you could get a warning from a some static analysis tool like pylint. But generally you should be using proper naming conventions (e.g. name your functions with a verbs, not nouns, e.g. `process_post_dump` or `normalize_tags_ids`; prefix those method names with underscore making them non-public)

**Comment by justanr** [comment]
To add to @maximkulkin this isn't even doable in Python 2.  If and when Marshmallow becomes Python 3 only, it can be done via the special prepare metaclass hook.

But you'd run into this issue with any class as class construction is essentially an exec into a dictionary, later values override previous ones.

**Comment by silenius** [comment]
I agree, forget about this issue :)
