### ISSUE TITLE
Unable to update context in between loads

### ISSUE THREAD

**Issue by lauwers** [marshmallow-code/marshmallow#594]
I'm using Marshmallow with Flask to parse payloads. I have a need to pass a number of request-dependent IDs to the various fields, for which I use the "context" field of my Schemas. I access context data within pre_load functions. 

The first time I "load" data, everything works fine: I create the necessary schema, and set my IDs in the context based on the request. Everything parses OK. However, all subsequent requests fail, because it seems that no matter what context data I pass to the Schema, the context data from the first requests are used. How do I update context in between loads?

**Comment by maximkulkin** [comment]
Source code, please.

**Comment by lauwers** [comment]
I’ll try to distill the simplest possible code snippet in a follow-up email.

After some more digging, it looks like this problem may be limited to List fields with nested schema:

Class NestedSchema(Schema):
   name = fields.Str()
   number = fields.Integer()

class MySchema(Schema):
  users = fields.List(fields.Nested(NestedSchema)


After the first time I use MySchema, any context updates don’t seem to get propagated to NestedSchema.

Thanks,

Chris

**Comment by lauwers** [comment]
Here is code that shows the problem. While experimenting, I found out that the problem only happens if I create multiple top-level schema objects. If I reuse the same top-level schema object, everything works as expected.

Chris

**Comment by maximkulkin** [comment]
Yes, it is a limitation of current design: on schema instantiation all field objects are bound to that particular instance. Through this binding they obtain context. If you will create multiple schemas, all field objects will bind to the last one created.

Solution: do not create multiple schemas, reuse a single instance.

**Comment by lauwers** [comment]
Thanks for the explanation. Will do.

Chris

**Comment by ethier** [comment]
Edit: I figured this out. [Here's](https://github.com/marshmallow-code/marshmallow/issues/594#issuecomment-409954832) my solution for it.

I know this is closed, but it really has me stymied. I'm not sure if this should be the intent here as I believe it would introduce thread-safe issues to the library.

At the very least, it makes it very difficult to test schemas. Here's an example (w/3.0.0b12):

```python
from marshmallow import fields, Schema, validates_schema, ValidationError


class ChildSchema(Schema):
    name = fields.Str()

    @validates_schema
    def validate_context(self, data):
        if self.context.get('foo') is not None:
            raise ValidationError('foo is set')


class ParentSchema(Schema):
    child = fields.Nested(ChildSchema())


class TestParentSchema():
    def test_with_context(self):
        schema_with_context = ParentSchema(context={'foo': 'bar'})

        result = schema_with_context.validate({'child': {'name': 'Joe'}})

        assert {'child': {'_schema': ['foo is set']}} == result

    def test_without_context(self):
        schema_without_context = ParentSchema()

        result = schema_without_context.validate({'child': {'name': 'Joe'}})

        assert {} == result
```

In this test run, the second test `def test_without_context` will always fail as it is still seeing the context set in the `schema_with_context` variable in the `def test_with_context` test.

It's important to `pytest path/to/file.py` on this (as a file) to invoke them in the same run, running them individually, they'll pass.

I suspect the issue is [here](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L414) but I haven't figured out a way to alter this logic. I've been following the discussion in #302 as well, as it seems to be possibly related to this.

Is there a better way to test schemas with contexts? Happy to open another issue here as well, but it is directly related to this issue so I thought I'd start here.

@lauwers did you ever find a way around this?

**Comment by lauwers** [comment]
I stopped using contexts altogether, since they didn’t solve my problem. I wanted “dynamic” context that would change on per-load basis. If I remember correctly, the problem I encountered was that once a schema was created without a context, it would never get passed a context, even if it was called as a Nested schema from a parent schema with a context. Said a different way, the context is associated statically with a schema for the duration of its lifetime, rather than passed dynamically at load time. Sounds like you have the same but opposite problem: once a schema is created with a context, you can never get rid of it.

Not sure if anything has changed since I encountered this problem 2 years ago.

Chris

**Comment by ethier** [comment]
Thanks! Yeah, I'm going to see if I can re-factor with instance vars and `__init__`. Just trying to figure out how to share them across nested schemas.

**Comment by ethier** [comment]
Alright, I figured out my issue, so here it is for anyone that might stumble on this.

In a lot of the marshmallow examples, they show class instances in the `fields.Nested` usage. This is where my problem was. If I switch out to just using the class name instead, then all tests pass successfully and context is specific to the individual usage.

It's subtle in the full example, it's:
`child = fields.Nested(ChildSchema())`

to this:
`child = fields.Nested(ChildSchema)`

Here's the full code with the fix. Hope this helps someone else.

```python
from marshmallow import fields, Schema, validates_schema, ValidationError


class ChildSchema(Schema):
    name = fields.Str()

    @validates_schema
    def validate_context(self, data):
        if self.context.get('foo') is not None:
            raise ValidationError('foo is set')


class ParentSchema(Schema):
    child = fields.Nested(ChildSchema)


class TestParentSchema():
    def test_with_context(self):
        schema_with_context = ParentSchema(context={'foo': 'bar'})

        result = schema_with_context.validate({'child': {'name': 'Joe'}})

        assert {'child': {'_schema': ['foo is set']}} == result

    def test_without_context(self):
        schema_without_context = ParentSchema()

        result = schema_without_context.validate({'child': {'name': 'Joe'}})

        assert {} == result
```
