### ISSUE TITLE
marshmallow field and schema validation order

### ISSUE THREAD

**Issue by norbertpy** [marshmallow-code/marshmallow#596]
Given the following Schema:

```
from marshmallow import Schema, fields, validates_schema

class Book(Schema):

  name = fields.Str(required=True)

  @validates_schema
  def validate(self, data):
    print ('>>> validating schema')
    print ('name is: ', data['name'])


u = dict(age=14)
r = Book(strict=True).load(u)

```
I expect to get a `ValidationError` exception because I didn't provide `name` which is a required field. But instead I get:

```
>>> validating schema
Traceback (most recent call last):
  File "python", line 14, in <module>
  File "python", line 10, in validate
KeyError: 'name'

```
Why is that? What is the order of validation in marshmallow?

**Comment by sloria** [comment]
Field validators (including `required=True`) are run before schema-level validators (`validates_schema`). In marshmallow 2.x, however, schema-level validators are still executes, even if field-level validators fail. You can prevent this by passing `skip_on_field_errors=True` to `validates_schema`.

```python
from marshmallow import Schema, fields, validates_schema

class Book(Schema):

    name = fields.Str(required=True)

    @validates_schema(skip_on_field_errors=True)
    def validate(self, data):
        print('>>> validating schema')
        print('name is: ', data['name'])


u = dict(age=14)
r = Book(strict=True).load(u)
# marshmallow.exceptions.ValidationError: {'name': ['Missing data for required field.']}
```

We are planning on making `skip_on_field_errors` default to `True` soon (see #352).
