### ISSUE TITLE
marshmallow to handle file uploading

### ISSUE THREAD

**Issue by JMStudiosJoe** [marshmallow-code/marshmallow#601]
Which marshmallow field or parameter do I need to handle csv files through python flask? 
class FileUploadSchema(BaseSchema):
    file = Raw(required=True, missing=None)
    type = String(required=False, missing=None)
    csv = Dict(required=False, missing=None)

I know my data is pinging it since type I know is being changed but file and csv are both none

**Comment by JMStudiosJoe** [comment]
turns out webargs is what is suppose to be used... not clear in documentation

**Comment by dragoncsc** [comment]
Can you elaborate on webargs? I'm having this same problem and can't find the solution in the docs.

**Comment by AWilliams17** [comment]
@dragoncsc The docs aren't very clear, and I have yet to try it myself (I used the Json extension for WTForms in my last api project just to get around these headaches), but as the docs say:
https://webargs.readthedocs.io/en/latest/quickstart.html#request-locations

> By default, webargs will search for arguments from the URL query string (e.g. "/?name=foo"), form data, and JSON data (in that order). You can explicitly specify which locations to search

> Available locations include: ... files

Then, going off of this https://github.com/marshmallow-code/webargs/issues/230

> If you use fields.Field, marshmallow won't do any processing on the value, so you'll get a framework-specific file wrapper object. For example, you'll get a FileStorage object in Flask.

So I guess that works.
