### ISSUE TITLE
post_load not running with fields.Method schemas

### ISSUE THREAD

**Issue by mike-lerch** [marshmallow-code/marshmallow#602]
I am attempting to create a schema that uses a specific class name based on some criteria. 

I wrote a useless (but generic) example to illustrate the issue I am running into:

```python
from marshmallow import Schema, fields, post_load


class User:
    def __init__(self, name):
        self.name = name


class SpecialUser(User):
    def __init__(self, special_stuff, **kwargs):
        super().__init__(**kwargs)
        self.special_stuff = special_stuff


class UserSchema(Schema):
    name = fields.Str(required=True)

    @post_load
    def make_user(self, data):
        return User(**data)


class SpecialUserSchema(Schema):
    name = fields.Str(required=True)
    special_stuff = fields.Str(required=True)

    @post_load
    def make_special_user(self, data):
        return SpecialUser(**data)


class UserEvent:
    def __init__(self, user, event):
        self.user = user
        self.event = event


class UserEventSchema(Schema):
    user = fields.Method('get_user_field', required=True)
    event = fields.Str(required=True)

    def get_user_field(self, obj):
        if obj.get('user').get('name') == 'jim':
            return SpecialUser
        return User


user_bob = UserSchema().load({'name': 'bob'})
assert type(user_bob.data) is User

user_jim = UserSchema().load({'name': 'jim'})
assert type(user_jim.data) is User

special_user_jim = SpecialUserSchema().load({'name': 'jim', 'special_stuff': 'is special'})
assert type(special_user_jim.data) is SpecialUser, type(special_user_jim.data)

user_event = UserEventSchema().load({'user': {'name': 'jim', 'special_stuff': 'is special'},
                                     'event': 'said hello world'})

assert type(user_event.data.get('user')) is User, type(user_event.data.get('user'))
```

The last assert fails. 

It appears that a field derived from `fields.Method` do not fire their post_load functions, so the object comes back as a dictionary instead of a `User`. 

If this were a `fields.Nested`, instead of a `fields.Method` returning a `fields.Nested`, the post_load would have fired and I get back a `User` object. However, I lose the ability to load `SpecialUser` objects.

Also a question: Is there a better way to do this? I feel like I'm just missing something obvious. 😄 

This example is very trimmed down and sanitized, but the actual project has many equivalent child classes beyond just `SpecialUser` and many equivalent schemas beyond just `SpecialUserSchema`, each with their own additional and unique required fields. Even if `fields.Method` behaved as I expected, this method would not scale as the `get_user_field` method would have to be copied everywhere I use the `UserSchema`. 

Thanks!

**Comment by lafrech** [comment]
Looks like polymorphism. You might be interested in https://github.com/maximkulkin/marshmallow-oneofschema.

**Comment by sloria** [comment]
I think the problem is that you are not passing the `deserialize` argument to `fields.Method`.

You can modify UserEventSchema like so to select a schema based on the `name` in the input:

```python
class UserEventSchema(Schema):
    user = fields.Method(deserialize='get_user_field', required=True)
    event = fields.Str(required=True)

    def get_user_field(self, value):
        if value.get('name') == 'jim':
            return SpecialUserSchema().load(value).data
        return UserSchema().load(value).data

assert type(user_event.data.get('user')) is SpecialUser, type(user_event.data.get('user'))
```

The assertion passes.

As @lafrech mentioned, you might want to check out marshmallow-oneofschema or [marshmallow-polyfield](https://github.com/Bachmann1234/marshmallow-polyfield).

Hope this helps!

**Comment by mike-lerch** [comment]
https://github.com/Bachmann1234/marshmallow-polyfield did the trick. Thank you so much!
