### ISSUE TITLE
Denormalize on deserialization

### ISSUE THREAD

**Issue by dtheodor** [marshmallow-code/marshmallow#606]
Is there a built-in way to denormalize when dealing with data with nested relationships, something like this: 

Deserialize this input:

```json
{
  "id": "id",
  "name": "parent",
  "children": [{
      "id": "id2",
      "name": "child1"
    }, {
      "id": "id3",
      "name": "child2"
    }]
}
```

To this

```json
[{
  "parent_id": "id",
  "parent_name": "parent",
  "id": "id2",
  "name": "child1"
}, {
  "parent_id": "id",
  "parent_name": "parent",
  "id": "id3",
  "name": "child12"
}]
```

Basically output a list of items, that are derived from some nested list, and enrich the items with data from their parent

**Comment by sloria** [comment]
You can do this sort of post-processing in a `post_load` or `post_dump` method. See https://marshmallow.readthedocs.io/en/latest/extending.html#pre-processing-and-post-processing-methods .
