### ISSUE TITLE
pre and post processing

### ISSUE THREAD

**Issue by silenius** [marshmallow-code/marshmallow#607]
Hello,

Let's say I have the following (simplified) code:

```python
import json

from marshmallow import Schema
from marshmallow import pre_load
from marshmallow import post_dump
from marshmallow.fields import Dict

class MySchema(Schema):
  props = Dict(required=False)

  @pre_load
  def pre_process(self, data):
    data['props'] = json.loads(data['props'])

  @post_dump
  def post_process(self, data):
    data['props'] = json.dumps(data['props'])
```

(in the end `props` is saved/loaded in/from a PostgreSQL JSON column)

Imagine the following use case:

1. I'm serializing an object (SQLAlchemy entity) according to the Schema’s fields (`.dump(entity)`)
2. I'm populating a form with the serialized data (`props` is now a serialized string)
3. The form is submitted by the user
4. I'm loading submitted data (`.load(request.POST)`), as I have a `@pre_load` decorator `props` is now a `dict`
5. Unfortunately let's say validation fails, and that I have to re-submit the form
6. Problem is that `post_process` is not called and that `props` is still a dict, whereas some client-side code expect a `string`

Is there a proper "Marshmallow-way" to handle this?

Thanks!

(BTW is there an "official" place to ask questions like this?)

**Comment by silenius** [comment]
another option would be to use:
```python
props = Function(lambda obj: json.dumps(obj.props), lambda value: json.loads(value), required=False)
```
and re-submit the form with the "raw" data

**Comment by sloria** [comment]
A perhaps more re-usable approach would be to use a custom field.

```python
from marshmallow import fields

class JSON(fields.Dict):

    def _deserialize(self, value, attr, data):
        decoded = json.loads(value)
        return super()._deserialize(decoded, attr, data)

    def _serialize(self, value, attr, obj):
        ret = super()._serialize(value, attr, obj)
        return json.dumps(ret)
```

Which you could use like so:

```python

import json
from marshmallow import Schema, ValidationError

class MySchema(Schema):
    props = JSON(required=False, validate=[validate_props])


sch = MySchema(strict=True)

data = {'props': json.dumps({'foo': 9})}

try:
    res = sch.load(data)
except ValidationError as err:
    print('invalid')
    print(err.data)
else:
    print('valid')
    print(res.data)
```

The output will be:

```
invalid
{'props': '{"foo": 9}'}
```

Hope this meets your use case. 

P.S. The issue tracker is the correct place to ask questions like this. =)

**Comment by silenius** [comment]
excellent, thank you :smiley:
