### ISSUE TITLE
Support for read-only fields

### ISSUE THREAD

**Issue by pmdarrow** [marshmallow-code/marshmallow#61]
It would be nice to have the ability to mark fields as read-only. When deserializing, validation should fail if field(s) marked as read-only are present in the target dictionary.

**Comment by sloria** [comment]
You could do something like:

``` python

from marshmallow import fields, Schema, ValidationError

def read_only(val):
    if val is not fields.missing:
        raise ValidationError('Cannot pass a read-only field.')


class AlbumSchema(Schema):
    published = fields.Date(validate=read_only)
    title = fields.Str()


s = AlbumSchema()
result = s.load({'published': '2014-11-18'})
print(result.errors)  # {'published': ['Cannot pass a read-only field.']}
```

**Comment by pmdarrow** [comment]
This works, but what do you think about making `readonly` an optional keyword argument, just like `required` is? Django REST Framework, Cerberus and a number of other serilzation / validation libraries implement it this way and I personally find it very convinient.

**Comment by rozenm** [comment]
I looked for a read only attribute as well. 
Used to working with Django Rest FrameWork 
and the read only flag is quite handy.

**Comment by sloria** [comment]
I will consider adding a read-only flag as a kwarg. Thank you for your input.

**Comment by philtay** [comment]
+1

**Comment by sloria** [comment]
I am leaning towards adding this feature, but I will probably call the parameter `dump_only` or something similar, for consistency with `load_only` as described in #87. This would also avoid confusion over what "read" and "write" mean (keep in mind that marshmallow isn't meant to do any sort of "writing").

Thoughts?

**Comment by sloria** [comment]
Added in https://github.com/marshmallow-code/marshmallow/pull/131
