### ISSUE TITLE
Bug: field "attribute" option ignored on deserialization

### ISSUE THREAD

**Issue by vgavro** [marshmallow-code/marshmallow#610]
Field's `attribute` works only for dump, but not for load. This way it's just duplicating `dump_to` functionality. 

Consider following example:
```python
In [4]: import marshmallow as ma

In [5]: class TestSchema(ma.Schema):
   ...:     fld_name = ma.fields.Str(attribute='attr_name', required=True)
   ...: 

In [6]: TestSchema().load({'attr_name': 123})
Out[6]: UnmarshalResult(data={}, errors={'fld_name': ['Missing data for required field.']})

In [7]: TestSchema().dump({'attr_name': 123})
Out[7]: MarshalResult(data={'fld_name': '123'}, errors={})
```

The question is - *is it expected behaviour*, have I missed something, or should i create pull request? Thank you.

**Comment by sloria** [comment]
`attribute` specifies the attribute to use for objects to serialize, not deserialize. If you want to alias an input value to `load`, use `load_from`.

Perhaps this can be made clearer in the documentation. Docs PRs welcome. =)
