### ISSUE TITLE
Proposal: field "load_from" option - lookup for dotted path

### ISSUE THREAD

**Issue by vgavro** [marshmallow-code/marshmallow#611]
It would be extremely useful to have dotted-lookup for loading objects, like it template engines for example.
Consider the following code:
```python
In [5]: class TestSchema(ma.Schema):
   ...:     fld_count = ma.fields.Str(load_from='fld.count', required=True)
   ...:     first_item_color = ma.fields.Str(load_from='items.0.color', required=True)
   ...:     

In [6]: TestSchema().load({'fld': {'count': 1}, 'items': [{'color': 'red'}]})
Out[6]: UnmarshalResult(data={}, errors={'items.0.color': ['Missing data for required field.'], 'fld.count': ['Missing data for required field.']})
```

There is some caveats, for example when dealing with dictionary with dotted key of same name - lookup will be ambiguous, but i don't think this can be a big problem. But if you consider this as backward-compatibility problem, option can be named "load_from_path".
I understand that we can use fields.Nested, but it will be problem if we want several fields on root schema from same object in nested schema.
Also I understand that we can use `@pre_load`, but it's obvious better to keep things in declarative way.
Should we extend `load_from`, or create new option for this? Should I create pull request? Thank you.

**Comment by sloria** [comment]
I am not entirely opposed to this feature, but I would be hesitant to integrate this if it added complexity to the codebase. Users can already use `fields.Method(deserialize=...)` for complex cases.

**Comment by douglas-treadwell** [comment]
I agree with @sloria, users can already use `fields.Method`.  Hopefully these cases are rare enough that one or two Method fields are not burdensome to write.  Is that not true in your case?

**Comment by vgavro** [comment]
@douglas-treadwell Actually yes, I'm using `fields.Function` and `fields.Method` in this cases and it's ok, just thought that it would be more handy with less code. To resolve object path may be used this function https://github.com/vgavro/flask-vgavro-utils/blob/master/flask_vgavro_utils/utils.py#L70
But I agree that it's adding complexity. Should I close this ticket?

**Comment by slint** [comment]
An issue that comes up when using `fields.Method/Function` is that from that point on all "magic" that comes with `fields.Nested` is now a reponsibility of the method/function. Example:

```python
class ItemSchema(Schema):
    id = fields.String(required=True)
    type = fields.String(validate=OneOf(['normal', 'special']))

class ContentSchema(Schema):
    items = fields.Nested(ItemSchema, load_from='item_array', many=True)

# vs.

class WeirdContentSchema(Schema):
    items = fields.Method('load_items', many=True)
    def load_items(self, obj):
        # ...some custom logic that cannot utilize `ItemSchema`
        # usually re-inventing what `fields.Nested` does...
        return {...}

# vs. (not possible atm)

class WeirdContentSchema(Schema):
    items = fields.Nested(ItemSchema, load_from='foo.item_array', many=True)
```

I've come across such cases noumerous times when consuming "verbose/deeply-nested" APIs and every time there's a different hack involved using `@pre_load`, `fields.Methods` and the likes. 

Is there some cleaner way to load something `ItemSchema`, while keeping validation errors?

**Comment by sloria** [comment]
This is basically the same as what was proposed in #1298 . As I said on that PR, I don't think using `load_from` or `data_key` is the optimal way to meet the use case because there may be valid use cases where the external representation has periods in the keys. Instead I think this can be solved by a custom field (see my [`Reach`](https://github.com/marshmallow-code/marshmallow/issues/1311#issuecomment-513478342) recipe). Discussion of whether not to include such a field can happen in https://github.com/marshmallow-code/marshmallow/issues/1315 , so closing this for now.
