### ISSUE TITLE
Add `include` kwarg to constructor

### ISSUE THREAD

**Issue by RussianCow** [marshmallow-code/marshmallow#614]
I would love to be able to have certain fields excluded by default, but included only in certain scenarios, without specifying the full list of fields I want every time. For instance, say I have a schema like this:

    class MySchema(Schema):
        id = fields.Integer()
        name = fields.String()
        expensive_field = fields.Function(lambda obj: obj.some_expensive_method())

I don't want `expensive_field` to be serialized 90% of the time, so I would like to be able to do something like this:

    class MySchema(Schema):
        # ...fields from above...
        class Meta:
            fields = ('id', 'name')

    MySchema(include=('expensive_field',))

Currently, it seems that I have to `exclude` the fields I don't want on every use rather than including them only when I need them. Is there currently a way to achieve this? And if not, would it be possible to add this?

**Comment by dradetsky** [comment]
Why not have 2 difft schemas, `MySchema` as above, and 

```
class MyMoreCommonSchema(MySchema):
    class Meta:
        exclude = ['expensive_field']
```

and use whatever procedure decides whether to pass the include field to instead decide which schema to use?

**Comment by RussianCow** [comment]
Thanks for the response! I don't want to do that because it's not necessarily all or nothing: I may want one or two of the optional fields but not all of them. If this is a use case you'd be open to supporting, I wouldn't mind submitting a PR when I have time; if not, that's fine too, just let me know either way. Or if you have any other ideas about how to handle this case, I'm all ears!

Thanks again!

**Comment by dradetsky** [comment]
I'm not actually authorized to merge code for marshmallow (although it's nice of you to assume I am), I'm just trying to be helpful. As far as I can tell, you want some combination of 2 different schemas, and maybe some other thing. So basically, like the following sloppy code:

```python
class A(Schema):
    a = Int()
    b = Str()

class B(A):
    x = Function()
    y = Method()
    z = Dict()

# typical

A().dump(input).data

# atypical 0: a, b, z

B(exclude=[x, y]).dump(input).data

# atypical 1: a, b, x

B(exclude=[y, z]).dump(input).data
```

And you want to be able to specify atypical 0 by `[z]` instead of by `[x, y]`. Have I got that right? If so, is there some reason you can't use [set differences](https://docs.python.org/3.6/library/stdtypes.html#set.difference)?

**Comment by RussianCow** [comment]
Ah, my mistake, I'm not sure why I made that assumption. :) Thanks either way!

You are correct about the use case. What do you mean when you say to use set differences? What sets are you referring to?

**Comment by sloria** [comment]
@russiancow Sorry for the delayed response to this.

As @dradetsky pointed out, I think your use case can be met without adding any API surface.

You can use set differences to get the excluded fields. From the code snippet above:

```
excluded = B's fields - A's fields - included fields
```

So, in code, you could do something like

```python
from marshmallow import Schema, pprint
from marshmallow.fields import *

class A(Schema):
    a = Int()
    b = Str()

    class Meta:
        ordered = True

class B(A):
    x = Int()
    y = Str()
    z = Dict()

    def __init__(self, *args, **kwargs):
        included = kwargs.pop('included', set())
        exclude = kwargs.pop('exclude', None) or set(self._declared_fields) - set(A._declared_fields) - set(included)
        kwargs['exclude'] = exclude
        super().__init__(*args, **kwargs)

a = A()
b = B()

data = {
    'a': 42,
    'b': 'foo',
    'x': 24,
    'y': 'bar',
    'z': {'baz': 424},
}


print("typical: a, b")
pprint(B().dump(data))

print("atypical 0: a, b, z")
pprint(B(included=['z']).dump(data))

print("atypical 0: a, b, x")
pprint(B(included=['x']).dump(data))
```

Output:

```
typical: a, b
{"a": 42, "b": "foo"}
atypical 0: a, b, z
{"a": 42, "b": "foo", "z": {"baz": 424}}
atypical 0: a, b, x
{"a": 42, "b": "foo", "x": 24}
```
