### ISSUE TITLE
Validation does not return errors when using 'attribute' in a field

### ISSUE THREAD

**Issue by gdalmau** [marshmallow-code/marshmallow#615]
I have the following code creating two different objects. 

The one named 'WorkingModel' uses the field name directly. 

The second one called 'NonWorkingModel', which doesn't seem to be working, uses the attribute name instead. 

When I validate both models the first one is able to find the error but the second one isn't.

```python
from marshmallow import Schema, fields, validate

class WorkingModel(Schema):
    str = fields.String(validate=validate.Length(max=5, error='String is too long'))

class NonWorkingModel(Schema):
    str = fields.String(
        attribute='sample_string',
        dump_to='SampleString',
        validate=validate.Length(max=5, error='String is too long')
    )

working_model = WorkingModel()
working_obj = {'str': '123456'}
errors = working_model.validate(working_obj)
print errors
# Output: 
# {'str': ['String is too long']}


non_working_model = NonWorkingModel()
non_working_obj = {'sample_string': '123456'}
errors = non_working_model.validate(non_working_obj)
print errors
# Output: 
# {}
```

**Comment by timster** [comment]
I think you are probably looking for `load_from`

```python
class NonWorkingModel(Schema):
    str = fields.String(
        load_from='sample_string',
        dump_to='SampleString',
        validate=validate.Length(max=5, error='String is too long')
    )


non_working_model = NonWorkingModel()
non_working_obj = {'sample_string': '123456'}
errors = non_working_model.validate(non_working_obj)

print(errors)
# {'sample_string': ['String is too long']}

```

**Comment by gdalmau** [comment]
Sorry if I didn't explain well and thanks for your fast reply.

I want to validate the object passed to the Schema and if it doesn't return erros then get the dump or the load, but I want to specify the name that the model should expect (using `attribute=` or `load_from=`) and the name which the model should do the dump to (`dump_to=`).

Another example with code:

```python
class NonWorkingModel(Schema):
    str = fields.String(
        load_from='sample_string',
        dump_to='SampleString',
        validate=validate.Length(max=5, error='String is too long')
    )

non_working_model = NonWorkingModel()
non_working_obj = {'sample_string': '123'}
errors = non_working_model.validate(non_working_obj)
if not errors:
    obj = non_working_model.dump(non_working_obj)
    print obj.data
    # Output:
    # {}
```

If there is no errors when validating the model, I would want to get an object like this:

```python
obj = {
    'SampleString': '123'
}
```

**Comment by timster** [comment]
Ah so in that case you need ``attribute``

```python
class NonWorkingModel(Schema):
    str = fields.String(
        load_from='sample_string',
        attribute='sample_string',
        dump_to='SampleString',
        validate=validate.Length(max=5, error='String is too long')
    )
```

``load_from`` = field to get data from when validating
``attribute`` = field to get date from when outputting
``dump_to`` = field to use in output dictionary

**Comment by gdalmau** [comment]
I thought `attribute` would work with both `validate` and `dump` methods so I made this issue.

It can be closed then.

Thanks for your reply :smile:
