### ISSUE TITLE
using an attribute named items when serializing a dict 

### ISSUE THREAD

**Issue by rozenm** [marshmallow-code/marshmallow#62]
When serializing  a dict with an attribute called "items"
the fails to get the correct "items" value and instead gets the items function of the dict object.
The problem is in utils line 298:
    if isinstance(key, basestring) and hasattr(obj, key):
hasattr(obj,key) == True.

**Comment by sloria** [comment]
I recommend overriding how values are pulled during serialization. See this relevant section of the docs: http://marshmallow.readthedocs.org/en/latest/extending.html#overriding-how-attributes-are-accessed

**Comment by rozenm** [comment]
Thanks, looks like a good work around.
But are you planning on fixing this issue? Do you want me to make a PR?
I still think it's a bug.

**Comment by sloria** [comment]
Yes, this is a bug that should be addressed. I can fix this sometime over the weekend, but if you'd like to send a PR, I would gladly review and merge it!
