### ISSUE TITLE
Valid byte representations of UUIDs fail

### ISSUE THREAD

**Issue by JeffBerger** [marshmallow-code/marshmallow#626]
If a byte representation of a UUID is passed into a marshmallow UUID field it will be flagged as invalid.  This is because the UUID constructor does not tell the difference between a hex string and a byte representation and will try and parse the byte representation as a hex string and fail.  To create a UUID from a byte representation the bytes must be passed into a `bytes` kwarg in the constructor.

Many databases use the byte representation of UUIDs because it is more compact and indexing is more efficient.  For example this package: https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.uuid .  While there is an option to store the UUIDs as chars it is less efficient and other users that are dealing with legacy systems that already have byte representations of UUIDs will not be able to use the UUID field in marshmallow.  Since this is a general issue involving UUIDs an not platform specific I thought it appropriate for the marshmallow core.

The change is small and I already made a pull request #625 .

**Comment by douglas-treadwell** [comment]
@JeffBerger While you're waiting for feedback on #625, what about creating a Byte[s]UUID field type?

**Comment by sloria** [comment]
This was done in 3.0.0b11
