### ISSUE TITLE
Serialized then deserialized Datetimes are not equal

### ISSUE THREAD

**Issue by sm11963** [marshmallow-code/marshmallow#627]
As a new user, I would expect the following code to work correctly:
```python
from marshmallow import Schema, fields
from datetime import datetime as dt, timezone as tz

class User():
    def __init__(self, datetime):
        self.datetime = datetime

class UserSchema(Schema):
    datetime = fields.DateTime()

user = User(dt.now())
serialized = UserSchema().dump(user).data
deserialized = UserSchema().load(serialized).data

assert user.datetime == deserialized['datetime']
```

Now since the DateTime field serializes differently when python-dateutil is available, there are two cases:

## python-dateutil is available

The above will fail since the utc timezone is added to the serialized datetime, which was timezone unaware before serialization.

## python-dateutil is not available

It will also fail in this case, since when python-dateutil is not available **neither microsecond or timezone** is deserialized in ISO format. They are however correctly serialized.

**Comment by sm11963** [comment]
Here is the code for deserializing iso datetime:
```python
def from_iso(datestring, use_dateutil=True):
    """Parse an ISO8601-formatted datetime string and return a datetime object.

    Use dateutil's parser if possible and return a timezone-aware datetime.
    """
    if not _iso8601_re.match(datestring):
        raise ValueError('Not a valid ISO8601-formatted datetime string')
    # Use dateutil's parser if possible
    if dateutil_available and use_dateutil:
        return parser.parse(datestring)
    else:
        # Strip off timezone info.
        return datetime.datetime.strptime(datestring[:19], '%Y-%m-%dT%H:%M:%S')
```

It seems like we are intentionally ignoring the timezone, so I am curious what is the reason for this??
Is it due to restrictions with Python 2?

**Comment by lafrech** [comment]
Could be related to https://github.com/marshmallow-code/marshmallow/issues/520.

**Comment by danieljfarrell** [comment]
A potential workaround (if you don't mind dropping microsecond precision and timezone support) is using `.replace(microsecond=0)` on datetime objects.

```python
from marshmallow import Schema, fields
from datetime import datetime as dt, timezone as tz

class User():
    def __init__(self, datetime):
        self.datetime = datetime

class UserSchema(Schema):
    datetime = fields.DateTime()

user = User(dt.now().replace(microsecond=0))  # <- this
serialized = UserSchema().dump(user)
deserialized = UserSchema().load(serialized)

assert user.datetime == deserialized['datetime']
```

**Comment by lafrech** [comment]
This is partly fixed in `dev` branch.

dateutil is not used anymore. TZ and microseconds are correctly parsed.

Naive/Aware consistency is being addressed in #1234, #1278.

**Comment by palango** [comment]
@lafrech I just ran into that problem. Can you maybe release a new RC with these fixes?

**Comment by sloria** [comment]
@palango I've cut 3.0.0rc8 that has the relevant change.
