### ISSUE TITLE
Deserialization errors not accessible from exception

### ISSUE THREAD

**Issue by miracle2k** [marshmallow-code/marshmallow#63]
I'd like to parse incoming request data using schema.load() and have my framework handle any parsing errors.

It seems that returning a clear error message to the user is hard to do, because I cannot figure out how to know from an UnmarshallingError which field actually failed.

**Comment by sloria** [comment]
Can you please provide a code snippet to show where you are receiving the error? `Schema#load` should return a dictionary of validation errors (keyed by field name) as the second element of its return value.

**Comment by miracle2k** [comment]
Yes, but I have set strict=True to raise an exception, and I want to let the exception bubble up to my Rest framework, so I can handle request parsing exceptions in one single place. I don't have access to the return value at that point, but I think it makes sense to attach it to the exception.

**Comment by sloria** [comment]
Oh, I see now. I didn't realize you were using `strict=True`. 

OK, I don't see a problem with storing the field name and field object on the `UnmarshallingError`. I will implement this shortly.

**Comment by sloria** [comment]
This has been added on latest dev branch.
