### ISSUE TITLE
Deserializing Nones into SQLAlchemy objects

### ISSUE THREAD

**Issue by luka-zitnik** [marshmallow-code/marshmallow#630]
Hi guys,

Are you familiar with this error?

`<class 'sqlalchemy.orm.exc.UnmappedInstanceError'>, UnmappedInstanceError("Class 'builtins.dict' is not mapped",)`

It appears when working with dictionaries with `None`s deserialized into SQLAlchemy objects.

**Comment by luka-zitnik** [comment]
I guess this and similar problems are resolved with https://github.com/marshmallow-code/marshmallow-sqlalchemy?

**Comment by sloria** [comment]
I'm not quite sure what the source of your problem is without seeing more of the code. Indeed, you might try out marshmallow-sqlalchemy to see if it handles your use case. Closing this for now, feel free to re-open and add more details if necessary.
