### ISSUE TITLE
Is it possible to exclude fields from serialization at dump time?

### ISSUE THREAD

**Issue by johnwheeler** [marshmallow-code/marshmallow#631]
Is it possible to exclude fields from serialization at dump time?
Something like

```
UserSchema().dump(user, exclude=('password',))
```
instead of having to exclude at the `Meta` class level?

Thanks

**Comment by Dem0n3D** [comment]
Answer is in marshmallow-code/flask-marshmallow#50

**Comment by ThiefMaster** [comment]
What about cases where the schema instance is used in many places? Then moving the exclude argument to the schema's constructor is not an option... It's also not very obvious why `only` is allowed in `dump()` while `exclude` isn't.

**Comment by lafrech** [comment]
I don't think `only` is allowed either.

The common way to do that is to share the Schema class but not the instance, and instantiate the schema with different options when needed. See discussion here: https://github.com/marshmallow-code/marshmallow/issues/761.
