### ISSUE TITLE
[Question] Skip output for None fields?

### ISSUE THREAD

**Issue by upmauro** [marshmallow-code/marshmallow#633]
Is possible remove None fields from serialize dumps?

Ex.:

`schema.dump({'id': 1,'value_null': None,}).data`

Want output like

`{'id': 1} `

**Comment by NikosVlagoidis** [comment]
A solution might be if you use the post_dump decorator and clear the field with None value

**Comment by sloria** [comment]
Yes, a post-dump method is the correct way to achieve this. See here: https://github.com/marshmallow-code/marshmallow/issues/229#issuecomment-134387999
