### ISSUE TITLE
Broken passing of context inside fields.List(fields.Nested(SomeSchema))

### ISSUE THREAD

**Issue by YuppY** [marshmallow-code/marshmallow#634]
If schema is declared like this:
```python
class ChildSchema(Schema):
    foo = fields.Method('dump_foo')
    def dump_foo(self, obj):
        print 'context is', self.context
  
class ParentSchema(Schema):
    child = fields.List(fields.Nested(ChildSchema))
```
Then `context` is saved on first call and ignored on further calls:
```python
>>> ParentSchema(context={'bar': 1}).dump({'child': [{}]})
context is {'bar': 1}
MarshalResult(...)
>>> ParentSchema(context={'baz': 2}).dump({'child': [{}]})
context is {'bar': 1}
MarshalResult(...)
>>> ParentSchema().dump({'child': [{}]})
context is {'bar': 1}
MarshalResult(...)
```

It is because `copy.deepcopy(self._declared_fields)` doesn't copy `List.container` field and schema with `context` is cached inside `Nested` field and saved inside `_declared_fields`.

**Comment by justanr** [comment]
Any reason to do it like that instead of declaring the nested field to be many? This sounds like a bug to me but on the other hand, is it a use case that Marshmallow should support?

**Comment by jssuzanne** [comment]
Hi, I have the same issue, In my mind the solution is to allow the breaking of the cache in Nested field. because the context is propagated only when the making of the cache

**Comment by jssuzanne** [comment]
Travis sound good for the PR #696

**Comment by alexeysofin** [comment]
@jssuzanne #696 completely breaks nested schemas, because when self.withcache == False,self.__schema will not be initialized at all. Am I getting something wrong? :)

**Comment by jssuzanne** [comment]
You may close this PR, I created my own nested field without cache for my need.
