### ISSUE TITLE
way to validate two attr in the same @validate decorator??

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/marshmallow#638]
```
class AuthorSchema(Schema):
    id = fields.Int(dump_only=True)
    first = fields.Str()
    last = fields.Str()

    @validates('id')
     def validate_id(self, value):
          id = value  # I can get the id value here.
          first = ???             #how can I get the first value ,,???
```

my problem is that how can I get the first value in the inline validate function???
I try to use self to get the value, but havn't find a way to get the value ...

**Comment by lafrech** [comment]
Use [schema-level validation](http://marshmallow.readthedocs.io/en/latest/extending.html#schema-level-validation).

**Comment by sloria** [comment]
Correct; use `@validates_schema` for your use case.

**Comment by ghost** [comment]
thks .@validates_schema works for me..
