### ISSUE TITLE
many=True renders wrong when given nothing to render

### ISSUE THREAD

**Issue by nickretallack** [marshmallow-code/marshmallow#64]
```
from marshmallow import Schema, fields, pprint

class User(object):
    def __init__(self, name, email, age=None):
        self.name = name

class ChildSchema(Schema):
    name = fields.String()

class ParentSchema(Schema):
    name = fields.String()
    children = fields.Nested(ChildSchema, many=True)

user = User(name="Monty")
schema = ParentSchema()
result = schema.dump(user)
pprint(result.data)
# -> {'children': {'name': ''}, 'name': u'Monty'}
```

I would expect the result to be `{'children': [], 'name': u'Monty'}`.  If I set a field to many=True, it should always be a list, no exceptions.  What I'm getting instead looks like a mistake.

**Comment by sloria** [comment]
In your example, `collaborators` is not an attribute of `user`, so the schema tries to `None` with all the declared fields.

Indeed, this is the incorrect behavior. Will fix this shortly.

**Comment by sloria** [comment]
Fixed in https://github.com/sloria/marshmallow/commit/39fe6f4fbc6c73f803b74c4e2c29ea12fc06bcaf
