### ISSUE TITLE
Rename class Meta to class Options

### ISSUE THREAD

**Issue by douglas-treadwell** [marshmallow-code/marshmallow#642]
Like [Schematics](https://schematics.readthedocs.io/en/latest/usage/models.html).

```python
class Meta
```
is too similar to \_\_metaclass__ or class MyClass(metaclass=...).

class Options is more semantically accurate for what this object is, and there's precedent for using that name, so I support renaming it.  For backward compatibility, marshmallow could check for the presence of either.

**Comment by sloria** [comment]
I'm not opposed, though `Meta` came to be a common convention thanks to Django, WTForms, and others. Not sure the benefit is worth it. I'll keep this open for feedback though.

**Comment by douglas-treadwell** [comment]
My proposal is to support both.

**Comment by sloria** [comment]
I would rather not have two names for the same thing. Consumer libraries would need to know about both names, which is burdensome.

**Comment by douglas-treadwell** [comment]
Good point.  I withdraw this proposal.  Actually I was working on something recently where I provided two hooks for the same configuration and ran into a bug, so I can imagine in a codebase that handles as many cases as Marshmallow it would lead to several bugs.
