### ISSUE TITLE
Add Polymorphic Schemas

### ISSUE THREAD

**Issue by Dr-ZeeD** [marshmallow-code/marshmallow#649]
I know that currently the marshmallow-polyfield package exists that adds polymorphism to nested fields. But I'd be very interested in a polymorphic schema, much akin to what is feasible using [SQLAlchemy's joined table inheritance](http://docs.sqlalchemy.org/en/latest/orm/inheritance.html#joined-table-inheritance)

Would this be something that may be implemented in marshmallow if someone implements it?

**Comment by smilledge** [comment]
Have you seen [marshmallow-oneofschema](https://github.com/maximkulkin/marshmallow-oneofschema)?

But +1 for adding polymorphic schemas and fields into marshmallow.

**Comment by sloria** [comment]
We don't have plans to add this feature to marshmallow core in the near future. For now, marshmallow-oneofschema is the way to go.
