### ISSUE TITLE
Inconsistent behavior between dump(obj, many=True) and Schema(many=True)

### ISSUE THREAD

**Issue by svenstaro** [marshmallow-code/marshmallow#65]
Doing

```
    schema = MySchema(many=True)
    print(schema.dump(mythings))
```

I get the correct behavior and everything works fine. However, doing

```
    schema = MySchema()
    print(schema.dump(mythings, many=True))
```

results in

`myfile.py:29: in get
    print(schema.dump(mythings, many=True))
env/lib/python3.4/site-packages/marshmallow/schema.py:435: in dump
    self._update_fields(obj)
env/lib/python3.4/site-packages/marshmallow/schema.py:583: in _update_fields
    ret = self.__filter_fields(field_names, obj)
env/lib/python3.4/site-packages/marshmallow/schema.py:630: in __filter_fields
    attribute_type = type(obj_dict[key])
E   TypeError: list indices must be integers, not str`

Something's up here.

**Comment by sloria** [comment]
Can you please provide a full snippet to reproduce the problem? What data structure is `mythings`?

**Comment by svenstaro** [comment]
The problem is that in __filter_fields() you only check against self.many (but don't respect the many that was just was just passed into dump()). Same goes for _postprocess(). I don't think you need any additional code of mine here as the bug is right there but I can try providing a minimal test case that reproduces the problem if you really want. However, I think reasoning about the code, we can already see where it goes wrong.

I do agree that self.many should not be changed and my pull request is bad. The whole idea of having dump() take many as a parameter is that the object stays unchanged, after all. This being the case, many needs to be passed through all called functions instead, then.

**Comment by sloria** [comment]
@svenstaro You are correct. `many` will have to be passed through to those private functions. Would you like to update your pull request?
