### ISSUE TITLE
String fields should return an error when given non-UTF-8

### ISSUE THREAD

**Issue by dan-blanchard** [marshmallow-code/marshmallow#650]
Currently, if a user specifies a `bytes` value for a `String` field that is not UTF-8, marshmallow will raise a `UnicodeDecodeError`. A more sensible thing to expect from a validation library like marshmallow would be for it to return an error message about this not being a valid UTF-8 `String`.

**Comment by cwisecarver** [comment]
@sloria Any thoughts on this? I can make a PR if it will help.

**Comment by sloria** [comment]
@dan-blanchard @cwisecarver Sorry for the delayed response; this one fell through the cracks. Yes, I think the proposed behavior is correct. I would certainly review and merge a PR for this.

**Comment by sloria** [comment]
This is fixed in 0.15.0.

**Comment by Chris2048** [comment]
Hi. This fix wraps the ensure_text_type call in the _deserialize method with a try loop; might this also be needed in the _serialize method?
