### ISSUE TITLE
Number fields does not handle the nan value

### ISSUE THREAD

**Issue by jbouzekri** [marshmallow-code/marshmallow#651]
This is really an edge case but it could lead to bug in program. `fields.Number` does not handle the python `nan` value.

If I define this schema : 

``` python
class MySchema(Schema):
    test = fields.Number(required=True, allow_none=False)
```

And I submit this query string `test=NaN`. Then the schema does not detect any error and the `test` param gets the python `nan` value

**Comment by lafrech** [comment]
Fixed in https://github.com/marshmallow-code/marshmallow/pull/945.
