### ISSUE TITLE
Contribute "official" Marshmallow Dash docset

### ISSUE THREAD

**Issue by jsynowiec** [marshmallow-code/marshmallow#655]
Hey, I don't know if you are familiar with a tool called [Dash](https://kapeli.com/dash) or one of its Windows or Linux alternatives but it would be nice to have "officially" maintained Marshmallow docset.

You can read more about contributing docsets here: [Dash-User-Contributions#contribute-a-new-docset](https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset)

**Comment by sloria** [comment]
I use Dash, but I don't have experience writing docsets. I would rather not take on maintenance of a docset right now. Ideally, it could be maintained separately in a different repo. Closing for now.
