### ISSUE TITLE
Proposal: Add a class Meta option to prevent adding a class to the internal registry

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#660]
## Purpose 

Implement a way to bypass marshmallow's internal class registry when it isn't necessary in order to optimize memory usage.

## Proposed API

```python
class MyNonRegisteredSchema(Schema):
    class Meta:
        register = False
```

**Comment by lafrech** [comment]
In [this comment](https://github.com/marshmallow-code/marshmallow/issues/657#issuecomment-317202762), @jtillman argues that registration could default to `False`.

Referring to a Schema by its name as string is a common use case, a feature that a user may have to use before he gets much experience, so having this working by default, and without scattering the code with Meta classes, is nice. Therefore I'd say let's keep registration at `True` by default.

This memory usage issue is a pitfall for users with more advanced needs. Hopefully, we can assume 
those user should have read a bit of documentation and an explicit warning pointing to this feature should be enough.

This is totally arguable and I don't have a strong opinion either way.

**Comment by sloria** [comment]
> Referring to a Schema by its name as string is a common use case, a feature that a user may have to use before he gets much experience, so having this working by default, and without scattering the code with Meta classes, is nice. Therefore I'd say let's keep this at False.

Isn't this an argument to default to `True`?

**Comment by lafrech** [comment]
Oh, right, sorry. I got mixed up and wrote exactly the opposite of what I was thinking. I fixed my comment.
