### ISSUE TITLE
Use fields.Constant to add function to schema

### ISSUE THREAD

**Issue by CausticYarn** [marshmallow-code/marshmallow#662]
I am trying to add a function as a constant field; not a fields.Function where the function returns the value, I want the value to be the callable function, e.g.:

`def foo(a, b):
  return a+b`

I have tried to use fields.Constant with the function, e.g.:

`field_name = fields.Constant(foo)`

It works fine if the field name is present on the input. However, if the field name is missing, the missing logic treats it as a callable and calls it.

I have also tried to wrap it in a lambda:

`field_name = fields.Constant(lambda: foo)`

and this gets past the missing logic, but it returns the lambda instead of the result of calling the lambda.

Is this a bug in the logic or am I missing something?

**Comment by sloria** [comment]
That does seem to be a bug on the surface. I would certainly review a PR fixing it.

**Comment by lafrech** [comment]
A solution could be to override `serialize`/`deserialize` (the ones without the trailing underscore).

```python
class Constant(Field):
    def __init__(self, constant, **kwargs):
        super(Constant, self).__init__(**kwargs)
        self.constant = constant
        self.missing = constant  # Keep this as it can help introspection like in apispec
        self.default = constant  # Keep this as it can help introspection like in apispec

    def serialize(self, attr, obj, accessor=None):
        return self.constant

    def deserialize(self, value, attr=None, data=None):
        return self.constant
```

But it feels kinda wrong. And it skips validation, unless we add `self._validate(self.constant)` in `deserialize`.

If we do that, why not do it for `Raw` as well? And what about custom `Field`s that would manipulate functions and would have `missing` or `default` values?

Maybe passing functions to `Field`s with `default` or `missing` can't be supported (which perhaps should be documented).

For this `Constant` use case, it is possible to use `post_load` / `post_dump` instead to add the function to the output. Or to subclass `Constant` to do what I did above, which I wouldn't recommend.

**Comment by sloria** [comment]
Closing this, as it has gone stale. Feel free to re-open if this is still relevant.
