### ISSUE TITLE
mypy types annotations

### ISSUE THREAD

**Issue by JulienPalard** [marshmallow-code/marshmallow#663]
I was trying mypy and on the same project I started using marshmallow. So I wrote an approximative and minimal (working for my usage) stub here: https://github.com/JulienPalard/typeshed/tree/marshmallow

I'm unsure if you prefer type annotations in your code or have a stub on python/typeshed.git or nothing so...

**Comment by sloria** [comment]
Thanks for posting. We won't be adding type annotations in the near future. Maybe if/when we decide to support Python 3 only, but we don't have plans for that at the moment.

**Comment by neilsh** [comment]
The marshmallow type annotations in typeshed would be useful for people using Python 3, but don't require the marshmallow project itself to be Py3-only.

**Comment by sloria** [comment]
I would prefer to have type annotations co-located with the codebase rather than typeshed stubs, which run the risk of getting outdated. [1]

We can add annotations as part of https://github.com/marshmallow-code/marshmallow/issues/1120

[1] If someone is up for maintaining typeshed stubs, go for it! I just won't have the time to maintain them myself ATM.

**Comment by lafrech** [comment]
Python 2 will be dropped in Marshmallow 3.

**Comment by JulienPalard** [comment]
Since then, it's possible to package type annotations: https://www.python.org/dev/peps/pep-0561/ but I think the better way is to have them inline. In a nutshell there's three ways for distributing annotations:

1. Write type information inline.
2. Package stubs in the package.
3. Package stube in another package (like typeshed).

**Comment by sloria** [comment]
Yes we will add these inline

**Comment by lafrech** [comment]
Draft PR by @fuhrysteve: https://github.com/marshmallow-code/marshmallow/pull/1259.

**Comment by sloria** [comment]
Types are now checked with mypy, and as of 3.1.0 type information is distributed with the package. Closing this for now; we'll continue to expand type coverage with proximate development, when it makes sense. PRs to expand type coverage are welcome.
