### ISSUE TITLE
validate.URL rejects hostnames with no dots

### ISSUE THREAD

**Issue by sduthil** [marshmallow-code/marshmallow#664]
My current use case:
I use Docker and I need to set some URL fields for the containers to communicate together. The URL fields look like `http://third-party/test`, where `third-party` is the hostname of one of the containers.

Currently, `validate.URL` rejects this URL as invalid, because there is no dot in the hostname `third-party`.

Other use cases include:
* a local network in the same subdomain, where hosts are queried using only the name of the machine, not the FQDN, having configured the DNS resolver to search `example.com` automatically, for example `webclient.example.com` querying `webserver` instead of `webserver.example.com`
* a stricly-local network, where there are no public TLD available, and all machines are name `machine1`, `machine2`, etc. very similarly to the Docker internal network

**Comment by jarmani** [comment]
Wouldn't it be interessting to do the same for email validator ?

Currently the validation is not symetrical to browser email validation.
