### ISSUE TITLE
force list

### ISSUE THREAD

**Issue by silenius** [marshmallow-code/marshmallow#666]
Hello,

I wondered if there is a better way to "force" incoming POST data to always be a list (even if there is only one value)  #than:

```python
def as_list(value):
    if isinstance(value, (tuple, list, set, frozenset)):
        return value
    return [value]
```

```python
class PolymorphicOrderSelectionSchema(Schema):

    selected = Nested(FolderOrder, many=True)
    polymorphic_loading = Boolean()
    polymorphic_children = List(Integer)

    # LOAD

    @pre_load
    def pre_load_adapt_polymorphic(self, data):
        data['polymorphic_children'] = as_list(data.get('polymorphic_children', ()))
        return data

#   (...)
```

I'm using Marshmallow with Pyramid (which use WebOb under the hood) with something like:
```python
schema = PolymorphicOrderSelectionSchema()
result, errors = schema.load(request.POST.mixed())
```

but `request.POST.mixed()` doesn't return a list of there is only one parameter (in my case it comes from a `<select multiple>` with only one selected item)

Thanks!

**Comment by sloria** [comment]
Your code about is correct. A pre_load method is the right place to apply the transformation to ensure that the input data is a list.
