### ISSUE TITLE
 pre_load needs to repeat validation

### ISSUE THREAD

**Issue by mei-li** [marshmallow-code/marshmallow#670]
First of all thanks a lot for the nice library to all contributors. We are using as our main validator of all our API input.
 
This issue describes a concern about a common `pre_load` pitfall  (imho) that leads to breaking code.

`pre_load` is used in all examples as a place to clean up data. But essentially to do a safe clean up, one needs to validate the type and the existence of the key most of the times.
For example in the following example that is from the documentation 
```
from marshmallow import Schema, fields, pre_load

class UserSchema(Schema):
    name = fields.Str()
    slug = fields.Str()

    @pre_load
    def slugify_name(self, in_data):
        in_data['slug'] = in_data['slug'].lower().strip().replace(' ', '-')
        return in_data
```
the following will break without validation error
```
schema = UserSchema().load({'name': 'Steve'})
```
I do not have a clear suggestion but it feels quite problematic and error prone. I our case we are doing in all the cases we use `pre_load` for accessing string fields
```
try:
   ....
except (KeyError, AttributeError):
    pass
```
which is not very elegant. 
Maybe stressing this out in the documentation would be enough.

**Comment by sloria** [comment]
Thanks for posting.

I'm not really sure how to address your concern. `pre_load` is meant to receive the un-processed input data, so it follows that there may be missing keys. If you want to do processing after validating `required` fields, then you should use `post_load`.

If there are any updates to the documentation to make more clear, I would gladly accept a PR.
