### ISSUE TITLE
Conditional `required` flag based either fields

### ISSUE THREAD

**Issue by ocervell** [marshmallow-code/marshmallow#675]
I have a particular use case where I have two fields, and exactly one is `required`, but it can be either one of them.

This is my current implementation:

```
class UserSchema(Schema):
   first_attr = ma.Field(required=False)
   second_attr = ma.Field(required=False)
```

I'd like to have a way to specify that if `first_attr` is passed, then `second_attr` is not required, and the other way around, but at least one of those fields **MUST** be passed.

Is there a way to do this in Marshmallow ?

**Comment by lafrech** [comment]
You should use a shema-level validator for this: http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.decorators.validates_schema

**Comment by lafrech** [comment]
For the sake of completeness, here's the doc about schema-level validation: http://marshmallow.readthedocs.io/en/latest/extending.html#schema-level-validation.

Please reopen if you're still stuck.
