### ISSUE TITLE
Instance fields

### ISSUE THREAD

**Issue by DrPyser** [marshmallow-code/marshmallow#680]
Is it possible to have fields specified(defined) by a schema instance(e.g. in a schema's `__init__` method)? 

If not, is there a reason why that shouldn't/couldn't be possible? 

The use case for this is the same as that of any class: to have the class specify attributes that are unchanging accross instances, but to have instances differ among each other on some attributes.

For example, to define a class of schemas for which some fields depend on another schema to be chosen at runtime:

```
class DependentSchema(Schema):
    def __init__(self, dependency, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.dependent_field = dependency.fields["a_field"]

    static_field = fields.Field() 
    class Meta:
        fields = ("static_field", "dependent_field")
```

Thanks.

**Comment by podhmo** [comment]
Yes,  It is possible.

Adding field to `self.fields`.

Below example is adding "extra" field after schema instance is initialized.
(If you want to define subclass like this, on __init__(), it is also ok.)

``` python
from marshmallow import Schema, fields


class S(Schema):
    v = fields.Integer(required=True)


print(S().load({"v": 10}))
print(S().load({"v": 10, "extra": "extra"}))

print("----------------------------------------")

s = S()
s.fields["extra"] = fields.String(required=True)
print(s.load({"v": 10}))
print(s.load({"v": 10, "extra": "extra"}))

# UnmarshalResult(data={'v': 10}, errors={})
# UnmarshalResult(data={'v': 10}, errors={})
# ----------------------------------------
# UnmarshalResult(data={'v': 10}, errors={'extra': ['Missing data for required field.']})
# UnmarshalResult(data={'v': 10, 'extra': 'extra'}, errors={})
```

**Comment by DrPyser** [comment]
Cool, thanks.
