### ISSUE TITLE
Tests on Python 3.4 in TravisCI fails

### ISSUE THREAD

**Issue by monotaro-yasushi-masuda** [marshmallow-code/marshmallow#681]
Currently, test in TravisCI on Python 3.4 is failing, causing check failure for recent pull-requests.
Something seems to be weird with six installation for 3.4 build image.

Explicitly upgrading six will fix it. Please see 
https://github.com/marshmallow-code/marshmallow/pull/678/commits/9905da8572d41a3381f1ab8b8f10054ca5ccddd7

Thanks

**Comment by sloria** [comment]
Thanks for the workaround. The builds should now be fixed.
