### ISSUE TITLE
Schema dump method does not validate?

### ISSUE THREAD

**Issue by larsks** [marshmallow-code/marshmallow#682]
According to the docs:

> Serialize objects by passing them to your schema’s dump method, which returns the formatted result (as well as a dictionary of validation errors...)

But as far as I can tell, the `Schema.dump` method does not perform validation.  I have:

```python
>>> from marshmallow import Schema
>>> from marshmallow.fields import String
>>> from marshmallow.validate import Regexp
>>> class TestSchema(Schema):
...     testfield1 = String(validate=Regexp('^foo'))
...     testfield2 = String(default='teststring')

>>> TestSchema().dump({'testfield1': 'bar'})
MarshalResult(data={'testfield2': 'teststring', 'testfield1': 'bar'}, errors={})
```

Based on the docs, I thought I would see validation errors in the `errors` key.  The `load` method validates as expected:

```python
>>> TestSchema().load({'testfield1': 'bar'})
UnmarshalResult(data={}, errors={'testfield1': ['String does not match expected pattern.']})
```

But the `load` message does not apply `default` values:

```python
>>> TestSchema().load({})
UnmarshalResult(data={}, errors={})
```

So the only way to get a validated data structure with default values applied appears to be:

```python
>>> result1 = TestSchema().load({'testfield1': 'foo'})
>>> result2 = TestSchema().dump(result1.data)
>>> result2.data
{'testfield2': 'teststring', 'testfield1': 'foo'}
```

The above is with:

```python
>>> marshmallow.__version__
'2.13.6'
>>> sys.version
'3.5.4 (default, Aug 23 2017, 18:32:05) \n[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)]'
```

Am I simply misreading the documentation?

**Comment by lafrech** [comment]
You're right, validation only occurs on deserialization (load).

Think of it as "I should validate data coming from the outside world, but I don't need to validate my data before I send it to the outside world, because it comes from trusted zone".

Regarding default values, there are two parameters: `default` and `missing`. The former applies to dump, the other applies to load.

http://marshmallow.readthedocs.io/en/latest/api_reference.html#module-marshmallow.fields

- default – If set, this value will be used during serialization if the input value is missing. If not set, the field will be excluded from the serialized output if the input value is missing. May be a value or a callable.
- missing – Default deserialization value for the field if the field is not found in the input data. May be a value or a callable.

You should use `missing`.

**Comment by larsks** [comment]
Thanks, that's tremendously helpful. Using `missing` was indeed the missing (ha! sorry.) piece.

Does `dump` ever return validation errors?  The documentation suggests that it does, but your comment implies that it does not.

**Comment by sloria** [comment]
@larsks `dump` does return validation errors as well. It will not execute user validators, but it will return errors for data that cannot be serialized (e.g. trying to serialize a string as an int).

**Comment by dnshio** [comment]
I wanted to validate during serialisation time and was disappointed to find this thread. 

However, it's not that difficult to do what I wanted by validating the output from `.dump()`. e.g:

```python
schema = SomethingSchema()
data, errors = schema.dump(some_object)

# call schema.validate to raise ValidationErrors 
schema.validate(data)
```

**Comment by afallou** [comment]
For anyone finding this thread (like I have), note that @dnshio's approach doesn't always work.

`validate` ignores fields with `dump_only=True` (see [here](https://github.com/marshmallow-code/marshmallow/blob/3575cddda6ba104ecfc6e18c38cc7c941b33bf10/src/marshmallow/schema.py#L636) – `load_fields` are fields that are not `dump_only`, as opposed to `dump_fields`).
As a result, those fields will be treated as unknown fields. For example, the following code:
```
class PersonSchema(Schema):
    name = fields.String(
        dump_only=True,
    )

schema = PersonSchema()
errors = schema.validate(dict(name="John"))
if errors:
    raise ValidationError(message=errors)
```
raises `marshmallow.exceptions.ValidationError: {'name': ['Unknown field.']}`

**Comment by gabor-akeero** [comment]
One use case when a dump validation would be handy is when one uses [marshmallow_union](https://python-marshmallow-union.readthedocs.io/en/latest/usage.html), where serialisation of a Union stops at the first member that serialises the object without exceptions.

Now, if I have a union of classes that differ mostly on some `entityType: Literal["BaseSomething"] = "BaseSomething"` or `entityType: Literal["DerivedSomething"] = "DerivedSomething"` members, then the base-class member will gladly serialise the derived-class object - but only the inherited members of it.

I know, if it needs a workaround, then probably it should go to `marshmallow_union`, but... at least now we have a valid use-case.

Edit: For anyone who needs validation on dump:
```
from marshmallow import Schema

class ValidateOnDumpSchema(Schema):
    @post_dump
    def post_dump_validate(self, data: Dict, many: bool = False, partial: bool = False) -> Dict:
        errors: Dict = self.validate(data, many=many, partial=partial)
        if errors:
            raise ValueError(errors)  # marshmallow_union proceeds to next union member on TypeError or ValueError
        return data
        
        
class MySchema(ValidateOnDumpSchema):
    # ...
```
