### ISSUE TITLE
proposal: changing fields.Field's `**metadata` to `metadata=None`

### ISSUE THREAD

**Issue by podhmo** [marshmallow-code/marshmallow#683]
**This is backward incompatible change.**

## pros

typo check is working correctly.

Sometimes, people that unfamiliar with marshmallow, want to add validation with typo.

e.g.

```python
class S(Schema):
    # this is typo. (correct keyword is `validate`)
    v = fields.Integer(validator=validate.Range(max=10))
```

Current marshmallow's fields.Field implementation is such as like below.

```python
class Field(FieldABC):
    def __init__(self, default=missing_, attribute=None, load_from=None, dump_to=None,
                 error=None, validate=None, required=False, allow_none=None, load_only=False,
                 dump_only=False, missing=missing_, error_messages=None, **metadata):
        pass
```

So, above typo is also valid schema definition. adding Range validator as metadata, and validation on deserialization is working without error when passing invalid data.

Sometimes, sometimes, the code such like this is passed our code review, then we are disappointed ours poor heads(this is careless human error).

But, if, metadata is just keyword argument(`metadata=None`), this typo-ed code is raising TypeError.

**Comment by podhmo** [comment]
If chainging gracefully, showing warning messages, when calling with old-style way.

```python
class Field(FieldABC):
    def __init__(self, default=missing_, attribute=None, load_from=None, dump_to=None,
                 error=None, validate=None, required=False, allow_none=None, load_only=False,
                 dump_only=False, missing=missing_, error_messages=None, metadata=None, **_metadata):
        if not _metadata:
            # warning message
            warnings.warn("this is obsoleted, please use metadata keyword")
        metadata.update(_metadata)
```

**Comment by sloria** [comment]
Thanks @podhmo for the suggestion.

You raise a fair point--the current way does run the risk of passing invalid kwargs.

My worry is that we'll be breaking lots of use cases. apispec and webargs, for example, both make use of `metadata` to add new field params not offered by marshmallow. Passing metadata as this way also allows users to add their own field kwargs. For example, I suggested using `metadata` to add a `key` parameter here: https://github.com/marshmallow-code/marshmallow/pull/714#issuecomment-355451867

I'll have to think more about the tradeoffs with this one.

**Comment by podhmo** [comment]
Yes, this change is huge pain, i think so.  And I **haven't** strong motivation (like MUST ADDING THIS FEATURE), so suggestion of corner-case.

Ah, using metadata internally, if so, this change is a bit strange, maybe.

**Comment by sloria** [comment]
One possible alternative to prevent typos from passing silently would be to pass a set of allowed metadata keys.

```python
class BaseSchema(Schema):
    class Meta:
        allowed_field_metadata = {
            'description',
         }
```

An error would be raised if metadata outside of that set were passed.

**Comment by lafrech** [comment]
Passing custom metadata is definitely a use case not to break.

We could add `Meta.allowed_field_metadata` as you suggest. Like with `only` in fields, `None` would mean "everything", so any kwarg would be passed. Empty set would mean nothing passes.

Question is, what would be the default value? `None` or empty set?

One one hand, this change is meant to prevent users from entering wrong parameters, so it would be even more useful to new users, and therefore activated by default (default = empty set).

On the other hand, it may complicate the life of new users of libs such as apispec, webargs, or any lib based on marshmallow. And I don't think those libs can be adapted to provide the right `BaseSchema` with the union of all their parameters. So `None` seems like a reasonable default.

Using `None` as default would make this a non-breaking change.

**Comment by sloria** [comment]
Closing this for now, as I don't think we'll add it in the near future. I'm open to the `allowed_field_metadata` idea, but I don't think it warrants the added complexity at this point.
