### ISSUE TITLE
Add option for generating envelops

### ISSUE THREAD

**Issue by svenstaro** [marshmallow-code/marshmallow#69]
This should be an option for the Schema class. There should be an option like MySchema(envelope="things") to wrap the generated output/assume an envelope on the input like this:

```
schema = AlbumSchema(envelope="album")
result = schema.dump(album)
pprint(result.data, indent=2)
# {'album': 
#   { 'artist': {'name': 'David Bowie'},
#     'release_date': '1971-12-17',
#     'title': 'Hunky Dory'}
```

The reasoning is partly security (http://flask.pocoo.org/docs/0.10/security/#json-security) though this is becoming outdated and partly because some APIs actually work like this. I think this is a proper thing marshmallow should have.

**Comment by sloria** [comment]
An added parameter is not necessary given marshmallow's existing hooks for modifying output data. The docs detail 2 ways to meet this very use case: http://marshmallow.readthedocs.org/en/latest/extending.html#transforming-data (see "Transforming Data" and "Extending "class Meta" Options")

**Comment by svenstaro** [comment]
Yeah that works for me, thanks.
