### ISSUE TITLE
Add a timezone validator or field

### ISSUE THREAD

**Issue by Shir0kamii** [marshmallow-code/marshmallow#690]
Hi,

I found myself in the need to validate a timezone string (such as `Europe/Paris`) and didn't found a way to do it with Marshmallow. I think it's common enough for people to use these even though it seems this hasn't been discused before. Maybe we could add it ?

I volonteer to implement it if it pleases you, but I would have a few questions.

I would implement it using `pytz` since maintaining a comprehensive list of timezone must be out of question. But I see marshmallow doesn't have dependencies, is it something that you would agree to change ?

Also, would it make more sense to add a field or a validator ? A validator seems enough, but most time it would then be converted as a `tzinfo` instance, so maybe a field is better.

Thank you for your time!

**Comment by sloria** [comment]
I'm not sure this needs to be added. You can just use `validate.OneOf`.

```python
from marshmallow.validate import OneOf
import pytz

class MySchema(Schema):
    timezone = fields.Str(validate=OneOf(pytz.all_timezones))
```
