### ISSUE TITLE
Is it possible to use OneOf() in a nested field?

### ISSUE THREAD

**Issue by threeoheight** [marshmallow-code/marshmallow#693]
I'm trying to validate a dict where the value can either be itself, i.e. `field = nested('self')` OR a different schema `field = nested(OtherSchema`.  Using OneOf() won't for schemas, so I was wondering if there was a correct way to do this.  Here is an example of a payload I'm trying to validate:

```
'field': {
    'op': 'foo'
    'field': {
        'op': 'val'
        'field': {
            'x': 'bar'
            'y': 'baz'
    }
}
```
So in this case, 'field' can either contain 'op' and a nested version of itself OR a schema with 'x' and 'y' as the values.

**Comment by sloria** [comment]
@threeoheight Take a look at [marshmallow-oneofschema](https://github.com/maximkulkin/marshmallow-oneofschema). It seems like it was built exactly for your use case.
