### ISSUE TITLE
Question: order of execution of schema-level validator

### ISSUE THREAD

**Issue by DrPyser** [marshmallow-code/marshmallow#695]
When a schema validator is registered via `@validates_schema`, when does it get executed with respect to other `pre`/`post`  hooks?

Thanks.

**Comment by hardy4yooz** [comment]
@validates_schema(skip_on_field_errors=True)

**Comment by sloria** [comment]
@DrPyser Schema validators are executed after `pre-load` and field validators are executed.

`pre_load` -> field validators -> schema validators -> `post_load`

**Comment by DrPyser** [comment]
Cool, thanks!
