### ISSUE TITLE
Nested.default — incorrect documentation

### ISSUE THREAD

**Issue by Inego** [marshmallow-code/marshmallow#701]
`Nested` field documentation says that the `default` parameter may be used to serialize `None` values:
`    :param default: Default value to if attribute is missing or None`
However, this does not correspond to reality: `default` values are only used to serialize missing fields. And it seems that there is no way to make the `default` value be used for serialization of `None` values — by fine-tuning the field parameters, at least.

**Comment by sloria** [comment]
Good catch. I've removed the `default` documentation for `Nested` because the semantics are the same as `Field`.
