### ISSUE TITLE
Validate field Y based on field X value

### ISSUE THREAD

**Issue by disconnect3d** [marshmallow-code/marshmallow#702]
Hey,

I want to have a validation of field Y based on field X.

I could potentially do it with `post_load` decorator but it seems it overrides all errors (e.g. the validation dict contains only the error from method decorated with `post_load` - it misses some basic info that for example a field is missing).
Is there a way to tell post_load method that its validation failure should also consist other validations?

Or is there a way of accessing another validated fields inside a validator method (the one decorated with `validates`)?

**Comment by lafrech** [comment]
Sounds like [schema-level validation](http://marshmallow.readthedocs.io/en/latest/extending.html#schema-level-validation) is what you need.

**Comment by disconnect3d** [comment]
@lafrech Okay, that works for me. Thanks.
