### ISSUE TITLE
How to use it with templates like WTForms?

### ISSUE THREAD

**Issue by zero-master** [marshmallow-code/marshmallow#704]
I search everywhere but did not find if it's possible to achieve this with marshmallow:
http://flask.pocoo.org/docs/0.12/patterns/wtforms/ (not validation, scroll down the the bottom half where the form fields are injected into template)

**Comment by sloria** [comment]
Rendering forms is outside marshmallow's scope.

You might look into https://github.com/fuhrysteve/marshmallow-jsonschema , which will allow you to generate a JSON Schema from a marshmallow Schema, which can be consumed by other tools (see the README for marshmallow-jsonschema for a listing of these) to render forms.

**Comment by twosigmajab** [comment]
Just noticed https://github.com/marshmallow-code/marshmallow/wiki/Ecosystem#forms links to https://github.com/podhmo/marshmallow-form, and momentarily got excited that @sloria's previous answer is now out of date. But then I clicked through and saw "(this is broken package. latest marshmallow is not suppported)" in the project description. (And perusing the README, looks like that project didn't address the use case that WTForms does anyway.) Too bad. In any case, looks like https://github.com/marshmallow-code/marshmallow/wiki/Ecosystem#forms should be updated.
