### ISSUE TITLE
peewee_example.py missing pre_load in TodoSchema

### ISSUE THREAD

**Issue by edwardinubuntu** [marshmallow-code/marshmallow#706]
In class TodoSchema(Schema) function: [make_object](https://github.com/marshmallow-code/marshmallow/blob/12044877d8af3d8f07c39bf0c5df78d3d7a22df1/examples/peewee_example.py#L79), need to add @pre_load, otherwise, it won't return the object, instead, return the original JSON object.

# Before
![screen shot 2017-12-15 at 8 27 04 pm](https://user-images.githubusercontent.com/414554/34042184-6747ea4c-e1d6-11e7-8294-a215e45357da.png)

# After
![screen shot 2017-12-15 at 8 25 20 pm](https://user-images.githubusercontent.com/414554/34042191-709f8d2a-e1d6-11e7-9b3b-a4caa4baf2b6.png)

**Comment by sloria** [comment]
Thanks for reporting. The example has been fixed.
