### ISSUE TITLE
marshmallow.validate - Regexp validating empty string or pattern

### ISSUE THREAD

**Issue by MarbilleJuntado** [marshmallow-code/marshmallow#716]
I have created a schema to validate URLs. Empty strings should also be valid.
This is the validator: 
`facebook_profile_url = fields.String(required=False, validate=validate.Regexp(
        '^$|https://facebook.com/[a-zA-Z][a-zA-Z 0-9._]{0,50}$', 0, 'Facebook username is invalid')
    )`

Regular URLs that follow the pattern are accepted, but not empty strings. How is that so?

**Comment by podhmo** [comment]
It looks empty string is also accepted, to me(I have misunderstanding, maybe).

```python
from marshmallow import Schema, fields, validate

class S(Schema):
    facebook_profile_url = fields.String(
        required=False,
        validate=validate.Regexp(
            '^$|https://facebook.com/[a-zA-Z][a-zA-Z 0-9._]{0,50}$', 0,
            'Facebook username is invalid'
        )
    )

print(S().load({"facebook_profile_url": ""}))
print(S().load({"facebook_profile_url": "https://facebook.com/a"}))
```

```
UnmarshalResult(data={'facebook_profile_url': ''}, errors={})
UnmarshalResult(data={'facebook_profile_url': 'https://facebook.com/a'}, errors={})
```

**Comment by deckar01** [comment]
@MarbilleJuntado Is the example podhmo provided working for you?

**Comment by lafrech** [comment]
Closing this for now. Please get back to us if you're still stuck on this.
