### ISSUE TITLE
Remove legacy API

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#73]
In version 2.0, the pre-1.0 legacy API will be completely removed from the codebase.

This includes:
- [x] Passing object to be serialized to `Schema` constructor
- [x] `data` and `errors` properties of `Schema`
- [x] The `error` param of `Fields` (still in question)
- [x] `Arbitrary`, `Fixed` and `Price` fields (remove in 2.0)
- [x] `Select` field (remove in 2.0)
- [x] Deprecated function validators. Alias validator classes?
- [x] `context` argument of Method fields? (in question)
- [x] `@Schema.preprocessor`, `@Schema.data_handler`, etc.
- [x] `MarshallingError` and `UnmarshallingError` (remove in 2.1)
- [x] `QuerySelect` and `QuerySelectList` (remove in 2.2)
- [x] `allow_none` and `required` string arguments (remove in 2.2)

EDIT: Updated checklist based on comments.

**Comment by sloria** [comment]
The `Arbitrary`, `Fixed`, and `Price` fields may also be removed in favor of the `Decimal` field.

**Comment by sloria** [comment]
Also, the deprecated function validators in the `validate` module.

**Comment by philtay** [comment]
Also, deprecate/remove the `Select` field in favor of `OneOf` validator.

**Comment by sloria** [comment]
Let's do this for the final release of 2.0.0 (rather than in 2.0.0-a) to ease the transition to the 2.0 line.

**Comment by sloria** [comment]
Went ahead and removed `Schema.data` and `Schema.errors`, as it is has been deprecated since 1.0.

**Comment by philtay** [comment]
Add the deprecated function validators in the checklist.

**Comment by sloria** [comment]
Done.
