### ISSUE TITLE
marshmallow validation issue

### ISSUE THREAD

**Issue by pntlsrsh** [marshmallow-code/marshmallow#733]
Accept = 2, Reject = 4, Maybe = 5
This filter is working fine when I am passing one value of below validations
like status=accept. getting result = 2
status = fields.String(load_only=True, validate=validate.OneOf(
            'accept', 'reject', 'maybe'))

How to pass list values(more than 1) in filters, I need like
status = accept & status = reject and result should be 6
I tried this, but not working. Showing error: Not a valid choice
status = fields.List(
    fields.String(), load_only=True, validate=validate.OneOf(
        'accept', 'reject', 'maybe'))

**Comment by pntlsrsh** [comment]
@sloria can you solve for me. TIA

**Comment by lafrech** [comment]
This question is pretty hard to understand.

Whatever you're trying to achieve, shouldn't it be

    status = fields.List(fields.String(load_only=True, validate=validate.OneOf('accept', 'reject', 'maybe')))

(Notice the attributes are on String, not on List.)

**Comment by lafrech** [comment]
Please reply here if you're still stuck on this.
