### ISSUE TITLE
(De)serialization to other types

### ISSUE THREAD

**Issue by dvf** [marshmallow-code/marshmallow#737]
I'd love for Marshmallow to be more modular, for example I'm loading from `JSON` and serializing to `bencode`. It would be great if there was a simple way to do this.

It was suggested in https://github.com/marshmallow-code/marshmallow/issues/130 but the solution assumes that the source and destination encoding are the same.

**Comment by lafrech** [comment]
I think you could use two schemas for this. Define a schema MySchema that speaks JSON, then subclass it as MyBencodeSchema and set the encoder to your bencode encoder.

**Comment by lafrech** [comment]
I was about to close this as this is a corner case and the two-schema solution seems reasonable enough.

OTOH, this would be really easy to achieve, all it takes is a `load_render_module` and a `dump_render_module` rather than just `render_module`.

**Comment by dvf** [comment]
Yeah but also remove the json-specific names of things like `json_module`

**Comment by lafrech** [comment]
Done in https://github.com/marshmallow-code/marshmallow/commit/3331f832608340efff7028aad89cf2859c679a53: 
https://github.com/marshmallow-code/marshmallow/blob/feede12e256724b835b590ca6926e9b3c2a5a478/docs/upgrading.rst#json_module-option-is-renamed-to-render_module

**Comment by lafrech** [comment]
My comment "Done in 3331f83" is misleading. It was a reply to the comment above about "the json-specific names". The feature in the OP is not implemented.

It would be easy to add, but it is also easy to achieve from user side so it is not critical.

Anyone, feel free to reopen if feeling strongly about it.

**Comment by sloria** [comment]
Ah, I see. OK, for now I'd recommend implementing a custom render class that implements dumps and loads.

```python
class ComboRenderer:
    @staticmethod
    def loads(s, *args, **kwargs):
        return json.loads(s, *args, **kwargs)

    @staticmethod
    def dumps(obj, *args, **kwargs):
        return yaml.dumps(obj, *args, **kwargs)


class MySchema(Schema):
    class Meta:
        render_module = ComboRenderer
```

**Comment by lafrech** [comment]
That's much better than my workaround. I find it easy enough not to bother implementing the OP.
