### ISSUE TITLE
Reusable Field Validation

### ISSUE THREAD

**Issue by erwinyusrizal** [marshmallow-code/marshmallow#739]
Hi, any idea on how to handle the field validation reusable? currently I use `validate` and define my common validation function

```
def validate_required(value):    
    if len(value) == 0:
        raise ValidationError('Cannot be empty.')

class RegisterSchema(Schema):

    fullname = fields.String(required=True, validate=[
        validate_required,
        validate.Regexp(r'^([a-zA-Z0-9\s]{5,45})$', error='Must have between 5 and 45 characters length and only letters, numbers and spaces are allowed.')
    ])
```

the problem is field validate method only support 1 arg which is only `value`, I cannot make my validation function dynamic for example if I want to add custom error message or dynamic regex pattern with variable.

Is there any other way to handle this validation reusable?

Thx

**Comment by lafrech** [comment]
What about [functools.partial](https://docs.python.org/3.5/library/functools.html#functools.partial)?
