### ISSUE TITLE
Callable as `missing` value for a DateTime field not working as expected

### ISSUE THREAD

**Issue by fqxp** [marshmallow-code/marshmallow#740]
With version 3.0.0b7, I am trying use a callable to set a datetime when a field is not set:
```python
class MySchema(Schema):
    f1 = fields.Int(missing=lambda: 123)
    f2 = fields.DateTime(missing=lambda: datetime.datetime(2018, 2, 18))
```
When I am trying to use the schema as following, though, I get a ValidationError:
```python
>>> MySchema().load({})
ValidationError: {'f2': ['Not a valid datetime.']}
```
I would expect to get a dictionary `{'f1': 123, 'f2': datetime(2018, 2, 18, …)`. Since I am new user, I am not sure if this is expected behavior, but when comparing this to the Int field, it looks like a bug to me.

**Comment by lafrech** [comment]
I think this has nothing to do with using a callable. And this is not specific to marshmallow 3. Marshmallow 2 behaves the same. Default value must be passed in deserialized form, which is not very practical.

Please try `datetime.datetime(2018, 2, 18).isoformat()`.

This is likely to change in marshmallow 3: https://github.com/marshmallow-code/marshmallow/issues/378.

Why use callables, by the way? Why not pass values?

    f1 = fields.Int(missing=123)
    f2 = fields.DateTime(missing=datetime.datetime(2018, 2, 18).isoformat())

**Comment by justanr** [comment]
If you're goal is to have a dynamic datetime be the default value, take a look at my library [datestuff](https://github.com/justanr/datestuff) -- I wrote it to deal with this exact issue (albeit in DRF).

**Comment by fqxp** [comment]
@lafrech: it was just an example. My goal is to set a field, e. g., `created_at` to the current time, as returned by `datetime.datetime.utcnow()`.

**Comment by fqxp** [comment]
@lafrech: thanks for your explanation, passing the value in deserialized form makes it work.
