### ISSUE TITLE
Add Schema 'Exclude' support NoneType

### ISSUE THREAD

**Issue by erwinyusrizal** [marshmallow-code/marshmallow#741]
Hi, I use webargs to handle my request arguments, I set schema `only` and `exclude` as an arguments.

```
myargs = {
    'only': fields.DelimitedList(fields.Str(), missing=None),
    'exclude': fields.DelimitedList(fields.Str(), missing=None)
}
@use_args(myargs, locations=['query'])
def get(self, args):
    schema = MySchema(many=True, only=args['only'], exclude=args['exclude'])
```

since by default `only` and `exclude` is set as None, if  `exclude` is None in my request, it returns 

`TypeError: 'NoneType' object is not iterable`

currently I fixed it with a simple conditional in line 
https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/schema.py#L633 

```
if self.exclude:
            excludes = set(self.opts.exclude) | set(self.exclude)
            if excludes:
                # Apply the exclude option to nested fields.
                self.__apply_nested_option('exclude', excludes)
```
and line https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/schema.py#L677

Thx

**Comment by lafrech** [comment]
I'm not sure I understand your use case.

Anyway, can't you just write

```python
myargs = {
    'only': fields.DelimitedList(fields.Str(), missing=set),
    'exclude': fields.DelimitedList(fields.Str(), missing=set)
}
```

so as to get empty sets rather than `None`?

**Comment by deckar01** [comment]
The source code defaults to an empty tuple `()` for the `only` and `exclude` parameters. `None` is not a valid parameter value according to the documentation.

http://marshmallow.readthedocs.io/en/latest/api_reference.html#schema

**Comment by lafrech** [comment]
> The source code defaults to an empty tuple () for the only and exclude parameters.

Right, `missing=set` is useless.
