### ISSUE TITLE
Virtual attributes

### ISSUE THREAD

**Issue by tispratik** [marshmallow-code/marshmallow#746]
I am using marshmallow schema and using a post_load method to copy data into an sqlalchemy model. There is a certain column that i want to be available as a non-persisting attribute on the sqlalchemy model. Is it possible to achieve something like that through the marshmallow post_load function?

```python
class AdSchema(Schema):
  """Schema Mapping class."""

  id = fields.Int(dump_only=True)
  available_formats = fields.List(fields.Str())

  @post_load
  def make_ad(self, data):
    return AdModel(**data)
```
```python
class AdModel(Base):
  """Ad ORM class."""
  __tablename__ = 'ad_model'

  id = Column(Integer, primary_key=True)
```

`AdSchema` is the marshmallow schema class and `AdModel` is an sqlalchemy model class.

**Comment by deckar01** [comment]
I am not sure what "a non-persisting attribute on the sqlalchemy model" is. It sounds like you want to provide a field from your data to the model constructor, but not have it persist to the database. You might find the sqlalchemy documentation on "hybrid attributes" useful.
http://docs.sqlalchemy.org/en/latest/orm/extensions/hybrid.html
