### ISSUE TITLE
Ordered deserialization (ordered loading)

### ISSUE THREAD

**Issue by dfee** [marshmallow-code/marshmallow#751]
I'm attempting so deserialize objects from a JSON data structure to database instances, but I need to rely on one field being serialized first.

For example, consider the `product` definition:
```
{
  "name": "t-shirt",
  "options": [
    { "name": "size", "values": ["small", "medium", "large"] },
    { "name": "color", "values": ["red", "yellow", "blue"] },
  ],
  "variants": [
    { "sku": "red_sm", options: [ { "name": "size", "value": "small" }, { "name": "color", "value": "red" } ],
  ]
```

In my database, this data is reflected using the entity-attribute-value pattern. Serialization into this form is fairly straightforward – with the help of `post_load`. However, when re-ingesting I need to have `options` processed before `variants`, so that my `variants` can reference their `options` instead of attempting to duplicate them.

Is there a way to deterministically invoke deserialization in order?

**Comment by dfee** [comment]
Alright I've tracked the call stack down:

```python
class ProductSchema(Schema):
    name = fields.Str()
    # implementation of nested schemas aren't relevant here
    options = fields.Nested('ProductOptionSchema', many=True) 
    variants = fields.Nested('ProdcutVariantSchema', many=True)

ps = ProductSchema()
ps.load({
  "name": "t-shirt",
  "options": [
    { "name": "size", "values": ["small", "medium", "large"] },
    { "name": "color", "values": ["red", "yellow", "blue"] },
  ],
  "variants": [
    { "sku": "red_sm", options: [ { "name": "size", "value": "small" }, { "name": "color", "value": "red" } ],
  ]
})
```

Now, let's explore the call stack, of the `load` method:

1. [`Schema.load(self, data, many=None, partial=None)`](https://github.com/marshmallow-code/marshmallow/blob/327530deee83073eb8d5f0fc80df3601e4320bd4/marshmallow/schema.py#L479) calls ->
2. [`Schema._do_load(self, data, many=None, partial=None, postprocess=True)`](https://github.com/marshmallow-code/marshmallow/blob/327530deee83073eb8d5f0fc80df3601e4320bd4/marshmallow/schema.py#L549) calls ->
3. [`Unmarshaller.deserialize(self, data, fields_dict, many=False, partial=False, dict_class=dict, index_errors=True, index=None)`](https://github.com/marshmallow-code/marshmallow/blob/327530deee83073eb8d5f0fc80df3601e4320bd4/marshmallow/marshalling.py#L214) executes ->
```python
        for attr_name, field_obj in iteritems(fields_dict):
            if field_obj.dump_only:
                continue
            field_name = attr_name
            if field_obj.load_from:
                field_name = field_obj.load_from
            try:
                raw_value = data.get(field_name, missing)
            # ... continues
```

With the answer being that we're iterating over `fields_dict` (the schema instance's `fields` attribute) which gets set to an `OrderedDict` (if `Schema.Meta.ordered = True`) in [`_update_fields(self, obj=None, many=False)`](https://github.com/marshmallow-code/marshmallow/blob/327530deee83073eb8d5f0fc80df3601e4320bd4/marshmallow/schema.py#L658) ... called in `Schema.__init__`.

So really, all I'm looking for is confirmation that this implementation is as expected, and not subject to change. Probably, would require an update to the [documentation for `Meta.ordered`](http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.Schema.Meta) which is currently:
```
* ordered: If True, order serialization output according to the order in which fields were declared. Output of Schema.dump will be a collections.OrderedDict.
```

and could possibly be updated by revising to:

```
* ordered: If True, order serialization output according to the order in which fields were declared. Output of Schema.dump will be a collections.OrderedDict. Also, deserialization will occur according to the order in which fields were declared, enabling a deterministic loading strategy.
```

Let me know what you guys think, especially @sloria

**Comment by deckar01** [comment]
```md
* ordered: If True, order serialization and deserialization according to the order in which
the fields were declared. Output of Schema.dump will be a collections.OrderedDict.
```

We should add tests to preserve this behavior if we don't already have some.

Is the output of `Schema.load` changed by the ordered argument? We might want to be explicit about that too.

**Comment by remeika** [comment]
I think everything is as it should be for this issue.

For serialization: `dump` serializes data in order if `Meta.ordered` is `True` on the schema. This is reflected in the documentation, and covered by the test [`test_declared_field_order_is_maintained_on_dump`](https://github.com/marshmallow-code/marshmallow/blob/966685e61b976e9006051658626de474be8bac82/tests/test_options.py#L103)

Next de-serialization: `load` de-serialzes to an OrderedDict if `Meta.ordered` is `True`. This behavior is covered by the test [`test_declared_field_order_is_maintained_on_load `](https://github.com/marshmallow-code/marshmallow/blob/966685e61b976e9006051658626de474be8bac82/tests/test_options.py#L109). Then you can set up a `@post_load` hook to act on that dictionary in a deterministic fashion.

I think this issue should be closed. Am I missing something?
