### ISSUE TITLE
DateTime deserializer cannot use dateutil

### ISSUE THREAD

**Issue by mchalek** [marshmallow-code/marshmallow#758]
The DateTime deserializer cannot use the dateutil library because it contains an inaccessible code path.

For example, parsing the string `2018/03/26` fails:
```python
>>> import marshmallow as ma
>>> f = ma.fields.DateTime()
>>> f.deserialize('2018/03/26')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "marshmallow/fields.py", line 261, in deserialize
    output = self._deserialize(value, attr, data)
  File "marshmallow/fields.py", line 929, in _deserialize
    raise self.fail('invalid')
  File "marshmallow/fields.py", line 216, in fail
    raise ValidationError(msg)
marshmallow.exceptions.ValidationError: Not a valid datetime.
```
Even though the `dateutil`-based parser knows how to deserialize it:
```python
>>> ma.utils.dateutil_available
True
>>> ma.utils.from_datestring('2018/03/26')
datetime.datetime(2018, 3, 26, 0, 0)
```

The cause of this is located in [this code block](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L923-L935).  Specifically: `dateutil` is only used when the field does not have a pre-defined date format, but the `deserialize` method itself sets the field's date format to a default value before that condition is evaluated.

I submitted #619 to address this last year, but I admit that the description was poorly worded and I never followed-up with it until recently, when user @znatty22 commented that she has run into the same issue.

Could someone please advise on steps to take in order to get #619 merged?

Thanks,

Kevin

**Comment by deckar01** [comment]
What if we registered `dateutil` in `DATEFORMAT_DESERIALIZATION_FUNCS` instead?

**Comment by lafrech** [comment]
What would it do when serializing? What would be the equivalent `to_datestring` function?

We could remove the dead code (including `from_datestring` function) for 3.0 and postpone the "how to use dateutil" issue.

**Comment by lafrech** [comment]
`dateutil` is not really a format. It is more more like an auto/catch-all/non-strict option to let dateutil do whatever it thinks appropriate to provide a datetime from a string, which is in line with the `auto_deserialize_format` approach in #619. Although it looks weird, I don't object to adding it as an option.

Also, I agree with @mchalek that reassigning `self.dateformat` in `_serialize` and `_deserialize` looks wrong. ~I can send a PR to use a local variable instead.~ Fixed in https://github.com/marshmallow-code/marshmallow/pull/934.

**Comment by lafrech** [comment]
If [my comment here](https://github.com/marshmallow-code/marshmallow/issues/899#issuecomment-418042719) is not total nonsense, if dropping dateutil is an option, then using it to deserialize datetimes can still be achieved by subclassing `DateTime` in one's application.
