### ISSUE TITLE
Setup for Nested Schemas with attribute access?

### ISSUE THREAD

**Issue by dsully** [marshmallow-code/marshmallow#759]
Hi - I have a reasonably complex legacy (JSON) file format that I'm trying to adapt to use Marshmallow.

Here is an example of the JSON:

```
{
  "name": "my-app",
  "build": {
    "toolchains": {
      "android-sdk-platform-tools": {
        "version": "26.0.0",
        "plugins": {}
      },
      "android-sdk-tools": {
        "version": "25.2.5",
        "plugins": {}
      },
      "gradle": {
        "version": "4.5",
        "plugins": {
          "android-emulator-plugin": {
            "libraries": [
              "gradle-emulator-plugin"
            ],
            "version": "0.0.43"
          },
          "buildScans": "com.gradle:build-scan-plugin:1.8",
          "deco": {
            "libraries": [
              "gradle-deco-plugin"
            ],
            "version": "@spec.product.deco.version@"
          },
          "tracking-constants": {
            "libraries": [
              "gradle-tracking-constants"
            ],
            "version": "0.1.12"
          }
        }
      }
    }
  }
}
```

```
class ToolChain(Schema):

    plugins = fields.Dict(keys=fields.String(), values=PolymorphicField(PolymorphicDependency))
    version = fields.String(required=True)


class Build(Schema):

    toolchains = fields.Nested(ToolChain)

    type = fields.String()
    uri = fields.String()


class MyModel(Schema):
    name = fields.String(required=True)
    build = fields.Nested(Build)
```

Setting aside the polymorphic portion (though, could certainly use some guidance there), what is the best way to structure my models such that I can use dot object notation to access the data?

eg: ```print(spec.build.toolchains.gradle)```

Thanks!

**Comment by lafrech** [comment]
From a quick glance, I think I'd use a Dict field for toolchains. In marshmallow 3 you can specify the type of the keys and values. Then you can use @maximkulkin's [oneofschema](https://github.com/maximkulkin/marshmallow-oneofschema) to handle polymorphism and specify the base polymorphic schema as the value type of the Dict.

**Comment by dsully** [comment]
@lafrech thanks for the quick reply. I am using the 3 beta of Marshmallow.

Setting as a dict doesn't allow me the attribute based access though. ie:

```toolchains = fields.Dict(keys=fields.String(), values=fields.Nested(ToolChain))```

Emits an AttributeError: ```'dict' object has no attribute 'gradle'```

**Comment by lafrech** [comment]
You're right. I ended up missing that part. I don't really understand that requirement. I suppose you could modify Dict field to return another base structure, a modified `dict` that does attribute access.

**Comment by dsully** [comment]
The requirement is such that one doesn't have to change to using a primitive instead of object / attribute notation when walking down the "data tree".

**Comment by lafrech** [comment]
Alright. For the "attribute dict", see here: https://stackoverflow.com/questions/4984647/accessing-dict-keys-like-an-attribute for instance.

**Comment by dsully** [comment]
Right, or https://pypi.python.org/pypi/attrdict - *but* - how do I shim that into Marshmallow while still allowing the data inside the dict to be mapped to a schema?

**Comment by lafrech** [comment]
> Right, or https://pypi.python.org/pypi/attrdict 

Yes, probably better.

> how do I shim that into Marshmallow

What if you subclass `Dict` like this?

```python
from attrdict import AttrDict

class AttributeDict(ma.fields.Dict):
    def _deserialize(self, value, attr, data):
        return AttrDict(super()._deserialize(self, value, attr, data))
```

**Comment by lafrech** [comment]
@dsully, did this work for you? Shall we close this?

**Comment by dsully** [comment]
I think it did - I need to get back to to my internal branch that pulls in Marshmallow.

Are you at PyCon right now by any chance?

**Comment by lafrech** [comment]
> I think it did - I need to get back to to my internal branch that pulls in Marshmallow.

OK. Then please have a look when you get the time. No rush.

> Are you at PyCon right now by any chance?

Nope. (It's a long way from France.) Happy PyCon everyone!

**Comment by lafrech** [comment]
@dsully did you solve this?

**Comment by lafrech** [comment]
Closing this. Please reppen if you're still stuck.
