### ISSUE TITLE
`fields.Boolean` doesn't accept truthy/falsy per documentation

### ISSUE THREAD

**Issue by sufianrhazi-blink** [marshmallow-code/marshmallow#762]
On the `stable` line (`2.15.0`), documentation indicates that `truthy` and `falsy` can be accepted as constructor parameters, but this just isn't true:

```python
>>> import marshmallow
>>> from marshmallow import Schema, fields
>>> class Example(Schema):
...     b = fields.Boolean(truthy=set(['Yes']), falsy=set(['No']))
... 
>>> ex = Example()
>>> print(ex.load({'b': 'Yes'}))
UnmarshalResult(data={}, errors={'b': ['Not a valid boolean.']})
```

To get this behavior in 2.15.0, you need to subclass `fields.Boolean` overriding the `truthy` and `falsy` properties:

```python
>>> from marshmallow import Schema, fields
>>> class MyBoolean(fields.Boolean):
...     truthy = set(['Yes'])
...     falsy = set(['No'])
... 
>>> class Example(Schema):
...     b = MyBoolean()
... 
>>> ex = Example()
>>> print(ex.load({'b': 'Yes'}))
UnmarshalResult(data={'b': True}, errors={})
>>> print(ex.load({'b': 'No'}))
UnmarshalResult(data={'b': False}, errors={})
>>> print(ex.load({'b': 'True'}))
UnmarshalResult(data={}, errors={'b': ['Not a valid boolean.']})
```

In the `dev` line, the behavior matches the documentation (`truthy` and `falsy` are constructor params)

**Comment by deckar01** [comment]
It looks like #590 was merged into the dev branch, but it never made it into the 2.x branch...

**Comment by deckar01** [comment]
Apparently this feature was not backwards compatible with 2.0. https://github.com/marshmallow-code/marshmallow/commit/ed847db552db0ac17ef7c1356eb93ad4cdc142ee#commitcomment-21880013

The docs are a little confusing here. The stable docs (2.x-line) don't actually show these arguments.

Stable:

> <img width="677" alt="screen shot 2018-04-03 at 3 48 00 pm" src="https://user-images.githubusercontent.com/3108007/38275119-75986718-3756-11e8-8ed1-a3fb80526c13.png">

Dev:

> <img width="683" alt="screen shot 2018-04-03 at 3 47 48 pm" src="https://user-images.githubusercontent.com/3108007/38275120-75abbcc8-3756-11e8-885c-9dd530d5e7fe.png">

Maybe you were looking at the "latest" docs? I think it is pointing at a 3.0 beta release by default. Not sure if that is desirable considering that is not what you get when you `pip install marshmallow`.

**Comment by sufianrhazi-blink** [comment]
Oh huh, you're right in that the stable docs don't specify `truthy` or `falsy` in the function signature. I definitely misread the `falsy` and `truthy` items directly below `kwargs` to mean that you could supply those as keyword arguments to the constructor.

Sorry about that, I guess this is working as documented then? (though it's unclear what the mention of `truthy` and `falsy` are, since they're not instance members...)

**Comment by deckar01** [comment]
I guess the class properties are mentioned in the documentation, because it is part of the public interface and useful for subclassing.

It is a feature in 3.0 though. If you get a chance, try out the beta release with `pip install marshmallow --pre`.
