### ISSUE TITLE
Issue with datetime serialization. 

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/marshmallow#763]
Cannot dump a dict which contain datetime with my defined format

```
requestData = {
    date="2018-04-10T22:00:00"
}

class MySchema(Schema):
    date = fields.DateTime(format='%Y-%m-%dT%H:%M:%S', required=True)
```

string has no attribute `strftime` and in result the application crashes. Apparently `_serialize` have to be fixed. 

```
    def _serialize(self, value, attr, obj):
        if value is None:
            return None
        self.dateformat = self.dateformat or self.DEFAULT_FORMAT
        format_func = self.DATEFORMAT_SERIALIZATION_FUNCS.get(self.dateformat, None)
        if format_func:
            try:
                return format_func(value, localtime=self.localtime)
            except (AttributeError, ValueError):
                self.fail('format', input=value)
        else:
            return value.strftime(self.dateformat)
```

Or is there anything im doing wrong ?

**Comment by lafrech** [comment]
"dump" creates a string from a DateTime object.
"load" creates a DateTime object from a string.

Do you want to dump / serialize and object or load / deserialize a string ?

**Comment by rocker19943** [comment]
@lafrech i want to serialize it

**Comment by ghost** [comment]
@lafrech Oh I see! my bad i didn't realize that. Indeed I should `.load` it first. thank you!
I'm closing this issue.
