### ISSUE TITLE
default for Nested doesn't work

### ISSUE THREAD

**Issue by karmux** [marshmallow-code/marshmallow#764]
```
class Limits(marshmallow.Schema):
    EUR = fields.Int(default=0)
    USD = fields.Int(default=0)


class TestSchema(marshmallow.Schema):
    limits = fields.Nested(
        Limits,
        default=Limits().dump(Limits())
    )
```
After serialization I get `"limits": null`. Expected result is `"limits": {"EUR": 0, "USD": 0}`. Field is also `null` when I write `default={'EUR': 0, 'USD': 0}`.

`limits` is a JSON field in PostgreSQL and SQLAlchemy. marshmallow version is 3.0.0b8.

**Comment by deckar01** [comment]
Your example seems to be working correctly for me on 3.0.0b8 with python 2.7.10 and python 3.6.5.

```py
TestSchema().dump({})
# {u'limits': {u'USD': 0, u'EUR': 0}}
TestSchema().dump(None)
# {u'limits': {u'USD': 0, u'EUR': 0}}
```

Are you serializing some other way?

**Comment by karmux** [comment]
```
>>> TestSchema().dump({'limits': None})
{'limits': None}
```
`default` works with missing fields exactly like written in the documentation:
http://marshmallow.readthedocs.io/en/latest/api_reference.html#module-marshmallow.fields

```
>>> Limits().dump({'EUR': None})
{'EUR': None, 'USD': 0}
```
I needed to override how attributes are accessed:
```
    def get_attribute(self, obj, key, default):
        if key == 'limits':
            return getattr(obj, key, None) or default
        return super().get_attribute(obj, key, default)
```
