### ISSUE TITLE
Execute schema validator *once*?

### ISSUE THREAD

**Issue by dargueta** [marshmallow-code/marshmallow#770]
I'd like to run the schema validator on my schema exactly *once*. As illustrated in the example of [detecting extra keys](http://marshmallow.readthedocs.io/en/latest/extending.html#validating-original-input-data), the validator appears to run once per key.

This is a minimized version of my code:

```py
import marshmallow as ma
import marshmallow.exceptions as ma_exc
import marshmallow.fields as maf

class MySchema(ma.Schema):
    foo = maf.Str()

    @ma.validates_schema(pass_original=True, skip_on_field_errors=True)
    def check_unknown_fields(self, data, original_data):
        expected_keys = {
            f.load_from or f.name
            for f in self.fields.values()
        }
        unknown = set(original_data) - expected_keys

        if unknown:
            raise ma_exc.ValidationError(
                'Unrecognized extra keys: %s' % ', '.join(sorted(map(repr, unknown))),
                field_names=list(unknown))
```

The problem I'm having is that I'm validating millions of records at a time and outputting these errors to a list. If the data we receive has five extra fields, I end up with five times as many errors as I expect. We're having I/O and storage problems because of this.

Am I doing something wrong? Is there an easy way to get this to run once per record?

**Comment by lafrech** [comment]
The validator runs once per schema load. If produces a ValidationError associated with a list of fields.

I don't understand what you expect. Can you show what you get and what you expect?

**Comment by dargueta** [comment]
Gaaaah crap I was misinterpreting our logging output. Marshmallow is working as intended. Sorry!
