### ISSUE TITLE
Is there a way to detect duplicate attribute ?

### ISSUE THREAD

**Issue by SnakePy92** [marshmallow-code/marshmallow#774]
Let's take the example from the documentation: http://marshmallow.readthedocs.io/en/latest/quickstart.html

The duplicate name in the input is not detected:

```py
user_data = {
    'created_at': '2014-08-11T05:26:03.869245',
    'email': u'ken@yahoo.com',
    'name': u'Ken',
    'name': u'The Survivor'
}
```

Result is: 

```py
{'created_at': datetime.datetime(2014, 8, 11, 5, 26, 3, 869245),
 'email': 'ken@yahoo.com',
 'name': 'The Survivor'}
```

Even the "@validates_schema(pass_original=True)" does work. Is there a way to detect the duplicate entry ?

Thanks.

**Comment by deckar01** [comment]
In this example, the first name value is overwritten before it ever gets to marshmallow. Python dictionaries can't have duplicate keys. It appears the that `simplejson` also overwrites when parsing duplicate keys. `pass_original` is unrelated to this behavior.

I'm not sure this is a use case that python or json directly support.

See https://stackoverflow.com/a/23195243/1440667

**Comment by lafrech** [comment]
There are `MultiDict` classes that accept duplicate keys.

- http://werkzeug.pocoo.org/docs/0.14/datastructures/#werkzeug.datastructures.MultiDict
- http://multidict.readthedocs.io

**Comment by deckar01** [comment]
The only use case I could find for deserializing to a multidict was for request parameters. @SnakePy92 Is your data coming from a form/url encoded network request?

**Comment by SnakePy92** [comment]
Thanks a lot for your answers, so the problem is not in marshmallow.
My web service uses a database file of ~100000 lines in JSON format which is sometimes manualy edited for corrections. This is why i would like to find these duplicate keys.

**Comment by deckar01** [comment]
You should be able to detect multiple keys using `object_pairs_hook` parameter for `json.load()`.

https://pythonadventures.wordpress.com/2016/03/06/detect-duplicate-keys-in-a-json-file/

**Comment by SnakePy92** [comment]
Yes, problem solved. Thanks again !
