### ISSUE TITLE
Documentation error:  utils.get_value attempts to __getitem__ before getattr

### ISSUE THREAD

**Issue by bkuczenski** [marshmallow-code/marshmallow#776]
I had a problem with a very basic use case (see https://stackoverflow.com/questions/49889233) and it turns out the explanation was that `Field.get_value()` -> `utils.get_value()` tries `__getitem__` and only falls back to `getattr` in event of an error. 

The first section of the Quickstart reads: 

> Create a schema by defining a class with variables mapping attribute names to Field objects.

Strictly speaking, this is not true, since `__getitem__` keys are not attribute names. This should be clarified somewhat exhaustively in the docs, as any object that does not raise an error on an invalid `__getitem__` key will not be marshallable.

**Comment by sloria** [comment]
Thanks for reporting this @bkuczenski. We would certainly review a PR revising the docs to make it clearer.
