### ISSUE TITLE
Proposal: Add SchemaMeta.process_meta hook to SchemaMeta.__new__

### ISSUE THREAD

**Issue by justanr** [marshmallow-code/marshmallow#786]
I have a need in [justanr/marshmallow-annotations](https://github.com/justanr/marshmallow-annotations) to process the Schema's meta definition before gathering declared fields, somewhere in this code block:

https://github.com/marshmallow-code/marshmallow/blob/1781e9a18895aa9b473fb5587de3cf922416733e/marshmallow/schema.py#L94-L101

This line:

https://github.com/marshmallow-code/marshmallow/blob/1781e9a18895aa9b473fb5587de3cf922416733e/marshmallow/schema.py#L97

is *almost* what I need except it doesn't receive the schema class as part of it's arguments.

Right now I'm working around this by doing Meta related stuff in [`get_declared_fields` which is kind of gross](https://github.com/justanr/marshmallow-annotations/blob/a4e06f5d5acb714fab6584ef005d1a404e8c70bb/src/marshmallow_annotations/scheme.py#L22-L35):

```python
        meta = getattr(klass, "Meta", None)

        if not meta:  # pragma: no branch
            return fields

        target = getattr(meta, "target", None)

        if target is None:
            return fields

        # need to walk up parents to find if they have a custom converter
        converter_factory = getattr(meta, "converter", BaseConverter)

        # weeeee circular references!
        meta.converter = converter = converter_factory(klass)
```

This hook would also relieve the circular reference as the converter only needs to know about the scheme/meta instance to do traversals up to find options set in parents. Instead with a hook like:

```python
@classmethod
def process_meta(mcls, klass, this_meta=None):
    pass
```

Meta could be processed before hand and my `get_declared_fields` becomes much simpler.

Alternatively, we could pass the schema class into the options class (at the risk of breaking other custom implementations).

Something else I've briefly considered is along the lines of:

```python
class SomeSchema(Schema):
    @classmethod
    def OPTIONS_CLASS(cls, meta, ordered):
        return CustomOpts(meta, ordered, cls)
```

but that seems a bit TOO clever.

**Comment by sloria** [comment]
Seems like a low-risk change--few users should need to touch this. In your proposed code above, is `this_meta` the `Meta` class object, or something else?

**Comment by justanr** [comment]
It'd be the Meta on the class being processed. I've currently worked around this by using the classmethod OPTIONS_CLASS but that feels sloppy.

**Comment by justanr** [comment]
Gonna close this since I did manage to work around it. If there's further interest, I'm happy to follow through with a PR otherwise what I have is good enough for my needs.
