### ISSUE TITLE
Suggestion: Add option to end validation after first error

### ISSUE THREAD

**Issue by marovargovcik** [marshmallow-code/marshmallow#793]
Hi,

I am not aware of option to end validation after first error. If there is, i'm sorry for my inattention while reading docs. 

Take this example:
```python
from marshmallow import fields, post_load, validates_schema, Schema, ValidationError

class UserSchema(Schema):
    username = fields.String(required=True)
    password = fields.String(required=True)

    @post_load
    def create_user(self, data):
        return f"Welcome, {data['username']}!"

    @validates_schema
    def validate_schema(self, data):
        if data["password"] > 5:
            raise ValidationError("That password is too strong.")
        if data["username"] == "Frank":
            raise ValidationError("Frank, stop it!")


payload = {
    "username": "Frank",
    "password": None
}

message, error = UserSchema().load(payload)

print(message)
print(error)
```

Resulting in key error because code block in `@validates_schema` is getting executed even if there is an error and it's trying to get key that had been popped out of `data`.

There is of course simple workaround to use in this example code, using `dict.get(key)` instead of `dict[key]` but i think it should be somehow possible to stop validation after first error. 

My idea of using `@validates_schema` is validating if provided data is valid and can be stored in database. Of course it isn't valid if someone sent request with null fields so don't even bother to continue Marshmallow 😃.

If anyone knows about better solution in this use case, let me know! 
Thanks and have a nice day!

**Comment by deckar01** [comment]
Enabling `skip_on_field_errors` should avoid this issue.

> If skip_on_field_errors=True, this validation method will be skipped whenever validation errors have been detected when validating fields.
>
> _Changed in version 3.0.0b1: `skip_on_field_errors` defaults to **True**._

http://marshmallow.readthedocs.io/en/dev/api_reference.html#marshmallow.decorators.validates_schema

**Comment by deckar01** [comment]
I edited your example code to remove an inappropriate reference. Our code of conduct does not allow joking about publishing others’ private information, mocking people, or sexual topics.

http://marshmallow.readthedocs.io/en/dev/code_of_conduct.html
