### ISSUE TITLE
Inconsistent behavior of strict option for Integer type

### ISSUE THREAD

**Issue by amirma** [marshmallow-code/marshmallow#794]
What is the semantics of _strict_ property for an Integer field, or in general, for a field of any type? The context to this question is [this SO question](https://stackoverflow.com/questions/50142866/python-marshmallow-force-field-int-to-only-accept-int-and-not-strings/50148026#50148026). As shown in the answer, the behavior seems to be inconsistent. 
If this is the intended behavior perhps it's better to reflect the intent in the docs to prevent confusions.

**Comment by deckar01** [comment]
There has been previous discussion about the string to number deserialization behavior and strict.

- https://github.com/marshmallow-code/marshmallow/pull/755#issuecomment-377662237
- https://github.com/marshmallow-code/marshmallow/issues/727#issuecomment-378363721

The documentation is missing for that parameter. We should definitely fix that.

**Comment by amirma** [comment]
Thanks -- closing this issue as it's a duplicate.
