### ISSUE TITLE
[question] localized validation messages

### ISSUE THREAD

**Issue by glenfant** [marshmallow-code/marshmallow#795]
Hi, is there a plan to provide translatable validation messages (using gettext like toolchain) ?

I know I could use custom fields (subclassing standard marshmallow Fields) that provide my personal validation messages or templates or message templates but it's somehow painful and would break with a future release of Marshmallow.

Thanks whatever's your answer for this great piece of software.

**Comment by deckar01** [comment]
It looks like this request was met with hesitation in the past. See #419.

It seems reasonable to adopt a text framework, include English only in the core, then allow the community to publish translation plugins. On the other hand I am not familiar with maintaining this type of architecture or how it would integrate with other parts of the marshmallow ecosystem.

I will do some research and see if I can improve my knowledge on this subject a little.

**Comment by lafrech** [comment]
uMongo is a library built on top of marshmallow that yields translated messages.

http://umongo.readthedocs.io/en/latest/userguide.html#i18n

**Comment by glenfant** [comment]
FTW, I made this to provide validation error messages into French. You just need to change `marshmallow.fields.XYZ` against `marshmallow_fr.XYZ` fields.

https://gist.github.com/glenfant/3bf7501a77ebb8bf9aec054f2fa5cf3a

Any comment under this Gist are welcome.

**Comment by sloria** [comment]
There is discussion of allowing `error_messages` to include callables, which would make it easier to implement i18n on the user's side. See https://github.com/marshmallow-code/marshmallow/issues/334 . Let's continue discussion on that issue.
