### ISSUE TITLE
MongoEngine model instances always marshal as a list

### ISSUE THREAD

**Issue by mattupstate** [marshmallow-code/marshmallow#8]
The way that marshmallow checks to see if it should marshal a list is perhaps a bit error prone when dealing with object instances that implement the `__iter__` magic method. For example, MongonEngine document instances [implement this method](https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/base/document.py#L168-L169). So any time I try to serialize a MongoEngine document instance it always returns a list. The first thing that came to mind was a flag for the serializer constructor that would force a single instance. However, I'm wary of suggesting you should pollute that space with more args.

Another approach I just thought of is to make the `Serializer._marshal` property configurable by passing one to the constructor. Otherwise, use the default implementation.

**Comment by sloria** [comment]
Indeed, the marshaller will incorrectly treat a single object as a collection if its class implements `__iter__`. For this reason, I am working on getting rid of implicit collection handling. 

I think the best solution is to explicitly specify when you are serializing a collection. 

``` python
users = [User('Mick'), User('Keith')]
serialized = UserSerializer(users, many=True)
```

Nested fields will be treated the same way:

``` python
class PersonSerializer(Serializer):
    name = fields.String()
    relatives = fields.Nested(RelativeSerializer, many=True)
```

What do you think of this solution?

**Comment by sloria** [comment]
I've added the above behavior to the development version. I think that should fix the problem with MongoEngine documents, so I'm closing for now.

Thanks for reporting this. I welcome further feedback.

**Comment by mattupstate** [comment]
@sloria thanks! I'll try it out and see if it suits my needs.
