### ISSUE TITLE
How can I pick which fields to use for serialization on a case by case basis?

### ISSUE THREAD

**Issue by federicobozzini** [marshmallow-code/marshmallow#817]
Let's say that I have a case like the following:

```
class DriverSchema(ma.ModelSchema):

    class Meta:
        fields = ('id', 'name')


class CarSchema(ma.ModelSchema):
    drivers = fields.Nested(DriverSchema, many=True)

    class Meta:
        fields = ('id', 'plate', 'drivers')
```

But I would like to include the `drivers` property of `CarSchema` only on some specific serialization operations, is there an easy way to do that?

I saw similar issues like #374 and #585 but the solutions proposed look a bit complex and I'm not sure if that's the correct way to go. Isn't maybe there a simple way similar to the one used to exclude fields (#50)?

I need this to implement some REST API where the consumer can decide which fields to include, and this looks like a very common use case.

**Comment by lafrech** [comment]
What about `CarSchema(exclude=('drivers',))` when you don't need this field?

**Comment by federicobozzini** [comment]
That would be really costly to maintain, since if a new field is added to the Schema than all the Schema instantiations should be updated. Of course it would be possible to build on top of that a smart mechanism where some fields are required explicitly and the other ones are excluded, but I think it would be just easier if there was some native way to achieve the same result.

**Comment by deckar01** [comment]
> **only** (_tuple_|_list_) – Whitelist of fields to select when instantiating the Schema. If None, all fields are used. Nested fields can be represented with dot delimiters.

https://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.Schema

```py
# Filter on args like "plate" or nested args like "drivers.name".
schema = CarSchema(only=req.args.filter)
return schema.dumps(data)
```

**Comment by federicobozzini** [comment]
Thank you, this looks like a very good option.
