### ISSUE TITLE
SKIPPABLE_VALUES for Number fields

### ISSUE THREAD

**Issue by Ch00k** [marshmallow-code/marshmallow#83]
Is there a specific reason we don't set `SKIPPABLE_VALUES` for `Number` field type? I would set it to `(None, 0, 0.0)`. I saw #71 and understand the concern but if we include empty string in `SKIPPABLE_VALUES` for String we probably would also like to include zeroes for Number.

**Comment by sloria** [comment]
`0` is considered a non-empty input value from the client. Whereas `None` and the empty string are null values--in the common case--`0` should not be omitted in serialized output. If you want an Number field to be skipped when its value is 0, you must explicitly override `SKIPPABLE_VALUES`.

This is consistent with the reasoning behind #76.
