### ISSUE TITLE
marshmallow load returns UnmarshalResult

### ISSUE THREAD

**Issue by silentnights** [marshmallow-code/marshmallow#830]
I have a marshmallow schema which has an implementation for a post_load processor which return an object.

As per the docs when I try to load a dictionary into the schema and the dictionary is valid, I should get an object returned by the post_load.

But I am getting UnmarshalResult which has two fields data and error. The data field contain my object and error is empty.

This is different from what is documented, and also different from the code that is available in github. I am using the version from pypi.

The behavior is the same for 2.15.2 and 2.15.3

I looked at the code in pypi and it returns UnmarshalResult, now I am not sure if pypi has an older version or what?

**Comment by lafrech** [comment]
This changed in marshmallow 3. Are you referring to marshmallow 3 docs? The code in `dev` (default) branch is marshmallow 3.

**Comment by silentnights** [comment]
Thanks lafrech for the answer.

I have installed the pre-release from pypi and all works fine. You can close the issue, I don't know if i can do that myself.
