### ISSUE TITLE
IDE thinks the return of Schema.load is always a dict, but not true.

### ISSUE THREAD

**Issue by nackjicholson** [marshmallow-code/marshmallow#836]
The Schema.load method is annotated with a docstring which declares the `:rtype: dict`. When using `@post_load` this isn't necessarily true. Is there a way for `load` to statically know the type of object which is returned?

```python
MyObj = namedtuple('MyObj', ['foo'])

class MySchema(Schema):
    foo: fields.Str()

    @post_load
    def make_obj(self, data):
        return MyObj(**data)

schema = MySchema()

my_obj = schema.load({'foo': 'bar'})

# PyCharm always infers the type of my_obj as a dict, even though it is MyObj.
```

**Comment by sloria** [comment]
`:rtype: dict` is meant to document the default return type. Since a post-load method may return any type, there's no easy way to tell static analyzers precisely what `load` will return.

Closing, as I don't there's much we can do about this.
