### ISSUE TITLE
fields.String() & fields.Email() : not same behavior when empty string

### ISSUE THREAD

**Issue by bourdeau** [marshmallow-code/marshmallow#846]
Hello,

I don't know if this is the expected behavior but if I have:

```python
    # Doesn't raise a ValidationError if the string is empty
    client_email = fields.String(
        data_key='client_email',
        attribute='email_2',
        required=False
    )
    # Raise a ValidationError if the string is empty
    client_email = fields.Email(
        data_key='client_email',
        attribute='email_2',
        required=False
    )
```
I expected not to have a ValidationError if `client_email` is either None, empty or a valid email address when using fields.Email.

Am I missing something?

**Comment by lafrech** [comment]
`required=False` (which should be implicit as it is the default) means that you may omit the key in input data, not that the value can be `None` or empty string.

To accept a `None` value, you'd need to add `allow_none=True`.

And of course, an empty string is valid for a `String` field but not for an `Email` field.

There's no way you can accept an empty string for an `Email` field. If you have no data, then the key/value pair should be omitted in input data.

Well, you could hack the `Email` field to accept an empty string, but this is probably not the right thing to do.

**Comment by bourdeau** [comment]
Thanks for the clarifications @lafrech 

So I guess I will have to nonify all the empty email strings on `pre_load` and set `allow_none=True` for email fields.

I'm closing this ticket as it is not an issue.

Thanks again for your help.

**Comment by lafrech** [comment]
At this point you'd be better off removing those empty strings in the `pre_load`. You wouldn't require `allow_none`.

Ideally, the client wouldn't send empty string. I think there's been discussions already about removing empty strings, because some forms send empty fields as empty strings. I don't remember what came out of that.
