### ISSUE TITLE
Attribute which contains dot not working

### ISSUE THREAD

**Issue by mpushki** [marshmallow-code/marshmallow#850]
```
class UserSchema(Schema):
    name = fields.String()
    email_addr = fields.String(attribute="email")
    date_created = fields.DateTime(attribute="created_at")

user = User('Keith', email='keith@stones.com')
ser = UserSchema()
result = ser.dump(user)
pprint(result)
# {'name': 'Keith',
#  'email_addr': 'keith@stones.com',
#  'date_created': '2014-08-17T14:58:57.600623+00:00'}
```

But i have field with dot:
`
email_addr = fields.String(attribute="user.email")`

It does not work - can anyone have any idea how to get around this? There is no way to remove a point from the input file

**Comment by lafrech** [comment]
I suspect what you need in not `attribute` but `dump_to`/`load_from` (Marshmallow 2) or `data_key` (Marshmallow3).

**Comment by mpushki** [comment]
@lafrech according to API I needed attribute:
i have csv file with user.email field - i need attribute to get it right?

**Comment by lafrech** [comment]
No, `attribute` is the attribute of the corresponding Python object once deserialized.

`user.email` is the key in the serialized data.

**Comment by mpushki** [comment]
Anyway, same problem with data_key
So for my example:
i have: 
`{'user.email': 'keith@stones.com'}`
My schema:
```
class UserSchema(Schema):
    email = fields.String(attribute="user.email")
```
i need to get after schema:
`{'email': 'keith@stones.com'}`
Logs that I see in your instructions are similar to the attribute. OK. If this is not an attribute.
I try:
`email = fields.String(data_key="user.email")`
In any case, the field does not detect a field with a dot.
If you remove the dot - I like work of attribute. Is it possible to add a check or condition so that field with dot works?

**Comment by lafrech** [comment]
I'm sorry I must be misunderstanding because I can't reproduce.

```python
        class AliasingUserSerializer(Schema):
            name = fields.String(data_key='Name')
            username = fields.Email(data_key='User.Name')
        data = {
            'Name': 'Mick',
            'User.Name': 'foo@bar.com',
        }
        result = AliasingUserSerializer().load(data)
        print(result)
        # {'username': 'foo@bar.com', 'name': 'Mick'}
```

Can you please provide a full example?
