### ISSUE TITLE
Change default for `unknown` to `RAISE`

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#851]
As a follow up to https://github.com/marshmallow-code/marshmallow/issues/524#issuecomment-397165731 and #838 : the default for `unknown` should be changed to `RAISE`.

**Comment by sloria** [comment]
@lafrech Were you still planning to work on this?

**Comment by lafrech** [comment]
Yep. I needed https://github.com/marshmallow-code/marshmallow/pull/857 merged first.

Here's the PR for this issue: https://github.com/marshmallow-code/marshmallow/pull/872.
