### ISSUE TITLE
Make the error messages for "unknown fields" and "invalid data type" configurable

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#852]
As a follow-up to https://github.com/marshmallow-code/marshmallow/pull/838#issuecomment-399677937 : Make the error messages for passing unknown fields (currently `'Unknown field.'`) and invalid input type (currently `'Invalid input type.'`) configurable on a `Schema`.

**Comment by lafrech** [comment]
Same with `"Invalid input type."` (https://github.com/marshmallow-code/marshmallow/pull/857#issuecomment-401613877).

**Comment by sloria** [comment]
Good call. Renamed the issue.

**Comment by Dunstrom** [comment]
Is this issue still relevant? If so I might be able to fix it.

**Comment by sloria** [comment]
@Dunstrom Yes, this is still up for grabs!

**Comment by Dunstrom** [comment]
Thanks for the info @sloria, I will start working on this.

**Comment by Dunstrom** [comment]
@sloria, I would love it if you had a look at my PR when you get the time!
