### ISSUE TITLE
"load_only" fields

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#87]
Possible feature: add a `Field` parameter that would make the field active for validation/deserialization but not appear in serialization output.

This came up in a discussion here: https://github.com/marshmallow-code/flask-marshmallow/issues/5#issuecomment-65887841 (though we used the term "write-only", which is a misnomer).

Related to #61 . 

EDIT: Fix URL to comment.

**Comment by sloria** [comment]
Added in https://github.com/marshmallow-code/marshmallow/pull/131

**Comment by Lacrymology** [comment]
is there a way to have dump_only fields throw an error if they're passed on to `load`?

**Comment by lafrech** [comment]
@Lacrymology, this could be a sub-use case of the `check_unknown_fields` example: http://marshmallow.readthedocs.io/en/latest/extending.html#validating-original-input-data

It seems the authors don't see this as a feature that should be in the core, available through a parameter, but leave this to user code (https://github.com/marshmallow-code/marshmallow/issues/524).
