### ISSUE TITLE
Allow multiple formats for DateTime deserialization

### ISSUE THREAD

**Issue by charlax** [marshmallow-code/marshmallow#874]
It would be nice for marshmallow to allow multiple deserialization formats for `DateTime` out of the box, because this seems to be a pretty common thing. By default `deserialization_formats` could be set to `['iso', 'rfc']` because those two formats are fairly unambiguous.

I did something like this (error handling removed for brevity):

```python
from marshmallow.fields import DateTime as MDateTime


class DateTime(MDateTime):

    deserialization_formats = ['iso', 'rfc']

    def _deserialize(self, value, attr, data):
        for format in self.deserialization_formats:
            func = self.DATEFORMAT_DESERIALIZATION_FUNCS[format]
            try:
                return func(value)
            except (TypeError, AttributeError, ValueError):
                continue

        raise self.fail('invalid')

```

**Comment by lafrech** [comment]
I'd rather not engage into this in marshmallow core.

To do this in client code, I'd create a new util function that uses existing rfc and iso utils to try both methods (what you did, but in the util function, not the field deserialization method), and then I'd map this new util function to a custom format that I'd add to a custom `DateTimeField` (or even monkeypatch `DateTimeField.DESERIALIZATION_FUNCS` to get nicer imports in my models...).

**Comment by lafrech** [comment]
Closing this.

Anyone disagrees, please comment / reopen.

**Comment by mkmoisen** [comment]
@lafrech 

I would like to support multiple formats as well, for what it's worth.

I think the following would be consistent with the API:
```
class Schema:
    foo = fields.DateTime(format=['%Y-%m-%d %H:%M:%S', '%Y-%m-%d'])
```
