### ISSUE TITLE
recent commit breaks use of exclude with marshmallow-sqlalchemy

### ISSUE THREAD

**Issue by yaheath** [marshmallow-code/marshmallow#877]
Commit 76e8c91e3decfa4f01ee3c48d71995d2e0a55a27 breaks our use of `exclude` in the Meta of a sqlalchemy-backed model schema.

For example:

```python
class CustomerSchema(BaseSchema):
    class Meta(BaseSchema.Meta):
        model = Customer
        exclude = ('orders',)
```

Where `Customer` is a sqlalchemy model and `orders` is a relation from another table. Putting the exclude in the Meta prevents marshmallow-sqlalchemy from creating the Relation field for `orders` into CustomerSchema. However, with the above commit which adds a check on the excludes, it'll now throw an exception at instantiation because 'orders' doesn't exist in the schema (because it was excluded!)

How should this be resolved? I could instead use `fields=()` in the Meta and explicitly list out the fields I want instead of using `exclude`, but that's more maintenance overhead (we have to remember to update the fields list if a column is added to the model)

**Comment by deckar01** [comment]
`marshmallow-sqlalchemy` should be declaring fields from the model. If fields are missing it sounds like a `marshmallow-sqlalchemy` issue.

**Comment by yaheath** [comment]
Yes, marshmallow-sqlalchemy declares fields from the model. That is not the problem. The problem is when I want it to **not** add a field from the model. So I put `exclude` in the Meta to prevent the field from being added. Works fine in marshmallow 2.x, but 3.0 breaks because of the change in 76e8c91e3decfa4f01ee3c48d71995d2e0a55a27

**Comment by lafrech** [comment]
And this worked because Marshmallow used to silently ignore when being asked to exclude a field that marshmallow-sqlalchemy didn't create in the first place.

Sounds like it is marshmallow-sqlalchemy's responsability do prevent this situation. Maybe this means using another keyword than `exclude` in there, or at least avoid passing `exclude` to marshmallow.
