### ISSUE TITLE
Remove "null" nested when deserialize

### ISSUE THREAD

**Issue by upmauro** [marshmallow-code/marshmallow#878]
Hello, first off all, thanks for your great project.

It's possible remove all null when deserialize a object?

Example, instead of a have this result:

`{"customer": null, "id: "1"}` 

Remove null and result just:

`{"id": "1"}`

**Comment by lafrech** [comment]
I think you mean when serializing, right? Otherwise, it would be `None`, not `null`.

See this thread: https://github.com/marshmallow-code/marshmallow/issues/229.
