### ISSUE TITLE
Validators are shared between Schema subclasses

### ISSUE THREAD

**Issue by amikholap** [marshmallow-code/marshmallow#88]
The code:

``` python
from marshmallow import Schema

class AppBaseSchema(Schema):
    pass

class Schema1(AppBaseSchema):
    pass

class Schema2(AppBaseSchema):
    pass

@AppBaseSchema.validator
def validate_appbaseschema(schema, input_data):
    print 'validating AppBaseSchema'
    return True

@Schema1.validator
def validate_schema1(schema, input_data):
    print 'validating Schema1'
    return True

@Schema2.validator
def validate_schema2(schema, input_data):
    print 'validating Schema2'
    return True


>>> s1 = Schema1()
>>> s1.load({})
validating AppBaseSchema
validating Schema1
validating Schema2
UnmarshalResult(data={}, errors={})
```

Name mangling doesn't occur for __validators__ attribute so all classes share the same dict.
Fixed this locally using a simple metaclass but this behavior seems undesired.
Maybe __validators should be used instead?

Local fix:

``` python
import copy

from marshmallow import Schema
from marshmallow.schema import SchemaMeta


class BaseSchemaMeta(SchemaMeta):
    def __init__(cls, name, bases, d):
        super(BaseSchemaMeta, cls).__init__(name, bases, d)
        cls.__validators__ = copy.copy(cls.__validators__)


class AppBaseSchema(Schema):
    __metaclass__ = BaseSchemaMeta
```

**Comment by sloria** [comment]
Thanks for reporting. Yes, you are correct that abstract classes should not share the validators of concrete classes. 

Marking this as a bug since the current behavior is not desired. I will add your fix to `SchemaMeta`.

**Comment by dgilland** [comment]
Is thread-safety a concern here? I don't believe `copy.copy` is thread-safe.

**Comment by amikholap** [comment]
> Is thread-safety a concern here? I don't believe copy.copy is thread-safe.

Metaclass code executes only once during class initialization. How can it be affected by threading?

**Comment by sloria** [comment]
As @amikholap pointed out, I don't think thread-safety should be much of a concern during class declaration. The edge cases for which this could be an issue seem too unlikely to justify the added complexity of handling it. I think the simple solution of doing 

``` python
# __validators__ is a list of functions,
# so we can just use slicing to copy
cls.__validators__ = cls.__validators__[:]
```

will suffice.

However, a simple _and_ safe solution would be to use tuples to store __validators__ (and __preprocessors__, etc.). These collections aren't expected to change much during applicaton runtime, so this shouldn't be very expensive. Furthermore, it was just pointed out to me that Python does some smart things with caching small tuples. Source: https://stackoverflow.com/questions/14135542/how-is-tuple-implemented-in-cpython via @jmcarp .

**Comment by sloria** [comment]
As a follow-up: While storing the validators as tuples is feasible, it would constrain the user to always use a tuple when defining `__validators__`, et al. on the class (they could not use a list). That would be a breaking change, so it would have to added in 2.0 if we decide on that.

For now, we'll go with the list-copy solution.
