### ISSUE TITLE
Issues with Capitalization

### ISSUE THREAD

**Issue by beneshed** [marshmallow-code/marshmallow#883]
Hi!

I'm trying to serialize a schema to have the fields upper case (dealing with Amazon API stuff)

The output should be so
```
{
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation"
      ],
      "Resource": "arn:aws:s3:::*"
}
```

The schema 
```
class StatementSchema(Schema):
    sid = fields.Str(attribute='Sid', data_key='Sid', default=str(uuid4()))
    effect = fields.Str(attribute='Effect', data_key='Effect', valdate=validate.OneOf(('Allow', 'Deny')))
    action = fields.Str(attribute='Action', data_key='Action', required=False, allow_none=True, many=True)
    not_action = fields.Str(attribute='NotAction', data_key='NotAction', required=False, allow_none=True, many=True)
    resource = fields.Str(attribute='Resource', data_key='Resource', required=False, allow_none=True, many=True)
    not_resource = fields.Str(attribute='NotResource', data_key='NotResource', required=False, allow_none=True,
                              many=True)
    condition = fields.Nested(fields.Dict(keys=fields.Str(), values=fields.Str()), attribute='Condition',
                              data_key='Condition')
```

I tried using a pre_dump hook to capitalize everythign
```
@pre_dump
def capitalize(self, data):
    new_data = {}
    for key, value in data.items():
        new_data[key.capitalize()] = value
    return new_data
```

But after dumping is
```
{"sid": "526a26e5-2517-4fcd-bafa-c2540904552f", "resource": "arn:aws:s3:::*", "effect": "Allow", "action": "['s3:ListAllMyBuckets', 's3:GetBucketLocation']"}
```

How can I force the keys to be uppercase?

**Comment by lafrech** [comment]
`data_key` should be enough.

Remove `attribute`, and remove the `@pre_dump` method.

Also you have a typo: valdate -> validate.

**Comment by beneshed** [comment]
@lafrech don't i need attribute to be able to both serialize and deserialize with uppercase?

I removed and it has the same effect

**Comment by beneshed** [comment]
I updated the field names themselves to be uppercase and it works fine....

**Comment by lafrech** [comment]
This should be enough:

    effect = fields.Str(data_key='Effect')

Assuming you're using Marshmallow 3 (still beta).

With Marshmallow 2, you'd write

    effect = fields.Str(load_from='Effect', dump_to='Effect')

Attribute specifies the key used in the deserialized form.

**Comment by beneshed** [comment]
@lafrech I was using the wrong version, thank you
