### ISSUE TITLE
Logical Or Type Field [Question]

### ISSUE THREAD

**Issue by beneshed** [marshmallow-code/marshmallow#884]
Hi,

I want a field that can either `fields.Str()` or `fields.List(fields.Str())`. I don't want to have to use https://github.com/Bachmann1234/marshmallow-polyfield because it seems to be more Schema / nested option oriented. Can anyone point me in the direction of being able to do the above?

Thanks!

**Comment by deckar01** [comment]
You could declare the field as a `List`, then add a schema hook that transforms the string to a list.

https://stackoverflow.com/questions/45088704/specify-a-one-or-many-field-using-marshmallow

If you want more complex or reusable behavior, you will probably want to make a custom field.

https://marshmallow.readthedocs.io/en/3.0/custom_fields.html

**Comment by beneshed** [comment]
@deckar01 awesome thanks!
