### ISSUE TITLE
ISO8601 time string with a Z comes out with +00:00 after load and then dump

### ISSUE THREAD

**Issue by nackjicholson** [marshmallow-code/marshmallow#889]
When using the `fields.DateTime` and a value `"2018-07-25T00:00:00Z"`. Loading and then dumping that data should result in the exact same value for that field. But it doesn't. What is dumped back out is `"2018-07-25T00:00:00+00:00"`. This is not technically a different time, but I think I should be able to serialize/deserialize data and not have it be altered from the voyage.

datetime strings are really difficult with python. My sympathies.

I'm going to try to make a subclass of field that does only what I want for tz-aware iso8601 strings and isn't as broad as `fields.DateTime`. I'll post it back for reference.

**Comment by nackjicholson** [comment]
Here, I used one of the only libraries in python that I could find that actually handles iso8601 datetime strings correctly and according to the actual ISO 8601 standard. 

https://pypi.org/project/isodate/

```python
import isodate as iso
from marshmallow import fields, Schema


class ISOTzAwareDatetimeField(fields.Field):
    def __init__(self, dtformat=iso.DT_EXT_COMPLETE, **kwargs):
        super(ISOTzAwareDatetimeField, self).__init__(**kwargs)
        self.dtformat = dtformat

    def _serialize(self, value, attr, obj):
        if value is None:
            return None
        return iso.datetime_isoformat(value, self.dtformat)

    def _deserialize(self, value, attr, data):
        if value is None:
            return None
        return iso.parse_datetime(value)


import unittest
from datetime import datetime

class TestISOTzAwareDatetimeField(unittest.TestCase):
    """
    python -m unittest -v test.test_fields.TestISOTzAwareDatetimeField
    """
    def setUp(self):
        # YYYY-MM-DD[T]HH:MM:SS[+-]HHMM
        custom_fmt = iso.DATE_EXT_COMPLETE + 'T' + iso.TIME_EXT_COMPLETE + iso.TZ_BAS

        class TestDatetimeSchema(Schema):
            foo = ISOTzAwareDatetimeField(required=True)
            bar = ISOTzAwareDatetimeField(required=True)
            baz = ISOTzAwareDatetimeField(custom_fmt, required=True)

        self.test_schema = TestDatetimeSchema

    def test_serialize(self):
        schema = self.test_schema()
        actual = schema.dump({
            'foo': datetime(2018, 7, 25, tzinfo=iso.UTC),
            'bar': datetime(2018, 7, 25, tzinfo=iso.FixedOffset(-7, 0, 'America/Los_Angeles')),
            'baz': datetime(2018, 7, 25, tzinfo=iso.FixedOffset(-7, 0, 'America/Los_Angeles'))
        })
        expected = {'foo': '2018-07-25T00:00:00Z',
                    'bar': '2018-07-25T00:00:00-07:00',
                    'baz': '2018-07-25T00:00:00-0700'}
        self.assertEqual(actual, expected)

    def test_deserialize(self):
        schema = self.test_schema()
        actual = schema.load({'foo': '2018-07-25T00:00:00Z',
                              'bar': '2018-07-25T00:00:00-07:00',
                              'baz': '2018-07-25T00:00:00-0700'})
        expected = {
            'foo': datetime(2018, 7, 25, tzinfo=iso.UTC),
            'bar': datetime(2018, 7, 25, tzinfo=iso.FixedOffset(-7, 0, 'America/Los_Angeles')),
            'baz': datetime(2018, 7, 25, tzinfo=iso.FixedOffset(-7, 0, 'America/Los_Angeles'))
        }
        self.assertEqual(actual, expected)
```

Still doesn't really address the issue though because still if +0000 comes in, you still get Z on the way out and vice-versa. Basically I can get around that by just always using Z for UTC, which I do.

EDIT: This allows some customization of the format as can be seen by the `baz` field.

**Comment by deckar01** [comment]
> Loading and then dumping that data should result in the exact same value for that field. But it doesn't.

It is the same value with different encodings. `Z` and `+00:00` are equivalent.

```py
import dateutil

dt = dateutil.parser.parse('2018-07-25T00:00:00Z')
dt.tzinfo()
# tzutc()
dt.isoformat()
# 2018-07-25T00:00:00+00:00
```

`dateutil`'s `parser` is passing the timezone correctly and `datetime.isoformat()` is allowed to represent `Z` as `+00:00`. If you are interfacing with a system that doesn't accept `+00:00` as a timezone, it probably isn't compliant. Otherwise it is a personal preference that can be achieved with a custom format.

**Comment by nackjicholson** [comment]
@deckar01 Okay, thanks for the response. I realize the `Z` and `+00:00` are equivalent. But in my system I'd like to keep the integrity of the data through the marshalling process, and our convention is to use `Z` for the UTC zone offset. My class above `ISOTzAwareDatetimeField` fits better with our convention, so I'll use it.

If this isn't an issue others have or one that marshmallow should bother itself with it, this issue could be closed.

**Comment by lafrech** [comment]
Maybe an option could be added to specify a format _à la_ [strftime](https://docs.python.org/3.7/library/datetime.html#datetime.date.strftime).

If not, then a custom `Field` can be used as shown above.

**Comment by vgavro** [comment]
Maybe this can be achieved with adding `format_options` parameter to `fieids.DateTime`.
This can also replace `LocalDateTime` field with `DateTime(format_options=dict(localtime=True))`, for now `LocalDateTime` is used only for formatting (serialize, not deserialize) and because of that name is *confusing*, plus if we implement "timestamp" format (as proposed in https://github.com/marshmallow-code/marshmallow/issues/612#issuecomment-429947895 ) "localtime" option will not have sense there, but other format_options (`as_int` for timestamp, for example) may have sense. Also api will be more extendable for future formats and options, imho.

**Comment by sloria** [comment]
Given the current design, there isn't a good way outside of passing `format` to `DateTime` that ensures that the input and output format are exactly the same. If you need more complex logic that `format`, a custom field is the way to go.
