### ISSUE TITLE
Odd Behavior for `Function` field

### ISSUE THREAD

**Issue by cancan101** [marshmallow-code/marshmallow#890]
```python
class TestSchema(Schema):
    test = fields.Function(deserialize=lambda x: 1)
    test2 = fields.Constant(11)
    
TestSchema().load({})
```
yields `UnmarshalResult(data={'test2': 11}, errors={})`, ie omitting `test`. The fix seems to be:
```python
class TestSchema2(Schema):
    test = fields.Function(deserialize=lambda x: 1, missing='asdf')
    test2 = fields.Constant(11)
```
yielding: `UnmarshalResult(data={'test': 1, 'test2': 11}, errors={})`.

**Comment by deckar01** [comment]
What version of marshmallow are you using? `pip show marshmallow`

**Comment by cancan101** [comment]
```
Name: marshmallow
Version: 2.15.3
Summary: A lightweight library for converting complex datatypes to and from native Python datatypes.
Home-page: https://github.com/marshmallow-code/marshmallow
Author: Steven Loria
Author-email: sloria1@gmail.com
License: MIT
```

**Comment by deckar01** [comment]
```py
class TestSchema(Schema):
    test = fields.Field()

TestSchema().load({})
# UnmarshalResult(data={}, errors={})
```

marshmallow 2.x fields are optional by default. Omitting the key during load ignores the field.

https://marshmallow.readthedocs.io/en/2.x-line/api_reference.html#marshmallow.fields.Field

**Comment by cancan101** [comment]
So  is there a clean solution here? It's a little odd the difference between Constant and Function

**Comment by deckar01** [comment]
```py
class TestSchema(Schema):
    test = fields.Function(deserialize=lambda x: 1, missing=lambda: 1)

TestSchema().load({})
# UnmarshalResult(data={'test': 1}, errors={})
TestSchema().load({'test': 'junk'})
# UnmarshalResult(data={'test': 1}, errors={})
```

`Function` might not be the best tool for the job though. It is really meant to transform an input value. If you don't need a value to deserialize, `Constant` is the right tool, but it does not currently support a callable value argument. The cleanest solution is probably to define a custom field.

https://marshmallow.readthedocs.io/en/2.x-line/custom_fields.html#custom-fields

```py
from marshmallow import Schema, fields

class DynamicConstant(fields.Constant):
    def _serialize(self, value, attr, obj):
        return self.constant()
    
    def _deserialize(self, value, attr, obj):
        return self.constant()

class TestSchema(Schema):
    test = DynamicConstant(lambda: 1)

TestSchema().load({})
# UnmarshalResult(data={'test': 1}, errors={})
TestSchema().load({'test': 'junk'})
# UnmarshalResult(data={'test': 1}, errors={})
```

**Comment by cancan101** [comment]
Yea the `DynamicConstant` looks more or less like what I would write. That being said, I was somewhat confused by the docs as to what Function should be used for.

**Comment by deckar01** [comment]
You could use it to invert a boolean value when mapping a field like `enabled` to `disabled`. Sometimes a custom field is overkill when the just need to transform the input value a little.

```py
disabled = field.Function(deserialize=lambda x: not x, load_from='enabled')
```
