### ISSUE TITLE
List of lists does not pass validation

### ISSUE THREAD

**Issue by hazardsy** [marshmallow-code/marshmallow#897]
I am trying to use a list of list of floats in my code, but I can't seem to pass the marshmallow validation, no matter what schema I try.
The following code looks to me like it should work, but somehow doesn't, is it an issue on my part ?
```
class FAQPostInput(Schema):
    location = fields.List(fields.List(fields.Float))

    class Meta:
        strict = True
```
Input : 
```
data = {
    "location": [
        [0.2, 0.3, 0.4]
    ]
}
```

Thanks for your answers !

**Comment by deckar01** [comment]
When I tested this by running `FAQPostInput().dump(data)`, it produced `{'location': [[0.2, 0.3, 0.4]]}` using both marshmallow 2.15.3 and and 3.0.0b12.

**Comment by lafrech** [comment]
I guess he's using 2.x since he uses `strict`.

Indeed, this passes with both 2.x and 3 beta:

```python
from marshmallow import Schema, fields

class FAQPostInput(Schema):
    location = fields.List(fields.List(fields.Float))

data = {
    "location": [
        [0.2, 0.3, 0.4]
    ]
}

print(FAQPostInput().dump(data))
print(FAQPostInput().load(data))
```

2.x:

```python
MarshalResult(data={'location': [[0.2, 0.3, 0.4]]}, errors={})
UnmarshalResult(data={'location': [[0.2, 0.3, 0.4]]}, errors={})
```

3b:

```python
{'location': [[0.2, 0.3, 0.4]]}
{'location': [[0.2, 0.3, 0.4]]}
```

**Comment by hazardsy** [comment]
Actually the issue came from the way I constructed my HTTP request and not from marshmallow itself.
Thanks for your answers !
