### ISSUE TITLE
Allow depth > 1 when nesting a serializer within itself

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#9]

**Comment by stephenemslie** [comment]
+1

This would be helpful when serializing models that are using the [adjacency list pattern](https://github.com/zzzeek/sqlalchemy/blob/master/examples/adjacency_list/adjacency_list.py). What are the concerns that led to the `self.exclude += (self.name, )` safeguard in [fields.py](https://github.com/sloria/marshmallow/blob/master/marshmallow/fields.py#L298)?

**Comment by stephenemslie** [comment]
It seems to be possible to work around this issue by referencing the serializer using it's full dotted name. e.g.

```
class UserSerializer(Serializer):
    name = fields.String()
    email = fields.Email()
    friends = fields.Nested('foo.bar.UserSerializer', many=True)
```

**Comment by sloria** [comment]
> What are the concerns that led to the self.exclude += (self.name, ) safeguard in fields.py?

The safeguard was added to prevent infinite recursion when nesting `'self'`. 

``` python
from marshmallow import Schema, fields, pprint

class User:
    def __init__(self, name, employer=None):
        self.name = name
        self.employer = employer

user = User('Foo')
employer = User('Bar')
user.employer = user2

class UserSchema(Schema):
    name = fields.String()
    employer = fields.Nested('self')

schema = UserSchema(strict=True)
# Without the safeguard, this would result in infinite recursion
result = schema.dump(user2)
result.errors
```

Now that you've brought this up, though, this behavior is inconsistent with the way two-way nesting works. In the case of two-way nesting, the user is responsible for preventing infinite recursion by explicitly excluding the nested field. 

I'm thinking that "self-nesting" should behave the same way.

``` python
class UserSchema(Schema):
    name = fields.String()
    # Explicitly exclude nested field
    employer = fields.Nested('self', exclude=('employer', ))
```

Also, as you point out, the safeguard is unnecessary when dealing with adjacency lists.

I think we have a good case for removing it. Thanks for your feedback on this.
