### ISSUE TITLE
Can a Nested schema serialize values from its parent?

### ISSUE THREAD

**Issue by bjmc** [marshmallow-code/marshmallow#900]
My apologies if this is covered in the docs somewhere and I missed it. Is it possible to have a Nested schema that refers to properties of the parent model object?

Assume you have a model that looks something like this:
```python

class UserModel():
    name = Column(String)
    created = Column(Datetime)
    updated = Column(Datetime)
```
And you want to produce serialized output like:
```python
{'meta': {'created': '2018-08-02T10:53:41',
          'updated': '2018-08-02T10:54:04'},
 'name': 'Some Name'}
```

If you define marshmallow schemas like:

```python

from marshmallow import Schema, fields

class MetaSchema(Schema):
    created = fields.DateTime(dump_only=True)
    updated = fields.DateTime(dump_only=True)

class UserSchema(Schema):
     name = fields.String()
     meta = fields.Nested(MetaSchema())
```

But there's no "meta" attribute on the ORM object, I just want to pull out specific properties. Is there a way to tell the Nested schema that it should look for values on the parent?

A guess a more general way to phrase this question would be: How can Marshmallow handle situations where the relationships between model objects is different that the relationships in the serialized output? Should I just be coercing it into the necessary shape with `@post_dump` and `@pre_load` modifiers?

**Comment by asthasr** [comment]
I found a solution to this that allowed me to avoid using custom fields (I'm using apispec and want to minimize that where possible). I added a hook:

```python
class SelfReferentialSchema(Schema):
    @pre_dump
    def add_self_reference(self, data):
        setattr(data, "_marshmallow_self_reference", data)
```

Then you can refer to this on the `fields.Nested` call:

```python
class UserSchema(SelfReferentialSchema):
    name = fields.String()
    meta = fields.Nested(MetaSchema(), attribute="_marshmallow_self_reference")
```

Unfortunately, there's no clean way that I can see to remove this; `@post_dump` doesn't receive the original data.

**Comment by sloria** [comment]
Let's continue discussion of this in #940
