### ISSUE TITLE
None with many=True sets valid_data to {} instead of []

### ISSUE THREAD

**Issue by tuukkamustonen** [marshmallow-code/marshmallow#907]
With `3.0.0.b13` this now passes:

```python
class Sch(Schema):
    foo = fields.Str()

with pytest.raises(ValidationError) as e:
    Sch(many=True).load(None)
assert e.value.messages == {'_schema': ['Invalid input type.']}
assert e.value.valid_data == {}
```

This sets `valid_data` to `{}` rather than `[]` as usual with `many=True`. I understand that we're not really interested about `valid_data` here, but isn't this kinda confusing because we're expecting a list (for `many=True`) and valid data is suddenly dictionary instead (invalid)?

**Comment by sloria** [comment]
Good catch. I agree that `valid_data` should be a list in that case. PRs welcome.
