### ISSUE TITLE
RAISE should be default for Nested()

### ISSUE THREAD

**Issue by tuukkamustonen** [marshmallow-code/marshmallow#908]
Isn't it a bit weird that `Schema` defaults to `RAISE` but `Nested` defaults to `EXCLUDE`?

It's probably not what one expects (at least I didn't). How about changing the default? Or what might be the reasoning?

**Comment by sloria** [comment]
Good catch @tuukkamustonen . This may have been an oversight. @lafrech Was the default intentionally left as EXCLUDE for Nested in https://github.com/marshmallow-code/marshmallow/pull/872 ?

**Comment by lafrech** [comment]
Oops, nope. I guess I missed that one. Sorry about that.
