### ISSUE TITLE
Option to return error codes instead of messages

### ISSUE THREAD

**Issue by ryantaylor** [marshmallow-code/marshmallow#915]
Hey guys, I've searched around everywhere and couldn't find an answer to my question. Basically, I'm looking for the ability to return error codes instead of messages when a validation or load on a schema fails. The application I'm using marshmallow in is a microservice and I want to offload error localization to the application calling the microservice API. Is this currently supported?

Thanks a lot!

**Comment by deckar01** [comment]
It is not, but someone has hacked together custom error messages in the past. See #795 for previous discussion about localized error message support.

**Comment by ryantaylor** [comment]
Thanks!
