### ISSUE TITLE
Excluding fields during deserialization of object

### ISSUE THREAD

**Issue by milost** [marshmallow-code/marshmallow#916]
The tuple notation seems to cause problems excluding fields during the serialization process. That documentation states that the following should work:

``` python
summary_schema = UserSchema(exclude=('name'))
summary_schema.dump(user)
# {"email": "monty@python.org", ...}
```

Unfortunately, specifying a tuple does not work if it only contains one element (in this case `name`). What works is to simply pass a list instead of a tuple, like this:

``` python
summary_schema = UserSchema(exclude=['name'])
summary_schema.dump(user)
# {"email": "monty@python.org", ...}
```
I think the documentation should be adapted to avoid confusion.

**Comment by deckar01** [comment]
`('name')` -> `('name',)`

https://stackoverflow.com/questions/12876177/how-to-create-a-tuple-with-only-one-element
