### ISSUE TITLE
bug in Nested field processing None value

### ISSUE THREAD

**Issue by zioniony** [marshmallow-code/marshmallow#920]
##test.py
```Python
from marshmallow import Schema, fields, validates


class ArtistSchema(Schema):
    name = fields.Str(required=True)

    @validates('name')
    def check_name(self, value):
        pass

class AlbumSchema(Schema):
    artists = fields.Nested(ArtistSchema, many=True)

s = AlbumSchema()
s.loads('{"artists": [null]}')
```

this will cause TypeError:
```
~/.virtualenvs/py3/lib/python3.6/site-packages/marshmallow/schema.py in _invoke_field_validators(self, unmarshal, data, many)
    880                 for idx, item in enumerate(data):
    881                     try:
--> 882                         value = item[field_obj.attribute or field_name]
    883                     except KeyError:
    884                         pass

TypeError: 'NoneType' object is not subscriptable

```

would it be better to check item first or catch more exception types?

**Comment by deckar01** [comment]
It doesn't look like it was intended to raise an error, so it should probably probe the data instead.

```py
data_key = field_obj.attribute or field_name
if data and data_key in data:
    ...
```

**Comment by deckar01** [comment]
It looks like there are 2 other places in this file that use the `try except KeyError pass else` pattern that would break in a similar way.

**Comment by zioniony** [comment]
> It doesn't look like it was intended to raise an error, so it should probably probe the data instead.

perhaps it's better to return validation error than raising a TypeError.

**Comment by deckar01** [comment]
I believe this logic is for handling inferred fields. The keys are present in `declared_fields`, but are not in `fields`. #810 can probably remove these checks since it creates a field instance for inferred fields.

/cc @taion

**Comment by taion** [comment]
I think this is an outright bug there. There should be a check there like https://github.com/marshmallow-code/marshmallow/blob/e0bfdc9ba423292630a30d03f94d45dabc8122d9/marshmallow/marshalling.py#L235-L237

**Comment by deckar01** [comment]
I agree the underlying issue is that the container needs to be validated sooner, but I was looping you in, because I noticed that this specific check that errored might not be necessary after #810. I did not see these modified in your diff. Probably should have made a comment on the PR instead.

**Comment by zioniony** [comment]
[#810](https://github.com/marshmallow-code/marshmallow/pull/810) fixed the issue.
I'll upgrade marshmallow. 
thank you for your replies.
I'll close this post.
