### ISSUE TITLE
Meta option unknown is no inherited on inherited Schema

### ISSUE THREAD

**Issue by YievCkim** [marshmallow-code/marshmallow#921]
Hello,

I am on v3.0.0b13
I have super class where I defined `unknow = EXCLUDE`. But the inherited schema doesn't inherit from this property. I think it's a bug because meta options like `ordered` are inherited.

```python
from marshmallow import Schema, EXCLUDE

class SuperSchema(Schema):
  class Meta:
    ordered = True
    unknown = EXCLUDE

class InheritedSchema(SuperSchema):
  class Meta:
    fields = ('a', 'b')
```

An instance of InheritedSchema give an OrderedDict as expected but raise an error when an unknown field is given.

**Comment by YievCkim** [comment]
update:

This behaviour occurs only when dup_only option is specified in inheirited class' Meta options :

```python
from marshmallow import Schema, EXCLUDE


class SuperSchema(Schema):
    class Meta:
        ordered = True
        unknown = EXCLUDE


class InheritedSchema(SuperSchema):
    class Meta:
        fields = ('a', 'b')
        dump_only = ('a', 'b')


class InheritedSchema2(SuperSchema):
    class Meta:
        fields = ('a', 'b')
        dump_only = ('a', 'b')
        unknown = EXCLUDE
```

gives:
```pycon
>>> s=InheritedSchema()
>>> s.load({"a": 1, "b": 3})
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/env/lib/python3.5/site-packages/marshmallow/schema.py", line 530, in load
    postprocess=True,
  File "/home/user/env/lib/python3.5/site-packages/marshmallow/schema.py", line 683, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'b': ['Unknown field.'], 'a': ['Unknown field.']}
>>> s=InheritedSchema2()
>>> s.load({"a": 1, "b": 3})
OrderedDict()
```

**Comment by YievCkim** [comment]
A workaround is to declare fields explicitly :
```python
class InheritedSchema3(SuperSchema):
    a = fields.String(dump_only=True)
    b = fields.String(dump_only=True)
```

```pycon
>>> s=InheritedSchema3()
>>> s.load({"a": 1, "b": 3})
OrderedDict()
>>> s.load({"a": 1})
OrderedDict()
>>> s.load({})
OrderedDict()
```

**Comment by deckar01** [comment]
I'm not very familiar with how implicit field creation is implemented, and am having trouble finding it when grocking through the code. I suspect implicit fields never get a field instance and we just try/pass around the validation when the field key is not found. It might be better to make a proper field class that encapsulates this behavior.

**Comment by deckar01** [comment]
It looks like #810 is adding an `Inferred` field type which could fix this.

**Comment by YievCkim** [comment]
Thx for the link to #810. I will look this. I am not very familiar with `fields` attribute me too. So the workaround works for me.

**Comment by lafrech** [comment]
#810 is merged in `dev` (not released yet). Is this fixed?

**Comment by YievCkim** [comment]
Thx I will look this ASAP.

**Comment by lafrech** [comment]
@MikHulk is this fixed? May we close this?

**Comment by sloria** [comment]
Closing for now. Please comment if this is still an issue.

**Comment by YievCkim** [comment]
Sorry, I didn't have time to test on dev branch. I found a workaround on my project. 

Very sorry about that.
