### ISSUE TITLE
Ability to disable implicit field creation

### ISSUE THREAD

**Issue by cancan101** [marshmallow-code/marshmallow#923]
Add an option to disable implicit field creation. I have been burned on this when using ModelSchema where a field changes name such that there is now a field with the old name an an auto generated field with the new name leading two duplicate fields.

**Comment by deckar01** [comment]
Can you provide an example?

**Comment by cancan101** [comment]
I shouldn't say duplicate. I should just say a Schema which is silently using the wrong name.

Originally my model is:
```python
class Widget(Model):
    ...
    other_id = ...
```
and then I have:
```python
class WidgetSchema(ModelSchema):
   class Meta:
     model = Widget
     fields = ('other_id')
```
and then `other_id` gets renamed in the Model. The Schema code doesn't get updated. Now there is an implicit `other_id` which is not using the nicely autogenerated field that `ModelSchema` would otherwise make.

**Comment by lafrech** [comment]
IIUC, this is a marshmallow-sqlalchemy issue.

But since it could affect any other marshmallow-whatever-database lib, and since the fix could be in marshmallow anyway, it makes sense to discuss it here.

**Comment by sloria** [comment]
Let's move forward with https://github.com/marshmallow-code/marshmallow/issues/1356 .
