### ISSUE TITLE
Nested Schemas Referring to Dictionary Keys

### ISSUE THREAD

**Issue by cdiggins** [marshmallow-code/marshmallow#924]
If I have a field that contains an ID which is a key to a value that is stored in a dictionary elsewhere, can I declare that in such a way that the whole value object is deserialized in place of the id. 

```py
    class UserSchema(Schema):
        name = fields.String()
        email = fields.Email()
        friends = fields.Relationship('self', path="AddressBook.contacts", many=True)
    
    class AddressBookSchema(Schema):
        contacts = nested.Dict(keys=fields.String(), values=fields.Nested(UserSchema))
    
    # ... create ``user`` ...
    serialized_data = AddressBookSchema().dump(user)
    pprint(serialized_data)
    # "contacts": {
    #   "Steve": {
    #     "name": "Steve",
    #     "email": "steve@example.com",
    #     "friends": ["Mike"]
    #   },
    #   "Mike": {
    #     "name": "Mike",
    #     "email": "mike@example.com",
    #     "friends": []
    # }
    
    
    deserialized_data = UserSchema().load(result)
    pprint(deserialized_data)
    # "contacts": {
    #   "Steve": {
    #     "name": "Steve",
    #     "email": "steve@example.com",
    #     "friends": [ {"name": "Mike", "email": "mike@example.com"]
    #   },
    #   "Mike": {
    #     "name": "Mike",
    #     "email": "mike@example.com",
    #     "friends": []
    # }
```

There is a[ StackOverflow question ](https://stackoverflow.com/questions/51992551/automatic-dictionary-key-resolution-with-nested-schemas-using-marshmallow) if you want to get some bounty for answering this there as well.

**Comment by lafrech** [comment]
The SO answer using `post_load` looks good to me.

Should we close this?

**Comment by carlosvega** [comment]
Sorry, is there any way to do this thanks to the resolution of #483 ?

I have the following structure with key being the foreign key of each children element, and the value being the serialised version of each children.

```
"reactions": {
   "1" : {
           "name" : "reaction 1",
           "id" : 1,
           "compound" : "compound A"
    },
    "2" : {
           "name" : "reaction 2",
           "id" : 2,
           "compound" : "compound C"
    }
}
```

Thank you very much. I can't manage to create this serialization/deserialization with Marshmallow.

**Comment by lafrech** [comment]
I don't think #483 (validation of keys/values in Dict field) helps with this.

AFAIU your question, pre/post_load/dump decorators would be suited for this.
