### ISSUE TITLE
question: how to decide and nest a schema based on a value

### ISSUE THREAD

**Issue by playgroundctl** [marshmallow-code/marshmallow#942]
Hi,

I was wondering if there is a way to nest a schema based on a field's value.
For example, let's assume that there is a number of `Unit` schemas that logically fall under the `Blueprint` schema. 
Let `UnitInterfacesSchema` be one of the schemas that can be nested in the `BlueprintSchema`.

```
class UnitInterfacesSchema(marshmallow.Schema):
    pass

class BlueprintSchema(marshmallow.Schema):
    unit = fields.Str()
```
    
The desired behaviour would be:
WHEN `unit` is equal to `interfaces`
THEN 

1. override the `unit` field like this `unit = fields.Nested(InterfacesSchema)` instead of ` unit = fields.Str()`
2. create an implicit field like this `_unit = fields.Nested(InterfacesSchema)`
3. something else ?

Would you be so kind to advise if that is possible ? If yes, how ?

**Comment by lafrech** [comment]
I don't get it.

If your data contains `{'unit': 'interfaces'}`, let's say the `unit` `fields.Str()` field is replaced with `fields.Nested(InterfacesSchema)`. What input data will this nested schema deserialize? Not the `'interfaces'` string, I suppose.

Do you have an example of input and expected output?

If you're dealing with polymorphism issues, try to search for "polymorphism" in the search box, there's been discussions about this already, it might help.

**Comment by playgroundctl** [comment]
Thank you for enlighten me :) https://github.com/marshmallow-code/marshmallow/issues/42 seems to describe it better than how I did. Not sure what is the exact status of the PR though, as it is not described in the documentation.

Alternatively, I could build some logic based on the input data. Now, that I am thinking of it will be more straightforward
