### ISSUE TITLE
RFC: extend allow_nan parameter to all number fields

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow#944]
`Decimal` field has an `allow_nan` parameter (`False` by default):

> If `True`, `NaN`, `Infinity` and `-Infinity` are allowed, even though they are illegal according to the JSON specification.

Any objection to extend it to all numbers?

Currently, `Int` will reject those as they are not integers, but they pass `Float` which just pawned me.

Should we add the same validation in `Float`? Move it up to `Number`?

Even if it is useless for `Int`, I'd be tempted to extend it to `Number`.

- Those are special values with a special meaning so a different error message makes sense.
- Any `Number` subclass would inherit it -> less duplication.

This is a breaking change as the default would be `False` so `Float` would need to be explicitly passed `allow_none=True`.

**Comment by lafrech** [comment]
On second thought, from a practical perspective, modifying only `Float` is easier...

It is easier to check after the input is cast to the right type and `int(value)` will fail on nan/infinity.

This check is done after the value is deserialized, so `Int` would fail before that anyway.

For now, I've monkey-patched `Float` in my app:

```py
import math

import marshmallow as ma



class Float(ma.fields.Float):

    default_error_messages = {
        'special': 'Special numeric values are not permitted.',
    }

    # override Number
    def _format_num(self, value):
        if value is None:
            return None
        num = super()._format_num(value)
        if math.isnan(num) or num == math.inf or num == -math.inf:
            self.fail('special')
        return num


ma.fields.Float = Float
```

Thoughts anyone?

**Comment by lafrech** [comment]
BTW, I don't see the point of returning the value in the `TypeError` [here](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/fields.py#L675), considering we don't return values in error messages and it is swallowed in `validated` when returning the `invalid` message.

```py
        if value is True or value is False:
            raise TypeError(
                'value must be a Number, not a boolean.  value is '
                '{}'.format(value),
)
```

**Comment by lafrech** [comment]
> On second thought, from a practical perspective, modifying only Float is easier...

And an `Int` with `allow_nan=True` wouldn't make sense.

Definitely better to do that on a per-field basis.

Shall I shoot a PR for `Float`?

**Comment by rooterkyberian** [comment]
seems like only benefit of having `allow_nan=True` is to allow easy path for regaining backwards compatiblity, so I would agree there is not reason to add it to `Int`

**Comment by lafrech** [comment]
Implementation proposed in #945.

Breaking because default is `False` and because the signature of the field's `__init__` changes.
