### ISSUE TITLE
Root reference is broken for nested/container fields when using schema inheritance 

### ISSUE THREAD

**Issue by chrisbune** [marshmallow-code/marshmallow#956]
I use schema inheritance a lot to reuse shared parts of schemas. Additionally I have some custom fields with validation methods which use references to the field's root schema. When these custom fields are used in nested schemas or inside lists, then the same field instance is used in different schema classes and thus the root reference is "broken":

```python
>>> import marshmallow
>>> marshmallow.__version__
'3.0.0b13'
>>> from marshmallow import fields
>>> from marshmallow.schema import Schema
>>> class A(Schema):
...     f1 = fields.List(fields.Integer())
... 
>>> class B(A):
...     pass
... 
>>> a = A()
>>> b = B()
>>> a_f1 = a.declared_fields['f1']
>>> b_f1 = b.declared_fields['f1']
>>> a_f1.root == a
True
>>> b_f1.root == b
True
>>> a_f1.container.root == a
False
>>> a_f1.container.root == b
True
```
So the problem is that the container root of field `f1` of schema instance `a` is schema instance `b`. In fact `a_f1.container` and `b_f1.container` point to the same object.

Is this a problem of how I use marshmallow or is this a bug?

I find the possibility to reference a field's root schema very valuable and the root property looks like it can be used like that. However, I think the problem here is that nested (or container) fields are not unique instances when used in multiple classes.

**Comment by chrisbune** [comment]
For now I use this custom list class, which appears to fix the problem:

```python
class List(_List):

    def _add_to_schema(self, field_name, schema):
        # make a shallow copy of the container to avoid binding the same
        # container instance to multiple parent schemas:
        self.container = copy.copy(self.container)
        super()._add_to_schema(field_name, schema)
```

**Comment by deckar01** [comment]
I was able to reproduce the issue. I suspect the `Dict` field has the same issue. `root` is also used internally to resolve the options for nested fields, so that is probably broken when inheriting with different meta options.

The schema does a deep copy of the static schema class's `_declared_fields` in the constructor, which is why `a_f1 is not b_f1`. `List` and `Dict` should do the same for their container instance since they are going to mutate it's attributes.

**Comment by deckar01** [comment]
`self.container = cls_or_instance` -> `self.container = copy.deepcopy(cls_or_instance)` should do the trick.

If you are interested in submitting a PR it would be greatly appreciated. Otherwise I will try to work on a fix when I find time.

**Comment by chrisbune** [comment]
Thanks for checking and confirming the issue. I'm not sure when I'll get to make a PR. Have it on my list, though. So whoever comes first ...

**Comment by chrisbune** [comment]
Thanks for the fix!
