### ISSUE TITLE
None string while dumping does not return errors

### ISSUE THREAD

**Issue by dmytrostriletskyi** [marshmallow-code/marshmallow#971]
Hello, try to work with schema's [fields](https://marshmallow.readthedocs.io/en/3.0/api_reference.html#module-marshmallow.fields
). The point is I have some string that may be `None`, maybe not. 

I have the following schema:

```python
class SomeSchema(Schema):
    some_string = fields.String(required=True)
    # or I also tried: some_string = fields.String(required=True, allow_none=False)
```

I do [dumping](https://marshmallow.readthedocs.io/en/3.0/quickstart.html#serializing-objects-dumping):

```python
arguments, errors = SomeSchema().dump({
    'some_string': None,
})
```

I get:

```python
{'some_string': None} {}
```

I expect:

```python
{} {'some_string': 'Value should be not empty.'}
```

What have I tried wrong?

**Comment by deckar01** [comment]
> **required** – Raise a ValidationError if the field value is not supplied during deserialization.

https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.fields.Field

`dump()` does not validate required fields, `load()` does. If you are not sure that your data source complies with your schema, it needs to be loaded first.

**Comment by dmytrostriletskyi** [comment]
@deckar01, `required` is not a point of the question, the point is why `None` value of the a `some_string` passed `dump` and goes to `arguments` instead of `errors`?

Load has helped me:

```python
{} {'identifier': ['Field may not be null.']}
```

@deckar01, cleared! Thanks you a lot! :)
