### ISSUE TITLE
Serializing dict of nested schema at the top level

### ISSUE THREAD

**Issue by jlzhao27** [marshmallow-code/marshmallow#972]
Hi all,

I am using marshmallow `3.0.0b16`. I am trying to write a REST endpoint that wants to return a json dictionary of objects. The python signature looks something like:

```
class Foo():
  def __init__(a: str, b: int):
    pass

def myEndpoint() -> Dict[str, Foo]:
  return { "a": Foo("a", 1), "b": Foo("b", 2) }

```

The `FooSchema` is pretty trivial to write, however when I want to write the schema for the dict, I found I have to wrap it with another top level object in order to get to dump correctly.
```
class FooDictSchema(Schema):
  foo_dict = fields.Dict(key=field.String(), value=field.Nested(FooSchema))
```
This works for dumping but injects an unnecessary `"foo_dict"` key at the top level of the json object, when I tried doing `schema = FooSchema(many=true)` and dumping the dict, i get a bunch of empty values.

Is there an easy way to dump a dictionary directly where it uses a nested type? This is very similar to the following issue: https://github.com/marshmallow-code/marshmallow/issues/483 but my usecase requires the nested dict to be at the top level.

**Comment by lafrech** [comment]
If the list of keys is known, you could write

```py
class FooDictSchema(Schema):
    a = field.Nested(FooSchema))
    b = field.Nested(FooSchema))
```

**Comment by deckar01** [comment]
> I have been experimenting with treating schema as an dict/object field internally. This allows all fields (including non-collection types) to be used like a schema. It also eliminates the need for the many schema constructor argument in favor of wrapping the schema in a list field.
>
> https://deckar01.gitlab.io/marsha/guide.html#deserializing-data

https://github.com/marshmallow-code/marshmallow/issues/316#issuecomment-407849303

What if `Field` had public marshalling methods?

```py
foo_dict_schema = fields.Dict(values=FooSchema)
foo_dict_schema.load(request.data)
```

**Comment by jlzhao27** [comment]
@lafrech the key is dynamic so they are not known ahead of time.

@deckar01 ya that would be idea, I actually tried to use the raw `Schema()` object to serialize the dict but it didn't work. I think making `many=True` work for `Dicts` would work for me or make`fields.Dict` implement `Schema` and let me use them for serialization/deserialization.

**Comment by Narmical** [comment]
I am having a similar problem, but with a self nested schema:
children = fields.Dict(required=False, keys=fields.String(), values=fields.Nested('self'))

when i try to use that filed a get an error that there is no load method of dict

**Comment by fenchu** [comment]
I have lots of [responder](https://github.com/kennethreitz/responder) restapis I like to use swagger on, but they do not pass marshmallowing dict of dicts where key name is based on response. responder has built in support for swagger via marshmallow. I like to use it as simple as possible and not add my own have to maintain code.

**Comment by sloria** [comment]
I think https://github.com/marshmallow-code/marshmallow/issues/1312 would meet this use case. The proposal there is to provide an easy way to generate schemas at runtime, so you could do:

```python
dynamic_data = {"a": 1, "b": 2}
FooDictSchema = Schema.from_dict({key: fields.Nested(FooSchema) for key in dynamic_data})
```

What do you think?

**Comment by sloria** [comment]
Closing for now, as a think the recently-added `from_dict` should meet this use case.

**Comment by fenchu** [comment]
Yes this works, thanks, but please update the docs with examples. I have tons of rest apis whose load dynamic content like active services, probing services, status etc. We do not have any problem marshalling the same content with jackson in java.

**Comment by sloria** [comment]
`from_dict` is documented in the Quickstart: https://marshmallow.readthedocs.io/en/latest/quickstart.html#creating-schemas-from-dictionaries

I also wrote up a quick blog post: https://stevenloria.com/dynamic-schemas-in-marshmallow/

**Comment by lauwers** [comment]
I don't think this addresses one of the earlier requirements, which was for a dictionary with unknown keys (issue #120): 

https://github.com/marshmallow-code/marshmallow/issues/120

Was there ever any progress made on supporting that use case? I continue to use my own NamedObjectMap field (which i show in #120) but I would much rather use something that is officially maintained.

**Comment by fenchu** [comment]
Use the mypy typing module instead.

**Comment by Spothedog1** [comment]
@lauwers Could you post an example using the code you wrote in #120? Like how am I supposed to use that class when I have a variable key name?

**Comment by lauwers** [comment]
Hi Ron. I’ll try to send something later today.

Chris

Sent from my iPhone

On Jul 19, 2020, at 9:18 AM, Ron Basumallik <notifications@github.com> wrote:

﻿

@lauwers<https://github.com/lauwers> Could you post an example using the code you wrote in #120<https://github.com/marshmallow-code/marshmallow/issues/120>? Like how am I supposed to use that class when I have a variable key name?

**Comment by lauwers** [comment]
Hi Ron, I’m attaching a small example using a Course Catalog, where the keys are course numbers (which could be arbitrary strings). Please let me know if you have any questions.

Thanks,

Chris

**Comment by Spothedog1** [comment]
@lauwers Thanks for replying so quickly, I don't think the attachment came through. Regardless I have figured out a solution for my use case, please feel free to post the example anyway for any one who may visit this thread in the future.

**Comment by lauwers** [comment]
[named_object_map_example.zip](https://github.com/marshmallow-code/marshmallow/files/4944905/named_object_map_example.zip)

**Comment by lauwers** [comment]
I just posted the example separately.

**Comment by vit-zikmund** [comment]
Hi @sloria, sorry to necromance on this closed issue, but isn't the `from_dict` a rather resource heavy approach?
I know it solves the problem, but if I understand it well, it creates a disposable schema with N fields for N keys in the dictionary, right? Seems more like a workaround than a solution.

I understand working directly with a `dict` might not fit in the whole marshmallow concept of `Schema`s being objects, but I think one could pretty easily use the `serialize`/`deserialize` interface of the field directly. I've developed a little example how this could work:
```python
from dataclasses import dataclass
from marshmallow.fields import Dict, Nested
from marshmallow_dataclass import add_schema


@add_schema
@dataclass(frozen=True)
class Record:
    item_str: str
    item_float: float


dict_field = Dict(values=Nested(Record.Schema))

data = {'a': Record('a', 1.0), 'b': Record('b', 2.0), 'c': Record('c', 3.0)}
print(data)
serialized_data = dict_field.serialize('n/a', data, accessor=lambda obj, _attr, _default: obj)
print(serialized_data)
data_back = dict_field.deserialize(serialized_data)
print(data_back)
```
The output is as expected:
```
{'a': Record(item_str='a', item_float=1.0), 'b': Record(item_str='b', item_float=2.0), 'c': Record(item_str='c', item_float=3.0)}
{'a': {'item_str': 'a', 'item_float': 1.0}, 'b': {'item_str': 'b', 'item_float': 2.0}, 'c': {'item_str': 'c', 'item_float': 3.0}}
{'a': Record(item_str='a', item_float=1.0), 'b': Record(item_str='b', item_float=2.0), 'c': Record(item_str='c', item_float=3.0)}
```
The `accessor` for `serialize` is a little hacky, but one could wrap that to a `dump`/`load` method just for the `Dict` field. Maybe :)
