### ISSUE TITLE
INTERNAL SERVER ERROR/TypeError: tuple indices must be integers, not str

### ISSUE THREAD

**Issue by ilovetogetspamed** [marshmallow-code/marshmallow#974]
I'm trying to run your example at [flask_example.py](https://marshmallow.readthedocs.io/en/3.0/examples.html#quotes-api-flask-sqlalchemy) and get the 'TypeError: tuple indices must be integers, not str' message when trying to follow the example.  e.g.,
`http POST :5000/quotes/ author="Tim Peters" content="Beautiful is better than ugly."`

**--Output (brief)--**

`  File "/tmp/marsmallow/flask-sqlalchmey-example.py", line 116, in new_quote
    first, last = data['author']['first'], data['author']['last']
TypeError: tuple indices must be integers, not str`

tried with Python 2.7.15 and Python 3.7.0
Flask            1.0.2    
Flask-SQLAlchemy 2.3.2
marshmallow      2.15.6
SQLAlchemy       1.2.12

**Comment by lafrech** [comment]
You're using marshmallow 2.x. Please refer to 2.x docs: https://marshmallow.readthedocs.io/en/2.x-line/examples.html

**Comment by ilovetogetspamed** [comment]
Sorry, my bad!
