### ISSUE TITLE
Ability to dump bypassing validation.

### ISSUE THREAD

**Issue by AndreiPashkin** [marshmallow-code/marshmallow#977]
Would the project's authors consider adding capability of serializing data without validation? Would a PR with such change be accepted?

Example use case:  I changed validation in my code but the data in my DB remained the same. But the DB is a trusted source and I don't want to change the old data, so it is reasonable to avoid validating data from DB at all.

**Comment by lafrech** [comment]
Validation only happens at load (deserialization) already.

**Comment by AndreiPashkin** [comment]
@lafrech, doesn't seem so:
https://github.com/marshmallow-code/marshmallow/blob/54e1605604aaf647ee4b03340284b348341eff62/marshmallow/schema.py#L481

**Comment by lafrech** [comment]
AFAIU, the code catches `ValidationError` if raised in dump or pre/post processors, but there is no validation invoked in dump method in the standard fields.

An error may still occur if a field is passed a data that does not comply to its type. This may trigger a `ValidationError`. But validators such as range, max length and such are not invoked.

Do you have an example of validator triggering an error when dumping?

**Comment by AndreiPashkin** [comment]
@lafrech, that is actually correct, I used the old 2.X version for testing.

**Comment by lafrech** [comment]
Good.

What I wrote should also apply to 2.x, except maybe for `Email` and `Url` fields that used to validate on dump, which was changed in v3.

**Comment by AndreiPashkin** [comment]
@lafrech, I used `Email` in my test.

**Comment by lafrech** [comment]
If you're starting a dev, it makes sense to use marshmallow 3.

If you want to stick to 2.x, subclassing `Email` and `Url` should be enough AFAICT.

**Comment by AndreiPashkin** [comment]
@lafrech, thx for the tip, I think I'm going to switch to 3.
