### ISSUE TITLE
Processing nested fields before loading schema data

### ISSUE THREAD

**Issue by kpagcha** [marshmallow-code/marshmallow#978]
Say I have this:

```
class Food(Schema):
    name = fields.Str()

class Menu(Schema):
    items = fields.Nested(Food, data_key=lambda m: get_food_items(m), many=True)
```

Where `get_food_items` is a function returning the food items for that menu because `menu.items` does not exist. But then I want to process the items somehow before they are loaded in the schema data. But how can I even access them? Where is the object that is to be dumped stored in the schema instance?

I thought the way to do this would be using the `pre_dump` operator but apparently not, because you can only access the object passed to the `dump` function. But how can I access the `items`? Where is that?

**Comment by deckar01** [comment]
> **data_key** (str) – The name of the key to get the value from when deserializing.

https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.fields.Field

I think you might need to use the `Function` field.

> A field that takes the value returned by a function.

https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.fields.Function

Can you provide an example of what the data looks like before loading, and what you would like it to look like after dumping?

**Comment by kpagcha** [comment]
I did consider using `Field` or `Method` but it is a bad idea because the whole point of using nested schemas is lost.

My actual data is this:

```
class Competition(models.Model):
	name = models.CharField()
	# ...

class Game(models.Model):
	competition = models.ForeignKey('Season')
	player1 = models.ForeignKey('Player')
	player2 = models.ForeignKey('Player')
	court = models.ForeignKey('Court', null=True)
	start = models.DateTimeField(null=True)
	end = models.DateTimeField(null=True)
	# ...

class GameSchema(Schema):
	# using just id for simplicity in the example, but it would have other fields (Str, Nested...)
	id = fields.Int()

class CompetitionSchema(Schema):
	name = fields.Str()
	games = fields.Nested(GameSchema, many=True)
```

`Competition` and `Game` are Django models. I want to serialize games in a competition (among other data). I want to be able to process the games loaded in the schema, for example, filter them based on a condition. And I want to do this in the `Schema` class, not in the actual `Competition`, for coupling and maintainability.

---

From https://github.com/marshmallow-code/marshmallow/issues/979#issuecomment-427035814

The scenario is this: as you can notice, the Competition class has no games attribute. They are instead accessed this way: competition.game_set.all(). What I need is a way to tell the schema to look for the value of the field in the place I explicitly point at, be it competition.game_set.all() or anything else containing Game objects matching the GameSchema. I want to tell the Schema class "hey, use THIS value I am giving you to populate your fields instead of looking for games yourself".

**Comment by deckar01** [comment]
Your DB model should have a way to declare a relationship so that `games` is populated on a `Competition` instance before you try to load it with marshmallow. Normally you don't `load` data that comes from the DB, because your model has already deserialized it, you just dump it.

**Comment by kpagcha** [comment]
As I said, I don't want the model to have anything to do with serialization. Absolutely no modifications should be introduced in the "data" classes (the models here).

> Normally you don't load data that comes from the DB, because your model has already deserialized it, you just dump it.

I am not sure what you mean here. When I said "games loaded in the schema" I am not talking about `load`. Sorry if it was confusing, I am having a hard time choosing the right terms. When I said "load in the schema" I meant the process of taking the dict/object you pass you `schema.dump` and assign them to the declared fiels. I mean, like, the actual serialization process.

**Comment by deckar01** [comment]
Thank you for clarifying. I think you were on the right track with the `pre_dump` decorator. You should be able to add data to the object just before dumping.

> Register a method to invoke before serializing an object. The method receives the object to be serialized and returns the processed object.

https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.decorators.pre_dump

> But how can I access the items? Where is that?

You should be able to initialize the `games` attribute in the dump hook.

```py
from marshmallow import Schema, fields, pre_dump

class Test(Schema):
    foo = fields.List(fields.Str())

    @pre_dump
    def load_foo(self, obj):
        obj['foo'] = []
        obj['foo'].append('test 1')
        obj['foo'].append('test 2')
        obj['foo'].append('test 3')
        return obj

Test().dump({})
# MarshalResult(data={'foo': ['test 1', 'test 2', 'test 3']}, errors={})
```

**Comment by kpagcha** [comment]
Thank you for answering! But sadly this is not helping either. First of all, that `obj` is the exact same object than the one you pass to the `dump` method, so a) I can't modify it in my case because it is an instance, not a dictionary and b) even if I could modify it, it presents the exact same problem about messing with the data class/instance we are trying to avoid to begin with.

Second of all, this would mean doing all the work for the serializer. Remember I was using `fields.Nested`. What exactly would I be supposed to initialize in my case? Would the `GameSchema` still work? In any case, this second point doesn't make much sense for the reason I detail in the first point: what you suggested just cannot be done.

**Comment by deckar01** [comment]
I'm fairly confident marshmallow is providing all the tools you need here. If you don't wan't to modify the original model, copy it first. If you need to create a new attribute use `setattr`. If you want to dump a nested schema, use `Nested`.

**Comment by kpagcha** [comment]
So the answer then is that I am stuck with preparing the data I pass to the serializer? I am pretty sure this is literally one of the core purposes of serializers, but oh well...

**Comment by deckar01** [comment]
It looks like you are using Django in those examples. If so, you are probably running into the issue that Django doesn't support the OneToMany relationship you are trying to express. I would recommend using model methods to encapsulate logic that involves querying this relationship and use the `@property` decorator to make it easy to use with marshmallow's `Nested` field.

https://docs.djangoproject.com/en/2.1/topics/db/models/#model-methods

**Comment by kpagcha** [comment]
Yeah no, that's not really my issue. As I said multiple times, I don't see why I would have to modify the model at all. The serializer should have the means to format and prepare the data.

**Comment by deckar01** [comment]
What about using the schema's `load` method and using a callable for the `missing` option to the nested field? You would need to load the model then dump it.

**Comment by deckar01** [comment]
@kpagcha Did you get this working?

**Comment by kpagcha** [comment]
Well I had to create intermediary classes to prepare/format the data to adapt exactly how the schemas want it...

**Comment by deckar01** [comment]
That sounds unusual. If you feel the need to refactor it into the schema I would recommend trying the load/missing strategy I mentioned in https://github.com/marshmallow-code/marshmallow/issues/978#issuecomment-427913324.

**Comment by kpagcha** [comment]
Not sure how I am supposed to be able to prepare the data like I want to with just using the `missing` option. I didn't quite get that strategy you mentioned.
