### ISSUE TITLE
How to properly run the tests?

### ISSUE THREAD

**Issue by svenstaro** [marshmallow-code/marshmallow#99]
Running tox locally for my python version yields 18 errors as compared to running tox on travis. What is different running tox locally as compared to travis that I would get errors here? How do I run the tests locally?

**Comment by sloria** [comment]
@svenstaro Do you have each of the interpreters installed locally? Also, what errors are you seeing?

**Comment by svenstaro** [comment]
Running

$ tox --skip-missing-interpreters &> /tmp/log

gives me this: https://gist.github.com/ca7bb1b6a8c339052e27

**Comment by svenstaro** [comment]
It seems like it's pulling in older versions of marshmallow which are obviously not compatible. I wonder why it does that since obviously we want to be testing the local version of marshmallow.

**Comment by svenstaro** [comment]
Ah, my problem is that marshmallow does not expect the virtualenv to be in the same dir as the git repo. This kind of sucks for me, because I always put my env there, as in marshmallow/env. Would you mind if I fixed marshmallow to disregard the popular "env" name for the virtualenv inside the git root?

**Comment by svenstaro** [comment]
I made a pr to fix the specific issues that I experienced here.
