### ISSUE TITLE
RFC: Respect schema prefix on load

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow#991]
I just realized schema prefix is only used when dumping.

Shouldn't it be used also when loading for consistency?

**Comment by deckar01** [comment]
> Optional prefix that will be prepended to all the serialized field names.

https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.Schema

It makes sense to me to apply it during load, but I'm not familiar with the use case for this feature.

**Comment by lafrech** [comment]
On second thought, the existence of the feature is questionable. It would be easy to achieve in a `post_dump` method, as it is not even recursive. The symmetric operation can be achieved in a `pre_load` method.

In fact, it is typically the kind of feature you (@deckar01) object to precisely because it adds to the maintenance burden while it would be easy to do on user side.

Here's the commit adding it: https://github.com/marshmallow-code/marshmallow/commit/78a237f932c3780589a50dd21c541727a3ef8c87.

**Comment by sloria** [comment]
Yes, it's a very old feature, and I don't even recall the use case for which it was added. I wouldn't be opposed to removing it.

**Comment by lafrech** [comment]
Alright. I just sent a PR to remove the feature.

The maintenance burden is relatively low, but the added value is low as well, considering the `@post_dump` method is trivial.
