### ISSUE TITLE
Accessing partial within validates_schema

### ISSUE THREAD

**Issue by cancan101** [marshmallow-code/marshmallow#994]
It does not look like there is a way for a function decorated with `validates_schema` to know if the schema is `load`ing with `partial=True`. This information is important in determining for example if certain validations should be skipped (ie if they involve combinations of fields that are not available on PATCHes).

**Comment by lafrech** [comment]
It makes sense and it looks like a simple change to make.

Just pass `partial` when calling validator from `Schema._do_load`.

Would you like to submit a PR?

This is a breaking change as it changes the validators signatures. Maybe in the documentation examples we could add `**kwargs` to make adding further kwargs less breaking...

**Comment by cancan101** [comment]
Given that this will be a breaking change to the API, does it make sense to take it as an opportunity to cleanup `validates_schema` by dropping `pass_original` (and always passing the original)?

**Comment by lafrech** [comment]
I like that.

If we decide the schema validator should expect `**kwargs` and ignore unused kwargs, we're free to always pass original data.

**Comment by cancan101** [comment]
also the docs say (bolding mine):
>If pass_many=True, the raw data (which may be a collection) **and the value for many is passed.**

however it does not look like `many` is being passed: https://github.com/marshmallow-code/marshmallow/blob/e2c0d527964250521b85fc52c58b368f0ff63cc9/marshmallow/marshalling.py#L165-L168
